### ISSUE TITLE
What's the relation between handler parameters and request details?

### ISSUE THREAD

**Issue by alfonso-eusebio** [actix/actix-web#1000]
Hi,

I've been looking for information on the mapping or relationship between the parameters passed to the handler and the details/information available in the request (data, query parameters, request body, etc.).
In the docs and examples I can see different types of parameters used in the handlers (`web::Data`, `web::Path`, `HttpRequest`, etc.). However, I haven't found any details as to which parameters are passed to the handler, in which order and where they come from.

Doing some tests, I can set application data several times for a route with different data types; and the order of the calls to .data() don't seem to affect the correct mapping to `web:Data` parameters in the handler. It only starts to do "funny" things when I pass the same data type (e.g. &str) more than once.

I apologise if this should be pretty obvious, but to me it's still a bit of magic. I tried to browse the code to see what was going on, but without much success.

Any help or pointers on this would be really appreciated.

Regards,
Alfonso

**Comment by fafhrd91** [comment]
Check FromRequest and Factory traits

**Comment by alfonso-eusebio** [comment]
Hi Nikolay,

I think I kind of get it now, but I must admit that all this combination of data, extractors, extensions, etc., it's still a bit fuzzy for me.
I'll be happy to help out with documenting all this (to the extent that I understand it) if you think that would help the project.

Regards,
Alfonso

**Comment by fafhrd91** [comment]
sure, docs is always priority!

**Comment by fafhrd91** [comment]
closing for now. if you'd like open pr with docs
