### ISSUE TITLE
will be provide a  http or http2 or json   RPC module?

### ISSUE THREAD

**Issue by zhuxiujia** [actix/actix-web#1001]
will be provide a  http/http2,json  RPC module?
like golang, Standard Library provide  httprpc,jsonrpc,tcprpc

**Comment by zhuxiujia** [comment]
some microservice framework  use requires RPC  module，so need  actix-web framework to support

**Comment by fafhrd91** [comment]
This is outside of the project concerns. This is good task for external crate

**Comment by zhuxiujia** [comment]
> This is outside of the project concerns. This is good task for external crate

but i find actix-grpc Archived........

**Comment by fafhrd91** [comment]
actix-grpc is way out of context, it is effectively dead
