### ISSUE TITLE
Support for DPDK for TCP and QUIC/HTTP3

### ISSUE THREAD

**Issue by jobs-git** [actix/actix-web#1002]
QUIC/HTTP3 protocol does not come free, according to [Google research](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46403.pdf), it incurs 2x hardware usage than TCP/TLS and they recommended kernel by pass alleviate this problem.

Some implementations of dpdk in rust
https://github.com/flier/rust-dpdk
https://crates.io/crates/rust-dpdk

However, I dont know if these are QUIC-ready, so that should be resolved as well

**Comment by fafhrd91** [comment]
This is outside os project scope.

**Comment by fafhrd91** [comment]
Also we just don’t have enough resources

**Comment by jobs-git** [comment]
If actix will be supporting QUIC/HTTP3 in the future, it should have a mechanism to do kernel bypass, else it would get a very poor Performance per hardware. So were do you think should we file that issue?
