### ISSUE TITLE
Export AppEntry

### ISSUE THREAD

**Issue by snoyberg** [actix/actix-web#1005]
Use case: I'm trying to extract the closure which lives inside `HttpServer::new` to its own top level function. However, I'm unable to write the type signature, since `AppEntry` is not publicly exported. Would you be open to a PR which would make `AppEntry` available publicly?

**Comment by fafhrd91** [comment]
Writing down App type is wrong approach. Try App::configure, if it doesn’t work then it is better to use `impl IntoNewService<...>` instead of App type

**Comment by snoyberg** [comment]
Thanks for the quick response! I'll go that route instead, thank you.
