### ISSUE TITLE
on_connect result isn't added to Request extensions when using HTTP2

### ISSUE THREAD

**Issue by hexd0t** [actix/actix-web#1009]
The result of the on_connect callback isn't added to the Request's extensions in the HTTP2 service.

Example on_connect:
```rust
fn cert_passthrough<T>(connection : &SslStream<T>) -> Option<X509> {
    connection.get_ref().ssl().peer_certificate()
}
```
Example Handler:
```rust
fn index(request : HttpRequest) -> String {
    format!("Option<X509>: {}", request.extensions().contains::<Option<X509>>() )
}
```
calling this with curl with client certificates:

| Protocol | Expected response | Response |
| --- | --- | --- |
| Force HTTP1.0 | `Option<X509>: true` | `Option<X509>: true` |
| HTTP2 | `Option<X509>: true` | `Option<X509>: false` |

Looking at the diff of https://github.com/actix/actix-web/commit/d286ccb4f5a86eca12c65b1632506a8bd8b37d19, DataFactory::set() of on_connect is called in actix-http/src/h1/dispatcher.rs poll_request:507, but nowhere in actix-http/h2

**Comment by fafhrd91** [comment]
fixed in master
