### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by claudiojulioferraz** [actix/actix-web#1010]
Congratulations on the project, it is ultra fast, but it has some questions that should be clarified so as not to alienate beginners like me.

Why are documentation and guides not translated as first class entities?

Why isn't dependency update top of the next goals?

Is actix dead or is actix-web his evolution? Why do you both have the same site? Wouldn't it be better to have a clearer separation? Why not rename actix-web?

_Automatically translated._

**Comment by fafhrd91** [comment]
> On Jul 28, 2019, at 7:21 PM, Cláudio Júlio Ferraz <notifications@github.com> wrote:
> 
> Congratulations on the project, it is ultra fast, but it has some questions that should be clarified so as not to alienate beginners like me.
> 
> Why are documentation and guides not translated as first class entities?
> 
Actix is open source project. It get translated if someone needs it.

> Why isn't dependency update top of the next goals?
> 
I don’t understand the quest.

**Comment by claudiojulioferraz** [comment]
Sorry, this is Google translate. I am Brazilian.

I would just find it interesting to have more detailed documentation with more examples. It would also be interesting to have a roadmap.

I am starting to use Duolingo and hope that in a year's time this confusion will not recur. ;)

**Comment by jfbaro** [comment]
@claudiojulioferraz I am Brazilian too, I can help you with this problem (Translating you question from Portuguese to English or Actix itself), just let me know.

**Comment by fafhrd91** [comment]
No actionable here. Re open if you’ll have more ideas or just create Pr
