### ISSUE TITLE
JSON Request: Json deserialize error: key must be a string at line 1 column 2

### ISSUE THREAD

**Issue by Tockra** [actix/actix-web#1012]
Hey Guys,

I copied the example from: https://actix.rs/docs/request/
```rust
use actix_web::{web, App, HttpServer, Result};
use serde::Deserialize;

#[derive(Deserialize)]
struct Info {
    username: String,
}

/// extract `Info` using serde
fn index(info: web::Json<Info>) -> Result<String> {
    Ok(format!("Welcome {}!", info.username))
}

fn main() {
    HttpServer::new(|| App::new().route("/", web::post().to(index)))
        .bind("127.0.0.1:8088")
        .unwrap()
        .run()
        .unwrap();
}
```

After starting the application I tried
```bash
.\curl.exe -H "Content-Type: application/json" -d '{"username": "someName"}' http://127.0.0.1:8088
```

But I get always these result:
```bash
Json deserialize error: key must be a string at line 1 column 3
```

Is there a failor on my side or does that function just not run ?

T

**Comment by sonfangos** [comment]
Shouldn't you include the HTTP method? This works for me:

`curl -H "Content-Type: application/json" -d '{"username":"someName"}' -X POST http://127.0.0.1:8088`

**Comment by llebout** [comment]
> Shouldn't you include the HTTP method? This works for me:
> 
> `curl -H "Content-Type: application/json" -d '{"username":"someName"}' -X POST http://127.0.0.1:8088`

`-X POST` is automatically set with `-d`

```
-d, --data <data>
              (HTTP)  Sends  the  specified  data in a POST request to the HTTP server, in the same way that a browser
              does when a user has filled in an HTML form and presses the submit button. This will cause curl to  pass
              the data to the server using the content-type application/x-www-form-urlencoded.  Compare to -F, --form.
```

As discussed with them on Gitter, the problem comes from PowerShell's handling of different kinds of quotes.

**Comment by Tockra** [comment]
Okay, sorry that was a windows powershell issue. The right command is:
`.\curl.exe -H "Content-Type: application/json" -d "{\`"username\`": \`"someName\`"}" http://127.0.0.1:8088`

**Comment by fadeevab** [comment]
The same about PowerShell. The following works for me:

```
curl -H "Content-Type: application/json" -d '{\"username\": \"someName\"}' http://127.0.0.1:8088
```
