### ISSUE TITLE
Expand book to also have an example with wrap_fn

### ISSUE THREAD

**Issue by svenstaro** [actix/actix-web#1013]
I think `wrap_fn` is super handy compared to the full-size middlewares. It should definitely get some exposure in the bug. As it stands, I've only stumbled upon it in the docs while browsing.

**Comment by fafhrd91** [comment]
I think `wrap_fn` should be adapter function and `App::wrap_fn()` should be deprecated

**Comment by svenstaro** [comment]
I would agree with that but that's not what this issue is about.

**Comment by svenstaro** [comment]
I went ahead and put forth a suggested fix.
