### ISSUE TITLE
Can't compile on 1.34.2 with latest dependencies

### ISSUE THREAD

**Issue by qnighy** [actix/actix-web#1017]
The [README](https://github.com/actix/actix-web/blob/web-v1.0.5/README.md) states that the MSRV is 1.34.0. However, its latest dependencies don't compile on 1.34.2.

- [actix-web 1.0.5 depends on actix-http `^0.2.7`](https://github.com/actix/actix-web/blob/web-v1.0.5/Cargo.toml#L81)
- [actix-http 0.2.7 depends on actix-connect `^0.2.1`](https://github.com/actix/actix-web/blob/b6ff786ed361cb2d1c4111629dd9c96e697a0cfe/actix-http/Cargo.toml#L49)
- [actix-connect 0.2.1 uses `Iterator::copied`](https://github.com/actix/actix-net/blob/connect-v0.2.1/actix-connect/src/connect.rs#L152)
- ...which was [recently stabilized in 1.36.0](https://github.com/rust-lang/rust/blob/1.36.0/RELEASES.md#stabilized-apis).

I suggest to update MSRV to reflect the fact or to fix `actix-connect` to avoid `Iterator::copied`.

**Comment by fafhrd91** [comment]
thanks, readme is updated.
