### ISSUE TITLE
Call to Community and Participation

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#1019]
Until now i made most of project related decisions. But unfortunately, i dont have much time anymore, also i'd like to spend more time outside of opensource. supporting of this large and complex project is time consuming so i'd like to hand it to contributors, who'd like to spend some time on the project. I am still planing to work on actix, but can not afford to spend that much time as before.

@actix/contributors

**Comment by sbditto85** [comment]
As someone with little OSS experience, what would the requirements be to be a contributor? I doubt I qualify but wouldn't mind helping where I could.

**Comment by cldershem** [comment]
I'm not sure I've got the technical chops to do much of the heavy lifting on `actix-web`, but after spending weeks working on the docs, I have a desire to see this project succeed. 

Do you think we could start the handoff by creating a project roadmap? I believe @mitsuhiko has been watching this project for a while, maybe he has some advice from when `flask`/`pallets` went to being community maintained?

**Comment by dewey4iv** [comment]
I'd love to help out. I've used actix (and actix-web) a number of times. I might be a little out of my depth here considering the recent changes to actix-web and the future of async/await. But I'll offer my help nonetheless. :)

**Comment by MattWhelan** [comment]
I'm interested in helping. I'd call myself relatively new to Rust, but I'm very familiar with http and web services. I really like actix-web, and I'd like to see it succeed and transition toward async-await. 

Some OS projects maintain a good-first-bugs list, but the one here is empty. I find fixing bugs to be a good way to learn the ins and outs of a new codebase.

**Comment by svenstaro** [comment]
I'm a fairly experienced open source maintainer but I'm barely
knowledgeable about actix internals. I've done a bit of cleanup work these
last few days in this project.

**Comment by 00benallen** [comment]
I'm an intermediate rust developer with a lot of full-stack web development experience, I'd be happy to help!

**Comment by pythoneer** [comment]
I am currently writing a little service with actix-web for my own personal use and have done a little project with it at my workplace. I would love to help keeping this project alive. I can see myself improving the documentation and work my way into code underneath the surfacing API. I think a road map and some goals would be pretty helpful.

**Comment by neoeinstein** [comment]
I am interested in participating in this process. I have some investment in the project already, and enjoy using it myself.

**Comment by Phil-dev17** [comment]
I have experience with Actix and Rust, but am new to contributing to open source projects and a newer dev ~3 years. I would love to contribute, but might need someone to provide me some direction or specific tasks to target to get started.

**Comment by jspeis** [comment]
I'm happy to help - I'm new to Rust and will need a little bit of guidance at first, but am happy to contribute as I can.

**Comment by augustocdias** [comment]
I'd be more than happy to help out.
I'm an experienced backend developer (mostly web). I have worked with other languages such as Java and C++ and I've started with Rust some months ago and since then I've been also using actix-web.

**Comment by mitsuhiko** [comment]
I would be more than happy to assist in creating a community around this and also contribute myself. We're using it at sentry actively :)

**Comment by fafhrd91** [comment]
just to be clear. i am not leaving the project completely, i just dont have same amount of time for contribution. also i'd like to make decision making process more strait forward and not dependent on me. i still use actix at my work and we are not planing to remove it. so dont panic!

@sbditto85 @dewey4iv @MattWhelan @00benallen @pythoneer @Phil-dev17 @jspeis @augustocdias i sent invitations to you. @neoeinstein and @svenstaro are already part of contributor team. `Contributor` team has permission to review and merge to master, but use this power wisely.

regarding `Core` team, i think contributors should promote to that team.
also @mitsuhiko member of `Core` group and has owner access to the probject.

regarding roadmap, i dont have one but from design perspective actix is in good state and does not require my full attention.

**Comment by robjtede** [comment]
Definitely would be interested in contributing in any small way. Want to see thiis crate continue to succeed.

**Comment by leizzer** [comment]
I have lot of experience with web techs mostly in Ruby, I used actix-web for a personal project and I would love to give you a hand guys.
Even if it is only reviewing, answering, issues or writing examples.

**Comment by srikwit** [comment]
Hey! count me in. Let me know how I can contribute.

**Comment by fMeow** [comment]
I'd love to participate in this process. I have use actix-web and also actix a lot, and I really enjoy it in the past few month, especially in websocket client and actix message passing. I like to contribute to this fansinate projects, especially on integrating async/await support into actix as this feature will be sooner or later stabilized.

**Comment by vmalloc** [comment]
I’d love to help out - I’ve helped in the past with documentation and a small fix or two. I love Actix and would really like to see it grow in user base and features!

**Comment by SRGOM** [comment]
I'm a total nobody but i wish to see this project succed. May I request people enter their 'nominations' in a format that's easy to sort out? Part of me thinks that the rust community has a fat tail with people who are new and very enthusiastic. I think the kind of people required are: 

* experienced in Rust- 
* have reasonable experience with various parts of the codebase (specially since @fafhrd91 mentioned here https://github.com/actix/actix-web/pull/968 that the code was written with the assumption that there will be someone very experienced reviewing the changes). Exxperience in web-dev or developing around actix would be a bonus but not a substitute... 
* Enthusiastic about OSS (and not just Rust)- OSS can be very tiring and, frankly, as I said in the last post here- https://github.com/actix/actix-web/pull/968#issuecomment-512146519 , people can be toxic. Actix is not just another web framework, it's currently one of the top performing ones across all programming languages. it's going to be a huge responsibility as things progress. As Rust gains adoption, its going to need a lot of energy. 

I'm not sure what other roles there could be- documentation wouldn't need one to become a maintainer (or post here, you could just send a PR quietly). I think one kind of people with two different roles are needed- maintainers and mentors (same set of people doing both jobs) 

Hence, if people agree with my post, lets keep this kinda short and apply only if you think you could check all three requirements and mention them explicitly (because it's not mentioned in half the posts here so far)

**Comment by fafhrd91** [comment]
@SRGOM you have good ideas.

@mitsuhiko could you take this from here

**Comment by bitemyapp** [comment]
We're using Actix at my company, we're Haskellers and your framework has contributed a lot to our enjoyment of Rust. I'd like to help out as a contributor if you believe that makes sense.

Thank you for your hard work @fafhrd91! You were nothing but patient and kind when I or my coworkers asked questions.

**Comment by SHDavies** [comment]
I don't have a ton of OSS experience either, but I've gotten pretty familiar with Rust over the last couple years and I'm really excited about what actix is doing and would love to help out any way I can. I'd be really interested in helping improve the API to be a bit more beginner friendly. We're using actix at my company and I'd love for it to have a bit less steep learning curve for new hires.

**Comment by vmalloc** [comment]
Can’t agree more. @fafhrd91 has been an amazing example of how to make people feel welcome when using a new project. He has answered even my dumbest questions with patience and humility, and I think many maintainers (myself included) can learn a lot from him. I think I speak for many when I say thank you!!!

**Comment by WindSoilder** [comment]
I'm happy to help on this, although I'm new to rust, but I have try to make some PR for rust open source project (Like [reqwest](https://github.com/seanmonstar/reqwest)).
I'm a backend programmer, and familiar with http and web programming, I think my experience can help me to do this :)

**Comment by gh67uyyghj** [comment]
Thank you @fafhrd91 for everything you did. Actix is one of the cleanest and most well-designed web framework in any language

**Comment by JohnTitor** [comment]
I'd like to help the actix project even a just little, can I participate? @fafhrd91 (I also emailed, please check it.)

**Comment by subhojit777** [comment]
I would like to help the Actix project. I checked the issue queue, couldn't find any issues labeled with _good first issue_. It would be great if there is a list of beginner issues.

I am new to Rust. I have used actix-web in a side project, but don't know much about its internals.

Thanks @fafhrd91 for all the hard work. The recent stable recent looks so much good.

**Comment by husseinraoouf** [comment]
I'd like to contribute to Actix project, although i am not yet very good with rust i think i could help with many things, at least i could help with documentation, making examples or fixing simple issue until i get familiar with actix code base

also it would be good to label simple issue with good-first-issue label so beginner like me can know where to start

**Comment by pythoneer** [comment]
especially @fafhrd91 @cldershem @svenstaro @mitsuhiko and everybody else in this thread – things have settled and i think the majority of the people that have heard of this issue and wanting to help have commented here. But i think we need a way to get things going. Any idea of how to proceed? I think a precise road map is out of scope currently. I look at the chat every know and then but i think it would be helpful to have kickoff meeting or anything alike, to exchange some ideas – what people think about how to proceed or what this "call to community" even means in the end?
I just don't want the enthusiasm many people brought to the table here to just vanish.

**Comment by leizzer** [comment]
@pythoneer I agree, I thought in posting something similar to this but didn't want to bother anyone. There are a bunch of members willing to work on the documentation, but I think they don't want to overlap or duplicate work and I believe is the same for any other big change.

**Comment by svenstaro** [comment]
I personally just help out here and there. I don't need to be part of a core team with a fixed road map. I'm a simple man: I see things that could be improved, I make a PR. :)

**Comment by cldershem** [comment]
@pythoneconfer I think you're right that things have settled. I'm at RustConf the next few days so I am a little bit busy. Maybe we can try to set up a time for us all to jump on the gitter channel? Really I don't know if we need something super formal at the moment. I think having a rough outline of where the project is headed and the big pain points right now would be a great start.

**Comment by NOVA-ME** [comment]
I'd like to contribute to Actix project, although I'm not good at rust, but I hvae already do so many translation works for rust community. So I think that I can do something for actix web too.

I really happy to join this community. 😄 

Thanks @fafhrd91, build up this wonderful web framework.  👍

**Comment by zzy** [comment]
I used actix-web as web-server for bigdata and AI project, it met my expectation with fast speed and fewer system resources.

I hope to see actix project succeed, and I am interested in participating in this process,  to integrate with other crates for real production use.

**Comment by fafhrd91** [comment]
i am not sure if this is success or not, but i'll close this ticket for now

**Comment by pythoneer** [comment]
Fair enough. I do think that there are many people wanting to help and i would include myself here. The Problem i see – as i stated earlier – is that many people don't really know what to do. I watched the migration to std::futures closely and can attest that i couldn't have done it on my own. I checked out `actix-files` yesterday and have started migration and had quite a few problems – actix-web as a whole is quite a big codebase and its hard to find a starting point. It would be helpful to know how difficult certain – leftover – issues are and and where to look at code wise to fix them. 

The degree in speed that you are able to "rush" through your familiar actix code in the very specific case in the std::future migration is intimidating fast. It almost feels like i am slowing you down in trying to help. I do think its a success to some degree but i think we need more `on boarding help`. I don't think its up to you to deliver that but i do think we as potential contributors need to better organize to help our self by e.g. better organize the current issues and/or make issues on how to proceed with certain features and breaking them down to digestible pieces. The whole std::futures migration was just to big for a single "outsider" to handle alone – with all respect @fafhrd91 you can lift some heavy pieces when it comes to code!

**Comment by naturallymitchell** [comment]
I can lead the community.
