### ISSUE TITLE
[Request] Change return type of HeaderName::from_static

### ISSUE THREAD

**Issue by TerminalWitchcraft** [actix/actix-web#1021]
The return type of `HeaderName::from_static` is misleading, and causes runtime panic in if non-standard header name is used. 

It would be nice if we could change the return type to `Result<HeaderName, InvalidHeaderName>` so that errors can be accordingly.

**Comment by fafhrd91** [comment]
It is better to fix panic

**Comment by neoeinstein** [comment]
Yep. The idea of this API is to provide a convenient way to provide a string that is statically known to be valid. I'm not sure of your use case, but since `from_static` only takes a `&'static str`, then a bad header would thus _always_ return the error case. In this case, the right time to take care of the invalid header name is at compile-time, rather than run-time.

**Comment by fafhrd91** [comment]
i dont understand how name could be checked at compile-time

**Comment by fafhrd91** [comment]
`HeaderName::from_static` is optimization, it does not allocate.

**Comment by neoeinstein** [comment]
Sorry, my intention wasn't to say that Actix should do the check at compile-time, though there might be a way to do so in the future using a function-style macro in expression position. Nonetheless, the correction should be by the developer, not by triggering run-time error handling.

**Comment by neoeinstein** [comment]
Example of using a function-style proc-macro in expression position to generate a `decimal` at compile time: paupino/rust-decimal#154

This did require using the `proc-macro-hack` crate, as I understand by default proc-macros in expression position is not yet stable.

Then, creating a HeaderName from a `&'static str` could be something like `http::header::header_name!("my-very-valid-header")`. A bad header could generate a compiler error.

**Comment by fafhrd91** [comment]
we can add macro. but i dont see reason for changing `::from_static()` method, it serve specific reason, we can not protect developers from silly and easily discoverable errors, add Result<> would reduce usability of the api.

**Comment by neoeinstein** [comment]
Yes, I agree.
