### ISSUE TITLE
Memory leak with header in request

### ISSUE THREAD

**Issue by squidpickles** [actix/actix-web#1022]
I am running into a memory leak when clients post large request bodies with custom headers.
Below is included client and server code for reproducing the bug.

An unusual bit of behavior is that varying either the header size or the request body size can trigger the memory leak; certain combinations appear safe.

Running on a MacBook Pro (using Instruments for watching allocations/process size), I've noticed the following:

- Sending no custom header causes no memory leak, regardless of body size. (Tested with several body sizes ranging from about 1kB - 4 MB)
- Sending a custom header with a value size 31 bytes or less does not trigger a memory leak, regardless of body size
- Sending a custom header with a value size 32 bytes or more does not trigger a memory leak if the body size is less than about 32 kB. (Seems like around 32608 bytes is the cutoff, but that may just be a very slow leak.)
- Sending a custom header with a value size 32 bytes or more triggers a memory leak with a body size 32kB or greater.

Here is the server code that is exhibiting the memory leak:
```rust
use actix_web::{error::Error, web, App, HttpResponse, HttpServer};
use futures::*;

pub fn upload(body: web::Payload) -> impl Future<Item = HttpResponse, Error = Error> {
    body.map_err(Error::from)
        .fold((), move |_, _| Ok::<_, Error>(()))
        .and_then(|_| Ok(HttpResponse::Ok().finish()))
}

fn main() {
    let server = HttpServer::new(move || App::new().route("/upload", web::post().to_async(upload)));
    server.bind(("127.0.0.1", 5000)).unwrap().run().unwrap()
}
```
and, the client code:
```rust
use std::{thread, time};

const THREADS: usize = 8;
const BODY_SIZE: usize = 32 * 1024;
const HEADER_SIZE: usize = 32;
const BODY_DATA: [u8; BODY_SIZE] = [b'x'; BODY_SIZE];
const HEADER_DATA: [u8; HEADER_SIZE] = [b'x'; HEADER_SIZE];

fn main() {
    for _ in 0..THREADS {
        thread::spawn(move || {
            let client = reqwest::Client::new();
            loop {
                let _ = client
                    .post("http://127.0.0.1:5000/upload")
                    .body(&BODY_DATA[..])
                    .header("X-Custom", &HEADER_DATA[..])
                    .send()
                    .map_err(|err| println!("Error: {}", err));
            }
        });
    }
    thread::sleep(time::Duration::from_secs(86400));
}
```
On my computer, the client settings above show about 6MB RAM growth every 10 seconds.

Attached are zip files for client and server code, including Cargo.lock
[leakserver.zip](https://github.com/actix/actix-web/files/3470842/leakserver.zip)
[leakclient.zip](https://github.com/actix/actix-web/files/3470843/leakclient.zip)

The alloc tracer says all the extra RAM is being allocated inside `__ZN10actix_http2h110dispatcher14read_available17h418619b95730ba74E`

**Comment by fafhrd91** [comment]
Is this reproducible on linux?

**Comment by squidpickles** [comment]
Yes, same behavior in Linux. Observations on an Ubuntu server:

Body | Header | memory leak?
----- | ------- | --------------
32kB | 32 | no
32kB | 128 | no
32kB | 128kB | no
48kB | 32 | no
512kB | 0 | no
128kB | 0 | no
128kB | 31 | no
64kB | 32 | yes
2MB | 512 | yes
1MB | 32 | yes
112kB | 32 | yes
128kB | 128 | yes
128kB | 32 | yes
512kB | 32 | yes

**Comment by bitemyapp** [comment]
I tried running the repro on Ubuntu 18.04 LTS w/ `cargo run --release`.

It spiked a megabyte and change each time I `SIGINT`'d the client and fired it up again from 500kb to 7.3MB. Once it hit 7.3 MB, it grew much more slowly. I don't know whether this fits what OP feels was aberrant or not. Gonna leave it to run for a long time, see where it gets.

**Comment by squidpickles** [comment]
@bitemyapp that's a helpful observation.
We've been seeing extremely large growth in memory in our production service (10 GB over 3 processes every 10 minutes). While I believed the above code reproduced the bug, I may not have run it long enough to confirm. Indeed, when it runs for 15 min or so, memory usage does seem to stabilize.

I'm going to investigate a few other things; please don't spend too much time on this yet!

**Comment by bitemyapp** [comment]
After one day of running leakserver and leakclient, holding steady at 7.4-7.5mb. I'll ignore it for now until you feel more confident about your repro.

**Comment by fafhrd91** [comment]
re-open with more evidence
