### ISSUE TITLE
gzipped response body is cut around 45kB of gzip

### ISSUE THREAD

**Issue by mockersf** [actix/actix-web#103]
When getting a long gzip body, the compressed response is always around 45KB, which decompress to around 250KB of my expected json (it's full size is around 420KB)

I added a test in tests/test_server.rs: test_body_gzip_large_random in #102
with a random string of 70000 characters, the response only contains 63747 chars (which makes a gzip of 47KB)

**Comment by fafhrd91** [comment]
should be fixed in master
