### ISSUE TITLE
call http and parse json inside route cause memory leak

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#1034]
repro_url: https://github.com/GopherJ/simple-reproduction-memory-leak-actix-serde

**Comment by jesskfullwood** [comment]
Thanks for the reduced repo. I have run it and it seems to be working fine AFAICT. Memory usage increases a little when a request comes in but when it is finished mem goes back down.

I ran the following loop (5 req/s) for about 10 minutes
```bash

while [ 1 ]
do
    curl -s http://localhost:8000 > /dev/null &
    sleep 0.2
done
```
and afterwards the RES mem was stable at about 830MB.

I'm running ubuntu 18.04, rustc 1.38.0-nightly (d3f8a0b5d 2019-08-04).

Could you say more about your system and how you are testing it?

**Comment by 0x8f701** [comment]
hello @jesskfullwood this is the information on my pc:

ubuntu19.04
rustc 1.36 stable

**Comment by 0x8f701** [comment]
hello I'm using `ubuntu 19.04` with `rustc 1.38.0-nightly`

I'm testing with nearly the same command:
```
while sleep 1; do curl -s http://127.0.0.1:8000 > /dev/null; done
```

clearly there is a problem, using nodejs my memory usage has never been able to reach 3%....

![memory-still-leak](https://user-images.githubusercontent.com/33961674/63025820-9695e800-bedc-11e9-86b5-be942262441b.gif)

**Comment by 0x8f701** [comment]
js
```js
#!/home/cheng/.nvm/versions/node/v10.15.3/bin/node
const Koa = require('koa');
const app = new Koa();
const fs = require('fs');
const axios = require('axios');

// response
app.use(async ctx => {
    ctx.body = (await axios.get('http://127.0.0.1:4000/payload.json')).data
});

app.listen(8000);
```
and memory usage:

![memory-not-leak](https://user-images.githubusercontent.com/33961674/63026632-1ff9ea00-bede-11e9-8e42-d51355855b2f.gif)

**Comment by jesskfullwood** [comment]
Sorry, I'm unable to reproduce - very stable on my box. Maybe someone else will have more luck.

![snapshot](https://user-images.githubusercontent.com/38404589/63027123-456a0200-bea4-11e9-9d77-a63ab2bc4b71.png)

**Comment by 0x8f701** [comment]
@jesskfullwood it seems when I compile again it disappears, it's really weird, I have an older rust version this morning and just changed to `1.38` this afternoon and just now it disappears....I'll try to rewrite my working code to use `awc` and test again, I'll let you know. Thanks!

**Comment by 0x8f701** [comment]
hello @jesskfullwood  I confirm that with `rustc 1.38.0 nightly` it works really well and no memory leak found for this moment, I'll continue to do some tests.

The only problem that I'm having is with `super big json (800MB)`, in this case it seems thread crashs and then it cannot release the memory allocated

**Comment by fafhrd91** [comment]
if thread crashes then all resources get leaked. you should fix cause of the crash. use RUST_BACKTRACE=1 to see where it crashes

**Comment by fafhrd91** [comment]
Reopen if you find other evidence

**Comment by harakas** [comment]
I would like to report that I have also run into this issue. My use case was a huge data structure passed into handlebars and then served with actix. I guess handlebars does serde serialization into json inside.

Static memory growth for each thread was 50+MB, with 28 workers my servers were quickly gaining 1.5GB of RAM. Quite insane. I mitigated the issue by cutting down the size of the data structure (making a smaller type by removing unnecessary stuff) and by reducing the actix server worker count.

As far as I can tell this is probably not an actix bug but I guess it does pop up for people using it as default server configuration uses a large worker count. I'm running with 2 workers now.
