### ISSUE TITLE
Support SameSite value "None" cookie attribute

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#1035]
We should set the cookie attribute “SameSite = None” for Chrome browser.

refs: 
- https://github.com/valyala/fasthttp/pull/581
- https://tools.ietf.org/html/draft-west-cookie-incrementalism-00
- https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html

**Comment by fafhrd91** [comment]
There is no such functionality, PR is required
