### ISSUE TITLE
doesn't build with stable due to flate2 dependency

### ISSUE THREAD

**Issue by estokes** [actix/actix-web#1036]
I just did a cargo update and due to a new release of flate2 actix-web no longer builds. I'm not sure exactly what the issue is with flate2, but the author seems to think it may be because it's being included with `default-features = false`.

see https://github.com/alexcrichton/flate2-rs/issues/205 for more info

**Comment by oyvindln** [comment]
It seems it's fixable by tacking on ```libc``` as a dependency feature in addition to ```miniz-sys```.

**Comment by estokes** [comment]
Sure, I was able to work around it, but I thought you guys should know about it.

**Comment by JohnTitor** [comment]
@estokes Could you check if `flate2 v1.0.11` fixes this issue?

**Comment by JohnTitor** [comment]
The original issue is marked as fixed so I'm going to close this. Feel free to re-open this if you still have a problem.
