### ISSUE TITLE
Arc<T> with different T don't work together as data

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#1043]
With the following code
```
    let pool = Arc::new(Mutex::new(ThreadPool::new(4)));
    let state = Arc::new(Mutex::new(State::new(conf)));
    HttpServer::new(move || {
        App::new()
            .data(Arc::clone(&pool)
            // .data(Mutex::new(ThreadPool::new(4)))
            .data(Arc::clone(&state))
```
This handler:
```
fn job_post(body: web::Json<msg::JobInit>,
            jobs: web::Data<Mutex<ThreadPool>>,
            state: web::Data<Arc<Mutex<State>>>) -> Json<Id> {
```

returns error 500 and says: `App data is not configured, to configure use App::data()`
However, if I make it a `Mutex<ThreadPool>` instead of an `Arc<Mutex<ThreadPool>>` it works fine.
I don't know whether this is a bug, or whether I am doing something wrong.

**Comment by jesskfullwood** [comment]
I don't understand how you can call 
```
Arc::clone(&pool)
```
when `pool` is a `Mutex`. Does your pasted code actually compile?

When using data, it will give you back exactly the type you put inside the `.data(..)` call. If you ask for something different, you get the error you saw.

**Comment by Ploppz** [comment]
Sorry, that's a typo / bad copy-pasting. I edited the issue.

**Comment by Ploppz** [comment]
I'm sorry, I can't reproduce the error anymore; if I really had `jobs: web::Data<Mutex<ThreadPool>>,` when I created this issue it's no wonder why it didn't work.
