### ISSUE TITLE
Making a function that returns App or HttpServer

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#1046]
I want to make such a function, that I can reuse for both running and testing my application. However, after much trial and error, I am not able to construct a good return type for such a function, due to some components of the type being private.
Is it possible? Could it be an idea to make it easier to make such a function?

**Comment by fafhrd91** [comment]
this is not possible in 1.0. You can only use `App::configure()` method

**Comment by Ploppz** [comment]
That seems to satisfy exactly what I need to do, thanks!
