### ISSUE TITLE
actix-web DOES NOT build because of `awc` dependecy compilation error

### ISSUE THREAD

**Issue by gh67uyyghj** [actix/actix-web#1048]
It seems that `awc` is not a direct dependency of `actix-http` but it cannot be successfully built because of this error
```
error[E0277]: the trait bound `serde_urlencoded::ser::Error: actix_http::error::ResponseError` is not satisfied
   --> /home/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-0.2.3/src/request.rs:504:44
    |
504 |             Err(e) => return Either::A(err(Error::from(e).into())),
    |                                            ^^^^^^^^^^^ the trait `actix_http::error::ResponseError` is not implemented for `serde_urlencoded::ser::Error`
    |
    = note: required because of the requirements on the impl of `std::convert::From<serde_urlencoded::ser::Error>` for `actix_http::error::Error`
    = note: required by `std::convert::From::from`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `awc`.
```

I compiled it on Rust 1.37 on linux and the version of `actix-http`  0.2.9

**Comment by jesskfullwood** [comment]
What exact commands will reproduce? Could you post a snippet?

Also, a quick `cargo update` sometimes resolves these sorts of problems.

**Comment by gh67uyyghj** [comment]
Sorry I don't even understand what happend but it's now resolved, I used `cargo clean` and removed the registry in my `~/.cargo` directory then replaced `actix-web` version with an older one `1.0.0` and it worked for now. I never experienced anything like this since I started coding in Rust but those were the worst 2 hours in my excellent Rust experience so far. It seems it is related to some cache issue but it's now gone

**Comment by antonok-edm** [comment]
Had the same issue here. `cargo clean` and removing `Cargo.lock` fixed it for me.
