### ISSUE TITLE
Websockets: Ping and Pong should have binary data

### ISSUE THREAD

**Issue by pathim** [actix/actix-web#1049]
The "Ping" and "Pong" messages defined in  actix-web/actix-http/src/ws/codec.rs take a String as parameter. This means that only valid utf8 can be used in these messages. But I think the [websocket spec](https://tools.ietf.org/html/rfc6455) does not actually require this.

The main problem with this is that a client that does not limit itself to utf8 ping messages will not receive correct pong messages because the data was mangled by from_utf8_lossy. This happens for example when using [this](https://websockets.readthedocs.io) python websocket library.

**Comment by rustrust** [comment]
#1006 would probably help

**Comment by yerke** [comment]
Should this be addressed in 2.0, since it will be a breaking change anyway?

**Comment by fafhrd91** [comment]
fixed in master
