### ISSUE TITLE
Start server from RawFd

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#105]
Cargo watch does not work because the sometimes the socket that's running will not be closed in time. That's why catflap exists. The problem is that the actix-web server does not allow for servers to be created from a raw file descriptor.

https://github.com/passcod/catflap  

There are integrations with hyper and iron but not with actix-web.

**Comment by fafhrd91** [comment]
Would you provide RawFd integration? Should be pretty strait forward.

**Comment by fafhrd91** [comment]
actually, i think server should accept TcpListener. then you can construct TcpListener from RawFd yourself

**Comment by fafhrd91** [comment]
it is possible to use [HttpServer::listen()](https://actix.github.io/actix-web/actix_web/server/struct.HttpServer.html#method.listen) for rawfd
