### ISSUE TITLE
Host header dropped on HTTP/2 requests

### ISSUE THREAD

**Issue by antonok-edm** [actix/actix-web#1050]
When connecting to an `actix-web` server over HTTP/1.0 or HTTP/1.1, the "Host" header is set as expected. When connecting over HTTP/2.0, it's mysteriously gone.

Minimal example below, using latest published versions of relevant crates:
```rust
use actix_rt::System;
use actix_service::Service;
use actix_web::{ web, App, HttpRequest, HttpServer };
use openssl::ssl::{ SslAcceptor, SslFiletype, SslMethod };

fn main() {
    let sys = System::new("system");

    let mut ssl_builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
    ssl_builder.set_private_key_file("/path/to/privkey.pem", SslFiletype::PEM).unwrap();
    ssl_builder.set_certificate_chain_file("/path/to/fullchain.pem").unwrap();

    HttpServer::new(move || {
        App::new()
            .wrap_fn(|req, srv| srv.call(dbg!(req)))
            .default_service(web::route().to(|_req: HttpRequest| "response"))
    })
        .bind_ssl("localhost:443", ssl_builder).unwrap()
        .start();


    sys.run().unwrap();
}
```

Server-side output when running `curl --http1.0 https://mydomain.com`:
```
[src/main.rs:14] req =
ServiceRequest HTTP/1.0 GET:/
  headers:
    "accept": "*/*"
    "host": "mydomain.com"
    "user-agent": "curl/7.65.3"
```
Server-side output when running `curl --http1.1 https://mydomain.com`:
```
[src/main.rs:14] req =
ServiceRequest HTTP/1.1 GET:/
  headers:
    "accept": "*/*"
    "host": "mydomain.com"
    "user-agent": "curl/7.65.3"
```
Server-side output when running `curl --http2 https://mydomain.com`:
```
[src/main.rs:14] req =
ServiceRequest HTTP/2.0 GET:/
  headers:
    "accept": "*/*"
    "user-agent": "curl/7.65.3"
```

This makes it impossible to determine which host was requested for HTTP/2.0 connections.

**Comment by fafhrd91** [comment]
this is http/2 specific, host header is forbidden

**Comment by antonok-edm** [comment]
@fafhrd91 it should be available somehow? Otherwise there is no way to support virtual hosting.

**Comment by fafhrd91** [comment]
URI contains full url

**Comment by fafhrd91** [comment]
we can not do anything on actix side. check what curl sends

**Comment by llucax** [comment]
Just in case someone else if fighting with this weird inconsistency between HTTP 1 and 2, there is a [host guard](https://docs.rs/actix-web/3/actix_web/guard/fn.Host.html) to implement virtual hosts transparently over both HTTP protocols without having to manually inspect both the `req.uri` and `req.headers()`.
