### ISSUE TITLE
Allow optional path segments

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#1054]
I was wondering how to implement a query for either a collection or a subresource, using the same handler. For example, say we have `/products` and `/products/{product_id}` -- it is currently impossible to manage both in the same handler conveniently.

I was wondering if it could be possible to use `web::Path<Option<String>>` for such cases, and have the handler check if a product id was specified in the URL. If that sounds reasonable I can try and craft a PR for it.

**Comment by jesskfullwood** [comment]
Interesting idea. How would we handle the case of `/some_path/{some_id}/more/paths`?

**Comment by vmalloc** [comment]
I think the optional scenario would only match in case the last path segment is both a parameter and missing...

**Comment by fafhrd91** [comment]
It is possible to use multiple patterns for resource in 2.0

```rust

App::new().service(web::resource([‘path1’, ‘path2/{name}/‘]).to(...)

```

**Comment by ChriFo** [comment]
Which method signature is needed for a resource with multiple patterns and optional path segment?

**Comment by vmalloc** [comment]
@ChriFo i don’t think this is supported with extractors. You would need to pass HttpRequest and use match_info to distinguish between the cases

**Comment by s97712** [comment]
> It is possible to use multiple patterns for resource in 2.0
> 
> ```rust
> App::new().service(web::resource([‘path1’, ‘path2/{name}/‘]).to(...)
> ```

How to do for  `actix_web::get/actix_web::post`?

**Comment by robjtede** [comment]
> How to do for actix_web::get/actix_web::post?

@s97712 Currently, it's not possible to provide multiple paths using the macros. PRs welcome.
