### ISSUE TITLE
actix-web 1.0 event loop hangs gets unresponsive, hangs forever after 1 month

### ISSUE THREAD

**Issue by jvo203** [actix/actix-web#1055]
This may or may not be related to https://github.com/actix/actix-web/issues/941 but anyway, after upgrading the application to actix 1.0 and having it run for a month without any problems (moderate network traffic, HTTP1.1 + WebSockets), suddenly it became completely unresponsive. It stopped responding to network requests, what is more, it even stopped responding to a "CTRL+C" clean shutdown request. Had to use killall -9 to terminate it. Internal logs did not reveal anything suspicious.

This (a bug?) might be very difficult to trace but somehow it seems as if the whole event loop underlying actix stopped working. Have you got any ideas of what might be causing it? A bug in the actix event loop? A bug in the tokyo library? It is hard to reproduce and hard to trace.

**Comment by leizzer** [comment]
Well as you said it is hard to debug without your code or time if being a month running causes it.

Is this something recurrent to you?
Or was it the first time?
Did you fallow the ticket mentioned?
Is it a windows machine too?

**Comment by jvo203** [comment]
Hi, The full production code is at https://github.com/jvo203/fits_web_ql
The production server runs CentOS 6.10, Rust is on 1.37. Yes I did follow the other issue ticket but it did not lead to a conclusive solution.

Unfortunately, after restarting the application (upgrading to Rust 1.37, recompiling the application) the problem has resurfaced after about 20 minutes of operation. At first the WebSocket part became unresponsive but the HTTP part was still OK. Then the HTTP part went down too, and CTRL+C stopped working too. The application became completely unresponsive. And I recall the other time last week when the application had experienced such a sudden "loss of responsiveness" problem on a few occasions but it seemed to resolve itself without a human intervention. The problem manifested itself after about 15 seconds since opening the web page. Usually the WebSocket part would stop responding first. Last week, when this problem happened I switched to another web browser (from Safari to Chrome) and the problem seemingly went away. But this time no matter what browser is used, the problem got worse and not even CTRL+C helps. 

On the production server we have now reverted to the last known stable git checkpoint containing actix 0.7 (before the upgrade to 1.0). So far so good. It seems that actix 0.7 seems to be quite stable. Prior to the change to 1.0 the code had been running OK for several months. Our hardware (networking etc) seems to be working OK so the only logical conclusion is that there might be a hard-to-trace software bug to do with actix 1.0 (or tokyo or other related libraries). Anyway, actix 0.7 seems to be working OK...

**Comment by fafhrd91** [comment]
Could you try to reproduce the problem in test environment?

**Comment by jvo203** [comment]
We have been unable to reproduce it on other machines (running CentOS 7, not 6 as the production server does). Unfortunately (or good news for actix!), after several hours of stable operation with the previous actix 0.7 the problem has resurfaced again. We will reboot the server which had been running continously since last November. Perhaps actix is not to blame after all. There may be something wrong with the production server (software and/or hardware), the OS event loop??? Don't really know how to debug such things though... Perhaps a simple reboot might help.

**Comment by jvo203** [comment]
Extra info: it seems the Apache proxy (it passes HTTP + WebSockets to our application) also experienced some failures. So it might be the case that a problem with the Apache proxy meant some requests had not been getting through to actix in recent days. 

We don't know the root cause of the problem in the proxy. And why would our application stop responding to CTRL+C? Perhaps the root cause of the problem lies somewhere elsewhere (hardware? CentOS 6?). But for now it seems actix is likely not to blame.

Whilst the live traffic to our website has been re-routed to another server, we will keep an eye on the failing production server for a while. Thanks to all involved for your comments. For now I will close this issue.
