### ISSUE TITLE
awc::ClientRequest: serialize to URI

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#1060]
It seems like functionality is already there? Because when you have `Query<T>` in some handler, `actix-web` automatically deserializes the incoming URI to the type `T`.

To name an example, in `reqwest` it's possible to serialize to URI: https://docs.rs/reqwest/0.9.20/reqwest/async/struct.RequestBuilder.html#method.query

I suggest to have a similar `query()` on [ClientRequest](https://docs.rs/awc/0.2.4/awc/struct.ClientRequest.html). What do you think?

**Comment by fafhrd91** [comment]
Sounds good

**Comment by fafhrd91** [comment]
fixed in master
