### ISSUE TITLE
Restore support for native-tls

### ISSUE THREAD

**Issue by CodeSandwich** [actix/actix-web#1061]
This is the only thing blocking me from migrating from 0.7 to 1.0

**Comment by jeizsm** [comment]
I will do it

**Comment by CodeSandwich** [comment]
`a guy who's a hero for fun`

**Comment by fafhrd91** [comment]
PR is welcomed.

**Comment by CodeSandwich** [comment]
Why is this issue closed?

**Comment by fafhrd91** [comment]
I am not planing to work on it, I don't want to keep dead issue
