### ISSUE TITLE
Request Extensions leak

### ISSUE THREAD

**Issue by pjenvey** [actix/actix-web#1062]
Request extension values can leak in between requests. This can be especially bad when e.g. storing pooled database connections in extensions, this leak can quickly exhaust such a pool.

actix-http's message module cache clears certain values when reclaiming req/resp "head" types, but actix-web's request module cache does not.

**Comment by fafhrd91** [comment]
1.0.7 is released

**Comment by fafhrd91** [comment]
thanks for reporting!
