### ISSUE TITLE
Idiomatic way of conditionally parsing json?

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#1067]
Currently trying to implement something like this:
```rust
fn route(data: web::Json<SomeData>) -> HttpResponse {
    if !is_user_authenticated(...) {
        return HttpResponse::Unauthorized().body("!!!");
   }
   // Work with data
}
```
Is prone to DoS attacks, because the server reads the request (even if it can be very big), deserializes it, and only then checks if the request is allowed.
What is the idiomatic way of achieving the same thing, only checking the authentication first?

**Comment by fafhrd91** [comment]
Move authentication to middleware or extractor

**Comment by vmalloc** [comment]
Can I count on the order of extraction for that matter?

**Comment by fafhrd91** [comment]
You can

**Comment by vmalloc** [comment]
Thanks for the quick reply!
