### ISSUE TITLE
Getting the request state in a future that consumes the request

### ISSUE THREAD

**Issue by niklasf** [actix/actix-web#107]
I basically want to do this in a handler:

```rust
req.urlencoded()
    .from_err()
    .and_then(move |params| {
        let state = req.state(); // req has been already moved into urlencoded :(
    })
    .responder()
```

For the same reason I also can't borrow it in advance. Am I missing an elegant way?

Using this workaround for now:

```rust
impl<S> HttpRequest<S> {
    pub fn split_state(self) -> (HttpRequest<()>, Rc<S>) {
        (HttpRequest(self.0, None, self.2), self.1.unwrap())
    }
}

// [...]

let (req, state) = req.split_state();

req.urlencoded()
    .from_err()
    .and_then(move |params| {
        let state = state; // yay!
    })
    .responder()
```

**Comment by fafhrd91** [comment]
I think something like `split_state` makes sense. right now you can just clone request

`req.clone().urlencoded()`

**Comment by niklasf** [comment]
Oh, thanks, I didn't realize it was Clone (or even that the Clone is just cloning Rc's). Probably I won't need `split_state` personally, then.

Close?

**Comment by fafhrd91** [comment]
yes
