### ISSUE TITLE
Runtime `App` config broken in 1.0

### ISSUE THREAD

**Issue by scottjmaddox** [actix/actix-web#1071]
I'm trying to upgrade to actix-web 1.0, and am running into a major issue: how to do runtime configuration of the App? In 0.7, I could use an if/else branch and add extra middleware, resources, and handles in one branch but not in the other. In 1.0, if I try to do that I get a type mismatch error between the two branches, because all of this is now encoded in the App's type! How do I deal with this?

**Comment by fafhrd91** [comment]
hmm, `broken`. so you say that I spend tons of time and built broken software, and now you want free help? nice.

**Comment by bitemyapp** [comment]
@scottjmaddox Could you post a small reproduction of the type error please? I don't recall having a problem like this when I migrated a ~2k loc actix-web application but it's possible my configuration needs were different from yours. I do remember things being a bit different.

**Comment by ghost** [comment]
Hi @scottjmaddox,

You can find an example of runtime config here: https://gitlab.com/bloom42/server/blob/dev/server/api/src/main.rs and https://gitlab.com/bloom42/server/blob/dev/server/api/src/app.rs

I think we can close this 'issue'

**Comment by scottjmaddox** [comment]
I've clearly caused offense, which was not at all my intention. I'm sorry for choosing my words so poorly and insensitively. You of course owe me absolutely nothing, and I should not have implied otherwise.

It does look like the example that @z0mbie42 provided contains the trick that I was missing (thank you for sharing it!), which is to do the branching inside of each call to `App::service` and either pass the desired service or disable it with this:

```
web::resource("*").route(web::route().to(kernel::api::route_disabled))
```

I would be happy to open a PR to add a note about this to the MIGRATION guide, if there's interest. Either way, I'm sorry again for not choosing my words more carefully and sensitively.
