### ISSUE TITLE
Move Askama/actix-web integration into actix-web

### ISSUE THREAD

**Issue by djc** [actix/actix-web#1072]
I have been struggling with the Askama integrations for different web frameworks. For now, Askama is not available for actix-web 1.0 because there are conflicting dependencies between actix-web/Gotham/Rocket, all of which Askama supports. Due to coherency issues, I think the integration code will have to live inside either actix-web or Askama. I'd still be happy to do any maintenance work required on the integration, but at this point I think it would be better if the actix-web/Askama integration moves into the actix-web crate (since the latter has many more requirements on the dependency tree than Askama itself).

**Comment by fafhrd91** [comment]
I am fine with moving askama support to actix-web repo.

**Comment by fafhrd91** [comment]
Anyone want to take this task? 

@actix/contributors

**Comment by fafhrd91** [comment]
whoever wants to help with this just open PR
