### ISSUE TITLE
TestRequest should allow for setting peer_addr

### ISSUE THREAD

**Issue by DavisFrench** [actix/actix-web#1074]
Currently I am trying to write tests for various endpoints in my code, but have found the TestRequests I'm building are not having `peer_addr` set. The endpoints I'm working on try to access `peer_address` via an expect, and panic in testing situations.

I was thinking that it could be possible to implement a `with_peer_addr` associated function and/or a `peer_addr` method to `TestRequest` so that a more customizable request can be made for testing situations.

**Comment by fafhrd91** [comment]
fixed in master
