### ISSUE TITLE
Futures for Async processing using ACTIX ?

### ISSUE THREAD

**Issue by KabDeveloper** [actix/actix-web#1082]
Hi,

Is there a way that actix-web support Async processing without reinitializing the function for each user request ?

My goal is to send data using KAFKA function:
https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/kafka_producer.rs

Need a producer/channel per worker, to not create producer for each request.

I opened an issue in rust-rdkafka github here:
https://github.com/fede1024/rust-rdkafka/issues/141

And need a follow up in this github since some infos/knowledge are missing in order to achieve my goal.

Thank you in advance.

**Comment by fafhrd91** [comment]
You can create separate component for kafka and communicate with it via channel. But in any case this is outside of scope of actix-web

**Comment by KabDeveloper** [comment]
Using channel to communicate datas to KAFKA worker is better than using KAFKA producer directly from actix ?

Anyway, thank you for your answer.

**Comment by fafhrd91** [comment]
I have no idea how kafka producer work, it is up to you.

**Comment by KabDeveloper** [comment]
@fafhrd91 DO you have example of Actixweb using channels please ?
