### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cheolgyu** [actix/actix-web#1083]
I am using actix-web.
I am trying to add the ability to query and modify db every minute.
**Method 1. Create a new schedule project.**
Disadvantages 1. 
Since the basic information used in the actix-web project is duplicated and added, the problem of modifying twice occurs.
Disadvantages 2. 
You need to add a router to use the internal functions you created in actix-web.
**Method 2. Add a schedule actor to my actix-web project as a db actor.**

I'm going to method 2.
create an actor
I want to know how to call the schedule actor's function repeatedly after SyncArbiter :: start () in main.rs.
in the main.rs file
I've put code in the loop that calls do_send, and the schedule actor's function works, but it doesn't work concurrently with actix-web.
The same goes for putting loops in actor's impl started ().

I want to know how to work concurrently with actix-web.

(Schedule actor will call dbactor every minute.)

**Comment by HiruNya** [comment]
If you use an (Async) Arbiter instead of a SyncArbiter then you can use the [run_interval](https://docs.rs/actix/0.8.3/actix/trait.AsyncContext.html#method.run_interval) function like this:
```rust
use actix::prelude::*;

use std::time::Duration;

struct MyActor {
    message: String,
}
impl Actor for MyActor {
    type Context = Context<Self>;
    
    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.run_interval(Duration::from_secs(60), |actor, _ctx| {
            println!("{}", actor.message);
        });
    }
}


fn main() {
    let system = System::new("Server-System");
    MyActor{ message: "One minute has passed!".to_string() }.start();
    system.run().unwrap();
}
```

Unfortunately, I don't think that can be done in a SyncArbiter though

**Comment by neoeinstein** [comment]
In the past, I've had an async actor trigger a sync actor. However, if this is an entirely background process, you might be better off just spawning a background thread, and having it sleep for a minute in between actions.

**Comment by fafhrd91** [comment]
i dont think issue tracker is good place for help questions
