### ISSUE TITLE
Allow serde_json::json to be argument to the response.body()

### ISSUE THREAD

**Issue by snawaz** [actix/actix-web#1086]
`active-web, 1.0.7` does not allow `serde_json::json` to be passed as argument to the response body:

```rust
use serde_json::json;

web::HttpResponse::Ok().body(json!({ ... }).to_string()); // OK

web::HttpResponse::Ok().body(json!({ ... }));  // ERROR
```

If it makes sense, please let me know. I'll create a PR for this.

**Comment by fafhrd91** [comment]
I am not sure about HttpResponse, but for builder you could use https://docs.rs/actix-web/1.0.7/actix_web/dev/struct.HttpResponseBuilder.html#method.json

**Comment by snawaz** [comment]
> I am not sure about HttpResponse, but for builder you could use https://docs.rs/actix-web/1.0.7/actix_web/dev/struct.HttpResponseBuilder.html#method.json

Nice. That'd work for me. Thanks. 

Still I think having this functionality in `body()` would make it more generic. So I'd keep it open till I hear more opinions.

**Comment by fafhrd91** [comment]
if you'd like you can create pr.

**Comment by snawaz** [comment]
Created the PR: https://github.com/actix/actix-web/pull/1096
