### ISSUE TITLE
Response error with json body

### ISSUE THREAD

**Issue by torepettersen** [actix/actix-web#1091]
I have a problem that the json body is being ignored on `ResponseError`. 
``` rust
impl ResponseError for ApiError {
  fn error_response(&self) -> HttpResponse {
    let status_code = match StatusCode::from_u16(self.status_code) {
      Ok(status_code) => status_code,
      Err(_) => StatusCode::INTERNAL_SERVER_ERROR,
    };

    HttpResponse::build(status_code)
      .json(json!({"message": self.message}))
  }
}
```

With this implementation I would have expected a the response body of the response to be json like this:
``` json
{
  "message": "Error message"
}
```

But instead I the response body always ends up being just a string representation of the error like this:
```
Error message
```

**Comment by fafhrd91** [comment]
you have to override `render_response` method

**Comment by fafhrd91** [comment]
this is known problem, will be addressed in future versions
