### ISSUE TITLE
Session within middleware is empty

### ISSUE THREAD

**Issue by Tarnadas** [actix/actix-web#1092]
Hi,

as a continuation to my previous issue #1088, I have now the problem that the Session received from ServiceRequest::get_session won't do anything at all when used within a middleware

```rust
impl<S, B> Service for AuthMiddleware<S> {
    // ...
    fn call(&mut self, req: ServiceRequest) -> Self::Future {
        let session = req.get_session();
        // this won't do anything at all
        if let Ok(Some(count)) = session.get::<i32>("counter") {
            println!("SESSION value: {}", count);
            session.set("counter", count + 1).unwrap();
        } else {
            session.set("counter", 1).unwrap();
        };
        Box::new(self.service.call(req).and_then(|res| Ok(res)))
    }
}
```

It also won't work with any value stored in the Session from outside the middleware. When I try to get any Session value within the middleware, it is always empty.

**Comment by fafhrd91** [comment]
order of middleware registration does matter, there is comment about that in UserSessiontrait.

**Comment by Tarnadas** [comment]
That was my assumption, which is why I first registered CookieSession and afterwards my own middleware. ~~The other way around has the same outcome~~

**Comment by fafhrd91** [comment]
https://github.com/actix/actix-web/blob/master/src/app.rs#L330

**Comment by Tarnadas** [comment]
sorry for being too fast here.

I haven't noticed that doc comment before, but now it is clear to me. Changing the order of middlewares solves my problem

**Comment by kevlarr** [comment]
If anyone else sees this and is struggling to get the session from a `ServiceRequest`, make sure that `actix_session::UserSession` is in scope, as this exposes `service_request.get_session()`

**Comment by KaiyuanMa** [comment]
For anyone looking at this 2023 and cant open the link, you need to register yor middleware before the SessionMiddleware.
```
App::new()
      .wrap(YourMiddleWare)
      .wrap(
          SessionMiddleware::builder(CookieSessionStore::default(), Key::from(&[0; 64]))
              .cookie_secure(false)
              .build()
      )
```
Also actix_session::UserSession is deprecated, use 

```
actix_session::session_ext::ServiceRequest
fn get_session(&self) -> Session
```
