### ISSUE TITLE
ConnectionInfo.remote() returns remote socket address not IP

### ISSUE THREAD

**Issue by gh67uyyghj** [actix/actix-web#1095]
The documentation in https://docs.rs/actix-web/1.0.7/actix_web/dev/struct.ConnectionInfo.html#method.remote says that it returns the IP of the peer. However, if it's obtained directly from the peer socket address, it returns also the peer socket address (e.g. `127.0.0.1:51286` and not `127.0.0.1`). This may cause real problems if this returned str value is used as is for rate limiting for example.

**Comment by fafhrd91** [comment]
PR is always welcomed

**Comment by fafhrd91** [comment]
doc string is updated
