### ISSUE TITLE
How to pass a Form to a request handler in a unit test

### ISSUE THREAD

**Issue by pfrenssen** [actix/actix-web#1099]
I'm practicing writing Rust code by attempting to write a unit test for the [`handle_post_2()`](https://github.com/actix/examples/blob/master/form/src/main.rs#L47) request handler in the `form` example.

The request handler looks like this:

```
fn handle_post_2(state: web::Data<AppState>, params: web::Form<MyParams>) -> HttpResponse {
    HttpResponse::Ok().content_type("text/plain").body(format!(
        "Your name is {}, and in AppState I have foo: {}",
        params.name, state.foo
    ))
}
```

I'm writing a unit test which is inspired on [`test_form()`](https://github.com/actix/actix-web/blob/master/src/types/form.rs#L377) from `actix_web::web::Form` but this relies on a private function `actix_web::web::Form::<T>::from_request()` (which is an implementation of the private `actix_web::extract::FromRequest` trait).

This is how my test looks so far:

```
#[cfg(test)]
mod tests {
    use super::*;

    use actix_web::http::{header::{CONTENT_LENGTH, CONTENT_TYPE}, StatusCode};
    use actix_web::test::{block_on, TestRequest};
    use bytes::Bytes;
    use actix_web::web::Form;
    use actix_web::extract::FromRequest; // Private trait.

    #[test]
    fn test_handle_post_2() {
        let state = TestRequest::default()
            .data(AppState {
                foo: "bar".to_string(),
            })
            .to_http_request()
            .get_app_data()
            .unwrap();

        let (req, mut pl) =
            TestRequest::with_header(CONTENT_TYPE, "application/x-www-form-urlencoded")
                .header(CONTENT_LENGTH, "11")
                .set_payload(Bytes::from_static(b"name=myname"))
                .to_http_parts();

        // ::from_request() is private.
        let params: Form<MyParams> = Form::<MyParams>::from_request(&req, &mut pl);

        let controller = handle_post_2(state, params);
        let response = block_on(controller).unwrap();
        assert_eq!(response.status(), StatusCode::OK);
    }
}
```

Because of the private function access I am getting the following error:

```
error[E0599]: no function or associated item named `from_request` found for type `actix_web::types::form::Form<MyParams>` in the current scope
  --> form/src/main.rs:91:56
   |
91 |         let params: Form<MyParams> = Form::<MyParams>::from_request(&req, &mut pl);
   |                                                        ^^^^^^^^^^^^ function or associated item not found in `actix_web::types::form::Form<MyParams>`
   |
   = help: items from traits can only be used if the trait is in scope
```

What is the recommended way to solve this? Do I have to implement this trait myself?

Side note: I know that `test::TestRequest::set_form()` can be used to test forms in functional tests. I would like to find out how to do this in a unit test that calls the request handler directly.

**Comment by fafhrd91** [comment]
did you check api docs? 

https://docs.rs/actix-web/1.0.7/actix_web/trait.FromRequest.html

**Comment by pfrenssen** [comment]
Thanks for the feedback! This documentation is not helping to pass the test but reading back I understand that I did a poor job of explaining my problem. I shouldn't have put this emphasis on the `from_request()` being private.

I had another look with the advantage of 1 more week of Rust experience under my belt and I found the solution. I can get the form that I need to pass in by doing `let params = Form(MyParams {name: "myname".to_string()});`.

Here is a working unit test for the `handle_post_2` request handler in the `form` example:

```
#[cfg(test)]
mod tests {
    use super::*;

    use actix_web::http::StatusCode;
    use actix_web::test::{block_on, TestRequest};
    use actix_web::web::Form;

    #[test]
    fn test_handle_post_2() {
        let state = TestRequest::default()
            .data(AppState {
                foo: "bar".to_string(),
            })
            .to_http_request()
            .get_app_data()
            .unwrap();

        let params = Form(MyParams { name: "john".to_string() });
        let controller = handle_post_2(state, params);
        let response = block_on(controller).unwrap();
        assert_eq!(response.status(), StatusCode::OK);
    }
}
```

Thanks for the assistance! If I find some time this weekend I will try to contribute some unit tests to the example repo which will hopefully help some other people that struggle with the same concept.

**Comment by pfrenssen** [comment]
Proposed a PR to add tests to the form example: https://github.com/actix/examples/pull/179
