### ISSUE TITLE
how can do this?

### ISSUE THREAD

**Issue by krircc** [actix/actix-web#11]
when request other paths return a specify file or path. like [this](https://rocket.rs/guide/requests/#multiple-segments)

**Comment by fafhrd91** [comment]
technically it is possible to do, but there is no easy way.  You can register application handler with `ApplicationBuilder::Handler`, it accepts prefix, then you can split prefix and get tail.

would you like to implement tail match for actix web?

**Comment by krircc** [comment]
@fafhrd91 yes. I want do a SPA with actic-web. so when request other paths it will return index.html. 
like:

    '/router/one'  ---> index.html
    '/router/two'  ---> index.html
    ......

**Comment by fafhrd91** [comment]
for your example you can use following example:
```rust
Application::default("/")
    .resource("/router/{section}", |r| {
        match r.params().get("section") {
          Some("one") => { do something },
          Some("two") => { do something else },
           _ => HTTPNotFound 
        }
    }))
```
is this what you need? you can match only one section at the moment.

**Comment by krircc** [comment]
@fafhrd91 no , I want match any paths not someone.  like '/router/{anyPaths}'
in rocket.rs like : 
```rust
#[get("/page/<path..>")]
fn path(path: PathBuf) -> io::Result<NamedFile> {
    NamedFile::open("webfront/index.html")
}
```
Is there a easy way do this current?

**Comment by fafhrd91** [comment]
it is not explicitly implemented at the moment. Would you like to participate in actix-web development and add this functionality?

there is temporary solution:
```rust
Application::default("/")
    .handler("/router/", |r| {
        let tail = r.path()[r.prefix_len()..];
        println!("Tail: {:?}", tail);
        HTTPOk
    }))
```
`tail` would contain everything after `/router/` prefix

**Comment by fafhrd91** [comment]
if you want just serve files from filesystem you can use https://github.com/actix/actix-web/blob/master/src/staticfiles.rs#L26

**Comment by fafhrd91** [comment]
actix-web is missing a lot of staff, any help is welcome!

**Comment by fafhrd91** [comment]
I just added tail pattern https://github.com/actix/actix-web/blob/master/src/recognizer.rs#L140

you can use it like this:
```rust

Application::default("/")
    .handler("/router/{tail:*}", |r| {
        let tail = r.match_info().get("tail").unwrap();
        println!("Tail: {:?}", tail);
        HTTPOk
    }))
```

I didn't test it though

**Comment by fafhrd91** [comment]
I'll close issue. reopen if you think we should add something else

**Comment by krircc** [comment]
@fafhrd91 please provide support reponse return file.

**Comment by fafhrd91** [comment]
Could you provide pull request?

**Comment by fafhrd91** [comment]
here is example

```rust
extern crate actix_web;
use actix_web::*;
use std::path::PathBuf;

fn index(req: HttpRequest) -> Result<fs::NamedFile> {
    let path: PathBuf = req.match_info().query("tail")?;
    Ok(fs::NamedFile::open(path)?)
}

fn main() {
    Application::default("/")
        .resource(r"/a/{tail:*}", |r| r.get(index))
        .finish();
}
```

**Comment by fafhrd91** [comment]
I dropped tail pattern, but it possible to do the same with custom regex ".*" :

```rust
extern crate actix_web;
use actix_web::*;
use std::path::PathBuf;

fn index(req: HttpRequest) -> Result<fs::NamedFile> {
    let path: PathBuf = req.match_info().query("tail")?;
    Ok(fs::NamedFile::open(path)?)
}

fn main() {
    Application::default("/")
        .resource(r"/a/{tail:.*}", |r| r.method(Method::GET).f(index))
        .finish();
}
```
