### ISSUE TITLE
Content-length not returned for chunked responses

### ISSUE THREAD

**Issue by nishtahir** [actix/actix-web#1100]
For the same response returning Json, it seems the content length is not returned consistently on the same endpoint.

It looks like when the response is chunked the content length is not returned in the header.

Here's a sample response that is small enough that it's not chunked
![image](https://user-images.githubusercontent.com/2018617/65476594-70575680-de51-11e9-80ea-ea40276af999.png)

Here's a response from the same endpoint that's larger and ends up being chunked. 
![image](https://user-images.githubusercontent.com/2018617/65476622-8a913480-de51-11e9-9879-1e8ef4e53b81.png)

**Comment by fafhrd91** [comment]
That is expected behavior. Actix-web returns chunked response if it can not determine content length

**Comment by nishtahir** [comment]
@fafhrd91 Thanks for validating the behavior. 

Can you elaborate on this a bit more for my own understaning. Given that i'm not streaming any data and pasing it a full struct how is it unable to determine the content length?
The only difference between the to images is that one is the size of the struct that is serialized.
