### ISSUE TITLE
HTTP/3 support

### ISSUE THREAD

**Issue by enfipy** [actix/actix-web#1104]
Any plans to support HTTP/3?

26th September was introduced HTTP/3 and [quiche](https://github.com/cloudflare/quiche) from Cloudflare. QUIC seems to be pretty fast and lightweight and it would be cool to add support of HTTP/3 in `actix-web`.

The blog post from Cloudflare - https://blog.cloudflare.com/http3-the-past-present-and-future/

**Comment by fafhrd91** [comment]
quiche does not use tokio, we can not use it.

**Comment by fafhrd91** [comment]
dup #309

**Comment by bitalianz** [comment]
> dup #309

Does it means that with https://github.com/djc/quinn crate it's possible to have it implemente in Actix Web?

**Comment by marcus-sa** [comment]
https://github.com/cloudflare/quiche would most likely be a better choice.

**Comment by Razican** [comment]
IETF has published [RFC 9114 (HTTP/3)](https://www.rfc-editor.org/rfc/rfc9114.html), and the h3 crate seems ready for starting with initial tests: https://github.com/seanmonstar/reqwest/issues/1558

**Comment by LinuxHeki** [comment]
> quiche does not use tokio

Now it does

**Comment by robjtede** [comment]
duplicate of https://github.com/actix/actix-web/issues/309
