### ISSUE TITLE
How to use `web::Data<T>` in `Future`

### ISSUE THREAD

**Issue by kathampy** [actix/actix-web#1105]
I've simplified the code to demonstrate the issue.
```
pub struct AppData {
    client: isahc::HttpClient,
}

...
App::new().data(AppData {
    client: isahc::HttpClient::builder().build().unwrap(),
})
...

pub fn handler(app_data: web::Data<AppData>)
-> impl Future<Item = HttpResponse, Error = ActixError> {
    let client = &app_data.client;
    ...
    client.send_async(request).then(|_| HttpResponse::Ok().body("Request Sent"))
}
```

This fails at `let client = &app_data.client;` with
```
`app_data` does not live long enough
borrowed value does not live long enough rustc(E0597)
```

It creates one instance of isahc::HttpClient per worker thread. What's the correct way to fix this?

**Comment by kathampy** [comment]
The issue is because the future from `send_async()` borrows the client.
Is there a way to extend the lifetime of the the client instances in each thread to static somehow?

**Comment by fafhrd91** [comment]
post handler code, and error

you can move Data<T> to any closure

**Comment by kathampy** [comment]
I don't have access to the code right now, but if I replace `isahc` client with `reqwest` or `awc` client, the same code works fine.
`isahc` is designed for `futures-0.3` and async / await. I'm using it using with `Compat` from futures-preview like the example provided by the developer:
https://github.com/sagebind/isahc/issues/86#issuecomment-535740398

The developer explains why it won't work with `actix-web` handlers:
https://github.com/sagebind/isahc/issues/86#issuecomment-536072319
`client.send_async()` returns a future that borrows `client`. The future outlives the handler scope, hence the error. I'm not sure how to `move` the client out of the handler and into the future.

**Comment by fafhrd91** [comment]
this is outside of actix-web scope. simple solution, just use awc or reqwest

**Comment by kathampy** [comment]
I’m using `isahc` because it allows every option like connection timeout, SSL trust, etc. to be set per request. I’m writing a benchmarking tool and I need to set these per request. Creating a new client with different options has a huge performance hit.

It will be great if you can consider moving all the options in `awc` to the request level, and only fall back to the client settings as defaults.

**Comment by fafhrd91** [comment]
Submit pr. I don’t have time for this and for my work this features are not required
