### ISSUE TITLE
Allow for disabling HTTP1/HTTP2

### ISSUE THREAD

**Issue by svenstaro** [actix/actix-web#1107]
I've already talked to @fafhrd91 about this in gitter. I want to conditionally disable HTTP1 or HTTP2 while keeping both of them enabled by default.

So despite this being a feature request, I've already been taking a stab at this but I'm not sure my Rust generics skills are up to par.

Currently, my approach looks like this:

```rust
    // src/server.rs
    
    pub enum EnabledProtocol {
        H1,
        H2,
        All,
    }

    pub fn listen(mut self, lst: net::TcpListener) -> io::Result<Self> {
        let cfg = self.config.clone();
        let factory = self.factory.clone();
        let addr = lst.local_addr().unwrap();
        self.sockets.push(Socket {
            addr,
            scheme: "http",
        });

        self.builder = self.builder.listen(
            format!("actix-web-service-{}", addr),
            lst,
            move || {
                let c = cfg.lock();
                let http_service = HttpService::build()
                    .keep_alive(c.keep_alive)
                    .client_timeout(c.client_timeout);
                match c.enabled_protocols {
                    EnabledProtocol::H1 => http_service.h1(factory()),
                    EnabledProtocol::H2 => http_service.h2(factory()),
                    EnabledProtocol::All => http_service.finish(factory()),
                }
            },
        )?;
        Ok(self)
    }
```

And I think from that point, I should try to cast the `http_service` into trait objects which satisfy `F: ServiceFactory<TcpStream>` (from `actix-server/src/builder.rs`).

Can anyone tell me whether this is a workable approach?

**Comment by pythoneer** [comment]
Implementing HTTP/3 would cause a breaking change on the `EnabledProtocol` enum, right?

**Comment by svenstaro** [comment]
Yes, but this seems unlikely to affect user code. Since users can't directly access the `enabled_protocols` in their code as it's write-only via the setter, they wouldn't `match` over it.

**Comment by fafhrd91** [comment]
you need `Either` service, but it would add extra match to hot path

**Comment by fafhrd91** [comment]
I am not sure we need this change, especially on hot path

**Comment by svenstaro** [comment]
My use case is special reverse proxies and debugging HTTP logger/web servers. I'd love to do this in actix-web. Are you sure the performance hit would be too terrible? I'm thinking this would likely not be too bad as it's just one conditional when it comes down to it. I think we're still not on the level of fast where single conditionals matter.

**Comment by fafhrd91** [comment]
Performance would not be big problem, I don’t like changes that implies penalty for most use cases and gives flexibility to very small use cases

**Comment by fafhrd91** [comment]
Also it is still possible to limit protocol with manual configuration

**Comment by svenstaro** [comment]
Is there a chance you could hack up a snippet how to manually configure the
connection to disable http2? In that case, I'd throw together a full
example. I tried this before but failed.

**Comment by fafhrd91** [comment]
some tests use manual config

https://github.com/actix/actix-web/blob/master/tests/test_server.rs#L65
use actix_server::Server instead of TestServer

actix_web::Server is just a wrapper, https://github.com/actix/actix-web/blob/master/src/server.rs#L243
