### ISSUE TITLE
Make actix_http::...::ContentDisposition public

### ISSUE THREAD

**Issue by zacps** [actix/actix-web#1109]
In actix-multipart there is a method to get the content-disposition header of the request, `actix_multipart::Field.content_disposition`.

However, this returns a private type (I didn't think this was allowed).

The full path is `actix_http::header::common::content_disopsition::ContentDisposition`

Motivation: To be able to identify, and parse, regular form fields differently from files.

**Comment by fafhrd91** [comment]
Content disposition is public https://docs.rs/actix-web/1.0.8/actix_web/http/header/struct.ContentDisposition.html

**Comment by zacps** [comment]
Can the docs in [acitx-multipart](https://docs.rs/actix-multipart/0.1.4/actix_multipart/struct.Field.html#method.content_disposition) be updated to show the public type?

That's why I thought it was private.

**Comment by fafhrd91** [comment]
`cargo doc` creates docs. I don’t know how to fix its output

**Comment by zacps** [comment]
You should be able to fix it by importing and returning the public type in actix-multipart.

actix-multipart already depends on actix web so I don't see any reason this can't be done.

**Comment by fafhrd91** [comment]
would you provide Pr? I don’t use multipart
