### ISSUE TITLE
NamedFile can only be returned from a GET request

### ISSUE THREAD

**Issue by swilcox3** [actix/actix-web#1113]
I've got a route that returns a NamedFile, and it works fine with GET requests.  But now I need to update some database state before I return the file, so I need a POST request.  But when I change my route to POST, I get a 405 error from actix_web with a body "This resource only supports GET and HEAD."  
I've traced the execution through my handler function up until I return the opened NamedFile to actix, so I know it's actually getting into my code and we're successfully opening the file handle.
Is it a requirement to only use NamedFile with GET?

**Comment by fafhrd91** [comment]
At the moment yes. It could be configurable. Pr is welcomed.
