### ISSUE TITLE
Failed to compile the hello-world example on  windows 10 using gcc

### ISSUE THREAD

**Issue by yy2428** [actix/actix-web#1124]
Hello,

I just got  started to learn actix, but have failed to compile the hello-world example. I am using rustc 1.38.0 (625451e37 2019-09-23);  gcc (Rev2, Built by MSYS2 project) 9.2.0;  windows 10.

The error message:

```
error: linking with `gcc` failed: exit code: 1
 |
 = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\User....
.........
 = note: D:\learning\rust\actix\hello-world\target\debug\deps\libbrotli_sys-0617787f4c953a93.rlib(metablock.o): In function `BrotliBuildMetaBlock':
          /cygdrive/c/Users/light/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-sys-0.3.2/brotli/enc/metablock.c:80: undefined reference to `__assert_func'
...   ..
```

There are  many "undefined reference to" `__errno`  and `__assert_func` errors.
The problem seems to be caused by the "-nostdlib" option in the gcc command.

Is there any way to solve or get around this issue?  Thanks a lot!

**Comment by JohnTitor** [comment]
It seems a linking issue and maybe doesn't seem to be related to Actix directly.
If you are in a hurry, you can try with MSVC. It works well on my local.

**Comment by yy2428** [comment]
Thank you for your reply so fast.  I want to build a web site using actix web.  The site will  be hosted on Linux, so gcc  will  be  used.  Since windows provides a  more convenient development environment for me , so I prefer to develop the code on windows using gcc.  If necessary, I can use virtualbox to code on linux.  But I  wonder if  the gcc issues will be there  too.  Any success on  linux?

**Comment by JohnTitor** [comment]
I guess the problem is on Windows (or related tools, environment) side. On Linux, the code should work well.

**Comment by fafhrd91** [comment]
I don't see this issue as actix-web's issue. you can disable compression support by disabling `brotli` and flate features. and you can file issue to upstream (brotli2) crate
