### ISSUE TITLE
how to get the raw request body

### ISSUE THREAD

**Issue by zhaobingss** [actix/actix-web#1127]
**how to get the raw request body ? please.**

![image](https://user-images.githubusercontent.com/14836112/66546135-e86e8d80-eb6e-11e9-9fc0-87f03e0a475a.png)
```
pub fn get_rate(req: HttpRequest) -> impl Responder {
    println!("{}", req.path());
    println!("{}", req.query_string());

    let bts = web::Bytes::extract(&req).wait().unwrap();
    println!("bytes：{:?}", bts);// got nothing

    JSONResult::new("get rate")
}
```

**Comment by HiruNya** [comment]
The only way I've found is to turn the ``Bytes`` into a ``String`` using ``String::from_utf8``.

Like this:
```rust
use actix_web::{App, HttpResponse, HttpServer, web::{Bytes, post}};

fn handler(bytes: Bytes) -> Result<String, HttpResponse> {
    match String::from_utf8(bytes.to_vec()) {
        Ok(text) => Ok(format!("Hello, {}!\n", text)),
        Err(_) => Err(HttpResponse::BadRequest().into())
    }
}

fn main() {
    HttpServer::new(||{
        App::new().route("/name", post().to(handler))
    }).bind("127.0.0.1:8080")
        .unwrap()
        .run()
        .unwrap();
}
```
Using ``curl``, I get this:
```shell
> curl 127.0.0.1:8080/name -X POST -d "HiruNya"
Hello, HiruNya!
```

The problem with this is that data is copied when ``to_vec`` is used, but I don't see any way around it.

**Comment by zhaobingss** [comment]
but how to get the query string，is  there any way to get the query string and rquest body together.
@HiruNya ,tks.

**Comment by HiruNya** [comment]
You put the [``Query``](https://docs.rs/actix-web/1.0.8/actix_web/web/struct.Query.html) struct next to the ``bytes`` parameter as a function argument, like this:
```rust
use actix_web::{App, HttpResponse, HttpServer, web::{Bytes, post, Query}};
use serde::Deserialize;

#[derive(Deserialize)]
pub struct Person {
    age: u8,
    id: u32,
}

fn handler(bytes: Bytes, query: Query<Person>) -> Result<String, HttpResponse> {
    let name = String::from_utf8(bytes.to_vec()).map_err(|_| HttpResponse::BadRequest().finish())?;
    Ok(format!("Hello, {}!\nYou are user #{} and are {} years old.\n", name, query.id, query.age))
}

fn main() {
    HttpServer::new(||{
        App::new().route("/name", post().to(handler))
    }).bind("127.0.0.1:8080")
        .unwrap()
        .run()
        .unwrap();
}
```
In CURL this gives me:
```
> curl "127.0.0.1:8080/name?age=18&id=2" -X POST -d "HiruNya"
Hello, HiruNya!
You are user #2 and are 18 years old.
```

**Comment by fafhrd91** [comment]
issue tracker is not good place to ask questions. better to use chat

**Comment by tqwewe** [comment]
@HiruNya 
> The problem with this is that data is copied when to_vec is used, but I don't see any way around it.

Can't you just do `String::from_utf8(&bytes)` to solve this?

**Comment by HiruNya** [comment]
@Acidic9 
> @HiruNya
> 
> > The problem with this is that data is copied when to_vec is used, but I don't see any way around it.
> 
> Can't you just do `String::from_utf8(&bytes)` to solve this?

`String:from_utf8` takes in a `Vec<u8>` so `&bytes` needs to be a `Vec<u8>`. But looking at the documentation, `&bytes` produces a `&[u8]` instead. So I'm not sure that'd work unfortunately. Would've been cool if it did though.

Disclaimer: This was like 2 years ago and `actix-web` has gone through breaking changes since then and I haven't used `actix-web` for a long time now so my memory is probably not as relevant these days.

[https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8)

**Comment by robjtede** [comment]
`str::from_utf8` takes `&[u8]`
https://doc.rust-lang.org/1.50.0/alloc/str/fn.from_utf8.html

**Comment by HiruNya** [comment]
> `str::from_utf8` takes `&[u8]`
> https://doc.rust-lang.org/1.50.0/alloc/str/fn.from_utf8.html

You're absolutely right and that'd probably be the way to go!
