### ISSUE TITLE
Slash needed when accessing a folder

### ISSUE THREAD

**Issue by robertohuertasm** [actix/actix-web#1132]
Related to #661 and probably #241 

Given this service:
```rust
.service(
            Files::new("/", "./www")
                .index_file("index.html")
                .show_files_listing()
                .default_handler(web::to(|| {
                    NamedFile::open("./www/404.html")
                        .and_then(|x| Ok(x.set_status_code(StatusCode::NOT_FOUND)))
                })),
)
```

Whenever I browse to `localhost:3000/beta`, which has an `index.html` in it, I get the html but all the referenced `.css` files and images are retrieved as if the file was being served from the `root`, that is, `localhost:3000/`, and hence, not being retrieved at all.

 If I put a final slash in the path `localhost:3000/beta/` everything works ok.

I think maybe `actix-web` should insert a final slash whenever it detects that we're dealing with a folder so we could fix this issue.

**Comment by fafhrd91** [comment]
I don't think inserting slash is good idea. it might be configurable option for `Files` but that is it

**Comment by robertohuertasm** [comment]
Fair enough. Now, looking a little bit into the code and the issue I realize that it's not a matter of inserting a slash as this happens in the client. The first request is good but all the internal references are wrong. I can only think of creating a middleware that does a redirect to a url with final slash if needed. Would that be a valid approach? Do you have any other suggestions to fix this issue?

**Comment by fafhrd91** [comment]
Redirect is good approach and you can redirect in default handler

**Comment by robertohuertasm** [comment]
The middleware approach works ok. If you think it's a good approach I could upload it to the middleware collection or maybe try to add this behavior into the `Files` crate.
