### ISSUE TITLE
 actix_web::web::Query docs are missing error handling examples

### ISSUE THREAD

**Issue by plaes** [actix/actix-web#1137]
Currently, documentation samples (at least for `impl<T> FromRequest for Query<T>`) is missing error handling example:
    1) It should either link to `actix_web::web::QueryConfig`
    2) or document an alternative way how to parse the query string yourself (there seems to be no easy way of extracting it from `HttpRequest`)

**Comment by fafhrd91** [comment]
could anyone provide PR?
