### ISSUE TITLE
Modify HTTP handlers on running server

### ISSUE THREAD

**Issue by CodeSandwich** [actix/actix-web#1138]
# What I need
I'm writing a server which changes exposed API on runtime. On startup it only has 1 simple route (`/status`) but when it loads all its resources, the simple route is replaced with full set of routes (`/status` with way more stats and `/res`). The `State` data changes as well.

# What I can do now
I've found two solutions, but none is really good:
- Stop the whole `Server` and start new instance with another `App`, but same config (cons: short downtime)
- 1. Pass mutable shared enum with different variants of context into `State`
  1. check `State` enum variant inside every handler and reject the request with 404 if it's not possible to handle yet
  1. Change the enum variant when resources are loaded
  1. (cons: infects all handlers with `if/else` boilerplate)

# What I wish for
I wish it was possible to somehow change handlers on a running server with no downtime. E.g.
- Prepare completely new `App` with new `State` and replace the running one with it
- Add the new handler and then remove the old one using some ID (very elastic, maybe could be used in other cases)

**Comment by fafhrd91** [comment]
Runtime modification of routing table is not supported but you can write http service and handle routes however you want
