### ISSUE TITLE
Clarifications on id.forget

### ISSUE THREAD

**Issue by sabahtalateh** [actix/actix-web#1140]
Hi everyone) Can you guys help me to clarify the behaviour of the actix-identity ```id.forget``` method? I followed through the https://gill.net.in/posts/auth-microservice-rust-actix-web1.0-diesel-complete-tutorial/. When I call logout http endpoint that in turn call ```id.forget``` and then try to get information about the currently logged in user with the cookie that was previously got from the login method then I still can get the user information, however user just was logged out with ```id.forget```. Is it expected behaviour? Should the client be responsible for cookie management? Thanks

**Comment by fafhrd91** [comment]
you should inspect cookie that user gets. it should get cookie expire settings

**Comment by sabahtalateh** [comment]
@fafhrd91 it has cookie expire settings in the response.  I mean is it correct that I still can get the user information when passed the cookie that was 'forgotten'?

**Comment by fafhrd91** [comment]
I don’t remember. Check source code, it is simple
