### ISSUE TITLE
Social Authentication in Actix

### ISSUE THREAD

**Issue by mugoh** [actix/actix-web#1145]
##### Social Media Authentication in actix?
Given a situation that considers the use of **OAuth** in actix-web for user authentication, would this be achievable? And what might be the scope of getting it done?

**Comment by JohnTitor** [comment]
It's possible to use awc. There is the snippet in #679, it might help you.

**Comment by hogum** [comment]
> It's possible to use awc. There is the snippet in #679, it might help you.

:+1:
