### ISSUE TITLE
When is `web::block()` justified?

### ISSUE THREAD

**Issue by kathampy** [actix/actix-web#1146]
My handler extracts a POST body with `actix-protobuf` and uses the values to build a `http::Request`. This includes creating a `Uri` and parsing a few `SocketAddr`s from a `Vec<String>`.

Are those last two operations CPU intensive enough to justify moving them to a `web::block()`, or is it not worth the thread switching cost? I see that the handler does encoding / decoding in `web::block()`s, but those are much heavier operations. The goal is to have a C10k capable server.

**Comment by fafhrd91** [comment]
depends on amount if socket addrs, if you have only few then overhead would be higher, otherwise you need to measure.
