### ISSUE TITLE
please cheke the issues

### ISSUE THREAD

**Issue by sheiy** [actix/actix-web#1148]
https://github.com/google/brotli/issues/778

could you change the brotli-sys  to other version?

**Comment by fafhrd91** [comment]
You should file bug report for brotli2 https://github.com/alexcrichton/brotli2-rs/tree/master/brotli-sys

**Comment by sheiy** [comment]
I think brotli2 is an old lib, the last commit is 2 years ago
use another lib to replace it?

**Comment by sheiy** [comment]
thanks for your reply
I'm a newer for rust ; Is there have a way to iterate a mod ?
````rust
mod service;
let app = App::new();
for rs in service{
for func in rs{
//if func is public 
app.service(func)
}
}
````

**Comment by fafhrd91** [comment]
I don’t know any other viable brotli library. Other question is for chat and not for issue
