### ISSUE TITLE
actix-http-test: Connect(Timeout)

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#1149]
I randomly (maybe one time per 20) get `Connect(Timeout)` error in my tests where I use `actix_http_test::TestServer`, and when I block on a request like this:

```
        let req = srv.get("/api/v1/load").send();
        let mut response = srv.block_on(req).unwrap();
```
It's that last line that gives the error. The endpoints themselves should not take a long time, they are quite light.

**Comment by Ploppz** [comment]
I see in the code that the timeout is set to 500ms. But I timed the handler that timed out, and it took 35ms. So I wonder whether the actix-web (test) framework is slow (in debug mode), which I doubt. But another possibility is that when you have a lot of tests running in parallel sending many requests to different TestServers, they might all get slowed waiting for IO? Is that possible? The timeout should probably be increased in any case.

**Comment by leizzer** [comment]
I noticed you submited changes that were merged.
Can we close this?

**Comment by Ploppz** [comment]
Yes :)
