### ISSUE TITLE
How to read more than 64k from payload?

### ISSUE THREAD

**Issue by sabahtalateh** [actix/actix-web#1150]
Hi everyone) How is it going?
I wonder how to read more than 64k from payload. 
```rust
let fut = payload.fold(BytesMut::new(), |mut body, chunk| {
        dbg!(body.len());
        body.extend_from_slice(&chunk);
        Ok::<_, PayloadError>(body)
    });
    dbg!(fut.wait());
```

When using such code it stucks when `body.len()`  becomes equal to 65535 bytes
I noticed from here https://github.com/actix/actix-web/issues/499 that actix read buffer size is 64k.. So is it a way to clear that buffer when it full.. I am not a PRO with all these buffers so maybe it is a silly question)
Or maybe there is some other way to read content that is larger than 64k?
Thanks

**Comment by fafhrd91** [comment]
this should work. #499 is about different buffer. you dont need to manage it.

could you create runnable example, i'll check

**Comment by sabahtalateh** [comment]
@fafhrd91 Looks like it was my misunderstanding. When return future from request handler like below 
```rust
body.map_err(Error::from)
        .fold(web::BytesMut::new(), move |mut body, chunk| {
            body.extend_from_slice(&chunk);
            Ok::<_, Error>(body)
        })
        .and_then(|body| {
            let len = body.len();
            dbg!(body);
            Ok(HttpResponse::Ok().body(format!("{} bytes read", len)))
        })
```
and not call `.wait()` on it, then it works on payloads of any size
