### ISSUE TITLE
NormalizePath no longer handles appending forward slashes to the path.

### ISSUE THREAD

**Issue by hubbabubbagump** [actix/actix-web#1152]
In the actix.rs documentation, normalizing a path is describe as adding a trailing slash and merging multiple slashes into one. The older version of [NormalizePath](https://docs.rs/actix-web/0.3.3/actix_web/struct.NormalizePath.html) did the former through setting the `append` parameter to true.

The current version of NormalizePath only performs the forward slash merging at the moment. Is this the expected behavior or should NormalizePath be modified to follow the old version?

**Comment by fafhrd91** [comment]
dup #959
