### ISSUE TITLE
1.0.9 release

### ISSUE THREAD

**Issue by popzxc** [actix/actix-web#1161]
Hello!

[We](https://github.com/exonum/exonum)'re waiting for the `actix-web` release 1.0.9 (which will include changes introduced by https://github.com/actix/actix-web/pull/1110), since it contains crucial feature that stops us from updating to actix 1.0 (actually we also wait for `actix-web-actors` which will use `actix-web` 1.0.9 by default, but it can be overriden via `cargo patch` and thus not critical).

Can you please clarify when approximately the release is going to happen so we can adjust our plans?

Thanks!

**Comment by fafhrd91** [comment]
1.0.9 is released. you should tell me next time that you need release.

**Comment by popzxc** [comment]
Thanks!
