### ISSUE TITLE
How to disable compression in 0.7.9？

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#1165]
I would like to debug an error, I'm not sure if it's the compression of actix-web doesn't work well, but I didn't find a way to disable it.

Is there a way to disable it?

**Comment by 0x8f701** [comment]
Anyone can help on this?

**Comment by fafhrd91** [comment]
disable flate features

**Comment by 0x8f701** [comment]
Hello @fafhrd91 , I did this but it's still compressed, am I doing anything wrong?

```
actix-web = { version = "0.7.19", default-features = false, features = ["cell", "ssl", "session"] }
```

**Comment by fafhrd91** [comment]
I think you can set default encoding on app level, check api doc. 0.7 is very old

**Comment by 0x8f701** [comment]
Thanks yes I found it.
