### ISSUE TITLE
actix-session Session canot be used in async function

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#1169]
Session and CookieSession middleware cannot be used in async handlers as Rc and RefCell are used to manage the inner states.

Any workaround without reimplementing the functionality using mutex?

**Comment by fafhrd91** [comment]
Actix uses single threaded runtime and does not require `Send`

**Comment by ghost** [comment]
Thanks, it was the future compatible layer instead of using boxed() (which requires Send) I had to use boxed_local.

**Comment by fafhrd91** [comment]
alpha.1 is released, it is based on std::future
