### ISSUE TITLE
Can't use actix-web-actors with actix-web `2.0.0-alpha.1`

### ISSUE THREAD

**Issue by flaper87** [actix/actix-web#1174]
I wanted to test the latest `actix-web` alpha release to use async/await but I'm not able to get it to work with the currently released `actix-web-actors` as the latter depends on `actix-web = 1.0.9`.

Is this a supported scenario? How can I test websockets with async?

**Comment by fafhrd91** [comment]
actix-web-actors depends on actix, actix is not ported to std::future

**Comment by flaper87** [comment]
a-ha, I knew I was missing something. thanks for the heads up 😊
