### ISSUE TITLE
documentation on docs.rs is broken

### ISSUE THREAD

**Issue by miquels** [actix/actix-web#1175]
The main website on https://actix.rs/ has a link to to docs at https://docs.rs/actix-web/. Those are the docs of of 2.0-alpha.1, but they failed to build ([see error here](https://docs.rs/crate/actix-web/2.0.0-alpha.1/builds/200340)].

If that can't be fixed right away, perhaps link to https://actix.rs/actix-web/actix_web/index.html instead, at least in the mean time?

**Comment by JohnTitor** [comment]
The reason is that 512dd2be636ba796ab8e345319e330902449088d doesn't disable `rustls` feature completely.

@fafhrd91: On master, it seems we revived `rustls` feature with 4dc31aac93977572f062a43e5a38c23160ea2d5d, this is intended?

**Comment by fafhrd91** [comment]
tokio-rustls depends on tokio 0.2, which is not compatible with actix

**Comment by krircc** [comment]
There is [async-tls](https://github.com/async-rs/async-tls) base on futures

**Comment by fafhrd91** [comment]
@krircc stop spamming, async-std is not compatible at all.

**Comment by krircc** [comment]
@fafhrd91 Sorry, the [async-tls](https://github.com/async-rs/async-tls) not use async-std, I only think may help.

**Comment by JohnTitor** [comment]
2.0.0-alpha.2 has been released and the issue has been fixed. Closing this issue.
