### ISSUE TITLE
"failed to link or copy" error on auto-reload

### ISSUE THREAD

**Issue by art-in** [actix/actix-web#1180]
I'm using vs-code with docker dev container (win10 host, ubuntu base).

Minimal server code and auto-reload configuration, the same as [described in docs](https://actix.rs/docs/autoreload/).

Error:

```
root@c9b37cc3dfac:/workspaces/cookbook.git/rust# systemfd --no-pid -s http::0.0.0.0:8080 -- cargo watch -x run
~> socket http://0.0.0.0:8080/
[Running 'cargo run']
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
     Running `target/debug/server`
Listening on 0.0.0.0:8080
[Running 'cargo run']
   Compiling server v0.1.0 (/workspaces/cookbook.git/rust/server)
error: failed to link or copy `/workspaces/cookbook.git/rust/target/debug/deps/server-13f372ec3379c813` to `/workspaces/cookbook.git/rust/target/debug/server`

Caused by:
  No such file or directory (os error 2)
[Finished running. Exit status: 101]
```

So there can be series of successful reloads, and then sudden fail.

Probably this is not issue of `actix-web`, but `cargo` or `cargo watch` or `vscode remote`... I have no idea.

rust v1.39.0  
actix-web v1.0.9
vscode v1.40.2  
vscode-remote-extensionpack v0.17.0

**Comment by leizzer** [comment]
I recently set up a Rails/React project in Win10 with WSL2 and had a similar issue.

Try the hacks listed here and see if that helps.
https://github.com/shayne/wsl2-hacks/blob/master/README.md

```Increase max_user_watches

If devtools are watching for file changes, the default is too low.

# /etc/rc.local runs as root by default
# if you run these yourself add 'sudo' to the beginning of each command

sysctl -w fs.inotify.max_user_watches=524288
```

**Comment by leizzer** [comment]
Also, if you are using WSL2, move your project to linux's tree directory and don't use the project from the mounted Windows drive.

@art-in please let me know if I can close this ticket

**Comment by art-in** [comment]
@leizzer you can safely close the tick since we both sure it is not issue of `actix`.  
after all whole idea of this issue is to be an anchor for ppl running into same error.

I'll make some investigation and get back as soon as I have any fix.
