### ISSUE TITLE
[Feature]Adding webdav support

### ISSUE THREAD

**Issue by sidju** [actix/actix-web#1183]
Considering [the HTTP crate electing not to include webDAV support,](https://github.com/hyperium/http/issues/346) would you be interested in implementing webDAV in actix-http as a feature using [webdav-handler](https://crates.io/crates/webdav-handler)?

(I am considering starting writing a simple replacement of nextcloud (since it keeps bugging out on me) with calDAV and cardDAV, and would love to do that in actix.)

**Comment by fafhrd91** [comment]
is it really needed to change actix-http? as I understand webdav can be handled on application level.

**Comment by sidju** [comment]
It is possible (although the example has been removed), but it would be nice to have abstractions through actix-web to make it less painful.

As you can see here https://github.com/miquels/webdav-handler-rs/blob/47181aa697136ac88c56102f9f12daf6db0c3c13/examples/actix-web.rs there are a lot of conversions back and forth that I expect could be better handled in backend.

But perhaps writing a separate crate for dav would be better, using actix from the ground up?

**Comment by fafhrd91** [comment]
this example is for actix-web 0.7

could you show me changes that are needed to make it more ergonomic? at the moment this is very abstract.

**Comment by sidju** [comment]
To be honest, the more I read the more it seems that the library needs adjustments. Up to date documentation and a wrapper to handle the conversions from and to actix is really what I am missing, but that should be placed in the library itself or a separate crate.

**Comment by sidju** [comment]
I am closing this and I will write up a new guide somewhere and link it in a subsequent comment (as well as trying to get webdav-handler to add it to the documentation).
