### ISSUE TITLE
Identity middleware should also give access to request

### ISSUE THREAD

**Issue by xrl** [actix/actix-web#1184]
I am writing some code which needs to pull out URL match info _and_ I need to check that a user is logged in.

I have a handler like this:

```
pub fn cronjobs_trigger(r: HttpRequest) -> Result<impl Responder, DatascienceWebError> {
    
    match r.match_info().get("name") {
[[[ SNIP ]]]
```

but how can I also get the `Identity` parameter? I understand the identity middleware is wrapping these service handler calls, and that based on the signature of the handler it either provides the request or the identity. But how do I get both?

**Comment by fafhrd91** [comment]
1. idenity policy has access to request https://docs.rs/actix-identity/0.2.0-alpha.1/actix_identity/trait.IdentityPolicy.html
2. https://docs.rs/actix-identity/0.2.0-alpha.1/actix_identity/struct.Identity.html
