### ISSUE TITLE
CSRF middleware for actix-web 1.0

### ISSUE THREAD

**Issue by tommket** [actix/actix-web#1185]
Where is the CSRF middleware for actix-web 1.0?

**Comment by fafhrd91** [comment]
It wasn’t ported.

**Comment by tommket** [comment]
Is there any chance of https://github.com/SnoozeTime/actix-csrf getting some more support?

**Comment by 0xpr03** [comment]
@tommket what do you mean with support ? You can ask the author https://github.com/SnoozeTime if you're missing any features.

**Comment by tommket** [comment]
@0xpr03 I mean if it could become one of the other actix-... crates the same way the other middleware crates got created and continually maintained?
There is an open issue https://github.com/SnoozeTime/actix-csrf/issues/1 where the author recently stated that he is waiting for someone sufficiently knowledgeable in actix and rust to review his code, before he is willing to release it as a crate. So pls anyone contributing to actix-... code and willing to review it would be welcome.

**Comment by 0xpr03** [comment]
Just as a note: I'm using the SameSite attribute as CSRF prevention.

**Comment by tommket** [comment]
@0xpr03 Yes I read about that too, but that does not help with subdomains.

**Comment by fafhrd91** [comment]
i guess there is nothing to do in actix-web repo

**Comment by 0xpr03** [comment]
@tommket I'd recommend to ask in the actix Gitter chat and see if you'll find some people to help you with this project.

**Comment by Deprecatedoldaccount321** [comment]
Does anyone know why it was removed?

**Comment by yoozzeek** [comment]
If somebody is looking for CSRF implementation for Actix web that supports synchronizer token (statefull) and double-submit cookie (stateless powered by HMACs) patterns, check this crate: https://github.com/yoozzeek/actix-csrf-middleware

Not audited, may contain bugs/security issues. If some Rust/Actix/Sec pros could make 10min review and a GH issue that would help a lot. I fix fast and want to stabilize the crate.

Maybe one day it lands in actix-web core, but it uses actix-session (optional feature) for synchronizer-token logic; so it's probably not suitable PR for core.
