### ISSUE TITLE
Unable to change tokio runtime, preventing migration to a newer version of actix-web

### ISSUE THREAD

**Issue by jannickj** [actix/actix-web#1186]
We have an API which does calls to S3 using rusoto, rusoto currently uses the older version of *hyper*. This older version of hyper breaks on the newer version of Tokio 0.2. However a compatibility layer for Tokio 0.1/0.2 exists: https://github.com/tokio-rs/tokio-compat, which works great. However because actix-web doesn't allow me to set the Tokio runtime myself, I am unable to migrate to the newer version.

Am I missing something or is there an option somewhere?

**Comment by fafhrd91** [comment]
alpha.3 https://docs.rs/actix-rt/1.0.0-alpha.3/actix_rt/struct.System.html#method.run_in_tokio

stable https://docs.rs/actix-rt/0.2.6/actix_rt/struct.System.html#method.run_in_executor
