### ISSUE TITLE
Support functions returning an App or similar trait

### ISSUE THREAD

**Issue by robo-corg** [actix/actix-web#1190]
To support testing the same app it would be nice if there was a way to return an App or an HttpService from a function.

It doesn't seem possible in either stable 1.0.9 or what is in master to make a function that returns an App since AppEntry doesn't seem to get forwarded publicly anywhere. I think it might be possible if App::new() is called and then passed in but the problem remains the bounds on the impl for App is fairly complicated and seems to rely on traits that are not re-exported in actix-web::dev or anywhere else.

I suspect this might also partially be a documentation issue? If there is a way I can open a PR to update the docs (assuming someone points me in the right direction).

**Comment by fafhrd91** [comment]
Even if AppEntry would be in dev any new middleware would change type of app

**Comment by bitemyapp** [comment]
@fafhrd91 I spoke up in another issue about this. I'll reply to your answer which says:

>Even if AppEntry would be in dev any new middleware would change type of app

I am fine with that. I just want to be able to centralize creation of the `App` in a function so I'm not copying and pasting App initialization code in all of my test functions. The latter is more costly than the App type changing because it only gets mentioned in one place.

Am I doing something wrong? How should I write tests that talk to my Actix app? The first few lines of every test function look like this:

```rust
#[test]
pub fn test_creates_two_log_messages() {
    let conf = config::get_env();
    let conf_copy = conf.clone();
    let oauth_context = auth::initialize_context(&conf_copy);
    let dbexec = config::make_app_state(conf.db);
    let mut app = test::init_service(
        App::new()
            .data(AppState { db: dbexec.clone(), oauth_context: oauth_context.clone(), })
            .configure(router::config_app),
    );
```

The only work-around that has occurred to me is having a single function with `#[test]` and invoking sub-tests with `App` as a parameter.

**Comment by fafhrd91** [comment]
you can use impl Trait,

```rust

fn create_app() -> impl ServiceFactory<
        Config = (),
        Request = Request,
        Response = ServiceResponse<impl MessageBody>,
        Error = impl std::fmt::Debug,
    > {
}
```

**Comment by bitemyapp** [comment]
@fafhrd91 Thank you for the help! I think I'm on the right track with your suggestion but it's a little tricky to get right. I was passing the app to `test::init_service` so I think I have a `Service` rather than a `ServiceFactory`. Here's what I have so far:

```rust
fn create_test_app() -> (
    db::DbExecutor,
    impl Service<
        Request = Request,
        Response = ServiceResponse<impl MessageBody>,
        Error = impl std::fmt::Debug,
    >,
) {
```

~~It's currently complaining that I'm not allowed to import `actix_http::request::Request` but that's what it wants me to provide in the `impl Service` arguments I believe. Is it the case that `impl ServiceFactory` is intended to work but `impl Service` is not? Or am I just fumbling around here?~~

I needed to change my import to `use actix_http::Request;` instead of `use actix_http::request::Request;` I'm all good now, worked beautifully, thank you @fafhrd91! :champagne:

**Comment by robo-corg** [comment]
Thanks for the help. I hit that problem and ended up something like this:

```
pub fn with_app<'a, T, B>(
    config: config::Config,
    app: App<T, B>,
) -> App<
    impl NewService<
            Config = (),
            Request = ServiceRequest,
            Response = ServiceResponse<B>,
            Error = actix_web::Error,
            InitError = (),
        > + 'a,
    B,
>
where
    B: MessageBody + 'static,
    T: NewService<
            Config = (),
            Request = ServiceRequest,
            Response = ServiceResponse<B>,
            Error = actix_web::Error,
            InitError = (),
        > + 'static,
{
...
}
```

Those impl traits look much nicer!

**Comment by fafhrd91** [comment]
@robo-corg I think you can replace `T` and `B` with impls. I don't think you need `'a` lifetime

**Comment by Dowwie** [comment]
Leaving this here for when these folks return once their App factory pattern stops working following their migration to actix-web 2.0.  The following pattern works.  return the call to init_service, as illustrated.
```rust
pub fn create_test_app() 
    -> impl Future<Output=impl Service<Request = Request, 
                                       Response = ServiceResponse<impl MessageBody>,
                                       Error = AWError>>
{
...
    test::init_service(
         App::new()
             ...
    )
}
```

**Comment by adwhit** [comment]
Even more copy-pastable:
```rust
use my_server::configure_app;

use actix_http::Request;
use actix_web::http::StatusCode;
use actix_web::{dev as ax_dev, dev::Service as _, test, App, Error as AxError};

pub async fn test_app() -> impl ax_dev::Service<
    Request = Request,
    Response = ax_dev::ServiceResponse<impl ax_dev::MessageBody>,
    Error = AxError,
> {
    test::init_service(App::new().configure(configure_app)).await
}

#[actix_rt::test]
async fn my_test() {
    let req = test::TestRequest::get().uri("/my_endpoint").to_request();
    let resp = test_app().await.call(req).await.unwrap();
    assert_eq!(resp.status(), StatusCode::OK);
}
```

**Comment by wontheone1** [comment]
@adwhit Tried your code but didn't work because 
```
error[E0432]: unresolved import `actix_http`
  --> src/main.rs:58:9
   |
58 |     use actix_http::Request;
   |         ^^^^^^^^^^ use of undeclared type or module `actix_http`
```

or if I use `use actix_http::request::Request;` (including `actix_http` dependency)

then I get 
![Screen Shot 2020-05-23 at 17 19 53](https://user-images.githubusercontent.com/11784756/82733081-209b9880-9d1a-11ea-9eaf-188059f9d063.png)

**Comment by adwhit** [comment]
@wontheone1 try it as shown i.e.
```
use actix_http::Request;
```

**Comment by santiagomed** [comment]
The proposed code snippets seem to be out-of-date since they are not working for me. Does anyone know how to do this currently?

**Comment by robjtede** [comment]
```rust
pub fn my_app() -> App<
    impl ServiceFactory<
        ServiceRequest,
        Response = ServiceResponse<impl MessageBody>,
        Config = (),
        InitError = (),
        Error = Error,
    >,
> {
    App::new()
        // e.g. logger can be removed without affecting the return type
        .wrap(crate::middleware::Logger::default())
        .route("/", web::to(|| async { "hello" }))
}

let _ = init_service(my_app());
```

taken from https://github.com/actix/actix-web/blob/b1c85ba85be91b5ea34f31264853b411fadce1ef/actix-web/src/app.rs#L698

**Comment by santiagomed** [comment]
@robjtede Thanks for the reply! I tried this and get the following compiler error:

```rust
error[E0107]: this trait takes 0 generic arguments but 1 generic argument was supplied
   --> server/src/handlers/account_handlers.rs:264:14
    |
264 |           impl ServiceFactory<
    |  ______________^^^^^^^^^^^^^^-
    | |              |
    | |              expected 0 generic arguments
265 | |             ServiceRequest,
266 | |             Response = ServiceResponse<impl MessageBody>,
267 | |             Config = (),
268 | |             InitError = (),
269 | |             Error = Error,
270 | |         >,
    | |_________- help: remove these generics
    |
note: trait defined here, with 0 generic parameters
   --> /Users/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/lib.rs:155:11
    |
155 | pub trait ServiceFactory {
    |           ^^^^^^^^^^^^^^
```

Am I missing something? Removing the generics just gives me another compiler error.

**Comment by robjtede** [comment]
The example only works on the latest v4.x versions.

**Comment by santiagomed** [comment]
I am using actix-web v4.3.0

**Comment by robjtede** [comment]
`cargo tree -i=actix-service`

**Comment by santiagomed** [comment]
I was running an older version of `actix-service`. Thanks!

**Comment by SamuelMarks** [comment]
Scary errors trying this solution with latest actix-web:
```rs
actix_web::test::call_and_read_body_json(&mut app, req).await;
    |                                                  ---------------------------------------- ^^^^^^^^ expected `ServiceResponse<_>`, found associated type
    |                                                  |
    |                                                  required by a bound introduced by this call
    |
    = note:       expected struct `ServiceResponse<_>`
            found associated type `<impl actix_web::dev::ServiceFactory<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<impl actix_http::body::MessageBody>, Config = (), InitError = (), Error = actix_web::Error> + actix_web::dev::Service<actix_http::Request> as Service<...>>::Response`
```

Which I got after changing your aforementioned signature due to this error:
```
actix_web::test::call_and_read_body_json(&mut app, req).await;
    |                                                  ---------------------------------------- ^^^^^^^^ unsatisfied trait bound
    |                                                  |
    |                                                  required by a bound introduced by this call
    |
    = help: the trait `actix_web::dev::Service<actix_http::Request>` is not implemented for `impl actix_web::dev::ServiceFactory<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<impl actix_http::body::MessageBody>, Config = (), InitError = (), Error = actix_web::Error>`
note: required by a bound in `call_and_read_body_json`
   --> actix-web-4.9.0/src/test/test_utils.rs:324:8
    |
322 | pub async fn call_and_read_body_json<S, B, T>(app: &S, req: Request) -> T
    |              ----------------------- required by a bound in this function
323 | where
324 |     S: Service<Request, Response = ServiceResponse<B>, Error = Error>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `call_and_read_body_json`
help: consider further restricting this bound
    |
36  |         > + actix_web::dev::Service<actix_http::Request>,
    |           ++++++++++++++++++++++++++++++++++++++++++++++
```
