### ISSUE TITLE
HTTPS Connection and Request/Response read phase handler

### ISSUE THREAD

**Issue by rohitjoshi** [actix/actix-web#1191]
Does `actix-web` support different read phases where application validation code can be executed?

E.g,

1. SSL Negotiation successful:  When SSL connection is establish, I want to validate SSL CN from whitelisted CNs from configuration

2. HTTP Request/Response Headers read completed: When HTTP headers read is completed, validate the certain headers for the security reason (e.g. Authorization or OWASP rules) prior to reading body

3. HTTP Request/Response body read: This is where we have Request/Response object is populated with both body and header.

**Comment by fafhrd91** [comment]
all this possible

**Comment by rohitjoshi** [comment]
I would appreciate any doc/code which I can use.
Regarding SSL CN verification, it was easier with my own implementation using `mio` but would like to understand if these handlers are exposed.  E.g. after ssl connection accept call: https://github.com/rohitjoshi/gadu/blob/master/src/server.rs#L383

**Comment by fafhrd91** [comment]
for 2 and 3 you need to change middlewares docs and example.

1 does not have much docs, you have to check source code.
server builds ssl chain automatically, you can do the same manually and have full control on ssl negotiation process
https://github.com/actix/actix-web/blob/1.0/src/server.rs#L277
