### ISSUE TITLE
Consider creating actix-db maybe?

### ISSUE THREAD

**Issue by hbobenicio** [actix/actix-web#1193]
Actix [documentation](https://actix.rs/docs/databases/) talks about database integration demonstrating the pattern of creating a new actor (DbExecutor) and query messages and handlers... and then how to create SyncArbiter for starting parallel db executors and then how to bind that to the App state... wow... that seems a lot of stuff, right?

Is it feasible to have some `actix-db` crate with some higher level utility functions or with some generic db executors / actors / queries which could improve this API or simplify some of those steps?

Am I the only one missing something like that or is there already something like that I'm not aware of? Or is it just the way the API should be?

**Comment by fafhrd91** [comment]
Did you check db examples? It’s pretty simple, I don’t think you can find much high level concepts related to actix-web itself

**Comment by hbobenicio** [comment]
Checking now db examples from [here](https://github.com/actix/examples/tree/master/diesel), yeah I see that this is a simpler approach than what the docs shows.

It just creates the pool and set it to App::data(). Then in the handler, just get it from web::Data<Pool> and use it, write?

If this is the way to go, this seems just a docs issue. Just got confused about what actually is the advised approach. I saw that it's currently under development for 1.0 version but I've missed that example. 

Nevermind then and thanks for pointing to the right direction! :)
