### ISSUE TITLE
Question: Dynamically modify Router 

### ISSUE THREAD

**Issue by yanickxia** [actix/actix-web#1194]
i try build a api gateway on actix-web. the gateway will scheulder pull the api config, so i use the router of `actix-router`, has anyway to add/remove path for the router？

and, i try shared the router between different thread, but contains RC<String> can't shared..

**Comment by fafhrd91** [comment]
actix-web router is designed to be read only. If you want to modify router at runtime you have to create your own router, you can use actix-router crate

**Comment by yanickxia** [comment]
@fafhrd91  thanks for your help. i have other question,  the `Router` type of `actix-router` is designed to be single thread. beacuse `PatternType::Dynamic(Regex, Vec<Rc<String>>, usize)` Rc<String> can't Sync or Send... has any way to update it at other thread. (Sorry, maybe is language question)

**Comment by fafhrd91** [comment]
I’d suggest simply fork it. It is stable, so you won’t lose any upstream updates

**Comment by cdbattags** [comment]
@yanickxia if you do decide to build this feature I'd love to track it!

I think a Rust gateway/proxy is the logical next step for the ecosystem.

Mind commenting here if you do make progress?
