### ISSUE TITLE
Support diesel and Tera?

### ISSUE THREAD

**Issue by ziselive** [actix/actix-web#12]
Does the program support diesel and Tera?

**Comment by fafhrd91** [comment]
I don’t see why it should not. I’ll add examples later today

**Comment by fafhrd91** [comment]
added tera example https://github.com/actix/actix-web/tree/master/examples/template_tera

**Comment by fafhrd91** [comment]
added diesel example https://github.com/actix/actix-web/tree/master/examples/diesel
