### ISSUE TITLE
Clarify dependency between actix_web and actor and std::future

### ISSUE THREAD

**Issue by gzp79** [actix/actix-web#1201]
For now there are a lot of tickets requesting to update actix and web-actor to use future 3.1, but all of them are closed referencing each other but there is no additional information on how to use actor, actix_web and future 0.3.1 in a project. (If it is supported or planed to be supported)

Please clarify the dependency and support (and maybe a timeline) as I think it is very confusing at the moment. (ex. web-actor still references actix_web 1.0.9).

**Comment by fafhrd91** [comment]
actix-web startting 1.0 does not depend on actix actors. there is integration package. integration with 2.0 will work same way whenever actix will be upgraded to std::futures
