### ISSUE TITLE
`AppConfig::secure()` is always false.

### ISSUE THREAD

**Issue by daxpedda** [actix/actix-web#1202]
`HttpRequest::app_config().secure()` will always return false.
While looking through the source code, trying to fix it myself, I couldn't find a place where it actually gets changed, it always remains in the default `false` state as far as I could see.

**Comment by fafhrd91** [comment]
It should be removed

**Comment by daxpedda** [comment]
Is there a safe way to check if the connection is `https` than? Is `Uri::scheme()` a safe indicator?

**Comment by fafhrd91** [comment]
Such information exists, but it is being set. This should be fixed rather than removed
