### ISSUE TITLE
Performance issues with awc

### ISSUE THREAD

**Issue by augustocdias** [actix/actix-web#1212]
I'm not sure if I was using it wrong or if it does have perfomance issues. But here's what happened:

I have an application that for every request, it downloads some images process them and respond to the client. I was using `awc` as my http client and it caused some issues when I deployed it into production. 
I have a struct that holds some configuration for my client and I was thinking on sharing a single awc client for the whole application and wrapping it inside this struct.
When I registered this object as `data` in my service I've got a compilation error because the client is not thread safe:

```std::rc::Rc<awc::ClientConfig>` cannot be shared between threads safely```

I then tried to create one client/request with `Client::default()`. 

When I finally deployed this application into production, we have gotten a huge spike in our DNS server that started to affect the rest of the application pipeline. 
I decided to try another http client and went with hyper. After the change the application was able to handle way more requests and dns lookups were solved as well. 
I'm not sure but I believe this is due to the connection pooling that hyper has in place.

Unfortunately I don't have data from previous the deployment, but as you can see in the graph, the requests to the dns server kept down the whole time after the switch to hyper.

<img width="3339" alt="Screenshot 2019-12-13 at 15 26 54" src="https://user-images.githubusercontent.com/1080789/70811770-9a704300-1dc6-11ea-9c1d-7575e6c4c3f9.png">

**Comment by Dowwie** [comment]
@fafhrd91 thoughts on awc connection pooling, assuming that is the issue at hand?

**Comment by fafhrd91** [comment]
@augustocdias did you create `Client` per request?

@Dowwie i receives notifications and i can read emails. there is no need to nudge me, its just annoying

**Comment by augustocdias** [comment]
@fafhrd91 yes

**Comment by Dowwie** [comment]
@fafhrd91 noted.

**Comment by fafhrd91** [comment]
@augustocdias that could be cause of the problem

**Comment by fafhrd91** [comment]
i can not debug this issue. reproducable example is required
