### ISSUE TITLE
compatibility with the http and http_body crates

### ISSUE THREAD

**Issue by miquels** [actix/actix-web#1217]
It would be very nice if actix-web provided compatibility with the standard types and traits from the [http](https://docs.rs/http) and [http-body](https://docs.rs/http-body/0.3.1/http_body/trait.Body.html) crates. This would help with interoperability with request-handlers from crates that expect that API (like my own [webdav-handler](https://crates.io/crates/webdav-handler/0.2.0-alpha.2) crate).

Implementing this would involve, for the request side:

- implementing `FromRequest for http::Request<Payload>`, so that you can write a handler that takes a `http::Request`, like
```rust
async fn handler(request: http::Request<Payload>, davhandler: web::Data<DavHandler>) -> HttpResponse {
   davhandler.handle(request).into()
}
```
- implementing the [http_body::Body](https://docs.rs/http-body/0.3.1/http_body/trait.Body.html) trait for dev::Payload (and/or maybe web::Payload)

And for the response side:

- implementing `From<http::Response<B>> for HttpResponse where B: http_body::Body ..`
- and probably `From<Result<http::Response<B>, Error> for HttpResponse where B: http_body::Body ..`

I've started [an attempt using some wrapper-types](https://github.com/miquels/webdav-handler-rs/blob/2aabaec9c653b6e5f068770ae4a376ef9a4de9d8/attic/actix-web.rs) that shows that it's not too complicated.

**Comment by fafhrd91** [comment]
webdav-handler supports actix. Actix already has a lot of dependencies, I don’t want add new one that is very rear used

**Comment by miquels** [comment]
I'm sorry you feel that way. It is not good for the Rust ecosystem that there are so much splits in the ecosystem, like  tokio vs async-std, actix vs hyper (the http and http_body crates fall under the hyper umbrella) because people cannot agree on common traits. I really hope that in the future this can be resolved.

By the way, webdav-handler does _not_ support Actix right now, I'm trying to add actix compatibility because Actix 2.0 looks promising and I think it's going to be quite popular but it would be so much easier if this support was in Actix itself. Hence this issue. However, feel free to close it.
