### ISSUE TITLE
How can I pass the WebsocketContext to thread?

### ISSUE THREAD

**Issue by tomocrafter** [actix/actix-web#1221]
I wrote the following code:
```Rust
impl StreamHandler<Result<ws::Message, ws::ProtocolError>> for MyWebSocket {
    fn handle(&mut self, msg: Result<ws::Message, ws::ProtocolError>, ctx: &mut Self::Context) {
        let msg = match msg {
            Err(_) => {
                ctx.stop();
                return;
            }
            Ok(msg) => msg,
        };

        match msg {
            ws::Message::Text(msg) => {
                println!("Message received: {}", &msg);
                thread::spawn(move || {
                    calc(msg, move |progress| { // <-- calc method blocks thread, and callbacks the progress
                        ctx.text(json!({"progress": progress}).to_string()); // <-- Here!
                    }
                });
            }
            _ => {}
        }
    }
}
```
but it causes following compile error:
```
error[E0277]: `(dyn actix::fut::ActorFuture<Actor = WebSocket, Output = ()> + 'static)` cannot be sent between threads safely
```
How can I solve this problem? or Don't I need to create the thread for better performance and there is better solution for solve this problem? (I am sorry for Bad English. I'm currently learning the English hard)

**Comment by fafhrd91** [comment]
You can not pass context to different thread

**Comment by tomocrafter** [comment]
Okay, I understand that. But If calculation method blocks the thread, but I want to send the result of calculation as text by websocket when requested from client. What can I do?

**Comment by fafhrd91** [comment]
Check web::block

**Comment by tomocrafter** [comment]
```
error[E0277]: `(dyn actix::fut::ActorFuture<Actor = WebSocket, Output = ()> + 'static)` cannot be sent between threads safely
   --> src/main.rs:58:21
    |
58  |                     web::block(|| {
    |                     ^^^^^^^^^^ `(dyn actix::fut::ActorFuture<Actor = WebSocket, Output = ()> + 'static)` cannot be sent between threads safely
```
Thank you! but seems like it doesn't work.

**Comment by fafhrd91** [comment]
Use web::block for computation only

**Comment by tomocrafter** [comment]
calc method blocks thread but calls callback closure to tell progress of computation. and when computation finished, it calls closure with result of computation. and I want to sent it as text by websocket. `web::block` is just only used for passing the result, right?
I'm started learning rust a week ago. So definitely I'm wrong something. I apologize for that.

**Comment by fafhrd91** [comment]
You can use mpsc  channel

**Comment by tomocrafter** [comment]
Could you provide example code?

**Comment by fafhrd91** [comment]
just crate futures::channel::mpsc channel, send values from sync code, read from ws context side.

**Comment by tomocrafter** [comment]
I wrote the following code:
```Rust
let (tx, rx) = mpsc::unbounded();
web::block(|| {
    calc(tx);
    Ok(())
});
for progress in rx { // <- Blocks here till calc ends.
    match progress {
        Progress::Progress(i) => ctx.text(json!({"type": "PROGRESS", "progress": i})),
        _ => {} // Supress others for example.
    }
}
```
It can be compiled because ctx is not inside thread. but `for progress in rx {` blocks thread. so it does not work...

**Comment by fafhrd91** [comment]
this is not an actix issue, you should ask in chat

**Comment by dessalines** [comment]
Has anyone figured out how to use `web::block` in any of the websocket examples?
