### ISSUE TITLE
Synchronous extractors in async handlers?

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#1222]
I couldn't find in the code where extractors are actually run by actix-web, so posting the question here:

If I implement FromRequest that blocks the current thread - will it block actix-web's executor? Will it be run in a thread pool? What is the documented behavior for such extractors?

Thanks in advance!

**Comment by fafhrd91** [comment]
trait definition https://docs.rs/actix-web/2.0.0-alpha.6/actix_web/trait.FromRequest.html
it is async, sync code will block whole thread

**Comment by vmalloc** [comment]
@fafhrd91 but sync *routes* (handler functions) are being run in a thread pool, right? Just making sure I understand

**Comment by fafhrd91** [comment]
No, actix-web does not use threads. It is single threaded

**Comment by vmalloc** [comment]
I see. And how about block_on? That does use a dedicated thread pool, right?

**Comment by fafhrd91** [comment]
web::block uses threadpool from actix-threadpool crate

**Comment by vmalloc** [comment]
I see. Thanks a lot for clarifying!
