### ISSUE TITLE
Question: Idiomatic way for custom request/response types

### ISSUE THREAD

**Issue by saschagrunert** [actix/actix-web#1228]
Hey, I'm playing around with futures 0.3 and axtic web (async/await). 

Right now I've implemented `Future` for a custom `CborRequest` (see: https://github.com/saschagrunert/webapp.rs/blob/ef6d90b39b88b4713512b0d009d26b0fd09339e3/backend/src/cbor.rs#L41-L78).

Is something like this still possible with actix-web and futures 0.3? I'm wondering what the most idiomatic way is in transforming the code into the recent actix version.

**Comment by fafhrd91** [comment]
you could use extractor/responder, something like `Cbor<T: Serialize>`
similar to `Json<T>`

**Comment by saschagrunert** [comment]
> you could use extractor/responder, something like `Cbor<T: Serialize>`
> similar to `Json<T>`

So basically adapting this implementation?
https://github.com/actix/actix-web/blob/74fa4060c2138dd070e9bfac65429d2ff81568cf/src/types/json.rs

**Comment by fafhrd91** [comment]
I think this is simplest solution. CborRequest and CborResponseBuilder seems slightly artificial.

btw Responser provides extra methods, `with_status()` and `with_header()`, so it is possible to customize response for any responder

**Comment by fafhrd91** [comment]
@saschagrunert do you still need something for this ticket?

**Comment by saschagrunert** [comment]
No thanks, lets close it for now.

**Comment by Noah-Kennedy** [comment]
For anyone who finds this thread, I have created a crate implementing CBOR for requests and responses.

[https://crates.io/crates/actix-cbor](https://crates.io/crates/actix-cbor)
