### ISSUE TITLE
Streaming proxy support

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [actix/actix-web#1231]
Hi,

I'm brand new to actix and a Rust newb (coming form TypeScript).  I found this example of a streaming proxy:

https://github.com/actix/actix-web/issues/128

However it doesn't work - the implementation completely changed in 1.0

Are there any 2.0 examples on how to do a streaming proxy?

Sincerely, :)

Artem

**Comment by fafhrd91** [comment]
https://github.com/actix/examples/tree/master/http-proxy

**Comment by artem-v-shamsutdinov** [comment]
Thank you for your response.  I would like to verify that this example is streaming the request and the response.  Being completely new to Actix it appears to me that it loads the entire request and response into memory and does not stream them.  Is that not the case?

Sincerely,

Artem

**Comment by fafhrd91** [comment]
You right, you need to  change line https://github.com/actix/examples/blob/master/http-proxy/src/main.rs#L40

Ok(client_resp.streaming(res.body()))

And in general, it is good idea to read docs

**Comment by artem-v-shamsutdinov** [comment]
Great, thank you so much! :)  I'll do my best to read the docs going forward.
