### ISSUE TITLE
Bigger content-length field makes actix return 504

### ISSUE THREAD

**Issue by jrabello** [actix/actix-web#1234]
I'm using actix for a couple of weeks and realized that for the following request:

```
curl -X 'POST' 'http://localhost:8080/3-git-hook-img-store' -H 'connection: close' -H 'content-length: 8000'  -d$'...'
```

Given that "-d" parameter content is less than 8000 bytes actix waits until return 504 after a while

My question is, when large amounts of requests are sent can this cause some kind of DoS problem to actix?

**Comment by fafhrd91** [comment]
this is dos for any system. it is just matter of amount.

**Comment by jrabello** [comment]
@fafhrd91 I understand your point, but I believe we should not "trust" requests too much, some kind of checking in serverside must be necessary, any inconsistency with the true data content-length should be treated as an error

**Comment by fafhrd91** [comment]
what is your suggestion?

**Comment by jrabello** [comment]
For this similar request:
```
curl -d '{"key1":"value1", "key2":"value2"}' -H "content-length: 800" -H "Content-Type: application/json" -X POST https://localhost:8080 -v
```

That's the expected response(400):
```
< HTTP/2 400
< content-type: text/html; charset=UTF-8
< referrer-policy: no-referrer
< content-length: 1555
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
<
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
```

We need to check into webserver for possible inconsistency between client header content-length and the true data's content length from POST request (in this case only 34 bytes)
