### ISSUE TITLE
why must the requirement exist, Error("missing field `create_time`" 

### ISSUE THREAD

**Issue by qmdx** [actix/actix-web#1238]
```
pub fn add(app_dto: web::Json<AppDTO>, pool: web::Data<Pool>) -> HttpResponse {
...
}
```

>  Error in response: Deserialize(Error("missing field `create_time`"

But  I want to allow properties not to exist. Is there a solution

**Comment by fafhrd91** [comment]
it is your code specific problem, actix-web has nothing to do with this.
