### ISSUE TITLE
Allow configuration of client in TestServer

### ISSUE THREAD

**Issue by kljensen** [actix/actix-web#1243]
The [TestServer](https://github.com/actix/actix-web/blob/a4ad5e6b69e1f9205d76ff40d56260bc125bbd08/test-server/src/lib.rs#L115) implementation keeps the awc HTTP client private. *I believe making the client public or somehow mutable would help testing features like redirections.* 

(In my particular case, I am trying to test that a certain handler returns a 307 redirect with a particular `location` header. The HTTP client in the TestServer follows redirects by default.)

**Comment by fafhrd91** [comment]
Http client does not follow redirect

**Comment by fafhrd91** [comment]
Also it is better to use actix_web::test::TestServrr

**Comment by kljensen** [comment]
My bad 🙁. I’ll take a more close look.

**Comment by fafhrd91** [comment]
I don't want to expose client atm. you can always create whatever client you need with `actix_web::client`
