### ISSUE TITLE
ServiceRequest.take_payload() payload hanging on .next().await

### ISSUE THREAD

**Issue by jbrookins13** [actix/actix-web#1245]
Within middleware I am attempting to get the request body payload for HMAC authentication but if the body actually has something in it this function seems to be hanging, possibly on the `body.next().await`. Here is the function
```
async fn get_request_body(req: &mut ServiceRequest) -> Result<BytesMut, Error> {
    let mut bytes: BytesMut = BytesMut::new();

    let mut body = req.take_payload();

    while let Some(chunk) = body.next().await {
        bytes.extend_from_slice(&chunk?);
    }

    Ok(bytes)
}
```
and here is the calling context
```
fn call(&mut self, mut req: ServiceRequest) -> Self::Future {
        let mut svc = self.service.clone();
        match futures::executor::block_on(get_request_body(&mut req)) {...}
```
`get_request_body()` doesn't hang if there is no request body.

**Comment by fafhrd91** [comment]
This won’t work. You block thread with block_on

**Comment by jbrookins13** [comment]
Yeah, I thought that might not work. I kept getting errors as it seems my `get_request_body()` isn't actually returning a `Result<BytesMut, Error>`.  This
```
let body_result: Result<BytesMut, Error> = get_request_body(&mut req);
```
gives this error
```
  --> src\custom_middleware\auth.rs:98:52
   |
98 |         let body_result: Result<BytesMut, Error> = get_request_body(&mut req);
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found opaque type
   |
   = note: expected type `std::result::Result<bytes::bytes_mut::BytesMut, actix_http::error::Error>`
              found type `impl core::future::future::Future`
```
I tried searching for something to get me on the right track, but to no avail.

**Comment by fafhrd91** [comment]
Replace block_on with `Box::pin(async move { get_request_body(...).await})`

**Comment by jbrookins13** [comment]
Currently the `Self::Future` for `call()` is this
```
type Future = Either<S::Future, Ready<Result<Self::Response, Self::Error>>>;
```
Would that need to change to use `Box::pin()`?

**Comment by fafhrd91** [comment]
well, you can check api docs, specifically `Box::pin()`

**Comment by jbrookins13** [comment]
Understood, I'll look into as soon as I can. Thanks for the help.
