### ISSUE TITLE
Can I create a not standard header in actix-web?

### ISSUE THREAD

**Issue by zzhengzhuo** [actix/actix-web#1246]
When I write a http proxy server,I'd like to add a not standard header in the request.However when I use 
```
res.headers_mut().insert(
                    HeaderName::from_static("not-standard-header"), 
                    HeaderValue::from_static("11"));
```
which only support standard header,and it failed and panic
```
 panicked at 'invalid header name'
```
Thanks for your help

**Comment by JohnTitor** [comment]
Does this example help you?
https://docs.rs/actix-web/2.0.0/actix_web/http/header/struct.HeaderName.html#examples-1

**Comment by zzhengzhuo** [comment]
> Does this example help you?
> https://docs.rs/actix-web/2.0.0/actix_web/http/header/struct.HeaderName.html#examples-1

Thanks for your help.However it just support standard header,and panic
```
 panicked at 'invalid header name'
```

**Comment by fafhrd91** [comment]
`failed` pretty useless description

**Comment by JohnTitor** [comment]
Related to #1021
