### ISSUE TITLE
Register a route middleware

### ISSUE THREAD

**Issue by 0x1793d1** [actix/actix-web#1247]
Hi,

Is there a way to register a middleware on route level?
I created an Authenticate middleware to do a redirection if no user is logged in and I'd like to register the middleware only on delete method.

The problem is that I only can do it on resource level like below:

```rust
.service(
    web::resource("/{repository}/{architecture}/{name}")
        .wrap(Authenticate::new("/user/sign_in"))
        .route(web::get().to(controller::package::get_package))
        .route(web::delete().to(controller::package::delete_package)),
)
```

Thanks!

**Comment by fafhrd91** [comment]
You can not register Middlewares on route level. And it is not planned

**Comment by ppoliani** [comment]
Is there any particular reason why this is implemented? I believe that this is quite a common thing to have in a web framework.

**Comment by robjtede** [comment]
Planned for 4.1. See #2725
