### ISSUE TITLE
actix_web::dev::Server.stop() does not work on windows

### ISSUE THREAD

**Issue by Rudi3** [actix/actix-web#1249]
I'm starting the server in another thread and send the `actix_web::dev::Server` back to the main thread via an asynchronous channel. With `server.stop(true);` I can stop it on Linux without any issues.

On Windows however, the server stops responding - but does not terminate properly. I checked `netstat` and it is still "officially" listening on the port. Starting another thread after that does not work, but neither does it cause an error to be thrown.

[**Example for repro**](https://gist.github.com/Rudi3/a859451f22363794dd12a34e2a044d01)

**Comment by tworec** [comment]
I'm having similar issue, when trying to stop http server with 
```
actix_rt::System::current().stop()
```
after that server is recovering on first HTTP request

```
ERROR [actix_server::accept] No workers
ERROR [actix_server::builder] Worker has died 0, restarting
INFO [actix_server::accept] Accepting connections on 127.0.0.1:7465 has been resumed
ERROR [actix_server::builder] Worker has died 7, restarting
ERROR [actix_server::builder] Worker has died 6, restarting
ERROR [actix_server::builder] Worker has died 5, restarting
ERROR [actix_server::builder] Worker has died 4, restarting
ERROR [actix_server::builder] Worker has died 3, restarting
ERROR [actix_server::builder] Worker has died 2, restarting
ERROR [actix_server::builder] Worker has died 1, restarting
INFO [actix_web::middleware::logger] 127.0.0.1:55562 "GET / HTTP/1.1" 200 34 "-" "curl/7.58.0" 0.000183
```

**Comment by fafhrd91** [comment]
@tworec could you run app with RUST_BACKTRACE=1. seems workers panic when receive stop signal

**Comment by tworec** [comment]
nothing more has shown on my console... I'm using `RUST_BACKTRACE=1 RUST_LOG=debug cargo run ...`

```
actix-rt = "1.0"
actix-web = "2.0"
```

and 

```
                HttpServer::new(|| {
                    App::new()
                        .wrap(middleware::Logger::default())
                        .service(index)
                })
                .bind(ctx.http_address())
                .context(format!("Failed to bind http server on {:?}", ctx.http_address))?
                .run()
                .await?;
```

**Comment by Rudi3** [comment]
Interesting. I'm getting something different (should have turned on logging earlier...):

```
[2020-01-10T13:52:09Z INFO  actix_server::builder] Starting 4 workers
[2020-01-10T13:52:09Z INFO  actix_server::builder] Starting server on [...]:[...]
server has been started successfully.
[2020-01-10T13:52:09Z DEBUG tokio_reactor] adding I/O source: 0
Command: 
[2020-01-10T13:52:09Z DEBUG tokio_reactor::background] starting background reactor
[2020-01-10T13:52:09Z DEBUG tokio_reactor] adding I/O source: 4194305
[2020-01-10T13:52:09Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2020-01-10T13:52:09Z DEBUG tokio_reactor::registration] scheduling Read for: 1
//accepts connections normally here
stop-server //issue command to stop server
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
Command: //still listening on given port
start-server //starting new server
[2020-01-10T13:52:36Z INFO  actix_server::builder] Starting 4 workers
[2020-01-10T13:52:36Z INFO  actix_server::builder] Starting server on [...]:[...]
server has been started successfully.
Command: //does not accept any connections, still listening
[2020-01-10T13:52:36Z DEBUG tokio_reactor] adding I/O source: 8388610
[2020-01-10T13:52:36Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2020-01-10T13:52:36Z DEBUG tokio_reactor::registration] scheduling Read for: 2
```

Strangely, there are no errors - but it doesn't work.
**Correction:** After the second startup, a second listener seems to be added on the same port, same pid.

**Comment by Rudi3** [comment]
**Correction: I'm still using actix_web `1. something`, that's an oversight, I'll update with new information as soon as my application is ported to the upstream version**
@tworec are you starting a new `let sys = actix::System::new("mysystem")`?

I'm using what basically boils down to:

```
HttpServer::new(myapp)?.start(); //send Result<actix_web::dev::Server> to other thread to stop it later
sys.run(); //"block" current thread for actix system; maybe this doesn't exit properly...
```

**Comment by Rudi3** [comment]
It's doing exactly the same thing on `2.0`. After shutting down all workers, it's still listening.

After the second startup, there is a second listener and it doesn't answer/process anything. It only stops listening when the whole application is terminated.

*Note:* I'm using `rustls` - I'm not sure if listening is handled in the same way as it would be without it.

**Comment by Rudi3** [comment]
Both on Windows and Linux, the server thread seems to terminate properly. I've tested it by printing a line within the `spawn` closure.

`reuse_address(true)` could be the reason why it doesn't show an error when starting up for the second time and binding the same post and address again.
https://github.com/actix/actix-web/blob/6a0cd2dced8b085865e966e2d40baf1b8ad9d640/src/server.rs#L573

I'm not sure what the underlying issue is, but I've tried just `TcpListener::bind` and it "unbinds" just fine as the `TcpListener` gets out of scope on Windows. Perhaps it's something in https://github.com/rust-lang-nursery/net2-rs/blob/master/src/socket.rs as it's part of `net2-rs`. There would be some unsafe code there, but perhaps it's just missing a `Drop` implementation somewhere. Should I file a bug with `net2-rs`/do you think it might be coming from there?

It may be nice to just use `TcpListener`, if possible. But I'm not sure if it's as capable and if that's desireable. I just had a brief look so far and I saw that the `Socket` is converted to `TcpListener` in the end - if I got that right.

**Comment by Rudi3** [comment]
If my interpretation of `net2-rs`'s `Socket` and of [`sys::net::Socket`](https://doc.rust-lang.org/src/std/sys_common/net.rs.html#10), the Socket used in the [`TcpListener`](https://doc.rust-lang.org/src/std/net/tcp.rs.html#699) (via [`sys_common::net::TcpListener`](https://doc.rust-lang.org/src/std/sys_common/net.rs.html#385)) is correct, then it probably gives different results because it has an own [Windows implementation](https://github.com/rust-lang/rust/blob/6c0b779b7bb23ad1bead914e8023642cc2368406/src/libstd/sys/windows/net.rs#L89).

**Comment by Rudi3** [comment]
I tried [just using `net::TcpListener::bind`](https://github.com/Rudi3/actix-web/tree/use_std_TcpListener) - it's behaving exactly the same way. Currently, I'm at my whit's end in this regard.

**Comment by robjtede** [comment]
sample provided: https://gist.github.com/Rudi3/a859451f22363794dd12a34e2a044d01

**Comment by Rudi3** [comment]
I had a look at the `actix_server::ServerBuilder` and I think that i found that the list of sockets/tcplisteners stored is empty before the shutdown even occurs. I thought about trying to close them manually at that point, but they aren't there(`len()=0`)...
Test: https://github.com/Rudi3/actix-net/blob/f582a8b4c60e18e1eea65d30d23af0db94a6f95b/actix-server/src/builder.rs#L451

stopping the server with this gives me basically this output:
```
0 //amount of listeners tracked
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
[2020-01-10T13:52:22Z INFO  actix_server::worker] Shutting down worker, 0 connections
```

**Comment by alekseysidorov** [comment]
I have wrote another example to expose this bug. 
In my case I launch a two tasks: one task restarts server every 20 seconds, another task sends a lot of requests to server.

https://github.com/alekseysidorov/actix_web_windows_restart_bug

It seems that there are some bug during the socket close that leaves socket in an open state after the server shutdown. I.e when server starts again with the `reuse_address` option it bind with the socket that is in the undefined state. And then server becomes freeze.

I also have found a workaround for this issue. I keep listener socket handle and close them after `server.stop()` call. In other words for some reasons `Server` doesn't actualy close socket after shutdown.

https://github.com/alekseysidorov/actix_web_windows_restart_bug/commit/0ed9f49b4a944b18160fdcf11f53aecdb794b8a1

I hope this information is helpful to find a way to fix this issue.

**Comment by neilyoung** [comment]
Could somebody please elaborate, how I could safely terminate an instance from another thread (maybe from a route handler of a REST API) an instance, launched  like so?

```
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
     HttpServer::new(
         || App::new()
             .service(web::resource("/").to(|| HttpResponse::Ok())))
         .bind("127.0.0.1:59090")?
         .run()
         .await
}
```

**Comment by fivethousand** [comment]
@neilyoung see https://github.com/actix/examples/tree/master/shutdown-server

**Comment by fivethousand** [comment]
Stopping the system, however, does not work (on Linux and macOS, I don't have a Windows system, actix-web 3.2.0):
~~(Background: Restarting the entire system is currently the only way to change routes)~~

Example:
```
use actix_web::{get, middleware, web, App, HttpResponse, HttpServer};
use futures::executor;
use std::time;
use std::{sync::mpsc, thread};

#[get("/stop")]
async fn stop(stopper: web::Data<mpsc::Sender<()>>) -> HttpResponse {
    stopper.send(()).unwrap();
    HttpResponse::NoContent().finish()
}

fn main() -> std::io::Result<()> {
    std::env::set_var("RUST_LOG", "trace");
    env_logger::init();

    let (tx, rx) = mpsc::channel::<()>();
    let mut system = actix_web::rt::System::new("main");

    system.block_on::<_, std::io::Result<()>>(async move {
        let server = HttpServer::new(move || {
            App::new()
                .data(tx.clone())
                .wrap(middleware::Logger::default())
                .service(stop)
        })
        .bind("127.0.0.1:8080")?
        .run();

        let srv = server.clone();
        thread::spawn(move || {
            rx.recv().unwrap_or_else(|_| {});
            executor::block_on(srv.stop(true))
        });

        server.await
    })?;

    let mut tries = 0;
    while actix_web::rt::System::is_set() && tries < 20 {
        println!("Waiting for the system to stop...");
        actix_web::rt::System::current().stop();
        thread::sleep(time::Duration::from_millis(500));
        tries += 1;
    }

    if actix_web::rt::System::is_set() {
        println!("Could not stop system.");
    }

    Ok(())
}
```

Am I doing something wrong, or is this a bug?

**Comment by fivethousand** [comment]
Calling `actix_web::rt::System::current().stop();` does seem to work somehow: It does terminate all worker threads, and the port is closed. Yet, `actix_web::rt::System::is_set()` remains true.

**Comment by fakeshadow** [comment]
System is just a handler of runtime and stored in thread_local.
It's never cleaned up until your program end. Calling `System::is_set` is just a way to check if the thread_local variable is inited already

**Comment by neilyoung** [comment]
@fivethousand  Thanks for the stopper hint. Did totally forget about.

**Comment by robjtede** [comment]
This is probably fixed in the newer v4 betas given how Server behavior has changed. Would be better to open a new issue if this is still a problem.
