### ISSUE TITLE
Is there any library which exports actix-web features as C-like API?

### ISSUE THREAD

**Issue by silvioprog** [actix/actix-web#1250]
Hi.

Is there any library which exports all the actix-web features (server and client) into an ANSI C API? If so, could you share its repository?!

Such a library would be useful to taste actix-web in other programming languages (e.g. C/C++, Python, Pascal and so on). :-)

Thank you!

**Comment by fafhrd91** [comment]
i dont think such library exists

**Comment by naturallymitchell** [comment]
Yes. Please look around my repositories.
