### ISSUE TITLE
Access to client's certificate

### ISSUE THREAD

**Issue by wojciech-wilk** [actix/actix-web#1251]
Hi

Background: I want to authenticate a client using the X509 certificate. For security reasons I need to have access to some fields in the cert and process them.

I am using actix-web 2 and OpenSSL. I've managed to verify cert by openssl, but I am struggling with a way to access it in the handler. I've tried #844, #946, #994 but I cannot get it to work.

I would really appreciate a working example of accessing the cert in a handler (or passing some data from the cert to the handler) if it's possible.

Thanks in advance!

**Comment by fafhrd91** [comment]
you have to build http service manually, https://github.com/actix/actix-web/blob/master/actix-http/src/service.rs#L232

**Comment by fafhrd91** [comment]
https://docs.rs/actix-http/1.0.1/actix_http/struct.HttpServiceBuilder.html#method.on_connect

**Comment by baoyachi** [comment]
is there any example with `Access to client's certificate` in `actix-web`？

**Comment by robjtede** [comment]
@baoyachi not yet, i believe you should track #1727

**Comment by robjtede** [comment]
@howard0su I've made progress on exposing this in #1754. It can provide access to `rustls::Certificate` or `openssl::x509::X509` and should be enough to support this use case.

**Comment by robjtede** [comment]
I've made progress on exposing this in #1754. It can provide access to `rustls::Certificate` or `openssl::x509::X509`.
