### ISSUE TITLE
actix-web without async main

### ISSUE THREAD

**Issue by ldm0** [actix/actix-web#1252]
Hello, I'm new to `actix-web`.
I've noticed that for every actix example, there is a `actix_rt::main` with main declared as async function.
How can I use actix-web without a main declared as async? Or it is a must?
I tried to search some docs but found nothing about it...

**Comment by DominicWrege** [comment]
All handlers must be async.

**Comment by ldm0** [comment]
@DominicWrege Is main a handler?

**Comment by DominicWrege** [comment]
You can only use await inside an async fn. ```actix_rt::main``` is just a macro that rewrites your functions declaration because you need a runtime. Does this helps to you?

**Comment by ldm0** [comment]
@DominicWrege Yes this helps a lot. Thanks bro.
