### ISSUE TITLE
Error when using rustls feature

### ISSUE THREAD

**Issue by robertohuertasm** [actix/actix-web#1253]
I'm getting this error while trying to compile:

![image](https://user-images.githubusercontent.com/696981/71770626-0b6eca80-2f2f-11ea-996d-aa37e7ae7b53.png)

It seems that somehow `failure v0.1.5` is dependant on `backtrace v0.3.13` although in the [0.1.5 Cargo.toml](https://github.com/rust-lang-nursery/failure/blob/0.1.5/Cargo.toml#L18) it seems to be using `backtrace  v0.3.3`. I'm not sure if upgrading to the latest `failure` version would fix this issue.

**Comment by fafhrd91** [comment]
Check dependencies for privateer crate. Actix works fine with rustls

**Comment by robertohuertasm** [comment]
I will. For the sake of having the full information, these are the dependencies:

```
[dependencies]
# server
actix-rt = "1.0.0"
actix-web = { version = "2.0.0" }
actix-cors = "0.2.0"
actix-files = "0.2.1"
actix-service = "1.0.1"
toml = "0.5"
futures = { version = "0.3.1" }
# utils
lazy_static = "1.4.0"
bytes = "0.5.3"
console = "0.9.1"
rayon = "1.3.0"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1.22"
# github v3
reqwest = { version = "0.10", features = ["blocking", "json"] }
frank_jwt = "3.1"
time = "0.1"
# serialization
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# crypto
hmac-sha1 = "0.1.3"
base16 = "0.2.1"
````
