### ISSUE TITLE
Maintenance transfer of actix-web-httpauth crate

### ISSUE THREAD

**Issue by svartalf** [actix/actix-web#1257]
I have this [`actix-web-httpauth`](https://crates.io/crates/actix-web-httpauth) crate, which provides headers and extractors for HTTP Authorization routines; right now it supports only `actix-web = "^1"`, but there is a [PR](https://github.com/svartalf/actix-web-httpauth/pull/14) for `actix-web 2.x`, so it should not be a big problem to update it quickly.

Yet, I don't think that I will be able to allocate time to support it properly in a nearby future, so I want to handle the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) here and transfer the maintenance; that includes moving the repository and adding crate maintainers at crates.io.

I would prefer to transfer it to https://github.com/actix org directly if it is okay with the Actix Team, but I'm open to suggestions too.

**Comment by fafhrd91** [comment]
@actix/contributors

**Comment by fafhrd91** [comment]
I am happy to move it to actix org, but someone should take formal maintainer role

**Comment by JohnTitor** [comment]
I'm available to maintain that crate and help some work. (nice work @svartalf!)

**Comment by svartalf** [comment]
@fafhrd91 great to hear! As far as I understand, nothing stops us to start the process?

@JohnTitor it seems that crates.io requires from user to be a part of github organization in order to add `github:actix:owners` owner to the crate, so I can add you as a crate owner and you will handle any ownership issues from there; is it okay with you?

**Comment by JohnTitor** [comment]
> so I can add you as a crate owner and you will handle any ownership issues from there; is it okay with you?

Sure thing 👍

**Comment by fafhrd91** [comment]
@svartalf yes, just move it to actix org

**Comment by JohnTitor** [comment]
@svartalf AFAIK, transfering repo to org also needs permission to create a repo in the org. If so, could you transfer repo to @fafhrd91 or me?

**Comment by svartalf** [comment]
@JohnTitor yeah, you are right, I can't transfer repo to `actix` org directly, so I requested transfer to you and added you as a crate owner also (there should be a pending invite in your crates.io profile somewhere)

**Comment by JohnTitor** [comment]
Okay, transfering(moving repo and setting crate owner on crates.io) seems successful.

@fafhrd91 could you modify permissions for the repo? I cannot do because I'm not an org owner.

And @svartalf, thanks again for your great work!

**Comment by fafhrd91** [comment]
done

**Comment by JohnTitor** [comment]
So, all work is done?

**Comment by svartalf** [comment]
@JohnTitor it seems so. Feel free to contact me in case we forgot about something :)
Thank you for handling this crate, it would be a pity to abandon it
