### ISSUE TITLE
Can actix-web query a site?

### ISSUE THREAD

**Issue by joshsleeper** [actix/actix-web#126]
That is, from everything I've read, it seems like `actix-web` is great at _responding_ to requests, but I can't find anything about _making_ requests to some URL.

e.g. I want to query some external site and use that response data within my `actix-web` server.

Maybe that's totally out of scope for the project, but I figured I'd ask.
Thanks!

**Comment by fafhrd91** [comment]
there is [actix_web::client](https://actix.github.io/actix-web/actix_web/client/index.html) api, it is not in guide yet, but i am planing to add guide section for client

you can also check [http proxy](https://github.com/actix/actix-web/blob/master/examples/http-proxy/src/main.rs) example

**Comment by fafhrd91** [comment]
there is also [websocket client](https://actix.github.io/actix-web/actix_web/ws/struct.Client.html)

**Comment by fafhrd91** [comment]
reopen, if you have questsions
