### ISSUE TITLE
Use multiple CookieSession with different sign

### ISSUE THREAD

**Issue by gzp79** [actix/actix-web#1262]
As I see only 1 (Cookie)Session can be added to a webapp or scope.
In my usecase I have a few cookies with different sign keys and different cookie properties (secure, time-to-live)

ex: user_id is a signed cookie provided by the ID server
tracking_id is not signed and sometimes generated by the client but server also generates, replaces it
geo_location which is also signed but may exists without a user login. It is generated by another service but used by many other and has a different key.

So is there any way to use actix_session to manage multiple independent cookies ? 
I see it can be used as a key-value map, but all of them are stored in the same cookie.

**Comment by gzp79** [comment]
As I see it is not possible at the moment, but what if the whole Session, CookieSession, CookieSessionMiddleware gets a generic "Scope" type ? The only purpose of the generic type is to generate a new type, app data, middleware etc. for each independent session/cookie.

Something like this:
```
// for backward compatibility defined in the crate
pub type Session = ScopedSession<()>; 
pub type CookieSession = ScopedCookieSession<()>;

struct MyScope; // my new "scope"
type MySession = ScopedSession<MyScope>;
type MySession = ScopedCookieSession<MyScope>;

App::new.wrap(CookieSession::signed(key1).name("c1")).wrap(MyCookieSession::signed(key2).name("c2"));

pub fn endpoint(session: Session, mySession: ScopedSession);
```

**Comment by fafhrd91** [comment]
`endpoint` won't work. I think you would need something like

```rust
pub fn endpoint(session: Session<()>, mySession: Session<MyScope>);
```

**Comment by fafhrd91** [comment]
It is possible to experiment with session outside of actix-web repo

**Comment by gzp79** [comment]
It is possible but actix-session is part of THIS repo. 
So it means that the request to support multiple session in a single app/scope is rejected ? 

(My second  comment was an idea how to do it in a backward compatible way without a huge change)

**Comment by fafhrd91** [comment]
request is not rejected, you are welcome to create PR
