### ISSUE TITLE
Connection pooling when using ClientRequest/ClientRequestBuilder

### ISSUE THREAD

**Issue by dcastelltort** [actix/actix-web#127]
Hi,

First, thanks for actix/actix web, and all the work/time you put into it, the more I drill into it, the more I like it :)

I'm currently expanding/building on top of the http_proxy example. (needing to build an application proxy at the app level, not the protocol). I'm trying to get as much throughput, and as low latency as possible. I've increased backlog, threads, removed all logging , but I'm still at 1/3 of the throughput of the service I want to proxy.

I think I might spend too much time opening/closing HTTP connections when using client::clientRequest, and I'm thinking to pool connections and reuse them if possible. I noted there is with_connector() and [with_connection](https://docs.rs/actix-web/0.4.9/actix_web/client/struct.ClientRequestBuilder.html#method.with_connection)() on ClientRequestBuilder but I'm having a hardtime figuring out how/where to create such pool/connection and reuse these as I build those requests.

I'm kindly asking for help, if you could share with me some hint/guidance as to where I could look for example/reference in the code to get myself booted, please ?

Thanks for any help you could provide.
Kind regards.

**Comment by fafhrd91** [comment]
what version of actix-web do you use? 0.4.10 already has basic connection pooling

**Comment by fafhrd91** [comment]
it is not possible to customize pool yet. here is link to a [pool](https://github.com/actix/actix-web/blob/master/src/client/connector.rs#L359)

**Comment by fafhrd91** [comment]
you should join getter channel, we can discuss performance questions

**Comment by dcastelltort** [comment]
Hi,

Thanks for your help. :)

Indeed, sorry, I was using 0.4.8 , using 0.4.10 improved the rate.

I'm still having an issue but this should be coming from something else. 

At some point I get the following errors spamming:
ERROR 2018-03-21T13:22:44Z: actix_web::pipeline: Error occured during request handling: Failed to connect to host: Cannot assign requested address (os error 99)
ERROR 2018-03-21T13:22:44Z: actix_web::pipeline: Error occured during request handling: Failed to connect to host: Cannot assign requested address (os error 99)

I managed to reproduce this using only actix web examples: hello world and http_proxy.
Basically, I'm proxying hello_world with http_proxy.
[changes.patch.gz](https://github.com/actix/actix-web/files/1833464/changes.patch.gz)

My setup is as follow:
- hello_world example with 2 threads, in release, log=error, listening on 8088
- http_proxy example with 2 threads, in release, log=error , listening on 8080
- localhost:8080/streaming => localhost:8080/

I get the following (most likely because of the errors):

**Direct call to hello_world (no errors)**
$ wrk -t2 -c128 -d10s http://localhost:8088/
Running 10s test @ http://localhost:8088/
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   499.28us  303.65us   8.90ms   96.20%
    Req/Sec   121.03k     9.08k  141.43k    75.00%
  2407300 requests in 10.00s, 296.16MB read
Requests/sec: 240618.76
Transfer/sec:     29.60MB

**calling http_proxy (with errors in http_proxy, all fine in hello_world side)**
$ wrk -t2 -c128 -d10s http://localhost:8080/streaming
Running 10s test @ http://localhost:8080/streaming
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    36.15ms   41.71ms 270.02ms   79.59%
    Req/Sec     3.41k     8.27k   35.90k    89.80%
  66956 requests in 10.08s, 6.55MB read
  Non-2xx or 3xx responses: 10528
Requests/sec:   6643.18
Transfer/sec:    665.23KB

I'm going to keep on investigating, but wanted to share the use case/test.
I will surely step by the gitter later this week.

Thanks.
Kind regards.
Damien

**Comment by fafhrd91** [comment]
Did you increase number of file descriptors?

**Comment by fafhrd91** [comment]
pooling bug should be fixed in master. i got about 40% proxy throughput. i will do more optimizations in next version

**Comment by fafhrd91** [comment]
one note, tokio-core=0.1.15 has performance regressions. to get maximum performance you should use 
```toml
tokio-io = "=0.1.5"
tokio-core = "=0.1.11"
```
