### ISSUE TITLE
No way to extract a URI fragment?

### ISSUE THREAD

**Issue by Alovchin91** [actix/actix-web#1271]
~~Hi,~~

~~I couldn't find a way to get a URI fragment from `HttpRequest`, even though the documentation mentions a fragment part of the URL: https://docs.rs/actix-web/2.0.0/actix_web/http/uri/struct.Uri.html~~

```
abc://username:password@example.com:123/path/data?key=value&key2=value2#fragid1
                                                                        |-----|
                                                                           |
                                                                        fragment
```

~~Is it possible to get it with Actix somehow? Thanks!~~

Nevermind, apparently it's my poor knowledge of the web stack 😬

**Comment by chansen-p44** [comment]
It would have been nice if you had answered your own question, instead of just striking it all out. 
I can't figure out how to get it either.

**Comment by Alovchin91** [comment]
@chansen-p44 Oops, sorry, I thought my question was too stupid to answer it 😄

As far as I understand, the `fragment` part of the URI is client-side only, so server has no option to get it. Quote from Wikipedia:

> Fragments depend on the document MIME type and are evaluated by the client (web browser). Clients are not supposed to send URI fragments to servers when they retrieve a document <...>

So - yet again, from my understanding - because Actix is a server, it has no way to retrieve the fragment.

**Comment by chansen-p44** [comment]
> @chansen-p44 Oops, sorry, I thought my question was too stupid to answer it 😄
> 
> As far as I understand, the `fragment` part of the URI is client-side only, so server has no option to get it. Quote from Wikipedia:
> 
> > Fragments depend on the document MIME type and are evaluated by the client (web browser). Clients are not supposed to send URI fragments to servers when they retrieve a document <...>
> 
> So - yet again, from my understanding - because Actix is a server, it has no way to retrieve the fragment.

Thanks! I came to the same conclusion after digging around for an hour or so.
