### ISSUE TITLE
struggles with shared mutable state in 2.0

### ISSUE THREAD

**Issue by jeremyandrews** [actix/actix-web#1272]
I'm trying to update my code from Actix 1.0 to 2.0, and am struggling to convert `register_data()` to `app_data()`. I've not figured out how to resolve the error, `App data is not configured, to configure use App::data()`.

Here's a link to the 1.0 code which was working -- setting up the data:
https://github.com/jeremyandrews/kakaia/blob/master/src/main.rs#L37

And then using the data in a thread:
https://github.com/jeremyandrews/kakaia/blob/master/src/speech.rs#L128

And this works as intended:
```
$ curl -v --request POST --data @test/test.base64 http://127.0.0.1:8088/convert/audio/text
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8088...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8088 (#0)
> POST /convert/audio/text HTTP/1.1
> Host: 127.0.0.1:8088
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 45632
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 5
< content-type: text/plain; charset=utf-8
< date: Sun, 12 Jan 2020 08:50:13 GMT
< 
test
* Connection #0 to host 127.0.0.1 left intact
```

However, having updated to 2.0 I can't seem to get this working -- here's where I set up the data:
https://github.com/jeremyandrews/kakaia/blob/actixweb2/src/main.rs#L38

And here's where I'm using the data in a thread:
https://github.com/jeremyandrews/kakaia/blob/actixweb2/src/speech.rs#L128

When I push data to the API, I get the following error:
```
$ curl -v --request POST --data @test/test.base64 http://127.0.0.1:8088/convert/audio/text
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8088...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8088 (#0)
> POST /convert/audio/text HTTP/1.1
> Host: 127.0.0.1:8088
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 45632
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 56
< content-type: text/plain; charset=utf-8
< date: Sun, 12 Jan 2020 08:44:36 GMT
* HTTP error before end of send, stop sending
< 
* Closing connection 0
App data is not configured, to configure use App::data()
```

I'm not seeing what I'm doing wrong -- any help would be greatly appreciated!

**Comment by adwhit** [comment]
The rules are (through trial and error):
* `.app_data(...)`  -> your data **must** be wrapped in a `Data<..>`
* `.data(...)`  -> your data **must not** be wrapped in a `Data<..>`

Why do two versions exists? If you want to share state between threads, use `.app_data`. If not, you may use `data`.

IMO this is not clear from the docs, I wonder if they are out of date.

**Comment by fafhrd91** [comment]
PR is always welcomed

**Comment by jeremyandrews** [comment]
With the above feedback (and referring to the documentation PR) I've made it work, but I'm still a bit confused. Ultimately I (believe I) need my data wrapped in an Arc<T> so I can clone it to pass to all threads. My code is working here:
https://github.com/jeremyandrews/kakaia/blob/actixweb2/src/main.rs#L38
https://github.com/jeremyandrews/kakaia/blob/actixweb2/src/speech.rs#L128

Using `app_data()` added the Arc<T> for me, and I suspect that in my current implementation I'm incorrectly (or sub-optimally) invoking a double Arc<T> as mentioned in this comment:
https://github.com/actix/actix-web/blob/master/src/data.rs#L71

In any case, my server code is finally working with Actix-Web 2.0 which is progress, thanks!

**Comment by adwhit** [comment]
You have double-`Arc`ed it, I think. My advice is replace the `Arc` with a `Data` and then use `.app_data(..)` to add to your app.

(Apologies, I got `data` and `app_data` mixed up in the earlier comment, now corrected)

**Comment by jeremyandrews** [comment]
While that makes sense to me, that's what I originally had done. I see that my original links are no longer valid, and are now pointing to the new version of the code. Here's the old version:

- https://github.com/jeremyandrews/kakaia/commit/877a241d5822398b0cca58f3900fcacc0116d604#diff-639fbc4ef05b315af92b4d836c31b023L38
- https://github.com/jeremyandrews/kakaia/commit/877a241d5822398b0cca58f3900fcacc0116d604#diff-0ff8e1d9f6a60b543548672442a937b2R128

If I'm understanding your recommendation correctly, that's what I'd done, but it had led me to the `App data is not configured, to configure use App::data().` error message.

**Comment by adwhit** [comment]
I believe your original error was because `config_web` was attached with `.data(..)` but was not wrapped in a `Data<_>`.

**Comment by adwhit** [comment]
Humm . Unfortnately I can't get your code to compile so I can't check. If you create a reduced example I am happy to take a look. However I believe the example here https://github.com/actix/examples/blob/94892d992ddf80233e10e45e84099f1987ba70b8/state/src/main.rs is correct.

**Comment by jeremyandrews** [comment]
I created a reduced example and it worked fine. Through further trial and error, I discovered my problem is in how I'm trying to limit the maximum upload size, while the shared mutable state was defined correctly.

I'm now trying to figure out how to correctly limit the upload size with a configurable option with actix-web 2.0:
https://github.com/jeremyandrews/kakaia/blob/actixweb2/src/main.rs#L45

**Comment by jeremyandrews** [comment]
I created a reduced example here, which doesn't have difficult to compile dependencies:
https://github.com/jeremyandrews/actix-configure

I believe the problem is from changes in `FromRequest` in 2.0.

**Comment by jeremyandrews** [comment]
This seems to be the fix -- I confirmed doing the same in my main codebase also works:
https://github.com/jeremyandrews/actix-configure/pull/1/files

**Comment by jeremyandrews** [comment]
I believe this can be closed now -- thanks for the help!

**Comment by adwhit** [comment]
Glad you got it working. I will try have a bit of a dig this evening to find out what's really going on here.
