### ISSUE TITLE
r2d2 + websockets (how to pass a connection pool to a websocket server)

### ISSUE THREAD

**Issue by dessalines** [actix/actix-web#1273]
I'm using these two actix_web examples as reference: the [r2d2 pooling](https://github.com/actix/examples/blob/master/r2d2/src/main.rs), and the [websocket tcp chat](https://github.com/actix/examples/tree/master/websocket-tcp-chat)

My questions are below:

```rust 
async fn chat_route(
    req: HttpRequest,
    stream: web::Payload,
    srv: web::Data<Addr<server::ChatServer>>,
    // Easy to add the pool here as a shared state
    pool: web::Data<Pool<ConnectionManager<PgConnection>>>,

) -> Result<HttpResponse, Error> {

    // How should I pass the pool ( or just a connection ) here? And what's the right way to do that?
    // And how can I make sure to use web::block to get synchronous pool fetches?
    ws::start(
        WsChatSession {
            id: 0,
            hb: Instant::now(),
            room: "Main".to_owned(),
            name: None,
            addr: srv.get_ref().clone(),
        },
        &req,
        stream,
    )
}
```

From above:

- How should I pass the pool ( or just a connection ) here? And what's the right way to do that?
- And how can I make sure to use web::block to get synchronous pool fetches?

Thanks in advance.

**Comment by Kilerd** [comment]
`pool` is wrapped in `Arc`, so you can add a field in `WsChatSession` to store the database pooled connection.

**Comment by dessalines** [comment]
How do I make sure this uses `web::block` so it doesn't block the thread though? I'm finding from a single websocket connection, I can't do multiple actions in async.

**Comment by dessalines** [comment]
I'm totally stuck. Does anyone have web::block working in a websocket application?

**Comment by robjtede** [comment]
closing, discussion about web::block in websocketes continues in #1455
