### ISSUE TITLE
More ergonomic proxy support

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#128]
Not sure if I'm doing things incorrectly, but using the http proxy example is fine if it's only a GET request, and you don't want to send the client headers or body.

It gets much more interesting if you want to copy over the headers, and stream out the request body:

```
let mut builder = client::ClientRequest::build();

for (key, value) in req.headers() {
    builder.header(key.clone(), value.clone());
}

builder
    .uri(&url)
    .method(req.method().clone())
    .body(Body::Streaming(Box::new(req.from_err())))
    .unwrap()
    .send()
    .map_err(error::Error::from)
    .and_then(|resp| {
        let mut client_response = HttpResponse::build(resp.status());

        for (key, value) in resp.headers() {
            client_response.header(key.clone(), value.clone());
        }
        client_response.body(Body::Streaming(Box::new(resp.from_err())))
            .map_err(|e| e.into()) // HttpOk::build() mayb return HttpError, we need to convert it to a Error
    })
    .responder()
```

Where `req` is a `HttpRequest<S>`

On top of having to iterate through all the headers, using the `header()` method, the state `<S>` has to be `'static` for this to allow the streaming boxed body.

Is there a more ergonomic way of doing this without having to do so much handling?

**Comment by fafhrd91** [comment]
do you really need actix-web in this case? simple tcp proxy would be faster and simpler.

btw why `'static` is the problem? it just mean you can not use reference

**Comment by cetra3** [comment]
If it was just a proxy, no I wouldn't need actix-web.  But this is just one of the handlers needed.  `'static` isn't a problem, but It'd be nice to not have that restriction.

**Comment by fafhrd91** [comment]
1. i dont think it is possible to remove `'static`.

2. there is [HttpResponseBuilder::streaming()](https://github.com/actix/actix-web/blob/master/src/httpresponse.rs#L519)
and i added similar to `ClientRequestBuilder`

3. also i can add `impl From<ClientResponse> for HttpResponseBuilder` and `impl From<HttpResponse> for ClientRequestBuilder`

**Comment by fafhrd91** [comment]
maybe for 3, instead of `From<>` just add custom method, something like `ClientRequest::build_from()`

what do you think?

**Comment by fafhrd91** [comment]
added some conversions, you can rewrite your code like this

```rust
client::ClientRequest::build_from(&req)
    .uri(&url)
    .streaming(req)
    .unwrap()
    .send()
    .map_err(error::Error::from)
    .and_then(|resp| HttpResponse::build_from(&resp).streaming(resp))
    .responder()
```

**Comment by fafhrd91** [comment]
this may work

```rust

fn index(req: HttpRequest) -> Result<Box<Future<Item=HttpResponse, Error=Error>>, Error> {
    Ok(client::ClientRequest::build_from(&req)
        .uri(&url)
        .streaming(req)?
        .send()
        .map_err(error::Error::from)
        .and_then(|resp| HttpResponse::build_from(&resp).streaming(resp))
        .responder())
}
```

**Comment by fafhrd91** [comment]
i added example to guide, third example

https://actix.github.io/actix-web/guide/qs_4.html#async-handlers
