### ISSUE TITLE
Please return this repo to the original URL to not break existing projects.

### ISSUE THREAD

**Issue by easyaspi314** [actix/actix-web#1284]
By moving the project here and putting a dummy repo in place, you are causing many projects to fail to build, written by people who *respected* your code. 

Archiving it is a much better idea than trying to delete history.

See: https://github.com/actix/actix-web/issues/5

**Comment by bitemyapp** [comment]
I believe Nikolay said he was going to find some maintainers that he trusts for taking over the public version of the Actix repositories. I don't think bugging him about it will help anything, you're just going to have to wait and work around any issues for now.

**Comment by Pzixel** [comment]
Николай, спасибо тебе за твою работу.

Я знаком с тобой в основном по общениям чатах, и знаю как ты эмоционально реагируешь на многие вещи. 

Мне очень жаль что очередное закидывание какашками спровоцировало выгорание и нежелание развивать фреймворк дальше. Больше тысячи людей в телеграм чате телеграма выразили сочувствие твоей ситуации, на реддите большинство тоже считает, что тебя ни за что обидели (последняя статья клабника на эту тему вышла, возможно тебе будет интересно прочитать).

Актикс-веб наверное единственный адеватный веб-фреймворк на расте, и единственный для того, чтобы эффективно справляться с высокой нагрузкой. Мы на нашем проекте его использовали, и были очень рады, потому что он помог нам справиться с OOM и обрабатывать запросы с нужной скоростью.

Про то, чтобы ты не удалял проект тебе скажут многие, но как мне кажется тебе сейчас возможно не сильно важно, что там будет с проектом. Ты работал многие годы над открытым проектом, не получая знаков уважения, которые ты несомненно заслужил. Ты очень много души вкладывал в проект, и поэтому так больно реагировал на критику со стороны других людей. Мне кажется, ты _слишком_ много себя отдавал проекту, и поэтому произошло то, что произошло.

Не могу говорить за всё ру коммьюнти, но знай что очень много людей поддерживает тебя, и сожалеет, что интернет тролли которым безопасности оказалось "Недостаточно много" спровоцировали тебя на такие действия.

Напоследок хотел пару слов о проекте: пожалуйста, сотни проектов и тысячи людей зависят от него. Не дай пропасть своему труду, передай управление сторонним контрибуторам. Конечно же, оставайся сам одним из них, если у тебя есть такое желание, хотя я думаю, что ты уже давно больше тяготишься проектом, а не радуешься за него.

Мы с тобой. И береги себя.

---

For non-russian speakers: sorry for writing it in native language but as I have seen Nikolay is not perfect in English (so am I), so I did it to express my thoughts on the matter more precisely. Use google translate (ru->en) if you are interested in translation.

**Comment by kfogel** [comment]
But why remove the project from view while doing that?

**Comment by rhzs** [comment]
What is the requirement to become maintainer?? There are a lot of people including me who gladly to become main maintainer to uphold open source foundation.

**Comment by naturallymitchell** [comment]
> you're just going to have to wait and work around any issues for now.

One URL path segment is easily within your power to address.

**Comment by kajmagnus** [comment]
> By moving the project here

I understand that's annoying — at the same time, is there an upside? Namely that people notice that something has changed (when their build breaks or sth like that), and go to the Actix-Web repo, and see the *"Actix project postmortem"* readme. — It's a bit important that people who use Actix read it?

I like Actix, @rhzs I hope there'll be some maintainers & future development :- ). I'm just about to continue learning Rust and building a web app based on Actix.
