### ISSUE TITLE
Спасибо тебе, Николай, за твою работу. Мне очень жаль, что так получилось

### ISSUE THREAD

**Issue by Pzixel** [actix/actix-web#1285]
Николай, спасибо тебе за твою работу.

Я вижу, как много людей просят, чтобы ты не удалял проект, и оставил его. Но очень мало кто говорит не о нем, а о тебе, как о человеке, который пострадал от неконструктивной критики.

Я знаком с тобой в основном по общениям чатах, и знаю как ты эмоционально реагируешь на многие вещи.

Мне очень жаль что очередное закидывание какашками спровоцировало выгорание и нежелание развивать фреймворк дальше. Больше тысячи людей в телеграм чате телеграма выразили сочувствие твоей ситуации, на реддите большинство тоже считает, что тебя ни за что обидели (последняя статья клабника на эту тему вышла, возможно тебе будет интересно прочитать).

Актикс-веб наверное единственный адеватный веб-фреймворк на расте, и единственный для того, чтобы эффективно справляться с высокой нагрузкой. Мы на нашем проекте его использовали, и были очень рады, потому что он помог нам справиться с OOM и обрабатывать запросы с нужной скоростью.

Про то, чтобы ты не удалял проект тебе скажут многие, но как мне кажется тебе сейчас возможно не сильно важно, что там будет с проектом. Ты работал многие годы над открытым проектом, не получая знаков уважения, которые ты несомненно заслужил. Ты очень много души вкладывал в проект, и поэтому так больно реагировал на критику со стороны других людей. Мне кажется, ты слишком много себя отдавал проекту, и поэтому произошло то, что произошло.

Не могу говорить за всё ру коммьюнти, но знай что очень много людей поддерживает тебя, и сожалеет, что интернет тролли которым безопасности оказалось "Недостаточно много" спровоцировали тебя на такие действия.

Напоследок хотел пару слов о проекте: пожалуйста, сотни проектов и тысячи людей зависят от него. Не дай пропасть своему труду, передай управление сторонним контрибуторам. Конечно же, оставайся сам одним из них, если у тебя есть такое желание, хотя я думаю, что ты уже давно больше тяготишься проектом, а не радуешься за него.

Мы с тобой. И береги себя.

For non-russian speakers: sorry for writing it in native language but as I have seen Nikolay is not perfect in English (so am I), so I did it to express my thoughts on the matter more precisely. Use google translate (ru->en) if you are interested in translation.

**Comment by anurbol** [comment]
Да правильно сделал всё. Кто-то должен был поднять эту тему. Вокруг эпидемия неблагодарности и "entitlement"-а.

**Comment by fafhrd91** [comment]
Спасибо!

**Comment by chertov** [comment]
Тоже хочу высказаться в поддержку автора actix! Николай, Спасибо тебе Большое!! Твоя работа крайне важна и намного более востребована чем может показаться!

Скорее всего я не смогу подобрать нужных слов чтобы как-то существенно поддержать, слишком уж я "толстокожий". Негативные мнения в отношении меня или в отношении дел/проектов (как моих, так и чужих) меня никогда особо не тревожили, поэтому я не в полной мере могу корректно понимать и воспринимать произошедшее.
Но я вот могу описать чем результат труда Николая для меня является и насколько он оказался важен!

Я использую actix практически без actix-web и просто кайфую от того удобства которую предоставляет мне actix в сочетании с гарантиями надежности, удобства кроссплатформенноcти, удобства разработки которую представляем сам rust! Поверх actix запилил уже достаточно много небольших приложений, компонентов, tcp/udp сервисов.. все это работает на дохлых камерах видеонаблюдения, а так же в облаке и не падает! никогда! аптайм уже более полугода на тестовой уличной камере видеонаблюдения. Только с нее за это время почти 300'000 фото actix загрузил в телеграм, 6Тб видео записал, периодически стримит видео по p2p, каждый день наблюдает закаты и рассветы!) Я уже потерял всякую надежду на то что оно упадет и я найду новую багу в моем софте! Единственное где я пока не смог использовать актикс это wasm в браузере на стороне клиента, но возможно я что-то упустил, буду надеяться что и там смогу когда-нибудь! После такого переворота в технологиях мне уже страшно писать на Си и даже Golang) я относительно слабый программист, но раст и актикс позволяют даже мне создавать продукт и работать по большей части над функционалом. Скорее всего без этих вещей я бы не достиг моих текущих результатов! Это просто офигенное чувство когда написание кода доставляет удовольствие и ты кайфуешь каждый день от кода, от его работы и от работы над ним, от надежности и качества продукта!

Николаем проделана офигенная работа, actix реально двигает технологии вперед и меняет мир! Для меня actix это практически единственное, что дало возможность легко погрузиться в rust и начать использовать его возможности. Уже и не представляю как без actix делать асинхронный код на голых фьючах.. таскать с собой состояние в каком-нибудь Arc<Mutex<..>>.. страшный сон.. модель акторов в actix для меня оказалась невероятно удобна, всегда доступный &mut self, сообщения между акторами! Настолько привык, что теперь мне страшно что Николай закроет свои проекты.. угроза ядерной войны и мирового финансового кризиса меня не так пугает как риск потери такого крутого инструмента!)

Я уверен что адекватные люди, которые нашли какие-либо слабые стороны или варианты улучшения проекта, всегда бы смогли нормальным образом донести решение до автора, сделать прототипы/реализации новых идей, патчи и тд. Такие действия не могли бы никак привести к каким-либо негативным последствиям для проекта, разработчиков и сообщества.
Считаю не стоит обращать никакого внимания на каких-либо негативно настроенных личностей.. уверен они не преследовали никаких других целей кроме того чтобы нести негатив, испортить настроение и автору, и сообществу. Никому не стоит на них тратить время, а особенно время человека который способен делать такие крутые вещи как actix!
Кто бы там что ни говорил, а актиксом пользуются много людей и он отлично работает! Уверен что у Николая есть идеи как сделать свои проекты еще лучше и очень надеюсь что будут для этого все возможности и желание, а также помощь сообщества. Вроде бы в среде разработчиков в основном должны быть образованные и воспитанные люди, но видимо это не совсем так и не всегда. Скорее всего ненавистники рано или поздно неизбежно появятся.. для меня это как плохая погода или стихийное бедствие, хотелось бы конечно, чтобы их не было, но, к сожалению, это неизбежность.. проект уже офигенный и может стать еще лучше, просто не стоит обращать на хэйтеров внимания, или хотя бы не воспринимать их так близко.. "собака лает, поезд идет".. На одного ненавистника есть тысяча-другая благодарных разработчиков, десятки-сотни их крутейших продуктов и миллионы счастливых пользователей!

Я как раз один из тех разработчиков которые пользуются проектом и не заглядывают в "Issues" просто потому что все отлично работает и никаких проблем нет. Это тоже некоторый показатель качества проекта. Даже и не подумал бы что тут могут быть проявления негатива.. так что в противовес негативным личностям хочу привнести немного позитива)

Буду верить в светлое будущее! кто бы там чего не писал..
