### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#1289]
I realized, a lot of people depends on actix. And it would be unfair to just delete repos. I promote @JohnTitor to project leader. He did very good job helping me for the last year. I hope new community of developers emerge. And good luck!

**Comment by krircc** [comment]
@fafhrd91 Thank you, and Please stay well.

**Comment by berkus** [comment]
Please stay well, Nikolay! And good luck.

**Comment by sergeysova** [comment]
@fafhrd91 thank you, for your work

**Comment by VadimGaltsev** [comment]
thank you! U are the best!!!

**Comment by leekt** [comment]
@fafhrd91 Thank you for everything

**Comment by AlphaHot** [comment]
Hooray! @JohnTitor the best!

**Comment by captain-yossarian** [comment]
@fafhrd91 Thank you!

**Comment by adelarsq** [comment]
@fafhrd91 Thanks for your effort on this!

**Comment by saifali96** [comment]
@fafhrd91 Thank you very much Nikolay, you have made a very wise decision! All the best for your future endeavors.

**Comment by MechanicalOrange5** [comment]
Thank you @fafhrd91. Your years of hard work is appreciated beyond what you might know. I hope this will be a good thing for you personally, and the actix projects.

**Comment by JordiPolo** [comment]
@fafhrd91 Thank you for your work. If you have not see it, the community wrote you a [letter](https://github.com/actix-support/letter)

**Comment by TheBestJohn** [comment]
Nikolay, thank you so much for your time, effort and absolute selflessness in sharing your project. I hope you stay well and continue to do things that are fun and interesting for you. I know how difficult it is to show something that's as close to you and bare it open for people to criticize. Cheers to you friend!

**Comment by kosson** [comment]
@fafhrd91 I felt encouraged to pick up on Rust because of your work. Gave me a lot of courage to take this leap of faith. Thank you for your time and this fabulous gift - time from your life time. A long bow. I will keep learning Rust! Thank you!

**Comment by In-line** [comment]
I hope that with the new leadership, you can have a good rest for all the hard work that you have done for the community.

Now it doesn’t matter who was right or who was wrong. Your decision today shows your attitude towards the community. This is what matters.

Thank you very much for your past, present and future hard work!

**Comment by ice-creamer** [comment]
@fafhrd91 Thank you for your decision. And good work.

**Comment by wilyceef** [comment]
@fafhrd91 Thank you very much.

**Comment by nnovikov** [comment]
@fafhrd91 Thank you!

**Comment by sidekick101** [comment]
Thank you so much , your effort is deeply appreciated.

**Comment by Immortalin** [comment]
@fafhrd91 thank you for everything that you have given us. Please don't give up on contributing to open source.

**Comment by imtsuki** [comment]
@fafhrd91 Thanks! Wish you all the best!

**Comment by TakehiroTada** [comment]
@fafhrd91  NICE!!!! Thank you! :)

**Comment by yim7** [comment]
thank you, for your work.

**Comment by akidsuki** [comment]
@fafhrd91 Thank you!!

**Comment by rollschild** [comment]
@fafhrd91 Thank you. We understand the frustration and appreciate your work. This is good news.

**Comment by a3d0n** [comment]
@fafhrd91 Thank you ❤

**Comment by danylaporte** [comment]
@fafhrd91 Thank you very much! Wish you the best! Thanks for your work! I really appreciate.

**Comment by barryblando** [comment]
Thank you! Appreciated! For Rust!

**Comment by lcmartinsfilho** [comment]
Thank you!

**Comment by Acanguven** [comment]
Great decision! Thank you.

**Comment by niofis** [comment]
Thank you!

**Comment by angel-afonso** [comment]
Thank you very very much!

**Comment by Exegetech** [comment]
Yaaay!

**Comment by MajorFailz** [comment]
Woop!! :) Thanks dude! I've just been learning actix web for a project and was like nooooooooo when I read the news. Thanks for keeping it going in some form and for all the good work you've done :)

**Comment by chrish42** [comment]
Thank you for all the work you've done. And really sorry about all the... negative energy present in some corners of the opensource world. Hopefully we'll figure out a way to alleviate that problem in the future.

**Comment by azymohliad** [comment]
Thank you!

**Comment by EthanYidong** [comment]
Thank you @fafhrd91 for all your hard work.

**Comment by Adeynack** [comment]
The King is dead. Long live the King!

But seriously, thanks. I understand there was a lot of shit raining on you about this project, but deleting the repos would have been a shame, without allowing people to at least fork them to continue on their own maintaining it.

Transferring ownership is an even better solution!

Anyways, thanks for all the work you've done. It's just ironic that I started checking for REST frameworks 1 day before Actix got officially discontinued :O

**Comment by danbruder** [comment]
Thank you for all of your great work! @fafhrd91

**Comment by karakaplanm** [comment]
Thank you!

**Comment by larspederamlie** [comment]
Thank you:)

**Comment by jdd-rb** [comment]
No matter what some people might say about this or that line of code, you were the project leader for one of the most used web servers available in the whole of the rust language. That's an incredible achievement which try as they might, many fine coders around the world will not match.

It's clear when it comes to Rust you are best in class, and that's something that will be true of you for many years to come. You've genuinely made a huge contribution to the community, and you should be nothing but proud of the work you have done. Top class.

Well done @fafhrd91 - your sky high achievement is something for the rest of us to strive for.

**Comment by Malanche** [comment]
@fafhrd91 Thank you a lot for all your hard work! I hope this marks a tipping point for the community to realize the effort it takes to build such a great framework, and we need to get involved in a constructive way to make it even better. The kindness you show with these actions is an example for all the community. I hope you stay well, and I wish this will get better for all in the near future. Respect!

**Comment by dessalines** [comment]
@fafhrd91 I'm using your actix in https://github.com/dessalines/lemmy , and I couldn't be happier with its performance, and support. Thank you for all your hard work!

**Comment by durnosmih** [comment]
@fafhrd91 Thank you so much for your work. You did really great job and I hope that your repo stay active even more as it was 🚀.

And also don't abandon opensource. There are a lot of nice people to work with and a lot of ideas to realize.

**Comment by zareone** [comment]
Thank you very much!

**Comment by SRGOM** [comment]
@fafhrd91 THank you so much. I sincerely hope that you will take back the reins one day, only because this would mean you've learnt the ignore the "entitled crowd".

@JohnTitor A very good luck. As I noted here- https://github.com/actix/actix-web/issues/1019#issuecomment-517568283 you are obviously good with the first two points. I hope you can handle the pressure and the partially toxic rust community. If it were up to me- I would add a CoC which would instantly ban and delete issues/PR from entitled people, so as to nip in bud any kind of toxic behavior.

**Comment by timvisee** [comment]
Brilliant! Thanks for the work and this amazing piece of software, from both of you.

**Comment by seyiade50** [comment]
Thanks a lot Nikolay. I am doing some swell stuff with actix and I would love to keep you posted. 

Actix rocks!

**Comment by Ruddickmg** [comment]
The framework you created is awesome, fun to work with and fast as hell! Thank you for all you've done!

**Comment by shirshak55** [comment]
Thanks @fafhrd91 . I am sure new maintainer will also give priority to performance,ergonomics and safety just like you did. 

Thanks :)

**Comment by artemshein** [comment]
Thank you! Hope you'll be back, your work much more important than all the haters shitposting, just ban them all ;-).

**Comment by smorin** [comment]
Thanks @fafhrd91  , sorry you had to deal with this situation.  I am sure it can be very frustrating.

**Comment by winding-lines** [comment]
Thank you Nikolay!

**Comment by milesgranger** [comment]
You're a legend, Nikolay!! :100:

**Comment by dewey4iv** [comment]
To @fafhrd91: I'm sure it's obvious, but I don't want it to go without saying: the Rust web/http ecosystem wouldn't be what it is today without your selfless contributions to the community. Thank you.

To @JohnTitor: Welcome and congratulations! Thank you for agreeing to pick up this project. I have every confidence that you'll continue to keep the project moving forward. I'd like to offer whatever help in whatever form would be most beneficial.

**Comment by thorjelly** [comment]
Thank you so much. I'll always appreciate what you did for the Rust community. I'm sorry so much turned difficult. I hope the best for your future. And I apologize for all the people who said a lot of terrible things.

**Comment by Aaron1011** [comment]
@fafhrd91: As the author of PR https://github.com/actix/actix-web/pull/968, I'm sorry if I made this whole situation worse in any way. You've made an incredible project, and I only ever intended to help.

Thanks for all of your hard work!

**Comment by zeroxff** [comment]
Thanks!

**Comment by xudesheng** [comment]
@fafhrd91 Thank you! 
I can continue my third microservice on top of actix-web now.
Always appreciate your hard work!

**Comment by Snipey** [comment]
Thank you :)

**Comment by zmilan** [comment]
You made my day, this is awesome news. Thanks a lot for everything, I hope you will recover from this situation asap. 
Thanks for all your hard work and stay good.

**Comment by anthonyjchriste** [comment]
Great news. Thank you.

**Comment by pfrenssen** [comment]
Thanks for this amazing project and your great support!

**Comment by zeroows** [comment]
Thank you so much for all your work on this and Good luck

**Comment by RyanLassigBanks** [comment]
Thank you for all of your hard work! Best of luck!

**Comment by akram-bhs** [comment]
thanks @fafhrd91 👍👏

**Comment by nicolaiunrein** [comment]
I am really glad you took this step! When I read about the end of actix-web friday night I could not believe it. I always thought actix-web will be THE go-to web-framework in future-Rust. Something like Express in Node. Over the weekend I again looked into the alternatives but none could really deliver what actix-web gives us (async, stable rust, multi-part and much more...). Thinking about switching to another framework really depressed me.
Thank you for your work and all the best for your future.

**Comment by tommket** [comment]
@fafhrd91 Thanks for passing the torch, probably too much people started to depend on your project so they tended to nitpick it. Take some much needed rest.

**Comment by alosarjos** [comment]
Thanks a lot for you hard work @fafhrd91. I hope you don't give up at all on OSS. Actix is an amazing project. Hoping the best for you.

**Comment by Deprecatedoldaccount321** [comment]
Hey thanks for such a wonderful tool.  Hope you find more projects that interest you forward. GL.

**Comment by lovasoa** [comment]
Thank you !

**Comment by joshhansen** [comment]
Thank you for all your efforts. Best wishes.

**Comment by njust** [comment]
Thank you!

**Comment by JohnTitor** [comment]
Thanks @fafhrd91! We, the community and I, will do our best to maintain the actix project.

**Comment by toddtreece** [comment]
@fafhrd91 thank you for your work! as someone relatively new to rust, it has been great to work with actix, and i am happy to see that the project will live on.

**Comment by zzy** [comment]
@fafhrd91 You're a legend! Thank you for everything. Please stay well, and best of luck!
@JohnTitor You’re the best, a very good luck.

**Comment by slanterns** [comment]
@fafhrd91 Fully appreciate your great contribution to the community, and enjoy your future life!

**Comment by micouy** [comment]
@fafhrd91 Thank you!

**Comment by 3c1u** [comment]
@fafhrd91 Glad to hear this news, thank you!

**Comment by plus7wist** [comment]
@fafhrd91 thank you for your work!

**Comment by phjeltman** [comment]
@fafhrd91 Actix is really great. Many thanks for your fantastic work on this project!

**Comment by bb010g** [comment]
@fafhrd91 Thank you so much for the work you've done with Actix's code & community. And thank you for the smooth transition to @JohnTitor's leadership, so Actix may go even further beyond, without the mars of a rough community split.

**Comment by alienzj** [comment]
Thanks @fafhrd91

**Comment by DanSnow** [comment]
Thanks for your work

**Comment by llgoer** [comment]
Thanks @fafhrd91

**Comment by jesse996** [comment]
Thank you very much for what you've done

**Comment by jetli** [comment]
A HAPPY day for RUST!

**Comment by lisun** [comment]
Thanks @fafhrd91

**Comment by lygz5016** [comment]
@fafhrd91 Thank you for your work!

**Comment by UkonnRa** [comment]
Thanks for your contribution and stay happy~ @fafhrd91

**Comment by Smicry** [comment]
Thanks for your work!

**Comment by BBDXF** [comment]
Thanks for your work!😊

**Comment by toplinuxsir** [comment]
A wise decision ! Thanks  for you work!

**Comment by EvanCarroll** [comment]
Much love for this. Thanks a ton @fafhrd91. Sorry to see you leave the open source community. Good luck to you wherever you end up going.

**Comment by x1957** [comment]
Thanks! a happy day!

**Comment by lmumar** [comment]
Thank you!!!!

**Comment by JmPotato** [comment]
Thanks for all the work you done for Rust and community!

**Comment by laike9m** [comment]
El Psy Kongroo

**Comment by marcusradell** [comment]
Thank you <3

**Comment by Norbytus** [comment]
Thank you for your work and good luck

**Comment by henriktorget** [comment]
Thanks a lot!

**Comment by uCryNet** [comment]
Thanks bro! We are with you. Everything will be OK

**Comment by Shushtank** [comment]
Ты лучший, не ссы - прорвемся!)

**Comment by Speedy37** [comment]
Thanks @fafhrd91

**Comment by robinmoussu** [comment]
Thanks @fafhrd91, and I wish you the best in this one or any other of your projects.

**Comment by silven** [comment]
Thank you for your great work on this, I wish you the best.

**Comment by swr1bm86** [comment]
Thanks for everything! @fafhrd91

**Comment by csaf4370** [comment]
Awesome, great decision! Thank you and all the best for you!

**Comment by efleurine** [comment]
I plan to learn a bit more of Rust this year and it actix-web for sure.
keep moving forward

**Comment by richardchey** [comment]
Thanks @fafhrd91

**Comment by leizzer** [comment]
Thank you for your work!!

**Comment by Deseteral** [comment]
Thank you for your good work and take care! :D

**Comment by nshcat** [comment]
Thank you for all the work you did for the Rust community!

**Comment by ptravers** [comment]
@fafhrd91 thanks so much for your work! I'm sorry people did not treat you with the respect and decency people deserve

**Comment by ChristophWurst** [comment]
Thank you! :)

**Comment by ghost** [comment]
I learned my lesson well. You need to have control over a framework. Write your own!

For me Rust is dead!

Thanks for your awesome work, nevertheless!

**Comment by cerceris** [comment]
Thank you, Nikolay! Actix is awesome! It's a shame that you were forced to leave the project this way. Unbelievable how people, especially individuals from the "friendly" Rust community, might be such ungrateful. Unfortunately morons exist everywhere. And we have to live with this fact :(
Good luck to you, Sir! And thank you again for your amazing work!

**Comment by oronsh** [comment]
Thank you so much @fafhrd91 <3

**Comment by cndkhuong** [comment]
Thank and wish the best for you @fafhrd91

**Comment by zzFluke** [comment]
Thank You a lot @fafhrd91! Personally I lean more to  "if it works and somebody take responsibility to maintain it then who cares whether `unsafe` there"

**Comment by xujq1** [comment]
@fafhrd91 Please stay well, Nikolay!  
Actix is a great project, please keep on and stay well
Ignore their noises

Good luck to you

**Comment by mthgr** [comment]
You clearly created something that became bigger than yourself and that in itself is an accomplishment most of us will be denied in this life. You were also able to let go which is an equal accomplishment in my book.

And for this, I salute you.

**Comment by mariopal** [comment]
@fafhrd91 Thank you!

**Comment by crusty-dave** [comment]
@fafhrd91 Thanks Nikolay for all that you have done.  Sorry to hear that you are leaving the project, hopefully it will continue to grow under the new leadership.

**Comment by realcr** [comment]
@fafhrd91 : Thank you for all the great work!

**Comment by vroussea** [comment]
Thank you for your work, and all the help you provided.

**Comment by Nicolab** [comment]
@fafhrd91 Your excellent work on Actix will live on. Thank you for everything.

**Comment by boundless-forest** [comment]
@fafhrd91  Thank you for your excellent work.

**Comment by ksangabriel** [comment]
@fafhrd91 Thank you, sir! Thank you! Thank you!

**Comment by schrepfler** [comment]
Thanks @fafhrd91 !!!

**Comment by jturnersm** [comment]
Thank you @fafhrd91 I enjoyed using Actix to explore Rust.

**Comment by sdegutis** [comment]
To be clear about my thumbs-down on the issue, I don't support anyone being ousted from their own project for any reason. Discussing, collaborating, and forking are all good options. Shaming, berating and ousting should not be tolerated. 👎

**Comment by ghost** [comment]
Thanks for great work. I used actix , and report issue, and watching for it's envolved.

**Comment by gagarin55** [comment]
@fafhrd91, Thank you for your excellent work.
Man, life is not a fun game, it is a fighting for resources game. You shouldn't even react on those comments. Trolls attacked you and took over your great project.

**Comment by xiazhouquan** [comment]
Thank you for your excellent work

**Comment by bsjung** [comment]
Thank you for great work.

**Comment by madgene** [comment]
Thank you very much for your great work.

**Comment by dave-filion** [comment]
This is great! Thanks for all your hard work!!

**Comment by ossdesign** [comment]
I came to this page via an article I just read. I am not a Rust programmer (let a lone much of a programmer at all), but do lots of varied IT works and dabble all over the place. I read the article to learn some Rust context.

While reading the last paragraph, I started thinking "welcome to the internet, where (at least in some places) it is 'mob rules', and those that shout the loudest 'win', not what might be actually true or reasonable." It is clearly a huge problem in some places out there, as we all know. But in the technical community, it would be nice to see this more tempered.

From reading most of the comments here, it sounds like you are appreciated. And me not actually being part of the community, but having gotten a quick learner in some things, just wanted to pass on my own kudos and thanks to you, some day I may try my hand at using the framework you put some much time and effort into creating!

**Comment by JJBordy** [comment]
@fafhrd91 Thank you!

**Comment by ruseinov** [comment]
Very happy with Actix, just started a couple of pretty important projects using it as opposed to alternatives, never looked back!

**Comment by tramjoe** [comment]
Found this thread from a youtube video explaining the UB PRs story and giving a timeline of events. Wanted to chime in and say that I support and feel the pain and frustration you must have endured @fafhrd91 . Keep at it, putting work out for a community to use does not mean you should be the community's slave.

**Comment by AryanBeezadhur** [comment]
@tramjoe looks like we're here from Ben Awad's channel! :joy:

❤️

**Comment by ALiwoto** [comment]
@fafhrd91 Ohh Nikolay... thanks for all of your efforts on this project. Please stay well.
