### ISSUE TITLE
URL Requests are truncated via proxy

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#129]
I'm seeing some weird stuff when trying to proxy requests with large URLs (around 400 characters), whereby it looks like the buffer is overriding the HTTP request headers.

As an example, if set up a proxy to a URL `/blah` and append the query params from the client. 

If I have a small amount of characters, I see this in wireshark:
```
GET /blah?sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss= HTTP/1.1
host: 127.0.0.1
....
```

If I append more characters, to the request, then the URL is completely truncated out:

```
GET host: 127.0.0.1
....
```

Not really sure what's happening here.

**Comment by DoumanAsh** [comment]
@cetra3 Can you check `uri` of your requests? Is it truncated there too?
All requests/responses have `uri()` method to access it

**Comment by cetra3** [comment]
the URL starts off as a `String`, then I use the ClientRequestBuilder to set the uri.

If i print out the URL beforehand, it does not appear truncated.

**Comment by cetra3** [comment]
Looking at the code, it appears the `HttpClientWriter` is only allocated [256 bytes](https://github.com/actix/actix-web/blob/master/src/client/writer.rs#L115) for the status line, which may be the culprit

Is there a way to ensure that the buffer is always the appropriate size?

I'm not sure what happens to that type of buffer if the `write!` call is oversized

**Comment by fafhrd91** [comment]
That is bug

**Comment by fafhrd91** [comment]
fixed in master
