### ISSUE TITLE
Format of sequence query parameters?

### ISSUE THREAD

**Issue by vimpunk** [actix/actix-web#1301]
Can I pass a list of things as a query parameter with actix? Trying to deserialize into a `Vec<i32>` gives me the following error response:
```
Query deserialize error: invalid type: string "[1,2]", expected a sequence
```
Which suggests to me it is possible, but the format is incorrect.

I tried `ids=[1,2]`, `ids={1,2}`, escaping special chars (`[]{},`), all to no avail. Insight would be much appreciated.

BTW : I'm really happy actix is back! Thanks again!

**Comment by tyranron** [comment]
@mandreyel `ids=[1,2]` and `ids={1,2}` is not a standard HTTP way of doing this, so `actix-web` doesn't deal with them out-of-the-box.

The appropriate one would be: `ids[]=1&ids[]=2`.

But still, if you need to deal exactly with `ids=[1,2]`, you have the following options:
1. Just accept `ids` argument as string and deserialize it manually.
2. Create you own type to represent such arguments and implement [FromRequest](https://docs.rs/actix-web/2.0.0/actix_web/trait.FromRequest.html) for it. Now you can use this type as a handler function argument.

**Comment by vimpunk** [comment]
@tyranron Thanks for the response! I'll try `ids[]=1&ids[]=2`.

**Comment by tyranron** [comment]
@mandreyel nice! Please, do not forget to close this issue once/if you will think it's resolved for you.

**Comment by onelson** [comment]
I could be remembering this incorrectly, but I think there was a limitation with the dependency actix-web uses in the `Query` extractor that actually squashes repeated keys in the query string.

We ended up using something like this to convert Query extracted fields from `Option<String>` to a vec of T.

```rust
/// A trait to help convert things into vecs of different values, such as shotgun ids.
///
/// The initial use case is the converting of `Option<String>`s coming in
/// from query params as CSV.
trait AsCSV {
    fn as_csv<T>(&self) -> Result<Option<Vec<T>>, ()>
    where
        T: std::str::FromStr;
}

impl<S> AsCSV for Option<S>
where
    S: AsRef<str>,
{
    fn as_csv<T>(&self) -> Result<Option<Vec<T>>, ()>
    where
        T: std::str::FromStr,
    {
        match self {
            Some(ref s) if !s.as_ref().trim().is_empty() => {
                let mut acc = vec![];
                for s in s.as_ref().split(',') {
                    let item = s.trim().parse::<T>().map_err(|_| ())?;
                    acc.push(item)
                }
                if acc.is_empty() {
                    Ok(None)
                } else {
                    Ok(Some(acc))
                }
            }
            _ => Ok(None),
        }
    }
}
```

https://gist.github.com/onelson/1b1d899ad4c616e171c7172809961671

**Comment by erdfern** [comment]
> @tyranron Thanks for the response! I'll try `ids[]=1&ids[]=2`.

I'd be interested whether or not this works for you. In my experience `param[]` is recognized to be a different name from `param`, meaning I'd get a `Query deserialize error: missing field 'param'` when using this notation. A while ago, I've tried every sequence notation for querystrings I could dig up, but to no avail.

I've had this issue - trying to deserialize sequence query parameters - since I've started to implement some network services with actix-web a few months back. From discussing this in the actix gitter channel, I gathered that it's a limitation of the `serde_urlencoded` crate, which is used to parse querystrings in actix-web. There's an alternative, [`serde_qs`](https://github.com/samscott89/serde_qs), which may enable parsing querystrings with nested parameters. There's an actix interop available, with a [pending pull request](https://github.com/samscott89/serde_qs/pull/25) for v2 support.

I never got it to work for me, though.

Since my requirement was to merely parse sequence parameters in `simple` notation - meaning just one parameter with comma separated string value -, I bit the bullet and simply implemented trivial functionality to parse it myself. I had spend way to much time on trying to appease the deserialization mechanism supplied with actix-web - also driven by the error messages which seemingly suggested that I just had to get the notation right - to keep on bothering.

**Comment by zero-systems** [comment]
Actix uses serde for deserializing queries, I can suggest you try to impelement your own serde Deserializer trait for query struct. It should fix your problem

**Comment by vimpunk** [comment]
@Decisional Unfortunately it didn't work for me either. I'll experiment with other solutions suggested by zero-systems and onelson.

**Comment by sify21** [comment]
What's the status of this issue? I don't see any issues related in `serde_urlencoded`.
It's a common use-case. For example when you want to delete multiple entries, the http spec don't encourage you to put data in the delete body, so you have to pass ids in query string.

**Comment by jplatte** [comment]
I don't think there's been any movement on this. `serde_urlencoded`s author has closed any issues that asked for this feature, because it would complicate the code and at least for `foo=bar&foo=baz` (as opposed to `foo[]=bar&foo[]=baz`) requires additional state tracking and possibly allocations.

However, this doesn't need to be supported in `serde_urlencoded` for it to be possible to parse query strings. You can declare `req: HttpRequest` as an extractor on any route and use `serde_qs::from_str(req.query_string())` to deserialize the query string using [serde_qs](https://crates.io/crates/serde_qs). `serde_qs` only has an implementation of the notation with the square brackets, but I've also forked `serde_urlencoded` into [`ruma_serde::urlencoded`](https://docs.rs/ruma-serde/0.2.3/ruma_serde/urlencoded/index.html) to support the other syntax. I could put it in a separate crate if there is interest in that.

**Comment by vimpunk** [comment]
It's true that no changes are required in `serde_urlencoded` for this. We can just implement custom deserializers.

E.g. to parse the following query parameter: `ids={uuid1},{uuid2},...`, you could do:

```rust
#[derive(Deserialize)]
pub struct Query {
    #[serde(deserialize_with = "deserialize_stringified_uuid_list")]
    pub ids: Vec<Uuid>,
}


pub fn deserialize_stringified_uuid_list<'de, D>(deserializer: D) -> Result<Vec<Uuid>, D::Error>
where
    D: de::Deserializer<'de>,
{
    struct StringVecVisitor;

    impl<'de> de::Visitor<'de> for StringVecVisitor {
        type Value = Vec<Uuid>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a string containing a list of UUIDs")
        }

        fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            let mut ids = Vec::new();
            for id in v.split(",") {
                let id = Uuid::parse_str(id).map_err(E::custom)?;
                ids.push(id);
            }
            Ok(ids)
        }
    }

    deserializer.deserialize_any(StringVecVisitor)
}
```

This has the benefit of being able to use the query struct as is, without further conversions needed, as it's already type safe.

**Comment by ghost** [comment]
> We can just implement custom deserializers.

This is a nice walk around. However, frameworks should support multiple URL parameters out of the box, right?
Can we clarify it? Is it *won't fix* or there is an issue for it or new one should be created?

**Comment by robjtede** [comment]
Changing the way the current Query extractor works, even in a breaking release, would be pretty distruptive. There's a discussion to be had around how to support the standardized ways of passing array-ish values but not in this issue. This one has a satisfactory answer of custom deserializers.

**Comment by ghost** [comment]
@robjtede good to know, thanks. Would be awesome to link the discussion here in future ;)

**Comment by robjtede** [comment]
@xliiv Feel free to get the discussion going. We'd be happy to look at proposals and experimental PRs if you'd like.

**Comment by platy** [comment]
Based on @mandreyel 's custom deserialiser above, here's one for a generic list which I think will fix this issue satisfactorily for my use case:

```rust
use serde::{de::{self, IntoDeserializer}, Deserialize};
use std::fmt;
use uuid::Uuid;

#[derive(Deserialize)]
pub struct Query {
    #[serde(deserialize_with = "deserialize_stringified_list")]
    pub ids: Vec<Uuid>,
}


pub fn deserialize_stringified_list<'de, D, I>(deserializer: D) -> std::result::Result<Vec<I>, D::Error>
where
    D: de::Deserializer<'de>,
    I: de::DeserializeOwned,
{
    struct StringVecVisitor<I>(std::marker::PhantomData<I>);

    impl<'de, I> de::Visitor<'de> for StringVecVisitor<I>
    where I: de::DeserializeOwned {
        type Value = Vec<I>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a string containing a list")
        }

        fn visit_str<E>(self, v: &str) -> std::result::Result<Self::Value, E>
        where
            E: de::Error,
        {
            let mut ids = Vec::new();
            for id in v.split(",") {
                let id = I::deserialize(id.into_deserializer())?;
                ids.push(id);
            }
            Ok(ids)
        }
    }

    deserializer.deserialize_any(StringVecVisitor(std::marker::PhantomData::<I>))
}
```

**Comment by miguelcaravantes** [comment]
> Based on @mandreyel 's custom deserialiser above, here's one for a generic list which I think will fix this issue satisfactorily for my use case:
> 
> ```rust
> use serde::{de::{self, IntoDeserializer}, Deserialize};
> use std::fmt;
> use uuid::Uuid;
> 
> #[derive(Deserialize)]
> pub struct Query {
>     #[serde(deserialize_with = "deserialize_stringified_list")]
>     pub ids: Vec<Uuid>,
> }
> 
> 
> pub fn deserialize_stringified_list<'de, D, I>(deserializer: D) -> std::result::Result<Vec<I>, D::Error>
> where
>     D: de::Deserializer<'de>,
>     I: de::DeserializeOwned,
> {
>     struct StringVecVisitor<I>(std::marker::PhantomData<I>);
> 
>     impl<'de, I> de::Visitor<'de> for StringVecVisitor<I>
>     where I: de::DeserializeOwned {
>         type Value = Vec<I>;
> 
>         fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
>             formatter.write_str("a string containing a list")
>         }
> 
>         fn visit_str<E>(self, v: &str) -> std::result::Result<Self::Value, E>
>         where
>             E: de::Error,
>         {
>             let mut ids = Vec::new();
>             for id in v.split(",") {
>                 let id = I::deserialize(id.into_deserializer())?;
>                 ids.push(id);
>             }
>             Ok(ids)
>         }
>     }
> 
>     deserializer.deserialize_any(StringVecVisitor(std::marker::PhantomData::<I>))
> }
> ```

this works for `Vec<String>` but not for `Vec<i32>`

**Comment by jbtobar** [comment]
> 

in case it helps here, this works for `Vec<usize>`. More precisely for `Option<Vec<usize>>` which is what I needed in my case, but you can change the `Option<Vec<usize>>` in the fn result and return of `visit_str`. Basically its same as above expect removing the `I` param. (commented out what I removed)

```rust
pub fn deserialize_stringified_list<'de, D>(deserializer: D) -> std::result::Result<Option<Vec<usize>>, D::Error>
where
    D: de::Deserializer<'de>,
    // I: de::DeserializeOwned,
{
    struct StringVecVisitor(std::marker::PhantomData<usize>);

    impl<'de> de::Visitor<'de> for StringVecVisitor
    // where I: de::DeserializeOwned
    {
        type Value = Option<Vec<usize>>;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a string containing a list")
        }

        fn visit_str<E>(self, v: &str) -> std::result::Result<Self::Value, E>
        where
            E: de::Error,
        {
            let mut ids = Vec::new();
            for id in v.split(",") {
                // let id = usize::deserialize(id.into_deserializer())?;
                let id = id.parse::<usize>().map_err(de::Error::custom)?;
                ids.push(id);
            }
            Ok(Some(ids))
        }
    }

    deserializer.deserialize_any(StringVecVisitor(std::marker::PhantomData::<usize>))
}
```

**Comment by decapo01** [comment]
Note for any one that comes across this in the future I used the solution from this issue

https://github.com/actix/actix-web/issues/786#issuecomment-484259799

They are using this [crate](https://github.com/samscott89/serde_qs) and did not need to create a custom deserializer

**Comment by jplatte** [comment]
There is also now [`actix_web_lab::extract::Query`](https://docs.rs/actix-web-lab/0.20.1/actix_web_lab/extract/struct.Query.html) if you only need simple sequences, not the advanced nesting / reordering features of `serde_qs`.
