### ISSUE TITLE
Pull Request Tagging

### ISSUE THREAD

**Issue by godofdream** [actix/actix-web#1306]
Currently "waiting-on-author" and "waiting-on-review" tags are used to describe the state of the pull-requests.
However as an pull request author I can not remove the "waiting-on-author" tag.
And "waiting-on-review" is basically the default state, hence no need to tag it.

Rather than tagging by hand i propose using github apps states and maybe increasing the minimum reviewers count.
https://github.com/apps/minimum-reviews

There are Review States and even Filters for these: 
 • Review required 
 • Approved
 • Changes Requested

Additionally I propose using the WIP Plugin (if It's not activated yet)
https://github.com/marketplace/wip/

**Comment by JohnTitor** [comment]
> However as an pull request author I can not remove the "waiting-on-author" tag.

When you addressed the review, it's enough to ping the reviewer to notice that. You don't need to drop the label.

> And "waiting-on-review" is basically the default state, hence no need to tag it.

We put the `"waiting-on-review"` label manually, so I think it could indicate that someone saw the PR and requested reviews if needed.

**Comment by robjtede** [comment]
> Additionally I propose using the WIP Plugin (if It's not activated yet)

Don't fraft PRs act like WIP anyway?

> We put the "waiting-on-review" label manually, so I think it could indicate that someone saw the PR and requested reviews if needed.

I feel that, looking down the current PR list, that there could be some redundancy 🙃

**Comment by godofdream** [comment]
> Don't draft PRs act like WIP anyway?

I didn't know about "Draft Pull Requests". 
In this case the WIP Plugin doesn't add benefits, however I think some users still use the old "[WIP] My Pullrequest" scheme.

> We put the "waiting-on-review" label manually, so I think it could indicate that someone saw the PR and requested reviews if needed.

It's possible to request a review with the "reviewers" section.
This way the reviewer gets Informed by an github notification.
There are also some automation Tools to specify reviewers based on changes on the folders.
e.g. changes on Readme or docs -> Reviewer A, and B
changes on *.rs Files -> Reviewer B and C

**Comment by robjtede** [comment]
the current system is: `P-{affected_crate}` for each crate affected plus a `semver-{semver_level}` to indicate what kind of version bump is required
