### ISSUE TITLE
Active ClientRequests sometimes segfaults on exit

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#131]
Not sure how to reduce this one down to an example to replicate, but it appears to be an issue when there are active Client Requests, and you try to shut down the actix system.

I have a few endpoints that are proxy to other webservices.

If a browser is making requests to the actix web service, and you try to shut it down, then the following is displayed in the logs:

```
SIGINT received, exiting
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Shutting down http worker, 0 connections
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Force shutdown http worker, 1 connections
 INFO  actix_web::server::worker     > Shutting down http worker, 0 connections
Segmentation fault: 11
```

I can see that there are active connections to the proxy locations, even though the client has closed connection with actix.  I.e, they are sticking around for a bit.  Eventually (after like 5 seconds?) these connections close off.

I.e, `client -> actix` is closed, but `actix -> service` is open.

It might be to do with something when the `ClientRequest` connections are finally destroyed

**Comment by fafhrd91** [comment]
i saw similar segfault several times. i think this is logger prints to console during shutdown

**Comment by fafhrd91** [comment]
i added 0.5 sec delay before exit, try this commit 449709dd7e291e6b5612eca85477d2722bfbcc9a

**Comment by cetra3** [comment]
I haven't been able to seg fault it with that version

**Comment by fafhrd91** [comment]
great!
