### ISSUE TITLE
Stopping the server from an action?

### ISSUE THREAD

**Issue by biot023** [actix/actix-web#1315]
Hi.
I need to create and endpoint that kills the server (and exits the application).
I guess I need to do that with `HttpServer.system_exit()` in a lambda passed to the route "/die" (or whatever path).
What I can't figure out, though, is how to access the server to issue that method call on it from the function in the route declaration.
Could anyone advise me on how to do that?
Or the approach I *should* be taking to achieve what I need?
Thank you,
   Doug.

**Comment by robjtede** [comment]
@biot023 I created an [example](https://github.com/actix/examples/pull/240/files) to show how this can be done.

**Comment by biot023** [comment]
That's perfect, thank you!

**Comment by abau** [comment]
Since actix handles `SIGINT`, raising `SIGINT` from a route appears to work as well:

```
unsafe {
    libc::raise(libc::SIGINT);
}
```
