### ISSUE TITLE
Fails to build with bazel and cargo-raze. Error: use of undeclared type or module `fail_ure`

### ISSUE THREAD

**Issue by a1ph** [actix/actix-web#1318]
The recent change broke my bazel build. Here's the error:

```
error[E0433]: failed to resolve: use of undeclared type or module `fail_ure`
   --> external/raze__actix_http__1_0_1/src/error.rs:968:24
    |
968 | impl ResponseError for fail_ure::Error {}
    |                        ^^^^^^^^ use of undeclared type or module `fail_ure`

error: aborting due to previous error
```

Is there a way to work around it?

**Comment by JohnTitor** [comment]
You should enable `failure` feature, then it should work fine.

**Comment by a1ph** [comment]
How do I enable the feature in cargo-raze config?

**Comment by JohnTitor** [comment]
Try to modify `Cargo.toml` (I'm not familiar with `cargo-raze` though).

**Comment by sergeysova** [comment]
https://github.com/actix/actix-web/blame/63730c1f732d100f523cb51e1b9e4f7168e0f45d/actix-http/Cargo.toml#L37

**Comment by sergeysova** [comment]
![image](https://user-images.githubusercontent.com/5620073/74253135-be390200-4cff-11ea-8699-fe9e041b20ac.png)

**Comment by robjtede** [comment]
@sergeysova The `failure` crate is aliased to `fail-ure` so we can use the name as a feature flag, That version of cargo-tree musnt support the `package=""` aliasing. It's possible cargo-raze doesn't either.

**Comment by JohnTitor** [comment]
I think there is no action that we can take here?

**Comment by nikclayton-dfinity** [comment]
FYI, this was resolved in https://github.com/google/cargo-raze/issues/143
