### ISSUE TITLE
awc: Doesn't support IPv6 [::1]

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#1320]
I'm not exactly sure what `[::1]` means but entering `http://[::1]:9200/` in Firefox works fine (substitute with any port that is actually used for something on your computer). However, `awc::Client` panics upon trying to send a request to this address:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { inner: stack backtrace: ....
```
 and then 
```
Label contains invalid characters: Err(Errors([DissallowedByStd3AsciiRules, ValidityCriteria])) }))'
```
Actually I constructed this address by using Rust's built-in address resolution on `"localhost"`, and that why I think this should be fixed in awc. Minimal example for reproduction:

```
use awc::Client;
use std::{
    net::{SocketAddr, ToSocketAddrs},
    path::PathBuf,
};


#[actix_rt::main]
async fn main() -> Result<(), ()> {
    let cli = Client::default();
    let addr = ("localhost", 9200).to_socket_addrs().unwrap().next().unwrap();
    println!("SocketAddr: {:?}", addr);
    let uri = format!("http://{}/", addr);
    println!("URI string: {:?}", uri);
    let response = cli.get(&uri).send().await.unwrap();
    println!("{:?}", response);
    Ok(())
}
```

`Cargo.toml`:
```
[package]
name = "a"
version = "0.1.0"
authors = ["Erlend Langseth <3rlendhl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
awc = "1.0.1"
actix-rt = "1.0.0"
```

.. prints before panicking:
```
SocketAddr: V6([::1]:9200)
URI string: "http://[::1]:9200/"
```

**Comment by robjtede** [comment]
This is a quirk in how IPv6 addresses of that format have to be printed when accompanied by a port. (`::1` means localhost in the IPv6 space.)

You can see [in this playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ea970e4d3dede0ef9f554b55200e51e0) that rusts SocketAddr cannot parse this particular format despite it being what's printed by its Display impl.

Havent been able to find a way to solve this issue (might have missed something) but a trace log of a request shows that it fails when trying to resolve DNS "[::1]" in actix-connect.

**Comment by fakeshadow** [comment]
This is potential fixed with current master branch of actix-tls.
And with https://github.com/actix/actix-web/pull/1905 could possibly fix this with awc

**Comment by fakeshadow** [comment]
This is working on master branch.
```rust
use actix_web::{get, App, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let server = HttpServer::new(|| App::new().service(index))
        .bind("[::1]:8080")?
        .run();

    let res = actix_web::client::Client::new()
        .get("http://[::1]:8080/hi")
        .send()
        .await
        .unwrap()
        .body()
        .await
        .unwrap();

    assert_eq!("Hello World !", std::str::from_utf8(res.as_ref()).unwrap());

    server.stop(true).await;

    Ok(())
}

#[get("/hi")]
async fn index() -> &'static str {
    "Hello World !"
}
```

I assume this is resolved but not all platforms are tested. Please reply if you still encounter ipv6 resolve problem.
