### ISSUE TITLE
Николай блин!

### ISSUE THREAD

**Issue by GildedHonour** [actix/actix-web#1324]
Напугал. Я ж думал "всё, удалил, навсегда!"
Фуууууу

Больше так не пугай!

**Comment by robjtede** [comment]
> Напугал. Я ж думал "всё, удалил, навсегда!"
> Фуууууу

> Scared. Well I thought, "deleted everything, forever!"
> Fuuuuuu

fear not :)

**Comment by GildedHonour** [comment]
@robjtede  eres un traductór o quén? 

por qué no traduciste "fuuuuuu" entonces?

**Comment by robjtede** [comment]
https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%D0%9D%D0%B0%D0%BF%D1%83%D0%B3%D0%B0%D0%BB.%20%D0%AF%20%D0%B6%20%D0%B4%D1%83%D0%BC%D0%B0%D0%BB%20%22%D0%B2%D1%81%D1%91%2C%20%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D0%BB%2C%20%D0%BD%D0%B0%D0%B2%D1%81%D0%B5%D0%B3%D0%B4%D0%B0!%22%0A%D0%A4%D1%83%D1%83%D1%83%D1%83%D1%83%D1%83
