### ISSUE TITLE
web::Query does not decode url key without value into None

### ISSUE THREAD

**Issue by thorjelly** [actix/actix-web#1329]
I have an endpoint which takes a query:

```
#[post("/api/task/add")]
async fn add_task(
    query: web::Query<front::NewTask>,
    req: HttpRequest,
) ...
```

With the query containing optional elements:

```
#[derive(Deserialize, Clone)]
pub struct NewTask {
    /// The name of this task
    pub name: String,

    /// The description of this task
    pub description: Option<String>,

    /// A team that this task is attached to
    pub team_id: Option<TeamId>,
}
```

Omitting the parameters works:
```
http://localhost:8080/api/task/add?name=test
```

However a url with keys without values does not work, even though this is (apparently) considered a valid URL:
```
http://localhost:8080/api/task/add?description=&name=test&team_id 400 (Bad Request)
```

according to https://github.com/nodejs/node/issues/9500#issuecomment-287823229

If this is a valid URL, actix-web should not return a BadRequest error, which implies a malformed request, but correctly decode the keys without values into None, since this appears to be a valid way to encode a url.

**Comment by robjtede** [comment]
It may help to know what your `TeamId` is. I think it's arguable that this is unexpected.

**Comment by robjtede** [comment]
I wouldn't expect the outcome of `?team_id` to be None. The presence of the key in the querystring, albeit with no value, has a meaning different to not including it.

Edit: might have to take that back, going to see what the standard has to say.

**Comment by robjtede** [comment]
The WHATWG URL standard states that `?foo` == `?foo=`; there's an empty string in there which cannot be deserialized in a meaningful way for a `type TeamId = u8;` for example. For a `type TeamId = String` this deserializes fine.

My recommendation to you is to have your team_id field be `Option<String>`, then map `Some("")` to `None` and deserialize out the `TypeId` manually. (Or write a custom extractor to do those steps.)

This reminds me of JSON null vs undefined deserialization problem. I was hoping that an `Option<Option<T>>` would work for `TypeId = u8` and produce a `Some(None)` but it threw the same error.

Either way actix-web relies on serde_urlencoded to deserialize the querystring so this would be a bug on their crate if at all.

More folks from @actix/contributors should chime in before we close this though.

--- 

As an aside, not even `Option<()>` was able to deserialize using `?team_id` which seems like an obvious thing to support just for presence detection of a query parameter. Just like in #1301 and #786 users seem to run into a wall with serde_urlencoded quite a bit. It's my opinion we should look into replacing it or writing our own.

**Comment by cetra3** [comment]
It seems like the behaviour within the `serde_urlencoded` crate, and not related specifically to actix web, so happy to close it.

**Comment by thorjelly** [comment]
Alright, thank you. And yes, TeamId is just a u32. I'm satisfied with that conclusion and I'll close the issue since this does seem to be an issue with serde_urlencoded.
