### ISSUE TITLE
Websocket handling don't allow throttling of outgoing requests

### ISSUE THREAD

**Issue by uzytkownik** [actix/actix-web#133]
Currently there is no way of detecting throttling of the outgoing data. This means that if data is generated by outside source (for example other clients) and connection was throttled so client does not consume data fast enough the upstream producer doesn't have a way of knowing it.

Ideally there would be a way to ensure that `WebsocketContext` `stream` (and any buffering that happens below this level) does not happens out of bound.

**Comment by fafhrd91** [comment]
If I understand you right, there are two ways for that. You can set [write buffer capacity](https://actix.github.io/actix-web/actix_web/struct.HttpResponse.html#method.set_write_buffer_capacity) or [WebsocketContext::drain()](https://actix.github.io/actix-web/actix_web/ws/struct.WebsocketContext.html#method.drain)

**Comment by uzytkownik** [comment]
@fafhrd91 What happens when write buffer capacity is exceeded? Is the whole context stopped (I presume so)? I presume drain is when the data leaves internal buffers and gets to OS, not when the ACK is send back from client but it would be nice to have it documented.

PS. I would recommend changing drain to flush or at least document it better as usually 'drain' pulls from the stream collection while flush moves data out of it.
**EDIT:** PPS. By question I mean that it is not immediately obvious from documentation.

**Comment by fafhrd91** [comment]
yes, if write buffer capacity is exceeded whole context get stopped. client is not involved here, write buffer and drain are both behave similar.

I use `drain` after python's asyncio event loop (I was one of the original developers of it)
technically, we are waiting for internal buffer to drain. but I don't really see much difference with flush :)

**Comment by fafhrd91** [comment]
closing. if you have more questions of would like to make PR, re-open
