### ISSUE TITLE
proposal for an actix-web-extras repo

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1330]
There's a few loose repos in the org that could be consolidated so we don't forget about them:
- actix-redis
- actix-protobuf
- actix-web-httpauth

A case could be made for `actix-{cors,identity,session}` to move out of the main repo as well. My criteria for suggesting these is just "that which feels extra to actix-web".

Thoughts?

**Comment by tyranron** [comment]
Seems quite reasonable!

**Comment by JohnTitor** [comment]
One concern is that it will increase CI time and cache size in main repo but I basically agree with that.

**Comment by robjtede** [comment]
Increase ci time? Surely moving modules out of actix/actix-web would decrease it

**Comment by JohnTitor** [comment]
Aha! I misread your comment, was thinking the opposite. Yeah, I definitely agree with that!

**Comment by robjtede** [comment]
started on it here https://github.com/actix/actix-extras and managed to preserve the git histories
