### ISSUE TITLE
impossibility to be build with musl

### ISSUE THREAD

**Issue by unegare** [actix/actix-web#1331]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

be build

## Current Behavior

```
cannot produce proc-macro for `actix-macros v0.1.1` as the target `x86_64-unknown-linux-musl` does not support these crate types
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

alpine
x86_64-unknown-linux-musl
actix-web = { version="^2.0", features=["openssl"] }

* Rust Version (I.e, output of `rustc -V`): 1.40
* Actix Web Version: 2.0

**Comment by Aaron1011** [comment]
This is not specific to `actix-web` - it's a general issue with running proc-macros on a musl host. See https://github.com/rust-lang/cargo/issues/7563

**Comment by nazar-pc** [comment]
Looks like upstream issue was resolved and after installing `musl-dev` on Alpine Linux I'm able to build working static binary with Actix-Web.

I believe this can be closed now.
