### ISSUE TITLE
Can we publish documentation for all of the Actix crates together?

### ISSUE THREAD

**Issue by peterjoel** [actix/actix-web#1340]
Documentation is currently published on a per-crate basis, which makes it difficult to find objects from the different crates. It's not always obvious which crate to search in, and newcomers may not be aware of the structure.

The docs at https://docs.rs/actix-web/2.0.0/actix_web currently look like this:

![](https://i.imgur.com/iITlLmK.png)

It would be really nice if it looked like this:

![](https://i.imgur.com/xWkdCLf.png)

Which I built with `cargo doc --workspace --no-deps`

**Comment by robjtede** [comment]
@peterjoel see https://actix.rs/actix-web/actix_web/
