### ISSUE TITLE
No feature named `uds`

### ISSUE THREAD

**Issue by masnagam** [actix/actix-web#1348]
First of all, there is no practical problem.  `bind_uds()` and `listen_uds()` are available without the `uds` feature.

## Expected Behavior

Build should not fail when we follow the steps described in the documentation.

## Current Behavior

When defined the `uds` feature as described in [the document](https://docs.rs/actix-web/2.0.0/actix_web/struct.HttpServer.html#method.bind_uds)

```toml
# Cargo.toml
[dependencies]
actix-web = { version = "2.0", features = ["uds"] }
```

Build fails:

```console
$ cargo build
error: failed to select a version for `actix-web`.
    ... required by package `proj v0.1.0 (/path/to/proj)`
versions that meet the requirements `= 2.0.0` are: 2.0.0

the package `proj` depends on `actix-web`, with features: `uds` but `actix-web` does not have these features.


failed to select a version for `actix-web` which could resolve this conflict
```

## Possible Solution

There are two possible solutions:

1. Define the `uds` feature if it should be defined
2. Otherwise, update documention comments like below
```diff
diff --git src/server.rs src/server.rs
index 11cfbb6b..97dd9f7f 100644
--- src/server.rs
+++ src/server.rs
@@ -443,8 +443,6 @@ where

     #[cfg(unix)]
     /// Start listening for unix domain connections on existing listener.
-    ///
-    /// This method is available with `uds` feature.
     pub fn listen_uds(
         mut self,
         lst: std::os::unix::net::UnixListener,
@@ -483,8 +481,6 @@ where

     #[cfg(unix)]
     /// Start listening for incoming unix domain connections.
-    ///
-    /// This method is available with `uds` feature.
     pub fn bind_uds<A>(mut self, addr: A) -> io::Result<Self>
     where
         A: AsRef<std::path::Path>,
```

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.41.0 (5e1a79984 2020-01-27)
* Actix Web Version: 2.0.0

**Comment by leizzer** [comment]
I would like to hear more opinions on this but in case a change in docs is necessary would you take care of it @masnagam ??

**Comment by robjtede** [comment]
Doesn't look like it requires more dependencies to support unix sockets so i'd consider this to need a docs removal.

**Comment by masnagam** [comment]
@leizzer @robjtede I completely agree with @robjtede.  I think there is no significant benefits of adding the `uds` feature.

**Comment by robjtede** [comment]
Unless anyone gets to it sooner, i'll PR the docs change later today.

**Comment by masnagam** [comment]
@robjtede I created PR #1356.
