### ISSUE TITLE
apply middleware for a scope

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#1352]

**Comment by robjtede** [comment]
Scope already has the `.wrap` and `.wrap_fn` methods. See docs: https://docs.rs/actix-web/2.0.0/actix_web/struct.Scope.html#method.wrap

**Comment by 0x8f701** [comment]
Thanks for the docs!

**Comment by oscartbeaumont** [comment]
I am trying to apply the compression middleware to only certain routes and am having an issue applying the middleware to a scope using the `.wrap` method. I am using the code [here](https://gist.github.com/oscartbeaumont/471772733c83efab04238a4b189be751) and it is not able to compile.
Any help would be appreciated.
