### ISSUE TITLE
JSON documentation (or use) issue

### ISSUE THREAD

**Issue by csterritt** [actix/actix-web#1353]
Hello,

Trying to get a simple example handling JSON, building on the excellent examples in the codebase.

I'm trying to limit the size of the payload sent in.  I saw an example that indicated I should be able to use:

``` rust
app.data(web::JsonConfig::default().limit(4096)) // <- limit size of the payload (global configuration)
```

However, this doesn't appear to work... I can send in an arbitrarily large payload, and it's sent to my processing function without any error.

Looking at the [actix_web::web::JsonConfig](https://docs.rs/actix-web/2.0.0/actix_web/web/struct.JsonConfig.html) documentation, it indicates that this should work:

``` rust
    let mut server = HttpServer::new(|| {
        App::new()
            // enable logger - always register actix-web Logger middleware last
            .wrap(middleware::Logger::default())
            .service(
                web::resource("/userinfo")
                    .app_data(
                        // change json extractor configuration
                        web::Json::<Info>::configure(|cfg| {
                            cfg.limit(4096)
                                .error_handler(|err, req| {  // <- create custom error response
                                    error::InternalError::from_response(
                                        err, HttpResponse::Conflict().finish()).into()
                                })
                        }))
                    .route(web::post().to(userinfo))
            )
    });
```

But when I compile it, I get the following error (using cargo 1.41.0):

```
   Compiling mystore v0.1.0 (/Volumes/Second/Chris/hacks/rust/web/mystore)
error[E0599]: no function or associated item named `configure` found for type `actix_web::types::json::Json<Info>` in the current scope
  --> src/main.rs:37:44
   |
37 |                         web::Json::<Info>::configure(|cfg| {
   |                                            ^^^^^^^^^ function or associated item not found in `actix_web::types::json::Json<Info>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use actix_web::extract::FromRequest;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `mystore`.

To learn more, run the command again with --verbose.
```

So I'd love a clue on how to do this, but also since I am a Rust noob, I'd be curious how I would go about figuring out the cause of this error, I guess through finding the right documentation.

Thanks!

**Comment by robjtede** [comment]
Things you should know starting out with Rust number 1: the compiler is very helpful.

`the following trait is implemented but not in scope; perhaps add a `use` for it` `use actix_web::extract::FromRequest;`

**Comment by csterritt** [comment]
D'OH! How did I miss that... thanks @robjtede !

And, it works (that is, fails properly) with a huge request.
