### ISSUE TITLE
App::wrap_if

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#1355]
Hello, is it possible to have an new API for `actix_web::App` which is called `wrap_filter`.

```rust
pub fn wrap_filter<M, B1, F>(
    self,
    mw: F
) -> Option<App<impl NewService<Config = (), Request = ServiceRequest, Response = ServiceResponse<B1>, Error = Error, InitError = ()>, B1>> where
    M: Transform<T::Service, Request = ServiceRequest, Response = ServiceResponse<B1>, Error = Error, InitError = ()>,
    B1: MessageBody,
    F: IntoTransform<M, T::Service>, 
```

**Comment by robjtede** [comment]
Can you give us some more details:

- what you are expecting this to do?
- what use cases does this enable or make easier?
- how is it different from `.wrap` or `.wrap_fn`?
- are you willing to make a PR for it?
