### ISSUE TITLE
allow sharing event loops

### ISSUE THREAD

**Issue by nayato** [actix/actix-web#136]
Currently starting two HTTP servers would mean creation of 2 sets of event loops for each to run on.
Would be helpful to have a way to set it up so that both servers share a single set of event loops.

**Comment by fafhrd91** [comment]
added general purpose [`Server`](https://actix.rs/actix-web/actix_web/server/struct.Server.html)
it allows to run custom [`Service's`](https://actix.rs/actix-web/actix_web/server/trait.Service.html)
