### ISSUE TITLE
preferred/recommended way to use diesel with actix-web

### ISSUE THREAD

**Issue by j-brn** [actix/actix-web#1364]
Hi , i wondered what's the best/recommended way to use diesel (or other synchronous database drivers) with actix-web. The diesel example in the examples repository uses `web::block` while the "databases" section on the website uses a DB actor.

Are there any benefits or drawbacks in using `web::block` instead of an actor, and vice versa?

BTW: Thanks for bringing back actix, i'm happy to to see it back in action.

**Comment by cdbattags** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/main_diesel.rs

Hopefully this should point you in the right direction!

**Comment by jbrookins13** [comment]
In a general sense, is using the `web::block` method worse in some way? I wouldn't mind investigating an alternate methodology if it had substantive advantages.

**Comment by robjtede** [comment]
`web::block` is just the built-in way to run blocking code on a task threadpool such that your app isn't blocked from handling HTTP requests. It's a pretty convenient alternative to setting up a SyncArbiter (though your application's complexity may warrant it, anyway).

The website is still in the process of being updated to v2, I'd use the examples repo as the guide to follow on databases for now. Going to close but if you have further questions you can reach out on the [Gitter channel](https://gitter.im/actix/actix-web).
