### ISSUE TITLE
Error types are lost when using web::block

### ISSUE THREAD

**Issue by BartWillems** [actix/actix-web#1377]
When using the `web::block()` calls to un-block the actix-web threads, I lose the error types.

[Example](https://github.com/actix/examples/blob/dc8d61eb59dd80278e8b5e5d6cf49bf6ea204d0a/diesel/src/main.rs#L59)

When I don't use the `web::block()`, I can map the diesel errors to actual http errors, for example: if a unique constraint is violated, I can return a BadRequest, or 409 Conflict, .. 

When I **do** use `web::block()`, I only receive an `actix_threadpool::BlockingError::Error(e)` (I'm ignoring the `::Canceled` value for now).
I can't seem to figure out how to convert this `e` error to the actual DB error.

**Comment by Jonathas-Conceicao** [comment]
Have you try using pattern matching to get the error?
```Rust
match web::block(something).await {
  Ok(k) => todo!("ok value"),
  Err(BlockingError::Canceled) => todo!("handle canceled"),
  Err(BlockingError::Error(diesel_error) => todo!("handle diesel error"),
}
```

**Comment by BartWillems** [comment]
If I do that inline, it does seem to work, but I can't seem to figure out how to implement these Blocking errors for my own error types .

``` rust
impl<E: std::fmt::Debug> From<actix_threadpool::BlockingError<E>> for ServiceError {
    fn from(error: actix_threadpool::BlockingError<E>) -> ServiceError {
        error!("actix threadpool pool error: {}", error);
        match error {
            actix_threadpool::BlockingError::Error(e) => {
                return e;
            }
            actix_threadpool::BlockingError::Canceled => return ServiceError::InternalServerError,
        }
    }
}
```

this results in:

```
error[E0308]: mismatched types
  --> src/errors.rs:68:24
   |
63 | impl<E: std::fmt::Debug> From<actix_threadpool::BlockingError<E>> for ServiceError {
   |      - this type parameter
64 |     fn from(error: actix_threadpool::BlockingError<E>) -> ServiceError {
   |                                                           ------------ expected `errors::ServiceError` because of return type
...
68 |                 return e;
   |                        ^ expected enum `errors::ServiceError`, found type parameter `E`
   |
   = note:        expected enum `errors::ServiceError`
           found type parameter `E`
   = help: type parameters must be constrained to match other types
   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustfuif`.
```
I understand that I'm simply returning the incorrect type, but I can't seem to figure out how to correctly implement this. I don't really have experience with generics atm.

**Comment by Jonathas-Conceicao** [comment]
The problem in the code you present is in fact with the generic parameter of the `BlockingError`. The type signature you have says that it can hold any `E` that implements `Debug`. But in your code you try to return `E` as a `ServiceError`. You have to either constrain your implementation of `From` to be only valid for `BLockingError<ServiceError>` or to require that the generic `E` you specify can be converted into `ServiceError`. Can you try something like this:
```Rust
impl From<actix_threadpool::BlockingError<E>> for ServiceError
where
    E: std::fmt::Debug,
    E: From<ServiceError>,
{
    fn from(error: actix_threadpool::BlockingError<E>) -> ServiceError {
        error!("actix threadpool pool error: {}", error);
        match error {
            actix_threadpool::BlockingError::Error(e) => {
                return ServiceError::from(e);
            }
            actix_threadpool::BlockingError::Canceled => return ServiceError::InternalServerError,
        }
    }
}
```

**Comment by BartWillems** [comment]
Aha, that was something I was looking for! This does however, cause a new issue :s 

``` 
error[E0277]: the trait bound `errors::ServiceError: std::convert::From<E>` is not satisfied
  --> src/errors.rs:74:24
   |
74 |                 return ServiceError::from(e);
   |                        ^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<E>` is not implemented for `errors::ServiceError`
   |
   = note: required by `std::convert::From::from`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rustfuif`.
```
I've already implemented the `From` traits for diesel result errors & r2d2 errors, so I don't know why it still doesn't compile :thinking:

**Comment by Jonathas-Conceicao** [comment]
The error messages suggests that your `E` is too generic. Have you constrained `E: From<ServiceError>` as I suggested before? It's generally easier to help when you post the faulty code as well.

**Comment by Jonathas-Conceicao** [comment]
It looks like I suggested the from the other way around. I think what you want is:
```Rust
where
    E: std::fmt::Debug,
    From<E>: ServiceError,
{
```

Because you need `ServiceError` to be generated from `E`, not the `E` to be generated from `ServiceError`.

**Comment by robjtede** [comment]
Think you're on the right track there @Jonathas-Conceicao, though it may be more intuitive to say `E: Into<ServiceError>`.

**Comment by BartWillems** [comment]
Thanks you guys, it works now!

This is what I ended up using:
``` rust
impl<E> From<actix_threadpool::BlockingError<E>> for ServiceError
where
    E: std::fmt::Debug,
    E: Into<ServiceError>,
{
    fn from(error: actix_threadpool::BlockingError<E>) -> ServiceError {
        error!("actix threadpool pool error: {}", error);
        match error {
            actix_threadpool::BlockingError::Error(e) => e.into(),
            actix_threadpool::BlockingError::Canceled => ServiceError::InternalServerError,
        }
    }
}
```
