### ISSUE TITLE
How to add header for fs::Files::new("/", "./static/").index_file("index.html")

### ISSUE THREAD

**Issue by javasn** [actix/actix-web#1383]
I want to add header "Access-Control-Allow-Origin" for the index.html response.
How to do?
Thanks.

**Comment by robjtede** [comment]
You want to look at [actix-cors](https://docs.rs/actix-cors/0.2.0/actix_cors/) middleware. If you have further questions come ask in [the gitter channel](https://gitter.im/actix/actix-web).
