### ISSUE TITLE
Hello actix

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#14]
Hello

I discover your actix-web project and this one seems really promising. Can be as promising as the nodesjs/express framework (easy, cool, fast, documented...).

Is there a minimal example to use a third tokio module (https://tokio.rs/docs/going-deeper-tokio/third-party/) to call curl, postgres, cassandra... in a road function? is that even possible?

Thank you

**Comment by fafhrd91** [comment]
Actix is based on tokio, so you can use any tokio library with it, you just need to implement async handler https://actix.github.io/actix-web/guide/qs_4.html#async-handlers

I’ll add example

**Comment by fafhrd91** [comment]
I'll close this as I don't see actionable at the moment. I'll add more examples over time
