### ISSUE TITLE
actix-web does not follow the rfc3986

### ISSUE THREAD

**Issue by icyk** [actix/actix-web#1405]
## Expected Behavior

Url request: /rest/xxx/xxx?key=abc%40de
HttpRequest: req.uri().query() === "abc@de"

## Current Behavior

HttpRequest: req.uri().query() === "abc%40de"

## Possible Solution

I found it in the https://github.com/actix/actix-web/issues/556 issue.  And fix in #577 merge.  But lost when actix-web upgraded to 1.0.0 version .

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.39.0
* Actix Web Version: 2.0.0

**Comment by pickfire** [comment]
The uri stored in actix is not decoded, the original uri (not url) does not do it either. I can't seemed to find any decoding logic for `query`, probably need to decode it manually with `Url` (not `uri`).

**Comment by VeaaC** [comment]
You actually cannot decode automatically: Sometimes the programmer needs to know what is encoded, and what is not:
If the value of a parameter has a complex structure, and a control character used in that structure should appear in an inside value, it needs to be encoded (but only then).

E.g.: a `|` separated list (common pattern in OpenAPI 3), that can also contain `|` as part of a list item:

`my_value=foo%7Cgar|bar|uff`
versus
`my_value=foo|gar|bar|uff`

**Comment by pickfire** [comment]
@VeaaC But how does not developer knows that it is not encoded by default? Is there any clear docs to let others know without digging deep into the docs?

**Comment by aliemjay** [comment]
As @VeaaC pointed out, this works as intended. If you want decoded parameters, you can use `Query` extractor.

from RFC 3986:

>    When a URI is dereferenced, the components and subcomponents
   significant to the scheme-specific dereferencing process (if any)
   must be parsed and separated before the percent-encoded octets within
   those components can be safely decoded, as otherwise the data may be
   mistaken for component delimiters.
