### ISSUE TITLE
feature request: optional safe user input

### ISSUE THREAD

**Issue by BartWillems** [actix/actix-web#1409]
Currently when I accept user input, from eg `actix_web::web::Json<T>`, I have to make sure to implement validation logic for T and also make sure to actually validate it.

Example

``` rust
#[post("/games")]
async fn create(game: Json<CreateGame>, pool: Data<db::Pool>) -> server::Response {
    let game = game.into_inner();
     
    // validate game durations/name/...
    game.validate()?;
    let game = web::block(move || Game::create(game, &pool.get()?)).await?;

    http_created_json!(game);
}
```
The rust compiler isn't able to notify me if I forget to call `game.validate()`.

Would it be possible to have `SafeJson<T>` types, that require an implemented `validate` trait?

Actix-Web could automatically call this trait on these objects and return 403 Bad Request automatically if the user implemented `validate` function fails.

**Comment by robjtede** [comment]
This should be possible to implement yourself. Some struct `SafeJson<T>` that's impls `FromRequest` (so can be used in place of `Json<T>` in the params) and runs the validation before the handler is entered.

**Comment by robjtede** [comment]
If you need further help you can talk to us on the [gitter channel](https://gitter.im/actix/actix-web).
