### ISSUE TITLE
Unnecessary usage of unsafe keyword

### ISSUE THREAD

**Issue by OriolMunoz** [actix/actix-web#1417]
Rust newbie here:
I was toying around with the project in my spare time and checked the usages of `unsafe` in the source code out of curiosity.
The definition of `ShortSlice` in `mask.rs` is:
```rust
impl<'a> ShortSlice<'a> {
    unsafe fn new(slice: &'a mut [u8]) -> Self {
        // Sanity check for debug builds
        debug_assert!(slice.len() < 8);
        ShortSlice(slice)
    }
    [...]
}
```
as far as I could tell, and the compiler seems to agree, the `unsafe` keyboard is unnecessary there.

In the same file, line 101:
```rust
unsafe { (ShortSlice::new(buf), &mut [], ShortSlice::new(&mut [])) }
```
shouldn't be necessary with the previous change.

In line 96, the unsafe can be moved inwards:
```rust
(ShortSlice::new(head), unsafe { cast_slice(mid) }, ShortSlice(tail))
```

Am I missing something here? Is/was there any reason for those unsafe to be there?

Thanks!

**Comment by robjtede** [comment]
I think the rationale here is that its up to the caller of ShortSlice::new to uphold some invariant that could cause weird behavior and/or memory corruption if violated. The debug_assert! protects against this in debug builds.

Some libraries will decide to panic when these invariants are violated to prevent undefined behavior but in this case, the author decided to mark it as unsafe as an extra flag that it **could** cause UB if called with a slice larger than 8 in length while removing the need for an extra check at runtime.
