### ISSUE TITLE
JsonConfig::default()::limit(a) not working

### ISSUE THREAD

**Issue by Jarves42** [actix/actix-web#1419]
Hi, I have created an HTTP server using actix-web v2.0.0. I want to change json payload for both(request body and response body). I tried with `web::scope("api")
                    .app_data(JsonConfig::default().limit(json_payload_limit_conf()))` but it did not work it was still using default size which was 262_144.  After some more digging i found it used PayloadConfig struct to check limit so after adding this `web::scope("api")
                    .app_data(PayloadConfig::new(json_payload_limit_conf()))` it worked.

Adding my entire server creates code. 

**Code Which Did not work:**
```rust
HttpServer::new(move || {
        HttpApp::new()
            .wrap(middleware::Logger::new("%a %t %s %D %b %U"))
            .wrap(DefaultHeaders::new().header(http::header::HOST, get_hostname()))
            .wrap(middleware::Compress::default())
            .data(app.clone())
            .service(
                web::scope("api")
                    .app_data(JsonConfig::default().limit(json_payload_limit_conf()))
                    .route("/hello", web::get().to(index))
                    .configure(|cfg| build_common_api::<App>(cfg, replication_guard))
                    .configure(custom_http_routes),
            )
    })
    .workers(http_workers_conf())
    .shutdown_timeout(10)
    .listen(listener)
    .with_context(|| "Error in starting actix web server")?
    .run()
    .await?;
```

**Code Which Worked:**
```rust
HttpServer::new(move || {
        HttpApp::new()
            .wrap(middleware::Logger::new("%a %t %s %D %b %U"))
            .wrap(DefaultHeaders::new().header(http::header::HOST, get_hostname()))
            .wrap(middleware::Compress::default())
            .data(app.clone())
            .service(
                web::scope("api")
                    .app_data(PayloadConfig::new(json_payload_limit_conf()))
                    .route("/hello", web::get().to(index))
                    .configure(|cfg| build_common_api::<App>(cfg, replication_guard))
                    .configure(custom_http_routes),
            )
    })
    .workers(http_workers_conf())
    .shutdown_timeout(10)
    .listen(listener)
    .with_context(|| "Error in starting actix web server")?
    .run()
    .await?;
```
**Can anyone explain what is different in JsonConfig and PayloadConfig struct? When to use which one?**

**Comment by adwhit** [comment]
What is the signature of `index` handler? The `JsonConfig` is for use with the `Json` extractor, the `PayloadConfig` is for use with the `Payload`,  `String` and `Bytes` extractors.

**Comment by Jarves42** [comment]
If a request contains a header Content-Type: application/json then actix will use `Json` extractor right?

And index is just hello world API I was facing error in another API which I build in  `build_common_api` method.
Below is the function signature.

```rust
pub fn build_common_api <S>(replication_guard: ReplicationGuard) -> RoutesBuilder
where
    S: 'static + Application + Clone,
{
    |cfg| {
        cfg.route(
            "",
            web::get()
                .guard(guard::Header(ACCEPT_HEADER.as_str(), CONTENT_TYPE_AVRO_BINARY))
                .to(get_key_as_avro_for_cf::<S>),
        )
        .route(
            "",
            web::get()
                .to(get_key_as_json_for_cf::<S>),
        )
        .route("", web::delete().to(delete_data_for_cf::<S>))
        .route("", web::patch().to(delete_partial_data_for_cf::<S>))
        .route("", web::put().to(put_data_for_cf::<S>))
        .route("", web::post().to(merge_data_for_cf::<S>));
    }
}
```

And this is signature of merge_data_for_cf function.

```rust
pub async fn merge_data_for_cf<S>(
    data_key: web::Path<DataKey>,
    data: web::Bytes,
    state: web::Data<S>,
    req: HttpRequest,
) -> WebResult<&'static str>
where
    S: 'static + Application,
{
    //Request handler
}
```

**Comment by adwhit** [comment]
> If a request contains a header Content-Type: application/json then actix will use Json extractor right?

I don't think this is correct. The `Json` extractor is only used if it is explicitly listed in your handler arguments.

**Comment by Jarves42** [comment]
` in your handler arguments` how can I mentioned that?

**Comment by robjtede** [comment]
@Jarves42 

`data: web::Bytes,` => `data: web::Json<T>,`

**Comment by Jarves42** [comment]
@robjtede Thanks.

**Comment by robjtede** [comment]
If that solves your problem feel free to close the issue.
