### ISSUE TITLE
Renderers for error pages

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#142]
i think this should something like:

```rust

fn render_500(req: HttpRequest, resp: HttpResponse) -> HttpResponse {
    unimplemented!()
}

Application()
     .error_renderer(StatusCode::INTERNAL_SERVER_ERROR, render_500)
```

**Comment by max-frai** [comment]
We have `handler`, `resource`. In my opinion, `error_renderer` is a bit overcomplicated naming. Maybe `error_handler` ?

**Comment by fafhrd91** [comment]
i am not sure about `handler`. native speakers?

**Comment by DanielJoyce** [comment]
err_handler would be pretty standard.

**Comment by fafhrd91** [comment]
added [ErrorHandlers](https://actix.github.io/actix-web/actix_web/middleware/struct.ErrorHandlers.html) middleware
