### ISSUE TITLE
Proposal: create deno-plugin-actix - actix-deno bindings to be used via deno 

### ISSUE THREAD

**Issue by frank-dspeed** [actix/actix-web#1427]
deno is a js runtime written in rust + c++ it would be really nice to use actix with javascript together

https://github.com/denoland/deno/issues/4465

I have also created an issue there about that idea.

there is a project node-graalvm from oracle that demonstrated exactly the same with vertx the java equivalent of actix and it produced amazing results but actix + deno will perform even better so I would love to see that happen.

**Comment by jctaoo** [comment]
I'm interested in it. The performance of Vert.x is truly beyond my expectation as java cannot make this. After doing research on actix and actix-web write in rust, I'm working on integrating Actor Model for deno.

**Comment by frank-dspeed** [comment]
@jctaoo i am a bit more far with that project at present and found out that also deno will not do it and using actix with NodeJS is relativ easy via https://github.com/neon-bindings/neon that can compile the rust code to .node module so it can get used with NodeJS which is simply the fastest codebase.

**Comment by frank-dspeed** [comment]
@jctaoo if your interrested we could pair to release actix.node actix-web.node i have that on my list but i could change priority.

**Comment by robjtede** [comment]
Sorry. The current team doesn't have the capacity to take on an endeavor like this.
