### ISSUE TITLE
Documentation refers to a feature "client" which does not exist

### ISSUE THREAD

**Issue by otavio** [actix/actix-web#1430]
The feature list on the documentation is wrong. It refers to a missing feature. See at:

https://github.com/actix/actix-web/blob/206733188478f4d18df376a72fac3a4938b99bd6/src/lib.rs#L79

I found that when looking for a way to disable to client build.

**Comment by otavio** [comment]
@robjtede the reason why I opened this issue is to raise the problem and see if we can add the feature back. Is there any interest in this or just the docs need an update?

**Comment by robjtede** [comment]
Do you mean you wish the client to be put back behind a feature flag? If not we can just remove the reference to the flag in docs since the client is always available at `actix-web::client` in v2.

**Comment by otavio** [comment]
In fact, I was interested in know what what is the goal here. Having fewer dependencies to build when no client will be used is always good but it is not a hard requirement for me.

**Comment by robjtede** [comment]
Will have to do some tests of binary size/compile times with and without the client. Would be in favor of re-adding the flag (as a default) if it is seen to be beneficial.

**Comment by otavio** [comment]
Adding it, without changing the inner code to *not* use the `awc` dependency during the build is easy. It does not change compile times in this case.

Dropping `awc` use is more convoluted as it is used a lot on the tests.
