### ISSUE TITLE
upgrading to v2 alternative to sync handlers

### ISSUE THREAD

**Issue by crmckenzie** [actix/actix-web#1436]
Thank you to the maintainers for your work on this project. I very much appreciate it.

i'm trying to upgrade my project to actix 2. I have a fairly mature web application that cleanly separates domain code from framework code. The majority of that code is written in non-async functions. Rest and gRPC clients are either written using synchronous clients or are sync'd to the current thread using `futures::executor::block_on`. 

None of this works after the actix 2 upgrade. I'm loathe to rewrite my entire call stack as async functions as part of this upgrade. Here's a dramatically simplified code sample that illustrates the problem:

```rust
/*
curl http://localhost:3000/sync-async 
Hangs indefinitely.
*/
#[actix_web::get("/sync-async")]
fn sync_async(config: actix_web::web::Data<Config>) -> HttpResponse {

    /*
        This example simplifies a lot of complexity.
        In reality the api call is buried deep in an model that
        is implemented via synchronous function calls. For
        this reason, it would be a big change to modify everything
        to be async all the way down.
    */
    let rest_client = config.rest.clone();
    let http_response = futures::executor::block_on(exec_reqwest_async(rest_client));
    match http_response {
        Ok(_) => HttpResponse::Ok().json("Success!"),
        Err(_) => HttpResponse::InternalServerError().json("No good."),
    }
}

// This fn is a stand-in for a layered call-stack with domain and validation logic
// in front of the actual API calls.
async fn exec_reqwest_async(client: reqwest::Client) -> Result<String, reqwest::Error> {
    println!("Executing reqwest asychronously!");
    let body = client.get("https://www.rust-lang.org").send()
        .await?;

    println!("Reqwest executed!");

    let text = body
        .text()
        .await?;
    
    println!("Body read!");

    Ok(text)
}
```

I have a [gist](https://gist.github.com/crmckenzie/24ff6db72213af049024522967eb50f7) including this example along with other things I've tried. (It also appears that actix 2 doesn't work with the `reqwest::blocking::Client` client at all.

I really hope I'm just missing something obvious and you can direct me to a solution.
Thank you.

**Comment by robjtede** [comment]
There are no sync handlers in v2. You would not expect using futures::executor to work or reqwest blocking since they spawn executors but your handler is already inside an executor.

There is [web::block](https://docs.rs/actix-web/2.0.0/actix_web/web/fn.block.html) which helps run sync code. Plenty of examples of this being used in the example repo. Diesel is a common sync-only lib which where web::block is necessary.

Tokio also has some [helper functions](https://docs.rs/tokio/0.2.14/tokio/task/index.html#functions) you could experiment with.

**Comment by crmckenzie** [comment]
Cool. I was about to use `web::block` in the handler and then create a new runtime to `block_on` down in my business code. Unfortunately it's still a lot of changes to the overall system. I can't find any examples of _I'm in a sync method and just want to yield the thread to a future until it's done or times out_ using an threadpool. All of the examples assume you're already in an `async` method and can therefore just call `await`.

I appreciate your help and I've learned a lot the last couple of days. I'm going to close the issue since the ultimate answer to my question is "you can't do what your trying to do without a lot of surgery."
