### ISSUE TITLE
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements

### ISSUE THREAD

**Issue by sbrl** [actix/actix-web#1438]
## Expected Behavior
Not crash?

## Current Behavior
Crashes with an error:

<details>
<summary>(expand to see error)</summary>
<pre><code>
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> wopplebloxd/src/http_server/mod.rs:27:5
   |
27 |     #[actix_rt::main]
   |     ^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 27:5...
  --> wopplebloxd/src/http_server/mod.rs:27:5
   |
27 |     #[actix_rt::main]
   |     ^^^^^^^^^^^^^^^^^
note: ...so that the types are compatible
  --> wopplebloxd/src/http_server/mod.rs:27:5
   |
27 |     #[actix_rt::main]
   |     ^^^^^^^^^^^^^^^^^
   = note: expected  `&http_server::WopplebloxApp`
              found  `&http_server::WopplebloxApp`
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `impl std::future::Future` will meet its required lifetime bounds
  --> wopplebloxd/src/http_server/mod.rs:27:5
   |
27 |     #[actix_rt::main]
   |     ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
error: could not compile `wopplebloxd`.

To learn more, run the command again with --verbose.
</code></pre>
</details>

## Possible Solution
I have no clue what's going on.

## Steps to Reproduce (for bugs)

1. Compile code (see below)
2. Get error

<details>
<summary>(expand to see code)</summary>
<pre><code>
pub struct WopplebloxApp {
    settings : Settings
}

impl WopplebloxApp {
    pub fn new(settings : Settings) -> WopplebloxApp {
        WopplebloxApp {
            settings : settings
        }
    }
    
    #[actix_rt::main]
    pub async fn start(&self, port: i16) -> std::io::Result<()> {
        let address = format!("127.0.0.1:{}", port);
        
        handlers::print_embedded_files();
        
        let data = web::Data::new(GlobalState::new(self.settings.clone()));
        
        info!("Starting listener on http://{}", address);
        
        HttpServer::new(|| {
            App::new()
                .app_data(data)
                .wrap(Logger::default())
                .route("/static/{filepath:.*}", web::get().to(handlers::handle_static))
                .route("/", web::get().to(index))
        })
            .keep_alive(120)
            .bind(address)?
            .run()
            .await
    }   
}
</code></pre>
</details>

## Context

I'm trying to build a web app (self-hosted microblogging thingy, to be precise) with Actix, Rusqlite (+r2d2_sqlite, because threading). As part of this I'm using a shared immutable (I assume?) state. That object is as follows:

```
pub struct GlobalState {
    pub sitename : String,
    pub db : Database,
    pub translations : Translations // Contains a fluent::concurrent::FluentBundle<FluentResource>
}
```

The problem is that the error message doesn't reference any of my code enough for me to figure out what I've done wrong.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): `rustc 1.42.0 (b8cedc004 2020-03-09)`
* Actix Web Version: From my `Cargo.toml`:

```toml
actix-web = "2.0"		# Web framework
actix-rt = "1.0"		# Who knows?
```

**Comment by robjtede** [comment]
#[actix_rt::main] macro MUST be used on the program entrypoint fn main.

**Comment by sbrl** [comment]
Hey, thanks @robjtede! That's very odd, but it seems to have fixed it. What even is `actix_rt`?

For future reference, not only does the `#[actix_rt::main]` need to be on your `main()` method, but your main method also needs to be async, like this:

```rust
#[actix_rt::main]
async fn main() {
    
}
```

In addition, you need to await the method that actually contains your server:

```rust
match app.start(port).await {
	Ok(_) => {
		info!("Server exited normally.");
	},
	Err(message) => {
		error!("Error: The HTTP server fell over! Details:");
		error!("{}", message);
	}
}
```
