### ISSUE TITLE
0.5 release

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#145]
new:

* type-safe information extraction

breaking changes:

* `HttpResponseBuilder::body()`, `.finish()`, `.json()` now returns `HttpResponse` instead of `Result`
* `Method` and `StatusCode` moved to `actix_web::http` module
* `NormalizePath` moved to `http` module as well
* `actix_web::header` moved to a `actix_web::http::header`
* `DefaultHeaders` got simplified
* `StaticFiles` got simplified
* `CookieSessionBackend` got simplified
* `httpcodes` module is deprecated, `HttpResponse::Ok()` and other fn should be used instead

**Comment by fafhrd91** [comment]
@DoumanAsh @max-frai @brandur would mind checking how painful is to upgrade to actix-web master?

@brandur i noticed you use hyper as http client, did you try `actix_web::client`? btw would you mind if i translate your blog post to russian and post it on tech website?

**Comment by brandur** [comment]
> @DoumanAsh @max-frai @brandur would mind checking how painful is to upgrade to actix-web master?

Sure! I just timed it and it took me 10 minutes to upgrade. My project had ~50 or so changes required (see https://github.com/brandur/podcore/commit/45caaf2c0bafcf790d46fdbe96ef07d0a7d0ce17 in case it's helpful to someone else).

Some API stabilization would be nice, but I have to say that especially the change to `HttpResponseBuilder` functions returning `HttpResponse` is a huge improvement — previously I was a little confused as to what I was supposed to be doing with that `Result`.

> @brandur i noticed you use hyper as http client, did you try actix_web::client?

Not yet. My use of `hyper` is mostly for historical reasons — basically I was pulling in packages as I needed to do things, and `hyper` was the predominant HTTP client. I'm not married to it, but I want to make other changes first. I've put trying `actix_web::client` in my TODO list.

> btw would you mind if i translate your blog post to russian and post it on tech website?

Go for it!

**Comment by DoumanAsh** [comment]
@fafhrd91 Well it is certainly a bit bothersome with all these renaming and change in return values for HttpResponse.

Still it is a bit better API thanks to HttpResponseBuilder to return HttpResponse directly instead of old way

**Comment by fafhrd91** [comment]
@DoumanAsh i'd like to reduce amount api you need to export (api sureface), this takes some time.

note on `.body()` method. originally i used same approach as `http` crate. it seemed good. but over time i realized that it is not very ergonomic and also nobody actually check for body error and just return it.

**Comment by DoumanAsh** [comment]
`DefaultHeaders` got simplified too while it is breaking change, it is still better API :)

**Comment by haozileung** [comment]
it seems actix-redis is not working with 0.5

**Comment by fafhrd91** [comment]
@haozileung try actix-redis from master

**Comment by fafhrd91** [comment]
0.5 is released
