### ISSUE TITLE
ab test performance drops?

### ISSUE THREAD

**Issue by shvargon** [actix/actix-web#1456]
Sorry my bad english.
I am learning rust and created a small server on actix [gist](https://gist.github.com/RuAnDe/425b345cde762cf8c2a7ccad6599b340). Then he conducted his stress testing using ab. At first, the results were good ~6-9k requests per second. But after several passes, the results fall to ~ 1.7k. And at this level, and approximately remain [video](https://youtu.be/n8zFnbdvMHk). ab works fine with nodejs ~2.5k [gist](https://gist.github.com/RuAnDe/06c8a97d6cd5c9af984e53c61028907a) and [video](https://youtu.be/oRZ28rGkE3s).

And I do not understand is this my mistake or is there something wrong with actix?

Ubuntu 18.04.4 LTS

rustc 1.42.0 (b8cedc004 2020-03-09)
cargo 1.42.0 (86334295e 2020-01-31)

actix-web = "2.0"

**Comment by jeffsmith82** [comment]
so the command your running is 

ab -n 1000 -c 1000 http://localhost:8080/

This will create 1000 tcp connections and then close them. They do not fully close for 2 minutes normally they will get put into a TIME_WAIT state. once you have run out of free ports it will cause errors and terrible performance.

Try adding -k to ab so it reuses the same connection.

ab -n 1000 -k -c 1000 http://localhost:8080/

Also let it run a lot longer then you are to get a better idea about performance.

ab -n 1000000 -k -c 1000 http://localhost:8080/

You can confirm the number of TIME_WAIT's with 

ss -anp | grep 8080 | grep "TIME-WAIT" | wc -l

**Comment by ghost** [comment]
ab -n 1000000 -k -c 1000 -r http://localhost:8080/
add -r option and check the failed requests

Roberto Della Pasqua
www.dellapasqua.com<http://www.dellapasqua.com>

Da: Jeffrey Smith <notifications@github.com>
Inviato: sabato 18 aprile 2020 09:56
A: actix/actix-web <actix-web@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [actix/actix-web] ab test performance drops? (#1456)


so the command your running is

ab -n 1000 -c 1000 http://localhost:8080/

This will create 1000 tcp connections and then close them. They do not fully close for 2 minutes normally they will get put into a TIME_WAIT state. once you have run out of free ports it will cause errors and terrible performance.

Try adding -k to ab so it reuses the same connection.

ab -n 1000 -k -c 1000 http://localhost:8080/

Also let it run a lot longer then you are to get a better idea about performance.

ab -n 1000000 -k -c 1000 http://localhost:8080/

You can confirm the number of TIME_WAIT's with

ss -anp | grep 8080 | grep "TIME-WAIT" | wc -l

**Comment by shvargon** [comment]
@jeffsmith82

Many thanks!


Yes, this is my mistake; I did not know that ab works with tcp connections this way. With such parameters, it outputs stably ~ 40k, which is really surprising.
The test still could not load actix so there is nothing in TIME_WAIT. When loading the processor at 60-70% and time 20 sec.


But the node with the same parameters performs the test in 126 sec and the processor load is 100%. With a result of ~7k and ~13k in TIME_WAIT (watch -n 1).


So the question is closed again thanks a lot for the explanation.
