### ISSUE TITLE
request "context"

### ISSUE THREAD

**Issue by wyanlord** [actix/actix-web#1458]
In the entire request process, a container like kv storage is needed to store some request id, which can be used to concatenate all services.

**Comment by Jonathas-Conceicao** [comment]
Can [Extensions](https://docs.rs/actix-web/2.0.0/actix_web/dev/struct.Extensions.html) be used for that? They are a generic storage associated to the request and can be accessed by [HttpRequest::extensions](https://docs.rs/actix-web/2.0.0/actix_web/struct.HttpRequest.html#method.extensions) and modified by [HttpRequest::extensions_mut](https://docs.rs/actix-web/2.0.0/actix_web/struct.HttpRequest.html#method.extensions_mut).

**Comment by 0x8f701** [comment]
@wyanlord can this be closed?
