### ISSUE TITLE
Determining which route is which from middleware

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#146]
Is it possible to identify the current route from middleware? For example some kind of identifier for the route which can be used to apply rules / handle caching / etc.

**Comment by fafhrd91** [comment]
It is not possible at the moment, but I already thought about this. I will add current route info later today

**Comment by fafhrd91** [comment]
Added [HttpRequest::resource()](https://actix.github.io/actix-web/actix_web/struct.HttpRequest.html#method.resource)
