### ISSUE TITLE
ConnectorPoolSupport leaks in each pool call

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#1464]
https://github.com/actix/actix-web/blob/751253f23e54b4eae6665b858430d9c1fc79b8d7/actix-http/src/client/pool.rs#L95

**Comment by cdbattags** [comment]
Any more data/sample code to support this claim?

**Comment by fafhrd91** [comment]
Did you actually check link I posted?

**Comment by jtescher** [comment]
@cdbattags that future is spawned on every awc request, and you can see that it will never complete in https://github.com/actix/actix-web/blob/d5ceae20740837bddef85053c3354452b437877a/actix-http/src/client/pool.rs#L435-L484

**Comment by jtescher** [comment]
Was this meant to be tied to the lifecycle of the pool rather than one per request?

**Comment by robjtede** [comment]
Tenatively fixed with #1580.
