### ISSUE TITLE
How to set Byte payload config

### ISSUE THREAD

**Issue by stevemk14ebr** [actix/actix-web#1469]
I cannot figure out how to set the payload limit for the Bytes type. I'm trying to use

```
async fn view_index_features(state: ActixAppState, _: HttpRequest, body: Bytes) -> Result<HttpResponse, Error> {
 ...blah...

}

App::new()
     .wrap(middleware::Logger::default())
     .app_data(app_state.clone())
     .service(web::resource("/index/")
         .app_data(web::PayloadConfig::new(1000000 * 250))
         .route(web::put().to(view_index_features)))
```

But this gives an app_data is not configured error. If i do .data() on the app itself the payload limit is not respected and i get a 413: A payload reached size limit. I'm on the latest actix 2 version

**Comment by stevemk14ebr** [comment]
Wait... can you not have a stateful app, and also configure route upload settings? I got it working if i do the app_data at the App level but it doesn't work at the service level. How do i get different configs at the service level

**Comment by Jonathas-Conceicao** [comment]
Could you try using [FromRequest::configure](https://docs.rs/actix-web/2.0.0/actix_web/trait.FromRequest.html#method.configure) for it? Something like:
```Rust
.app_data(actix_web::web::Bytes::configure(|cfg| {
    cfg.limit(1000000 * 250) // Set max file size to 6 Mib
}))
```

Documentation for [JsonConfigure](https://docs.rs/actix-web/2.0.0/actix_web/web/struct.JsonConfig.html) has a more complete example for it.

**Comment by stevemk14ebr** [comment]
The bytes type does not have a configure field

**Comment by stevemk14ebr** [comment]
I get the same error about app data not being configured if i do that. I believe this is because service app_data overrides app level app_data but i am not sure. I have to add the config as an app level config but that effects all routes.

**Comment by stevemk14ebr** [comment]
@robjtede i know you did some work with this data layer stuff. Is the behavior i am seeing expected. A working configuration is:
```
    let srv = HttpServer::new(move || {
            App::new()
                .wrap(NormalizeSlash)
                .wrap(middleware::Logger::default())
                .wrap(Cors::default())
                .app_data(app_state.clone())
                .app_data(web::PayloadConfig::new(1000000 * 250))
                .app_data(web::Json::<ViewMultFeatureSamplesInput>::configure(|cfg| {
                    cfg.limit(1000000 * 25).error_handler(json_error_handler) 
                }))
```

The json config must be specified at the top level .app_data. If i move it to any route below i get a runtime error about data not being configured and it appears to 'unregister' my app_state.clone() data line.

**Comment by cybuch** [comment]
It doesn't work for me as well. I use actix-rt 1.0.0 and actix-web 2.0.0
Here's my config:
```
    HttpServer::new(move || {
        App::new()
            .data(app_config.clone())
            .app_data(web::PayloadConfig::new(50_242_880))
            .data(Client::new())
            .wrap(middleware::Logger::default())
            .route("/{path:.*}", web::get().to(proxy))
    }).bind(server_address)
        ?.run()
        .await
```

where `proxy` is:
```
pub async fn proxy(
    original_request: HttpRequest,
    body: Option<web::Bytes>,
    client: web::Data<Client>,
    app_config: web::Data<AppConfig>
) -> Result<HttpResponse, Error> {
```
And I'm getting `Overflow` error. However I've found in `payload.rs` in line 197 that it loads `PayloadConfig` from the app data registry or it uses default one. Unfortunately I use IntelliJ with Rust plugin so I haven't got debug, but I see that it doesn't use my config. Am I doing anything wrong? I've tried multiple options e.g. use the configure function as @Jonathas-Conceicao suggested, but it doesn't work. I still get 413 response with Overflow error.

**Comment by cybuch** [comment]
If you call HTTP client that will have response larger than 256kb then you should also set limit for that response e.g. 
```
            request.send()
                .await
                .map_err(Error::from)?
                .body()
                .limit(1024)
```

**Comment by robjtede** [comment]
Just following up @stevemk14ebr, this might be solved by the changes made to data stacking in v3 beta.

**Comment by robjtede** [comment]
I believe this issue is fixed. Please open a new issue if further problems arise.

**Comment by kpcyrd** [comment]
I've opened a discussion on how to do this with actix-web 4: https://github.com/actix/actix-web/discussions/2722
