### ISSUE TITLE
test::TestRequest::post().param() not working, query params is empty

### ISSUE THREAD

**Issue by pymongo** [actix/actix-web#1471]
```rust
#[post("/post_test")]
pub async fn post_test(req: HttpRequest) -> impl Responder {
  let params = req.match_info();
  format!("params.is_empty()={}, value={}", params.is_empty(), params.query("key"))
}

// tests
#[actix_rt::test]
async fn test_for_post_test() {
  let mut app_service = test::init_service(App::new().service(post_test)).await;

  let req = test::TestRequest::post()
    .param("key", "123")
    .uri("/post_test")
    .to_request();
  let resp = test::call_service(&mut app_service, req).await;
  let resp_body = test::read_body(resp).await;
  let resp_string = std::str::from_utf8(&resp_body).unwrap();
  assert_eq!(resp_string, "params.is_empty()=false, value=123");
}
```

**Expected:** params.is_empty()=false, value=123  
**Actual:** &nbsp;&nbsp;&nbsp;&nbsp; params.is_empty()=true, value=

I put param("key", "123") on test::TestRequest::post(), but request's query params is **empty**

## Environment

* Rust Version: 1.4.2
* Actix Web Version: 2.0.0
* OS: macOS 10.14.6

**Comment by robjtede** [comment]
AFAICT, using `.param("id", "1")` is for path parameters like `/user/:id`. If you're trying to set a querystring like `...?key=123` then it needs to be included in the `.uri("...?a=1")` call and extracted in the handler with `HttpRequest::query_string` or using the `web::Query<T>` extractor.
