### ISSUE TITLE
Re-export awc::error::JsonPayloadError

### ISSUE THREAD

**Issue by cryslith** [actix/actix-web#1474]
I'm trying to decode a returned json response from a web server while handling the response appropriately.  However, the error from the `actix_web::client::ClientResponse::json` method cannot be handled easily because there is no way to refer to `awc::error::JsonPayloadError` without adding an additional dependency on `awc`, which seems to defeat the purpose of `actix_web` reexporting most of the `awc` interface in the first place.

One solution would be to re-export JsonPayloadError in `actix_web::client`.  Another is to just add a re-export for the whole `awc` crate to solve future issues of this type.

**Comment by attila-lin** [comment]
Is it exported already?

https://docs.rs/actix-web/3.0.0-alpha.2/actix_web/error/enum.JsonPayloadError.html

**Comment by cryslith** [comment]
No.  That is a different type.

**Comment by attila-lin** [comment]
Got it!
I think I can help to make them the same one.
