### ISSUE TITLE
Question: Handle form data with dynamic number of fields and field types

### ISSUE THREAD

**Issue by zmilan** [actix/actix-web#1475]
Hi,

I have struggled to find the right way to handle a form submission with a dynamic number of fields. When you have a known number of fields and their types you can create a struct and it works awesome. But I need to handle requests which can have 1 or 20 fields and they can be all types of string or int or boolean.

The only way that I have found is something like this, but I'm not sure that is the best/right way to do it:

`
/// extract text data from request

async fn index(text: String) -> String {
    format!("Body {}!", text) // Body input1=blah%20truc&input2=1221&input3=12.12&input4=true
}
`
And then I could parse it and continue with business logic.

Is there some better way to handle this?

**Comment by robjtede** [comment]
Using an extractor with a shape like `web::Form<HashMap<String, String>>` should work

**Comment by zmilan** [comment]
@robjtede great thanks, I have tried to implement it with HasMap by like field inside of struct, which didn't work. This looks much better and exactly what I was looking for...
