### ISSUE TITLE
How to ask a server to stop from a handler?

### ISSUE THREAD

**Issue by artemshein** [actix/actix-web#148]
And how to get a server actix System from a handler?

**Comment by fafhrd91** [comment]
you need server address. `HttpServer::start()` returns `Addr<Sync, HttpServer>`.
then from handler you need to send `server::StopServer` message.

**Comment by fafhrd91** [comment]
what is the purpose? you can also stop whole System, in that case all actors that run in this system stop. this is pretty easy.

```rust
actix::Arbiter::system().do_send(actix::msgs::SystemExit(0))
```

**Comment by artemshein** [comment]
Ok, thanks

**Comment by kylixs** [comment]
The latest way :
actix::Arbiter::current().stop()
