### ISSUE TITLE
feature request: expose actix_web::service

### ISSUE THREAD

**Issue by unional** [actix/actix-web#1480]
I want to write a plugin based web application.
One of the things I want to do is to put a reference of `App` in a struct and pass that struct to the plugins to register routes.

Something like this (simplified):

```rust
// application
struct Activator<'a> { app: &'a App }

fn load_plugin<'a>(app: &'a App) {
  let a = Activator::new(app)
  let func = libloading::Symbol<
    unsafe extern "Rust" fn(a: Box<dyn Activator>)
  > = libloading.get(b"activate")?;
  unsafe { func(Box::new(a)) }
}

// plugin
pub fn activate(activator: Box<dyn Activator>) {
  activator.add_route("/", web::get()::to(greet));
}
```

When doing that, I run into problem with the type constraint of `T`:
```rust
struct Activator<'a, T, B>
where
  B: MessageBody,
  T: ServiceFactory<
    Config = (),
    Request = ServiceRequest,
    Response = ServiceResponse<B>,
    Error = Error,
    InitError = (),
  >,
{
  app: &'a App<T, B>,
}
```

The `ServiceRequest` and `ServiceResponse` is not exposed.
And since Rust is nominal type, I can replace the constraint with my own definition and make it work.

So I get an error like this:
```rust
// service is private
use actix_web::service::ServiceResponse;
```

I'm new to Rust, so what I try to do may not be idiomatic (or even correct) for Rust.
If there are better ways to achieve this, please let me know.

I wanted to do it like this because:

- Plugin has better development experience. With access to the `Activator` struct the developer can leverage auto-complete to get exactly what is needed.
- Plugin can obtain runtime status from the Application and do different things.

In contrast, I can tell to plugin to expose simple functions to get configuration:

```rust
// plugin
function get_setup(app_state: Box<dyn AppState>) -> Config {
  Config::new(
    Route::new("/", web::get()::to(greet))
  );
}
```

* Rust Version (I.e, output of `rustc -V`): 1.43.0
* Actix Web Version: 2.0.0

**Comment by robjtede** [comment]
`ServiceRequest` and `ServiceResponse` are exposed by the `actix_web::dev` module.

**Comment by unional** [comment]
Thanks!
