### ISSUE TITLE
Configurable body size with JSON extractor

### ISSUE THREAD

**Issue by tazjin** [actix/actix-web#149]
Hey,

I'm playing with the new extractors on `master` and am currently a bit confused about whether it's possible to change the maximum request body size (seems to be hardcoded to 256kb) for extractor-decoded JSON bodies.

It seems like there's a [limit function](https://github.com/actix/actix-web/blob/b2e771df2cb4130889a5e45cfff97a76772639ce/src/json.rs#L175) for a related purpose, but the instance of `JsonBody` used by specifying a `Json<T>` extractor doesn't seem available to the user.

Is this supported atm?

Thanks!

**Comment by fafhrd91** [comment]
Configuration is not supported yet. I am planing to add something before release

**Comment by fafhrd91** [comment]
Now .with() returns `ExtractorConfig<T>`

Here is [example](https://actix.github.io/actix-web/actix_web/dev/struct.JsonConfig.html)

**Comment by tazjin** [comment]
Awesome, thank you!

**Comment by ZelphirKaltstahl** [comment]
This looks so neat, I might change the code I have already in my project to use this …

**Comment by fafhrd91** [comment]
right now you can configure only size of the body. but we can add more configuration, like 
content-type, custom error handling, etc.

thoughts?

**Comment by ZelphirKaltstahl** [comment]
I like that one can declare the expected type in the `Json<type here>` in the handler. Is the handler then never called with wrong JSON, or does it log an error and ignore the JSON? Anyway, this should avoid some bugs and quickly reveal wrongly structured JSON arriving at the server side.

I don't know, whether there is already some example for how to do CORS, but I imagine that one could specify a list of allowed hosts too (`.with(…).allowed_origins(some kind of origin list or expression)`), best already implemented in a way that allows more than either 1 origin or `*`. This might make sense if it is possible, to specify more than one HTTP method, for example GET + OPTION for the actual request and pre-flight stuff.

This should probably go into another issue. Oh and nevermind, I just found: https://actix.github.io/actix-web/actix_web/middleware/cors/index.html

**Comment by fafhrd91** [comment]
handler is never called with wrong json. it is not possible to influence error at the moment, but I think jsonconfig should support custom error handler.

for CORS you can check this example https://github.com/OUISRC/Rust-webapp-starter
cors is not very ergonomic, but I am planing to change it before 0.5 release
