### ISSUE TITLE
What is NO_CHUNKING streaming?

### ISSUE THREAD

**Issue by omid** [actix/actix-web#1492]
You can find NO_CHUNKING flag [here](https://github.com/actix/actix-web/blob/master/actix-http/src/message.rs#L29) and also the main logic over it [here](https://github.com/actix/actix-web/blob/master/actix-http/src/h1/encoder.rs#L79).

There is also a test related to this which you can find it [here](https://github.com/actix/actix-web/blob/master/tests/test_server.rs#L370).

As far as I understood, it's sending a stream with Content-Length (means without Transfer-Encoding). So it means we know the size beforehand!

For what reason, we don't want to use Transfer-Encoding: chunked?
What's the purpose of it? Why should we support such a thing?

PS: This question pops up after our discussion and PR related to #1439 .

**Comment by fafhrd91** [comment]
It is for this case https://github.com/actix/actix-web/blob/master/actix-http/src/body.rs#L18

Example https://github.com/actix/actix-web/blob/b521e9b2218a23b3c2e288611ec123042b287053/actix-files/src/named.rs#L394

**Comment by omid** [comment]
Thanks :-)
I'll close this issue and continue the discussion in #1439
