### ISSUE TITLE
How to return a file as response?

### ISSUE THREAD

**Issue by TheCGDF** [actix/actix-web#1498]
For example, I have a file(`1800.zip`) on my server.
When user click "download" button or use download link(`http://......com/download?name=1800.zip`), the server should return "1800.zip" as response.
![vivaldi_YqyYQtRUMn](https://user-images.githubusercontent.com/17256673/81464736-27e18300-91ff-11ea-851f-60130eb69dcc.jpg)

However, I cannot find some examples about this.

**Comment by omid** [comment]
Here is the example project of serving static files:

https://github.com/actix/examples/tree/master/static_index

**Comment by Stigjb** [comment]
I found this thread via a search, but the above example project link is dead. Here is the updated one:

https://github.com/actix/examples/tree/master/basics/static-files
