### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#15]
Hello

I discover actix-web. When I follow the instructions of the example https://actix.github.io/actix-web/guide/qs_2. html with this code

```
fn main () {

    let sys = actix:: System:: new ("example");

    let app = Application:: new ()
        . resource ("/", |r| r. f (index)
        . finish ();

    HttpServer:: new (|| app)
        . bind ("127.0.0.0.1:8088"). unwrap ()
        . start ();

}
```

then I have the mistake 

```
HttpServer:: new (|| app)
^^^^^^^^^^^^^^^^^^^^^^`actix_web:: application:: HttpApplication` is not an iterator; maybe try calling ``iter ()` or a similar method
```

How to compile the code ``HttpServer:: new (|| app)`` without error? 

The final example works but is not consistent with the first steps indicated.

Thank you

**Comment by fafhrd91** [comment]
I updated guide

**Comment by AlbanMinassian** [comment]
Thank you
