### ISSUE TITLE
actix-* 3.0 sync

### ISSUE THREAD

**Issue by igor-raits** [actix/actix-web#1510]
Hello,

Maintainer of actix-* crates in Fedora speaking here.

I am curious if there is any plan to make synchronized release of actix crates with version 3.x? Right now, actix-files depends on actix-web `2.0.0-rc`, and there is already 3.0.0-alpha.3 is around. They are maintained together, so I am curious why there were no releases to sync that version.

Moreover, I think some of dev-deps still mention actix* 1.0 on crates.io.

It would be amazing to see some plan (and probably some timelines) when the new 3.x stack would be released.

Thanks!

**Comment by igor-raits** [comment]
@JohnTitor any comments? :)

**Comment by JohnTitor** [comment]
Yeah, I'm aware of that, making releases for actix-related crates recently.

**Comment by JohnTitor** [comment]
I think we've done most alpha releases in this repository, the rest item is to do backports. Is there anything that I'm missing?

**Comment by igor-raits** [comment]
@JohnTitor I think the things which are in Fedora are now in better shape. Thank you!

**Comment by rofrol** [comment]
Can it be closed?

**Comment by JohnTitor** [comment]
Yeah, I think so. Let me know if I'm missing something :)
