### ISSUE TITLE
Request time is doubled in Logger middleware

### ISSUE THREAD

**Issue by bwasty** [actix/actix-web#152]
The `%T` at the end of the standard format for the logger middleware always prints twice the amount of time passed (tested with some `thread::sleep` calls).

The culprit seems to be here:
https://github.com/actix/actix-web/blob/74d0656d27e6afd87c6a0b805eb88e581410fb38/src/middleware/logger.rs#L235-L236

-> `num_nanoseconds` is the whole duration (in contrast to `std::time::Duration::subsec_nanos`).

**Comment by fafhrd91** [comment]
interesting. thanks for report.

**Comment by fafhrd91** [comment]
fixed by 83bf852
