### ISSUE TITLE
I'm missing an explaination of how the actor model is implemented

### ISSUE THREAD

**Issue by MrEmanuel** [actix/actix-web#1521]
I read the half finished Actix book which is great. It gives a good introduction to the actor model that Actix is based on. Very informative and useful. The Ping example is amazingly simple and good! [Actix Ping Example](https://actix.rs/book/actix/sec-1-getting-started.html)

I am missing the same type of conceptual connection to Actix-web. I can't see the actor model through actix-web. Have it been abstracted away? Or how does the Actix base and the actor model "shine through" in actix-web? 

I would greatly appreciate an explanation as I think it would help me reason about the framework and get an overview of it better. 

Thanks!

**Comment by adwhit** [comment]
My understanding is `actix-web` originally used `actix` internally, but that is no longer the case - they can be thought of as independent projects. In that sense the name is anachronistic.

However, they still play well together. A pattern I have used is: you receive a request that should trigger some kind of 'slow' task (e.g. vacuuming a database) - spawn off an actor to handle the task, and return a response immediately. This stops you from blocking the client on the task. (Sure, this could be done just by spawning a new thread, using an actor is just a bit more principled).

**Comment by MrEmanuel** [comment]
Thanks for the clarification. 
I guess I'm finding it a bit hard to get a good overview of actix-web. It's easy to understand actix with it conceptual actor model. It's hard to understand actix-web without an overview of the high level concepts. 
I'm quite visual I think and always appreciate a nice system diagram. :) 

Reading https://actix.rs, let's see if I get this. 
Actix-web has Responders that provide an interface to deliver information through http. (i.e give a http response).
It also has Extractors that receive http requests. 
Same for form handling and routing of paths. 
So far so good? 

I think the missing piece of the puzzle for me is how it all fits together in a complete web app. 
I guess I'll have to work through a few more examples and see if it "clicks". 

I'm closing the issue and will try to make a PR if I can find a way to contribute in the future regarding this. If a contributor feel like a conceptual overview is needed, feel free to open the issue again. Thanks. :)

**Comment by robjtede** [comment]
Yeah, you seem to have picked up the main ideas from the website alright 👍.

The high level can maybe be expressed in a crude ascii pictoral form as:

```
             DB/other services/etc.
                      ^ |
                      | |
                      | V
                   your handler
                  (with app data)
                ^                V
    Extractors  |                |
   (actix-web)  |            HttpResponse
                |                |
       Routing  |                |
   (actix-web)  ^                V
                |                |
           HttpRequest           |
                |           ServiceResponse
                |                |
                |                |
    Middleware  |                |  Middleware
   (actix-web)  |                |  (actix-web)
                |                |
                |                |
         ServiceRequest          |
                |                |
  HTTP Framing  |                |  HTTP Framing
  (actix-http)  ^                V
                |                |
           TCP Packets       TCP Packets
                |                |
                |                |
    TCP Socket  |                |
    (actix-net  |                |
     packages)  ^                V
                |                |

```


There's usually folks available on the [Gitter Chat](https://gitter.im/actix/actix-web) to help answer questions, too.

**Comment by shujaatak** [comment]
@MrEmanuel I have a hard time understanding how everything is interconnected in actix-net and actix-web. I am also a visual learner and the UML or Sequencing Diagram might have helped a lot if it could be accessed somewhere.

The crude ascii pictoral form shared by **robjtede** is one step towards it but fairly complete diagram will help new users / contributors a lot.
