### ISSUE TITLE
Guard provides immutable reference, how to set request extension? [Question]

### ISSUE THREAD

**Issue by wbrickner** [actix/actix-web#1524]
Hello,

I have written a custom guard to validate a JWT header on requests.

During validation I end up with the contents of the JWT which will likely be needed by whichever  route handler.

In the Guard documentation it's noted that while you can't modify the request itself, it's recommended that one use request extensions to store data on the request.

I'm unable to get a mutable reference to the request extension by using `req.extensions()`.

I'm an Actix newbie, so maybe I'm missing something.

What's the idiomatic way of writing to an extension from a guard?
I can't seem to find any information in the docs.

Thank you!

**Comment by robjtede** [comment]
Guards are for routing. You should implement logic for reading JWTs in a Extractor (search docs for “FromRequest”) or Middleware.

There’s folks available on the Gitter chat if you have more questions as you go.
