### ISSUE TITLE
NormalizePath inconsistent trailing slash 

### ISSUE THREAD

**Issue by Fabianstelmach** [actix/actix-web#1536]
The `NormalizePath` middleware is inconsistent in the `3.0.0-alpha.3` version. Using a route `/user/{id}/` and the `NormalizePath` middleware, the trailing slash is only added when the request path contains duplicated slashes somewhere else.

Minimal example to reproduce:

```
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        App::new()
            .wrap(middleware::NormalizePath)
            .route("/user/{id}/", web::get().to(| | HttpResponse::Ok().body("hello world")))
        })
    .bind("127.0.0.1:8088")?
    .run()
    .await
}
```

## Expected Behavior
I expect the trailing slash to be added regardless of the amount of duplicate slashes in the rest of the path.
| Request Path  | Expected Response |
| ------------- | ------------- |
| /user/1 | 200  |
| /user//1  | 200  |

## Current Behavior

The trailing slash is added only if there are duplicate slashes somewhere in the path.
| Request Path  | Actual Response |
| ------------- | ------------- |
| /user/1 | 404 |
| /user//1  | 200  |
## Possible Solution

The current implementation of NormalizePath [looks like this:](https://github.com/actix/actix-web/blob/b9e268e95fb433aa69f3ac08cbbebd820afe0e05/src/middleware/normalize.rs#L78)
```
...
        // always add trailing slash, might be an extra one
        let path = head.uri.path().to_string() + "/";
        let original_len = path.len();

        // normalize multiple /'s to one /
        let path = self.merge_slash.replace_all(&path, "/");

        if original_len != path.len() {
...
```
The path is only updated if `original_len != path.len()`. But `original_len` is the length with the trailing slash added. If adding the trailing slash is the only change, then the URI will not be updated.

A possible solution could be to calculate the `original_len` before adding the extra slash, like this:
```
...
        let path = head.uri.path().to_string();
        let original_len = path.len();

        // always add trailing slash, might be an extra one
        let path = path + "/";

        // normalize multiple /'s to one /
        let path = self.merge_slash.replace_all(&path, "/");

        if original_len != path.len() {
...
```

## Steps to Reproduce (for bugs)

1. Run the example code
2. Make a GET request to `127.0.0.1:8088/user/1`

## Context

I wish to use the NormalizePath middleware to append a trailing slash to the route regardless of the rest of the path.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): `1.43.1 (8d69840ab 2020-05-04)`
* Actix Web Version: `3.0.0-alpha.3`

**Comment by stevemk14ebr** [comment]
Hi, i am responsible for that length bug, the relevant commit is: https://github.com/actix/actix-web/commit/aaff68bf05fd69bf0ea652dc5507c31729e49050 do you want to submit a PR to fix? I agree with your analysis that the orginal length should be calculated first. Please add a test case as well for this.

**Comment by Fabianstelmach** [comment]
Thank you for your response. I will submit a PR soon.
