### ISSUE TITLE
web::Payload total size is half of expected size

### ISSUE THREAD

**Issue by adelbertc** [actix/actix-web#1543]
## Expected Behavior
If I send a file of size N and it gets routed to a handler with `web::Payload`, and I then sum the length of the bytestring of each chunk, it should sum to N.

## Current Behavior
Instead it sums to N/2.

This same thing happens with a randomly generated 1 GB payload, 512 MB payload, or 256 MB payload. I assume it happens with anything.

## Steps to Reproduce (for bugs)

Build:
```toml
[package]
name = "mini-app"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
futures = "0.3.5"
bytes = "0.4.12"
```

Code:
```rust
use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use futures::future::FutureExt;
use futures::stream::StreamExt;

async fn upload(payload: web::Payload) -> impl Responder {
    let size: usize = 0;

    payload.fold(size, |acc, msg| async move {
        let size = msg.unwrap().len();
        acc + size
    }).map(|i| {
        HttpResponse::Ok().body(i.to_string())
    }).await

    // I tried this too just in case..
    // while let Some(p) = payload.next().await {
    //     let psize = p.unwrap().len();
    //     println!("Payload piece is: {}", psize);
    //     size += psize;
    // }
    // println!("{}", size);
    // HttpResponse::Ok().finish()
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(web::resource("/upload").route(web::post().to(upload)))
    })
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

```
$ dd if=/dev/urandom of=data.dat bs=1G count=1
$ curl -i localhost:8080/upload --data @./data.dat
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
content-length: 9
date: Sat, 30 May 2020 03:12:39 GMT

532200804
```

532200804 bytes is ~ 0.5 GB.

## Your Environment
```
actix-web = "2.0.0"
actix-rt = "1.0.0"
```

**Comment by Lesiuk** [comment]
Also all of the line feeds (0a, \n) are missing
![image](https://user-images.githubusercontent.com/543264/83976762-56d13e80-a8fc-11ea-8271-b712336e643e.png)

UPDATE:
Your command was wrong. You should use ```curl -i localhost:8080/upload --data-binary @./data.dat```. As stated by curl documentation

> **--data-ascii**
> 
> (HTTP) This is just an alias for -d, **--data.**
> 
> **--data-binary**
> 
> (HTTP) This posts data exactly as specified with no extra processing whatsoever.
> 
> If you start the data with the letter @, the rest should be a filename. Data is posted > in a similar manner as -d, --data does, **except that newlines and carriage returns** are > > preserved and conversions are never done.
> 
> Like -d, --data the default content-type sent to the server is application/x-www-form-> > urlencoded. If you want the data to be treated as arbitrary binary data by the server > then set the content-type to octet-stream: -H "Content-Type: application/octet-stream".
> 
> If this option is used several times, the ones following the first will append data as > described in -d, --data.

**Comment by Lesiuk** [comment]
Your command was wrong. You should use ```curl -i localhost:8080/upload --data-binary @./data.dat```

**Comment by robjtede** [comment]
Seems the wrong curl flag was the reason. Ping @adelbertc. I was doing testing with large files recently using --data-binary and getting correct sizes reported. Closing.

**Comment by adelbertc** [comment]
👍 Ahh interesting I did not know about that distinction for cURL - thanks!
