### ISSUE TITLE
actix-web-codegen hides function documentation

### ISSUE THREAD

**Issue by deavid** [actix/actix-web#1549]
When we add a new method for actix using the macros like in [this example], the documentation of the function disappears when doing "cargo doc". This is because the macro is moving the function inside another function: [macro source code]

This leaves basically two options, add documentation even if it's not visible, or avoid using the macros.

For me it would be nicer if there was a second form of the macro that did not hide the function at all. For example:
```rust
#[service_get("/welcome", dst="welcome_service")]
fn welcome(session: Session, req: HttpRequest) -> Result<HttpResponse> {
  todo!()
}
(...)
fn main() -> io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(welcome_service)
(...)
```

This also would allow the documentation to find the original function and signature, which would be less confusing.

(I'm still new to Rust, probably there are better ways of doing this)

[this example]: https://github.com/actix/examples/blob/44053504ad39b2bb023712c7577a06091629ad41/basics/src/main.rs#L24
[macro source code]: https://github.com/actix/actix-web/blob/master/actix-web-codegen/src/route.rs#L209

**Comment by robjtede** [comment]
this was fixed a while back

https://github.com/actix/actix-web/pull/2022
