### ISSUE TITLE
websockets always close with error code 1006

### ISSUE THREAD

**Issue by BartWillems** [actix/actix-web#1555]
## Expected Behavior

When a client stops an active websocket session, the server should respond with the correct code.
Example: 1000 when a disconnect message is sent, or 1001 when the user changes pages.
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

## Current Behavior

The webserver always responds with 1006 (Abnormal Closure)

## Possible Solution

Respond with the correct exit code.

## Steps to Reproduce (for bugs)

1. Clone the websocket chat broker example: https://github.com/actix/examples/tree/master/websocket-chat-broker
2. Log the disconnect event (eg: change `socket.onclose = () =>` to `socket.onclose = (msg) =>` and log `msg`) in https://github.com/actix/examples/blob/master/websocket-chat-broker/static/index.html#L147
3. start the chat broker, connect & disconnect, observe in the console of the browser

## Context

I'm using actix in this project: https://github.com/BartWillems/rustfuif
I want to attempt to reconnect with the webscocket if an unexpected disconnect occurs and notify the user when the server connection is lost.
Currently this is not possible because all disconnects look unexpected.

## Your Environment

Problem occurs in both Firefox and Chromium.

* Rust Version (I.e, output of `rustc -V`): 1.44.0
* Actix Web Version: ^2.0

**Comment by rustrust** [comment]
Maybe it would be worth upping the priority of including autobahn tests

https://github.com/actix/actix-web/issues/1006

**Comment by robjtede** [comment]
Removing the bug label since it was a bug in the example not in the framework.
