### ISSUE TITLE
Copying the cookie crate without attribution violates its licenses

### ISSUE THREAD

**Issue by SergioBenitez** [actix/actix-web#1556]
Hello!

It appears that the entirety of the [`cookie`](https://github.com/SergioBenitez/cookie-rs) crate, with the exception of its license(s), has been [copied into the `actix-http` crate](https://github.com/actix/actix-web/tree/4f9a1ac3b761dd2b8aa31e086ad84d8455e7893b/actix-http/src/cookie) . This is in violation of the two license options (MIT and Apache 2.0) at your disposal, both of which require attribution. Furthermore, it looks like [upstream](https://github.com/SergioBenitez/cookie-rs/commit/50ef66357921673d8292aeecd344d2645ba65fe4) [commits](https://github.com/SergioBenitez/cookie-rs/commit/451928eada489322e4c49f9c38dd2f8604e5ec50) are simply being [copied](https://github.com/actix/actix-web/commit/63864ecf9e3e6b8dbf883d3030267a525fb50a18#diff-dc185b5b55e47631d97ea058d6e405b5) [here](https://github.com/actix/actix-web/commit/d5ceae20740837bddef85053c3354452b437877a#diff-dc185b5b55e47631d97ea058d6e405b5), again without attribution. And, while this latter point doesn't further violate any licenses, I would consider it poor practice and poor open-source citizenship.

Please either attribute the `cookie` code as per either the MIT license or the Apache 2.0 license or remove the code from your repository. Better yet: why not use `cookie` as a dependency? You'd benefit from upstream improvements automatically, and any improvements you've made here could potentially benefit the community at large. In true open-source fashion: it's a win-win. Please do consider this latter option.

Thank you!

**Comment by robjtede** [comment]
Thanks for pointing this out Sergio. PR #1558 migrates handling to the crate.

**Comment by mocsy** [comment]
I remember reading it in the docs, that it was copied from that crate, and that it needed some modifications. There was a technical reason involved as well. I can't seem to find that part though.
