### ISSUE TITLE
[awc::Client] Connect(Timeout) occurs on sending requests to different hosts 

### ISSUE THREAD

**Issue by LexxFedoroff** [actix/actix-web#1563]
Hello, I faced with weird behaviour of awc::Client
I have the following code: 
```rust
use awc::Client;
use std::io;

#[actix_rt::main]
async fn main() -> io::Result<()> {
    let res = Client::default()
        .get("https://httpbin.org/status/200")
        .send()
        .await;
    assert_eq!(200, res.unwrap().status());

    let res = Client::default().get("https://yandex.ru").send().await;
    assert_eq!(200, res.unwrap().status());

    Ok(())
}
```
Full project was pushed to the [repo](https://github.com/LexxFedoroff/awc_client_timeout)

## Expected Behavior
The program should finish without any errors. I expect that I receive two 200's http code. 

## Current Behavior
I get the error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Timeout)', src/main.rs:13:21
```

## Steps to Reproduce (for bugs)
just run the project `cargo run`

## Your Environment
* Rust Version (I.e, output of `rustc -V`):
`rustc 1.44.0 (49cae5576 2020-06-01)`
* Actix Web Version:
```
actix-web = { version = "2.0.0", features = ["openssl"] }
actix-rt = "1.1.1"
awc = "1.0.1"
```

**Comment by JakeOShannessy** [comment]
I've been having the same issue, in fact it's always timing out after 1 s (the time between creating the request and it through an error is consistently in the range of 1,000-1,015 ms for me). The default timeout is supposed to be 5 s, but even modifying the timeout on either the client (in general) or the request doesn't seem to make an impact.

Using curl takes me about 200 ms to get a response from yandex and 80 ms from google. So even if the timeout was 1 s it doesn't seem like it should be tripped. This happens always on Windows and only occaisionally on Linux. I'm yet to work out under what circumstances it fails on Linux.

I've added a slight variation to the test code you provided. It works find to localhost.

```rust
use awc::{Client, ClientBuilder};
use std::{time::Duration, io};

#[actix_rt::main]
async fn main() -> io::Result<()> {
    {
        let t1 = std::time::Instant::now();
        let res = Client::default().get("http://localhost:8080").timeout(Duration::from_secs(20)).send().await;
        let t2 = std::time::Instant::now();
        eprintln!("Localhost Time: {} ms", (t2-t1).as_millis());
        assert_eq!(200, res.unwrap().status());
    }
    {
        let t1 = std::time::Instant::now();
        let res = Client::default().get("http://google.com").timeout(Duration::from_secs(20)).send().await;
        let t2 = std::time::Instant::now();
        eprintln!("Google (Client) Time: {} ms", (t2-t1).as_millis());
        assert_eq!(200, res.unwrap().status());
    }
    {
        let t1 = std::time::Instant::now();
        let client = ClientBuilder::new().timeout(Duration::from_secs(20)).finish();
        let res = client.get("http://yandex.ru").send().await;
        let t2 = std::time::Instant::now();
        eprintln!("Yandex (ClientBuilder) Time: {} ms", (t2-t1).as_millis());
        assert_eq!(200, res.unwrap().status());
    }
    {
        let t1 = std::time::Instant::now();
        let res = Client::default().get("http://yandex.ru").timeout(Duration::from_secs(20)).send().await;
        let t2 = std::time::Instant::now();
        eprintln!("Yandex (Client) Time: {} ms", (t2-t1).as_millis());
        assert_eq!(200, res.unwrap().status());
    }
    Ok(())
}
```

**Comment by fakeshadow** [comment]
This could be because the default `ConnectorConfig`'s [timeout](https://github.com/actix/actix-web/blob/160995b8d49b8f1e556e4944617c9982f1ac2ad8/actix-http/src/client/config.rs#L22) is 1 second so slow connection would be rejected in place.
Maybe it's a good idea to relax the timeout duration a bit?

When people construct a client without a custom connector setting it's very easy to confuse the timeout of a request with the inner connector.

And a quick fix for you guys. You would want to construct a connector if you expect a slow connection.
```rust
use std::io;
use std::time::Duration;

#[actix_rt::main]
async fn main() -> io::Result<()> {
    let connector = awc::Connector::new()
        // This is the timeout setting for connector. It's 1 second by default
        .timeout(Duration::from_secs(3))
        .finish();

    let client = awc::Client::build()
        .connector(connector)
        // This is the timeout setting for requests. It's 5 seconds by default.
        .timeout(Duration::from_secs(5))
        .finish();

    let res = client.get("https://httpbin.org/status/200").send().await;
    assert_eq!(200, res.unwrap().status());

    let res = client.get("https://yandex.ru").send().await;
    assert_eq!(200, res.unwrap().status());

    Ok(())
}
```

**Comment by JohnTitor** [comment]
> Maybe it's a good idea to relax the timeout duration a bit?

Sounds good! And we could document this behavior somewhere to avoid confusion?

**Comment by fakeshadow** [comment]
> And we could document this behavior somewhere to avoid confusion?

The doc is in the `actix-http` crate and it's pretty accurate but the `awc::Connector` APIs are not exposed through `awc::ClientBuilder` so for now unless user construct a connector manually there is no way to observe or make changes to connector's config.

Maybe we can pass the `ClientBuilder::timeout` or `ClientBuidler::disable_timeout` to connector and make it have the same timeout value as the `Client`'s request timeout.

**Comment by LexxFedoroff** [comment]
Thanks for the advice!
