### ISSUE TITLE
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfRangeError(())', src/alert/alertor.rs:253:28

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#1567]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Rust Version (I.e, output of `rustc -V`):
* Actix Web Version:

**Comment by 0x8f701** [comment]
This error is really not clear for me, can someone tells me what is it about?

**Comment by robjtede** [comment]
Err source is `src/alert/alertor.rs:253:28` in your code. Would need much more info to help. Come ask on the [Gitter chat](https://gitter.im/actix/actix-web).

**Comment by 0x8f701** [comment]
@robjtede sorry just found it's an error from my code later this afternoon but forgot to close it.... while doing convertion from chrono::Duration to stdard duration it overflowed.

Thanks
