### ISSUE TITLE
Unable to run "hello world" program

### ISSUE THREAD

**Issue by shoooe** [actix/actix-web#1569]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

Running the basic README example with:

```toml
[dependencies]
actix-web = "2"
```

and:

```rust
use actix_web::{get, web, App, HttpServer, Responder};

#[get("/{id}/{name}/index.html")]
async fn index(info: web::Path<(u32, String)>) -> impl Responder {
    format!("Hello {}! id:{}", info.1, info.0)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(index))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

and 

## Expected Behavior
The program should compile.

## Current Behavior
The program doesn't compile with:

```
error[E0433]: failed to resolve: could not find `main` in `actix_web`
 --> src/main.rs:8:14
  |
8 | #[actix_web::main]
  |              ^^^^ could not find `main` in `actix_web`

error[E0277]: `main` has invalid return type `impl std::future::Future`
 --> src/main.rs:9:20
  |
9 | async fn main() -> std::io::Result<()> {
  |                    ^^^^^^^^^^^^^^^^^^^ `main` can only return types that implement `std::process::Termination`
  |
  = help: consider using `()`, or a `Result`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0433.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `dcf`.

To learn more, run the command again with --verbose.
```

## Steps to Reproduce (for bugs)
1. Include the framework as dependency
2. Copy and paste the example program
3. `cargo run`

## Context
I'm trying to run the hello world program.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.43.1 (8d69840ab 2020-05-04)
* Actix Web Version: 2

**Comment by shoooe** [comment]
I was looking at the `master` README which apparently is an unstable build?

**Comment by robjtede** [comment]
@shoooe yep please use the official docs on actix.rs or docs.rs/actix-web for v2. Master branch is transitioning for a v3 release.
