### ISSUE TITLE
Inability to configure full request timeout leads to DoS / resource leak in HTTP client

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#1572]
awc currently does not allow specifying a timeout for the entire request (i.e. until the request body is finished transferring), which means an established connection will hang indefinitely if the remote host doesn't stops replying.

While it's not necessary to set such timeout by default (most other HTTP clients don't), it must be possible to configure it for awc to be usable for e.g. building reliable services that query a remiote API over HTTP, or for defending against DoS attacks where the remote host sends 1 byte per second, keeping the connection open indefinitely.

Consider an image hosting service like imgur.com: users enter URLs of images they want to host, and the HTTP client fetches the images and puts them into storage. If a user enters a URL to a malicious host that replies more often than the read timeout, but keeps replying indefinitely, this means that the connection will be open indefinitely. If an attacker keeps getting the service to open such connections, this will eventually lead to the exhaustion of the thread pool or network ports on the client.

**Comment by fakeshadow** [comment]
Would something like this work for you?
```rust
use std::collections::HashMap;
use std::future::Future;
use std::time::Duration;

use actix_rt::time::{timeout, Timeout};

trait EasyTimeout
where
    Self: Sized,
{
    fn timeout(self, dur: Duration) -> Timeout<Self>;
}

impl<F> EasyTimeout for F
where
    F: Future,
{
    fn timeout(self, dur: Duration) -> Timeout<Self> {
        timeout(dur, self)
    }
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let res = awc::Client::new()
        .get("https://crates.io")
        .send()
        .timeout(Duration::from_secs(5))
        .await?
        .unwrap()
        .json::<HashMap<String, String>>()
        .timeout(Duration::from_secs(10))
        .await?;
    Ok(())
}
```

**Comment by Shnatsel** [comment]
The API looks reasonable to me, but I'm not very familiar with awc and its API, so take that with a grain of salt.

`reqwest` implements a timeout for the entire request, perhaps it can be used as inspiration: https://docs.rs/reqwest/0.10.6/reqwest/struct.ClientBuilder.html#method.timeout
