### ISSUE TITLE
Describe websocket functionality as beta in README.md?

### ISSUE THREAD

**Issue by rustrust** [actix/actix-web#1573]
Autobahn tests report a great many failed test results for actix-web websockets functionality:

https://htmlpreview.github.io/?https://github.com/mlodato517/examples/blob/ml-start-autobahn-test-suite/websocket-autobahn/autobahn-test-results/index.html

The webpage describes websockets as part of actix-web functionality, but makes no indication that it is still a work-in-progress. Perhaps this should be changed?

**Comment by fafhrd91** [comment]
this kind of issues and comments remind me why I don't work on actix anymore, very nice.

**Comment by rustrust** [comment]
I don't see anything wrong with asking to make it more clear to new users of actix-web that the websockets functionality is still very much a work-in-progress

**Comment by robjtede** [comment]
It's true there are some gaps in spec complaince but I don't think it's fair to say the websocket functionality provided is in beta stage. Many actix users, myself included, are using websockets in production without problems.

**Comment by rustrust** [comment]
Oh, okay! Well that's good to know too!
