### ISSUE TITLE
Memory leak with Dispatcher on actix-web 2.0.0 and actix-http 1.0.1

### ISSUE THREAD

**Issue by adelbertc** [actix/actix-web#1574]
## Expected Behavior
Even after a large payload (e.g. ~500MB) is sent to the server, the memory usage of the server settles down to a stable amount.

## Current Behavior
After a series of large payloads being individually sent to the server, the memory usage seems to climb as a function of the payload size and only ever grows.

![Screen Shot 2020-06-20 at 2 53 05 PM](https://user-images.githubusercontent.com/1332980/85212252-e0720a80-b305-11ea-9cdc-4b8786c02cbd.png)

## Possible Solution
I traced this with the BPF/BCC [memleak](https://github.com/iovisor/bcc/blob/master/tools/memleak_example.txt) tool which tracks what track traces led to memory allocations which were never free'd and there was one line in particular that was suspicious:

```
1474560 bytes in 45 allocations from stack
actix_http::h1::dispatcher::Dispatcher$LT$T$C$S$C$B$C$X$C$U$GT$::new::he552b6f647883536+0xc0
```

This suggests [this function](https://github.com/actix/actix-web/blob/master/actix-http/src/h1/dispatcher.rs#L185-L206) is allocating memory which is never free'd, and the more suspicious thing there is the `BytesMut` or maybe the `codec`.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.41.0
* Actix Web Version: 2.0.0, actix-http 1.0.1

**Comment by robjtede** [comment]
Fixed in master by https://github.com/actix/actix-web/pull/1550

**Comment by adelbertc** [comment]
@robjtede Oops I realized I put the wrong values for the environment, but this is happening on an app that has the fixes in #1550 . In this case it seems it is not so much that the memory buffer is being resized too large but that whatever is allocating in `Dispatcher::new` is never being freed.

**Comment by robjtede** [comment]
Ok can you update the title and versions with what you're using and provide reproduction steps if you can.

We have a few other reports of memory leaks that might be related but havent found a great way to quantify yet. What OS are you on and how are you generating that graph?

**Comment by adelbertc** [comment]
Re-closing this for now 😅 After some more tracing we've turned our suspicions to reqwest and hyper.. sorry for the false alarm!

**Comment by kaushik-barodiya** [comment]
Hey @adelbertc what were the issues you found on  with request?
