### ISSUE TITLE
Timeout when proxying a large request

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#158]
Not sure how to solve this one.  We're proxying a large file upload to a backend service through actix-web, and it's hitting some implicit timer somewhere:

```
 ERROR actix_web::pipeline           > Error occured during request handling: Timeout out while waiting for response
```

The client is still uploading a file at this point, so it shouldn't be timing out as the connection is still streaming through

Using the following as the `proxy` implementation:

```
        let mut builder = client::ClientRequest::build();

        for (key, value) in req.headers() {
            if key != header::CONNECTION {
                builder.header(key.clone(), value.clone());
            }
        }

        builder
            .uri(&url)
            .method(req.method().clone())
            .body(Body::Streaming(Box::new(req.from_err())))
            .unwrap()
            .send()
            .from_err()
            .and_then(|resp| {
                let mut client_response = HttpResponse::build(resp.status());

                for (key, value) in resp.headers() {
                    if key != header::CONTENT_LENGTH {
                        client_response.header(key.clone(), value.clone());
                    }
                }

                client_response.body(Body::Streaming(Box::new(resp.from_err())))
                    .map_err(|e| e.into()) // HttpOk::build() mayb return HttpError, we need to convert it to a Error
            })
            .responder()
```

**Comment by fafhrd91** [comment]
I see the problem. this happens because actix uses 5 secs timeout for server response,
but you upload data, so response is not available for longer time. 

as a fast solution you can increase timeout for client request. 

```rust
     builder
            .uri(&url)
            .method(req.method().clone())
            .body(Body::Streaming(Box::new(req.from_err())))
            .unwrap()
            .send()
            .timeout(Duration::from_secs(600))
```

**Comment by cetra3** [comment]
Yeah, I would think that the timeout would only kick in after the body and request being sent has finished.  Otherwise, if you're uploading something on a super slow connection, you could get timeouts quite easily

I will bump up the timeout in the interim.

**Comment by fafhrd91** [comment]
I will change timeout behavior

**Comment by fafhrd91** [comment]
fixed in master

**Comment by rofrol** [comment]
Fixed in https://github.com/actix/actix-web/commit/eeae0ddab4ca8bee6a48946011350e889765be0e
