### ISSUE TITLE
Add private cookie sessions

### ISSUE THREAD

**Issue by adwhit** [actix/actix-web#159]
At the moment, cookie-based sessions are secure but not private. This means that the client is able to view the session data, but not alter it.

While this is usually good enough, it would be nice to enable private cookies (a feature which already exists in [cookie-rs](https://github.com/alexcrichton/cookie-rs)) so that the user can neither read nor alter session cookies.

**Comment by adwhit** [comment]
@fafhrd91 I would be happy to attempt a PR for this if you think it would be a useful feature

**Comment by fafhrd91** [comment]
Sure, PRs are always welcome!
