### ISSUE TITLE
Capture the remainder of the path?

### ISSUE THREAD

**Issue by roy-work** [actix/actix-web#1595]
## Expected Behavior

I'd like to do something like,

```
      web::resource("something/{remainder...}")
```

(The syntax is made up, as I believe this is a feature request.)

Where `{remainder...}` represents the remainder of the path.

## Current Behavior
Currently, `web::resource` can do something like `web::resource("/something/{segment}")`, but that only captures a single segment of the path, as opposed the rest. That is, it matches `/something/foo`, but not `/something/foo/bar`; I would like some means of matching both. (I want a handler to handle an entire subtree of the path.)

## Possible Solution
I think this would require some dedicated syntax in `PathDeserializer`, but that's as far as I've gotten.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.44.1 (c7087fe00 2020-06-17)
* Actix Web Version: 2.0.0

**Comment by robjtede** [comment]
There is a default regex applied to the resource patterns that stops at slashes. See the docs here: https://docs.rs/actix-web/2.0.0/actix_web/web/fn.resource.html.

Here's something that will do what you want.

```rust
#[get("/one/{path:[^{}]+}")]
async fn handler(path: web::Path<String>) -> io::Result<HttpResponse> {
    println!("{:?}", path);
    Ok(HttpResponse::Ok().finish())
}
```

Calling the path `/one/two/three` will print `two/three`.
