### ISSUE TITLE
json-rust

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#16]
Hello

I would like to use json-rust (light and fast https://github.com/serde-rs/json-benchmark) instead of serde_json. I found example #2 https://actix.github.io/actix-web/guide/qs_7. html#json-request ``you can manually load payload into memory and ther deserialize it. Here is simple example. ...``.

I copied/paste the code into the file the example actix-web-master/examples/json/src/main. rs and I have several errors:

I've fixed ``fn index (mut req: HttpRequest) -> Future<Item=HttpResponse, Error=Error=Error> {```` in ``fn index (mut req: HttpRequest) -> Box<Future<Item=HttpResponse, Error=Error>>>> {`` but then I have the error

```
error[E0599]: no method named `concat2` found for type `actix_web:: payload:: ReadAny` in the current scope
  src/main. rs: 29:32
   |
29 | req. payload_mut (). readany (). concat2 ()
   | ^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use' for it:
           candidate #1: `future:: Stream; `
```

Could you fix this example in the documentation and add an example that works in actix-web-master/examples/json/src/main. rs.

Sorry, I'm really a beginner
Thank you

**Comment by fafhrd91** [comment]
Why do you want to use streams directly? Actix already uses streams and serde, `req.json()` just convinience helper with extra checks

https://github.com/actix/actix-web/blob/master/src/json.rs#L50

To fix your compilation bug, just add `use futures::Stream` to your code

**Comment by AlbanMinassian** [comment]
Hello (and merry Christmas)

with json-rust:

1) I can use several useful functions (is_object, is_array... https://docs.rs/json/0.11.12/json/enum.JsonValue.html#method.is_object) that serde_json does not implement (or poorly documented)
2) transforming into structure is not useful in many cases (therefore less code)
3) faster than serde_json https://github.com/serde-rs/json-benchmark
4) easy for beginners like me
5) why not and for fun

Why do you want everyone to use serde_json? Why don't you implement a ``req. json_rust ()`` (json-rust) and ``req. json_serde ()``.

Ami44

**Comment by fafhrd91** [comment]
I see, your reasons are valid. I’ll add example.

`req.json()` just a convince, I am still playing with api.

**Comment by fafhrd91** [comment]
I updated guide and example.

would you provide PR for `json-rust` crate integration?

**Comment by AlbanMinassian** [comment]
Thank you. I have been discovering rust for 2 weeks and I don't have the level to propose a PR

**Comment by AlbanMinassian** [comment]
but I proposed a PR https://github.com/flosse/rust-web-framework-comparison/pull/36 to improve the visibility of actix-web :-)

**Comment by fafhrd91** [comment]
thanks.

btw adding json-rust is easy task, it should be mostly copy from exiting JsonBody implementation

**Comment by fafhrd91** [comment]
Could you update your PR and include `yes` for sessions. Actix has sessions now

**Comment by AlbanMinassian** [comment]
Done
