### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by attila-lin** [actix/actix-web#1606]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

The memory usage should be stable.

## Current Behavior

The memory usage keeps growing.

![image](https://user-images.githubusercontent.com/3176481/87501584-ffa85180-c691-11ea-84df-c7c9dfe7b4b2.png)

the red one is using actix-web 3.0.0-alpha.3, the yellow one is actix-web 3.0.0-beta.1

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

Sorry for cant provide a minimal reproduction.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.46.0-nightly (16957bd4d 2020-06-30)
* Actix Web Version: 3.0.0-beta.1

**Comment by robjtede** [comment]
It's very difficult for us to investigate reports of memory leaks without any sort of example.

At the very least, we need much more information about what code paths to check: OS, system or custom allocator, HTTP 1 or 2, TLS (and which one) or not, middleware used, other notable features used, other crates used, how many req/s does this server deal with?

Even better if you're not able to provide the code would be if you are able to profile the allocations yourself.

**Comment by morphy2k** [comment]
This could be the same memory issue that I casually mentioned in #1607 yesterday.

I've just made 100,000,000 requests with 200 concurrent connections against the root endpoint in [my example](https://github.com/morphy2k/actix-web-issue). The memory consumption was less than 500KB at the beginning, after the benchmark was finished it was almost 800MB.

I'm still a Rust newbie, but if I can help in any way, for example further testing, let me know.
