### ISSUE TITLE
Falling throughput when extracting path information

### ISSUE THREAD

**Issue by morphy2k** [actix/actix-web#1607]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior
Throughput should be constant.

## Current Behavior
Throughput drops with the number of requests.

## Possible Solution
...

## Steps to Reproduce (for bugs)
**[Link to example](https://github.com/morphy2k/actix-web-issue)**

1. Build and start the server
2. Benchmark the root endpoint where no path information is extracted
3. Benchmark the ID endpoint where path information is extracted
4. Compare the results

## Context
I noticed the issue while developing a search backend.
As soon as I extract path or query information, the throughput drops continuously during benchmarking.
In addition, regardless of whether I extract information, I noticed that the memory consumption is continuously increasing, which could indicate a memory leak.

## Your Environment
- **CPU** Ryzen 5 2600
- **RAM** 16GB DDR4-3200
- **OS** Fedora 32 Workstation (5.7.8-200.fc32.x86_64)

* Rust Version (I.e, output of `rustc -V`): rustc 1.44.1 (c7087fe00 2020-06-17)
* Actix Web Version: 3.0.0-beta.1

**Comment by fakeshadow** [comment]
I believe this line is the cause of your problem. 
https://github.com/actix/actix-web/blob/2fd96c03e5a2d93671412252d864859e5de1b345/src/app_service.rs#L248

Commenting it and your example runs OK for me. It would be good if someone can look into it and see if it's ok to remove it.

**Comment by robjtede** [comment]
for context: https://github.com/actix/actix-web/pull/1486#discussion_r419165842

**Comment by fakeshadow** [comment]
Or maybe we can clear the `data` pushed to `HttpRequest` when dropping it too(If it returns to pool). 
I'm not familiar with how cached pool works so I could be wrong but it seems in certain cases we just keep push data and the vec become too long.
Well actually if a request is already in cache do we really need to push data again?

**Comment by morphy2k** [comment]
Can confirm that this causes the problem, as well as the high memory consumption #1606 
As soon as I comment out the line, the memory consumption and throughput remains constant.
