### ISSUE TITLE
Failed to compile example from guide: unresolved import `actix_web::App`

### ISSUE THREAD

**Issue by davechallis** [actix/actix-web#161]
The example in the guide at https://actix.github.io/actix-web/guide/qs_2.html doesn't compile against the version of actix-web specified on that page (`actix-web = "0.4"`), failing with:

```
error[E0432]: unresolved import `actix_web::App`
 --> src/main.rs:2:17
  |
2 | use actix_web::{App, HttpRequest, HttpResponse, HttpServer};
  |                 ^^^ no `App` in the root
```

It looks like `App` is going to be in version 0.5 though, so I expect this error will go away once the guide is updated for 0.5 (but if that release is a long way off, could be helpful to newcomers to fix the guide).

**Comment by fafhrd91** [comment]
Guide is upgraded to 0.5 already. I will release 0.5 in couple days

**Comment by davechallis** [comment]
Fantastic, looking forward to it.
