### ISSUE TITLE
customization of NormalizePath behavior

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1612]
excerpt from #959 

> I think had hoped that NormalizePath might let you create a route like /hello and accept either /hello or /hello/ I suppose this can also be achieved via route matching (e.g. #[get(r#"/hello{tail:/?}"#)]) (as an aside: I also wonder if users would prefer to accept both distinct routes or have one version 301 redirect to the other?).
>
> When I tried to check v3 beta, seems like my usage of NormalizePath did not work for me? Not sure if I have something mixed up here, but wasn't able to access either /hello or /hello/.

So, middleware should take option `TrailingSlash::{Always, Trim}` and possibly an option to 301 redirect to the normalized path.

**Comment by l-2-j** [comment]
I'd be interested to get something like this added. I made a small [branch to test it on](https://github.com/ljoonal/actix-web/blob/trailing-slash-normalization/src/middleware/normalize.rs) even. But I by no means thought a ton about the implementation, so it'd probably be good for someone to see if I missed something obvious :sweat_smile:

**Comment by robjtede** [comment]
@ljoonal looks like a good start. feel free to open a draft PR to get the implementation discussion going.
