### ISSUE TITLE
HttpServer with multiple un-prefixed Apps

### ISSUE THREAD

**Issue by adwhit** [actix/actix-web#162]
`HttpServer` can be provided with multilple `App`s like so:
```rust
let app1 = App::new()...
let app2 = App::new()...
let server = HttpServer::new(|| vec![app1, app2])
```
This works great when the apps have different prefixes, but if they have the same prefix then the server 'works' but the second app will not respond to any request. I think if two or more apps are provided with the same prefix, either `actix-web` should error at startup, or the routes should 'just work' as expected.

**Comment by fafhrd91** [comment]
with current design, both options are not possible. I don't think this needs to be fixed as you can get similar problem with resources. also this problem is covered in [user guide](https://actix.github.io/actix-web/guide/qs_3.html#application)

**Comment by adwhit** [comment]
OK, fair enough!
