### ISSUE TITLE
Memory leak with awc::Client

### ISSUE THREAD

**Issue by ajsyp** [actix/actix-web#1622]
It appears that creating multiple `awc::Client` instances results in a memory leak, even once the `Client` objects leave scope. The documentation rightfully points out that a `Client` should be reused rather than created on a per-request basis, but even so we should expect no memory leaks.

It does not appear that the recent PR (#1580) addresses this leak.

##  Expected Behavior

Memory associated with a `Client` is released after the client (and its associated requests) are complete.

## Current Behavior

Instantiating multiple clients in a loop results in excessive and unbounded memory usage.

## Steps to Reproduce (for bugs)

Here is a simple `awc-mem-leak` application.

`Cargo.toml`:
```
[dependencies]
actix-rt = "1.1.1"
awc = { version = "2.0.0-beta.2", features = ["compress"] }
```

`main.rs`:
```
// Change this to target an example HTTP server.
const URL: &str = "http://localhost:8000";

#[actix_rt::main]
async fn main() {
    let mut i = 0;
    loop {
        i += 1;
        if let Err(_) = awc::Client::build().finish().get(URL).send().await {
            eprintln!("{}: error", i);
        } else {
            eprintln!("{}: ok", i);
        }
    }
}
```

**Usage**: Stand up a local HTTP server (e.g., `python3 -m http.server`), adjust `URL` above, and run: `cargo run --release`. Memory will increase unboundedly.

Running this client application with valgrind & massif makes the memory leak very clear.

1. Build the binary: `cargo build --release`
2. Profile it: `valgrind --tool=massif target/release/awc-mem-leak`
3. After a couple minutes, Ctrl+C the process. This will produce a `massif.out.PID` file.
4. Visualize: `massif-visualizer massif.out.PID`

**Heap usage**. After running for 5 minutes (about 31k iterations of the above loop), Massif shows:

![image](https://user-images.githubusercontent.com/7648333/88844485-b9361500-d1b0-11ea-92f5-d24cdc1c389a.png)

The original Massif capture is [here](https://gist.github.com/ajsyp/12fcaaaabcab65cc7060e22e5d60eddd).

## Environment:
```
OS: ArchLinux (x86_64)
cargo 1.45.0 (744bd1fbb 2020-06-15
rustc 1.45.0 (5c1f21c3b 2020-07-13)
```

**Comment by fakeshadow** [comment]
Add code below to [this line](https://github.com/actix/actix-web/blob/cf1c8abe62d1d94e86c6a62ff8aa9fd6f23bc88a/actix-http/src/client/pool.rs#L482) and your example would stop leaking on my machine.

```rust
if Rc::strong_count(&this_inner) == 3 {
      return Poll::Ready(());
}

```

Don't have time to look into the pool's future so I'm not sure where the leak happen.

**Comment by fakeshadow** [comment]
Ok. After some investigation I think the problem is the pool support future would not wake up anymore when we build a client and destroy it quickly. So I think adding this would solve the leaking issue.

```rust
impl<T, Io> Drop for ConnectionPool<T, Io>
    where
        Io: 'static,
{
    fn drop(&mut self) {
        // wake up the support future when the ConnectionPool is dropped.
        self.1.borrow().waker.wake();
    }
}
```

Beyond this I think it's better we just pass `Rc` instead of `Weak` to the support future. I believe the cause of the pool's leak is not circular reference of `Rc` in the code but not properly wake up futures which result them hang in executor forever.

```rust
#[pin_project]
struct ConnectorPoolSupport<T, Io>
where
    Io: AsyncRead + AsyncWrite + Unpin + 'static,
{
    connector: T,
    // go back to use Rc instead of Weak.
    inner: Rc<RefCell<Inner<Io>>>,
}

impl<T, Io> Future for ConnectorPoolSupport<T, Io>
where
    Io: AsyncRead + AsyncWrite + Unpin + 'static,
    T: Service<Request = Connect, Response = (Io, Protocol), Error = ConnectError>,
    T::Future: 'static,
{
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {

        let this = self.project();

        if Rc::strong_count(this.inner) == 1 {
            // If we are the last copy of Rc it means we are safe to resolve this future.
            return Poll::Ready(());
        }
        ...  unchanged ...
   }
}
```

I'd like to hear some suggestion if we should go back to use `Rc`.
