### ISSUE TITLE
Please update dependency to allow arm platform building

### ISSUE THREAD

**Issue by iav** [actix/actix-web#1623]
Currently there are dependency
```
cargo-tree tree -i -p v_escape:0.12.0
v_escape v0.12.0
└── v_htmlescape v0.10.0
    └── actix-files v0.3.0-beta.1
```
`v_escape v0.12.0` can't be build on non-x86 platforms.
It was fixed in `v_escape v0.12.1`.
Please, pull dependency version to allow link `v_escape v0.12.1`

**Comment by dessalines** [comment]
Can confirm that this is preventing lemmy from being able to be built on arm.

**Comment by vpzomtrrfrt** [comment]
I don't think that is an issue here, this repo has no lockfiles

**Comment by JohnTitor** [comment]
Note that we don't depend on `v_escape` directly, you should file this issue to `v_htmlescape` instead if you want to ensure it. And you can resolve it with `cargo update` anyway as these crates are libraries and you should have your own lockfile.
Closing as wontfix.

**Comment by dessalines** [comment]
Ah my bad, I didn't realize this built without a lock file. I'll run an update.
