### ISSUE TITLE
V3 Not Found

### ISSUE THREAD

**Issue by JimLynchCodes** [actix/actix-web#1627]
When I scaffold a new cargo project:
```
cargo new hello-kitten
```

Then I add in cargo.toml the line for actix-web v3, copy the "hello world" code, and run `cargo run`, but I get this error:

```
error: failed to select a version for the requirement `actix-web = "^3"`
  candidate versions found which didn't match: 2.0.0, 1.0.9, 1.0.8, ...
  location searched: crates.io index
```

**Comment by attila-lin** [comment]
Not released yet. use beta version instead.
```toml
actix-web = "3.0.0-beta.1"
```

**Comment by JohnTitor** [comment]
Yeah, we don't release any stable v3 yet.
