### ISSUE TITLE
Actix-web JsonConfig error_handler not working

### ISSUE THREAD

**Issue by steelx** [actix/actix-web#1628]
I have this below code, everything works expect the error_handler. Im not sure whats wrong. If I make post request with correct format I get 200 with response data. But on bad request I'm expecting 400 with Json data which is not receiving. It just says 400, but doesnt return any error json data.

## Expected Behavior
BAD REQ -> curl -X POST -H "Content-Type: application/json" -d '{"bad": "Someone was here"}' localhost:8080/send
```
status 400
{
    error: String,
    server_id: usize,
    request_count: usize,
}
```

## Current Behavior
BAD REQ -> curl -X POST -H "Content-Type: application/json" -d '{"bad": "Someone was here"}' localhost:8080/send
status 400

## Possible Solution
I replaced `.data` with `.app_data` it works, but then it not able to find `AppState`

# CODE
```rust
    pub struct MessageApp {
        pub port: u16,
    }

    impl MessageApp {
        pub fn new(port: u16) -> Self {
            Self{port}
        }

        pub async fn run(&self) -> std::io::Result<()> {
            let messages = Arc::new(Mutex::new(vec![]));
            println!("Starting http server: 127.0.0.1:{}", self.port);

            HttpServer::new(move || {
                App::new()
                    .data(AppState {
                        server_id: SERVER_COUNTER.fetch_add(1, Ordering::SeqCst),
                        request_count: Cell::new(0),
                        messages: messages.clone(),
                    })
                    .wrap(middleware::Logger::new(LOG_FORMAT))
                    .service(index)
                    .service(
                        web::resource("/send")
                        .data(
                            web::JsonConfig::default()
                                .limit(4096)
                                .error_handler(post_error)
                        )
                        .route(web::post().to(post))
                    )
                    .service(clear)
            })
            .bind(("127.0.0.1", self.port))?
            .workers(8)
            .run()
            .await
        }
    }
```
**error handler**
```rust
    fn post_error(err: JsonPayloadError, req: &HttpRequest) -> Error {
        let extns = req.extensions();
        let state = extns.get::<web::Data<AppState>>().unwrap();
        let request_count = state.request_count.get() + 1;
        state.request_count.set(request_count);

      let post_error = PostError {
          server_id: state.server_id,
          request_count,
          error: format!("{}", err),
      };

      InternalError::from_response(err, HttpResponse::BadRequest().json(post_error)).into()
    }
```

## Context
I'm just trying to learn Actix

## Your Environment
Pop OS 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.45.2 (d3fb005a3 2020-07-31)
* Actix Web Version: 2.0.0

**Comment by robjtede** [comment]
The JsonConfig should be in `.app_data()` and your AppState should be in `.data()`. However, there is a known limitation with version 2 that will prevent this setup from working at all. Either place JsonConfig at same level as AppState or try the actix-web v3 beta.

**Comment by steelx** [comment]
@robjtede Thanks for commenting. But doing that I get error 
`note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt:worker:7' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:134:17`

also mentioned here https://actix.rs/actix-web/actix_web/web/struct.JsonConfig.html (but this gets an error)
which is at this line -> 
```
    let extns = req.extensions();
    let state = extns.get::<web::Data<AppState>>().unwrap();//134
```

**Comment by steelx** [comment]
@robjtede Im quite not sure about how to do this:

   > Either place JsonConfig at same level as AppState

**Comment by robjtede** [comment]
@steelx 

> Im quite not sure about how to do this:

```rust
App::new()
	.app_data(JsonConfig ...)
	.data(AppState { ... })
```

**Comment by steelx** [comment]
> @steelx
> 
> > Im quite not sure about how to do this:
> 
> ```rust
> App::new()
> 	.app_data(JsonConfig ...)
> 	.data(AppState { ... })
> ```

@robjtede 
I updated my code as below, moving `app_data` out
```

HttpServer::new(move || {
            App::new()
                .app_data(
                    web::JsonConfig::default().limit(4096).error_handler(post_error)
                )
                .data(AppState {
                    server_id: SERVER_COUNTER.fetch_add(1, Ordering::SeqCst),
                    request_count: Cell::new(0),
                    messages: messages.clone(),
                })
                .wrap(middleware::Logger::new(LOG_FORMAT))
                .service(index)
                .service(post)
        })
        .bind(("127.0.0.1", self.port))?
        .workers(8)
        .run()
        .await
```

still same error with this approach. Its not able to find AppState. If I remove finding AppState from extentions it works fine.
`thread 'actix-rt:worker:3' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:134:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by robjtede** [comment]
Extensions is for request-local data, for application data, use `HttpRequest::app_data`

```rust
let state = req.app_data::<web::Data<AppState>>().unwrap();
```

**Comment by steelx** [comment]
> Extensions is for request-local data, for application data, use `HttpRequest::app_data`
> 
> ```rust
> let state = req.app_data::<web::Data<AppState>>().unwrap();
> ```

thank you so much works fine now :+1: 

Also, I would like to ask is this a correct way of error_handling ?? Which Im doing ?

**Comment by robjtede** [comment]
It's correct if it has the behaviour you want. We provide a bunch of ways to handle errors. `Option<T>` and `Result<T, E>` extractors, error handler middleware and the way you're using here. Myself and other are available to talk in [Gitter](https://gitter.im/actix/actix-web) about strategies if you have more questions :)

**Comment by steelx** [comment]
> Extensions is for request-local data, for application data, use `HttpRequest::app_data`
> 
> ```rust
> let state = req.app_data::<web::Data<AppState>>().unwrap();
> ```

this works now with the limiting as well.
```rust
.service(
                    web::resource("/send")
                    .app_data(
                        web::JsonConfig::default().limit(4096).error_handler(post_error)
                    )
                    .route(web::post().to(post))
                )
```
