### ISSUE TITLE
NormalizePath is always adding trailing slash

### ISSUE THREAD

**Issue by Lesiuk** [actix/actix-web#1632]
## Code
```rust
use actix_web::{get, middleware, web, App, HttpServer, Responder};

#[get("/{id}/{name}/index.html")]
async fn index(path: web::Path<(u32, String)>) -> impl Responder {
    format!("Hello {}! id:{}", path.1, path.0)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(index)
            .wrap(middleware::NormalizePath::default())
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

## Steps to Reproduce (for bugs)
1. Execute `curl -i http://localhost:8080/20/smith/index.html`

## Expected Behavior
HTTP/1.1 200 OK

## Current Behavior
HTTP/1.1 404 Not Found

## Context
I expect that all of the already working urls should also work after path normalization.

## Your Environment
* Actix Web Version: 3.0.0-beta.1

**Comment by robjtede** [comment]
When using NormalizePath *all* your route defs must end with a trailing slash.

In your case:

```rust
#[get("/{id}/{name}/index.html/")]
async fn index() { ... }
```

**Comment by Lesiuk** [comment]
Yeah. I noticed it. But maybe we should make NormalizePath a little smarter. We can close it in favor of https://github.com/actix/actix-web/issues/1612
