### ISSUE TITLE
closing a websocket request always results in a http 500 error

### ISSUE THREAD

**Issue by BartWillems** [actix/actix-web#1633]
## Expected Behavior

A user tries to open a websocket connection, but lacks permissions, so a 403 is responded.

## Current Behavior

In my code I respond with 403 forbidden, but a 500 is sent out.

## Steps to Reproduce (for bugs)

Code example from my repo:

https://github.com/BartWillems/rustfuif/blob/8094f455599d23c847744062d802c25917af2bdd/src/websocket/transactions.rs#L20

``` rust
pub async fn route(
    req: HttpRequest,
    stream: web::Payload,
    srv: Data<Addr<server::TransactionServer>>,
    game_id: Path<i64>,
    id: Identity,
    pool: Data<db::Pool>,
) -> Result<HttpResponse, Error> {
    let user = auth::get_user(&id)?;

    let game_id = *game_id;

    web::block(move || {
        let conn = pool.get()?;
        if !Game::verify_user(game_id, user.id, &conn)? {
            // This macro simply returns a 403 http response with a message
            // This is also where it goes wrong
            forbidden!("you are not in this game");
        }
        Ok(())
    })
    .await?;

    ws::start(
        SalesUpdates {
            id: 0,
            hb: Instant::now(),
            game_id,
            addr: srv.get_ref().clone(),
        },
        &req,
        stream,
    )
}
```

## Context

This currently causes incorrect errors to be presented to users.

According to the first yellow tip banner on this page, it should be possible to respond with 403: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Client_handshake_request

## Your Environment

Linux, latest stable rust, latest stable Actix versions

* Rust Version (I.e, output of `rustc -V`): `rustc 1.45.2 (d3fb005a3 2020-07-31)`
* Actix Web Version: `2.0.0`

**Comment by robjtede** [comment]
This is expected since web::block returns a wrapped error who's ResponseError impl returns the 500.

You'll need to use an if let on the result or map_err before the ? operator.
