### ISSUE TITLE
resource multi-patterns act as prefixes by default

### ISSUE THREAD

**Issue by shujaatak** [actix/actix-web#1647]
I am playing with actix-web = "3.0.0-beta.3", my code looks like this:

```RUST
use actix_web::{web, App, HttpResponse, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| 
        App::new()
            .service(web::resource(vec!["/request", "/an_another_request"]).to(|| async {
                "Hello!"
            }))
            .default_service(web::route().to(|| HttpResponse::NotFound()))
        )
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```
I was expecting that my server would reply me `Hello!` when browsing this http://127.0.0.1:8080/request or this http://127.0.0.1:8080/an_another_request else returning me `NotFound` response. While testing, I found that my server correctly replied me with `Hello!` message while browsing either  http://127.0.0.1:8080/request or this http://127.0.0.1:8080/an_another_request **but** I accidentally browsed this http://127.0.0.1:8080/request_an_another_request to which my server responded with the same message` Hello!` then I browsed http://127.0.0.1:8080/request/bla/bla/bla which also responded with the same message while I was expecting `NotFound` response from the server.

**Comment by shujaatak** [comment]
actix-web considers "request", "requesttt", "requestttttabcdefg...", request/../../ as equal although they are not.

I think, Actix-web just match the initial characters equal to the length of the path given by the developer in the service().

**Comment by robjtede** [comment]
My feeling is that it is _intended_ behaviour but it certainly is unintutive given the single pattern resource defs do not act like this.

When using a multi-pattern like this, each pattern is treated as a Regex string. For example, the following has the behavior you'd expect:

```rust
vec!["/request$", "/an_another_request$"]
```

Alternatively, use two single pattern defs pointing to the same function.

**Comment by shujaatak** [comment]
I wonder why resource multi-patterns are set to be prefixes by default even though I'm happy with them.

**Comment by Silentdoer** [comment]
i think this is not a necessary feature

**Comment by robjtede** [comment]
> i think this is not a necessary feature

@Silentdoer what do you mean exactly?

**Comment by shujaatak** [comment]
Pattern as a Regex string **is very useful feature** and somewhat necessary feature but being set as prefixes by default is neither intuitive nor feeling a good idea.
