### ISSUE TITLE
Flagged by Rust-San: Possible Memory Leak in actix-http?

### ISSUE THREAD

**Issue by YoshikiTakashima** [actix/actix-web#1648]
Hello.

To the best of my knowledge, this is unreported. However, I don't have time to read 88 issues, so please feel free to close it if you think it is a duplicate.

## Expected Behavior
No memory leak warnings should be given off by [rust-san](https://github.com/japaric/rust-san)

## Current Behavior
Running some code or test case with Request results in memory leak warnings emitted from rust-san.

Example: automatically minimized version of `header::common::accept::test_accept::test_fuzzing1`
```
use crate::test::TestRequest;

fn test() {
 let x1_0: TestRequest = TestRequest::with_header(crate::header::ACCEPT, "chunk#;e");//LAYER:0
 let mut x2_0: TestRequest = x1_0;//LAYER:1
 let x3_0: &mut TestRequest = &mut x2_0;//LAYER:2
 let x4_0: actix_web::dev::Request = x3_0.finish();//LAYER:3
 return;
}
```

Leaks with the following output:
```
==25091==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x5640fdd8536d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5640fe3b4875 in std::sys::unix::alloc::_$LT$impl$u20$core..alloc..global..GlobalAlloc$u20$for$u20$std..alloc..System$GT$::alloc::h5c6f1ed480be2f17 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/unix/alloc.rs:14:13
    #2 0x5640fe3f1ff5 in __rdl_alloc /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/alloc.rs:304:9
    #3 0x5640fe130a2e in alloc::alloc::alloc::hdbf753b11eb8ebb6 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/alloc.rs:80:14
    #4 0x5640fe131c9b in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..AllocRef$GT$::alloc::haaff6f4f7779c654 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/alloc.rs:174:49
    #5 0x5640fe1426da in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h229235c89fb1b8d1 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:183:32
    #6 0x5640fe1463a0 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h86f3e87ca6524ab0 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:159:9
    #7 0x5640fe151715 in actix_http::message::REQUEST_POOL::__init::h2716201452841522 /home/ytakashima/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.0.0-beta.3/src/message.rs:430:72
    #8 0x5640fe151a11 in std::thread::local::fast::Key$LT$T$GT$::try_initialize::h288892500414c647 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:425:22
    #9 0x5640fe151ef2 in std::thread::local::fast::Key$LT$T$GT$::get::h06ac742968e54975 /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:410:25
    #10 0x5640fe15173c in actix_http::message::REQUEST_POOL::__getit::h587119af2ea3156c /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:175:17
    #11 0x5640fe12e6ae in std::thread::local::LocalKey$LT$T$GT$::with::hed78f2a44e85f74b /home/ytakashima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239:9
    #12 0x5640fdda6656 in root::TestRequest::finish::hb4d0834a63f5bcac /home/ytakashima/Desktop/share/rust-bugs/actix-web/actix-web-testcase/src/main.rs:165:13
    #13 0x5640fdda4f99 in root::test::h8797aaa451b4e9e1 /home/ytakashima/Desktop/share/rust-bugs/actix-web/actix-web-testcase/src/main.rs:25:38
    #14 0x5640fdda537a in root::main::hf50ae5c2c1dee681 /home/ytakashima/Desktop/share/rust-bugs/actix-web/actix-web-testcase/src/main.rs:33:3
    #15 0x5640fdda87b5 in root::tests::test_fun::h804618109df1f41e /home/ytakashima/Desktop/share/rust-bugs/actix-web/actix-web-testcase/src/main.rs:46:9

#...a bunch more traces

SUMMARY: AddressSanitizer: 1520 byte(s) leaked in 5 allocation(s).
error: test failed, to rerun pass '--bin root'
```
## Possible Solution
Sorry, no idea. Looking at the trace, it looks like the leak comes from request pool. There are also other leaks, many of which are not from request pool I know there has been recent memory leak fixes (say #1626) in other areas of the code, so maybe there are more leaks. Since this is an indirect leak, I suspect fixing other direct leaks will fix this one.

## Steps to Reproduce (for bugs)
Option 1: extremely easy.
1. download [this tarball](https://github.com/actix/actix-web/files/5138447/actix-web-leak.tar.gz) contains the a synthesized minimal test case.
2. Inside the unzipped directory, run `RUSTFLAGS=-Zsanitizer=address  RUSTDOCFLAGS=-Zsanitizer=address cargo test -Zbuild-std --target x86_64-unknown-linux-gnu`
5. The above leak is flagged.

Option 2: slightly less easy
1. Clone `actix-web`
2. delete `actix-web/rust-toolchain` so you can use -Z options.
3. go to actix-http.
4. run `RUSTFLAGS=-Zsanitizer=address  RUSTDOCFLAGS=-Zsanitizer=address cargo test -Zbuild-std --target x86_64-unknown-linux-gnu header::common::accept::test_accept::test_fuzzing1`
5. Same leak is flagged.

## Context
I'm a grad student testing a bug-finding tool for Rust. I just happened to test your library because it fit my evaluation criteria. I don't use Actix very often, but from the code, I suspect this is used to process http requests. Thus, memory leak makes it a DoS threat, albeit a fairly minimal one.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.46.0-nightly (2753fab7c 2020-07-05)
I understand you are not using nightly by default, but analysis tools like rust-san will not work unless -Z is enabled via nightly.
* Actix Web Version: Hash 75d86a6bebe2829f8e4bc3f54945b08073fb1710

**Comment by robjtede** [comment]
Firstly, thanks for opening an issue on this; always good to have folks looking at the code.

This will need more investigation to determine whether a "leak" really exists. I can image that the method we use to do request pools would appear as a leak to ~the ASAN~ an address sanitizer in a single test but as far as we know its controlled and bounded.

**Comment by YoshikiTakashima** [comment]
Hi @robjtede.

Thank you for the quick response.

I'll try the same technique as #1622 and see if I can generate a similar memory curve.

**Comment by YoshikiTakashima** [comment]
Also, I am not too familiar with actix internals. If the flag is a false positive, what is the behavior that gets flagged by ASAN?

**Comment by YoshikiTakashima** [comment]
Hmmm. After looping the snippet code for 15 minutes, it looks okay. It even goes down.

I will close this, but if you don't mind, please let me know what makes Actix so hard for ASAN.
```
$ ms_print massif.out.PID

    KB
5.008^#
     |#
     |#
     |#
     |#
     |#
     |#
     |#
     |#
     |#
     |#
     |#      ::::@@::::@@::::::
     |#      : : @ : : @ : : ::  :  :  @  :  :  : ::
     |#::::::: : @ : : @ : : :::::@@:::@::::::::::: ::::@@::::::::@::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
     |#: ::::: : @ : : @ : : ::: :@ :: @: :: :: ::: : : @ : : : : @::::@::::@:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   508.7
```

**Comment by robjtede** [comment]
I'm not sure exactly but my mind immediately shifts to the `Box::leak` calls within request pool implementations:
- https://github.com/actix/actix-web/blob/751253f23e54b4eae6665b858430d9c1fc79b8d7/actix-http/src/message.rs#L436
- https://github.com/actix/actix-web/blob/971ba3eee14b4191ccddd6ddae0a5c135ae789e9/src/request.rs#L360

Which is an optimisation to avoid re-allocating HttpRequest objects unnecessarily.

On the client side, there are some methods of keeping connections alive for performance reasons.

**Comment by baoyachi** [comment]
Is there any new progress，fix memory leak ?
