### ISSUE TITLE
Tests are somehow broken with actix-web 3.0.0-beta.3 (was fine in 3.0.0-alpha.3)

### ISSUE THREAD

**Issue by igor-raits** [actix/actix-web#1651]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Current Behavior

```rust
error[E0433]: failed to resolve: use of undeclared type or module `env_logger`
  --> examples/uds.rs:26:5
   |
26 |     env_logger::init();
   |     ^^^^^^^^^^ use of undeclared type or module `env_logger`
error[E0433]: failed to resolve: use of undeclared type or module `env_logger`
  --> examples/basic.rs:22:5
   |
22 |     env_logger::init();
   |     ^^^^^^^^^^ use of undeclared type or module `env_logger`
error[E0433]: failed to resolve: use of undeclared type or module `brotli2`
  --> tests/test_server.rs:10:5
   |
10 | use brotli2::write::{BrotliDecoder, BrotliEncoder};
   |     ^^^^^^^ use of undeclared type or module `brotli2`
error[E0433]: failed to resolve: use of undeclared type or module `flate2`
  --> tests/test_server.rs:12:5
   |
12 | use flate2::read::GzDecoder;
   |     ^^^^^^ use of undeclared type or module `flate2`
error[E0433]: failed to resolve: use of undeclared type or module `flate2`
  --> tests/test_server.rs:13:5
   |
13 | use flate2::write::{GzEncoder, ZlibDecoder, ZlibEncoder};
   |     ^^^^^^ use of undeclared type or module `flate2`
error[E0433]: failed to resolve: use of undeclared type or module `rand`
  --> tests/test_server.rs:16:5
   |
16 | use rand::{distributions::Alphanumeric, Rng};
   |     ^^^^ use of undeclared type or module `rand`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
error[E0432]: unresolved import `flate2`
  --> tests/test_server.rs:14:5
   |
14 | use flate2::Compression;
   |     ^^^^^^ use of undeclared type or module `flate2`
error[E0432]: unresolved import `rand`
  --> tests/test_server.rs:16:5
   |
16 | use rand::{distributions::Alphanumeric, Rng};
   |     ^^^^ use of undeclared type or module `rand`
error: could not compile `actix-web`.
```

and more. See https://kojipkgs.fedoraproject.org//work/tasks/160/50370160/build.log (note that it is not there forever).

## Steps to Reproduce (for bugs)

1. Get tarball of actix-web 3.0.0-beta3 from crates.io
2. Unpack, cd
3. Run `cargo test` (I did not have time yet to investigate, but it might happen that `-Zavoid-dev-deps` is needed, it often uncovers missing dependencies that are just brought by some dev dependencies or like that.)

## Context

When packaging crates in Fedora we get archive from crates.io so crates like actix-web that have huge number of interconnected packages tend to be problematic to run tests.

## Your Environment

Fedora Rawhide.

* Rust Version (I.e, output of `rustc -V`): 1.46
* Actix Web Version: 3.0.0-beta.3

**Comment by robjtede** [comment]
the avoid-dev-deps theory sounds plausible since all the crates mentioned in the log are dev dependencies used only for tests

**Comment by robjtede** [comment]
With v3 out, what's the status of this?

**Comment by robjtede** [comment]
going to close, feel free to open another issue if there's something we can do to help
