### ISSUE TITLE
Getting mutable state reference when using HttpRequest::json()?

### ISSUE THREAD

**Issue by spease** [actix/actix-web#166]
```
    req.json()                   // <- get JsonBody future
       .from_err()
       .and_then(|val: MyObj| {  // <- deserialized value
           println!("==== BODY ==== {:?}", val);
           Ok(httpcodes::HttpOk.into())
       }).responder()
```

The problem:
I have state which is retrieved with req.state() that depends on the value of the serialized JSON. However, json consumes the request object. If I gain a mutable reference before calling json(), it prevents json(). If I try to gain a mutable reference during or after json(), the object has already been consumed.

**Comment by fafhrd91** [comment]
you can clone request `req.clone().json()`

in master you can use `State` and `Json` extractors
https://actix.github.io/actix-web/actix_web/struct.State.html

**Comment by spease** [comment]
Doh, thanks, that was a really fast response and obvious in hindsight. :)

**Comment by fafhrd91** [comment]
np
