### ISSUE TITLE
Expose `max_age` for `CookieSessionBackendBuilder`

### ISSUE THREAD

**Issue by brandur** [actix/actix-web#167]
Currently, cookies created with `actix-web`'s built-in middleware have an invalid expiry date showing up in the distant past:

![image](https://user-images.githubusercontent.com/96890/38469249-58e1dc0e-3b06-11e8-86a2-924dda76176a.png)

This should be fixed by exposing a `max_age` option for `CookieSessionBackendBuilder`. [`set_max_age`](https://docs.rs/cookie/0.10.1/cookie/struct.Cookie.html#method.set_max_age) is exposed by the underlying `cookie` Crate, so this should be fairly easy to do.

BTW, @fafhrd91 any thoughts on getting a `rustfmt.toml` in place? I was going to just contribute this feature myself, but after running into some pretty nasty diffs caused by `rustfmt` save hooks activating automatically, I just opened this issue instead :)

**Comment by fafhrd91** [comment]
added https://github.com/actix/actix-web/blob/master/src/middleware/session.rs#L395

should we set default `max_age`?

i am planing to add rustfmt, i dont like how it work, so i will need to tune it

**Comment by brandur** [comment]
> added https://github.com/actix/actix-web/blob/master/src/middleware/session.rs#L395

Awesome, thank you!

> should we set default max_age?

I'd actually lean toward "no" I think — if you don't send an expiry back with `Set-Cookie`, the browser should persist it for the duration of the browser session, which seems like a sane default. We could add more documentation indicating that to make a cookie really persistent, `max_age` will need to be set.

> i am planing to add rustfmt, i dont like how it work, so i will need to tune it

Ah, k. I'm not sure if you tried it recently, but I'm finding the defaults these days *much* better. I ended up with just a few exceptions in my project:

``` toml
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
struct_field_align_threshold = 20
wrap_comments = true
```

(And it makes coding so easy!) The only trouble is that some of those are still considered experimental and need a nightly build. I work around this by having my CI setup to only check `rustfmt` in the nightly build.

**Comment by fafhrd91** [comment]
Added rustfmt.toml

**Comment by brandur** [comment]
@fafhrd91 YES! This is amazing. Thanks.
