### ISSUE TITLE
Missing v3 migration note on req.app_data::<T>() ?

### ISSUE THREAD

**Issue by staninprague** [actix/actix-web#1680]
Thank you for version 3!

After migration I noticed that for my app data of type ServerData that I used to retrieve in middleware as:

```
let app_data = req.app_data::<ServerData>();
```

Version 3 newly returns None when version 2 used to retrieve app data.

Instance method documentation is:
```
/// Counterpart to [`HttpRequest::app_data`](../struct.HttpRequest.html#method.app_data).
```

HttpRequest::app_data documentation points to the root cause:

```
    /// If `App::data` was used to store object, use `Data<T>`:
    ///
    /// ```rust,ignore
    /// let opt_t = req.app_data::<Data<T>>();
```

For my code, this is a runtime breaking change from v2 and it would be nice to have a migration point:

Change:

```
let app_data = req.app_data::<T>();
```
To
```
let app_data = req.app_data::<Data<T>>();
```

* Rust Version (I.e, output of `rustc -V`):
1.46.0
* Actix Web Version:
3.0.1

**Comment by robjtede** [comment]
Thanks for flagging this missing doc, I've made some additions to the migration guide. Since you mention middleware, you must be referring to ServiceRequest::app_data method since HttpRequest::app_data has always worked like this. Now they work the same.

**Comment by staninprague** [comment]
> Since you mention middleware, you must be referring to ServiceRequest::app_data method since HttpRequest::app_data has always worked like this. Now they work the same.

True, sorry for the mystification, it is a ServiceRequest.
