### ISSUE TITLE
Logger middleware exclude pattern

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1682]
So that a regex can be used for exclusion, for path prefixes and such.

```rust
impl Logger {
	fn exclude_pattern(mut self, pattern: impl Pattern) -> Self
}
```

**Comment by mattgathu** [comment]
@robjtede I'm interested in picking this one up. Do you have an idea of what the `Pattern` trait looks like, or did you perhaps mean `IntoPattern` which exists.

**Comment by robjtede** [comment]
Not used the pattern stuff in rust directly but I thought here would be a good start:

- https://doc.rust-lang.org/1.46.0/std/str/pattern/index.html
- https://doc.rust-lang.org/1.46.0/std/primitive.str.html#method.find

though in looking at this now the Pattern trait is nightly only... ? So we may need a dedicated `exclude_regex` method to support the regex crate :(

**Comment by mattgathu** [comment]
okay, can I then pivot to implementing the `exclude_regex` variant?
