### ISSUE TITLE
Allow multiple apps to have different State

### ISSUE THREAD

**Issue by adwhit** [actix/actix-web#169]
It would be nice if it were possible to run two apps with different state e.g.
```rust
struct MyState;
let app1 = App::new()
    .prefix("/stateless")
    .route("/", http::Method::GET, |_| HttpResponse::Ok());
let app2 = App::with_state(MyState)
    .prefix("/stateful")
    .route("/", http::Method::GET, |_| HttpResponse::Ok());
// attempt make vec of IntoHttpHandler trait objects
let apps: Vec<Box<IntoHttpHandler<Handler=???>>> = vec![Box::new(app1), Box::new(app2)];
//                                        ^^^ What goes here?

let server = server::new(|| apps);
// ...
```
Unfortunately the State is part of the type of HttpApplication so it isn't possible to create an iterator of apps with different state. I think this really limits the usefulness of using multiple apps as they can't be properly isolated from each other.

**Comment by fafhrd91** [comment]
it is possible, just box application.

https://actix.github.io/actix-web/actix_web/struct.App.html#method.boxed

**Comment by fafhrd91** [comment]
your example does not work because, you have to create all apps inside a closure that you pass to a server constructor

**Comment by adwhit** [comment]
Ah OK, my mistake. Thanks

**Comment by theduke** [comment]
@fafhrd91 this info would be very helpful in the (Application) docs.

Struggled with the same problem as well.

**Comment by fafhrd91** [comment]
@theduke here is example https://actix.rs/actix-web/actix_web/struct.App.html#method.boxed

**Comment by theduke** [comment]
Yeah I discovered that, I was more thinking of https://actix.rs/book/actix-web/sec-2-application.html

**Comment by fafhrd91** [comment]
@theduke would you provide PR?

**Comment by theduke** [comment]
@fafhrd91 https://github.com/actix/book/pull/3

**Comment by fafhrd91** [comment]
Thanks!
