### ISSUE TITLE
Long, huge streaming response breaks after a while at random point

### ISSUE THREAD

**Issue by nazar-pc** [actix/actix-web#1691]
## Expected Behavior
Arbitrary sized streaming response should be downloadable.

## Current Behavior
When downloading large files (17GiB in this case) generated on the fly, sometimes download is interrupted.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Unfortunately no reproducible steps yet.

Actor implementation is essentially this:
```rust
impl Actor for Downloader {
    type Context = HttpContext<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.add_stream(self.source.stream());
    }
}
```

`source.stream()` assembles stream on the fly and the only place that can end that stream is handled in such a way that I can distinguish between actix-web stopping stream unexpectedly and EOS there.

## Context
Looks similar to #1686, but in my case there is no HTTPS involved since app is behind Traefik, which in turn prints this into logs when this happens:
```
2020-09-17 20:26:30 | time="2020-09-17T17:26:30Z" level=error msg="vulcand/oxy/buffer: error when reading request body, err: unexpected EOF"
```

Which in turn was reported as https://github.com/traefik/traefik/issues/6308 and indicated an issue in Python 3.5 (https://github.com/odoo/odoo/issues/20158), which is why I admit it can be an issue in actix-web, but not claiming it is 100% actix-web fault.

I know this is a rather vague report, I'm willing to make more specific debugging if you have suggestions and will dig deeper on my own to hopefully find the root cause of it.

## Your Environment
Kubernetes with Traefik  2.2.8 as ingress.

* Rust Version (I.e, output of `rustc -V`): 1.48.0-nightly (d006f5734 2020-08-28)
* Actix Web Version: 3.0.1

**Comment by Silentdoer** [comment]
may be cause the network, actix-web is a web framework, not a downloading server, it has not the function of resume from break-point

**Comment by fakeshadow** [comment]
1686 is fixed with 4.0.0-beta.3. 
Worth to try if it fix your problem.

**Comment by nazar-pc** [comment]
I don't think I'll be able to experiment with this until stable version is out, I basically see that for some downloads this issue happens and for some doesn't, so I know no other way than deploying an update and see how it performs.

But thanks for heads up, I'll make sure to migrate to 4.0 as soon as it is out!

**Comment by nazar-pc** [comment]
Closing for now, will reopen when I test it with 4.0 and if it is still an issue then
