### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#17]
Hello

I test a little app and i use cargo-watch as ``cargo watch -x run`` : it's work but often  i have ``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:906:4``

And i wait (1mn) ... and after it's restart

actix does not seem to release the listened port correctly (after a SIGTERM for example).

But then how to close a connection to a database or use actix-web with kubernetes like (https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/).

Have you an example to properly close actix-web.
Thank

**Comment by fafhrd91** [comment]
Yes, it is a problem at the moment. I have “gracefull shutdown” item in my todo list

**Comment by fafhrd91** [comment]
Btw thanks for reporting this problems, it is very helpful

**Comment by AlbanMinassian** [comment]
After your last commit, i search now how catch SIGINT, SIGTERM ... i have found [Signal handling – Tokio Example](https://www.codeday.top/2017/09/16/43883.html) but i don'k know how use it whith actix. What solution did you code to catch the signals ?

Thanks.

**Comment by fafhrd91** [comment]
You try this actor https://github.com/actix/actix/blob/master/src/actors/signal.rs

**Comment by fafhrd91** [comment]
I checked example, it should just work. All you need to do is send StopServer to http server on sigterm.

I will add example

**Comment by AlbanMinassian** [comment]
i wait your example because i don't understand what to do.

I have clone actix, set my ``Cargo.toml`` with ``actix = { "path" = "../actix", features=["signal"] }``
and what to do after ...

how change ``let addr = HttpServer::new(...).bind(...).spaw()`` to include ``let addr: SyncAddress<_> = Signals.start();`` and after (when SIGTERM) call ``StopServer`` ?

I you have a full example, i take.
Thanks for your help.

**Comment by fafhrd91** [comment]
I added signals support, but I think api could be better

here is example https://github.com/actix/actix-web/tree/master/examples/signals

**Comment by AlbanMinassian** [comment]
Sorry, but I still don't understand how to call the StopServer api after the sigterm signal inside a function which call dev::StopSever + print a graceufll message (by example) + and unconnect db (by example). Is not clear.

**Comment by fafhrd91** [comment]
it is not possible to call any arbitrary function on signal at the moment.
if you want to receive signals, you need to implement as `Handler` for `Signal` message.

but I see your problem, I will think about this problem.

**Comment by fafhrd91** [comment]
btw usually you don't need explicit disconnect in rust, usually connections get closed on "drop"

**Comment by AlbanMinassian** [comment]
I understand better https://actix.github.io/actix-web/guide/qs_3_5.html

**Comment by AlbanMinassian** [comment]
I have set ``.shutdown_timeout(1)`` (DEV mode) and i feel like I don't have any more latency time when the application is restarted with ``cargo watch -x run``.

**Comment by fafhrd91** [comment]
only SIGTERM is graceful restart, SIGINT and SIGQUIT are force restart
