### ISSUE TITLE
`#[scope]` macro

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1709]
an idea from a fork that seem cool:

https://docs.rs/actix-web-cute-codegen/0.1.0/actix_web_cute_codegen/attr.scope.html

**Comment by tomharmon** [comment]
I'd be interested in working on this, what improvements do you want to see in the existing crate? what changes might we want to make to `actix-web` to better support this kind of macro?

**Comment by pmd3d** [comment]
Hi. I'm interested in trying to implement this. I'm new though, but it says good first issue
