### ISSUE TITLE
How to normalize many error types?

### ISSUE THREAD

**Issue by bibhas2** [actix/actix-web#1711]
## Expected Behavior
I will like to normalize multiple error types by using ``anyhow::Error`` or ``Box<dyn std::error::Error>``. These are fairly common approaches in Rust. Neither seem to compile in Actix.

```rust
#[get("/product")]
async fn err_test1() -> std::result::Result<HttpResponse, Box<dyn std::error::Error>>  {
    return Ok(HttpResponse::NotFound().finish());
}

#[get("/product")]
async fn err_test2() -> std::result::Result<HttpResponse, anyhow::Error>  {
    return Ok(HttpResponse::NotFound().finish());
}
```

## Current Behavior
Receiving compilation error.

## Your Environment
```
rustc 1.43.1
cargo 1.43.0
actix-web = "3.0"
```

* Rust Version (I.e, output of `rustc -V`): rustc 1.43.1 (8d69840ab 2020-05-04)
* Actix Version: 3.0

**Comment by ansrivas** [comment]
@bibhas2 Until the compatibility is achieved between Actix's error, you can also try the reverse approach. All your internal errors can be of type [thiserror](https://docs.rs/thiserror/1.0.21/thiserror/#example) and then you can implement a  `From` trait to convert them to `actix_web::error::Error`.

You can check out [from implementation](https://github.com/ansrivas/bid-tracker-rs/blob/491d9a0a7a5f36d2298a580b4f8e4d8a9eeab649/src/errors.rs#L35)  and its [usage](https://github.com/ansrivas/bid-tracker-rs/blob/491d9a0a7a5f36d2298a580b4f8e4d8a9eeab649/src/api/handler.rs#L65) and see if this will suit your implementation.

**Comment by MuhannadAlrusayni** [comment]
wrapping `anyhow::Error` in newtype works for me:
```rust
struct MyError {
    err: anyhow::Error,
}
impl actix_web::error::ResponseError for MyError {
    ...
}
impl From<anyhow::Error> for MyError {
    fn from(err: anyhow::Error) -> MyError {
        MyError { err }
    }
}
```
The first impl makes it usable as the error type in a `Responder`, and the second impl makes the question mark operator work with anyhow's error type. You can use `downcast_ref` to check for the underlying error type, and use that to find the corresponding error code.

the [source](https://users.rust-lang.org/t/using-actix-and-anyhow-together/40774/2)

**Comment by Nutomic** [comment]
I also ran into this problem. Wrapping anyhow::Error in a newtype works, but ends up really verbose for an example. As a partial solution, it would be nice if actix-web could provide an `impl ResponseError for anyhow::Error`, as that should cover a very common case. The same could be done for other error crates (maybe behind feature flags).

**Comment by robjtede** [comment]
We still encourage custom enums or at least newtypes around these generic error type wrappers.

If we provide a default impl for `anyhow::Error`, `eyre::Report`, `error_stack::Report` etc. etc. then folks will (should) _still_ want customizable responses codes/body formats for various error modes.

The `error` module in Actix Web provides basic, convenient ways to wrap errors (impl std::Error) with customizable responses.

**Comment by Nutomic** [comment]
Its true that some projects will want to customize their error responses, but that is not true for all. For example i have an example in a libary which uses actix, which has to define an error wrapper to compile. There is no customization at all, and the existence of this error type distracts from the main functionality of the library.

https://github.com/LemmyNet/activitypub-federation-rust/blob/main/examples/federation/error.rs
