### ISSUE TITLE
actix-files suggestion: A optional feature which allow me to response a file embeded in released binary.

### ISSUE THREAD

**Issue by SuperHacker-liuan** [actix/actix-web#1713]
I want to provide webapps w/o any resource files to customers in traditional industries. So I tried to use [rust-embed](https://crates.io/crates/rust-embed) to embed the statics folder into the actix-web release binary. 

Till now, in actix-*, I cannot find the feature that allow me to response a file being embeded via `rust-embed` , so I implemented a class called `EmbedFile` to solve this problem myself.

Is there any plan to implement a similar feature in actix-files? With this feature, developers are able to provide only a binary executable to customers w/o providing source code tree or independent static files tree. Customers will nolonger need to set the working directory.

## Expected Behavior

In my practise, I provide a static file response via the following code.
```rust
use crate::actix_patch::EmbedFile;
use rust_embed::RustEmbed;

web::scope("/foo")
        .route(r#"/styles/{filename:.*\.css}"#, web::get().to(styles))

async fn styles(filename: web::Path<PathBuf>) -> Result<EmbedFile> {
    Ok(EmbedFile::open(
        Statics,
        PathBuf::from("styles").join(&*filename),
    )?)
}

#[derive(RustEmbed)]
#[folder = "statics/"]
struct Statics;
```

## Current Behavior

No such feature yet.

## Possible Solution

My implementation for EmbedFile looks like following.

```rust
type EtagMap = HashMap<&'static str, BTreeMap<String, u128>>;

// ETags of resource in RustEmbed classes should never be changed since resources be embeded into the binary.
// To avoid repeatable calculate ETag, make a Pool to store these constant etag value.
// Use thread_local to avoid lock acquires between threads.
thread_local! {
    static ETAG: RefCell<EtagMap> = init();
}

fn init() -> RefCell<EtagMap> {
    RefCell::new(EtagMap::new())
}

fn get_etag<E>(filename: &str) -> Option<u128>
where
    E: RustEmbed,
{
    let filename = filename.to_string();
    let typename = std::any::type_name::<E>();
    ETAG.with(|m| {
        if let Some(map) = m.borrow().get(typename) {
            return map.get(&filename).map(|u| *u);
        }
        let map = init_etag::<E>();
        let r = map.get(&filename).map(|u| *u);
        m.borrow_mut().insert(typename, map);
        r
    })
}

fn init_etag<E>() -> BTreeMap<String, u128>
where
    E: RustEmbed,
{
    let mut map = BTreeMap::new();
    for file in E::iter() {
        let file = file.as_ref();
        let etag = match E::get(file).and_then(|c| digest(c)) {
            Some(etag) => etag,
            None => continue,
        };
        map.insert(file.into(), etag);
    }
    map
}

/// Returns true if `req` doesn't have an `If-None-Match` header matching `req`.
fn none_match(etag: Option<&header::EntityTag>, req: &HttpRequest) -> bool {
    match req.get_header::<header::IfNoneMatch>() {
        Some(header::IfNoneMatch::Any) => false,

        Some(header::IfNoneMatch::Items(ref items)) => {
            if let Some(some_etag) = etag {
                for item in items {
                    if item.weak_eq(some_etag) {
                        return false;
                    }
                }
            }

            true
        }

        None => true,
    }
}

fn io_not_found<S>(info: S) -> io::Error
where
    S: AsRef<str>,
{
    io::Error::new(io::ErrorKind::NotFound, info.as_ref())
}

pub struct EmbedFile {
    content: Vec<u8>,
    content_type: mime::Mime,
    etag: Option<header::EntityTag>,
}

impl EmbedFile {
    pub fn open<E, P>(_: &E, path: P) -> io::Result<EmbedFile>
    where
        E: RustEmbed,
        P: AsRef<Path>,
    {
        let mut path = path.as_ref();
        while let Ok(new_path) = path.strip_prefix(".") {
            path = new_path;
        }
        Self::open_impl::<E>(&path).ok_or(io_not_found("File not found"))
    }

    fn open_impl<E>(path: &Path) -> Option<EmbedFile>
    where
        E: RustEmbed,
    {
        let content_type = mime_guess::from_path(&path).first_or_octet_stream();
        let filename = path.to_str()?;
        let etag = get_etag::<E>(filename);
        let r = EmbedFile {
            content: E::get(filename)?.into_owned(),
            content_type,
            etag: etag.map(|etag| header::EntityTag::strong(format!("{:x}", etag))),
        };
        Some(r)
    }

    fn into_response(self, req: &HttpRequest) -> HttpResponse {
        let status_code = if !none_match(self.etag.as_ref(), req) {
            StatusCode::NOT_MODIFIED
        } else {
            StatusCode::OK
        };

        HttpResponse::build(status_code)
            .set(header::ContentType(self.content_type))
            .if_some(self.etag, |etag, resp| {
                resp.set(header::ETag(etag));
            })
            .body(self.content)
    }
}

impl Responder for EmbedFile {
    type Error = Error;
    type Future = Ready<Result<HttpResponse, Error>>;

    fn respond_to(self, req: &HttpRequest) -> Self::Future {
        ready(Ok(self.into_response(req)))
    }
}
```

## Context

With this feature, we can release a webapp with single binary file, rather than a binary file w/ plenty of static resource file. To deploy a webapp with single file is more easier.

## Your Environment

* Rust Version: rustc 1.46.0 (04488afe3 2020-08-24)
* Actix Web Version: 3.0.2
* Actix Files Version: 0.3.0

**Comment by ansrivas** [comment]
Just wanted to chime in here and say I have a very similar implementation using `rust-embed` and I keep reusing it very frequently whenever html templates are involved.

Personally I'd think to rather keep this as an example in the [examples-repo](https://github.com/actix/examples) but if this is unified behind a feature flag in actix-files it could also be a great idea.

**Comment by ufoscout** [comment]
I have a similar need, in my case, I have to send files directly from a remote datasource (e.g. a database, a NoSql system, a generic cloud file storage, etc..), I ended up with a custom solution that duplicates most of the code of `actix-files`. 
From my point of view, the solution to all of these problems is that `actix-files` implementation should depend on an abstract `File` trait, so each user could provide his own implementation that reads the data from the desired source.

**Comment by ctaque** [comment]
Just dig into this today and found an example on rust-embed to use with actix if useful : 
https://github.com/pyros2097/rust-embed/blob/master/examples/actix.rs

**Comment by ufoscout** [comment]
@ctaque 
Your example does not handle the mime_type/content_type headers of the response as done by `actix-files::NamedFile` that infers them from the filename. That is the part that I had to duplicate (i.e. copy&paste) from NamedFile to handle my uploads from DB. That's why I proposed to make it abstract.

**Comment by robjtede** [comment]
Seems to me this use case is pretty well supported by https://github.com/kilork/actix-web-static-files. I've included it in the "community crates" section here: https://github.com/actix/actix-extras#community-crates for visibility.

Going to close this issue as out of scope for actix-files since this lib exists and seems well maintained.

**Comment by ufoscout** [comment]
@robjtede what about downloading files from a generic source (e.g. from DB, cloud storage, etc..)?

**Comment by robjtede** [comment]
Please open a new issue with a proposal.
