### ISSUE TITLE
how to get client certificates serialnumber in https with actix-web by used rustls or openssl

### ISSUE THREAD

**Issue by baoyachi** [actix/actix-web#1735]
In `server.rs`,I just want get client certificates serialnumber in https by used rustls or openssl

* in rustls,I just find function:`get_peer_certificates` https://github.com/ctz/rustls/blob/main/rustls/src/server/mod.rs#L623

* in openssl ,I just find function:`serial_number()` 
https://github.com/sfackler/rust-openssl/blob/master/openssl/src/x509/mod.rs#L573

How to used it ?

**Comment by robjtede** [comment]
track #1727

**Comment by robjtede** [comment]
I've made progress on exposing this in #1754. It can provide access to `rustls::Certificate` or `openssl::x509::X509`.
