### ISSUE TITLE
call_service panics when controller returns an error

### ISSUE THREAD

**Issue by mcohen97** [actix/actix-web#1738]
this is call_service in test.rs:

```
pub async fn call_service<S, R, B, E>(app: &mut S, req: R) -> S::Response
where
    S: Service<Request = R, Response = ServiceResponse<B>, Error = E>,
    E: std::fmt::Debug,
{
    app.call(req).await.unwrap()
}
```

If I am expecting an error from the controller, it unwraps the error and panics, is there any way to avoid this? 
Is the function call public?

**Comment by robjtede** [comment]
what sort of error are you trying to handle here? can you provide more of the code you're working with?
