### ISSUE TITLE
crate a new Examples repo

### ISSUE THREAD

**Issue by krircc** [actix/actix-web#175]
I think something should change, after i update [Rust-webapp-starter](https://github.com/OUISRC/Rust-webapp-starter) to actix-web V0.5, It's more easier now, it's time for people to try it widely.

now examples at actix-web is good for maintenance than users, it dep on master not release and change everytime. after  actix-web V0.5, I think we should move things from master to release. It should be more stable for people to try it. we should recommend people use release everywhere(repo, office..etc).  

also It's more easier for PRs

**Comment by fafhrd91** [comment]
Great idea! https://github.com/actix/examples

**Comment by fafhrd91** [comment]
We need to move user guide as well

**Comment by krircc** [comment]
@fafhrd91 cool.
do you think move 'Rust-webapp-starter' to actix repo, maybe a new name 'actix-web-vuejs-starter'.
Is it a good idea?

**Comment by fafhrd91** [comment]
I think that is fine. Do not remove old repo just add link to new repo to readme 

You should have write permission for examples repo

**Comment by krircc** [comment]
OK

**Comment by krircc** [comment]
@fafhrd91 i crate repo : awesome-actix. is that ok?
this repo should be there, before is better than after.
where a place people can share

**Comment by fafhrd91** [comment]
let remove awesome-actix at the moment, we dont really have anything for it at the moment

**Comment by krircc** [comment]
@fafhrd91 ok, 
do you mean move user guide?
move to where?

**Comment by fafhrd91** [comment]
move guide to separate repository, because it contains examples too

**Comment by krircc** [comment]
@fafhrd91  I no permission, you can remove awesome-actix.
a separate repository ? 
new 'book' repo ok?  It should have the all content about actix, actix-web, and other things about atix

**Comment by fafhrd91** [comment]
yes, book is ok.

if you want to move guide, then copy whole actix-web report and then remove unneeded, then we can maintain change history of the guide

**Comment by krircc** [comment]
@fafhrd91 ok, you are right!  It should have the all content about actix, actix-web, and other things about atix

**Comment by krircc** [comment]
@fafhrd91 I maybe do something wrong
```bash
$ git clone https://github.com/actix/actix-web.git
// then I change the guide title content and remove unneeded files
$ git remote add origin https://github.com/actix/book.git
$ git add --all
$ git commit -m "first add actix-web guide"
$ git pull origin master --allow-unrelated-histories
$ git push --set-upstream origin master
```
result : the maintain change history of the guide not there

**Comment by fafhrd91** [comment]
just clone repo from actix-web and then push same to book

**Comment by krircc** [comment]
when i do , often wrong....

**Comment by krircc** [comment]
it's ok now
