### ISSUE TITLE
Client Request with custom Body Stream halting on certain size requests

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#176]
I can probably take time to reduce this issue to something, but there might be something [obvious](https://github.com/actix/actix-web/issues/129) that may stick out.

I have created a handler that accepts a binary PUT, decorates the binary info (in this case turn it into a multipart request with the binary and a few extra values) and submits this to a backend service.  The multipart request is a custom stream, that returns Bytes when you poll it.

This works fine if:

* The binary size is below ~130kb
* The binary size is above ~265kb

If the binary size is within that range (130kb - 265kb) then the following happens:

* The Submission from the client to actix web is written on the wire
* The Stream (from debug logs) is completed
* The Client Request writes out to the backend connection roughly ~130kb and halts.
* The request never completes, the backend service gets annoyed and closes the connection after its timeout.

I can't see anything in the debug logs from the actix side of things which indicates where it's up to, or what it's getting stuck on.  I also have tried various binary sizes, or various binary formats  (I've just been generating purely random binary files to test).

The custom Stream will create variable Bytes length depending on where it's up to.  So sometimes it will return 140 bytes, sometimes it will return 32kb.

I am wondering if this has some relation to the `MAX_BUFFER_SIZE` and the maths around computing what is left.

**Comment by fafhrd91** [comment]
on it

**Comment by fafhrd91** [comment]
i can not reproduce, could you show your code? 

here is my handler:

```rust
fn streaming(req: HttpRequest) -> FutureResponse<HttpResponse> {
    req.multipart()
        .from_err()
        .and_then(|item| {
            match item {
                multipart::MultipartItem::Field(field) => {
                    client::ClientRequest::get("http://localhost:8088")
                        .body(Body::Streaming(Box::new(
                            field.from_err()
                                .map(|b| {println!("len: {}", b.len()); b})
                        )))
                        .unwrap()
                        .send()
                        .map_err(error::Error::from)
                        .and_then(|resp| {
                            println!("resp {:?}", resp);
                            Ok(HttpResponse::from(HttpResponse::Ok()))
                        })
                },
                multipart::MultipartItem::Nested(_) => {
                    panic!();
                }
            }
        })
        .finish()
        .map(|_| HttpResponse::from(HttpResponse::Ok()))
        .responder()
}
```

**Comment by cetra3** [comment]
I'll see if I can reduce it down to something more concise

**Comment by cetra3** [comment]
Ok I've managed to create a project which can replicate what I'm seeing: https://github.com/cetra3/actixtest.

I am only able to replicate this if the backend and passthrough servers have a bit of latency between them, running them both on loopback doesn't appear to trigger this behaviour, so it's best to host them on seperate devices, or introduce a bit of latency somehow.

To reiterate: the `backend` server is running fine, but the `passthrough` server is the one that gets stuck.

### Steps to Replicate

Clone the [actixtest](https://github.com/cetra3/actixtest) repo on two machines, `backend` and `passthrough`

Run this on the `backend` server:

```
cargo run -- -s
```

Run this on the `passthrough` server to have it decorate the submission before sending it to `backend`:

```
cargo run -- -c "http://<backend_ip>:7878/"
```

Create a dummy 210kb file:

```
dd if=/dev/zero of=./test.bin bs=1 count=210000
```

Submit this to the `passthrough` server a few times:

```
curl -X PUT --data-binary "@another.bin" http://<passthrough_ip>:7878
```

You should reliably be able to make the passthrough server stuck, although it doesn't get stuck all the time.

**Comment by fafhrd91** [comment]
thanks for example! fixed by 58cc0df

btw your multipart code looks good, would you contribute it?

**Comment by cetra3** [comment]
Thanks! I wouldn't mind contributing it, but would probably need to flesh it out more (to include nested multiparts, etc...)

**Comment by fafhrd91** [comment]
I think, as an initial implementation, it is pretty good.
