### ISSUE TITLE
Codegen makes certain variable names unusable

### ISSUE THREAD

**Issue by prk3** [actix/actix-web#1761]
## Expected Behavior
I'm using `get` from codegen crate to decorate a handler.
```rust
use actix_web::{get, Responder};

#[get("/fruits")]
pub async fn fruits() -> impl Responder {
    let fruits = "apple, banana, melon";
    fruits
}

#[get("/instruments-and-fruits")]
pub async fn instruments_and_fruits() -> impl Responder {
    let instruments = "guitar, piano, triangle";
    let fruits = "plum, pineapple, cherry";

    vec![instruments, fruits].join(", ")
}
```

If not the `get` attributes here, this code would compile without a problem.

However, with attributes I get the following error from `let fruits = "plum, pineapple, cherry";`:
```
error[E0308]: mismatched types
   --> src/handlers.rs:223:9
    |
214 | #[get("/fruits")]
    | ----------------- unit struct defined here
...
223 |     let fruits = "apple, banana, melon";
    |         ^^^^^^   ---------------------- this expression has type `&str`
    |         |
    |         expected `str`, found struct `handlers::fruits`
    |         `fruits` is interpreted as a unit struct, not a new binding
    |         help: introduce a new binding instead: `other_fruits`

error[E0308]: mismatched types
   --> src/handlers.rs:225:23
    |
225 |     vec![instruments, fruits].join(", ")
    |                       ^^^^^^ expected `&str`, found struct `handlers::fruits`
```

Renaming either the `fruits` function or `fruits` variable solves the problem. Hovewer, this quirk makes using attribute macros a bit annoying. Is there any alternative to creating a global unit struct?

* Rust Version (I.e, output of `rustc -V`): 1.47.0
* Actix Web Version: 2.0.0 or 3.0.0, both behave the same

**Comment by robjtede** [comment]
Seems there's a limitation being hit as a side-effect of how we generate the handler wrapping. I recommend just avoiding this by using separate modules/files or just renaming that binding.

Alternatively, and this is not a serious suggestion, adding `fn fruits () {}` as the first line of `instruments_and_fruits` also fixes it.
