### ISSUE TITLE
HttpRequest::url_for is broken with multiple separated scopes

### ISSUE THREAD

**Issue by antoine-de** [actix/actix-web#1763]
A bit different from #915 

When mounting a route with the same name on different scopes I don't see a way to choose a route or the other.

Consider the following scoped routes:
- `/a/nested` (scoped by `a`)
- `/b/nested` (scoped by `b`)
I don't see a way to get `url_for` to choose between the two routes.
`req.url_for("nested", &[])` cannot choose between the two, neither is `req.url_for("nested", &["a"])`

## Current Behavior
Here is a failing unit test:
```rust
    #[actix_rt::test]
    async fn test_url_for_multiple_scopes() {
        // We mound the route named 'nested' on 2 different scopes, 'a' and 'b'
        let mut srv = init_service(
            App::new()
                .service(web::scope("/a").service(
                    web::resource("/nested/").name("nested").route(web::get().to(
                        |req: HttpRequest| {
                            HttpResponse::Ok().body(format!(
                                "{}",
                                req.url_for("nested", &["a"]).unwrap()
                            ))
                        },
                    )),
                ))
                .service(web::scope("/b").service(
                    web::resource("/nested/").name("nested").route(web::get().to(
                        |req: HttpRequest| {
                            HttpResponse::Ok().body(format!(
                                "{}",
                                req.url_for("nested", &["b"]).unwrap()
                            ))
                        },
                    )),
                )),
        )
        .await;
        let a_resp =
            call_service(&mut srv, TestRequest::with_uri("/a/nested/").to_request())
                .await;
        assert_eq!(a_resp.status(), StatusCode::OK);
        let body = read_body(a_resp).await;
        assert_eq!(body, Bytes::from_static(b"http://localhost:8080/a/nested/"));

        let b_resp =
            call_service(&mut srv, TestRequest::with_uri("/b/nested/").to_request())
                .await;
        assert_eq!(b_resp.status(), StatusCode::OK);
        let body = read_body(b_resp).await;
        assert_eq!(body, Bytes::from_static(b"http://localhost:8080/b/nested/")); // <--- fails, equals http://localhost:8080/a/nested/
    }
```

While the mounting several named routes like this might seems stupid, I think it makes sense while doing it in a for loop. (I'm doing it [there](https://github.com/etalab/transpo-rt/blob/d023b3490015e97d28c97556e32a5145306ad061/src/server.rs#L96-L108)).
## Possible Solution
I don't really know what would be a good api for this :thinking: 

using the [url_for elements](https://github.com/actix/actix-web/blob/web-v3.1.0/src/rmap.rs#L55) doesn't really feels ok.
Neither is adding another method (`scoped_url_for`) or doing tricks on the name. Do you see a way to handle this?

The 'funny' thing was that this was working before migrating my app from actix 0.7 to actix 3.1 because I was previously mounting those scopes as different `App`s .

For me I can bypass this with custom naming (naming each routes as `{scope}/{route}`, but I'll loose the beautiful api based on the `#[get("/route")]` macro :sob: 
## Your Environment
* Actix Web Version:
the current one, 3.1.0

**Comment by robjtede** [comment]
Seems that the name resolution only searches upwards in the tree and not sideways. I havent tested but it's possible that the [external resource](https://docs.rs/actix-web/3.1.0/actix_web/struct.App.html#method.external_resource) method could be useful.

**Comment by antoine-de** [comment]
hum maybe but it seems cumbersome to add all scoped sub routes as external resource no?
Maybe we could add a way to treat hardcoded scopes as a variable by naming them.

Like 
```rust
web::scope("/a").name("a").service(...)
``` 
would need an element for the scope in the `url_for` ?

**Comment by robjtede** [comment]
For now, names of resources should be unique across an App. We now allow changing the default name of a resource that's using the routing macros if you find there's a conflict.

Example:
```rust
#[get("/", name = "something_else")]
fn handler()
```
