### ISSUE TITLE
StaticFiles unable to find files in folder with whitespace in its name

### ISSUE THREAD

**Issue by limira** [actix/actix-web#177]
Actix-web version: 0.5.0

This is an extract from log:

    "GET /glyphs/Open%20Sans%20Regular/256-511.pbf HTTP/1.1" 404 0 "http://localhost:3000/"
    ...
    ... Error occured during request handling: No such file or directory

I double-checked that the required folder/file exists (of course, it has whitespace instead of %20). Other files in non-whitespace-folder have been served successfully.

**Comment by fafhrd91** [comment]
fixed by 22c776f
