### ISSUE TITLE
Add on_connect extension data to all subsequent calls made through the connection

### ISSUE THREAD

**Issue by hce** [actix/actix-web#1770]
## Expected Behavior
I'm using on_connect to extract a TLS client certificate and add it to the Extensions data structure to expose it to API handlers via ReqData. I expect this data "attached" to extensions to be retrievable during all subsequent calls made to the API through the same TLS session.

## Current Behavior
The data attached to the Extensions structure is discarded after the first HTTP call. Subsequent HTTP calls yield calls to the rust API handlers I implemented, but without the TLS client certificate available through ReqData anymore.

## Possible Solution
Since one TLS connection can be reused multiple times, the Extensions data structure should be preserved for the duration of the TLS session, or there should be an alternative mechanism to attach data to the TLS session.

## Steps to Reproduce (for bugs)
Call .on_connect on an HttpServer and have the function attach some data to the Extensions structure, like this:

    struct HelloWorldExt;
    fn attach_test(connection: &dyn Any, data: &mut Extensions) {
        data.insert(HelloWorldExt);
    }
    http_server.on_connect(attach_test);

Then implement an API handler like this:

    async fn api_handler(hwext: ReqData<HelloWorldExt>) { eprintln!("Success!"); ... }

This call will fail after the first time when made through the same TLS connection.

## Context
This issue prevents me from implementing authentication via TLS client certificates for my REST API.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix-web Version: 3.2.0

**Comment by robjtede** [comment]
I had the impression rustls or openssl would handle the TLS session continutation though I admit I didn't test this case when coding this up. Possibly some additional config on rustls at least could make this work: https://docs.rs/rustls/0.18.1/rustls/struct.ServerConfig.html#method.set_persistence.

**Comment by hce** [comment]
Thanks! I just added a session cache like this:

        let cache = rustls::ServerSessionMemoryCache::new(512);
        rustls_config.set_persistence(cache);

But to no avail. on_connect is still only called once and the data it sets is no longer accessible after the first call.

**Comment by robjtede** [comment]
Oh I see, the issue is that the on_connect hook is skipped for subsequent TLS calls. Can I ask you to just with keep alive turned off, might help pin-point the problematic code.

**Comment by hce** [comment]
Changed my code to

    .keep_alive(None)
    .on_connect(get_conn_info);

But still the same. on_connect is only called once.

**Comment by robjtede** [comment]
Okay, thanks. Are you able to share any client side code for validating a fix?

**Comment by hce** [comment]
I can write a stub library to reproduce the problem if you like.

**Comment by hce** [comment]
But I think you should be able to test it with https://github.com/actix/actix-web/blob/master/examples/on_connect.rs ; just make the call to the whoami service twice from the browser...

**Comment by hce** [comment]
My bad, the on_connect example needs to be expanded a bit. I'll do it and let you know.

**Comment by hce** [comment]
Here you go: https://github.com/hce/actix-web-client-cert-test

**Comment by hce** [comment]
Do you think a good workaround would be to register a middleware that writes a (random string,certificate) into a database and sets a cookie with the random string so all subsequent calls can retrieve the certificate from the database when they see that cookie value?

**Comment by hce** [comment]
That's the workaround I now implemented and it works wonderfully.

By the way, I read this ticket's backlog again: I don't think the on_connect function needs to be called more often; just the results it stores should be preserved.

**Comment by leonbreedt** [comment]
@robjtede @hce I am facing the same problem, due to the same issue.

This appears to be the cause, in the dispatchers:

```rust
this.on_connect_data.merge_into(&mut req);
```

This method is called for each request, however, it will only once populate the extensions for the first request, because it drains the `Extensions` created by the `on_connect` callback, probably due to the fact that it stores owned data that cannot be copied/cloned, and therefore inserted multiple times.

```rust
    pub(crate) fn merge_into(&mut self, req: &mut Request) {
        if let Some(ref mut ext) = self.0 {
            req.head.extensions.get_mut().drain_from(ext);
        }
    }
```

So I am not sure how `on_connect` could work to insert extension data for connections that will have multiple requests go over the channel.
