### ISSUE TITLE
actix client struggles with 'Expect: 100-continue' header

### ISSUE THREAD

**Issue by LeSim** [actix/actix-web#1775]
First of all, thanks for this great tool.

## Expected Behavior
When the client send a put request with a `Expect: 100-continue` header, it could receive a 100 (Continue) intermediary response. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect, https://tools.ietf.org/html/rfc7231#section-5.1.1). But the client must not consider it as the final server answer.

## Current Behavior
The client immediatly returns the intermediary response `HTTP/1.1 100 Continue`.

## Steps to Reproduce (for bugs)
```
use actix_web::Error;

#[actix_web::main]
async fn main() -> Result<(), Error> {

    let client = actix_web::client::Client::new();

    let response = client
        .put("http://httpbin.org/put")
        .header("Expect", "100-continue")
        .send_body("hello")
        .await?;

    println!("Is success: {:?} ", response.status().is_success()); // is_success : false ; status code: 100

    Ok(())
}
```

## Context
I was hit by this pb while trying to debug an integration test of an proxy (https://github.com/betagouv/ds_proxy/blob/master/tests/end_to_end.rs#L91) . It could also be reproduce using the vanilla example https://github.com/actix/examples/tree/master/http-proxy . And I suppose it should re open https://github.com/actix/examples/issues/273 .

## Your Environment
ubuntu 18.04
rustc 1.46.0
actix-web 3.2.0

**Comment by fakeshadow** [comment]
With 2049 merged I'm able to run the example code and get the expected behavior.
Closing this for now and please ping me for re-open if you still encounter problem.
