### ISSUE TITLE
local_address support for non-default network interfaces

### ISSUE THREAD

**Issue by Gelbpunkt** [actix/actix-web#1778]
## Usecase
I have a nondefault network interface that I want to send awc client requests over.

## API example
```rust
let addr = std::net::IpAddr::v4(std::net::Ipv4Addr::new(127, 0, 0, 1));
let client = ClientBuilder::new().local_address(addr).finish();
```

## Other implementations
[reqwest has such method.](https://docs.rs/reqwest/0.10.8/reqwest/struct.ClientBuilder.html#method.local_address)

**Comment by fakeshadow** [comment]
@Gelbpunkt Can you give the master branch a try to see if it works as you expected?

**Comment by Gelbpunkt** [comment]
@fakeshadow hi there, yes it works perfectly :+1:
