### ISSUE TITLE
Websocket does not work properly when client and server have different endianess

### ISSUE THREAD

**Issue by thanasis2028** [actix/actix-web#1782]
I am running an actix-web websocket server on a MIPS big-endian system. Communication with an actix websocket client running on the same system works properly, however when trying to connect using any client on x86_64 (tried with actix, python, and js clients), the client will either get disconnected immediately, or the server will receive wrong text (garbage characters).

The same should probably happen if the client is running on MIPS and the server on x86_64 but I haven't tested that.

## Expected Behavior
Any client should connect and send/receive messages properly.

## Current Behavior
The client will either get disconnected immediately, or the server will receive wrong text (garbage characters).

## Possible Solution
I tracked the bug in the way actix-http handles masks; they always use little endian while they should use native endian. (both client and server-side have the same bug and that's why it works on big-endian to big-endian.

The following patch fixed it for me (works for x86_64->x86_64, x86_64->MIPS, MIPS->MIPS):
```
diff --git a/actix-http/src/ws/frame.rs b/actix-http/src/ws/frame.rs
index 0598a9b4..460e4fc6 100644
--- a/actix-http/src/ws/frame.rs
+++ b/actix-http/src/ws/frame.rs
@@ -78,7 +78,7 @@ impl Parser {
             }

             let mask =
-                u32::from_le_bytes(TryFrom::try_from(&src[idx..idx + 4]).unwrap());
+                u32::from_ne_bytes(TryFrom::try_from(&src[idx..idx + 4]).unwrap());
             idx += 4;
             Some(mask)
         } else {
@@ -188,7 +188,7 @@ impl Parser {

         if mask {
             let mask = rand::random::<u32>();
-            dst.put_u32_le(mask);
+            dst.put_slice(&mask.to_ne_bytes());
             dst.put_slice(payload.as_ref());
             let pos = dst.len() - payload_len;
             apply_mask(&mut dst[pos..], mask);
```

## Steps to Reproduce (for bugs)
1. Compile and run any websocket server on a big-endian system. The [websocket-chat](https://github.com/actix/examples/tree/master/websocket-chat) example is good enough.
2. Run any websocket client on a small-endian system and try to communicate with the server. Again, the [python client](https://github.com/actix/examples/blob/master/websocket-chat/client.py) in websocket chat is a good example.
3. The server will either receive garbage data or disconnect the client immediately.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: 3.2.0
For the server, I'm cross-compiling using `--target=mips-unknown-linux-gnu`.

**Comment by fakeshadow** [comment]
I believe this is fixed with the current master branch.

Closing for now. Please ping me if there is still issue on this for re-open or further discussion.
