### ISSUE TITLE
cause memory leak by create new socket?

### ISSUE THREAD

**Issue by baoyachi** [actix/actix-web#1789]
cause memory leak code under below:
```rust
impl HttpRequestPool {
    /// Allocates a slab of memory for pool use.
    pub(crate) fn create() -> &'static HttpRequestPool {
        let pool = HttpRequestPool(RefCell::new(Vec::with_capacity(128)));
        Box::leak(Box::new(pool))
    }
}
```
the `Box::leak` caused memory leak?

**Comment by fakeshadow** [comment]
No.
Firstly HttpRequestPool does not create new socket. No idea why you think that way.
Second HttpResquestPool is owned by AppInitService which would clear the pool on drop.
Third there is a capacity for the pool and it can not grow beyond that.
