### ISSUE TITLE
Cannot access app_data in middleware of Scope

### ISSUE THREAD

**Issue by trevor-crypto** [actix/actix-web#1790]
## Simple Use Case
```rust
...
web::scope("/api")
    .app_data(web::Data::new(1usize))
    .wrap_fn(|req, srv| {
        let i = req.app_data::<usize>();
        println!("i {} ", i.is_some()); // outputs "i false"
        let fut = srv.call(req);

        async move {
            let res = fut.await?;
            Ok(res)
        }
    })
...
```
## Expected Behavior
Ability to access the request's `app_data` within the middleware (`wrap` / `wrap_fn`) of a `Scope`.

## Current Behavior
Looking at the example code above, you would expect that `app_data` from the request can be retrieved, but it does not work.
If you move the setting of `app_data` outside the scope (ex. on `App::new().app_data(data)`) the data is accessible from within the middleware.

## Possible Solution
Spoke with @robjtede on the Gitter channel and he advised me to submit this issue. I am currently looking into debugging it myself, but I am new to the code.

One thought that I have is that in the use case above you can't get the data because `ScopeService` doesn't invoke `call()` until after trying to get the data, since on `ScopeService::call()` it stuffs its data into the request.

* Rust Version (I.e, output of `rustc -V`): rustc 1.50.0-nightly (825637983 2020-11-18)
* Actix Web Version: actix-web = "3"

**Comment by robjtede** [comment]
for anyone finding this, a workaround is possible using an empty scope, eg:

```rust
scope("/mobile")
    .app_data(1usize)
    .service(
        scope("").wrap_fn(...)
    )
```
