### ISSUE TITLE
Connection Reset and Trace Logging

### ISSUE THREAD

**Issue by d00z3l** [actix/actix-web#1796]
## Expected Behavior
Each request should work as expected. Trace/debug logs should be displayed.

## Current Behavior
I am using Postman to test my actix web server and are getting random "connection reset" errors when using a POST request. They are random in that they could happen every n-th time I issue a request. It could happen every 20th time, 5th or two in a row. Re-issuing the request will normally be successful. When it fails it fails immediately.

I am using `CookieSession`, not sue if that has anything to do with it.

```
POST http://localhost:5050/view/Flight/execute
Error: read ECONNRESET
```

I have tried to enable the trace logs for actix_web and actix_net that other people have referred to but can't get any log messages. I am on Windows and have tried the following `RUST_LOG` values:
```
set RUST_LOG=info,actix_web=trace,actix_net=trace
set RUST_LOG=actix_web=trace,actix_net=trace
set RUST_LOG=trace
```

The standalone `trace` value will log trace logs for actix_server, actix_http and mio, for all 3 I never see any actix_web or actix_net logs. Should I be using different logs?

## Possible Solution
If I could get the logs working I can probably find the issue myself.

## Steps to Reproduce (for bugs)
1. Execute POST request using Postman N times
2. Receive `ECONNRESET`

## Context
It isn't a big impact while testing but I am worried it will fail when going to production.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.48.0 (7eac88abb 2020-11-16)
* Actix Web Version: 3.2.0

**Comment by robjtede** [comment]
Do you have env_logger crate initialized? If not, check out the examples repo, most of those projects use it.
