### ISSUE TITLE
req.query inside future

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#18]
Hello

i have this route (POST) "/name/{name}" to match "/name/aaa?token=xxxxxxxxxxx"
i try to get data inside path (ok) AND query (ko) AND body (ok)
```
fn action(mut req: HttpRequest) -> Box<Future<Item=HttpResponse, Error=Error>> { // println!("{:?}", req);
    let name: String = req.match_info().query("name").unwrap(); // <== OK, i get "aaaa"
    let query:HashMap<Cow<str>, Cow<str>> = req.query(); println!("{:?}", query); // <== KO, if i add this line
    req.payload_mut().readany() .... <== OK, i get body 
```
build error 

```
error[E0502]: cannot borrow `req` as mutable because it is also borrowed as immutable
   --> src/main.rs:84:5
    |
73  |     let rawquery:HashMap<Cow<str>, Cow<str>> = req.query(); println!("{:?}", rawquery);
    |                                                --- immutable borrow occurs here
...
84  |     req.payload_mut().readany()
    |     ^^^ mutable borrow occurs here
...
129 | }
    | - immutable borrow ends here

```

But if set ``fn action(req: HttpRequest) `` i have another error.

How extract query params (when i need also path and body) - see nothing in doc.
Thanks

**Comment by fafhrd91** [comment]
`req.query()` returns hash map of references, in most cases it does not copy data, 
that is why borrows `req`. so you have to extract query() parameter and convert it to String, then you should be able to use payload.

something like:
```rust
let param = req.query().get("token").unwrap().to_owned();
```

I am not sure about `req.query()` api yet. maybe it should return owned string

**Comment by fafhrd91** [comment]
other option is something like "query extractor" similar to `Params` type

**Comment by AlbanMinassian** [comment]
my quickly solution 

```
use url::{form_urlencoded};
...
for (key, val) in form_urlencoded::parse(req.query_string().as_ref()) { 
     println!("{} => {}", key, val);
}
```

Thanks

**Comment by fafhrd91** [comment]
I'll make this api more friendly later today

**Comment by fafhrd91** [comment]
I change `query()` api, it should more user friendly now

https://actix.github.io/actix-web/actix_web/struct.HttpRequest.html#method.query

**Comment by AlbanMinassian** [comment]
Thank you, that's great.
