### ISSUE TITLE
MovedPermanenty -> MovedPermanently

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#180]
https://github.com/actix/actix-web/blob/22c776f46ea169a29d5a34572d71a966db25044b/src/httpcodes.rs#L205

There is a typo in there:

 `STATIC_RESP!(MovedPermanenty, StatusCode::MOVED_PERMANENTLY);`

Should be `MovedPermanently` (MovedPermanent**l**y)

**Comment by fafhrd91** [comment]
thanks! fixed
