### ISSUE TITLE
Optionally support hidden files/directories in actix-files

### ISSUE THREAD

**Issue by dodomorandi** [actix/actix-web#1808]
## Expected Behavior
It should be possible to serve static hidden files/directory.

## Current Behavior
A leading dot in a url fragment is currently not allowed, even if a file or directory with the exact name exists.

## Steps to Reproduce (for bugs)
Instantiate a server with a `Files` service to serve static files, then try to access an existing hidden file or directory.

## Context
This is particularly useful when trying to use certbot to perform its challenge. Probably its not good to allow this by default, I would like the feature to be enabled using a boolean flag.

## Your Environment
* rustc 1.48.0 (7eac88abb 2020-11-16)
* actix-files: 0.4.1
* actix-web: 3.3.0

**Comment by robjtede** [comment]
released in actix-files v0.5.0
