### ISSUE TITLE
Support custom handling of extractor errors

### ISSUE THREAD

**Issue by connec** [actix/actix-web#181]
Example:

```rust
fn main() {
    ...
    App::new().resource("/items", |r| r.with(create_item))
    ...
}

#[derive(Deserialize)]
struct Item {
    ...
}

fn create_item(item: Json<Item>) -> HttpResponse {
    ...
}
```

Currently, if there is a deserialization error when attempting to extract an `Item` (e.g. because the JSON payload has missing fields, or is the wrong type) an empty HTTP 400 Bad Request response will be returned due to the impl of [`ResponseError for DeError`](https://github.com/actix/actix-web/blob/master/src/error.rs#L122).

Whilst this is sufficient for experimental or internal APIs, it would be useful to be able to customise or override how errors are handled. For myself, I wanted to include the text of the serialization error in the response body so consumers can debug their bad requests.

**Comment by fafhrd91** [comment]
added [JsonConfig::error_handler()](https://actix.rs/actix-web/actix_web/dev/struct.JsonConfig.html)

**Comment by fafhrd91** [comment]
you can use this method https://actix.rs/actix-web/actix_web/error/struct.InternalError.html#method.from_response

**Comment by connec** [comment]
Wow, quick update, thanks! I will give it a try 😄

**Comment by fierydrake** [comment]
> added [JsonConfig::error_handler()](https://actix.rs/actix-web/actix_web/dev/struct.JsonConfig.html)

moved to here https://actix.rs/actix-web/actix_web/web/struct.JsonConfig.html#method.error_handler

**Comment by axic** [comment]
Active docs at https://docs.rs/actix-web/latest/actix_web/web/struct.JsonConfig.html#method.error_handler
