### ISSUE TITLE
No method to get cookie from 'ServiceRequest'

### ISSUE THREAD

**Issue by codingben** [actix/actix-web#1818]
## Expected Behavior
`let cookie = req.cookie("whoami");`

## Current Behavior
`let (http_req, payload) = req.into_parts();`
`let cookie = http_req.cookie("whoami");`
`let req = ServiceRequest::from_parts(http_req, payload).ok().unwrap();`

## Possible Solution
Add cookie method to 'ServiceRequest' (Let's say: &self.cookie(x) or similar).

## Context
It's weird to use 'into_parts()' to get only cookie and then 'from_parts()'. There is no other way to do this, see the [ServiceRequest](https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.ServiceRequest.html) documentation.

**Comment by robjtede** [comment]
Now that I've had a look, it seems that cookies should be supported on ServiceRequest through the HttpMessage impl. https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.ServiceRequest.html#impl-HttpMessage

See if you can replace your current implementation by importing that trait and using its cookie method. https://docs.rs/actix-web/3.3.2/actix_web/trait.HttpMessage.html#method.cookie

**Comment by Martichou** [comment]
Oh yeah, you're right. It's already supported ! 
My bad, my PR is useless :-1: Gonna close it !

We just need to `use actix_http::HttpMessage` and the `cookie()` function is accessible !

**Comment by robjtede** [comment]
Sorry about that @Martichou. Thanks for opening it. 🙃
