### ISSUE TITLE
High CPU usage with WebSocket server and `thor` benchmark

### ISSUE THREAD

**Issue by lberrymage** [actix/actix-web#1819]
## Expected Behavior
A basic WebSocket server should be able to handle many concurrent connections from the [`thor`](https://github.com/observing/thor) benchmarking tool (and any other tool) with ease.

## Current Behavior
Running `thor` against a basic WebSocket server maxes out a CPU core for each WebSocket connection it makes. Other tools, namely [`wscat`](https://github.com/websockets/wscat) and `curl` with the proper headers, do not, and create practically zero CPU usage for a single connection as they should.

## Possible Solution
Unknown

## Steps to Reproduce
1. Create a new `cargo` project with the following contents:

`Cargo.toml`
```toml
[package]
name = "actix_high_cpu_test"
version = "0.0.0"
edition = "2018"

[dependencies]
actix = "0.10.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
```

`src/main.rs`
```rust
use std::io;

use actix::{Actor, StreamHandler};
use actix_web::{
    web::{self, Payload},
    App, HttpRequest, HttpServer, Responder,
};
use actix_web_actors::ws::{self, ProtocolError, WebsocketContext};

#[actix_web::main]
async fn main() -> io::Result<()> {
    HttpServer::new(|| App::new().route("/", web::get().to(websocket_service)))
        .bind("localhost:8080")?
        .run()
        .await
}

async fn websocket_service(req: HttpRequest, stream: Payload) -> impl Responder {
    ws::start(WsSession::default(), &req, stream)
}

#[derive(Default)]
struct WsSession;

impl Actor for WsSession {
    type Context = WebsocketContext<Self>;
}

impl StreamHandler<Result<ws::Message, ProtocolError>> for WsSession {
    fn handle(&mut self, _: Result<ws::Message, ProtocolError>, _: &mut Self::Context) {}
}

```

2. Install `thor` from the [GitHub repository](https://github.com/observing/thor/tree/20c51d6c5dcc57a1927ae0c6e77f21836d71f9de) (the npm version is broken) via `npm install -g https://github.com/observing/thor`
3. Run the `cargo` project
4. In another terminal, run `thor ws://localhost:8080 -A 1 -C 1`
5. Check the `cargo` project's CPU usage. It should max out out a core for each time you run `thor`, and continue maxing the CPU even after the `thor` process(es) are killed.

## Your Environment

* Rust Version (i.e, output of `rustc -V`): `rustc 1.48.0 (7eac88abb 2020-11-16)`
* Actix Web Version: `3.3.2`

**Comment by fakeshadow** [comment]
```rust
impl StreamHandler<Result<ws::Message, ProtocolError>> for WsSession {
    fn handle(&mut self, res: Result<ws::Message, ProtocolError>, ctx: &mut Self::Context) {
        match res {
            Ok(_) => println!("do something"),
            Err(e) => {
                println!("got error: {:?}", e);
                ctx.stop();
            }
        }
    }
}
```

What your example does is expose itself to spam attack since you don't handle error at all and take in anything as a useful ws stream.

actix-web-actors in general is a low level API. It expose the websocket stream to you with error. You have to deal with the error yourself. 

On top of handling error you would also want a rate limit and payload limit for your ws endpoints. These in general are not part of actix-web/actix-web-actors API. So you need something homebrew or third party.

**Comment by lberrymage** [comment]
My assumption was that ignoring a given message would drop it and effectively ignore it. I realize this isn't always desired behavior in a real application, but I would think that ignoring a message, "good" or malformed, is sometimes desired.

In an `Err(_)` continually re-passed through `StreamHandler::handle()` until the actor is stopped, unlike valid messages?

**Comment by fakeshadow** [comment]
You can use any tool that produce large amount of unmasked frame and it would also burn your CPU. 
This's how stream works. You treat error as success, and you don't yield to executor. Then it just keep going.

Bechmark IO only makes sense when there is actual IO. 

The minimal error types you want to deal with are 
`ProtocolError::{UnmaskedFrame, InvalidOpcode, Overflow}`
and `ProtocolError::MaskedFrame` if you run it as a client.

Parsing the metadata of ws frames only peek into the stream data and not consuming it.
Ignoring them would change your benchmark to how fast my CPU can produce parsing errors.

**Comment by lberrymage** [comment]
Thank you for explaining that, it makes sense to me now. Do you think it's worth mentioning in the docs that errors are not consumed for the reasons you brought up?

**Comment by fakeshadow** [comment]
Yea sure. PR is welcome. 
Preferably in `actix-web-actors` as the actual parsing logic is in `actix-http` and I doubt people would go in that deep to see the detailed doc.

**Comment by lberrymage** [comment]
Great. I think I'll close this then since the "issue" itself is resolved, and I'll get on updating the documentation sometime soon.
