### ISSUE TITLE
Improve `web::Query`

### ISSUE THREAD

**Issue by attila-lin** [actix/actix-web#1822]
Now actix-web seems will not deal with a query like 

`get xxxx/api?color[]=blue&color[]=black&color[]=red`

with

```
struct ColorQuery {
    color: Vec<String>
}
```

I think it will be very useful in some cases.

**Comment by robjtede** [comment]
This has been brought up a few times. Search the closed issues.

The serde-qs crate provides an actix extractor that supports this I believe.
