### ISSUE TITLE
"actix-rt:worker" received signal SIGSEGV

### ISSUE THREAD

**Issue by Hcreak** [actix/actix-web#1833]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Current Behavior

The program exits abnormally. And Use gdb to debug output:
`Thread 2 "actix-rt:worker" received signal SIGSEGV, Segmentation fault.`

## Possible Solution

Use `glibc` instead of `musl` to compile without problems
#### Problematic environment: ####
build container image: `rust:alpine`    run container image: `alpine:latest` 
#### Successful environment: ####
build container image: `rust:buster`    run container image: `ubuntu:focal`

## Steps to Reproduce (for bugs)

1.   build container image: `rust:alpine`    run container image: `alpine:latest` 
2.   Cargo.toml
```
[package]
name = "user_admin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
log = { version = "0.4.5", features = ["std"] }
env_logger = "0.7.1"
simple_logger = "0.5"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
actix-web = "2.0"
actix-rt = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
rand = "0.7.3"
tokio-postgres = { version = "0.5", features = ["with-serde_json-1","with-chrono-0_4"] }
deadpool-postgres = "0.5.5"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v1"] }
urlencoding = "1.1.1"
rust-crypto = "0.2.36"
base64 = "0.12.3"
time = "0.2.16"
regex = "1.3.9"
jwt = "0.10.0"
sha2 = "0.9"
hmac = "0.8"
 ```
3.
4.

## Your Environment

* Rust Version (I.e, output of `rustc -V`):
* Actix Web Version:  `2.0`

**Comment by fakeshadow** [comment]
Can you try start the server with `HttpServer::disable_signals`?

Edit: Never mind. I missed the signal type has nothing to do with normal signals.

**Comment by robjtede** [comment]
I'm surprised it even built successfully under musl. I'm certain this wasn't always the case. Anyhow it's risky to do so still as some of our upstream deps don't really support it though these days I couldn't say for sure which ones.

**Comment by robjtede** [comment]
Closing because stance on official musl support is still the same; we don't officially support it because there is not that much demand to do so.

If it works, great. If it doesn't, then it's likely that some of our dependency crates are at fault rather than actix.
