### ISSUE TITLE
Implement FromRequest for header types

### ISSUE THREAD

**Issue by lovasoa** [actix/actix-web#1837]
Currently, there are no extractors for HTTP headers, and application code has to extract the headers itself, which can be a little verbose, and can [annoy users](https://stackoverflow.com/questions/52919494/is-there-simpler-method-to-get-the-string-value-of-an-actix-web-http-header).

## Expected Behavior
```rust
#[post("mypost")]
async fn post_handler(
    req_body: web::Bytes,
    content_type: Option<http::header::ContentType>
) -> impl Responder {
    /* do something with the content type*/
    req_body
}
```

## Current Behavior
Compiling the code above raises the following error : 

```
the trait `actix_web::FromRequest` is not implemented for `actix_web::http::header::ContentType`
```

## Possible Solution

Maybe `FromRequest` could be implemented for the various types in `actix_web::http::header::*` ?

## Context

Sometimes an application has to handle a request differently based on an HTTP header. Having to parse the header in code is a slight friction that could be resolved. 

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: 3.3.2

**Comment by pickfire** [comment]
```rust
#[post("mypost")]
async fn post_handler(
    req_body: web::Bytes,
    accepts: Vec<http::header::Accept>
) -> impl Responder {
    /* do something with the accept */
    req_body
}
```

Doesn't that means this could work as well? Since some types can appear multiple times (or multiple values within the same header).
