### ISSUE TITLE
Sending shared text messages to Websocket clients

### ISSUE THREAD

**Issue by nikarh** [actix/actix-web#1846]
Currently Websocket message enum is defined as follows:

```rust
pub enum Message {
    Text(String),
    Binary(Bytes),
    Continuation(Item),
    Ping(Bytes),
    Pong(Bytes),
    Close(Option<CloseReason>),
    Nop,
}
```

The `Binary` type contains `Bytes` which essentially is a shared pointer to the actual data. But at the same time `Text` member contains an owned `String`, which makes it impossible to send the same `String` to multiple Websocket connections without actually copying string bytes.

## Expected Behavior
I would expect Text messages to be consistent with Binary messages and for it to be possible to make Websocket text messages with shared strings.

## Current Behavior
With text Websocket messages it is only possible to move a string with it's data.

## Possible Solution
A breaking change in the API, which changes String to an Arc<String> in

```rust
pub enum Message {
    ...
    Text(String),
    ...
}
```

## Context
Image a scenario where many Websocket clients are connected to a server, and a server occasionaly wants to send the same (potentially huge) text payload to all of the clients. A server would have to clone the same String for each client, which is a huge overhead.

## Your Environment

* rustc 1.50.0-nightly (d9a105fdd 2020-11-23)
* Actix Web Version: 3.3.2

**Comment by fakeshadow** [comment]
Message type is meant to be handled by single thread.

Changing it to Arc would be forcing everyone to pay for extra atomic operations when most people don't need it.

You can go a bit lower by implementing your own payload decode logic and get a `Frame` type which is basically a collection of Bytes. Or just raw Bytes.

**Comment by nikarh** [comment]
I'm not sure I understand how that would help me in this situation, since in the use case I described I'm actually talking about encoding, and not decoding.
I agree that there is no reason to make an Arc in a decoder, since I can always move value from a decoded message to wherever I want.

In order to send shared strings I will basically have to copy and re-implement the whole actix ws implementation (both actix_http::ws and actix-web-actors).
In my opinion the use case I have described (sending the same message to multiple clients) is not that rare for a Websocket server. Also I see an inconsistency here, because `Binary` messages already are smart pointers with Send, so they already force everyone who sends binary messages to pay for it, but not those who send String messages.

**Comment by fakeshadow** [comment]
There is no incontinence. Bytes is used because that's a part of tokio.

**Comment by nikarh** [comment]
As far as I can tell, an Encoder doesn't actually require `Bytes`, since in it's implementation it calls `Parser::write_message` which accepts any `AsRef<[u8]>`. It looks like an Encoder accepts `Bytes`, just because it uses Message enum which for `Binary` type happened to use `Bytes`. It doesn't have anything to do with tokio. I would agree that `Bytes` are essential in a Decoder (because of tokio), but not in an encoder. So to me that still looks like an inconsistency.

Is there a particular reason why ws messages are encoded with a `Message`, but decoded to a `Frame` (later to be mapped to a `Message` by `actix-web-actors`)?
To me it looks like an Encoder can also work with `Frames` internally, this way `actix-web-actors` would still be able to provide convenient methods for sending messages (like `text<T: Into<String>>(&mut self, text: T)`), but those who have the same use case as I do can go low-level (`write_raw`) without having to rewrite ws implementation.

I know that I am biased by my use case, but to me it still looks like a Sync overhead is negligible comparing to the overhead imposed by inability of broadcasting the same message to many clients without doing unnecessary copies of strings.

**Comment by nikarh** [comment]
It also might be possible fix this without forcing everybody to use Arcs by making an Encoder use `Either<Message, SharedMessage>` where one contains `String` or `Vec<u8>`, and the other `Arc<String>` or `Bytes`.
This approach was taken in a [yet to be merged PR](https://github.com/snapview/tungstenite-rs/pull/104/files) in tungstenite-rs

**Comment by robjtede** [comment]
Potentially could be solved by using [`bytestring::ByteString`](https://docs.rs/bytestring/0.1.5/bytestring/struct.ByteString.html) as the contained type with any relevant methods taking `Into<ByteString>` to allow accepting Strings still.
