### ISSUE TITLE
decouple web and client

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1855]
Currently the re-export of awc as actix_web client means that breaking changes to the client effect web, too.

I'd like to remove this publicly visible link as well as any others regarding the integration testing.

**Comment by punkeel** [comment]
awc is _only_ used in `src/test.rs`. Would it be possible to move this test code to `actix-http-test`?

EDIT: I do't see awc as a re-export from actix_web, is that ticket still relevant? 
https://github.com/actix/actix-web/blob/effacf8fc8ee8aedf1a5c809dbb1b066aad7a862/src/test.rs#L875

**Comment by robjtede** [comment]
Yep the client mod has been removed.
Moving the integration test functionality to a separate crate left to close this.

**Comment by fakeshadow** [comment]
I would suggest remove client from actix-http(at least for connector and connection part. codec and header/body types can be kept in). Any client break change happens at client::connector level would still break actix-http therefore breaks actix-web

**Comment by robjtede** [comment]
removing it with the intention of merging the right abstractions back in for this breaking release would be okay
