### ISSUE TITLE
EventSource / Server Sent Events (SSE) support

### ISSUE THREAD

**Issue by greglearns** [actix/actix-web#186]
Can actix-web support SSE / server-sent events / event source?

**Comment by fafhrd91** [comment]
it supports streaming responses. you need to implement event source yourself. 
here is example https://github.com/actix/sockjs/blob/master/src/transports/eventsource.rs

**Comment by fafhrd91** [comment]
@greglearns join gitter, you can ask me directly

**Comment by brandonros** [comment]
Can a newer example please be posted?

**Comment by robjtede** [comment]
@brandonros 

https://github.com/actix/examples/tree/master/server-sent-events
