### ISSUE TITLE
add msrv to clippy config

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1861]
https://github.com/rust-lang/rust-clippy#specifying-the-minimum-supported-rust-version

**Comment by ibraheemdev** [comment]
Is the msrv 1.46?
```markdown
// readme
- runs on stable Rust 1.46+
```

**Comment by Martichou** [comment]
https://github.com/actix/actix-web/commit/2a2a20c3e740a47b1534662500e9d3c065bdfa79

@ibraheemdev  I guess so
