### ISSUE TITLE
session name & example

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#19]
Hello

We can set cookie ``path``, ``domain``, ``secure`` ... but not ``name`` : always ``actix_session``. Can you add a method to modify it? 

If you have an example to manage database sessions (with [tokio-redis](https://github.com/tokio-rs/tokio-redis) or [tokio-postgres](https://github.com/sfackler/rust-postgres/tree/master/tokio-postgres)) I would be interested to find example inside example/basic.rs (login/logout)

Thanks

**Comment by fafhrd91** [comment]
Would you provide PR for “actix_session”? It is easy, I think you can do this :)

Redis integration is one of my next items. I am not sure about tokio-postgres, I think diesel example is more ergonomic and more performant.

**Comment by AlbanMinassian** [comment]
PR https://github.com/actix/actix-web/pull/20

**Comment by fafhrd91** [comment]
I added redis integration https://github.com/actix/actix-redis
