### ISSUE TITLE
Client timeout error occur at high latency

### ISSUE THREAD

**Issue by Icatream** [actix/actix-web#1915]
## Environment
WSL2 ubuntu 20.04
Rust Version 1.48 or 1.49

### Cargo.toml
```
[package]
name = "ws-bd"
version = "0.1.0"
authors = ["wind"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version="0.3", features=["async-await"]}
#futures-util = "0.3"
async-std = "1"
actix-web = {version="3", features=["rustls"]}
rustls = {version="0.18.1",features=["logging"]}
log = "0.4"
rustls-native-certs = "0.4"
simple_logger = "1.11.0"

[profile.dev]
debug = true
```

### main.rs
```
use actix_web::client::{Client, Connector};
use rustls::ClientConfig;
use log::{error, info};
use simple_logger::SimpleLogger;
use std::error::Error;
use std::fs::File;
use std::io::BufReader;
use std::time::Duration;
use std::sync::Arc;

#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
    SimpleLogger::new().init().unwrap();

    let mut config = ClientConfig::new();

    let mut reader = File::open("ca-bundle.crt").map(BufReader::new)?;
    config.root_store.add_pem_file(&mut reader).unwrap();

    //config.root_store = rustls_native_certs::load_native_certs().expect("could not load platform certs");

    let rc_config = Arc::new(config);
    let client = Client::builder()
        .timeout(Duration::from_secs(30000))
        .connector(Connector::new().rustls(rc_config).finish())
        .finish();
    //let url = "https://www.rust-lang.org/";
    let url = "https://www.bing.com";
    //let url = "url of corporate network env";
    let response = client
        .get(url)
        .header("User-Agent", "actix-web/3.0")
        .send()
        .await;

    match response {
        Ok(mut res) => {
            info!("STATUS {:?}", res.status());
            let body = res.body().await;
            info!("BODY {:?}", body);
        }
        Err(e) => error!("Err: {:?}", e),
    }
    Ok(())
}
```
## 

I have do several test. The error response is `Err: Connect(Timeout)`, certs is fine. 
The code above is executable, just replace the certs and the url. My rust version was updated today, 1.48 and 1.49 didn't effect on this.
* `www.rust-lang.org` works fine.
* `www.bing.com` failed most of the times, but succeed sometimes. ping `www.bing.com` is about 70ms.
* The `corporate url` is more than 200ms latency from my PC, always failed. When I put the executable file to the server, which has an very low latency to the `corporate url`, that works fine.
* The other low latency site works fine.

* The `timeout` argument doesn't work at all. I have try several `Duration`, the `Duration::from_secs(30000)` was the last one I wrote(Seems to be insane). I tried to debug this, but I don't know what's wrong with it. The err `Err: Connect(Timeout)` occur in 1 seconds. eg.
  ```
  2021-01-18 14:21:31,233 DEBUG [rustls::anchors] add_pem_file processed 137 valid and 0 invalid certs
  ...
  2021-01-18 14:21:32,235 ERROR [ws_bd] Err: Connect(Timeout)
  ```

**Comment by fakeshadow** [comment]
Could be related
https://github.com/actix/actix-web/issues/1563#issuecomment-671202196

**Comment by Icatream** [comment]
> Could be related
> [#1563 (comment)](https://github.com/actix/actix-web/issues/1563#issuecomment-671202196)

Thanks.
I should set both connector and client timeout.

Code should be
```
let client = Client::builder()
    .timeout(Duration::from_secs(5))
    .connector(Connector::new().timeout(Duration::from_secs(5)).rustls(rc_config).finish())
    .finish();
```

**Comment by Icatream** [comment]
@fakeshadow 
Seems, client timeout is useless.
If I only set connector timeout, it also works.
Does it means client timeout didn't work as expected?

**Comment by fakeshadow** [comment]
> Seems, client timeout is useless.

The connector timeout is used at the dns lookup and tls handshake phase. The client timeout does not cover this phase of a connection.

The client timeout is used at the actual http requests. It's default to 5 seconds if you don't set it specificly. 

Anyway the naming of timeouts and/or the error information are not clear enough. Sorry about that.

**Comment by Icatream** [comment]
I got it.
It doesn't use client timeout when creating `ClientRequest`. So client timeout is unused.

**Comment by fakeshadow** [comment]
> It doesn't use client timeout when creating `ClientRequest`. So client timeout is unused.

client timeout is passed in config and used as fallback.
The timeout of ClientRequest is used to override the config timeout so you can have a different timeout for certain request.

https://github.com/actix/actix-web/blob/0c8196f8b07022e56fb4f967c26426cd3076ffdf/awc/src/sender.rs#L197

**Comment by Icatream** [comment]
> > It doesn't use client timeout when creating `ClientRequest`. So client timeout is unused.
> 
> client timeout is passed in config and used as fallback.
> The timeout of ClientRequest is used to override the config timeout so you can have a different timeout for certain request.
> 
> https://github.com/actix/actix-web/blob/0c8196f8b07022e56fb4f967c26426cd3076ffdf/awc/src/sender.rs#L197

I see.
Then I got much more confused, why connect timeout err occur when I only set client timeout?

**Comment by Icatream** [comment]
> > > It doesn't use client timeout when creating `ClientRequest`. So client timeout is unused.
> > 
> > 
> > client timeout is passed in config and used as fallback.
> > The timeout of ClientRequest is used to override the config timeout so you can have a different timeout for certain request.
> > https://github.com/actix/actix-web/blob/0c8196f8b07022e56fb4f967c26426cd3076ffdf/awc/src/sender.rs#L197
> 
> I see. Thank you
