### ISSUE TITLE
actix-web = { version = "3", features = ["rustls"] }client https not work 

### ISSUE THREAD

**Issue by wzhsh90** [actix/actix-web#1918]
actix_web: 3.3.2
os: win10 x64
    let client = Client::default();
    let response = client
        .get("https://www.baidu.com")
        .header("User-Agent", "Actix-web")
        .timeout(Duration::from_secs(10))
        .send().await.unwrap(); // <- Send http request

always  value: Connect(Timeout)

**Comment by fakeshadow** [comment]
```rust
    use actix_web::client;
    let connector = client::Connector::new()
        // connector timeout
        .timeout(std::time::Duration::from_secs(5))
        .finish();

    let client = client::Client::builder().connector(connector).finish();

    let res = client.get("https://www.baidu.com").send().await.unwrap();
```

**Comment by wzhsh90** [comment]
still not work

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', src\main.rs:141:64

**Comment by wzhsh90** [comment]
> ```rust
>     use actix_web::client;
>     let connector = client::Connector::new()
>         // connector timeout
>         .timeout(std::time::Duration::from_secs(5))
>         .finish();
> 
>     let client = client::Client::builder().connector(connector).finish();
> 
>     let res = client.get("https://www.baidu.com").send().await.unwrap();
> ```

**Comment by fakeshadow** [comment]
https://github.com/actix/actix-web/issues/1047
