### ISSUE TITLE
how to seperate router into different file

### ISSUE THREAD

**Issue by wzhsh90** [actix/actix-web#1928]
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/", web::get().to(greet))
            .route("/{name}", web::get().to(greet))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
default we can add route into main.rs ，but as team work and many routers ，all write into main.rs is not good . 
each team member should modify main.rs

is there a good way to solve the situation ?

**Comment by fakeshadow** [comment]
Seperate your app into different services. There are `Scope` and `Resource` types to help you do that. You can also write your own service type for more complicated collaborate situation where you can even outsource Services to other crates.

**Comment by wzhsh90** [comment]
I know this api , but still need to modify main.rs

use actix_web::{web, App, HttpResponse, HttpServer};

// this function could be located in a different module
fn scoped_config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/test")
            .route(web::get().to(|| HttpResponse::Ok().body("test")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    );
}

// this function could be located in a different module
fn config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/app")
            .route(web::get().to(|| HttpResponse::Ok().body("app")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    );
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .configure(config)
            .service(web::scope("/api").configure(scoped_config))
            .route("/", web::get().to(|| HttpResponse::Ok().body("/")))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}

**Comment by fakeshadow** [comment]
```rust
use actix_web::{web, App, HttpResponse, HttpServer};

// this function could be located in a different module
fn scoped_config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/test")
            .route(web::get().to(|| HttpResponse::Ok().body("test")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    );
}

// this function could be located in a different module
fn config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/app")
            .route(web::get().to(|| HttpResponse::Ok().body("app")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    )
    .service(web::scope("/api").configure(scoped_config))
    .route("/", web::get().to(|| HttpResponse::Ok().body("/")));
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().configure(config))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

**Comment by wzhsh90** [comment]
I want seperate router into different files . each file routers auto register into app .

**Comment by fakeshadow** [comment]
then just do it? the code example already showed you how to do that

**Comment by wzhsh90** [comment]
App::new()
            .configure(config)
            .service(web::scope("/api").configure(scoped_config))
            .route("/", web::get().to(|| HttpResponse::Ok().body("/")))

the example can not implment all I want.
I want to add a new router file and not modify main.rs . As you suggest that I need prepare write main.rs .

**Comment by robjtede** [comment]
There's no method to magically import routes from unspecified files.

**Comment by ZhenYisp** [comment]
Can external routes be async?
