### ISSUE TITLE
Websocket CloseCode Empty/Status is ambiguous

### ISSUE THREAD

**Issue by fuchsnj** [actix/actix-web#193]
The `CloseCode::Empty` and `CloseCode::Status` are basically the same code.

According to the RFC, if a client sends no close code (`CloseCode::Empty`) this is equivalent to 1005 (`CloseCode::Status`). This can be confusing since it might not be obvious which one of these values you should check against.

I suggest removing `CloseCode::Empty` and using an `Option::None` instead.
I would also recommend changing `CloseCode::Status` to `CloseCode::NoStatus` to reflect what it actually means.

These are both breaking changes, but if you like them I can make a PR for this.

**Comment by fuchsnj** [comment]
After thinking more... it might make sense to get rid of _both_ of these, and replace them with `Option::None`

**Comment by fafhrd91** [comment]
let's use `Option::None`, i think it makes sense.
