### ISSUE TITLE
Cannot compile actix-web-codegen

### ISSUE THREAD

**Issue by daggy1234** [actix/actix-web#1945]
## Expected Behavior

When compiling actix-web using cargo wharf with docker build kit, the crate should compile

## Current Behavior

Errors with the following message
```rust
------
 > Compiling actix-web-codegen:
#242 2.736 error[E0432]: unresolved import `proc_macro`
#242 2.736   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-codegen-0.4.0/src/lib.rs:63:5
#242 2.736    |
#242 2.736 63 | use proc_macro::TokenStream;
#242 2.736    |     ^^^^^^^^^^ help: a similar path exists: `syn::proc_macro`
#242 2.754 
#242 3.138 error: aborting due to previous error
#242 3.138 
#242 3.138 For more information about this error, try `rustc --explain E0432`.
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = Unable to build the crate => caused by: Unable to solve the graph => caused by: grpc-status: Unknown, grpc-message: "failed to build LLB: executor failed running [rustc --edition=2018 --crate-name actix_web_codegen /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-codegen-0.4.0/src/lib.rs --color never --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C metadata=a3bb0cb5e1cde293 -C extra-filename=-a3bb0cb5e1cde293 --out-dir /target/release/deps -L dependency=/target/release/deps --extern proc_macro2=/target/release/deps/libproc_macro2-d94ec969ac1bef7e.rlib --extern quote=/target/release/deps/libquote-0451cbe6c2d2830e.rlib --extern syn=/target/release/deps/libsyn-2ff5fc6c29cb0289.rlib --cap-lints allow]: runc did not terminate sucessfully"
```

## Possible Solution
 no idea but it suggests changing the import

## Steps to Reproduce (for bugs)

1) Setup Docker build kit and try and compile actix-we with cargo wharf

ex: https://github.com/Daggy1234/dagpi-auth

## Context

Its hard to compile actix web with build kit

## Your Environment

* Rust Version (I.e, output of `rustc -V`): Docker(1.48.0)
* Actix Web Version: 3.3.0

**Comment by robjtede** [comment]
Not being able to find proc_macro crate sounds like a pre- Rust v1.42 problem where an `extern crate` would otherwise be needed. Hard to say what the issue is it's definitely on v1.48.

**Comment by daggy1234** [comment]
Yeah I use rust v1.48.0 so am curious. It works fine with a normal docker build, but for some reason cargo wharf breaks it.

**Comment by JohnTitor** [comment]
> 
> 
> Yeah I use rust v1.48.0 so am curious. It works fine with a normal docker build, but for some reason cargo wharf breaks it.

Seems it uses an old cargo: https://github.com/denzp/cargo-wharf/blob/ef460f80bf8fe1b9ec95dad321a79929d67f0c45/cargo-container-tools/Cargo.toml#L12

**Comment by daggy1234** [comment]
Ohhh that explains it. I'll make a PR there to bump cargo. Thanks!
