### ISSUE TITLE
Excessive memory usage / possible leak

### ISSUE THREAD

**Issue by Davester47** [actix/actix-web#1946]
## Expected Behavior
For a very simple program, it should use a reasonable amount of RAM, and RAM usage should decrease when it's idle.

## Current Behavior
For my very simple program, it uses over 1 gigabyte if I stress test it, and it doesn't go down even after 3 hours.

## Possible Solution
Nope, unless there's a `mem::forget` somewhere.

## Steps to Reproduce (for bugs)
I tried to make the program that shows this bug as simple as possible. It will respond to any request
```Rust
use actix_web::{web, App, HttpServer};
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        App::new()
    })
    .bind("0.0.0.0:8080")?
    .run()
    .await
}
```
When you hit it with `curl`, it responds as follows:
```
$ curl -v localhost:8080
*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 0
< date: Wed, 03 Feb 2021 02:18:42 GMT
<

* Connection #0 to host localhost left intact
```

1. Compile it in release mode against actix 3.3.2.
2. Increase the number of available file descriptors: `ulimit -n 16384`
3. Stress test it using `wrk` but any other benchmark would probably work fine. I used this command: `wrk -t4 -c16k -d20s http://localhost:8080/`. This will run `wrk` with 4 threads and 16 thousand simultaneous connections for 20 seconds.
4. Watch the memory usage go up in your task manager. I used `htop`.
5. If you run `wrk` over and over, the memory will increase every time, until it reaches a little bit less than 1.1 gigabytes.

Using 1.1 gigabytes of memory to serve a page with a content-length of 0 is probably not what it's supposed to do. The memory usage does not go down afterwards, and I ran it for 3 hours without giving it any requests. If this is due to caching, like was mentioned in #1780, then it probably needs to be fixed if it is caching 1.1 gigabytes of an empty response.

## Context
I was working on a slightly more complex CRUD api, and I was noticing the memory kept going up and up. I'd like to be able to run this on a Raspberry Pi which only has 1 gigabyte of memory, but this would definitely cause it to run out. Even though this simple example stabilizes at about a gigabyte, I'm worried that a more complex program would use more memory, and even a beefier server might run out of memory.

## Your Environment
OS: Linux 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
CPU: i3-4170

* Rust Version (I.e, output of `rustc -V`): rustc 1.49.0 (e1884a8e3 2020-12-29)
* Actix Web Version: 3.3.2

**Comment by fakeshadow** [comment]
You can use https://github.com/actix/actix-web/issues/1780 as reference. Closing this for now.
