### ISSUE TITLE
Option for CamelCase headers in actix_web::HttpResponse

### ISSUE THREAD

**Issue by david6983** [actix/actix-web#1979]
I would like to return headers in CamelCase instead of lowercase only using `HttpResponse` for a project.

## Expected Behavior

The final headers should follow the syntax I choosed

## Current Behavior

The final headers are in lowercase even if I entered a CamelCase header

## Possible Solution

- Add the possibility to return CamelCase headers in HttpResponse like in the `ClientResponse` struct

## Steps to Reproduce (for bugs)

src/main.rs

```
use actix_web::{get, App, HttpServer, HttpResponse, HttpRequest};
use std::{env};
use crate::defaultheaders_custom::DefaultHeadersCustom;
use actix_web::http::ConnectionType;
use actix_http::h1::MessageType;
use actix_web::client::ClientRequest;

#[get("/")]
async fn index() -> HttpResponse {
    let mut res = HttpResponse::Ok()
        .content_type("plain/text")
        .header("Dummy", "Value")
        .body("data");

}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    env::set_var("RUST_LOG", "actix_web=debug,actix_server=info");
    env_logger::init();

    HttpServer::new(||
        App::new()
            .wrap(DefaultHeadersCustom::new()
                .header("Connection", "Keep-Alive")
                .header("caca", "dummy")
            )
            .service(index)
    )
        .bind("127.0.0.1:8006")?
        .run()
        .await
}
```

Cargo.toml

```
[dependencies]
actix-web = "3.3.2"
env_logger = "0.8"
http = "0.2.3"
actix-service = "1.0.6"
futures-util = "0.3.12"
actix-http = "2.2.0"
```

```
$ curl 127.0.0.1:8006 -v
....
< HTTP/1.1 200 OK
< content-length: 4
< content-type: plain/text
< dummy: Value
```

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.49.0-nightly (2020-11-09)
* Actix Web Version: 3.3.2

**Comment by 1c3t3a** [comment]
I would like to work on this and looked into this, but as far as I'm concerned this would require to change the general behavior of `HeaderName`, which I don't think is wanted. Currently the doc say that it only holds lowercase string values:

> `HeaderName` represents standard header names using an enum, as such they will not require an allocation for storage. All custom header names are lower cased upon conversion to a HeaderName value. This avoids the overhead of dynamically doing lower case conversion during the hash code computation and the comparison operation.

`ClientResponse` only archives reading header names as CamelCase through mocking the lowercase with the undocumented `AsName` trait.

**Comment by robjtede** [comment]
Once #2587 is released, you will be able to send camel-case headers using: `res.head_mut().set_camel_case_headers(true);`.
