### ISSUE TITLE
Add pretty-printing json helper

### ISSUE THREAD

**Issue by Fiedzia** [actix/actix-web#198]
Json does not provide any way of pretty-printing. A PrettyJson variant would be nice to have.

**Comment by fafhrd91** [comment]
i dont understand what do you want `PrettyJson` to provide. Could you elaborate

**Comment by Fiedzia** [comment]
https://github.com/actix/actix-web/blob/master/src/json.rs#L122
It want to have a way for this to call serde_json::to_string_pretty

So that I could just use PrettyJson instead of Json (or have a methof on Json to do so)

**Comment by fafhrd91** [comment]
I see, but I am not sure it should be part of actix-web.

**Comment by fafhrd91** [comment]
this should part of external library

**Comment by medwards** [comment]
I wrote:

```rust
type EitherJson<T> = actix_web::Either<Json<T>, PrettyJson<T>>;

struct PrettyJson<T>(pub T);

impl<T: Serialize> actix_web::Responder for PrettyJson<T> {
    type Item = HttpResponse;
    type Error = actix_web::Error;

    fn respond_to<S>(self, req: &HttpRequest<S>) -> Result<Self::Item, Self::Error> {
        let body = serde_json::to_string_pretty(&self.0)?;

        Ok(req
            .build_response(actix_web::http::StatusCode::OK)
            .content_type("application/json")
            .body(body))
    }
}
```

And changed my endpoint function return types and this works quite well (can vary formatting on a per-request basis if I want to).

I think it's worth including something like this in `actix_web` because before I didn't need to include `serde_json` in my manifest since `Json` abstracts it.

Like if we think `PrettyJson` belongs in an external library then `Json` is also inappropriate to include in `actix_web`, and instead in its place we'd have some kind of `SerdeType` where the user provides the serialization callback they want.

**Comment by neilyoung** [comment]
@medwards Thanks for sharing. I apologise for being a Rust noob, but could you please elaborate how you did that?

I'm stuck with

`type `Item` is not a member of trait `actix_web::Responder`
`

Using actix-web 3.1.0

**Comment by neilyoung** [comment]
Thanks or your assistance.

**Comment by neilyoung** [comment]
A very nice @robjtede enlightened me. For those of us noobs, stumbling across the same: Here is an example of how to do it. Just replace the serialization with `to_string_pretty` as above and good.

https://github.com/actix/actix-web/issues/1766#issuecomment-719743487

**Comment by MightyPork** [comment]
Here is an updated version of the implementation by @medwards as that one no longer compiles.

```rs
use actix_web::body::EitherBody;
use actix_web::error::JsonPayloadError;
use actix_web::web::Json;
use actix_web::{Either, HttpRequest, HttpResponse, Responder};
use serde::Serialize;

/// Pretty or compact Actix web JSON response
pub(crate) type EitherJson<T> = Either<Json<T>, PrettyJson<T>>;

/// Make a JSON payload, pretty or compact formatted
pub(crate) fn json_response<T: Serialize>(payload: T, pretty: bool) -> EitherJson<T> {
    if pretty {
        Either::Right(PrettyJson(payload))
    } else {
        Either::Left(Json(payload))
    }
}

/// Actix web JSON response that is pretty-printed
pub(crate) struct PrettyJson<T>(pub T);

impl<T: Serialize> Responder for PrettyJson<T> {
    type Body = EitherBody<String>;

    fn respond_to(self, _: &HttpRequest) -> HttpResponse<Self::Body> {
        match serde_json::to_string_pretty(&self.0) {
            Ok(body) => match HttpResponse::Ok().content_type(mime::APPLICATION_JSON).message_body(body) {
                Ok(res) => res.map_into_left_body(),
                Err(err) => HttpResponse::from_error(err).map_into_right_body(),
            },

            Err(err) => HttpResponse::from_error(JsonPayloadError::Serialize(err)).map_into_right_body(),
        }
    }
}
```
