### ISSUE TITLE
Allow compiling without C dependencies

### ISSUE THREAD

**Issue by jcarres-mdsol** [actix/actix-web#199]
Actix web has currently only three possible C dependencies:
Brotli which may bring Brotli-sys which is a wrapper to a C library and
Openssl which also can bring a C dependency or not
Miniz which can bring Miniz-sys.

In the case of Miniz it is possible via features to use a different Rust only backend. Although such backend is considered experimental.

Actix web already allows Brotli and openssl to be removed or use rust backends. 
If Actix web gives a way to either remove Miniz or allow it to use the Rust backend, then it will have no C dependencies and it will be easier to cross compile it by just adding and using  the target chain of the system which would run it.

**Comment by fafhrd91** [comment]
we can add `flate2-rust` feature and enable `rust_backend` backend for miniz. would you provide PR?
I'll be able to work on this issue in couple days

**Comment by jcarres-mdsol** [comment]
I'll try my best

**Comment by fafhrd91** [comment]
added two features "flate2-c" and "flate2-rust", by default "flate2-c" is enabled.

you can define actix-web dependency like this:

```toml
actix-web = { version="^0.5.5", features=["flate2-rust"], default-features = false }
```

**Comment by jcarres-mdsol** [comment]
Thank you! Definitely much more simple than what I was trying to do!
