### ISSUE TITLE
Complete static files support

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#2]
add last_modified, etag, cache-control, thread workers, sendfile, follow symlink

**Comment by fafhrd91** [comment]
use walkdir?

**Comment by AlbanMinassian** [comment]
And keep the same problems about static files as the gotham framework (issues/55)

```A significant trap that I've seen other frameworks (Rust and non Rust) fall into when dealing with static files is exposing path traversal attack vectors. OWASP has some good documentation on what this is if you've not come across it before. Not getting this right scares the crap out of me so it will need some focus.```

Ami44

**Comment by fafhrd91** [comment]
Actix checks for path traversal atack.

**Comment by fafhrd91** [comment]
I think Gotham is over complicated framework. I don’t think we should use it an example

**Comment by krircc** [comment]
@fafhrd91 I try to set a file sever like this:
```rust
extern crate actix_web;
use actix_web::*;
use std::path::{Path, PathBuf};
use actix_web::fs::NamedFile;

fn index(req: HttpRequest) -> Result<fs::NamedFile> {
    Ok(fs::NamedFile::open(Path::new("examples/index.html"))?)
}

fn parh(req: HttpRequest) -> Result<fs::NamedFile> {
    let path: PathBuf = req.match_info().query("tail")?;
    //Ok(fs::NamedFile::open(path)?)
    Ok(fs::NamedFile::open(Path::new("examples/index.html"))?)
}

fn main() {
    let sys = actix::System::new("readme");
    HttpServer::new(
        || Application::new()
            .resource("/", |r| r.f(index))
            .resource(r"/a/{tail:.*}", |r| r.method(Method::GET).f(parh))
            .handler("/", fs::StaticFiles::new("examples", true)))
        .bind("127.0.0.1:8080").unwrap()
        .start();
    println!("Started http server: 127.0.0.1:8080");
    let _ = sys.run();
}
```
my file struct:
```text
|-examples
  |-index.html
  |-style.css
  |-main.js
|-src
|-Cargo.toml
```
but when i do "http://localhost:8088/a/h"  , like js/css file can't work
![screen](https://raw.githubusercontent.com/krircc/nothing/master/2018-01-03%2016-31-36%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by AlbanMinassian** [comment]
A priori this is not an actix-web problem: js/css files are related to the html file displayed. You should probably fix the css/js path in your index. html file.

**Comment by fafhrd91** [comment]
@krircc I think your code works right. For /a/h url `parh` function get call and it always returns index.html file

**Comment by krircc** [comment]
@fafhrd91 @ami44 yes i think it's right.
I change this:
**before**
```html
<link rel="stylesheet" href="styles.css">
<script src="main.js"></script>
```
**after**
```html
<link rel="stylesheet" href="/styles.css">
<script src="/main.js"></script>
```
now it is well. I don't think this, this work well use rocket. so now I can start new SPA project use Actix. it's cool.
thanks @fafhrd91 @ami44

**Comment by fafhrd91** [comment]
Done
