### ISSUE TITLE
Compilation failure in 0.5.5 with default-features = false

### ISSUE THREAD

**Issue by mgeorgehansen** [actix/actix-web#200]
In my cargo.toml I've specified `actix-web = { version = "0.5", default-features = false }` as a dependency, and after running `cargo update` and updating to actix-web v0.5.5 I started to get compilation failures that seem to stem from the new flate2 dependency.

There are a lot of build errors in the `cargo build` command, but this one in particular is at the top:

> error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.1/src/ffi.rs:132:5
      |
132 |     extern crate miniz_sys;
      | 

It seems like one of the required backends to flate2 isn't being pulled in when default-features are excluded, and I've verified that removing `default-features = false` from my Cargo.toml config resolves the issue.

Not sure if this counts as a breaking change but it definitely caught me by surprise, and unfortunately the resulting error messages are pretty cryptic.

**Comment by fafhrd91** [comment]
You should include "flate2-rust” or “flate2-c” feature

**Comment by fafhrd91** [comment]
fixed in 0.5.6 release
