### ISSUE TITLE
actix_files::HttpRange was copied without any attribution

### ISSUE THREAD

**Issue by bancek** [actix/actix-web#2002]
I just found out that the code from my library [rust-http-range](https://github.com/bancek/rust-http-range/blob/75cc9827aa3d740392dae59b99bf69c71f65cf9f/src/lib.rs) was just ~~stolen~~ copied into `actix-web`. The code first appeared [here](https://github.com/actix/actix-web/blob/6efc3438b83497577b8d791b77c6600e95660f35/actix-staticfiles/src/lib.rs#L455) and was later moved to [range.rs](https://github.com/actix/actix-web/blob/master/actix-files/src/range.rs).

The upstream code received some performance improvements and [bug fixes](https://github.com/bancek/rust-http-range/pull/3) so if `actix-web` does not want to depend on my library it would be good to copy the latest code or at least add some attribution.

**Comment by robjtede** [comment]
Thanks for raising this. I can assure you the current maintainers were not aware of this and will take immediate steps to rectify. Either as a dependency or as attribution as needed after a review.

That code may also still be alive in various forks of actix-web which may be worth checking.
