### ISSUE TITLE
Split to a low lever http server and web part?

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#201]
Sever part is pretty isolated, should it be split to a separate crate?

**Comment by fafhrd91** [comment]
@brandur thoughts?

**Comment by brandur** [comment]
Hi @fafhrd91, this seems like a cool idea. Just for clarity: the idea would be that you have a low level HTTP server that does almost nothing beyond giving you a way to hook into handling an HTTP request right? That way you could build your own higher-level handler constructs on top of it. Then, you'd layer on the rest of `actix-web`, like the middlewares, error codes, and response helpers into a separate crate?

If possible, would you mind pointing to some of the particular source code files in the project that would probably be broken into the lower level crate? I have some familiarity with the source now, but I'm still very much a beginner! That would help me build a better picture of the proposal. Thanks!

(Made a few corrections to the above for clarity.)

**Comment by jcarres-mdsol** [comment]
Related to your question on what would that crate have inside, have you considered https://github.com/tower-rs/tower ?
I would hope the Rust ecosystem evolves towards different implementation being able to reuse those middlewares. 
You basically would get a lot of functionality maintained elsewhere and your server can focus on interfacing to that and to the rest of actix.

**Comment by fafhrd91** [comment]
this will happen as part of actix-net work
