### ISSUE TITLE
reopen: Error types don't return reason to the client.

### ISSUE THREAD

**Issue by patrickelectric** [actix/actix-web#2014]
from: https://github.com/actix/actix-web/issues/606
The issue was closed without linking PRs, without providing how and why is closed, no further documentation and information was also provided. Issues should be closed with at least a kind of reference.

**Comment by adwhit** [comment]
Note that fafhrd91 no longer works on this project and that since it has new maintainers and has changed a fair bit since 2019, it would be best just to open a new issue restating your problem.

**Comment by patrickelectric** [comment]
Well, this issue uses as reference #606, so that's what I would like to know how to accomplish. 
TLDR: actix does not answer POST methods with the wrong payload about what is incorrect.
Sending a typo inside the json or the wrong type and etc.

**Comment by BartWillems** [comment]
While Actix indeed doesn't send this info by default, here's how you can do this in your project: 

Custom error handler: https://github.com/BartWillems/rustfuif/blob/master/src/server.rs#L36
Attaching the handler: https://github.com/BartWillems/rustfuif/blob/master/src/server.rs#L95

**Comment by adwhit** [comment]
I think actix-web has the right default here. Generally you don't want to leak information to the user, it should be opt-in.

**Comment by patrickelectric** [comment]
> While Actix indeed doesn't send this info by default, here's how you can do this in your project:
> 
> Custom error handler: https://github.com/BartWillems/rustfuif/blob/master/src/server.rs#L36
> Attaching the handler: https://github.com/BartWillems/rustfuif/blob/master/src/server.rs#L95

![image](https://user-images.githubusercontent.com/1215497/108913175-628a9f80-7608-11eb-9618-07e3414bca1a.png)
