### ISSUE TITLE
Documentation method and method while using the crate, doesn't match

### ISSUE THREAD

**Issue by rishadbaniya** [actix/actix-web#2018]
Is is normal that the method name in the documentation is not same as the one during the usage.
![image](https://user-images.githubusercontent.com/54678051/108603718-ae073880-73d1-11eb-8659-d807c9b2fb78.png)
![image](https://user-images.githubusercontent.com/54678051/108603733-beb7ae80-73d1-11eb-8333-6834083ccc66.png)

From the above pic, i suppose "maxconnrate" name should be "max_connection_rate"

**Comment by robjtede** [comment]
the screenshot shows 0.7 docs

**Comment by rishadbaniya** [comment]
> the screenshot shows 0.7 docs

ohhhhhh shit... didn't see that, sorry for the trouble
