### ISSUE TITLE
add scopes / nested routes

### ISSUE THREAD

**Issue by Myaats** [actix/actix-web#202]
adding scopes / nested routes would allow you to manage your code based on the url path and is an easy way to avoid having the same path over and over again when writing resources for APIs

example: https://github.com/gotham-rs/gotham/blob/master/examples/routing/scopes/src/main.rs

**Comment by fafhrd91** [comment]
https://actix.rs/actix-web/actix_web/struct.Scope.html

**Comment by fafhrd91** [comment]
@Datamats @brandur @DoumanAsh thoughts on design?

**Comment by Myaats** [comment]
Looks great! But I think adding another function to open for creating scopes inside scopes and have them nestable would be really nice. If I remember correctly multiple web frameworks allows for this

**Comment by fafhrd91** [comment]
i agree. i already started working on scope nesting

**Comment by fafhrd91** [comment]
nested scopes get added
