### ISSUE TITLE
ARM64 macOS (11.0+, Big Sur+) - Target Support

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#2028]
## Expected Behavior
A Rust project depending on the `actix-http` crate (and its dependents, such as `actix-web`) should compile on the Tier 2 `aarch64-apple-darwin` Rust platform.

## Current Behavior
Compilation fails on ARM64 macOS (11.0+, Big Sur+).

## Possible Solution
Switch to a different implementation of Brotli which builds on ARM64 macOS (11.0+, Big Sur+), such as the [`brotli`](https://crates.io/crates/brotli) crate, Dropbox's implementation of Brotli in Rust, which should be a drop-in replacement [according to Dropbox](https://github.com/dropbox/rust-brotli/blob/master/README.md). I have not tested this.

## Steps to Reproduce (for bugs)
1. Install the Rust toolchain on an Apple M1-powered machine
2. Attempt to compile a Rust project with `actix-http` down its dependency tree

## Context
This affects one of my projects, [`dokkoo`](https://crates.io/crates/dokkoo). As a CLI tool, I intend to make my project available to users on most platforms, including the latest Apple consumer hardware. I have [GitHub Actions](https://github.com/MadeByEmil/dokkoo/actions) set up to ensure my project is building on Linux (x86_64, ARM, Debian packaging, RPM packaging), Windows (x86_64), and macOS (x86_64, ARM), and all platforms build successfully except ARM macOS.
I made [an issue](https://github.com/alexcrichton/brotli2-rs/issues/36) in the GitHub repository for the [`brotli2`](https://crates.io/crates/brotli2) crate (which Actix Web uses) back in January, with still no response; the repository seems to have seen very litte activity since late 2019 and early 2020. Having seen no help from the developer of that crate, I've made this issue, hoping to make the Actix Web developers, contributors, and community aware of this problem.
This issue does not seem to be related to #1795 (closed as @JohnTitor felt it was more appropriate to file an issue with the [`brotli-sys`](https://github.com/alexcrichton/brotli2-rs) developers); the compilation fails with messages such as `error: architecture not supported` and `error: Unsupported architecture`, so the problem is quite clear, and the solution almost as so.
I will be obtaining access to an Apple M1-powered machine sometime in March, so I will provide updates then. Hopefully, Rosetta 2 will be able to translate the x86_64 macOS binary on-the-fly, making this less of an immediate issue.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): `rustc 1.50.0 (cb75ad5db 2021-02-10)`
* Actix Web Version: [`v4.0.0-beta.3`](https://crates.io/crates/actix-web/4.0.0-beta.3)

**Comment by DoumanAsh** [comment]
Out of curiosity you could try my crate `compu-brotli-sys` which uses more recent version of brotli (specifically it targets `v1.0` branch)

Note that dropbox's library is quite slower

**Comment by ghost** [comment]
Thanks for the suggestion @DoumanAsh , I'll attempt to compile your crate once I have access to M1-powered hardware beyond a GitHub runner. This should be sometime tomorrow, or the day after, when my M1-powered MacBook Air arrives, so expect an update sometime this week or so, as promised in the original post.

In addition to your crate, I will attempt compiling (on my own machine this time, which, again, is not yet here) the pre-existing Brotli bindings used in Actix, along with Dropbox's Brotli implementation, just in-case I've fundamentally misunderstood or misdiagnosed my troubles compiling.

Again, thanks for the suggestion; I'm happy to see someone cares, even if ARM on PC isn't (yet) mainstream.

**Comment by ghost** [comment]
I may have discovered another source of the issue: the GitHub workflow I was using to compile.
Now that I have access to M1-powered hardware myself, I've attempted compilation and it … just worked.
As it turns out, the macOS GitHub runner is presently Intel-only, and compiling using `cross` doesn't change anything as there is no ARM macOS Docker container either (this could be why I am able to compile for ARM GNU + Linux but not ARM macOS). I suspect that the architecture-related errors during compilation are actually the result of an Intel-powered Mac (the GitHub Runner) attempting to compile for M1-powered Macs.

However, this new understanding may be wrong and my initial suspicions may actually be correct; perhaps Rosetta 2 is involved in the compilation somehow, and I'm not actually compiling an ARM binary on my MacBook. I'm not sure how to check for this—bear in mind that I've never used a macOS machine before until these past few days.

Could somebody more familiar with the macOS ecosystem help verify whether or not my initial bug report is mistaken? If so, apologies for the (potential) false alarm!

**Comment by kr4xkan** [comment]
I just tried to build a basic actix program on my M1 mac using your exact config and it worked flawlessly. I do not see any problem with this repo.

**Comment by robjtede** [comment]
if we can confirm the that openssl, rustls and compress features work then this can be closed

**Comment by kr4xkan** [comment]
I'm willing to help to try these features, but I'm quite new to Rust so if you have any tests written for these or sample projects I can test them ^^

**Comment by robjtede** [comment]
i think basically just running `cargo test --workspace --all-features` should do it

**Comment by kr4xkan** [comment]
Ran this command and all tests passed 👌🏽

**Comment by robjtede** [comment]
awesome, gonna close then. if anything comes up we can reopen to investigate
