### ISSUE TITLE
String-based header deprecation is a bit harsh

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#2031]
I've had code like:

```rust
resp.set_header("Cache-Control", "public, max-age=259200, stale-while-revalidate=72000, stale-if-error=72000")
```

but this is now deprecated in favor of typed headers. However, a type header requires me to alloc a `Vec<CacheDirective>` and supply the data in a raw format, which ultimately will end up serializing to the same string I already have. To me this seems like an unnecessary complication.

And `CacheDirective` doesn't even have `stale-while-revalidate` or `stale-if-error` built-in, so that's four more `String`s to allocate.

I suggest that the deprecation is premature and goes too far. I would like to continue using the simple string-based API.

**Comment by fakeshadow** [comment]
You can use `Response::with_body` and `Response::new` API for performance sensitive response building.
ResponseBuilder is mainly for ease of use rather than low overhead.

**Comment by kornelski** [comment]
But construction via typed headers isn't easier either. I much prefer inserting two strings using universal 20-year-old HTTP syntax than search docs for newly invented custom types for bits of each header.

**Comment by fakeshadow** [comment]
I don't mean ease of use by every use case would be easier. It's not possible and not what a builder API is after either.

**Comment by kornelski** [comment]
Anyway, that's just my feedback: it's slower, it's less convenient, it causes churn I find unnecessary and undesirable.

**Comment by robjtede** [comment]
Equivalent call now is: `insert_header(("name", "value"))`

**Comment by fakeshadow** [comment]
I use `Response::xxx` API exclusively in actix-web. There are overhead in `ResponseBuilder` and it's expected.
