### ISSUE TITLE
AppEntry inaccessible due to app_service being a private module

### ISSUE THREAD

**Issue by philip-peterson** [actix/actix-web#2039]
Hi there,

I was hoping to make a function that returns an `App`, but because it takes two generic types, one of which defaults to `AppEntry`, that was impossible. It would be nice if the `app_service` module was public so we can do this.

**Comment by fakeshadow** [comment]
It's possible and you don't need the `AppEntry` type. As soon as you introduce some middleware it would transform to opaque type.

```rust
use actix_service::ServiceFactory;
use actix_web::dev::{Body, ServiceRequest, ServiceResponse};
use actix_web::middleware::{Compat, Logger};
use actix_web::{get, App, Error, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| app())
        .bind("127.0.0.1:8080")?
        .run()
        .await
}

fn app() -> App<
    impl ServiceFactory<
        ServiceRequest,
        Config = (),
        Response = ServiceResponse,
        Error = Error,
        InitError = (),
    >,
    Body,
> {
    App::new()
        .wrap(Compat::new(Logger::default()))
        .service(index)
}

#[get("/hi")]
async fn index() -> &'static str {
    "Hello World!"
}
```

In general do not return an App instance unless you have a very good understanding of how to describe the complicated types App returns. It wants an opaque type that impl `ServiceFactory` trait and a `Body` generic type of response body
Instead you can use `App::configure` API to customize your app build.

**Comment by simon-an** [comment]
Your code does not compile with the latest stable release

**Comment by robjtede** [comment]
[App::configure](https://docs.rs/actix-web/3/actix_web/struct.App.html#method.configure) is the recommended solution. `app_service` is intentionally private.

**Comment by fakeshadow** [comment]
> Your code does not compile with the latest stable release

Sorry the code is for actix-web v4. For actix-web v3 there is no Compat middleware to help you figure out the body type but you can try this if you don't wrap any middleware. 
```rust
use actix_service::ServiceFactory;
use actix_web::dev::{Body, ServiceRequest, ServiceResponse};
use actix_web::{get, App, Error, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| app())
        .bind("127.0.0.1:8080")?
        .run()
        .await
}

fn app() -> App<
    impl ServiceFactory<
        Request = ServiceRequest,
        Config = (),
        Response = ServiceResponse,
        Error = Error,
        InitError = (),
    >,
    Body,
> {
    App::new().service(index)
}

#[get("/hi")]
async fn index() -> &'static str {
    "Hello World!"
}
```

This is why I said if you don't know how the types return needed to be you would have hard time to figure it out.
How you construct your App could change the returned type and it's up to you to figure that out with your own app.
