### ISSUE TITLE
`ResponseBuilder::json` requiring the argument to impl `Deref` is confusing (4.0.0-beta.3)

### ISSUE THREAD

**Issue by jplatte** [actix/actix-web#2047]
## Expected Behavior

It should be possible to use an owned value for `HttpResponse::Ok().json(<here>)`. Currently, this doesn't work, and the error message is not very helpful:

```
error[E0277]: the trait bound `MySerializableType: Deref` is not satified
```

## Current Behavior

Currently, only types implementing `Deref` can be passed to `Json`.

## Possible Solution

Only require `Serialize` again. `&T where T: Serialize` implements `Serialize` itself so that would work, otherwise requiring a reference like `serde_json::to_string` would work too (it would mean churn when you moved the value into `.json()` before, but at least give a helpful diagnostic). `AsRef<T> where T: Serialize` would work too if you want to be more generic (i.e. supporting smart pointers that don't implement `Serialize`).

## Context

Upgrading from actix-web 3.0 to 4.0.0-beta.3.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.50.0 (cb75ad5db 2021-02-10)
* Actix Web Version: `4.0.0-beta.3`

**Comment by robjtede** [comment]
The migration step for usages of passing an owned value is just to add a &. The internal call to serde_json::to_string() takes a reference. It was a clear choice to simplify API and support more use cases with 1 method. Eg passing a vec by value works because deref vec is slice which is Deserialize also.

**Comment by jplatte** [comment]
I get that I just have to add `&`, but it's not at all obvious from the error message. And in what way does this simplify the API?

**Comment by robjtede** [comment]
Before there were two methods for sending JSON: `json` and `json2`.

**Comment by jplatte** [comment]
Okay, but why were there two methods? I mentioned `Serialize` being implemented for `&T where T: Serialize`, maybe that fact was simply missed when adding `json2`?

**Comment by jplatte** [comment]
Also I'd be entirely in favor of having `json` take `&T` like `serde_json::to_string` but the current solution just leads to bad error messages and no fix suggestions (if it was `&`, migration of these would probably be as easy as `cargo fix`, now it requires manual work).

**Comment by robjtede** [comment]
perhaps it would be equivalent to take T if we impled Serialize for `Data<T>` also

**Comment by jplatte** [comment]
Yeah, if that's a thing people do why not (`ReqData` also comes to mind).

**Comment by robjtede** [comment]
the goal is one method, if it can be done like that i'm all for it
