### ISSUE TITLE
Examples for integration with tokio

### ISSUE THREAD

**Issue by dylanede** [actix/actix-web#205]
I have an existing crate built upon tokio that I want to use within a web server. It makes heavy use of tokio timers and `spawn`. There don't appear to be any examples in actix-web of how to integrate tokio-based code with the tokio event loops underpinning actix. I'm also not sure how I would go about getting a reactor handle to call spawn on in actix-web.

**Comment by ms-ati** [comment]
Yes! Same question, specifically for making AWS calls via the [Rusoto](https://github.com/rusoto/rusoto) crate, which is based on Tokio reactor as well. How can we get to run on same reactor as the Actix server?

**Comment by fafhrd91** [comment]
maybe you can get handle `Arbiter::handle()` and convert it to tokio handle?

as I understand Rusoto uses hyper 0.11, which is tokio-core based. `Arbiter::handle()` is tokio-core'a handle

**Comment by fafhrd91** [comment]
I will migrate actix to Tokio in next version. actix 0.6 and actix-web 0.7

**Comment by nayato** [comment]
@fafhrd91 is it there already in terms of maturity / stability / tuning to make the switch?

**Comment by fafhrd91** [comment]
@nayato I don’t know. But I hope with local executor we won’t loose performance. On other hand we should get some boost with simd in 1.27

**Comment by nayato** [comment]
@fafhrd91 I don't think there's anything magic about SIMD support. That is unless it is explicitly employed in HTTP parsing, unmasking WS payload, etc. Am I missing smth? :)

**Comment by fafhrd91** [comment]
you are not, but with stable simd we can start using simd :)

**Comment by vmalloc** [comment]
I'm also interested in examples on how to integrate tokio (especially tokio-proto) with actix and actix-web. If anyone has pointers or working examples that would be greatly appreciated

**Comment by fafhrd91** [comment]
for current stable 0.6 release only way to integration with tokio-core is Handle. 
Handle is available from arbiter [Arbiter::handler()](https://docs.rs/actix/0.5.7/actix/struct.Arbiter.html#method.handle)

master uses tokio, so `tokio::spawn()` and `Handle::default()` should be enough.

**Comment by rocallahan** [comment]
Unfortunately mixing actix-web 0.7 and old-tokio (`tokio-core`) crates is very hard because old/new-tokio interop depends on constructing a `tokio_core::reactor::Core`, getting a `tokio_core::reactor::Handle` and calling `new_tokio_handle()` on it to get a `tokio::reactor::Handle`. But as far as I can tell you can't start actix with just a `tokio::reactor::Handle`.

**Comment by DoumanAsh** [comment]
You're not supposed to mix old tokio at all, it would be the best to get rid of it

**Comment by rocallahan** [comment]
Sure. Unfortunately, a lot of existing crates haven't been updated to new tokio yet.

**Comment by DoumanAsh** [comment]
Maybe it is sad that these libraries are abandoned but no one has plans for actix to support `tokio-core` precisely because it is deprecated.

**Comment by rocallahan** [comment]
Yeah, that's fine.

**Comment by timglabisch** [comment]
is it fine to run actix and another tokio runtime side by side? i dont want to mix them.

**Comment by fafhrd91** [comment]
pretty obvious https://docs.rs/actix-rt/1.0.0/actix_rt/struct.System.html#method.run_in_tokio

**Comment by Alovchin91** [comment]
Is there any example on how to use `run_in_tokio`?

* `tokio::Runtime.handle()` doesn’t seem to be compatible with `LocalSet` expected in this method. What shall I use?

* What shall I do with the `Future` returned by this method?

It feels like this method’s supposed to do something different from what the documentation says.

Could you please clarify the usage? Thanks!

**Comment by thangchung** [comment]
I have seen that with new `actix-web`, we have `actix_web::rt::System::with_tokio_rt` to run the `tokio runtime`. But I haven't found any example for how to use it. Could anyone give us an example to use `actix-web` with `tokie`?

**Comment by robjtede** [comment]
See #1283.
