### ISSUE TITLE
actix_web::client was removed without notice

### ISSUE THREAD

**Issue by bugadani** [actix/actix-web#2064]
[This commit](https://github.com/actix/actix-web/commit/871ca5e4ae2bdc22d1ea02701c2992fa8d04aed7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759) removed the client reexports. The change seems completely unrelated to the commit message, there is no PR associated to it as far as I can see, and no changelog entry. What happened?

**Comment by robjtede** [comment]
removal was intentional but it was unintentionally rolled into another commit as you point out

will leave this issue open until it is documented in the changelog
