### ISSUE TITLE
Provide a blocking example for AWC

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2074]
I'm trying to create a simple program that fetches a URL using awc, prints the contents to stdout and exits. However, I cannot get it to work - I'm getting various obscure errors from the depths of tokio, such as `thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`'`. So far I could not get it to work.

There seems to be no examples in the awc/ directory, and the snippets on docs.rs are very incomplete - they don't show the imports and other boring but crucial stuff.

Here's what I've tried, for reference:
Blocking `main()` via `futures::executor::block_on`: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/c9ea74ea2fe5613c25b8d46ff179c8c4664de3ef/awc-smoke-test/src/main.rs
Async `main()` via `#[tokio::main]` annotation: https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/6b063272f154003e83249ce2f46897e89fc1498e/awc-smoke-test/src/main.rs

**Comment by robjtede** [comment]
the client example is under the -web repo still:
https://github.com/actix/actix-web/blob/master/examples/client.rs

**Comment by fakeshadow** [comment]
The readme example in awc should be working.(The header method is outdated in latest awc but removing it would be still working)

**Comment by Shnatsel** [comment]
I got my code working based on the example under actix-web as well as a version adapted from the README. Turns out the docs are there, I just failed to locate them. Thanks for the help!
