### ISSUE TITLE
Update tokio to 1.0?

### ISSUE THREAD

**Issue by rodya-mirov** [actix/actix-web#2080]
Hello,

I am doing my quarterly review of my project's dependencies and I've noticed that actix-web is still using tokio 0.2, while most of the other dependencies in the ecosystem have updated to tokio 1 or higher. I'm a bit nervous about keeping two incompatible versions of tokio running in my process at the same time, since (iirc) due to semver incompatibilities, they can't share a tokio runtime.

I also understand that upgrading from 0.2 to 1.0 is not a trivial project by any means, even for a simple project (which actix is not). Is there any plan in the medium term to do this upgrade? I searched open issues, but didn't see anything.

**Comment by robjtede** [comment]
existing beta versions are on tokio v1

**Comment by rodya-mirov** [comment]
Thanks for quick reply!

Is there a sense that it's soon, or far away? I don't know actix's release candence.

I only ask because I'm trying to decide if I should do the work to update other dependencies and leave actix-web on an incompatible tokio, then update in several months; or if I should wait for the new actix-web and do it all at once.

Thanks again,
Richard

**Comment by robjtede** [comment]
I would say try the beta, there are not many breaking changes remaining. We are definitely less than several months away from a stable release.

**Comment by rodya-mirov** [comment]
Sounds great, I'll get a branch ready that updates, if only to see the scope of the changes. For better or worse, I can't deploy the beta branch to production (organizational policy) but I'll check out the changes.

Thanks!
