### ISSUE TITLE
URL parameters not being decoded.

### ISSUE THREAD

**Issue by cedws** [actix/actix-web#209]
I have a basic project using `actix-web`, with a route, accepting a URL parameter named `url`.
When I call this route by requesting `http://localhost:8080/%2F`, the parameter is not decoded, and remains as "%2F" instead of "/".

```rust
server::new(|| App::new().resource("/{url}", |r| r.with(process)))
    .bind("0.0.0.0:8080")
    .unwrap()
    .start();
```
...
```rust
// RETURNS "%2F" NOT "/"
let url = req.match_info()
    .get("url")
    .unwrap();
```

**Comment by fafhrd91** [comment]
decoding `/` would change uri path, actix-web does not decode `/` and this is explicit decision.

**Comment by cedws** [comment]
@fafhrd91 Could we discuss this before closing please? I have been using `actix-web` for a month or so now, and back when I first implemented it into the project, this feature was working. 

Parts of a URL element with a "%" followed by two hexadecimal digits is intended to be decoded as text. It should not change the route of the URL itself. This is standard across all web frameworks I've used.

Has `actix-web` removed this feature because it wants users to do this decoding themselves?

Thanks.

**Comment by fafhrd91** [comment]
problem with decoding `/`, it changes semantics. same for `+`.

**Comment by fafhrd91** [comment]
I think original behavior was wrong

**Comment by cedws** [comment]
@fafhrd91 I see. I've just switched my project over to use query parameters instead which is decoded correctly. I would prefer to use URL parameters but I respect that it may be difficult.

**Comment by fafhrd91** [comment]
you can manually do percent decoding.

 something like `/path/{url}`
```
use percent_encoding::percent_decode;

fn index(data: Path<(String,)>) -> Result<HttpResponse> {
    let url = percent_decode(data.0)?;
    ....
}
```

#182

**Comment by cedws** [comment]
@fafhrd91 It's definitely a possible workaround. I see that you introduced a fix in #182, but I guess that the issue still persists. Please look into getting it working if you have the time :smile:. Thank you.

**Comment by fafhrd91** [comment]
what issue?

**Comment by fafhrd91** [comment]
#182 is properly fixed https://github.com/actix/actix-web/blob/master/tests/test_handlers.rs#L152

**Comment by cedws** [comment]
@fafhrd91 From what I can see, #182 is referring to the same issue as I am. The `%2F` expansion into `/` causing routes to not match has been fixed, but the problem of not being able to use encoded characters in URL parameters still exists.

**Comment by fafhrd91** [comment]
I need test case. #182 introduced new Url type which decode percent encoding of utf8 symbols except `/+`

**Comment by cedws** [comment]
@fafhrd91 Ah yes, sorry, my bad. All characters *appear* to be getting decoded, except `/` and `+`, but I need to be able to have `/` decoded for my use case.

**Comment by fafhrd91** [comment]
example I posted above should work

**Comment by cedws** [comment]
@fafhrd91 Yes, but it's a workaround. Ideally `actix-web` should be able to do it standalone. I feel that excluding `/` and `+` from decoding is also inconsistent/unexpected behavior. I'm sure it must be possible to decode all characters.

**Comment by vimpunk** [comment]
Having the same issue, would be good to get `/` and `+` decoded as text without changing the route.
