### ISSUE TITLE
awc panics if redirected to an IP address (not a DNS name) when using rustls

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2100]
## Expected Behavior
No way for the remote server to induce a panic in the actix-web HTTP client.

## Current Behavior
On some websites, e.g. terbit21.wtf, awc panics with the following error:

> terbit21.wtf:thread 'main' panicked at 'rustls currently only handles hostname-based connections. See https://github.com/briansmith/webpki/issues/54: InvalidDNSNameError', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-tls-3.0.0-beta.4/src/connect/ssl/rustls.rs:91:14

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test terbit21.wtf`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

**Comment by fakeshadow** [comment]
Thanks for reporting. It seems this is an upstream issue from webpki.
Would the correct behavior here by returning the error message instead of panic? Or is there a way to work around the limiation.

**Comment by robjtede** [comment]
> Expected Behavior
> No way for the remote server to induce a panic in the actix-web HTTP client.

I read this as it should be an error. I think if we do that then we will automatically get support for the IP based hosts when webpki starts supporting it.
