### ISSUE TITLE
awc: "Payload reached size limit" error on 6% of websites

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2101]
## Expected Behavior
awc being able to successfully download the websites that work with curl and Firefox.

## Current Behavior
On some websites, e.g. http://thenaic.org, awc fails with the following error:

> Payload reached size limit.

61771 websites out of the top million are affected. List of all affected websites: [payload-size-reached-domain-list.txt.gz](https://github.com/actix/actix-web/files/6179134/payload-size-reached-domain-list.txt.gz)

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test thenaic.org`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

**Comment by fakeshadow** [comment]
Thanks for the detailed test report.

The default upper limit for `response.body()` API was 256kb so it could be the reason some sites failed.
This limit can be changed with `response.body().limit(<usize>)` API.
