### ISSUE TITLE
awc: "Invalid Header provided" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2103]
## Expected Behavior
awc being able to successfully download the websites that work with curl and Firefox.

## Current Behavior
On some websites, e.g. http://omegasports.com, awc fails with the following error:

> Invalid Header provided

184 out of the top million websites are affected. List of all affected websites: [awc-invalid-header.txt.gz](https://github.com/actix/actix-web/files/6179208/awc-invalid-header.txt.gz)

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test omegasports.com`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

**Comment by robjtede** [comment]
related to https://github.com/seanmonstar/httparse/issues/88

**Comment by fakeshadow** [comment]
Can confirm. At least for the site mentioned in issue it's an error generated by `httparse` crate. I'm not sure about the other 183 and may need some test on them. But in general the error source of invalid header name/value would be from it.
