### ISSUE TITLE
awc: "Invalid URL: Missing URL scheme" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2105]
## Expected Behavior
awc being able to successfully download the websites that work with curl and Firefox.

## Current Behavior
On some websites, e.g. http://erepairables.com, awc fails with the following error:

> Invalid URL: Missing URL scheme

57 out of the top million websites are affected. List of all affected websites: [awc-missing-url-scheme.txt.gz](https://github.com/actix/actix-web/files/6179242/awc-missing-url-scheme.txt.gz)

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test erepairables.com`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

**Comment by fakeshadow** [comment]
Just looked into this site. The reason of this error is it returns status for redirect but does not offer Location header so the redirect service can not parse a valid url. Error message could be improved to describe it better.

**Comment by mohsen-alizadeh** [comment]
Since `Location` header is not mandatory on redirect responses, I handled it in my PR
