### ISSUE TITLE
awc: "protocol error: unexpected internal error encountered" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [actix/actix-web#2107]
## Expected Behavior
awc being able to successfully download the websites that work with curl and Firefox.

## Current Behavior
On some websites, e.g. http://extradom.pl, awc fails with the following error:

> protocol error: unexpected internal error encountered

35 out of the top million websites are affected. List of all affected websites: [awc-protocol-internal-error.txt.gz](https://github.com/actix/actix-web/files/6179296/awc-protocol-internal-error.txt.gz)

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Shnatsel/rust-http-clients-smoke-test`
2. `cd rust-http-clients-smoke-test/awc`
3. `cargo build --release`
4. `target/release/awc-smoke-test extradom.pl`

## Context
I am testing a bunch of HTTP clients on the top million websites according to the [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L).

## Your Environment
Linux, Ubuntu 20.04 LTS

* Rust Version (I.e, output of `rustc -V`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
* Actix Web Version: awc 3.0.0-beta.3

**Comment by mohsen-alizadeh** [comment]
If you try `curl -L http://extradom.pl` you will get the same error. I guess a misconfiguration in the server-side causes this error

**Comment by Shnatsel** [comment]
Hmm, indeed, `curl` fails here. Firefox and Chromium work, however.

**Comment by dalton-oliveira** [comment]
@Shnatsel The issue is that this site doesn't return `Content-Length` header. You are using `awc = {version = "3.0.0-beta.3"}` which limits max length to `256 KB` and most current version limits to it's `2 MiB`. Just update to latest version and tests runs fine
