### ISSUE TITLE
actix_files : easy default file

### ISSUE THREAD

**Issue by lovasoa** [actix/actix-web#2115]
## Expected Behavior

It would be nice being able to write 

```rust
App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_handler(actix_files::NamedFile::open("./static/index.html")))
```

or even

```rust
App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_file("index.html"))
```

## Current Behavior
Currently, one has to write 

```rust
    HttpServer::new(|| {
        App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_handler(|req: ServiceRequest| {
                        let (http_req, _payload) = req.into_parts();

                        async {
                            let response = actix_files::NamedFile::open("./static/index.html")?.into_response(&http_req)?;
                            Ok(ServiceResponse::new(http_req, response))
                        }
                    }))
```

Unless there is a better way to serve an SPA ? I didn't find it in the docs.

## Context

It is common to to have Single-Page Applications where some of the routing is done on the client-side. In that case, one wants to always serve the index page, whatever the requested route. Currently, doing so is more complex and verbose than it could be (except if I missed something in the documentation...).

**Comment by onelson** [comment]
Maybe I'm missing something subtle in your setup, but it seems to me like what you're asking for already works? I've got this in one of my 3.x apps today:

```rust
  // snip ...
    HttpServer::new(move || {
        let static_dir = static_dir.clone();
        App::new()
            .wrap(Logger::default())
            // snip...
            .service(actix_files::Files::new("/", static_dir).index_file("index.html"))
    })
    .bind("0.0.0.0:7878")?
    .run()
    .await
```

In my case, my static dir points to a webpack build directory.

Edit: I will add, adding the default file like this doesn't cover cases where you're doing history manipulation for client-side routing. You'd need something more elaborate for that. Something to check if the requested path exists or not, then serve up the `index.html` as a fallback.

**Comment by lovasoa** [comment]
> `            .service(actix_files::Files::new("/", static_dir).index_file("index.html"))`

This does not fall back to index.html for unknown paths. The desired behavior is the one of the code snippet in *Current Behavior*

If I was not clear, the feature request is to implement ` IntoServiceFactory` for `NamedFile` so that it can be used in `default_handler`

**Comment by onelson** [comment]
Ah, so this is precisely the *"fallback to serving `index.html`'s bytes for paths that don't correspond to a file on disk"* use case. Got it! :sweat_smile: 

When I host SPAs via NGINX, I'd typically check the path against a series of static file extensions (js, css, images and so on) before offering the `index.html`'s contents as the response. I wouldn't want a missing image file in my deployment to silently become a text/html 200 response - I'd want a 404 for these cases.

I wonder if this could be achieved with guards.

**Comment by lovasoa** [comment]
# 🎊

**Comment by rthomas** [comment]
@onelson did you get anywhere investigating this with guards? I'd like to serve a different 404 page from the `No such file or directory (os error 2)` and have not yet been able to crack how to do it.

**Comment by onelson** [comment]
I didn't look into it yet.

**Comment by onelson** [comment]
My thought was to inspect the `RequestHead`'s `uri` field to try and only match the service if the file extension was one of a hard-coded list (much like I do in nginx).

Here's the example from the [guard docs](https://docs.rs/actix-web/3.3.2/actix_web/guard/index.html):

```rust
use actix_web::{web, http, dev, guard, App, HttpResponse};

fn main() {
    App::new().service(web::resource("/index.html").route(
        web::route()
             .guard(guard::Post())
             .guard(guard::fn_guard(|head| head.method == http::Method::GET))
             .to(|| HttpResponse::MethodNotAllowed()))
    );
}
```

So, in theory we could write something like:

```rust
 .guard(guard::fn_guard(|head| head.uri.path().ends_with(/* ... */)))
```

**Comment by Lejla94** [comment]
Hello, new to rust!!
Any solution about this?
no idea where to put the guard or anything.
Thanks
Edit: I want to redirect to index.html on every route except jpeg etc.
I am using Single Page Application (SPA) for frontend.

**Comment by Lejla94** [comment]
Hello, i have figured the way to do this.
The only problem i have is that the url ends with `/contact` and the post request ends too with `/contact`.
Thanks

My Code: 
```rust
.service(web::resource("index.html").route(
            web::route()
            .guard(guard::Post())
            .guard(guard::fn_guard(|head| head.uri.path().ends_with("/contact")))
            .to(|| HttpResponse::MethodNotAllowed())
        ))
        .service(web::resource("/contact").route(web::post().to(send_email::send_email)))
        .service(
            actix_files::Files::new("/", "./dist")
            .prefer_utf8(true)
            .show_files_listing()
            .index_file("index.html")
            .default_handler(|req: ServiceRequest| {
                let (http_req, _payload) = req.into_parts();
                
                async {
                    let response = actix_files::NamedFile::open("./dist/index.html")?.into_response(&http_req)?;
                    Ok(ServiceResponse::new(http_req, response))
                }
            })
        )
```

**Comment by eburghar** [comment]
Note that you can perfectly change the status code of the NamedFile response and you should if you want to serve a 404.html page in default_handler

```rust
let mut response = actix_files::NamedFile::open("./dist/404.html")?.into_response(&http_req)?;
*response.status_mut() = StatusCode::NOT_FOUND;
```

I handle the SPA routes upfront the Files service, so i'm sure that the default handler is really a 404 page.
