### ISSUE TITLE
actix-web is rebuilt even when there is no change

### ISSUE THREAD

**Issue by duongdominhchau** [actix/actix-web#2130]
I saw a similar bug reported (and fixed) in 2017, but from the comment it suggests that the bug is at version 1 while we are about to jump to version 4, so I report it again here.

## Steps to reproduce

1. Create a new project
2. Add `actix-web = "3.3"` to dependencies
3.  Change `src/main.rs` to

```rs
use actix_web::{get, App, HttpServer};

#[get("/hello")]
async fn hello() -> &'static str {
    "Hello"
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(hello))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

then `cargo build` twice, the second build will rebuild some crates even when there is nothing changed. Here is what printed in my second build:

```
   Compiling proc-macro-nested v0.1.7
   Compiling typenum v1.13.0
   Compiling futures-util v0.3.13
   Compiling generic-array v0.14.4
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling actix-rt v1.1.1
   Compiling actix-service v1.0.6
   Compiling futures v0.3.13
   Compiling h2 v0.2.7
   Compiling sha-1 v0.9.4
   Compiling actix-utils v2.0.0
   Compiling trust-dns-proto v0.19.7
   Compiling actix-server v1.0.4
   Compiling actix-tls v2.0.0
   Compiling trust-dns-resolver v0.19.7
   Compiling actix-testing v1.0.1
   Compiling actix-connect v2.0.0
   Compiling actix-http v2.2.0
   Compiling awc v2.0.3
   Compiling actix-web v3.3.2
   Compiling example v0.1.0 (/home/chau/example)
    Finished dev [unoptimized + debuginfo] target(s) in 12.20s
```

## Environment
- OS: Arch
- `rustc`: Both stable (`rustc 1.51.0 (2fd73fabe 2021-03-23)`) and nightly (`rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)`).
- `actix-web` version: 3.3.2

**Comment by fakeshadow** [comment]
I can not reproduce.

```rust
First:
Finished dev [unoptimized + debuginfo] target(s) in 36.05s

Second:
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
```

**Comment by duongdominhchau** [comment]
Seem like `sccache` is what caused the unnecessary recompilation. I have just retried and found this: if my first build is with `sccache`, the second build will always recompile these crates even when `sccache` is not used anymore (I use `~/.cargo/config`).

Edit: Here is a link to the issue reported on `sccache` repo: https://github.com/mozilla/sccache/issues/828

**Comment by fakeshadow** [comment]
Good to hear. That's something new to me.
