### ISSUE TITLE
Panic! When I tried to generate pdf the second with wkhtmltopdf-rs crate 

### ISSUE THREAD

**Issue by chanhuhu** [actix/actix-web#2134]
## Expected Behavior
I expected my server not panic when I generate pdf more than once.2

## Current Behavior
Do you guys know why I got panic when I tried to create pdf from html with wkhtmltopdf-rs the second time
![image](https://user-images.githubusercontent.com/49061454/113171641-db1cf580-9271-11eb-9f62-2170e2033ad8.png)
![image](https://user-images.githubusercontent.com/49061454/113171679-e5d78a80-9271-11eb-832f-7616ec733c75.png)

## Possible Solution
I have no idea what's wrong with this.
N/A

## Steps to Reproduce (for bugs)
1.`checkout https://github.com/anowell/wkhtmltopdf-rs`
2.
3.
4.

## Context
I built the application that needed to create pdf for making the report about Photos of alteration work.
floor plan condo

## Your Environment
Arch Linux 5.11.8-arch1-1
actix-cors = { git = "https://github.com/actix/actix-extras" }
actix-files = "0.6.0-beta.3"
actix-multipart = "0.4.0-beta.3"
actix-web = "4.0.0-beta.4"
bytes = { version = "1.0.1", features = ["serde"] }
chrono = { version = "0.4.15", features = ["serde"] }
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
env_logger = "0.8.3"
futures = "0.3"
log = "0.4.14"
sanitize-filename = "0.2"
serde = "1.0.115"
serde_json = "1"
sqlx = { version = "0.5.1", default-features = false, features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
tera = { version = "1.7.0", features = ["builtins"] }
unicode-segmentation = "1.7.1"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
validator = "0.12.0"
wkhtmltopdf = "0.3.0"

* Rust Version (I.e, output of `rustc -V`):
* rustc 1.51.0 (2fd73fabe 2021-03-23)
* Actix Web Version:
* actix-web = "4.0.0-beta.4"

**Comment by robjtede** [comment]
this is not an actix web issue, try the issue tracker for the pdf lib you're using
