### ISSUE TITLE
how to debug actix-web?

### ISSUE THREAD

**Issue by videni** [actix/actix-web#2147]
I wana show a backtrace for a request,  for example, somehow my handler never got executed, the frontend simpley got 400 error, but I want to know why 400 returned ? can I add a breakpoint to the place returned 400?  how can I debug it?  for advance programer, locating problem is  one of the most essential skills.

In order to know why this happened, it seem that  I need to read all source code of actix-web.

**Comment by arniu** [comment]
Install [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) and [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) in your VSCode, then you can add breakpoints and debug the app.

**Comment by JohnTitor** [comment]
Seconded @arniu's suggestion. I'm going to close this as this is a question about the Rust program itself rather than an actix-web one.
