### ISSUE TITLE
examples/json does not work with http/2

### ISSUE THREAD

**Issue by Lingli05** [actix/actix-web#215]
**Tested the examples/json using the following curl commands:**

1. curl --verbose -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/

2. curl --verbose -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/mjsonrust

3. curl --verbose -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/manual

4. curl --verbose -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/extractor

**Everything worked as expected. However adding --http2-prior-knowledge to the above commands would trigger failure:**
1. curl --verbose --http2-prior-knowledge -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/>

2. curl --verbose --http2-prior-knowledge -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/mjsonrust

3. curl --verbose --http2-prior-knowledge -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/manual

4. curl --verbose --http2-prior-knowledge -d '{"name":"value1", "number":100}' -H "Content-Type: application/json" -X POST http://localhost:8080/extractor

**I was hoping index_mjsonrust() and index_manual() would work with http/2, but saw the following after dumping req in each function:**

index_jsonrust_
HttpRequest HTTP/2.0 POST:/mjsonrust
  headers:
    "user-agent": "curl/7.58.0"
    "accept": "*/*"
    "content-type": "application/json"
    "content-length": "31"

ERROR 2018-05-08T21:12:31Z: actix_web::pipeline: Error occured during request handling: user error: release capacity too big
 INFO 2018-05-08T21:12:31Z: actix_web::middleware::logger: 127.0.0.1:37984 [08/May/2018:17:12:31 -0400] "POST /mjsonrust HTTP/2.0" 500 0 "-" "curl/7.58.0" 0.000642

**Comment by fafhrd91** [comment]
could you try master?

**Comment by fafhrd91** [comment]
Please, reopen if you still see same behavior

**Comment by Lingli05** [comment]
Tested and it worked well now. Highly appreciated!

**Comment by fafhrd91** [comment]
fix is part of 0.6.1 release
