### ISSUE TITLE
Possible regression in 0.6 beta

### ISSUE THREAD

**Issue by Legorooj** [actix/actix-web#2165]
## Expected Behavior
- actix app compiles and runs

## Current Behavior
```
error[E0277]: the trait bound `Files: HttpServiceFactory` is not satisfied
  --> src\main.rs:51:22
   |
51 |             .service(Files::new("/static", STATIC_DIR))
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpServiceFactory` is not implemented for `Files`

error: aborting due to previous error
```

## Solution
- downgrade `actix-files` to `0.5`

## Steps to Reproduce (for bugs)
1. Run https://github.com/actix/examples/blob/master/basics/static_index/src/main.rs with actix-files `0.6.0-beta.4`.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.53.0-nightly (7af1f55ae 2021-04-15)
* Actix Web Version: 3

If this is a duplicate etc, my apologies. I did some searching, couldn't find any info RE this.

**Comment by fakeshadow** [comment]
Use the example as it is. This include it's `Cargo.toml`.

actix-files 0.6 beta depend on actix-web v4 beta. You can use `https://crates.io/crates/actix-files/0.6.0-beta.4/dependencies` or `cargo tree` command to check your dep version.

**Comment by Legorooj** [comment]
Ah, makes sense it depends on v4 beta. Apologies for wasting your time.

**Comment by fakeshadow** [comment]
> Ah, makes sense it depends on v4 beta. Apologies for wasting your time.

No problem. Issues for question are welcomed.
