### ISSUE TITLE
service.rs is in beta5 does not compile since ca 1 day ago

### ISSUE THREAD

**Issue by gustav3d** [actix/actix-web#2166]
service.rs is in beta5 does not compile since ca 1 day ago:

error[E0432]: unresolved import `actix_service::pipeline_factory`
  --> /home/gustavt/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.5/src/service.rs:13:21
   |
13 | use actix_service::{pipeline_factory, IntoServiceFactory, Service, ServiceFactory};
   |                     ^^^^^^^^^^^^^^^^ no `pipeline_factory` in the root

**Comment by fakeshadow** [comment]
Add `actix-service = "=2.0.0-beta.5"` to your `Cargo.toml`

**Comment by gustav3d** [comment]
But i'm using the Master branch,  setting the service to "2.0.0-beta.5" will conflict with its  actix-service = "2.0.0"

**Comment by gustav3d** [comment]
But when trying the non Master, it still fails with same error when using :
actix-web = "4.0.0-beta.5"
actix-service = "2.0.0-beta.5"

**Comment by fakeshadow** [comment]
notice the "=" before version

Use patch session correctly if you want to depend on git. You can take a look at the patch session(Not all of them are needed for override though).
https://github.com/actix/actix-web/blob/5747f8473689b46bb46d6ad9c314263cc59680fa/Cargo.toml#L113

**Comment by gustav3d** [comment]
Thanks.

**Comment by fakeshadow** [comment]
You are welcome. I would suggest you stick with this for a bit longer.
```
actix-web = "4.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
```

Next actix-web beta version should be soon be published which would address the actix-service build problem
