### ISSUE TITLE
Could not document `trust-dns-resolver`.

### ISSUE THREAD

**Issue by adals** [actix/actix-web#217]
[dependencies]
actix-web="0.6.1"

cargo doc then

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable

warning: [trust_dns_proto::SecureClientHandle] cannot be resolved, ignoring it...

error: Could not document `trust-dns-resolver`.

**Comment by fafhrd91** [comment]
Try `cargo doc —-no-deps`

**Comment by adals** [comment]
it will not produce docs for actix-web right?

**Comment by fafhrd91** [comment]
it will produce actix-web docs, but it won't produce docs for dependencies

**Comment by adals** [comment]
tested not produce actix-web

Win8:my_app aaa$ cargo doc --no-deps
    Checking nodrop v0.1.12
...
...
   Compiling unicase v2.1.0
   Compiling actix_derive v0.2.0
   Compiling actix-web v0.6.1
    Checking encoding-index-tradchinese v1.20141219.5
....
.....
   Compiling actix v0.5.6
 Documenting my_app v0.1.0 ()
warning: [cfg] cannot be resolved, ignoring it...

    Finished dev [unoptimized + debuginfo] target(s) in 5m 56.06s

**Comment by fafhrd91** [comment]
if you need actix-web docs, then just clone actix-web repo and run `cargo doc --no-deps` in it

**Comment by fafhrd91** [comment]
you may also try `cargo doc -p actix-web`

**Comment by adals** [comment]
ok thanks

**Comment by adals** [comment]
FYI cargo doc -p actix-web did not work
error: Could not document `trust-dns-resolver`.

anyway i will clone it , thanks again

**Comment by adals** [comment]
FYI after clone it
cargo doc did not work

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable

warning: [trust_dns_proto::SecureClientHandle] cannot be resolved, ignoring it...

error: Could not document `trust-dns-resolver`.

but cargo doc --no-deps works very well
