### ISSUE TITLE
The trait bound `HttpResponseBuilder: ResponseError` is not satisfied

### ISSUE THREAD

**Issue by jplatte** [actix/actix-web#2173]
Hi! Just wanted to figure out whether this is a deliberate change or an accidental one. It's not mentioned in `CHANGES.md`.

## Expected Behavior

Up to 4.0.0-beta.5, I could do this in a function returning `actix_web::Result`:

```rust
let something = something_fallible.map_err(|e| {
    debug!("something_fallible failed: {}", e);
    HttpResponse::InternalServerError()
})?;
```

## Current Behavior

The pattern above doesn't work anymore since `HttpResponseBuilder` doesn't implement `ResponseError`. It seems like adding `.finish()` also doesn't help. Am I supposed to switch to the new `BaseHttpResponse` type?

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.51.0 (2fd73fabe 2021-03-23)
* Actix Web Version: 4.0.0-beta.6

**Comment by robjtede** [comment]
Yeah it's sort of accidental, I was rushing that beta release and have made a mess of error types. Recommend stay on beta 5 for now and pin anything that's broken. Sorry for this.

**Comment by jplatte** [comment]
Hm, is this working as intended? I think I read that somewhere, but it wasn't communicated *here*, yet the issue was closed.

**Comment by robjtede** [comment]
Good point. So the deal now is that response errors are required to have a cause/reason attached, so `HttpResponse` and `HttpResponseBuilder` no longer implement `ResponseError` by design. There are and will be more instances of this being important going forward.

Using response error types from the `error` module is the easiest way to migrate.

**Comment by martinmckenna** [comment]
how do I pass json to `actix_web::error::ErrorBadRequest` after converting? previously I was doing:

```
HttpResponse::BadRequest().json(web::Json(error))
```

but now passing `web::Json(BadPayload { error : "something went wrong" })` gives me:

```
`BadPayload` doesn't implement `std::fmt::Display`
the trait `std::fmt::Display` is not implemented for `BadPayload`
in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
```

**Comment by jplatte** [comment]
@martinmckenna I wouldn't recommend commenting on years-old, *possibly*-related issues. Your question seems more likely to receive an answer in the [Q&A](https://github.com/actix/actix-web/discussions/categories/q-a) section.
