### ISSUE TITLE
Allow non-destructive access to a request/payload of a ServiceRequest

### ISSUE THREAD

**Issue by andy128k** [actix/actix-web#2175]
## Expected Behavior
Expose references (mutable references) to a request and a payload of a ServiceRequest.

## Current Behavior
`ServiceRequest` allows to get a request and a payload by invoking `into_parts` method. But this method consumes a `ServiceRequest`.

## Possible Solution
1. Add getters (mutable getters).
2. Make fields public.

## Context
A middleware may have a need to access a request (or a payload) by a borrowed reference to A `ServiceRequest`.
Related issues: https://github.com/actix/actix-web/pull/2168 https://github.com/actix/actix-web/pull/1821

**Comment by ilyvion** [comment]
I really don't understand why it was decided to only add a `parts_mut` and not also a `parts`. I'm in a situation where I have a `&ServiceRequest` and I can't find any (non-UB) way of getting a hold of the inner `&HttpRequest`.

**Comment by aliemjay** [comment]
> I really don't understand why it was decided to only add a `parts_mut` and not also a `parts`. I'm in a situation where I have a `&ServiceRequest` and I can't find any (non-UB) way of getting a hold of the inner `&HttpRequest`.

This quite reasonable. Please consider opening another issue that covers `ServiceResponse` as well.
