### ISSUE TITLE
Wrong doc for http HeaderMap::get_all

### ISSUE THREAD

**Issue by plagerweij** [actix/actix-web#2179]
A code example for [`HeaderMap::get_all`](https://docs.rs/actix-http/2.2.0/actix_http/http/header/struct.HeaderMap.html#examples-11) uses a nonexistent `GetAll::iter` method, because somehow it refers to the example from the [http](https://docs.rs/http/0.2.1/src/http/header/map.rs.html#753-761) crate.

949d14ae2b78ca7d9d81af27d216b0cb4d3bcd7e seems to have added a correct doc comment example.

**Comment by robjtede** [comment]
This is fixed in master.

**Comment by plagerweij** [comment]
That's strange, because the [docs.rs](https://docs.rs/actix-http/3.0.0-beta.6/actix_http/http/header/struct.HeaderMap.html#examples-11) entry for actix-http v3.0.0-beta.6 still uses the same wrong example and wrong reference to the http crate.

**Comment by robjtede** [comment]
indeed, it was fixed in #2171 which has not had a release yet

See https://actix.rs/actix-web/actix_http for rendered master branch docs.

**Comment by plagerweij** [comment]
Thanks. I must have missed that.

**Comment by robjtede** [comment]
No worries, it was pretty confusing due to some overlapping glob imports.
