### ISSUE TITLE
Macro-based routes for missing services shouldn't be silently accepted

### ISSUE THREAD

**Issue by a3kov** [actix/actix-web#2187]
Currently one can make a noob mistake, by forgetting to include view function as `service(func)`. Actix-web will accept macro-configured route for the function even if it doesn't have corresponding service.
The framework could instead do one of the following:
- refuse to run the app, as this configuration could be considered invalid
- run, but issue a warning that a route is configured but not active due to missing service. This is similar to hints Rust itself issues in cases where it's obvious that no formal error happened but it's likely the developer meant something else.

**Comment by a3kov** [comment]
As a note, coming from outside-of-rust world, I would prefer to be able to enable services on the spot using a separate new macro or an option of existing macros, so that if I don't need to configure these services in any way, it would reduce boilerplate. But I understand such a feature may require a community discussion and could be difficult/impossible to implement.

**Comment by ibraheemdev** [comment]
I see the sentiment here, but I think this is impossible, the route has no way of knowing whether it was registered as a service. Does the compiler not output `dead_code` warnings?

**Comment by robjtede** [comment]
We try to make sure there isn't too much *magic* in Actix Web. I understand that different ecosystems have more tolerance for magic, especially Ruby and Java in my experience. We probably won't ever try to implement this sort of auto route linking for that reason.
