### ISSUE TITLE
"httpresponse future error"

### ISSUE THREAD

**Issue by a1ph** [actix/actix-web#2194]
Our logs showing a number of these "httpresponse future error" messages. Hence two questions:

1. What's going wrong?
2. Should it be a `log::error!` instead of `eprintln!`?

I believe it is coming from #2065 
https://github.com/actix/actix-web/blob/24415e2fbf7a8256d4a310efab83cdc055e1aa95/src/response.rs#L294

Thanks,
-alph

**Comment by Ten0** [comment]
Still present on master at https://github.com/actix/actix-web/blob/c17662fe39523ce4230234004c572618932be2c7/src/response/builder.rs#L425

**Comment by robjtede** [comment]
This was just missed when stripping out debug logging. Nothing is wrong and it'll be gone in next release. Thanks for flagging.
