### ISSUE TITLE
Impossible to test request handler that requires HttpRequest directly

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#2198]
I'm unsure if it's really in the scope of `actix-web` to support this, but I have found it very convenient that for very focused tests, you generally don't have to create a web server. You can instead create all the different arguments to the request handler (Data etc) and pass them to it. In fact I find it rather beautiful that you can basically emulate your whole application (whose state across request handlers reside in `Data` wrappers), without starting any web server.

However, I found that once I added `req: HttpRequest` to parameters of a function, this was not possible anymore, as you can't create a `HttpRequest` for testing purposes. Would you consider fixing this?
Alternatively, of course, I could make an "inner" request handler that takes as argument whatever I want to extract out of the `HttpRequest` instead of the `HttpRequest` itself. Feel free to close if it's a "won't fix".

**Comment by ibraheemdev** [comment]
[You can create a `TestRequest` and call `to_http_request` on it.](https://docs.rs/actix-web/3.3.2/actix_web/test/struct.TestRequest.html)

**Comment by Ploppz** [comment]
Thanks!
