### ISSUE TITLE
Unable to use custom error message, Actix expects `actix_web::BaseHttpResponse<actix_web::dev::Body>` ?

### ISSUE THREAD

**Issue by mdennyh** [actix/actix-web#2208]
I use "actix-web = "4.0.0-beta.5" and have no problem a week ago. 
Today, after installing some new crate, the actix-web throws an error in `ResponseError` trait. I use custom error message to handle errors in actix.

## Expected Behavior
This usually works: 

```
impl ResponseError for CustomError {
    fn status_code(&self) -> StatusCode {
        match *self {
            Self::FieldNotFound => StatusCode::INTERNAL_SERVER_ERROR,
            Self::NotFound => StatusCode::NOT_FOUND,
        }
    }
  
   // error on this function implementation
    fn error_response(&self) -> HttpResponse {
        let status_code = self.status_code();
        let error_response = ErrorResponse {
            code: status_code.as_u16(),
            message: self.to_string(),
            error: self.name(),
        };
        HttpResponse::build(status_code).json(error_response)
    }
}
```

## Current Behavior
It complaints that I need to use `BaseHttpResponse<Body>`. I do not know how to use it. What's it and how to you use it ?

```
method `error_response` has an incompatible type for trait
expected struct `actix_web::BaseHttpResponse`, found struct `actix_web::HttpResponse`
expected fn pointer `fn(&libraries::items::error_handler::CustomError) -> actix_web::BaseHttpResponse<actix_web::dev::Body>`
found fn pointer `fn(&libraries::items::error_handler::CustomError) -> actix_web::HttpResponse`rustc(E0053)
```

## Steps to Reproduce (for bugs)
1. I'm using this example of a custom error response from the website [this page](https://actix.rs/docs/errors/)
2.  and using the actix-web = "4.0.0-beta.5" 

## Your Environment
windows 10. Rust version 1.51
actix-web = "4.0.0-beta.5"

**Comment by robjtede** [comment]
Go back to beta 5 for now. Just put = before the version in your cargo toml.

**Comment by mdennyh** [comment]
I found the solution. Use this in the Cargo.toml file. I think I need to stick with this for a while until 4.0 release
```
actix-web = "4.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
```

[SOURCE](https://github.com/actix/actix-web/issues/2166)
