### ISSUE TITLE
actix  client bug,  can't run it on another function.

### ISSUE THREAD

**Issue by jerrytry1** [actix/actix-web#2210]
Hi, I take a simple example code to connect to my http server.  It works find. post method works successful, I got my index.php query.  

case 1  successful.
```
#[macro_use] extern crate serde_derive;
use actix_web::client::Client;
use actix_web::{App, Result, http};
use actix_web::client::ClientRequest;
use http::header;
#[actix_web::main]
async fn main() {
    
   
       let mut client =Client::default();
    println!("stuck here \n");
      let response = client.post("http://10.100.20.34:1000/index.php?querybbb=aaa")
      .header("X-TEST", "value")
     .header("User-Agent", "actix-web/3.0")
     .send()     // <- Send request
     .await;     // <- Wait for response
}
```

Above code works correctly, no bug.

However, after I put them into an async function 

case 2.   failed. 
```
async fn connect(){
       
       let mut client =Client::default();
   println!("stuck here \n");
    let response = client.post("http://10.100.20.34:1000/index.php?querybbb=aaa")
    .header("X-TEST", "value")
    .header("User-Agent", "actix-web/3.0")
    .send()     // <- Send request
    .await;     // <- Wait for response
}

async fn main(){
      block_on(connect()); //Will not work. It will not post my request
     //futures::join!(connect());// will not work block at the same place. 

}
```

From the wireshark, running the above code will connect to ip 10.100.20.34:1000, but it is not send post request,   http://10.100.20.34:1000/index.php?querybbb=aaa

Not only client.post,     client.put, client.get,   is not working  as expected

How to solve it, am I made mistakes? thanks.

**Comment by jerrytry1** [comment]
I am using  
toml="0.3"
serde_derive = "0.9

**Comment by robjtede** [comment]
If you're using `block_on` from async-std or `futures::executor` then that will not work. `awc` uses Tokio.

**Comment by jerrytry1** [comment]
Thanks
