### ISSUE TITLE
actix-web hanging after a few hours

### ISSUE THREAD

**Issue by pka** [actix/actix-web#222]
After a few hours, my actix-web application is hanging. HTTP request are hanging and SIGTERM has no effect. It's serving an iCal document using diesel/MySQL/r2d2 the same way as the diesel/sqlite example. It was only reproducable with Thunderbird as client which differs from a curl request:

curl request:
```
DEBUG 2018-05-14T15:29:34Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-05-14T15:29:34Z: actix_web::middleware::logger: xx.xxx.xx.xx:52600 [14/May/2018:17:29:34 +0200] "GET /ics?user_id=3 HTTP/1.1" 200 5452 "-" "curl/7.47.0" 0.071867
DEBUG 2018-05-14T15:29:34Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-05-14T15:29:34Z: tokio_reactor: dropping I/O source: 0
```

Thunderbird request:
```
DEBUG 2018-05-14T06:40:27Z: tokio_reactor: loop process - 1 events, 0.000s
 INFO 2018-05-14T06:40:27Z: actix_web::middleware::logger: xx.xxx.xx.xx:45230 [14/May/2018:08:40:27 +0200] "GET /ics?user_id=3 HTTP/1.1" 200 5276 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.7.0 Lightning/5.4.7" 0.101101
DEBUG 2018-05-14T06:41:27Z: tokio_reactor: loop process - 1 events, 0.000s
```

Versions:
* actix-web 0.6.4
* actix 0.5.6

[Backtrace](https://github.com/actix/actix-web/files/2002288/backtrace.txt)

**Comment by fafhrd91** [comment]
I don't see anything obvious in backtrace. through it uses actix-web 0.6.0

could you join getter, so we can chat directly

**Comment by pka** [comment]
Backtrace with the requested versions:
* actix-web 0.6.4
* actix 0.5.6
* tokio-io 0.1.5
* tokio-core 0.1.12

CPU 99.3%

[backtrace.txt](https://github.com/actix/actix-web/files/2003882/backtrace.txt)

**Comment by fafhrd91** [comment]
Could you print request. Actually I need headers that thunderbird sends

**Comment by fafhrd91** [comment]
could you try master?

**Comment by fafhrd91** [comment]
0.6.5 is released
