### ISSUE TITLE
New ServiceRequest::checked_expr is useless

### ISSUE THREAD

**Issue by andy128k** [actix/actix-web#2222]
`ServiceRequest::checked_expr` consumes `self` but when error is happening `ServiceResponse` cannot be created from an error because a request was dropped by `ServiceRequest::checked_expr`.

* Actix Web Version: master

**Comment by robjtede** [comment]
Would it be enough to return `(ServiceRequest, Error)` in the error case? I have never used this method in an app so unsure which use cases it caters to.

**Comment by andy128k** [comment]
IMHO, it may be removed. In my [PR to actix-extra](https://github.com/actix/actix-extras/pull/175) I [removed](https://github.com/actix/actix-extras/pull/175/files#diff-bdc67479975f7baa175591e8435ba2878add903e5b46c4912aa22a294e59cdbaL351) it's usage without any problem.

I suppose, its role was to simplify a creation of error response. Otherwise it is not needed.

**Comment by omid** [comment]
@andy128k What's the state of this ticket?
I'm asking since it's in the actix-web v4 milestone.

**Comment by andy128k** [comment]
@omid As far as I see, nothing changed since this ticket was created.
But this should not be considered as a blocker to anything.

---

https://github.com/actix/actix-web/blob/5f412c67db4c65dba51942bd098b58acc8fae035/src/service.rs#L396-L404

Even the doc-string of this method is outdated. It does not return a response, but an error. I suggest to just remove it.

**Comment by omid** [comment]
After this change [here](https://github.com/actix/actix-web/pull/2201/files#diff-5c6f87176b7f64fbbeabbc31f5ad377edc268ebeb231eb55ee31c14ec3834f23R401). @robjtede do you remember what was the reason?
The exact commit is [this](https://github.com/actix/actix-web/pull/2201/commits/b3709d1cb1b31ccfc4e0bf8fc7fca36005eaed7b#)
