### ISSUE TITLE
Reintroduce something like request.query()

### ISSUE THREAD

**Issue by mitsuhiko** [actix/actix-web#223]
Query was recently deprecated in favor of using the `Query<T>` extractor which is typed. That's fine for a lot of cases but many others need something like a key/value iterator over the raw query parameters. I would propose to either add a helper method again that returns a pair iterator for the query or alternatively to provide a helper function to parse a query string into such an iterator.

**Comment by fafhrd91** [comment]
i just dont want to store parsed query on request object.
do you think this signature would work?

```rust
   pub fn query(&self) -> HashMap<String, String>
```

**Comment by mitsuhiko** [comment]
I was thinking the storing on the request object would be the entire point. I need that data in different layers in my case (middleware and endpoint itself) so parsing it twice seems wasteful.

**Comment by fafhrd91** [comment]
Ok, I’ll remove depreciation warning.

**Comment by fafhrd91** [comment]
done. part of 0.6.5 release
