### ISSUE TITLE
the trait `Handler<_, _>` is not implemented for `fn(actix_web::web::Json<Config>) -> impl futures::Future {create}`

### ISSUE THREAD

**Issue by simeonexo** [actix/actix-web#2231]
The code that triggers the error is
```
#[route("/config/{id}", method = "GET", method = "HEAD")]
pub async fn find(_id: web::Path<i32>) -> Result<HttpResponse, CustomError> {
    let config = Config::find().await;
    match config {
        Ok(f) => Ok(HttpResponse::Ok().json(f)),
        Err(e) => Err(CustomError::from(e)),
    }
}
```

## Expected Behavior

Code should build without error.

## Current Behavior

`cargo build` throws 
```
the trait bound `fn(actix_web::web::Path<i32>) -> impl std::future::Future {<find as HttpServiceFactory>::register::find}: Handler<_, _>` is not satisfied

  |
7 | pub async fn find(_id: web::Path<i32>) -> Result<HttpResponse, CustomError> {
  |              ^^^^ the trait `Handler<_, _>` is not implemented for `fn(actix_web::web::Path<i32>) -> impl std::future::Future {<find as HttpServiceFactory>::register::find}`
```

## Possible Solution

https://github.com/LukeMathWalker/zero-to-production/issues/96#issuecomment-826865000 suggests downgrading `actix-web`'s version to `"4.0.0-beta.5"` and below.  

Implementing trait `ResponseError` for self-defined `CustomError` would also solve the problem.
But then a more accurate error message could be directed to trait `ResponseError` than to `Handler`.

## Steps to Reproduce (for bugs)

1. set `actix-web="4.0.0-beta.6"`
2. write an async fn that returns a `Result`
3. `cargo build`

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.54.0-nightly (e4ca1662f 2021-05-22)
* Actix Web Version: "4.0.0-beta.6"

**Comment by Cightline** [comment]
I have the same problem in `4.0.0-beta.5`, and yeah I think it's related to `ResponseError` not being implemented for something, but after doing a refactor I am having a hard time figuring out what exactly is causing this.

**Comment by robjtede** [comment]
if your custom error impls ResponseError that signature should work
