### ISSUE TITLE
Server doesn't finish receiving `payload` when streaming with `reqwest`

### ISSUE THREAD

**Issue by mlodato517** [actix/actix-web#2245]
Following up on [this gitter thread](https://gitter.im/actix/actix-web?at=60b7d3fabdecf719a0943a76) I have [an example](https://github.com/mlodato517/examples/pull/1) where proxying a streaming request to
an `actix-web` server times out because the `payload` stream never completes.

## Expected Behavior
The server receives the entire `payload`.

## Current Behavior
The server never leaves the loop that's polling the `payload`.

## Steps to Reproduce (for bugs)
Reproduction steps outlined [here](https://github.com/mlodato517/examples/pull/1).

## Your Environment
Reproduced with Rust version `1.52.1` and:
1. `actix-web` 3, `reqwest` 0.10, and `tokio` 0.2
2. `actix-web` 4, `reqwest` 0.11, and `tokio` 1

**Comment by mlodato517** [comment]
So I think the `Payload` variant we're ending up with is this [`h1::Payload`](https://docs.rs/actix-http/2.2.0/actix_http/h1/struct.Payload.html#impl-Stream) and the docs mention:
> Payload does not notify current task when new data is available.

Could that be related to the issue?

**Comment by mlodato517** [comment]
Mehh probably not - I stuck some `println!`s in `readany` and, in the `hello-world` logs see:
```
[2021-06-03T13:58:05Z INFO  hello_world] Waiting for next message
Calling readonly in payload
Payload pending and waiting for more data
Calling readonly in payload
Payload had an item
Does payload need to read more? need_read=true    eof=false
[2021-06-03T13:58:05Z INFO  hello_world] Received message
[2021-06-03T13:58:05Z INFO  hello_world] Waiting for next message
Calling readonly in payload
Payload pending and waiting for more data
Calling readonly in payload
Payload pending and waiting for more data
Calling readonly in payload
Payload pending and waiting for more data
Calling readonly in payload
Payload hit end of file
[2021-06-03T13:58:15Z INFO  hello_world] Received entire payload
[2021-06-03T13:58:15Z INFO  actix_web::middleware::logger] 127.0.0.1:46100 "POST /stress_test_short.wav HTTP/1.1" 200 1 "-" "-" 10.001007
```

So it receives the data, gets the first item and then keeps waiting for more data and doesn't get it until the sender times out.

**Comment by mlodato517** [comment]
Okay so the issue might be that in my `reqwest` example I'm not proxying the content length header. [MDN notes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) that, for chunked encoding, the content length header is omitted and the end of the message is signaled by an empty chunk. It seems like, for an `actix_web` server, however, the content length is required (which should be an easy enough change on my side). Either that or `reqwest` needs to be updated to send an empty chunk after it's done transmitting the stream (and then `actix_web` would need to be updated to handle an empty chunk correctly).

That seems to match my testing - does that seem correct to anyone else?

**Comment by mlodato517** [comment]
Gonna leave this open for a while though - while I no longer have a minimally reproducible example I do still see this in production so I'll try to cook something up.

**Comment by mlodato517** [comment]
Okay I am clearly taking forever on this - I'll close this issue and re-open it if I have a reproducible example. Sorry for the spam!

**Comment by milen-denev** [comment]
Is there any news on this issue, I am stuck with it.

**Comment by milen-denev** [comment]
@mlodato517

**Comment by mlodato517** [comment]
I'm sorry, but unfortunately not. If you have a minimum reproducible example, that might help very much, though! Good luck!

**Comment by milen-denev** [comment]
> I'm sorry, but unfortunately not. If you have a minimum reproducible example, that might help very much, though! Good luck!

This issue occurred on a reverse proxy system after a certain number of requests and not immediately, but it exists.
