### ISSUE TITLE
Spawning an actix server from within a tokio application no longer works

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#2268]
In actix-web 3.x, the pattern for spawning an Actix server from within a tokio app worked pretty well:

```rust
let local = LocalSet::new();
let _sys = actix_rt::System::run_in_tokio("server", &local);
let server = ...;
local.spawn_local(server.run());
```

This worked as expected, including termination handling and all.

I'm having a hard time understanding how to achieve the same thing in actix-web 4.0.0 beta. 

Trying the above with `System::new()`(since `run_in_tokio`got removed in actix_rt 2.2) panicks, since the runtime gets dropped.

Trying something else like:
```rust
local.spawn_local(async move {
        let _sys = actix_rt::System::new();
        server.run().await
    });
 ```
Runs ok, but it seems like the actual server never binds/listens to the port and doesn't actually function.

What is the recommended way of achieving this in actix-web 4?

**Comment by robjtede** [comment]
`tokio::main` support was introduced in newer betas

**Comment by firstdorsal** [comment]
Could you maybe provide an example of how this can be achieved with the newer betas? Thank you

**Comment by robjtede** [comment]
```rust
#[tokio::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
```
