### ISSUE TITLE
Shall we rename `actix-test` to `actix-web-test`?

### ISSUE THREAD

**Issue by arniu** [actix/actix-web#2275]
And how about to rename actix-test to actix-web-test?

**Comment by JohnTitor** [comment]
I have no objection to it.

**Comment by robjtede** [comment]
I'd rather not. The plan is to consolidate `actix-http-test` into this crate too.

**Comment by arniu** [comment]
Does it support testing actix actor?

**Comment by JohnTitor** [comment]
I think "actix" here means "the actix project" rather than "the actix crate", is it confusing? We might be able to find a better name but I currently don't have a strong preference.

**Comment by robjtede** [comment]
My honest feeling is that as we disconnect Actix actors and Actix Web more, the actors part is becoming less important, especially in the current async/await climate. Eg. Post-v4 we will introduce a way to create websockets without actix. I think it's okay, therefore, to encourage `actix` = `actix web` in this way.

Open to thoughts.

**Comment by robjtede** [comment]
`actix-test` will have a slightly broader scope than just -web so I feel (even more so now that time has passed) that the name is appropriate
