### ISSUE TITLE
Handler trait does not appear in documentation

### ISSUE THREAD

**Issue by jplatte** [actix/actix-web#2279]
Currently, the `Handler` trait used for `.to()` methods is not available in the generated documentation due to being part of the private `handler` module and not re-exported from a public module. I would like to suggest having it in the documentation.

It has documentation already, which implies to me that it was actually meant to be public. My own use case for wanting to see it in the docs today was wanting to find out how actix-web manages to implement a trait for closures with different arities¹.

It might be useful to seal the trait or add `#[doc(hidden)]` to its method, to make it impossible or hard to implement the trait in downstream crates.

I'm not sure how to best go about this, otherwise I'd have opened a PR already. Should `Handler` be re-exported or the `handler` module be made public?

<details><summary>¹</summary>Turned out the trick I was initially missing was having the arguments (as a tuple) in a type parameter on the trait instead of an associated type. The latter doesn't work since the type system theoretically allows one type to implement `Fn*` for different argument lists, leading to overlapping blanket impls.</details>

**Comment by robjtede** [comment]
> Should Handler be re-exported...

We [already export it](https://github.com/actix/actix-web/blob/master/src/dev.rs#L14) under the doc-hidden `actix_web::dev::Handler`.

It seems to have been hidden for a long time so I'm not sure of the reason. I'd want to see how it is used outside Actix Web before polishing it's docs and unhiding it.

---

> It has documentation already, which implies to me that it was actually meant to be public...

Just to note: I encourage documentation of internal types just as much as public types to help onboard new developers to the project.

**Comment by ibraheemdev** [comment]
Pretty sure it was just hidden because it's more of an implementation detail than something worth exposing and committing to publicly. There's `Route::service` if someone wants a trait to implement on their custom types. I think sealing the trait and exposing it in the docs is a good idea, `Handler<_, _> not satisfied` is a pretty common error message and the docs are helpful. If only `rustc_on_unimplemented` was stable.....

**Comment by robjtede** [comment]
closed with 5860fe53814ede54d3f6939af1a457a9b9549613
