### ISSUE TITLE
Json::extract() not working as expected after calling String::extract() for the same request

### ISSUE THREAD

**Issue by mitskevich** [actix/actix-web#229]
It appears that `FromRequest::extract(&req)` call somehow changes the internal state of the request data, despite `req` reference not being marked as mutable.

Example:

```rust
extern crate actix_web;
extern crate failure;
extern crate futures;

use actix_web as aw;
use actix_web::FromRequest;
use futures::Future;

fn str_then_json(req: aw::HttpRequest) -> Box<Future<Item = String, Error = aw::Error>> {
    let fut = <String>::extract(&req).unwrap().and_then(move |body_str| {
        println!("parsed body: {}", body_str);
        <aw::Json<()>>::extract(&req)
            .and_then(move |body_json| {
                Ok(format!(
                    "request body was: {}\ndecoded json: {:?}",
                    body_str, body_json
                ))
            })
            .or_else(|e| {
                println!("error parsing json: {}", e);
                Err(e)
            })
    });
    Box::new(fut)
}

fn just_json(req: aw::HttpRequest) -> Box<Future<Item = String, Error = aw::Error>> {
    let fut = <aw::Json<()>>::extract(&req)
        .and_then(move |body_json| Ok(format!("decoded json: {:?}", body_json)));
    Box::new(fut)
}

fn main() {
    aw::server::new(|| {
        aw::App::new()
            .resource("str-then-json", |r| r.with(str_then_json))
            .resource("json", |r| r.with(just_json))
    }).bind("0.0.0.0:8080")
        .unwrap()
        .run();
}
```

Handler that only uses `Json::extract()` call returns the result I expect:

```bash
$ curl -i -H "Content-Type: application/json" -d 'null' "localhost:8080/json"
HTTP/1.1 200 OK
content-length: 22
content-type: text/plain; charset=utf-8
date: Wed, 16 May 2018 20:31:56 GMT

decoded json: Json: ()
```

But handler, that uses `String::extract()` and then `Json::extract()` returns status code `400`:

```bash
$ curl -i -H "Content-Type: application/json" -d 'null' "localhost:8080/str-then-json"
HTTP/1.1 400 Bad Request
content-length: 0
date: Wed, 16 May 2018 20:30:15 GMT
```

It fails during JSON parsing (error: `Json deserialize error: EOF while parsing a value at line 1 column 0`).

Is this the correct behaviour of `FromRequest::extract()`? If so, shouldn't its signature better be `fn extract(req: &mut HttpRequest<S>) -> ...`?

**Comment by fafhrd91** [comment]
`HttpRequest` is a `Stream`, by using `String::extract()` you consume request payload.

**Comment by mitskevich** [comment]
Thanks for the clarification! I noticed that `HttpMessage::body()` takes request by ownership, and `String::extract()` takes non-mutable reference. Also in the source code I saw that `String::extract()` makes a clone of the request... Because of that I thought that `String::extract()` somehow makes a copy of the stream, and doesn't change the request's state... But it seems I was wrong and that's not the case.

So, my question remains: shouldn't `String::extract()` take mutable reference (or even ownership) of the request, like `HttpMessage::body()` does? Or, if that's impossible, maybe the documentation for `FromRequest` trait should say that its methods may drain request's stream? The way it works now, at least for me, looks like unexpected behaviour...

Also, I'm trying to accomplish the following: I want to log all requests including their payloads to a file/DB. Do I understand correctly, that the only way to do that currently is to `extract()` the request to `String`, put it to the log, then decode JSON manually from this string and send it to the handler function?

**Comment by fafhrd91** [comment]
regarding `String::extract()` and mutable reference. main reason is ergonomics. if handler function manually extracts some data, it would require to use `mut req`. and creating custom extractor is involved process in any case.

for logging payload. yes, you have to manually deserialize json.

**Comment by mitskevich** [comment]
good to know, thanks! i'll close the issue then.
