### ISSUE TITLE
postgresql performance

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#23]
Hello - Is not an issue

I found your example diesel/postgresql added to [FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Rust/actix).

I'm surprised that you don't use[tokio-postgres](https://github.com/sfackler/rust-postgres/tree/master/tokio-postgres) or[r2d2-postgres](https://github.com/sfackler/r2d2-postgres) - Using an ORM always means sacrificing a little bit of performance for a little bit of ease. Have you ever made a performance comparison that decided on the choice of "diesel"?

Thank

**Comment by fafhrd91** [comment]
I am not so sure about performance of diesel vs tokio-postgres, in high performance situations
postgres would be a bottle neck. also r2d2 uses thread pool and I am not sure how this affect async code. sync actors use [lock-free queue](https://docs.rs/crossbeam/0.3.0/crossbeam/sync/struct.MsQueue.html)

so without numbers it is hard to tell which one is better
