### ISSUE TITLE
[awc] HTTP client should reject GET request with payload.

### ISSUE THREAD

**Issue by ArtBlnd** [actix/actix-web#2307]
## Expected Behavior

GET request should not contain any payload. it should be rejected.

## Current Behavior

GET request with payload is accepted.

## Possible Solution

reject (returns error) if GET request has payload (but still, it should check its empty stream, not by Body::Empty)

## Steps to Reproduce (for bugs)

send GET request with paylaod

## Context

Cloudfront will reject you.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.53.0 (53cb7b09b 2021-06-17)
* Actix Web Version: awc 3.0.0-beta.7

**Comment by Saruniks** [comment]
It would break functionality for people who are using GET requests with payload.

And would be too opinionated IMHO.

Personally, I would not expect GET requests with payload to be rejected.

**Comment by ArtBlnd** [comment]
No, it breaks RFCs.
in RFCs, GET **MUST NOT** contain body.
>A message-body MUST NOT be included in a request if the specification of the request method (section 5.1.1)


And on server side.
in RFCs, GET with body **SHOULD** be ignored.
> if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.

It should never be happened at all.
If you doing this at your server or client, you are doing it wrong.

https://tools.ietf.org/html/rfc2616#section-4.3

**Comment by ArtBlnd** [comment]
Also see definition of "MUST NOT" and "SHOULD" over here

https://datatracker.ietf.org/doc/html/rfc2119

**Comment by omid** [comment]
@ArtBlnd that RFC is a little bit old and there are some updates regarding that.

Anyway, as you can see in the MDN documentation, it says it's `better` to avoid it, but it's `NOT prohibited`. ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET))
```
Note: Sending body/payload in a GET request may cause some existing implementations to reject the request 
while not prohibited by the specification, the semantics are undefined. It is better to just avoid
sending payloads in GET requests.
```

Even the awesome curl does support it, check [this URL](https://requestbin.com/r/en5aj229bu5b6/1v7ahC6jOXtATO3YWLhFqkscpmc) and test it with the following command:
`curl -X GET -d "test" https://en5aj229bu5b6.x.pipedream.net`

A search leads me to [this SO](https://stackoverflow.com/questions/978061/http-get-with-request-body) question, which shows for example [Elasticsearch uses request body in GET](https://www.elastic.co/guide/en/elasticsearch/guide/current/query-dsl-intro.html).

So I would say as a client, we MUST NOT restrict users.
Even as a general server/framework, we SHOULD NOT block them to use it. :)

**Comment by ArtBlnd** [comment]
Well, than chunked encoding shouldn't be exists if there is no payload exists (even its stream)
https://github.com/http-rs/surf/issues/72
