### ISSUE TITLE
What's up with data update performance?

### ISSUE THREAD

**Issue by mkpankov** [actix/actix-web#232]
Website claims Actix is blazingly fast. However, in [data update benchmark](https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=update) it has performance of 26.6% of the top solution. Why is that?

**Comment by fafhrd91** [comment]
db benchmarks depends on diesel. Diesel does not support batch updates. But let’s wqit next test results, I added some fixes for pg benchmarks

**Comment by mkpankov** [comment]
Diesel use is mandatory, or I can use DB w/o it?

**Comment by fafhrd91** [comment]
This benchmark is limited by diesel, that is it. But you can use whatever you want.

**Comment by rofrol** [comment]
Relevant comment:

>I haven't seen much real world usage that needs to execute multiple unrelated update statements in a single round trip. If you want to optimize for that benchmark, you can pass a SQL string to connection.batch_execute (this is how migrations are run).

https://github.com/diesel-rs/diesel/issues/1517#issuecomment-361712288

**Comment by mkpankov** [comment]
Thanks for your replies

**Comment by fafhrd91** [comment]
@mkpankov https://www.techempower.com/benchmarks/#section=test&runid=60fab9eb-a5ad-49cb-aefe-24ad0f377122&hw=ph&test=update
