### ISSUE TITLE
POST request with application/x-www-form-urlencoded are parsed as GET request.

### ISSUE THREAD

**Issue by ArtBlnd** [actix/actix-web#2323]
## Expected Behavior

`POST` request with parameters should not interpreted as `GET` request.

## Current Behavior

`POST` request is parsed as `GET` request.

![image](https://user-images.githubusercontent.com/2209400/125247151-99e6b800-e32d-11eb-8d24-46fa39c578e1.png)
![image](https://user-images.githubusercontent.com/2209400/125256402-614bdc00-e337-11eb-894c-322792d1cb04.png)

![image](https://user-images.githubusercontent.com/2209400/125247054-7cb1e980-e32d-11eb-9e69-f2b4a9fefa24.png)

## Possible Solution

Do not parse `POST` request with `application/x-www-form-urlencoded` to `GET` request.

## Context

Wordpress login system uses `POST` with `application/x-www-form-urlencoded`.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.53.0 (53cb7b09b 2021-06-17)
* Actix Web Version: 4.0.0-beta.8

**Comment by robjtede** [comment]
The problem is not clear from your description. A sequence diagram or sample code would be helpful.

**Comment by ArtBlnd** [comment]
I sent `POST` request with `application/x-www-form-urlencoded` payload. but actix parses this request as `GET` with parameters

**Comment by ArtBlnd** [comment]
wait, seems this is not the real reason why `application/x-www-form-urlencoded` is interpreted to GET with parameters.
its late here so, I'll provide sample code tomorrow.

**Comment by ArtBlnd** [comment]
nevermind I just confused with two requests. 

![image](https://user-images.githubusercontent.com/2209400/125330589-f07de180-e381-11eb-8eed-000a7dcd3078.png)
