### ISSUE TITLE
the trait `actix::actor::Actor` is not implemented for `MyWs` despite all dependencies being set to `*`

### ISSUE THREAD

**Issue by banool** [actix/actix-web#2328]
I am trying to update my crates by deleting `Cargo.lock` and then building, however I am getting this error:
```
error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
   --> src/endpoints.rs:145:5
    |
145 |     type Context = ws::WebsocketContext<Self>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
    |
   ::: /Users/dport/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-3.0.0/src/ws.rs:181:8
    |
181 |     A: Actor<Context = WebsocketContext<A>>,
    |        ------------------------------------ required by this bound in `WebsocketContext`
```

My Cargo.toml looks like this:
```
actix = "*"
actix-files = "*"
actix-rt = "*"
actix-web = "*"
actix-web-actors = "*"
```

I see there was an issue that somewhat referenced this issue, but the difference between that one and what I'm reporting now, is their `Cargo.toml` locked the versions of the crates whereas mine does not. The issue: https://github.com/actix/actix-web/issues/2121. I would assume that with `*` for all the versions, it would resolve to dependencies that do not suffer this problem.

## Expected Behavior
I would expect my app to build.

## Current Behavior
I see the above bug.

## Possible Solution
Set the dependencies such that the versions don't resolve to versions that are incompatible with each other.

## Steps to Reproduce (for bugs)
I can provide a MRE if required, though I suspect the issue might be self evident from the error.

## Context
This issue stops me from upgrading actix, unless I try to manually figure out which combinations of crates works.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.53.0 (53cb7b09b 2021-06-17)
* Actix Web Version: Attempted latest

Thanks!

**Comment by realaravinth** [comment]
I would recommend against using `*` while specifying dependencies. 

I'm guessing the error is caused due to version mismatch between, `actix`, `actix-rt` and `actix-web-actors`. `actix` latest and `actix-rt` latest rely on `Tokio -v1.x` where as `actix-web-actors` relies on `actix-v10` which relies on an older `actix-rt`.

**Comment by xunilrj** [comment]
Version was the problem!

This works:

[dependencies]
actix = "0.10.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"

This give the error above:
[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
