### ISSUE TITLE
actix-multipart   not allow get params from headers

### ISSUE THREAD

**Issue by zhuxiujia** [actix/actix-web#2346]
actix-multipart   not allow get params from headers

How do I get the header data when I'm using multipart?

**Comment by robjtede** [comment]
you can access headers the same way as regular requests, [through `HttpRequest`](https://docs.rs/actix-web/3.3.2/actix_web/struct.HttpRequest.html#method.headers)

```rust
async fn hander(req: HttpRequest, form: Multipart) -> impl Responder { ... }
```

can you elaborate on your problem?

**Comment by zhuxiujia** [comment]
> you can access headers the same way as regular requests, [through `HttpRequest`](https://docs.rs/actix-web/3.3.2/actix_web/struct.HttpRequest.html#method.headers)
> 
> ```rust
> async fn hander(req: HttpRequest, form: Multipart) -> impl Responder { ... }
> ```
> 
> can you elaborate on your problem?

I try and  passed. Thank you
