### ISSUE TITLE
Add documentation on how to generate key.pem and cert.pem for tls example

### ISSUE THREAD

**Issue by greenpdx** [actix/actix-web#235]
Openssl is tricky, there are many formats and ways to create crypto material. A list of steps to create a self signed ca and key would be great.

**Comment by fafhrd91** [comment]
would you provide PR? :)  It could be part of user guide

here is how I created cert:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -sha256 -subj "/C=US/ST=CA/L=SF/O=Company/OU=Org/CN=www.example.com"
openssl pkcs12 -export -out domain.name.pfx -inkey domain.name.key -in domain.name.crt
-nodes: no passphrase
```

**Comment by greenpdx** [comment]
The first command creates the key.pem and cert.pem files with a password, and those work.  
I then did
openssl rsa -in key.pem -out nopass.pem
then copied the as key.pem in the project directory to start it with no password

How do I add it to the user guide?

thanks

**Comment by fafhrd91** [comment]
create PR for https://github.com/actix/book repo
