### ISSUE TITLE
How to use the actix router module without using macros?

### ISSUE THREAD

**Issue by sansyrox** [actix/actix-web#2354]
I saw the example of using the router here(https://github.com/actix/actix-net/blob/master/actix-router/examples/flamegraph.rs) .

Is there a possibility of adding routes without using macros?

Also, how does one access the literals being passed in the router?

Thanks in advance 😄

**Comment by robjtede** [comment]
> Is there a possibility of adding routes without using macros?

this example just uses macros to reduce boilerplate code

---

> Also, how does one access the literals being passed in the router?

Can you elborate?

**Comment by sansyrox** [comment]
> this example just uses macros to reduce boilerplate code

@robjtede , I was having difficulties understanding the macros code. No worries, as I do understand it now.

> Can you elaborate?

Yes, e.g. for the route "/users/{p1}", if a route is entered as "/users/123", how does one access the value of "123" from the router?

**Comment by robjtede** [comment]
👌 

> how does one access the value of "123" from the router?

Things have changed a bit, I'll get back to you when the next router beta is out.

(Though for now here's the master branch docs: https://actix.rs/actix-web/actix_router/struct.ResourceDef.html#method.capture_match_info)

**Comment by aliemjay** [comment]
> Yes, e.g. for the route "/users/{p1}", if a route is entered as "/users/123", how does one access the value of "123" from the router?

`Path` stores matching info:

```rust
let rdef = ResourceDef::new("/users/{p1}");
let path = Path::new("/users/123");

assert!(rdef.capture_match_info(&mut path));
let p1: &str = path.get("p1");
```

**Comment by sansyrox** [comment]
Thank you @robjtede @aliemjay ! 😄 

Also, one last question, how does one store integer in a url? Or, does one has to manually cast it?

**Comment by aliemjay** [comment]
```rust
#[derive(serde::Deserialize)]
struct PathParams {
    uid: i32,
}

let rdef = ResourceDef::new("/users/{uid}");
let path = Path::new("/users/123");

assert!(rdef.capture_match_info(&mut path));
let path_params: PathParams = path.load().unwrap();
```

It is basically this. You derive deserialize for your struct and call `Path::load`.

**Comment by sansyrox** [comment]
Got it. Thank you, @aliemjay! :smile:
