### ISSUE TITLE
Cargo audit reports old CVEs against 4.0.0-beta.8

### ISSUE THREAD

**Issue by rodya-mirov** [actix/actix-web#2358]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

Namely https://rustsec.org/advisories/RUSTSEC-2018-0019 and https://rustsec.org/advisories/RUSTSEC-2020-0048

I believe both of these issues have been resolved, but (assumedly) because of the strange version number `4.0.0-beta.8` not matching the normal `major.minor.patch` format, audit is failing and reporting that these old CVEs are still active (although I think they aren't).

I'm not really sure what's to be done (aside from release a stable version with a normal version number), but this is blocking us from using the beta version in production.

* Rust Version (I.e, output of `rustc -V`):  `rustc 1.54.0 (a178d0322 2021-07-26)`
* Actix Web Version: `4.0.0-beta.8`

**Comment by robjtede** [comment]
It's a bug in cargo audit regarding comparing pre release versions. There's nothing we can do here. If there is an exception list you can use that would be best.
