### ISSUE TITLE
Halting on Keep-Alive Sessions

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#236]
This one is a hard one to troubleshoot, as it might be an error somewhere in my code.  It appears as though there is some blocking happening somewhere with keepalive sessions after a few requests on the same tcp stream.

Unfortunately I'm seeing this in a pretty deep-seeded project, and I can try to extract the relevant parts.

## Versions tested:

Actix Web `0.6.7` & `0.6.8`

## Steps to Replicate

* Clients connect to actix-web server using Keep-Alive
* A number of initial HTTP requests/responses work OK
* Client sends a HTTP Request header & body which is appropriately formatted as confirmed by Wireshark

### Expected Result

* Client receives http response

### Actual Result

* No Response is received by the client on the wire
* No log entry for the request is seen by `middleware::logger`
* Client times out and resets connection, creating a new tcp session

Also: shutting down actix-web shows that there are active workers, even if the sockets are closed on the client side

**Comment by fafhrd91** [comment]
how easy it to reproduce this bug on your side?
is there any delay between requests?

**Comment by cetra3** [comment]
It's quite easy to reproduce, but I'd have to extract the relevant parts. 

If I add `trace` level logging I can't see anything interesting.

Is there a way to disable keepalive and see if that's the issue?

**Comment by fafhrd91** [comment]
https://actix.rs/actix-web/actix_web/server/struct.HttpServer.html#method.keep_alive

**Comment by fafhrd91** [comment]
You can also clone actix-web and manually insert prints to the server/h1.rs file

**Comment by cetra3** [comment]
Ok, a couple more observations:

* With KeepAlive turned off, this works fine
* Adding in a `debug!("Decode Payload:{:?}", src);` in `H1Decoder::decode`, I don't see the `missing` request header.
* Some requests I can see actix sending a response, even before the request body is being finished sending from the client.  In these cases the handler doesn't even bother reading the request body, but the client is still sending one.

Could it be that, if the request body isn't read, then actix will always respond immediately? If that's the case, I'm not sure whether keepalive allows that situation, I would have thought that actix should wait until the client request has been fully sent (headers + body).

**Comment by fafhrd91** [comment]
server should consume payload before reading next request even if response is already sent. i'll check.

**Comment by fafhrd91** [comment]
actually, I think server should close connection.

**Comment by fafhrd91** [comment]
could you try master

**Comment by cetra3** [comment]
That does work, but I am seeing TCP resets now, so it does drop the keep-alive tcp stream.

**Comment by fafhrd91** [comment]
you should consume payload in your handler. otherwise server could be ddosed. for example, I can send chunked request, and even for 404 response server would need to consume payload.

**Comment by fafhrd91** [comment]
I'll release new version later today or tomorrow

**Comment by cetra3** [comment]
No worries.  That makes sense.  Thanks!
