### ISSUE TITLE
actix-web: Json requires that a Content-Type is provided.

### ISSUE THREAD

**Issue by jhgg** [actix/actix-web#2361]
In 1.0, `Json` did not require that a content type was provided. This is technically "incorrect" but in the real world, we have clients that don't send the header, but do send a json body. This means that we can't use Actix 4.0 in order to service these requests.

I want to open a PR that adds the ability via `JsonConfig` to re-enable this legacy behavior. I'm thinking adding a function called `require_content_type(self, require_content_type: bool) -> Self`.

**Comment by arniu** [comment]
Use `json_cfg.content_type(|_| true)` to skip content-type checking.

**Comment by robjtede** [comment]
> Use `json_cfg.content_type(|_| true)` to skip content-type checking.

The point of this is issue is to do with [this change](https://github.com/actix/actix-web/pull/2362/files#diff-7b229864a63b2f9e26f81d52e49931eb3f81f995a3ddf547a03db3800302f8a4L331-R341). I.e., a request without Content-Type will still fail to extract JSON when `json_cfg.content_type(|_| true)` is used.

**Comment by arniu** [comment]
How about to rename the option to `content_type_required`? Then `content_type` and `content_type_required` will be displayed near to each other.

**Comment by arniu** [comment]
And we should add one like `json_data` or `json_with_content_type_unchecked` to `awc::ClientResponse`.

**Comment by jhgg** [comment]
> How about to rename the option to `content_type_required`? Then `content_type` and `content_type_required` will be displayed near to each other.


Updated #2362 with that!

**Comment by jhgg** [comment]
> And we should add one like `json_data` or `json_with_content_type_unchecked` to `awc::ClientResponse`.

Unsure what this means :( 

EDIT: Oh I see, `awc::ClientResponse::json` exists. You are suggesting adding a `json_with_content_type_unchecked` which circumvents https://github.com/actix/actix-web/blob/44c55dd036eb1e4adae0853267685866257dc789/awc/src/response.rs#L342-L346
