### ISSUE TITLE
How to delegate handling of request to actix actor? -> Box<Future<Item...

### ISSUE THREAD

**Issue by Abendstolz** [actix/actix-web#237]
I would like to have different APIs e.g. one for json, one for binary etc. I can configure different endpoints just fine.

But now I would like to delegate the actual work to an actor that in turn uses actors to fulfill all the parts that are necessary in order to respond to the caller.

So I have this:

My actor:

    pub struct ProtocolWrapper {
        pub message: protocol::Message,
    }

    pub struct MyActor;

    impl Actor for MyActor {
        type Context = Context<Self>;
    }

    impl Handler<ProtocolWrapper> for MyActor {
        type Result = Result<ProtocolWrapper, ProtocolError>;

        fn handle(&mut self, msg: ProtocolWrapper, ctx: &mut Context<Self>) -> Self::Result {
            match msg.message {
                _ => unimplemented!("Handling of request not yet implemented!")
            }
        }
    }

    enum ProtocolError {
        Unhandled
    }

    impl Message for ProtocolWrapper {
        type Result = Result<ProtocolWrapper, ProtocolError>;
    }

And a handler:

    pub struct JsonHandler {
        actor: Addr<Unsync, MyActor>,
    }

    impl JsonHandler {
        pub fn new(actor: Addr<Unsync, MyActor>) -> Self {
            JsonHandler {
                actor,
            }
        }

        pub fn handle(&self, request: Json<serde_json::Value>) -> Box<Future<Item=String, Error=Error>> {
            let message: protocol::Message = serde_json::from_str(&request.to_string()).expect("Couldn't deserialize json");
            let actor_request = self.actor.send(ProtocolWrapper { message });

            Box::new(Arbiter::handle().spawn(
                actor_request.map(|res| {
                    match res {
                        Ok(result) => Ok(format! {"Response was created!"}),
                        Err(err) => Err(format! {"Something went wrong! :("})
                    }
                })
                .map_err(|e| {})
            ))
        }
    }

And the glue:

    fn main() -> () {
        let url = "localhost:8000";

        let sys = actix::System::new("test");

        Server::new(|| {
            let my_actor: Addr<Unsync, MyActor> = MyActor.start();
            let json_handler = JsonHandler::new(my_actor);

            App::new()
                .resource("api/json", move |r| r.method(http::Method::POST).with(move |req| json_handler.handle(req)))
        })
            .bind(url).expect(&format!("Cannot bind to {}", url))
            .run();
    }

But running it gives me:

> error[E0271]: type mismatch resolving `<futures::MapErr<futures::Map<actix::dev::Request<actix::Unsync, my_actor::MyActor, my_actor::ProtocolWrapper>, [closure@src/request_handlers/json.rs:35:31: 40:14]>, [closure@src/request_handlers/json.rs:41:26: 41:32]> as futures::Future>::Item == ()`
  --> src/request_handlers/json.rs:34:36
   |
34 |         Box::new(Arbiter::handle().spawn(
   |                                    ^^^^^ expected enum `std::result::Result`, found ()
   |
   = note: expected type `std::result::Result<std::string::String, std::string::String>`
              found type `()`

> error[E0277]: the trait bound `(): futures::Future` is not satisfied
  --> src/request_handlers/json.rs:34:9
   |
34 | /         Box::new(Arbiter::handle().spawn(
35 | |             actor_request.map(|res| {
36 | |                 match res {
37 | |                     Ok(result) => Ok(format! {"Response was created!"}),
...  |
41 | |                 .map_err(|e| {})
42 | |         ))
   | |__________^ the trait `futures::Future` is not implemented for `()`
   |

I can't seem to find any example how to go about this.

**Comment by fafhrd91** [comment]
this part is not covered in user guide. You need to use [HttpContext](https://actix.rs/actix-web/actix_web/struct.HttpContext.html) aa a context for you actor

**Comment by fafhrd91** [comment]
something like: 

```rust
fn index(req: HttpRequest) -> HttpResponse {
    let ctx = HttpContext::new(req, MyActor::new());

    Ok(resp.body(ctx))
}
```

**Comment by Abendstolz** [comment]
@fafhrd91 Thanks!

That means that I would have to do the parsing inside the actor, right? Because `Json<serde_json::Value>` is no longer the type of my request. (Because then again I need another layer of actors in between, that do the parsing of the appropriate structure [json, binary...])

But looks like I'll have a deeper look in the next couple of days, because out of the box I get stuff like:

>  type mismatch resolving `<my_actor::MyActor as actix::Actor>::Context == actix_web::HttpContext<my_actor::MyActor>`
  --> src/request_handlers/json.rs:36:19
   |
36 |         let ctx = HttpContext::new(request, MyActor {});
   |                   ^^^^^^^^^^^^^^^^ expected struct `actix::Context`, found struct `actix_web::HttpContext`

(Yes I saw the `MyActor::new()` in your hint)

**Comment by fafhrd91** [comment]
you need to use HttpContext in actor definition:

```rust
impl Actor for MyActor {
    type Context = HttpContext<Self>;
}
```

explain what are you trying to archive

**Comment by Abendstolz** [comment]
@fafhrd91 I am sorry, I thought I did! (Mea culpa)

I am in the middle of porting a Scala/Akka application to Rust/Actix.

That application handled protobuf (among other) formats via different endpoints.
Behind those endpoints everything was Actor driven.

So what I want is the same: I want to have my endpoints (e.g. /api/json) that gets some json data.
The endpoint prepares the data for the actor and sends it to the "main" actor (in our case this would be `MyActor`)

That actor then proceeds doing its thing (invoking other actors etc.) and at the end it returns some response to the user.

All in all not that complex, I think.

(Is it clearer now, or am I still talking in riddles? If the later, sorry, English isn't my mothertongue and maybe that's why I tend to talk my head off)

edit: With your last hint everything compiles, but the actors `handle` method never gets invoked, upon a new request. So the `JsonHandler` gets the message just fine and it also returns a response, but sadly just a 200 ok without a body.

**Comment by fafhrd91** [comment]
oh! I think I misunderstood your example. remove `Arbiter::handle().spawn(` from your original example.
just return boxed future.

**Comment by fafhrd91** [comment]
```rust
use futures::future::{ok, err};

impl JsonHandler {
    pub fn new(actor: Addr<Unsync, MyActor>) -> Self {
        JsonHandler {
            actor,
        }
    }

    pub fn handle(&self, request: Json<serde_json::Value>) -> Box<Future<Item=String, Error=Error>> {
        let message: protocol::Message = serde_json::from_str(&request.to_string()).expect("Couldn't deserialize json");
        let actor_request = self.actor.send(ProtocolWrapper { message });

        Box::new(
            actor_request.and_then(|res| {
                match res {
                    Ok(result) => ok(Ok(format! {"Response was created!"})),
                    Err(err) => err(Err(error::ErrorInternalServerError("Something went wrong! :(")))
                }
            })
        )
    }
}
```

**Comment by fafhrd91** [comment]
Reopen if you need help

**Comment by Abendstolz** [comment]
@fafhrd91 Mhm, thanks. Still trying to wrap my head around all the compiler errors I get here.

> >	error[E0271]: type mismatch resolving `<[closure@src/request_handlers/json.rs:36:36: 41:10] as std::ops::FnOnce<(std::result::Result<myActor::ProtocolWrapper, myActor::ProtocolError>,)>>::Output == std::string::String`
	  --> src/request_handlers/json.rs:36:9
	36 | /         Box::new(actor_request.map(|res| {
	37 | |             match res {
	38 | |                 Ok(result) => Ok(format! {"Response was created!"}),
	39 | |                 Err(err) => Err(error::ErrorInternalServerError("Something went wrong! :("))
	40 | |             }
	41 | |         }).map_err(|e| {})
	42 | |         )
	   | |_________^ expected (), found struct `actix_web::Error`

And at the same time:

> error[E0271]: type mismatch resolving `<futures::MapErr<futures::Map<actix::dev::Request<actix::Unsync, myActor::myActor, myActor::ProtocolWrapper>, [closure@src/request_handlers/json.rs:36:36: 41:10]>, [closure@src/request_handlers/json.rs:41:20: 41:26]> as futures::Future>::Item == std::string::String`
  --> src/request_handlers/json.rs:36:9
   |
36 | /         Box::new(actor_request.map(|res| {
37 | |             match res {
38 | |                 Ok(result) => Ok(format! {"Response was created!"}),
39 | |                 Err(err) => Err(error::ErrorInternalServerError("Something went wrong! :("))
40 | |             }
41 | |         }).map_err(|e| {})
42 | |         )
   | |_________^ expected enum `std::result::Result`, found struct `std::string::String`

**Comment by fafhrd91** [comment]
I slightly modified my previous comment

**Comment by Abendstolz** [comment]
@fafhrd91 Thanks, now there is a problem `(Err(err) => err)` is ambiguous for `err` (once a function, but also a variable)

Now I get 

> error[E0271]: type mismatch resolving `<futures::MapErr<futures::Map<actix::dev::Request<actix::Unsync, myActor::myActor, myActor::ProtocolWrapper>, [closure@src/request_handlers/json.rs:36:36: 41:10]>, [closure@src/request_handlers/json.rs:41:20: 41:26]> as futures::Future>::Item == std::string::String`
  --> src/request_handlers/json.rs:36:9
   |
36 | /         Box::new(actor_request.map(|res| {
37 | |             match res {
38 | |                 Ok(result) => ok(format! {"Response was created!"}),
39 | |                 Err(_) => err(error::ErrorInternalServerError("Something went wrong! :("))
40 | |             }
41 | |         }).map_err(|e| {}))
   | |___________________________^ expected struct `futures::FutureResult`, found struct `std::string::String`
   |
   = note: expected type `futures::FutureResult<std::string::String, actix_web::Error>`
              found type `std::string::String`
   = note: required for the cast to the object type `futures::Future<Error=actix_web::Error, Item=std::string::String>`

>error[E0271]: type mismatch resolving `<[closure@src/request_handlers/json.rs:41:20: 41:26] as std::ops::FnOnce<(actix::MailboxError,)>>::Output == actix_web::Error`
  --> src/request_handlers/json.rs:36:9
   |
36 | /         Box::new(actor_request.map(|res| {
37 | |             match res {
38 | |                 Ok(result) => ok(format! {"Response was created!"}),
39 | |                 Err(_) => err(error::ErrorInternalServerError("Something went wrong! :("))
40 | |             }
41 | |         }).map_err(|e| {}))
   | |___________________________^ expected (), found struct `actix_web::Error`
   |
   = note: expected type `()`
              found type `actix_web::Error`
   = note: required because of the requirements on the impl of `futures::Future` for `futures::MapErr<futures::Map<actix::dev::Request<actix::Unsync, myActor::myActor, myActor::ProtocolWrapper>, [closure@src/request_handlers/json.rs:36:36: 41:10]>, [closure@src/request_handlers/json.rs:41:20: 41:26]>`
   = note: required for the cast to the object type `futures::Future<Error=actix_web::Error, Item=std::string::String>`

But I don't understand where that originates and why.

**Comment by fafhrd91** [comment]
this version should compile:

```rust
use futures::future::{ok, err};

impl JsonHandler {
    pub fn new(actor: Addr<Unsync, MyActor>) -> Self {
        JsonHandler {
            actor,
        }
    }

    pub fn handle(&self, request: Json<serde_json::Value>) -> Box<Future<Item=String, Error=Error>> {
        let message: protocol::Message = serde_json::from_str(&request.to_string()).expect("Couldn't deserialize json");
        let actor_request = self.actor.send(ProtocolWrapper { message });

        Box::new(
            actor_request
                .map_err(error::Error::from)
                .and_then(|res| {
                match res {
                    Ok(result) => Ok(format! {"Response was created!"}),
                    Err(err) => Err(
                        error::ErrorInternalServerError("Something went wrong! :("))
                }
            })
        )
    }
}
```

**Comment by Abendstolz** [comment]
@fafhrd91 thanks a lot for the dedication and support. Got everything working as intended now! :)
