### ISSUE TITLE
Version was the problem! actix = "0.12.0"

### ISSUE THREAD

**Issue by ArunGust** [actix/actix-web#2388]
Version was the problem!

This works:

[dependencies]
actix = "0.10.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"

This give the error above:
[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"

_Originally posted by @xunilrj in https://github.com/actix/actix-web/issues/2328#issuecomment-890486402_

**Comment by robjtede** [comment]
actix-web-actors depends on actix 0.10
it is not semver compatible with 0.12

**Comment by ArunGust** [comment]
Thanks, Is there any plan to upgrade dependency ?

**Comment by robjtede** [comment]
The v4 beta version uses 0.12. To update it on v3 would be a breaking change.
