### ISSUE TITLE
Multiple Scopes with same path but different endpoint paths failing with 404

### ISSUE THREAD

**Issue by ivancea** [actix/actix-web#2392]
I have this configure:

```Rust
pub fn configure(server: &mut ServiceConfig) {
    server.service(
        web::scope("/item")
            .service(get_items) // #[get("")]
            .service(get_item) // #[get("/{item_id}")]
    );
    server.service(
        web::scope("/item/{item_id}")
            .service(update_stock) // #[post("/stock")]
    );
}

// Example functions

#[get("")]
async fn get_items() -> impl Responder {
    HttpResponse::Ok()
}

#[get("/{item_id}")]
async fn get_item() -> impl Responder {
    HttpResponse::Ok()
}

#[get("/stock")]
async fn update_stock() -> impl Responder {
    HttpResponse::Ok()
}
```

## Expected Behavior
Calling `POST /item/1/stock` should executoe `update_stock`

## Current Behavior
Calling `POST /item/1/stock` returns 404

## Possible Solution
I would expect it to keep trying other services if the Scope fails to handle the request. I suppose the logic just stops at the first Scope after the request passes the path test

## Steps to Reproduce (for bugs)
Add the configure code, and call a `POST /item/1/stock`.

## Context
Coming from Java-Spring, it's a possible thing to do. It's not common to share scopes, but I was trying to divide the code between modules by feature/domain (item/stock in my example), and that case would fit there.

For extra context, those `server.service()` inside that `configure` are each in their own modules, and called like:
```Rust
pub fn configure(server: &mut ServiceConfig) {
    item_endpoints::configure(server);
    stock_endpoints::configure(server);
}
```

I were refactoring the app to modularize the http things, when I found this.

## Your Environment
Windows 10 & Docker

* Rust Version (I.e, output of `rustc -V`): 1.52.0
* Actix Web Version: 4.0.0-beta.9

**Comment by robjtede** [comment]
Solution 1 (preferred):
```
	server.service(
        web::scope("/item")
            .service(get_items) // #[get("")]
            .service(get_item) // #[get("/{item_id}")]
			.service(update_stock) // #[post("/{item_id}/stock")
    );
```

~~Solution 2:~~
~~The 404 is because the *less*-specific scope service is matched first.~~
You're right this wouldn't work.
```
	server.service(
        web::scope("/item/{item_id}")
            .service(update_stock) // #[post("/stock")]
    );
	server.service(
        web::scope("/item")
            .service(get_items) // #[get("")]
            .service(get_item) // #[get("/{item_id}")]
    );
```

**Comment by ivancea** [comment]
The first solution wouldn't let me modularize those sets of requests, and the second solution would shadow the `/item/{item_id}` route of the other scope.

Was it considered to let `web::Scope` ignore the match if its services can't process the request? Of course, I can always avoid using `web::Scope`, as it only avoids to write the full path in every handler (in my usecase)

**Comment by aliemjay** [comment]
For this specific case, you can use guards to limit scopes to certain http methods:
```rust
    server.service(
        web::scope("/item")
            .guard(guard::Get())
            .service(get_items) // #[get("")]
            .service(get_item) // #[get("/{item_id}")]
			.service(update_stock) // #[post("/{item_id}/stock")
    );
```

But generally I recommend to construct `Scope` at higher module and use `Scope::configure` instead:
```rust
pub fn configure(server: &mut ServiceConfig) {
    server.service(
        web::scope("/item")
            .configure(item_endpoints::configure)
            .configure(stock_endpoints::configure)
    );
}
````

**Comment by ivancea** [comment]
Having guards would make it pretty complex, and sometimes, the same issue would emerge, as those were the first 3 endpoints, many more are to come...
But well, I see that's how Actix works, so I'll ignore scopes for now, as them doesn't fit my usecase.

Thanks!

**Comment by Wopple** [comment]
@robjtede I want to reiterate that this is an issue. In my case I have a scope, and later I have a resource with the same sub path which gets shadowed. IMO this is surprising behavior and should be changed. I have it separated out that way because I have feature flags that choose which endpoints to expose based on the build's use case.
