### ISSUE TITLE
signal not close postgresql client

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#24]
Hello 

actor do not close automatically postgresql conn after shutting down the actix-web application. 

When a start application, i mount 12 clients
```
let db_url = "postgres://postgres:azerty@localhost:5432/test";
let addr = SyncArbiter::start(num_cpus::get() * 3, move || db::DbExecutor::new(&db_url));

...

// (db.rs)
impl DbExecutor {
    pub fn new(db_url: &str) -> DbExecutor {
        DbExecutor{
            conn : match Connection::connect(db_url, TlsMode::None) {
                Err(err) => panic!("Error connecting to {} {:?}", db_url, err),
                Ok(conn) => conn
            }
        }
    }
}

```

I can count 12 clients with this sql cmd  [number-of-active-connections-and-remaining-connections](https://dba.stackexchange.com/questions/161760/number-of-active-connections-and-remaining-connections
)

```
select max_conn,used,res_for_super,max_conn-used-res_for_super res_for_normal
from
  (select count(*) used from pg_stat_activity) t1,
  (select setting::int res_for_super from pg_settings where name=$$superuser_reserved_connections$$) t2,
  (select setting::int max_conn from pg_settings where name=$$max_connections$$) t3;
```
If now i send ctrl+c, application stop (ok) and rerun sql cmd, i see always 12 connections (ko). If a rerun actix-web application i have 24 clients connections. etc.

https://github.com/actix/actix-web/issues/17 , you said ``btw usually you don't need explicit disconnect in rust, usually connections get closed on "drop"``.

What would be the solution to close also the postgresql connections after a signal ?

**Comment by fafhrd91** [comment]
could you share your code, seems like DbExecutor actor stays alive

**Comment by AlbanMinassian** [comment]
- ``git clone https://github.com/ami44/tmp-actix-web.git``
- ``vi tmp-actix-web/src/main.rs`` and edit login/password postgresql line 76
- ``cargo run``, ``ctrl+c``
- conn are not close

**Comment by AlbanMinassian** [comment]
Hello, i have updated https://github.com/ami44/tmp-actix-web.git to actix v0.4.2
and clients are now properly closed. thanks

**Comment by fafhrd91** [comment]
great!
