### ISSUE TITLE
Auto-appending trailing slash not working with scoped routes

### ISSUE THREAD

**Issue by Dowwie** [actix/actix-web#241]
Actix-web automatically appends trailing slashes for routes.  However, it doesn't for scoped routes.

[Example](https://github.com/actix/actix-website/issues/4)

GET .../project  fails where as GET .../project/ doesn't
GET .../project/{project_id}/task fails where as GET .../project/{project_id}/task/ doesn't

**Comment by fafhrd91** [comment]
i will add ability to register routes for empty resources, i.e. `.resource("", ||...)`
i dont think automatic trailing slash is good idea

**Comment by fafhrd91** [comment]
I need you to test your code. 
rules are:

## 1.
  scope: /app
  resource1: ""
  resource2: "/"

  /app - resource1
  /app/ - resource2

## 2.
  scope: /app/
  resource1: ""

  /app - not found
  /app/ - resource1

## 3.
  scope: /app/
  resource1: "/"

  /app - not found
  /app/ - not found
