### ISSUE TITLE
Should `ResponseError::error_response` accept `req`?

### ISSUE THREAD

**Issue by alex35mil** [actix/actix-web#242]
Sometimes, in `ResponseError::error_response` I need something from `req` (state/header/etc) to generate proper error response but currently it accepts only `&self`. Storing unrelated things in type seems awkward. Should `ResponseError::error_response` accept `req` the same way as it's done in `Responder::respond_to`? Or I misunderstood something and I can handle this case differently?

**Comment by fafhrd91** [comment]
You can use helper https://actix.rs/actix-web/actix_web/error/struct.InternalError.html#method.from_response

**Comment by fafhrd91** [comment]
@mitsuhiko thoughts?

**Comment by alex35mil** [comment]
If I understand it right, I still have to build responses inside handlers. If it's correct, then in my case this is something I want to abstract away and return from handler only struct w/ implemented `ResponseError`.

Also, somewhat related question about implementation of `Responder`. Is it preferable to use `ResponseError` for errors that I explicitly handle in my code or this is something that's supposed to be used only for errors that I don't handle explicitly. E.g. which variant is more idiomatic?

```rust
// Var 1
pub struct OAuthOk(pub Payload);
impl Responder for OAuthOk { ... }

pub struct OAuthErr(pub Message);
impl ResponseError for OAuthErr { ... }
impl From<MailboxError> for OAuthErr { ... }

// in handler
db.send(...).from_err().and_then(move |result| match result {
  Ok(user) => future::ok(OAuthOk(Payload { user })),
  Err(err) => future::err(OAuthErr(Message::InternalServerError)), // handled via ResponseError
})
```

```rust
// Var 2
pub enum OAuthResponse {
  Ok(Payload),
  Err(Message),
}
impl Responder for OAuthResponse { ... }

pub struct OAuthErr(pub Message);
impl ResponseError for OAuthErr { ... }
impl From<MailboxError> for OAuthErr { ... }

// in handler
db.send(...).from_err().and_then(move |result| match result {
  Ok(user) => future::ok(OAuth::Ok(Payload { user })),
  Err(err) => future::ok(OAuth::Err(Message::InternalServerError)),
})
```

In second case even if I handle almost everything via my `OAuthResponse` `Responder` I still need implementation of `ResponseError` for internal errors.

**Comment by fafhrd91** [comment]
I think we need to add `req` to `error_response`. `error::InternalError` is fine for application, but it is bad for libraries. 

regarding responder, I usually use variant 1 for quick prototype or application endpoints.
if I need re-usable code or library I prefer varian 2.

**Comment by mitsuhiko** [comment]
I'm +1 on changing this and upgrading the code should not be too bad for users.

**Comment by fafhrd91** [comment]
this actually is more complicated than I expected. 
adding `req` would prevent `impl From<Error> for HttpResponse`. for example HttpResponseBuilder uses `Into<HttpResponse>`. removing `Into<HttpResponse>` would reduce ergonomics of the api.

we could add extra `render()` method for `ResponseError` 

```rust
pub trait ResponseError: Fail {
    fn error_response(&self) -> HttpResponse;

    fn render(&self, req: &HttpResponse, resp: HttpResponseBuilder) -> HttpResponse;
}
```

or 

```rust
pub trait ResponseError: Fail {
    fn error_response(&self) -> StatusCode;

    fn render(&self, req: &HttpResponse, resp: HttpResponseBuilder) -> HttpResponse;
}
```

**Comment by fafhrd91** [comment]
I think we should switch to this trait.

```rust
pub trait ResponseError: Fail {
    fn error_response(&self) -> StatusCode;

    fn render(&self, req: &HttpResponse, resp: HttpResponseBuilder) -> HttpResponse;
}
```

it still allows to use `Into<HttpResponse>` on `Error`, but we can have separate render stage.

thoughts?

@mitsuhiko I think this can solve problem with error handlers.
@alexfedoseev

**Comment by alex35mil** [comment]
It sounds good to me!

**Comment by fafhrd91** [comment]
preferred would be separate trait for rendering errors, something like 
```rust
impl<T> JsonRenderer for T where T: ResponseError
```
and
```rust
impl<T> TextRenderer for T where T: ResponseError
````
but without specialization this is not very usable

**Comment by robjtede** [comment]
View of this issue remains that error types should contain all the information they need to generate an error.

Any further discussion should happen on a new issue in the context of Actix Web v4.
