### ISSUE TITLE
finishing response with `json(())` sends a response with a 0 byte body 

### ISSUE THREAD

**Issue by jbtrystram** [actix/actix-web#2421]
I am not sure what's the HTTP spec about that but it seems to be a grey zone. 

When sending back a HTTP Response with nothing in the body, the clients errors because the body is 0 byte. 

Here is how to trigger it, sending an `HttpResponse` :
```
 let result: Result<(), Error> = method_call();
 match result { 
 	Ok(resp) => Ok(HttpResponse::NoContent().json(resp)),
 	Err(e)   => HttpResponse::NotFound().finish(),
```

This cause cURL to error : 
```
* Excess found in a non pipelined read: excess = 4 url = /route/a/b/c (zero-length body)
* Connection #0 to host localhost left intact
```

Here is how I fixed it, because I know that `resp` will always be `()` : 
```
Ok(_) => Ok(HttpResponse::NoContent().finish()),
```

But maybe it's worth making sure that even when providing an empty input, the `json()` method will create an empty json object, or make it to not compile ? 

## Your Environment

* Rust Version : rustc 1.55.0 (c8dfcfe04 2021-09-06)
* Actix Web Version: 4.0.0-beta.8

**Comment by fakeshadow** [comment]
actix-web uses `serde_json` crate to encode json object. In this case () is encoded as "null" by it which is a valid json object with length of 4. 

Your problem here is that you are trying to send it with NoContent status code which indicated the response body should be empty but you actually have a body.

For more info please read rfc for spec of Http/1.1. https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5

**Comment by ctron** [comment]
I do understand that explanation. However, shouldn't the `NoContent` then prohibit one from passing in content? Ultimately, this combination compiles fine, can only result in a protocol error.

**Comment by fakeshadow** [comment]
~~Then please fix your issue post to reflex the situation correctly. The way you wording it is wrong and would not help for fixing.~~

Edit: Sorry was on mobile and did not see the name tag clearly. That said I would still suggest the issue be changed to a correct title. Maybe something like asking for a feature that make the ResponseBuilder more "idoit proof "/catch mistake at compile time.

**Comment by fakeshadow** [comment]
Closing for now. If further discussion of more beginner friendly ResponseBuilder is wanted please open up a new one.
