### ISSUE TITLE
Feature Request: Ability to split the .ressources definitions in multiple files.

### ISSUE THREAD

**Issue by lowlevl** [actix/actix-web#243]
I would be great to be able to make different modules for larger APIs with a basepath like:
```rust
App::new()
  .base("v1", v1mod)
  .ressource(...)
  .finish();
```

And the v1 will be accessed like `localhost:port/v1/...` with all the definitions in the *v1mod* module.

**Comment by fafhrd91** [comment]
There are two options

* [App::configure](https://actix.rs/actix-web/actix_web/struct.App.html#method.configure)
* [App::scope](https://actix.rs/actix-web/actix_web/struct.App.html#method.scope)

Does this help?

**Comment by lowlevl** [comment]
@fafhrd91, Oops, yeah, that's exactly what I searched for, sorry for bothering you !
Thanks for your crate also :+1:

**Comment by lowlevl** [comment]
Hi again @fafhrd91, I'm trying to achieve nested *.configure* + *.scope* like this:
```rust
fn handleadd(app: App) -> App{/* ... */}

fn handleroot(app: App) -> App{
  app.scope("/v1",  |s|
        s.configure(handleadd)
        .ressource("/refresh", |r| HttpResponse.Ok().body("Refresh all"))
    )
}

fn main() {
  App::new()
    .configure(handleroot)
}
```

But without success, do you have any idea how to do that ? (Because *.configure* don't exist in the Scope impl)

**Comment by lowlevl** [comment]
It could work using `Scope::nested`, with `Scope` as argument instead of `App`, but I can't find what `Type` should I pass to the `Scope<Type>` to pass it in function parameter !

**Comment by fafhrd91** [comment]
Why do you need access to the App from handleadd?

**Comment by lowlevl** [comment]
Because I need to add .ressources !

**Comment by lowlevl** [comment]
I maybe over compressed my code, but the Idea is to get nested modules like:
```
/src
|-  /api
|   |-  mod.rs
|   |-  /v1
|       |-  mod.rs
|       |-  someendpoints.rs
|       |- ...
|-  main.rs
```
I thought it would be great to do so for the maintainability of my project.

**Comment by fafhrd91** [comment]
you can register resources per scope.

check user guide https://actix.rs/docs/url-dispatch/ "Scoping routes" section

**Comment by lowlevl** [comment]
What I'm trying to do now is:
```rust
fn main() {
  App::new()
        .scope("/v1", v1handler) // Import the v1 API.
}

fn v1handler(s: Scope) -> Scope {
    s.resource("/blah", |_| HttpResponse::Ok())
}
```

**Comment by lowlevl** [comment]
But what If I don't want to register resources inline but in another function ?

**Comment by fafhrd91** [comment]
I don't understand. you can pass scope to function.
my concern is access to app instance from scope configuration function

**Comment by lowlevl** [comment]
Forget about the App instance, It should work with scope but I can't pass Scope to a function, look:
```
error[E0243]: wrong number of type arguments: expected 1, found 0
 --> src/api/v1/mod.rs:5:26
  |
5 | pub fn root(a: Scope) -> Scope {
  |                          ^^^^^ expected 1 type argument

```

**Comment by fafhrd91** [comment]
join getter chat, it is easier to chat online about this question

**Comment by lowlevl** [comment]
Link please ?

**Comment by fafhrd91** [comment]
```rust
fn root<S: 'static>(a: Scope<S>) -> Scope<S> {}
```

https://gitter.im/actix/actix

**Comment by lowlevl** [comment]
Okay, sorry for flooding the issue, no need to go to the Gitter, I'll join it if I need further assistance, this fixed my issue, I'm just beginning Rust and I was a bit confused.
Thanks
