### ISSUE TITLE
file upload Bug.

### ISSUE THREAD

**Issue by zhangwuqiao** [actix/actix-web#2438]
First of all, I'm not sure whether it's a bug or because it's a beta problem that hasn't been solved yet.

pub async fn upload(req: HttpRequest, form: web::Payload, mut payload: Multipart, db: web::Data<Pool>) -> ApiResult {

}

“Mut payload: multipart” cannot be passed in when uploading files.
Error reported:

error[E0277]: the trait bound `Multipart: FromRequest` is not satisfied
  --> src\appconfig.rs:80:54
   |
80 |         .route("/com_attachment/upload", web::post().to(attachment::upload))
   |                                                      ^^ the trait `FromRequest` is not implemented for `Multipart`
   |
   = note: required because of the requirements on the impl of `FromRequest` for `(HttpRequest, actix_web::web::Payload, Multipart, actix_web::web::Data<deadpool::managed::Pool<Manager>>)`

vscode report error:
   .route("/com_attachment/upload", web::get().to(attachment::upload))  

the trait bound `Multipart: FromRequest` is not satisfied
required because of the requirements on the impl of `FromRequest` for `(HttpRequest, actix_web::web::Payload, Multipart, actix_web::web::Data<deadpool::managed::Pool<Manager>>)`rustcE0277
error: the trait bound `Multipart: FromRequest` is not satisfied
label: the trait `FromRequest` is not implemented for `Multipart`
note: required because of the requirements on the impl of `FromRequest` for `(HttpRequest, actix_web::web::Payload, Multipart, actix_web::web::Data<deadpool::managed::Pool<Manager>>)`
label: the trait `FromRequest` is not implemented for `Multipart`

In Actix web 3, examples can be used normally, but there are some problems in Actix web 4.0.0-beta.10.
examples/forms/multipart
examples/forms/multipart-async-std
examples/forms/multipart-s3

Compilation errors in these projects:
    the trait `FromRequest` is not implemented for `Multipart`

Or is a new method used to handle file upload, but there is no sample code yet?

Thank you very much for your efforts and selfless dedication to the society!

**Comment by fakeshadow** [comment]
examples in `actix/example` should be used as is including their `Cargo.toml`.
beta releases are not targeted by examples and breaking changes are expected. Sorry about this but it's just impossible to keep all examples update with latest development so they always target recent stable release.

**Comment by fakeshadow** [comment]
There is not much material on migration. The best I can think of is to dig into the `CHANGES.md` in actix-web and actix-multiplart. And check the documentation on `doc.rs` also helps.

**Comment by zhangwuqiao** [comment]
thank you!
