### ISSUE TITLE
JWT authentication in actix-web 4.0.0

### ISSUE THREAD

**Issue by gcomte** [actix/actix-web#2455]
I'm trying to build use a JWT-based authentication into actix-web, based on [this tutorial](https://auth0.com/blog/build-an-api-in-rust-with-jwt-authentication-using-actix-web/).

When I copy all the code from the tutorial, the tutorial works just fine. However, the project I use the authentication for does not use `actix-web 2.0.0` as the tutorial, but `actix-web 4.0.0-beta.4` instead.

Using this version of actix web, the project does not compile anymore.

The compiler is unhappy with the following code:

```rust
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
    
        let auth = HttpAuthentication::bearer(validator);
    
        App::new()
            .wrap(auth)
            .route("/users", web::get().to(handlers::get_users))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}

async fn validator(req: ServiceRequest, credentials: BearerAuth) -> Result<ServiceRequest, Error> {
    // implementation
}
```

I receive the following compiler errors:

![Selection_473](https://user-images.githubusercontent.com/8024734/142770819-e464cae2-2c0c-4a69-93d3-669c065b78fb.png)

![Selection_474](https://user-images.githubusercontent.com/8024734/142770823-a9517f02-3248-4e05-a754-5b1ded4bb0b1.png)

Should authentication be done differently in version 4.0.0 ?

**Comment by ghost** [comment]
it's likely that you're using a prelease actix-web "4.0.0" with a stable release of actix-web-httpauth 
Try using `actix-web-httpauth = "0.6.0-beta.4"`  instead of stable release.

**Comment by gcomte** [comment]
Oh yes, that solves my issue, thanks for the hint!
