### ISSUE TITLE
Improve naming in the cookie API

### ISSUE THREAD

**Issue by LukeMathWalker** [actix/actix-web#2460]
`HttpResponse` currently provides two state-changing methods for cookies:

- `add_cookie`;
- `del_cookie`.

Based on the naming, I'd expect `add_cookie` to add a `Set-Cookie` header that matches the cookie I passed as argument, while `del_cookie` would add a `Set-Cookie` header with `max-age` equal to 0 to unset the cookie.

That's not what happens though: our intuition is right for `add_cookie`, but it fails us on `del_cookie`, which is instead designed to remove a cookie that was previously added via `add_cookie`.

Possible ways forward:

- (backward-compatible) provide an `unset_cookie` method, while documenting the difference between `add_cookie` and `del_cookie`;
- (backward-incompatible) reshape the cookie API to expose a mutable container, therefore removing the need for `del_cookie`, while exposing an `unset_cookie` method to set removal cookies.

**Comment by robjtede** [comment]
I've noticed that `HttpResponseBuilder::del_cookie`, which does operate on a `CookieJar` will produce removal cookies. These same-name methods should have the same behavior.
