### ISSUE TITLE
Unable to serve nested files with .service(Files::new("/", "./data/web"))

### ISSUE THREAD

**Issue by Zageron** [actix/actix-web#2464]
## Expected Behavior
I should be able to serve files nested in folders.

## Current Behavior
I cannot serve files nested in folders. I get the following output in all browsers.
`can not parse "style.css" to a u32`

## Steps to Reproduce (for bugs)
```rust
// Error handler for a 404 Page not found error.
fn not_found<B>(mut res: dev::ServiceResponse<B>) -> Result<ErrorHandlerResponse<B>> {
    res.response_mut().headers_mut().insert(
        http::header::CONTENT_TYPE,
        http::HeaderValue::from_static("Error"),
    );
    Ok(ErrorHandlerResponse::Response(res))
}

#[actix_web::main]
async fn main() -> io::Result<()> {
    HttpServer::new(move || {
        App::new()
            .wrap(ErrorHandlers::new().handler(StatusCode::NOT_FOUND, not_found))
            .wrap(Logger::default())
            .service(Files::new("/", "./data/web"))
    })
    .bind("127.0.0.1:8081")?
    .run()
    .await
}
```

File `css/sytle.css`.

## Context
Trying to mix routes and conclude with static file serving, but CSS wont render.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.56.1 (59eed8a2a 2021-11-01)
* Actix Web Version:
```toml
actix-files = "0.6.0-beta.4"
actix-http = "3.0.0-beta.13"
actix-web = "4.0.0-beta.12"
```

P.S. As an aside the wrap() ErrorHandler doesn't work when browsing missing files from the Files service.

**Comment by aliemjay** [comment]
Is any of the middlewares neccessary for reproduction?

> P.S. As an aside the wrap() ErrorHandler doesn't work when browsing missing files from the Files service.

This is unexpected. Please consider filing a separate issue for this!

**Comment by Zageron** [comment]
I'm having trouble reproducing it pared down so I believe that the middleware is required.
Here's a link to my repository.
https://github.com/Zageron/learn-splatoon

**Comment by Zageron** [comment]
Reproduced when I introduce the user service.
```rust
#[get("/{user}/{data}")]
async fn user(hb: web::Data<Handlebars<'_>>, path: web::Path<(String, u32)>) -> HttpResponse {
    let data = json!({
        "user": path.0,
        "data": path.1
    });
    let body = hb.render("user", &data).unwrap();

    HttpResponse::Ok().body(body)
}
```

```rust
    HttpServer::new(move || {
        App::new()
            .service(user)
            .service(Files::new("/", "./data/web"))
    })
    .bind("127.0.0.1:8081")?
    .run()
    .await
```

**Comment by Zageron** [comment]
I see now why it would happen, because of the pattern matching. 😨
