### ISSUE TITLE
consider guaranteeing the iteration order of `HeaderMap::get_all`

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#2466]
It was brought up that header collapsing is difficult without being able to find out/guarantee ordering at some level.

> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma.  The order in which header fields with the same field name are received is therefore significant to the interpretation of the combined field value; a proxy MUST NOT change the order of these field values when forwarding a message.
\- https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2

This idea might also extend to guaranteeing same-name header orders elsewhere.

**Comment by mkantor** [comment]
It appears that the current `GetAll` iterator (tested in 89c6d62) already does iterate in insertion order, while the version in actix-web 3.x does not (it's close, but the first two entries are transposed, e.g. `2,1,3,4,5,6,…`).

I think this would only be a doc change and perhaps some tests to prevent regression.

@robjtede thanks for filing this on my behalf!
