### ISSUE TITLE
# (hash tag) not working in path extractor

### ISSUE THREAD

**Issue by xspio** [actix/actix-web#2472]
## Expected Behavior
hash in url  referred to as a fragment
example: `<a href="http://example.com/page.html#foo">Jump to #foo on page.html</a>`

## Current Behavior
can't extract link path with hash tag (#) like this `<a id="myAnchor" href="/en-US/docs/HTMLAnchorElement/#Examples">Examples</a>`

* Rust Version (I.e, output of `rustc -V`): 1.56.1
* Actix Web Version: 3.3.2

**Comment by robjtede** [comment]
> It is worth noting that the part after the #, also known as the *fragment identifier, is never sent to the server with the request.*

See https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#anchor

**Comment by xspio** [comment]
@robjtede thanks for the replie, just read the article u post and u are right, and i learn something, thanks again
