### ISSUE TITLE
Request for Documentation of ConnectRequest and ConnectResponse

### ISSUE THREAD

**Issue by asonix** [actix/actix-web#2476]
I was implementing a middleware for awc today and had to deal with the ConnectRequest and ConnectResponse types. Creating the middleware was simple enough since I have experience creating Actix Web middlewares already, but i'm confused about the meaning of the `Tunnel` variants on the request and response types, and if or when I need to care about them.

My middlware sets headers in requests, reads the status code from responses, and maps over the response body, but I am unable to map over the Tunnel's response body, as it is a fixed `Framed<>` type. Since I don't know what a Tunnel is I'm not sure if this is a problem or not. My hunch is it's probably fine to ignore the Tunnel case for this but I can't be sure unless I actually know what Tunnel means.

**Comment by fakeshadow** [comment]
Tunnel is mostly use for websocket request. It's an internal implementation detail got leaked by the middleware feature.
In general you can just ignore the branch and forward it like the redirect middleware does
