### ISSUE TITLE
Backpressure/backlog problem

### ISSUE THREAD

**Issue by matklad** [actix/actix-web#250]
Hi! I am experimenting with actix-web, and I *think* I've found a case where actix doesn't handle backpressure or `.backlog` method. I am likely do something wrong though, because I haven't use actix-web before. 

The reproduciable example is here: https://github.com/matklad/actix-backpressure. It contains a server and a client. 

A server process requests one-by-one, using `SyncArbiter` over one thread. Each requests is just  `thread::sleep_ms(100)`. The server is configured with `backlog` of 64: 

https://github.com/matklad/actix-backpressure/blob/166695bd9247029a59c6e9cea43c5bbd1ff5cfc4/src/main.rs#L50

So I expect that the worst-case latency would be 64000 ms.

The client then sends 128 requests simultaneously, and then continues sending messages with 100ms interval. 

I would expect that the steady state would be 6400 ms of latency, or 100 ms of latency for most of clients and infinite latency for clients in the backlog. 

What I actually see is 12000 ms of latency (and more if I send more requests simultaneously)

Use `cargo run --bin server` and `cargo run --bin client` to run my example.

**Comment by fafhrd91** [comment]
there is no backpressure during accept socket stage. `.backlog()` is socket level configuration.

accept backpressure is in my todo.

**Comment by matklad** [comment]
Great to hear that! Feel free to close the issue or to use is as a feature request for back pressure!

**Comment by fafhrd91** [comment]
fixed in master
