### ISSUE TITLE
awc initialises openssl context several times, which can be excessively slow on openssl 3.0.0

### ISSUE THREAD

**Issue by matklad** [actix/actix-web#2502]
The following program: 

```rust
fn main() {
    awc::Client::builder()
        .connector(awc::Connector::new().max_http_version(awc::http::Version::HTTP_11))
        .finish();
}
```

calls `SslConnectorBuilder::build` three times, which is very slow (half a second for each call) on openssl 3.0.0. See https://github.com/sfackler/rust-openssl/issues/1576 for context and https://github.com/matklad/repros/tree/849734a22d015b6ec8cff4a7948350ab5dcc89ab/awc-openssl-init for a stand-alone reproduction. 

I would expect the ssl context to be initalized once, on the call to `.finish()`.

**Comment by robjtede** [comment]
I'm not seeing slowness particularly on my macOS dev machine but we can still make this better.

Would it be enough to only store the builder until we are ready to use the connector? I ask because the logs you inserted into `openssl` are on `set_default_verify_paths` so I'm wondering if this is the call that is slow.

**Comment by robjtede** [comment]
@matklad any thoughts on the above?

**Comment by matklad** [comment]
Yeah, I think #2503 should fix this particular issue, as it'll just creates a builder rather than a ready context. EDIT: confirmed via strace that I no longer see extraneous syscalls. 

Though, on the first glance, it seems there's a deeper issue here -- `Connector` is a builder, with a `fn finish(self)`, but it does a lot of (potentially redundant work) prior to finish. That is, we still call `Self::build_ssl` in the `new` method, but the results of that operation can be completely overwritten in `max_http_version` or `ssl` methods. That is probably OK practically, as now that's just some memory allocations and no syscalls,

Given that what we store in our context are builder objects themselves, I wonder if it makes more sense to not re-initialize the whole builder, but do something along the following lines? 

```diff
diff --git a/awc/src/client/connector.rs b/awc/src/client/connector.rs
index 423f656a..59730249 100644
--- a/awc/src/client/connector.rs
+++ b/awc/src/client/connector.rs
@@ -218,7 +218,7 @@ where
                 unimplemented!("actix-http client only supports versions http/1.1 & http/2")
             }
         };
-        self.tls = Connector::build_ssl(versions);
+        self.tls.config.alpn_protocols = version;
         self
     }
 
```
