### ISSUE TITLE
Compilation of 4.0.0-beta < beta 14 fail

### ISSUE THREAD

**Issue by chriskyndrid** [actix/actix-web#2506]
## Expected Behavior
I believe actix-web 4 beta releases prior to 14 should compile.

## Current Behavior
Compilation of less than beta 14 fails with hundreds of compilation errors referencing missing imports, E.G.:

```
error[E0412]: cannot find type `HeaderValue` in this scope
   --> /XyZ/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.13/src/response/response.rs:135:23
    |
135 |         let vals: Vec<HeaderValue> = headers
    |                       ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
1   | use actix_http::header::HeaderValue;

....

error[E0425]: cannot find value `CONTENT_LENGTH` in module `header`
   --> /XyZ/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.13/src/types/payload.rs:299:53
    |
299 |         if let Some(l) = req.headers().get(&header::CONTENT_LENGTH) {
    |                                                     ^^^^^^^^^^^^^^ not found in `header`
    |
help: consider importing this constant
    |
3   | use actix_http::header::CONTENT_LENGTH;
```

## Steps to Reproduce (for bugs)
An example of a failing Cargo.toml test:

```
[package]
name = "actix_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "=4.0.0-beta.13"}
```

## Context
Some of the dependencies I use for a project I'm working on have not upgraded to beta-14 yet, like [tracing-actix-web](https://github.com/LukeMathWalker/tracing-actix-web), which currently requires `actix-web = {version = "=4.0.0-beta.13"}`

## Your Environment
Tested on:

MacOS: 
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
```

Fedora:

```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
```

**Comment by robjtede** [comment]
due to the complexity of the crate graph, we only support latest beta versions

to fix your issue you will need to also pin actix-http and possibly actix-tls to older versions

it's a good idea to pin all your beta deps (find them with `cargo tree`) since cargo provides no guarantees around their compatibility

**Comment by chriskyndrid** [comment]
Bummer, but understandable. 

Thank you!
