### ISSUE TITLE
Result -> Fallible

### ISSUE THREAD

**Issue by mitsuhiko** [actix/actix-web#251]
This proposes to rename the Result alias to Fallible. Shadowing result is not great for documentation and the fallible alias has been proposed by the fail crate before and has found some use.

**Comment by DoumanAsh** [comment]
Where is this awful naming, '`Fallible`, comes from?

Rust have proper name spacing so I don't really see an issue with having result alias

**Comment by mitsuhiko** [comment]
The name comes from here: https://github.com/rust-lang-nursery/failure/issues/95

The problem with shadowing is that it makes examples hard to understand where you might not see the import yet. More importantly however it also causes a lot of code to do `use std::result::Result as StdResult` and similar where the result is aliased and this has caused a lot of headaches for us when refactoring in the past.

Worst however is if that breaks macros since they lack type hygiene.

**Comment by DoumanAsh** [comment]
The problem is that people should not import redefined `Result` directly but to use through namespace.

And if examples are using this alias directly, they should be corrected to use it through namespace.
afaik it should be like `error::Result` for short.

Anyway I only wanted to state that `Result` alias is not a problem.
But we should not use it directly in examples for sure to avoid confusion.
There is no real need for renaming

**Comment by mitsuhiko** [comment]
I don't think it's a great pattern when everything is documented as a direct import from `actix_web` except `Result` which would be `actix_web::error` -> `error::Result`. (Let alone that this does not answer which error this is). So it would probably become `actix_web::Result<T>` instead in use and at that point I don't think the alias brings any benefits.

**Comment by hayd** [comment]
Is `ActionResult` too verbose?

**Comment by ousado** [comment]
In favor of adding `Fallible` as an alias and perhaps deprecating the `Result` alias later. Regarding the "awful naming" - the more awful, the less likely it is to conflict in future, so that's a plus in this case.

**Comment by hazel-ocean** [comment]
Just going to throw in the perspective of someone who might be coming from another language, more or less familiar with Rust (maybe Rust is this person's second language?). As this person, I would really appreciate naming of standard ideas such as `Result` or `Error` within Actix to follow the Principle of Least Surprise. As this person, I wouldn't appreciate naming conventions inconsistent with the rest of the ecosystem, especially if I have the option of controlling the namespace or plan on wrapping into my own application's Error type.  
  
Glob importing is nice, but I wouldn't want to sacrifice ecosystem-wide conventions for it. Also, we can always do this, which I also appreciate.
```rust
use std::io::{Result as IOResult, *};
use std::result::{Result as StdResult, *};
use actix_web::{Result as ActixWebResult, *};
```

**Comment by fafhrd91** [comment]
i think it is too late to change name
