### ISSUE TITLE
awc connection pool with limit = 0 always times out

### ISSUE THREAD

**Issue by mvalenzuelamoixa** [actix/actix-web#2514]
## Expected Behavior
The documentation for `awc` states that `.limit(0)` means the connector has no limit. However, it seems that after this change:

https://github.com/actix/actix-web/pull/1994

The limit = 0 case stopped being handled differently, and instead now a semaphore with 0 permits is created, leading to the client not working. Looks like a regression.

## Current Behavior
Requests always time out.

## Possible Solution
I would say making the builder interface more idiomatic by  accepting an Option would be good, then handle the None case separately if we want to keep that functionality. Otherwise, if we always want to have a limit I would change the documentation.

## Steps to Reproduce (for bugs)
Create an awc::Client with limit = 0.

## Your Environment

Latest beta version of awc (3.0.0-beta.13) on rustc 1.51.0.

**Comment by mvalenzuelamoixa** [comment]
By the way, I am happy to contribute either of the changes (handle infinite limit differently, with or without builder interface change; or docs change), but I would need some direction on which way to go.

**Comment by robjtede** [comment]
cc @fakeshadow

**Comment by fakeshadow** [comment]
No limit should just go. awc does not offer protocol specific setting and it's already a problem in it's own.
Namely awc does not do any form of connection multiplexing at all which is anti-pattern for http2.
