### ISSUE TITLE
post json request bug

### ISSUE THREAD

**Issue by bzdx** [actix/actix-web#2532]
My front end and back end do not use the same host.

CORS err will occur for post json requests with data，but I‘ve set headers:
```
"Access-Control-Allow-Origin", "*"
"Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, PATCH"
```

request json data：
```
{username: "test-123"}
```

But it was normal when I‘ve post json request with no data.

## Expected Behavior
CORS shouldn’t appear when the header has been set 

* Rust Version (I.e, output of `rustc -V`):
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

* Actix Web Version: 
```
actix-web = "3"
```

**Comment by robjtede** [comment]
Re-read the CORS documentation (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and use [actix-cors](https://crates.io/crates/actix-cors) to set up your server-side CORS config properly.
