### ISSUE TITLE
cargo audit : chrono

### ISSUE THREAD

**Issue by kiap** [actix/actix-web#2536]
###  Environment
RUST VERSION : 1.57.0
Actix_web : master (git cloned)

OS: both CentOS 7 and RHEL 8.5 (Ootpa)
System: x86_64 bit

### Problem
 We recently decided to move Go code to Rust as the future release 1.18 will not have shared library support ! ( yeah you read it right)

Tried:
# cargo update
# cargo audit

Still chrono is reported as vulnerability ( including time ^0.1) due to realtime_r call which can be used to cause remote execution 

There are also 5 unmaintained dependencies 

# Question / Security 

1.  I believe unmaintained dependencies is a beginning to get messy security issues
2. Chrono is insecure why is it still used when time ^0.3 would do?
3. Comparing to hyper, which passes cargo audit, I have hard time to convince my boss that actix-web is superior (which is, don't get me wrong)
Is there any plan to fix this in future?

Please correct me if I am wrong,

And thanks for your great work

**Comment by robjtede** [comment]
Actually, chrono does not appear in our dependency tree for the library. The reason it fails cargo audit is a development dependency on `rcgen` for our test suite. You can confirm this by running `cargo tree --invert=chrono --edges=normal` in this repo (and see that removing the `--edges` arg shows its dep through `rcgen`).

Similarly, if you create a test project with Actix Web as the only dependency, `cargo audit` does not show the `chrono` advisory.

See https://deps.rs/crate/rcgen/0.8.14. It would be good to report this to the `rcgen` crate.
