### ISSUE TITLE
Misleading error on body size overflow with custom maximum size

### ISSUE THREAD

**Issue by tazjin** [actix/actix-web#256]
Hey!

This (sort of) relates to #149.

If a custom body size is set on a JSON extractor it seems like the error variant [`JsonPayloadError::Overflow`](https://github.com/actix/actix-web/blob/master/src/error.rs#L463) is still being displayed with the error message `"Payload size is bigger than 256k"`.

This can be slightly misleading and lead to us initially thinking the size change wasn't working, before looking at the error definition.

I don't think it's necessary to generate the text entirely dynamically, but just writing something like `... bigger than allowed. (default: 256kB)` would indicate that the text is generic over configurations.

Cheers!

**Comment by fafhrd91** [comment]
thanks!

fixed in master
