### ISSUE TITLE
Lack doc for panic condition in `ServiceRequest::match_info_mut`

### ISSUE THREAD

**Issue by fakeshadow** [actix/actix-web#2562]
## Expected Behavior

Doc for panic condition.

## Current Behavior

Panic info is hidden behind crate level function.

## Possible Solution

Copy the doc to public function.

**Comment by robjtede** [comment]
I think it could also beneficial to have a debug warning on from_parts if the Rc count is not 1.

**Comment by robjtede** [comment]
I think it could also beneficial to have a debug warning on from_parts if the Rc count is not 1.
