### ISSUE TITLE
Shouldn't FormConfig::limit returns 413 instead of 500?

### ISSUE THREAD

**Issue by bbigras** [actix/actix-web#257]
Right now exceeding the limit set by [FormConfig::limit](https://docs.rs/actix-web/0.6.10/actix_web/dev/struct.FormConfig.html#method.limit) makes the request return [500 Internal Server Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500). Shouldn't it be better to use [413 Payload Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413) or maybe [400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)?

**Comment by fafhrd91** [comment]
I think it should return 413, if is is not then it is bug
