### ISSUE TITLE
Don't consider the last slash (/) when routing

### ISSUE THREAD

**Issue by Thomasdezeeuw** [actix/actix-web#2573]
## Expected Behavior

I would expect the URL `/some/path/` to match the route `/some/path` and vice versa.

## Current Behavior

Having a route `/some/path` doesn't get hit when using `/some/path/` as URL.

## Possible Solution

I'm not sure if it's a breaking change, or even a desirable change, but it would be nice if the route would remove the last `/` automatically.

## Your Environment

- Actix Web Version: 4.0.0-beta.18

**Comment by robjtede** [comment]
This is intended behavior. See:
- https://actix.rs/actix-web/actix_web/dev/struct.ResourceDef.html#pattern-format-and-matching-behavior
- https://actix.rs/actix-web/actix_web/dev/struct.ResourceDef.html#trailing-slashes

The method for avoiding trailing slash concerns is to use the `NormalizePath` middleware. https://actix.rs/actix-web/actix_web/middleware/struct.NormalizePath.html

```rust
.wrap(NormalizePath::trim())
```

**Comment by Thomasdezeeuw** [comment]
Thanks @robjtede `NormalizePath` works.
