### ISSUE TITLE
`actix_router::Path::{path, unprocessed}` are equivalent!

### ISSUE THREAD

**Issue by aliemjay** [actix/actix-web#2588]
They both have exactly the same behavior.

Exisiting services may rely on this behavior (`Files` for example), so simply changing the behavior of `path` may introduce subtle bugs. I think renaming and the deprecating the old `path` is a better choice.

cc @robjtede. I think it is worth fixing before stabilizing `actix-router`.

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
- Actix Web Version: v4.0-beta.20

**Comment by robjtede** [comment]
They're only different in their panicking behavior. `unprocessed` will panic if `skip` indexes further than the path length but `path` won't.

What do you suggest doing with them anyway?

**Comment by aliemjay** [comment]
> What do you suggest doing with them anyway?

one sure thing is to remove `path` because the name is confusing.

maybe replace them with {`unmatched_path`, `full_path`, `unprocessed_path`, ..} ?
