### ISSUE TITLE
Extracting data from select multiple

### ISSUE THREAD

**Issue by gdanjou** [actix/actix-web#259]
Hello,

When i try extracting value from a select multiple im getting this message from logs :

> actix_web::pipeline: Error occured during request handling: Parse error

My code 

> .resource("/insert", |r| {
>                r.method(http::Method::GET).f(an_other_function);
>                r.method(http::Method::POST).with(insert)
>           })

> fn insert(form_insert: Form\<FormInsert>) -> Result\<HttpResponse> {

if i replace form_insert: Form<FormInsert> with form_insert: String and print the value of form_insert im getting this 

>material=1&material=3

this is my form html 

> \<form action="/insert" method="post">
>        \<select class="select" name="material" multiple="multiple">
>            {% for material in materials %}
>            \<option value="{{ material.id }}">{{ material.name_material }}\</option>
>            {% endfor %}
>        \</select>
>        \<button class="btn" type="submit">Send\</button>
>    \</form>
 
I don't know if i'm not using actix the right way or if it's something else.

EDIT : this is my version of actix i'm using : actix = "0.5" and actix-web = "0.6.1", i'm on W10

**Comment by ghost** [comment]
form extreactor uses serde_urlencoded. I couldn't find what it does with select multiple. There might be a
problem with the FormInsert struct. I think a multiple select field should become a vector of ids. I think that
parse error is returned only when serde_urlencoded return an error.

**Comment by soqe** [comment]
Same thing when I using textarea or input with checkbox/hidden type(idk what is it from the list). Version from master branch.

**Comment by DoumanAsh** [comment]
Oh... I kinda missed this issue.

I would like someone to clarify a bit what is the problem.
What is your struct and what data you send

**Comment by soqe** [comment]
My example:
```rust
pub struct MyStruct {
	pub field1: String,
	pub field2: String,
	pub field3: bool,
	pub field4: String,
	pub field5: String,
}
```
And Form looks like this:
```HTML
   ... plain text inputs ...
   <input type="text" name="date" value="2018-08-21 21:06:02"><br/>
   <input type="text" name="tags" value=""><br/>
   <textarea id="editor" name="content"></textarea><br/>
   <input type="checkbox" name="published" value=""><br/>
```

**Comment by DoumanAsh** [comment]
I imagine your struct should have the same field names as your form. You should check out how your browser sends out request.

**Comment by soqe** [comment]
Yes, I know about all the details. The example is just for example, all my code cover that details.

**Comment by gdanjou** [comment]
Hello again !

It was something like this 

//main.rs

```
#[macro_use]
extern crate serde_derive;
extern crate actix_web;
extern crate env_logger;

use actix_web::{http, server, App, Form, Result, HttpRequest, HttpResponse};

#[derive(Deserialize, Debug)]
struct Info {
    colors: Vec<String>,
}

fn index(_: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .body("<form action=\"\" method=\"post\">
<select class=\"select\" name=\"colors\" multiple=\"multiple\">
<option value=\"red\">Red</option>
<option value=\"blue\">Blue</option>
<option value=\"black\">Black</option>
</select>
<button type=\"submit\">Send</button>
</form>")
}

fn index_form(info: Form<Info>) -> Result<String> {
    println!("{:?}", info);
    Ok(String::from("OK"))
}

fn main() {
    std::env::set_var("RUST_LOG", "actix_web=info");
    env_logger::init();
    server::new(|| {
        App::new()
            .resource("/", |r| {
                r.method(http::Method::GET).with(index);
                r.method(http::Method::POST).with(index_form)
            })
    })
    .bind("127.0.0.1:8000")
    .expect("Can not bind to port 8000")
    .run();
}
```

//Cargo.toml

```
[dependencies]
actix-web = "0.7.3"
serde = "1.0.72"
serde_derive = "1.0.72"
env_logger = "*"
```

And i got this error : WARN 2018-08-21T17:46:21Z: actix_web::pipeline: Error occured during request handling: Parse error

Maybe actix don't handle select multiple correctly ?

Like I said in my original post, maybe i'm not using actix correctly, if it's the case sorry for the waste of time.

**Comment by DoumanAsh** [comment]
Not sure right now, we currently rely on `serde_urlencoded` implementation for that, and I never used it like that.

Maybe we don't support multiple select at all, but I need to investigate serde more

**Comment by soqe** [comment]
Found my problem. The problem is with checkbox only.

**Comment by DoumanAsh** [comment]
@gdanjou Can you please check update if this issue still present(serde_urlencoded) should be updated

**Comment by gdanjou** [comment]
Using the same main.rs as above and updated dependencies:

```
[dependencies]
actix-web = "0.7.14"
serde = "1.0.80"
serde_derive = "1.0.80"
env_logger = "*"
```
the problem is the same : i can't get value from a multiple select using :

```
#[derive(Deserialize, Debug)]
struct Info {
    colors: Vec<String>,
}
```

I keep getting this error : 

> [2018-11-23T18:09:16Z WARN  actix_web::pipeline] Error occurred during request handling: Parse error


When we look to : https://github.com/nox/serde_urlencoded/blob/master/tests/test_deserialize.rs

An url with 

> colors=red&colors=blue

is converted to : 

`vec![("colors".to_owned(), "red".to_owned()), ("colors".to_owned(), "blue".to_owned())]`

Maybe actix don't handle well the fact the vector contain 2 keys with the same value ("colors") ?


// After some tests 

//mains.rs

```
#[macro_use]
extern crate serde_derive;
extern crate actix_web;
extern crate env_logger;

use actix_web::{http, server, App, Query, Result, HttpRequest, HttpResponse};

#[derive(Deserialize, Debug)]
struct Info {
    colors: String,
}

fn index(_: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .body("<form action=\"test\" method=\"get\">
<select class=\"select\" name=\"colors\" multiple=\"multiple\">
<option value=\"red\">Red</option>
<option value=\"blue\">Blue</option>
<option value=\"black\">Black</option>
</select>
<button type=\"submit\">Send</button>
</form>")
}

fn index_form(info: Query<Info>) -> Result<String> {
    println!("{:?}", info);
    Ok(String::from("OK"))
}

fn main() {
    std::env::set_var("RUST_LOG", "actix_web=info");
    env_logger::init();
    server::new(|| {
        App::new()
            .resource("/", |r| {
                r.method(http::Method::GET).with(index);
            })
            .resource("/test", |r| {
                r.method(http::Method::GET).with(index_form)
            })
    })
    .bind("127.0.0.1:8000")
    .expect("Can not bind to port 8000")
    .run();
}
```

//Cargo.toml

```
[dependencies]
actix-web = "0.7.14"
serde = "1.0.80"
serde_derive = "1.0.80"
env_logger = "*"
```

got to URL : http://127.0.0.1:8000/test?colors=red&colors=blue

give me this error : 

> 2018-11-23T18:46:07Z WARN  actix_web::pipeline] Error occurred during request handling: duplicate field `colors`

If i'm not wrong its allowed to have multiple value with the same field like here : https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple



Sorry i can't help more, i'm a newby in Rust developpement :'(

**Comment by jesskfullwood** [comment]
`serde_urlencoded` has effectively tagged this as [won't-fix](https://github.com/nox/serde_urlencoded/pull/42) with the suggestion to use [`serde_qs`](https://github.com/samscott89/serde_qs) if you want this feature. We should consider doing so.

**Comment by fafhrd91** [comment]
As I remember serde_qs is based on serde_urlencoded, what is the difference?

**Comment by jesskfullwood** [comment]
I have never used it, but it allows de/serializing more complicated data such as `Vec`s and nested structs. 

It does contain this note in its docs:

> For users who do *not* require nested URL parameters, it is highly recommended that the `serde_urlencoded` crate is used instead, which
will almost certainly perform better for deserializing simple inputs.

Also, curiously it already has its own optional [actix interop](https://github.com/samscott89/serde_qs/blob/master/src/actix.rs) already, maybe that is enough.

**Comment by jesskfullwood** [comment]
As for the original problem here, for a browser form like
```
<form action="/action_page.php">
  <select name="cars" multiple>
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
<input type="submit">
</form>
```
The submitted query string will look like  (e.g.) `cars=volvo&cars=saab`.

There is apparently no clear standard as to how frameworks should handle this.

`Flask` simply lets you request particular query args as scalars with `request.args.get('key')` and list types with `request.args.getlist('key')`.

`php` will place the elements into an array if and only if the key is of the form `key[]`, i.e. above it would expect `cars[]=volvo&cars[]=saab`  (so in the HTML snippet, name must be `car[]`)

`serde_urlencoded` will attempt to deserialize into a `Vec<(String, String)>` e.g. `vec![("car", "volvo"), ("car", "saab")]`

`serde_qs` will do what we want, i.e. into some field `car: Vec<String>`, but only if the key is `car[]`, not `car`.


[Useful stackoverflow](https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request)

Maybe that clears things up a bit, maybe not!

**Comment by sonfangos** [comment]
@jesskfullwood 

> Maybe that clears things up a bit, maybe not!

That cleared the issue up for me, I think. Thank you! The serde_qs Actix feature didn't work for me for the HTML form, though. I found that I had to, in effect, percent decode the square brackets in the query string first before letting serde_qs do its thing.

Here's what I came up with, should anyone find it helpful:

```rust
use actix_web::{web, App, HttpRequest, HttpResponse, HttpServer};
use serde::{Deserialize};
use serde_qs;

#[derive(Deserialize)]
pub struct Vehicle {
   cars: Vec<String>,
}

fn index(_: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .body("<form action=\"select\" method=\"get\">
                <select name=\"cars[]\" multiple=\"multiple\">
                  <option value=\"volvo\">Volvo</option>
                  <option value=\"saab\">Saab</option>
                  <option value=\"opel\">Opel</option>
                  <option value=\"audi\">Audi</option>
                </select>
                <button type=\"submit\">Send</button>
              </form>")
}

fn select_cars(req: HttpRequest) -> String {
    serde_qs::from_str::<Vehicle>(&req.query_string()
        .replace("%5B", "[") // <= quick and dirty percent decode
        .replace("%5D", "]")) // <= quick and dirty percent decode
        .unwrap()
        .cars.iter()
        .map(|c| c.to_string())
        .collect::<Vec<String>>()
        .join(", ")
        .into()
}

fn main() {
    HttpServer::new(|| App::new()
        .route("/", web::get().to(index))
        .route("/select", web::get().to(select_cars)))
        .bind("0.0.0.0:8080")                                                                                                                        
        .unwrap()                                                                                                                                    
        .run()                                                                                                                                       
        .unwrap();   
}
```
EDIT:

Following @jesskfullwood 's suggestion below, you can also use serde_qs's non-strict mode to avoid having to decode the query string:

```rust
use serde_qs::Config;

fn select_cars(req: HttpRequest) -> String {
    let config = Config::new(10, false);
    let vehicle: Vehicle = config.deserialize_str(&req.query_string()).unwrap();
    vehicle.cars.iter()
        .map(|c| c.to_string())
        .collect::<Vec<String>>()
        .join(", ")
        .into()
} 
```

**Comment by jesskfullwood** [comment]
@sonfangos Interesting. Did you have a look at the [`serde_qs` docs](https://docs.rs/serde_qs/0.5.0/serde_qs/index.html#strict-vs-non-strict-modes)? It has a non-strict mode for your use-case, using `Config`.

```
let config = serde_qs::Config::new(10, false);
let vehs: Vehicle = config.deserialize_str(&req.query_string()).unwrap();
```

**Comment by sonfangos** [comment]
Many thanks! I've spelled out your improved solution in an edit at the bottom of my original comment.

I wasn't sure exactly where the problem lay re. decoding. Thanks for reaching out to the serde_qs maintainers. I look forward to seeing what they have to say about it.

**Comment by sonfangos** [comment]
Here's the same multiple-select HTML form as above, but using POST rather than GET, should anyone find it helpful.

Like the GET example, it also makes use of serde_qs:

```rust
use actix_web::{web, App, HttpRequest, HttpResponse, HttpServer, Error};
use serde::{Deserialize, Serialize};
use serde_qs::Config;
use futures::{Future, Stream};  

#[derive(Serialize, Deserialize)]
struct Vehicle {    
    cars: Vec<String>,    
}

fn index(_: HttpRequest) -> HttpResponse {
    HttpResponse::Ok()
        .body("<form action=\"select\" method=\"post\">
                <select name=\"cars[]\" multiple=\"multiple\">
                  <option value=\"volvo\">Volvo</option>
                  <option value=\"saab\">Saab</option>
                  <option value=\"opel\">Opel</option>
                  <option value=\"audi\">Audi</option>
                </select>
                <button type=\"submit\">Send</button>
              </form>")
}

fn select_cars(body: web::Payload) -> impl Future<Item = HttpResponse, Error = Error> {
    body.map_err(Error::from)
        .fold(web::BytesMut::new(), move |mut body, chunk| {
            body.extend_from_slice(&chunk);
            Ok::<_, Error>(body)
        })
        .and_then(|body| {
            let config = Config::new(10, false);
            let vehicle: Vehicle = config.deserialize_bytes(&body).unwrap();
            Ok(HttpResponse::Ok().body(vehicle.cars.iter()
                .map(|c| c.to_string())
                .collect::<Vec<String>>()
                .join(", ")
            ))
        })
}

fn main() {
    HttpServer::new(|| App::new()
        .route("/", web::get().to(index))
        .route("/select", web::post().to_async(select_cars)))
        .bind("0.0.0.0:8080")                                                                                                                        
        .unwrap()                                                                                                                                    
        .run()                                                                                                                                       
        .unwrap(); 
}
```

**Comment by fafhrd91** [comment]
i think this should be done outside of actix-web

**Comment by gundra** [comment]
You can just use plain key-value form and handle your data then:

`fn select_cars(form: web::Form<Vec<(String, String)>>) -> ...`
