### ISSUE TITLE
Settings from cmdline

### ISSUE THREAD

**Issue by bastiencyr** [actix/actix-web#2602]
Hello :)

What do you think about configure the webserver from cmdline or file ? For example, call ./actix-server --workers 4 with the following code:
```rust
let server = HttpServer::new(|| App::new().configure(config)).from_cmd().run().await;
```
will called :
```rust
let server = HttpServer::new(|| App::new().configure(config)).workers(4).run().await;
```

It permits to customize the server with a simple interface understandable by someone who is not familiar with rust.
The person who develops and the person who deploys are not necessarily the same in a project and some things are hard to understand so it makes sense to configure from cmdline. For example, if the server is behind a proxy, it makes sense to set keepalive to a higher value and the developer is not necessarily aware of this. Of course, each developer can implement the "from_cmd" function.

It permits also to simply configure integration like systemd. We can have for example an option --systemd to search the file descriptor socket in the environment. 

Thanks !

**Comment by robjtede** [comment]
Thanks for the suggestion. It is not in scope for Actix Web to read command line arguments. I suggest using `clap` or `structopt` and passing parameters you want to the server builder.
