### ISSUE TITLE
Streaming should not return std::error::Error

### ISSUE THREAD

**Issue by vporton** [actix/actix-web#2609]
## Current Behavior
```rust
pub fn streaming<S, E>(&mut self, stream: S) -> HttpResponse where
    S: Stream<Item = Result<Bytes, E>> + 'static,
    E: Into<Box<dyn Error>> + 'static, 
```
`std::error::Error` in return value of streaming is wrong, because not every error is serious enough to hold backtracing information that `std::error::Error` holds.

Consider for example implementing a proxy server. Upstream failure error should normally contain no backtracing information (like the code line where upstream failure was detected.

## Possible Solution
Streaming API needs to be changed. The simplest possible fix is to remove the line:
```rust
    E: Into<Box<dyn Error>> + 'static, 
```

Probably, there is a more elaborate solution than just removal.
## Context
I am trying to implement a proxy from a file archive to HTTP. It needs streaming and I don't know how to do it with current API.- Actix Web Version:

**Comment by robjtede** [comment]
Note than `Into<Box<dyn Error>>` is implemented for `String`s.

https://github.com/actix/actix-web/blob/b41b346c00260a164731bf484f930d492be61f67/actix-http/src/body/body_stream.rs#L144-L151
