### ISSUE TITLE
We have two different `v4.0.0-beta.21`

### ISSUE THREAD

**Issue by vporton** [actix/actix-web#2610]
As found during my work on #2609, https://docs.rs/actix-web/4.0.0-beta.21/actix_web/struct.HttpResponseBuilder.html#method.streaming shows
```rust
pub fn streaming<S, E>(&mut self, stream: S) -> HttpResponseⓘ where
    S: Stream<Item = Result<Bytes, E>> + 'static,
    E: Into<Box<dyn Error>> + 'static,
```
and this GitHub shows for `web-v4.0.0-beta.21`:
```rust
    pub fn streaming<S, E>(&mut self, stream: S) -> HttpResponse
    where
        S: Stream<Item = Result<Bytes, E>> + 'static,
        E: Into<BoxError> + 'static,
```

So, we have two different `v4.0.0-beta.21`. Which of them is correct?

**Comment by robjtede** [comment]
the canonical beta.21 is of course the one that docs.rs shows which based on the source uploaded to crates.io

**Comment by vporton** [comment]
I tried to create a PR (to solve #2609 with the practical purpose to make Actix work for my application) and am not sure which `v4.0.0*` (or `master`?) to use as the base of my PR. Please tell.

**Comment by robjtede** [comment]
base PRs on master, thanks
