### ISSUE TITLE
Server hangs on kept-alive connection if body not consumed

### ISSUE THREAD

**Issue by andrewhalle** [actix/actix-web#2632]
## Related issues
Seems very similar to #2357 which is closed but I can still reproduce.

## Expected Behavior

Server should not hang.

## Current Behavior

If multiple HTTP requests which contain data are sent on the same HTTP connection, and the body of the HTTP request is not consumed by the handler (or a handler does not exist) then the server hangs for the rest of that connection. Closing the connection and opening a new one recovers.

## Steps to Reproduce (for bugs)

server
```
use actix_web::{App, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new())
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}
```
with `Cargo.toml`
```
[package]
name = "echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.2"
actix-http = "3.0.0-rc.1"

[patch.crates-io]
actix-web = { git = "https://github.com/actix/actix-web.git", rev = "5ca42df" }
```
and client
```
use std::io::{Read, Write};
use std::net::TcpStream;
use std::thread;
use std::time::Duration;

const REQUEST_HEAD: &'static str = r#"POST /foo HTTP/1.1
Content-Length: 3

"#;

const REQUEST_BODY: &'static str = "abc";

fn main() {
    let mut stream = TcpStream::connect("127.0.0.1:8080").unwrap();

    for i in 0..10 {
        println!("{i}");
        write!(stream, "{}", REQUEST_HEAD.replace("\n", "\r\n")).unwrap();
        // if there is no sleep between sending the request headers and the request body, then there is no error
        //thread::sleep(Duration::from_millis(0));
        thread::sleep(Duration::from_millis(1));
        write!(stream, "{}", REQUEST_BODY).unwrap();
    }

    let mut buf = [0_u8; 1024];
    while let Ok(n) = stream.read(&mut buf) {
        if n == 0 {
            break;
        }

        print!("{}", String::from_utf8_lossy(&buf[..n]));
    }
}
```

## Context

intermittent 502s from a service behind a load balancer.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.58.1 (db9d1b20b 2022-01-20)
- Actix Web Version: git ref 5ca42df

**Comment by robjtede** [comment]
this fix isnt released yet, you'd have to patch the actix-http version to a git dep too to observe it

**Comment by andrewhalle** [comment]
I believe the commit ref I’m patching in my `Cargo.toml` is the commit that closed the related issue, so I would have thought I’d be able to see it. If that’s not the case, I can certainly try again with the next release!

**Comment by robjtede** [comment]
> I believe the commit ref I’m patching in my Cargo.toml is the commit that closed the related issue

it is but youre only patching actix-web

**Comment by andrewhalle** [comment]
Ah! Read right over it. Thank you!
