### ISSUE TITLE
Ability to configure log level for errors in actix_web::middleware::Logger

### ISSUE THREAD

**Issue by mseele** [actix/actix-web#2637]
## Expected Behavior

It should be possible to change the log level to something else than `debug` in `actix_web::middleware::Logger`.

## Current Behavior
Each error logged by `actix_web::middleware::Logger` is logged as log level `debug`:

https://github.com/actix/actix-web/blob/e0f02c1d9e764140b93d5eeaa853a667293907b9/actix-web/src/middleware/logger.rs#L308

## Possible Solution
Make log level configurable via an `enum`. Default value can be debug to keep backward compatibility.

## Context
In production, i only want to log the levels `warn` and above. But this is not possible with `actix_web::middleware::Logger`.

## Your Environment

- Rust Version: rustc 1.58.0 (02072b482 2022-01-11)
- Actix Web Version: 4.0.0-rc.3

**Comment by robjtede** [comment]
its not really practical to offer customizable logging level for each instance

you could use:
`RUST_LOG=warn,actix_web::middleware::Logger=debug cargo run`

**Comment by mseele** [comment]
Maybe i don't get it but isn't it possible to have a enum to configure the log level in the same way like the format is configurable?

**Comment by robjtede** [comment]
I mean for each instance of logging in the library. We've chosen debug for this one because it is appropriate to the purpose of the log, works well with the default log levels, and is expose-able with the usual methods within RUST_LOG env vars if you so choose. Offering two ways to expose the log provides no extra value.

**Comment by mseele** [comment]
Okay. Maybe I'm using it in a different way than it was designed:

I want to log all errors that happen inside a request (which might be a db failure or something else) and therefore I need another level than debug. Because these errors are a real problems/errors for me.

I'm willing to provide a PR. Would you consider merging it or do you have any other ideas to implement my need?

**Comment by robjtede** [comment]
> I want to log all errors that happen inside a request

`RUST_LOG=warn,actix_web::middleware::Logger=debug cargo run` will enable these logs

**Comment by mseele** [comment]
> > I want to log all errors that happen inside a request
> 
> `RUST_LOG=warn,actix_web::middleware::Logger=debug cargo run` will enable these logs

Yes, I know and we use this right now. But the log messages are all logged at debug level and we need to have them logged at error level. This is my "problem"...

**Comment by robjtede** [comment]
ok, then write yourself a little middleware that gets the error out of the response and logs it in the way that you need it

eg using: https://docs.rs/actix-web-lab/latest/actix_web_lab/middleware/fn.from_fn.html

```rust
async fn my_mw(
    req: ServiceRequest,
    next: Next<impl MessageBody>,
) -> Result<ServiceResponse<impl MessageBody>, Error> {
    let res = next.call(req).await?;

    if let Some(error) = res.response().error() {
        error!("Error in response: {:?}", error);
    }

    Ok(res)
}
```

**Comment by mrsarm** [comment]
Cross-posting here this [comment](https://github.com/actix/actix-web/issues/529#issuecomment-1677508878), my crate that it's a drop-in replacement of the original `Logger` middleware allows to customize the error in response logs as well, and print them out with a bit more details, check-out [`Logger::custom_error_resp_level()`](https://docs.rs/actix-contrib-logger/latest/actix_contrib_logger/middleware/struct.Logger.html#method.custom_error_resp_level):

```rust
use actix_contrib_logger::middleware::Logger;
use http::StatusCode;
use log::Level;

let logger = Logger::default()
    .custom_error_resp_level(|status| {
        if status.is_server_error() {
            Level::Error
        } else {
            Level::Info
        }
    });
```

Requests logs with errors will look like (the error in response logs are the first and the third lines):

```
[2023-08-13T21:51:02Z INFO  http_logger] Error in "400 Bad Request" response: Validation("Tenant already exists.")
[2023-08-13T21:51:02Z INFO  http_logger] 127.0.0.1 "POST /tenants HTTP/1.1" 400 56 "-" "HTTPie/3.2.1" 0.002368
[2023-08-13T20:59:53Z ERROR http_logger] Error in "500 Internal Server Error" response: DB(PoolTimedOut)
[2023-08-13T07:59:53Z ERROR http_logger] 127.0.0.1 "POST /users HTTP/1.1" 500 86 "-" "curl/7.68.0" 0.002023
```

Moreover, if you just want to print these logs with `ERROR` severity when it's a server side error (HTTP 5xx), that's the default, you don't need to use `custom_error_resp_level()` for that, while the rest of errors in responses will be logged by default with `DEBUG` severity (e.g. errors in HTTP 4xx responses).
