### ISSUE TITLE
Broken "Configure" example: trait Handler not implemented for closure

### ISSUE THREAD

**Issue by emptonaut** [actix/actix-web#2642]
## Expected Behavior

Rust and Actix beginner, so please forgive a potentially stupid question.
I've found the example provided in the "Configure" section of [Application documentation](https://actix.rs/docs/application/) doesn't work with the latest tagged version of `actix-web`. Source is also [here](https://github.com/actix/actix-website/blob/master/examples/application/src/config.rs).

## Current Behavior

Every instance of `to(closure)` yields an error like this:

```
error[E0277]: the trait bound `[closure@src/main.rs:16:34: 16:67]: Handler<_>` is not satisfied
   --> src/main.rs:16:31
    |
16  |             .route(web::get().to(|| HttpResponse::Ok().body("app")))
    |                               ^^ the trait `Handler<_>` is not implemented for `[closure@src/main.rs:16:34: 16:67]`
    |
note: required by a bound in `Route::to`
   --> /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-rc.3/src/route.rs:184:12
```

## Possible Solution
I don't have the knowhow to be useful here, besides noting that downgrading to 3.3.3 makes the example work. I also noticed that there are some similarities to #2231.

## Steps to Reproduce (for bugs)
1. `cargo new configure_example`
2. Add 
```
actix-web = "4.0.0-rc.3"
serde = {version = "1.0.136", features = ["derive"]} 
```
to dependencies
3. Copy the example program from the above link into `main.rs`. Reproduced here:
```
use actix_web::{web, App, HttpResponse, HttpServer};

// this function could be located in a different module
fn scoped_config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/test")
            .route(web::get().to(|| HttpResponse::Ok().body("test")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    );
}

// this function could be located in a different module
fn config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/app")
            .route(web::get().to(|| HttpResponse::Ok().body("app")))
            .route(web::head().to(|| HttpResponse::MethodNotAllowed())),
    );
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .configure(config)
            .service(web::scope("/api").configure(scoped_config))
            .route("/", web::get().to(|| HttpResponse::Ok().body("/")))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```
4. `cargo run`

## Context

I was beginning to follow this example to move my application handlers into a separate module using this example, but couldn't get it work. Discovered the example code itself didn't compile.

## Your Environment

- Rust Version 1.58.1
- Actix Web Version: 4.0.0-rc.3

Thank you for the great support!

**Comment by aliemjay** [comment]
Thanks for reporting. The website is yet to be updated to actix-web v4.

It should be updated soon. In the mean time you'll likely face many broken examples.

**Comment by robjtede** [comment]
https://github.com/actix/actix-web/blob/master/actix-web/MIGRATION-4.0.md

See "returning HttpResponse synchronously" section.
