### ISSUE TITLE
Actix Requested app data is not configured correctly

### ISSUE THREAD

**Issue by stanley355** [actix/actix-web#2650]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior
How to configure the web::Data to be passed to other function?

## Current Behavior && Steps to Reproduce (for bugs)
I was creating an API and I wanted the DB to be init on main. Then I use the `web::Data` to configure it:
The code on my main was like this:
```
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();

    let pg_pool = match PgPool::connect(pg_url).await {
        Ok(pool) => Box::new(pool),
        Err(err) => panic!("Can't connect to PG POOL: {}", err),
    };

    HttpServer::new(move || {
        App::new()
            .app_data(pg_pool.clone()) //--> the issue might be here
            .route("/api/v1", web::post().to(shorten::shorten_url))
    })
    .bind("localhost...")?
    .run()
    .await
}
```

And I want it to be passed to this function:
```
pub async fn shorten_url(
  pool: web::Data<PgPool>,
  req: web::Json<response::RequestURL>,
) -> Result<HttpResponse, actix_web::Error> {
  
  let req_data = Box::new(response::ResponseURL {
    origin_url: req.origin_url.clone(),
    hashed_url: utils::hash_url(&req.origin_url),
    custom_url: req.custom_url.clone(),
  });

  println!("{:?}", pool);
  println!("{:?}", req);

  let response = db::insert_url_data(pool, req_data.clone());

  return Ok(HttpResponse::Ok().json(req_data));
}
```
The req_data can be successfully sent, however when I added `pool: web::Data<PgPool>,`. Cargo run (no error) then insomnia returns like this:
![image](https://user-images.githubusercontent.com/53996155/154268323-a7c5c424-ded3-4b7b-bff0-8d64f8a25ea8.png)

Is it the fault on my code or an error on new rc version? Anybody having similar issue?

- Rust Version (I.e, output of `rustc -V`): 1.56
- Actix Web Version: 4.0.0.rc-1 (upgrading as SQLx requires tokio 2.x)

**Comment by robjtede** [comment]
Debug logs would be able to guide you on this but essentially you're adding a `T` to the app data but trying to extract a `Data<T>` so that's not going to work.

```diff
-           .app_data(pg_pool.clone())
+           .app_data(Data::new(pg_pool.clone()))
```

**Comment by stanley355** [comment]
> Debug logs would be able to guide you on this but essentially you're adding a `T` to the app data but trying to extract a `Data<T>` so that's not going to work.
> 
> ```diff
> -           .app_data(pg_pool.clone())
> +           .app_data(Data::new(pg_pool.clone()))
> ```

@robjtede Thanks, I tried however there was this issue:
```
Thread 'actix-rt|system:0|arbiter:0' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks
```
Should I use Arc or async await for this??
