### ISSUE TITLE
thread panic in actix-http-3.0.0-rc.3

### ISSUE THREAD

**Issue by ssokolow** [actix/actix-web#2655]
## Expected Behavior
No error message should appear in the terminal output.

## Current Behavior

I found two copies of this line in my terminal output:

```
`thread 'actix-rt|system:0|arbiter:1' panicked at 'dispatcher should not be in keep-alive phase if write_buf is not empty', /home/ssokolow/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-rc.3/src/h1/dispatcher.rs:934:13`
```

## Steps to Reproduce (for bugs)

I wasn't paying attention to the terminal at the time, so I'm not sure what I was doing to the browser at the time it happened, and I haven't figured out how to reproduce it yet.

...though, given that it appears to be [this `debug_assert!`](https://github.com/actix/actix-web/blob/master/actix-http/src/h1/dispatcher.rs#L936), I think it's a reasonable assumption that it has to be reproduced with a debug build.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.58.0 (02072b482 2022-01-11)
- Actix Web Version: 4.0.0-rc.3

**Comment by robjtede** [comment]
if you can figure out a minimal reproduction code and steps that would be extremely helpful

**Comment by ssokolow** [comment]
\*nod* I'll keep looking.

I noticed them in the log about five minutes after the fact, I'm still working on the JavaScript side of the same codebase, it hasn't happened again, and I'm not sure exactly what I've been doing differently.

**Comment by robjtede** [comment]
I've found a somewhat reliable reproduction so no pressure to figure out what's up.
