### ISSUE TITLE
mishandling of keep-alive in pipelined requests causes panic in dispatcher

### ISSUE THREAD

**Issue by ALSchwalm** [actix/actix-web#2678]
## Expected Behavior
When running a simple static file server via actix_files, clients should be able to pipeline requests within one TCP stream. 

## Current Behavior
When a client sends a pipelined request, an actix thread panics:

```
thread 'actix-rt|system:0|arbiter:0' panicked at 'dispatcher should not be in keep-alive phase if state is not none: State::SendPayload { .. }', /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0/src/h1/dispatcher.rs:929:13
```

A full backtrace is attached.

## Possible Solution

By some basic testing, removing the debug_assert at https://github.com/actix/actix-web/blob/955c3ac0c4124f3807d0ac7be647668ea831cecc/actix-http/src/h1/dispatcher.rs#L929 seems to make things work as expected, but I don't know if that's a correct solution.

## Steps to Reproduce (for bugs)
Run a trivial static file server like:

```
use actix_files::Files;
use actix_web::{App, HttpServer};

#[actix_web::main]
async fn main() {

    HttpServer::new(move || {
        App::new().service(Files::new("/static", "."))
    })
        .bind("localhost:8097").unwrap()
        .run()
        .await.unwrap();
}
```

And create a file 'example' like `echo contents > example` and start the server with `cargo run`.

Then make the attached request via netcat: `nc localhost 8097 < request.txt`. This request is two GET requests:

```
GET /static/example HTTP/1.1
GET /static/example HTTP/1.1
```

You will get back a response like:

```
HTTP/1.1 200 OK
content-length: 8
content-disposition: attachment; filename="example"
etag: "12a112d:8:6220e692:1592e92e"
content-type: application/octet-stream
accept-ranges: bytes
last-modified: Thu, 03 Mar 2022 16:02:26 GMT
date: Thu, 03 Mar 2022 16:07:01 GMT

content
HTTP/1.1 200 OK
content-length: 8
content-disposition: attachment; filename="example"
etag: "12a112d:8:6220e692:1592e92e"
content-type: application/octet-stream
accept-ranges: bytes
last-modified: Thu, 03 Mar 2022 16:02:26 GMT
date: Thu, 03 Mar 2022 16:07:01 GMT
```

Note that in the final 200 OK, the body is never received, and the server will show the thread panic message.

## Context
My company is using actix as part of a file server internally. Some tools like debian APT will attempt to pipeline requests under some circumstances and this bug causes commands like apt install to fail when connecting to the actix server.

## Your Environment

- rustc 1.56.1 (59eed8a2a 2021-11-01)
- actix-web 4.0.1
- actix-files 0.6.0
[backtrace.txt](https://github.com/actix/actix-web/files/8179284/backtrace.txt)
[request.txt](https://github.com/actix/actix-web/files/8179293/request.txt)

**Comment by ALSchwalm** [comment]
Actually, while this is an issue, I think there are additional problems with pipeline support in actix. I still see download failures with release builds. However, they cannot be reproduced as easily. I'll see if I can track them down and update this.

**Comment by robjtede** [comment]
Thanks for the report, I'll get this released now. If you find different problems please open a new issue.
