### ISSUE TITLE
wrap_fn &AppRouting  should use Arc<AppRouting>

### ISSUE THREAD

**Issue by zhuxiujia** [actix/actix-web#2681]
``` wrap_fn(|req,srv:&AppRouting|) ```  should use ```Arc<AppRouting>```

so i can use srv.clone() to  call ```let fut = srv.call(req);``` when ```async move {}```  check code done

Otherwise, the life cycle is not enough to borrow. Unable to return ServiceRespone early because ServiceRespone relies on ```ServiceRequest```, but ```ServiceRequest``` has already been consumed early (```let fut = srv.call(req);```)

**Comment by zhuxiujia** [comment]
AppRouting shoud be Export the module, otherwise it cannot be written as a function pattern

**Comment by Silentdoer** [comment]
Can you paste the minimal code and describe it in detail?

**Comment by zhuxiujia** [comment]
> Can you paste the minimal code and describe it in detail?

Here's a pseudocode.

check the token and returns normal data for HTTP 200 of JsonData

```rust
 App::new()
            .wrap_fn(|req, srv| {
                    let token = req.headers().get("access_token").clone();
                    let fut = srv.call(req);
                    async move {
                           
                            //check  permission
                            if check_fn(token).await{
                                    // here can't  return response
                                    let mut resp = req.into_response(json!({
                                        "code":-1,"msg":"permission denide!"
                                       }));
                                    return Ok(resp);
                             }
                            // let fut = srv.call(req);   if move  call to here, compiler failed again
                            let mut res = fut.await?;
                            Ok(res)
                     }
          })
```

*  As you can see, this approach simplifies the complexity of building middleware, but it is still complex

**Comment by zhuxiujia** [comment]
> Can you paste the minimal code and describe it in detail?

```rust
// AppRouting  can't be  import????
fn  auth(req:ServerRequest,srv:&AppRouting){

}
```

**Comment by robjtede** [comment]
This is working as intended. The type you receive in `srv` will change with more middleware being wrapped.

If you want to write standalone function middleware use: https://docs.rs/actix-web-lab/latest/actix_web_lab/middleware/fn.from_fn.html

Similar previous discussions about exposing private types: https://github.com/actix/actix-web/wiki/FAQ#how-can-i-return-app-from-a-function--why-is-appentry-private

**Comment by fakeshadow** [comment]
It's possible to make `wrap_fn` bound to `Clone` trait and infer the nested type's trait bound.
```rust
fn wrap_fn<Req, S: Service<Req>>(req: Req, service: S) -> impl Future<Output = Result<S::Response, S::Error>>{
    async {
        service.call(req).await
    }
}
```

Then for any service that is not exposed as clone you can always use explicit middleware to make it so.
```rust
App::new()
    .wrap(MakeCloneable) // Make AppRouting into Rc<AppRouting>.
    .wrap_fn(|req, s| async { s.call(req).await }) // you can use async await naturally.
    .wrap_fn(|req, s| async { s.call(req).await }) // clone bound is infered because both the Rc and wrap_fn closure are clone.
```

This has a base cost that every call to wrap_fn would need to call Clone so it's a tread off. But it's still better than unconditionally Rc service and adding more import types(Like from function middleware)

**Comment by lermana** [comment]
don't mean to clutter this thread, just wanted to say thanks to @robjtede for the suggestion to use `from_fn` (`actix_web_lab` as of this writing), which really simplified things for me (writing a standalone, `async` middleware function)

**Comment by zhuxiujia** [comment]
> 这是按预期工作的。您收到的类型`srv`将随着更多中间件的包装而改变。
> 
> 如果您想编写独立的函数中间件，请使用：https://docs.rs/actix-web-lab/latest/actix_web_lab/middleware/fn.from_fn.html
> 
> 之前关于公开私有类型的类似讨论：https://github.com/actix/actix-web/wiki/FAQ#how-can-i-return-app-from-a-function--why-is-appentry-private

```rust
fn handle(req:ServiceRequest,srv:&AppRouting){
    let fut = srv.call(req);
    async {
        let mut res = fut.await?;
        res.headers_mut()
            .insert(CONTENT_TYPE, HeaderValue::from_static("text/plain"));
        Ok(res)
    }
}

/// use tokio,because Rbatis specifies the runtime-tokio
#[tokio::main]
async fn main() -> std::io::Result<()> {
    //router
    HttpServer::new(|| {
        App::new()
            .wrap_fn(|req, srv| {
                handle(req,srv)
        })
}
```
error[E0412]: cannot find type `AppRouting` in this scope
  --> src\main.rs:19:35
   |
19 | fn handle(req:ServiceRequest,srv:&AppRouting){
   |                                   ^^^^^^^^^^ not found in this scope
```

```

**Comment by zhuxiujia** [comment]
> This is working as intended. The type you receive in `srv` will change with more middleware being wrapped.
> 
> If you want to write standalone function middleware use: https://docs.rs/actix-web-lab/latest/actix_web_lab/middleware/fn.from_fn.html
> 
> Similar previous discussions about exposing private types: https://github.com/actix/actix-web/wiki/FAQ#how-can-i-return-app-from-a-function--why-is-appentry-private


* as you see,wrap_fn can't move or call for any func

```rust
fn handle(req:ServiceRequest,srv:&AppRouting){
    let fut = srv.call(req);
    async {
        let mut res = fut.await?;
        res.headers_mut()
            .insert(CONTENT_TYPE, HeaderValue::from_static("text/plain"));
        Ok(res)
    }
}

/// use tokio,because Rbatis specifies the runtime-tokio
#[tokio::main]
async fn main() -> std::io::Result<()> {
    //router
    HttpServer::new(|| {
        App::new()
            .wrap_fn(|req, srv| {
                handle(req,srv)
        })
}
```
error[E0412]: cannot find type `AppRouting` in this scope
  --> src\main.rs:19:35
   |
19 | fn handle(req:ServiceRequest,srv:&AppRouting){
   |                                   ^^^^^^^^^^ not found in this scope
```

```

**Comment by zhuxiujia** [comment]
My ultimate solution (Move authorization function to module)：


* on main.rs
```rust

// you can move this method to any mod 
pub fn auth<S, B>(
    req: ServiceRequest, 
    srv: &S
) -> LocalBoxFuture<'static, Result<ServiceResponse<B>, actix_web::Error>>
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = actix_web::Error>,
    B: MessageBody,
    <S as Service<ServiceRequest>>::Future: 'static
{
    let fut = srv.call(req);
    Box::pin(async{
         fut.await
    })
}


#[tokio::main]
async fn main() -> std::io::Result<()> {
    // Start HTTP server
    HttpServer::new(|| {
        let cors = actix_cors::Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header()
            .max_age(3600);
            
        App::new()
            .route("/", web::get().to(|| async { web::Json(RespVO::from("hello".to_string())) }))
            .wrap_fn(auth)
           
    })
    .bind(&CONTEXT.config.server_url)?
    .run()
    .await
}

```

thanks...
