### ISSUE TITLE
append_header is not ergonomic ..

### ISSUE THREAD

**Issue by Silentdoer** [actix/actix-web#2682]
in V3, i can use HttpResponse::Found().header(key, value), but now i was told to use: append_header((key, value)), this should not use pair..

**Comment by robjtede** [comment]
Headers are inherently pairs. This interface has been designed to accept both name-value pairs and typed headers.

**Comment by Silentdoer** [comment]
> 
I'm sorry for the wrong description, but what I meant was that inserting a key value pair with a tuple would result in two pairs of parentheses, just like this:append_header((key, value)), If the arguments is two are key and value, then you just need is one pair of parentheses, like this:append_header(key, value)

**Comment by robjtede** [comment]
The decision to take one argument makes it possible to support these both in one method:

```rust
.append_header(ContentType::json())
.append_header(("content-type", "application/json"))
```

I know it seems weird at first but this is a net win for ergonomics.

**Comment by Silentdoer** [comment]
well, thanks for your explain.
