### ISSUE TITLE
How decode a struct(json) in from field form? (using serde(with)) is ignored)

### ISSUE THREAD

**Issue by mamcx** [actix/actix-web#2688]
### Discussed in https://github.com/actix/actix-web/discussions/2686

I think I hit a bug, or at least, an unexpected behavior:

- A failed parse of a form field SILENTLY fail and only using tracing I noted why.
- Is not possible to round-trip a composite structure that uses JSON and/or Display/FromStr

----

I have some struct that needs to travel with the form:

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Clock {
    /// An Id that identifies the partition (user, device, etc) that request the change
    pub actor: String,
    /// The version is a monotonical mark of the changes applied to the data
    pub version: usize,
    /// A timestamp in UTC used for last-updated-win semantics.
    pub t: DateTime<Utc>,
}

Clock {
        actor: "system",
        version: 0,
        t: 2022-03-04T19:59:01.970994Z,
    }

// IMPORTANT: Display is: "system-0-1646423941970994000"

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LineForm {
    pub dot: Clock,
}
```

Now the problem is that the field is not decoded back. I tried (using tera) like this:

```html
"{{row.dot | json_encode() }}"

<input type="hidden" name="dot" value = "{&quot;actor&quot;:&quot;system&quot;,&quot;version&quot;:0,&quot;t&quot;:&quot;2022-03-04T19:59:01.970994Z&quot;}" />

ERROR: Error for Option<T> extractor: Content type error.

"{{row.dot | json_encode() | safe }}"

<input type="hidden" name="dot" value ="{"actor":"system","version":0,"t":"2022-03-04T19:59:01.970994Z"}" />`

ERROR: Error for Option<T> extractor: Parse error: invalid type: string "{", expected struct Clock.
```

I tried to customize the serde attributes:

```rust
    #[serde(with = "from::serde_str")] //Using FromStr/Display
    pub dot: Clock,
```

```html
"{{row.dot | json_encode() | safe }}"

<input type="hidden" name="dot" value = "system-0-1646423941970994000" />

ERROR:  Parse error: invalid type: string "system-0-1646423941970994000", expected struct Clock.
```

P.D: Is with Actix 4.0.1, tera = "1.15.0"

**Comment by robjtede** [comment]
Actix Web doesn't implement (de)serialization. I suggest asking in serde/tera repos/chats.

**Comment by mamcx** [comment]
But the problem is that the Extractor (that _is doing deserialization_) is failing:

> ERROR: Error for Option<T> extractor: Parse error: invalid type: string "{", expected struct Clock.

This is the actix side. Tera fail too, in WRITE the value, but I think actix is failing in READ the value?.


and is not using the info from serde. I see the Form<T> extractor use URL decoding, but can't figure in what moment it "knows "  that " expected struct Clock."

**Comment by robjtede** [comment]
We delegate deserializtion to `serde_json` and `serde_urlencoded` so do some tests with those crates directly to nail down where the issue is. Or come up with a minimal complete reproduction that I can run to debug with.

**Comment by mamcx** [comment]
Ah great, I fail to see that the url_decoding was not part of actix. Thanks for the patiente
