### ISSUE TITLE
Actix Multipart not working.

### ISSUE THREAD

**Issue by krishnaTORQUE** [actix/actix-web#2711]
Actix Multipart not working.
I tried to follow this example below from docs
https://docs.rs/actix-multipart/0.4.0/actix_multipart/struct.Multipart.html#server-example

Code
```rust
use actix_multipart::Multipart;
use actix_web::{web, App, HttpRequest, HttpResponse, HttpServer};
use std::{io, str};

async fn upload(mut payload: Multipart) -> HttpResponse {
    while let Some(mut item) = payload.next().await {
        while let Some(chunk) = item.unwrap().next().await {
            println!("-- CHUNK: \n{:?}", str::from_utf8(&chunk.unwrap()));
        }
    }

    HttpResponse::Ok().body("Done")
}
```

Error
`no method named "next" found`

_Originally posted by @krishnaTORQUE in https://github.com/actix/actix-web/discussions/2710_

**Comment by robjtede** [comment]
You've deleted the StreamExt import from that example.

**Comment by krishnaTORQUE** [comment]
Oops Sorry. My bad
