### ISSUE TITLE
uring 0.2.0 makes actix panic as runtime is inited with 0.3.0

### ISSUE THREAD

**Issue by SchrodingerZhu** [actix/actix-web#2716]
https://github.com/actix/actix-web/blob/2fed9785972f964ecc1a27afca8705c3087aa17c/actix-files/Cargo.toml#L43

**Comment by SchrodingerZhu** [comment]
I suggest refactoring this part by exposing uring via `actix-rt` and do not direct use `tokio-uring` in dependent libs.

**Comment by SchrodingerZhu** [comment]
Hi, this should be a blocking error for uring usage. Is there anyone working on this?

**Comment by robjtede** [comment]
It would be done except the io-uring tests on our CI started failing after the update and I haven't got a Linux box handy to test on.

**Comment by robjtede** [comment]
fixed in master
