### ISSUE TITLE
`/` and `%2F` are treated differently

### ISSUE THREAD

**Issue by vporton** [actix/actix-web#2726]
## Expected Behavior
`%2F` in URL is another way to say `/`.

## Current Behavior

For
```rust
#[get("/p/{url}")]
```

`/` and `%2F` are treated differently. URLs like `https://example.org/xx%2Fyy` are accepted but `https://example.org/xx/yy` rejected.

## Possible Solution
`%2F` should be replaced by `/` before parsing the URL.

## Context
I got OK during testing but error 404 in production environment. (Google replaces `%2F` by `/` when I submit an URL.)

## Your Environment
Google.

- Rust Version (I.e, output of `rustc -V`): rustc 1.58.1 (db9d1b20b 2022-01-20)
- Actix Web Version: 4.0.1

**Comment by robjtede** [comment]
There's good docs here about how the routes are matched:  
- https://actix.rs/actix-web/actix_web/dev/struct.ResourceDef.html
- https://actix.rs/actix-web/actix_web/struct.HttpRequest.html#percent-encoding-and-url-parameters

In particular it looks like you want a tail match:  
https://actix.rs/actix-web/actix_web/dev/struct.ResourceDef.html#tail-segments

This is working as intended, as it's not possible to decode these at the router level and retain path integrity.
