### ISSUE TITLE
regex dependency should be updated, as stated by the deps.rs security report

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [actix/actix-web#2732]
- Actix Web Version: 4.0.1

https://deps.rs/crate/actix-web/4.0.1
states:
`regex ⚠️	required ^1.4 latest: 1.5.5	maybe insecure`

the vulnerability states:
`Unaffected: None        Patched:>=1.5.5`

So in my eyes simply the update of regex to 1.5.5 should make the vulnerability report green again.

**Comment by cguentherTUChemnitz** [comment]
Mh i looked it up again and saw that regex 1.5.5. is already used as fixed dependency version. https://github.com/actix/actix-web/blob/master/actix-web/Cargo.toml
So any idea here, why the report says it otherwise?

**Comment by robjtede** [comment]
fixed in master, just awaiting release

to close the vuln in your own project just run `cargo update`
