### ISSUE TITLE
actix 4.0.1 with oauth2 error

### ISSUE THREAD

**Issue by lpf763827726** [actix/actix-web#2737]
i try to use `oauth2 = "4.1.0"` in `actix = "4.0.1"`, but it return error
```
thread 'actix-rt|system:0|arbiter:3' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/sp2/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/shutdown.rs:51:21
```

i used to run it in `actix = "3.3.2"`, it working, but i try to use with `async-graphql = "3.0.38"` and `async-graphql-actix-web = "3.0.38"` now, it can't work

**Comment by lpf763827726** [comment]
BTW, my oauth2 code

```
let token_result = client
        .exchange_code(AuthorizationCode::new(code))
        .set_pkce_verifier(PkceCodeVerifier::new(pkce_verifier))
        .request(http_client)   # error from here
        .map_err(|err| {
            error!("Failed to exchange access token with oauth code, error: {}", err);
            AppError::BadRequestError("Failed to exchange access token with oauth code!".to_string())
        })?;
```

**Comment by robjtede** [comment]
The error is coming from something related to `async-graphql` or in your code so I can't offer much help here.

Firstly, run your app with `RUST_BACKTRACE=1 cargo run` to see where the panic comes from. This message often comes from `block_on` used incorrectly, like with a Tokio runtime `Handle` so check for those too.

You can use these as reference to guide your changes if it looks to be dependency related in any way:
- https://github.com/actix/examples/tree/master/graphql/async-graphql
- https://github.com/async-graphql/async-graphql/tree/master/integrations/actix-web
