### ISSUE TITLE
`spawn`'ed `HttpServer` is not interruptible

### ISSUE THREAD

**Issue by ueno** [actix/actix-web#2739]
I'm trying to run another async task alongside the main `HttpServer`, something like:

```rust
#[tokio::main]
async fn main() -> std::io::Result<()> {
    let server = HttpServer::new(|| App::new().service(greet))
        .bind("127.0.0.1:8080")?
        .run();
    let server_task = tokio::spawn(server);
    let worker_task = tokio::spawn(do_stuff_async());
    let _ = tokio::try_join!(server_task, worker_task)
        .expect("unable to join tasks");
    Ok(())
}
```
(The complete code can be found in this [repository](https://github.com/ueno/actix-web-4-spawn))

While it generally works, I cannot terminate the process with `ctrl-c`. If I add `.disable_signals()` to the server creation, it works, though I expect that signals are handled more gracefully by [default](https://github.com/actix/actix-net/blob/dc67ba770d1600fb4492e32565c8a414fc403245/actix-server/src/server.rs#L319).

## Expected Behavior
The process should exit when `ctrl-c` is received.

## Current Behavior
The process keeps running after `ctrl-c` is received.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
See above.

## Context
This came out of https://github.com/keylime/rust-keylime/pull/334, where we want to wait for ZeroMQ notification while serving a REST service.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.56.0 (09c42c458 2021-10-18)
- Actix Web Version: 4.0.1

**Comment by robjtede** [comment]
This is expected behavior given your task set up. Here's a solution that avoids using `select!`s.

```rust
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};

use actix_web::{get, web, App, HttpServer, Responder};

async fn do_stuff_async(shutdown_marker: Arc<AtomicBool>) -> std::io::Result<()> {
    loop {
        if shutdown_marker.load(Ordering::SeqCst) {
            break;
        }

        tokio::time::sleep(tokio::time::Duration::from_millis(1000)).await;
        println!("do_stuff_async");
    }

    Ok(())
}

#[get("/hello/{name}")]
async fn greet(name: web::Path<String>) -> impl Responder {
    format!("Hello {}!", name)
}

#[tokio::main]
async fn main() -> std::io::Result<()> {
    let server = HttpServer::new(|| App::new().service(greet))
        .bind("127.0.0.1:8080")?
        // disable default signal handling
        .disable_signals()
        .run();

    let server_handle = server.handle();
    let task_shutdown_marker = Arc::new(AtomicBool::new(false));

    let server_task = tokio::spawn(server);
    let worker_task = tokio::spawn(do_stuff_async(Arc::clone(&task_shutdown_marker)));

    let shutdown = tokio::spawn(async move {
        // listen for ctrl-c
        tokio::signal::ctrl_c().await.unwrap();

        // start shutdown of tasks
        let server_stop = server_handle.stop(true);
        task_shutdown_marker.store(true, Ordering::SeqCst);

        // await shutdown of tasks
        server_stop.await;
    });

    let _ = tokio::try_join!(server_task, worker_task, shutdown).expect("unable to join tasks");

    Ok(())
}
```

**Comment by ueno** [comment]
@robjtede thank you so much for the suggestion!
