### ISSUE TITLE
re-export actix_http::Request

### ISSUE THREAD

**Issue by tobdub-snce** [actix/actix-web#2746]
## Expected Behavior
I can use `actix_http::Request` without having to include a dependency to `actix-http`.

## Current Behavior
`actix_http::Request` is returned from some APIs, but not re-exported?

See e.g., https://docs.rs/actix-web/4.0.1/actix_web/test/fn.init_service.html

## Possible Solution
Re-export `actix_http::Request`.

## Context
I have to add `actix-http` as a dependency and make sure it is in sync with the version used by `actix-web`.

## Your Environment
- Linux Version: 5.4
- Rust Version: 1.60.0
- Actix Web Version: 4.0.1

**Comment by robjtede** [comment]
We're trying to make it easy to understand where the different request types are coming from so this is unlikely to be added as a re-export even though it is technically exposed in the `init_service` return type as you have pointed out.
