### ISSUE TITLE
add ClientRequestBuilder::form()

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#276]
`ClientRequestBuilder::form()` should be similar to `ClientRequestBuilder::json()` but it should encode payload with `application/x-www-form-urlencoded`.

Do we need to support `form()` on server side?

**Comment by DoumanAsh** [comment]
>Do we need to support form() on server side?

I don't think so, at least I cannot think of use case.
But if we're going to name it `form` I'd suggest to rename `HttpMessage::urlencoded` to `HttpMessage::form`

**Comment by fafhrd91** [comment]
closed by #306
