### ISSUE TITLE
Server deployment error

### ISSUE THREAD

**Issue by Jzow** [actix/actix-web#2761]
I deployed the service on the CentOS server, but requested 502

```rust

#[tokio::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/hello", web::get().to(|| async { "api server run successed" }))
            .service(user_api::register)
    })
    .bind(("localhost", 8082))?
    .run()
    .await
}
```
Do I need to fill in the server IP address for my localhost? Or what

**Comment by Jzow** [comment]
There was an error when I filled in my server IP
Error: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }

The port service monitored by the program is normal, and there is a 502 error when another machine accesses the server service

**Comment by zonghenghaunyu** [comment]
I also encountered this problem, Only the current machine can access this port. 
Other machines cannot access, even in the same LAN. 
Have you solved it?

**Comment by zonghenghaunyu** [comment]
I got it

**Comment by dullkingsman** [comment]
@zonghenghaunyu how did you fix this?

**Comment by robjtede** [comment]
Likely by using 0.0.0.0 as the bind address instead of localhost.

**Comment by arturs706** [comment]
Whats the port? for 0.0.0.0.
Want to deploy on render
