### ISSUE TITLE
Performance degradation in release mode on Apple Silicon (M1 Max)

### ISSUE THREAD

**Issue by joshualex** [actix/actix-web#2768]
## Expected Behavior
I'm trying to run the following code and benchmark its performance:

```rust
use actix_web::{post, web::Json, App, HttpResponse, HttpServer, Responder};
use serde::Deserialize;
use serde_json::json;

#[derive(Deserialize)]
struct Payload {
    param: String,
}

#[post("/")]
async fn route_func(params: Json<Payload>) -> impl Responder {
    HttpResponse::Ok().json(json!({
        "param": params.param
    }))
}

#[tokio::main]
async fn main() {
    let server = HttpServer::new(|| App::new().service(route_func));

    server.bind(("0.0.0.0", 8000)).unwrap().run().await.unwrap();
}
```

Benchmarking is done with:
```
$  hey -m POST -H "Content-type: application/json" -d '{"param": "test"}' http://127.0.0.1:8000
```
(I get similar results from other benchmarking tools).

I am conducting two runs - one in debug mode, and one in release. My expectations are for the release mode to be at least as fast as the debug mode build, if not faster :-)

The tests are all conducted on an Apple Silicon M1 Max (2021 16" Macbook Pro)

## Current Behavior

In Debug mode:
```

Summary:
  Total:	0.0080 secs
  Slowest:	0.0035 secs
  Fastest:	0.0003 secs
  Average:	0.0017 secs
  Requests/sec:	25014.7243

  Total data:	3400 bytes
  Size/request:	17 bytes

Response time histogram:
  0.000 [1]	|■
  0.001 [11]	|■■■■■■■■■
  0.001 [23]	|■■■■■■■■■■■■■■■■■■
  0.001 [32]	|■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.002 [50]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.002 [31]	|■■■■■■■■■■■■■■■■■■■■■■■■■
  0.002 [2]	|■■
  0.003 [0]	|
  0.003 [9]	|■■■■■■■
  0.003 [22]	|■■■■■■■■■■■■■■■■■■
  0.004 [19]	|■■■■■■■■■■■■■■■


Latency distribution:
  10% in 0.0007 secs
  25% in 0.0011 secs
  50% in 0.0015 secs
  75% in 0.0027 secs
  90% in 0.0032 secs
  95% in 0.0033 secs
  99% in 0.0035 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0004 secs, 0.0003 secs, 0.0035 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0002 secs
  resp wait:	0.0013 secs, 0.0002 secs, 0.0021 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0005 secs

Status code distribution:
  [200]	200 responses
```

While in Release:

```

Summary:
  Total:	0.0122 secs
  Slowest:	0.0068 secs
  Fastest:	0.0002 secs
  Average:	0.0023 secs
  Requests/sec:	16363.3207

  Total data:	3400 bytes
  Size/request:	17 bytes

Response time histogram:
  0.000 [1]	|■
  0.001 [20]	|■■■■■■■■■■■■■■■
  0.001 [30]	|■■■■■■■■■■■■■■■■■■■■■■■
  0.002 [36]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.003 [53]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.003 [27]	|■■■■■■■■■■■■■■■■■■■■
  0.004 [24]	|■■■■■■■■■■■■■■■■■■
  0.005 [3]	|■■
  0.005 [0]	|
  0.006 [1]	|■
  0.007 [5]	|■■■■


Latency distribution:
  10% in 0.0008 secs
  25% in 0.0015 secs
  50% in 0.0023 secs
  75% in 0.0029 secs
  90% in 0.0037 secs
  95% in 0.0039 secs
  99% in 0.0065 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0002 secs, 0.0002 secs, 0.0068 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0001 secs, 0.0000 secs, 0.0014 secs
  resp wait:	0.0017 secs, 0.0001 secs, 0.0027 secs
  resp read:	0.0001 secs, 0.0000 secs, 0.0014 secs

Status code distribution:
  [200]	200 responses
```

It appears that:

1. The slowest request is much slower in release mode
2. The average time for request serving has increased
3. The overall time needed to perform 200 requests as increased...

## Your Environment

- Rust Version (I.e, output of `rustc -V`): `rustc 1.61.0 (fe5b13d68 2022-05-18)`
- Actix Web Version: 4.0.1

**Comment by joshualex** [comment]
I am not sure the problem is indeed within actix-web, but I have no idea how to start investigating it otherwise...

**Comment by joshualex** [comment]
I found that performance improves when changing `tokio::main` to `tokio::main(flavor="current_thread")`. Requests/sec goes up in release mode to 36k when applying that change...

**Comment by robjtede** [comment]
There's nothing we can do about this really. The thread scheduler on M1 chips must prefer having fewer threads running per process. Good to know that it gets better when using current_thread mode.

**Comment by joshualex** [comment]
@robjtede that explanation doesn't sound convincing to me... If that were the case, why would release mode perform worse than debug?

**Comment by joshualex** [comment]
Also, when trying a plain tokio app that responds "naively" to http (just an incoming socket server spawning handling tasks, reading until \r\n and replying HTTP ok directly) - performance indeed improves in release mode, so the problem must reside in one of the abstractions being used on top of tokio IMO

**Comment by robjtede** [comment]
> why would release mode perform worse than debug?

I don't know, could be any number of reasons. ARM is not a tier 1 supported target for rustc and it's a new CPU arch anyway.

Given this problem is arch-specific, it's not something we can do anything about because Actix Web doesn't have any arch-specific code. I acknowledge that it's an issue but it's not an issue _here_.

**Comment by joshualex** [comment]
Ok, fair enough. Thanks!
