### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by axon-q** [actix/actix-web#279]
Is there an easy way to process file uploads from a browser (multipart/form-data) in actix-web? I can see that there's some kind of multipart support in the API docs, but it doesn't have much explanation. I've looked at [examples/multipart](https://github.com/actix/examples/blob/master/multipart/src/main.rs), but it appears to be very low-level. Is there a better API or a more complete example somewhere?

**Comment by fafhrd91** [comment]
if you really need efficient file upload you should use multipart api.

**Comment by axon-q** [comment]
Is there some documentation or a complete example that demonstrates the recommended way to use this API to handle file uploads, and explains all the combinators and trait methods needed to make this work?

**Comment by fafhrd91** [comment]
this examples shows how to read file too https://github.com/actix/examples/tree/master/multipart

there is python upload example 
https://github.com/actix/examples/blob/master/multipart/client.py

**Comment by axon-q** [comment]
Yes, that example is where I started. ;) Here are the problems I ran into with it:

1. The multipart processing seems to be incomplete: the form data in the Content-Disposition header is not parsed. This data will contain at least a `name` field and, for file transfers, also a `filename` field. This is documented in [RFC 7578](https://tools.ietf.org/html/rfc7578#section-4.2). (Note that there's [considerable confusion](https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http) around the encoding of the filename parameter.)
1. It's hard to understand how the `index` function in the example works, especially if you're not very familiar with Futures/Streams. Part of the difficulty is that some of the methods and types come from the `futures` crate, while others are extensions coming from `actix` or `actix-web` that don't have much documentation. For example, what's the difference between the `finish()` method from `actix::FinishStream` used in the example, and Stream's native `for_each` method (which also seems to work here)? A higher-level explanation of what's going on in this function and how each step works would help a lot.
1. How are errors handled? What happens if the client aborts or the network fails in the middle of a transfer? Can the incomplete transfer be detected?
1. How can the maximum size of an uploaded file be set? What will happen if the limit is exceeded?
1. How are nested multipart items meant to be handled? The example just returns `Ok(())` if it hits one. (This probably doesn't matter for file uploads, but it's still confusing.)

**Comment by fafhrd91** [comment]
a lot of questions! and i dont have answers at the moment. someone need to contribute answers.
eventually i will work on this, but at the moment i have higher priority tasks for actix

**Comment by axon-q** [comment]
@fafhrd91 I understand! You're doing great work with actix-web. :) Actually, I think the only code change needed is the Content-Disposition parsing, and maybe the ability to limit upload size if that's not already possible. The other points are probably just documentation items.

For Content-Disposition, it looks like there's already code to parse it in [src/header/common/content_disposition.rs](https://github.com/actix/actix-web/blob/master/src/header/common/content_disposition.rs), but this type is [excluded](https://github.com/actix/actix-web/blob/master/src/header/common/mod.rs#L16) from the exports for some reason. Is it possible to make this code available to users?

**Comment by fafhrd91** [comment]
would you provide PR for content-disposition?

**Comment by fafhrd91** [comment]
btw #282 ticket contains good example of file upload

**Comment by fafhrd91** [comment]
i updated multipart example https://github.com/actix/examples/blob/master/multipart/src/main.rs

**Comment by axon-q** [comment]
@fafhrd91 OK, another item is limiting the upload size. Right now if you have an `HttpRequest` you can call `req.body().limit(...)`. I think the same `limit` method is needed for multipart. But this looks like it will require modifying the multipart Stream implementation.

**Comment by fafhrd91** [comment]
do you really need `limit`? it understandable with `req.body()` because it loads payload to a memeory. but with multipart you get byte chunks as the server receives them. actix does not accumulate data in memory.

**Comment by axon-q** [comment]
Oh, I think you're right. I did some testing and saw very large chunks, but that was over a loopback interface. Over a network I assume the chunk size is bounded by the size of the receiver TCP socket buffer. In that case we don't need `limit` since the handler has full control and can fail the request early if it grows too large.

OK! With #284 and the updated multipart example, I think this can be closed, unless you want to keep it open to track docs/ergonomics improvements. Thanks!
