### ISSUE TITLE
add `rust-version` to Cargo.toml files

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#2791]
Declare our MSRV in the manifest. Should be done for v5 so that folks pinning transitive deps on v4 can still use it on older compilers.

**Comment by silverpill** [comment]
`rust-version` was added in actix-web 4.4.0 and set to 1.68, so now it can't be used with older compilers even if transitive dependencies are pinned to compatible versions. Can `rust-version` be changed to the version that actix itself requires?

**Comment by robjtede** [comment]
Thanks for the comment here. Actix Web itself does require a Rust version > 1.68.
