### ISSUE TITLE
set_camel_case_headers does not camel case all headers

### ISSUE THREAD

**Issue by letto4135** [actix/actix-web#2796]
## Expected Behavior
Using `res.head_mut().set_camel_case_headers(true);` should set all headers to camel case.

## Current Behavior
Several headers are not included as the headers that are have been explicitly specified.
Authorization and Location are both lowercase.

## Possible Solution
Possibly just don't change the case of headers passed in via append_header? Not sure what that entails or if append_header does change the case, but something does along the lines.

## Steps to Reproduce (for bugs)
```
async fn redirection(req: HttpRequest) -> impl Responder {
    let auth = req.headers().get("Authorization").unwrap().to_str().unwrap();
    let mut res = HttpResponse::TemporaryRedirect()
        .append_header(("Location", "https://google.com"))
        .append_header(("Authorization", auth))
        .finish();

    res.head_mut().set_camel_case_headers(true);

    println!("{:?}", res);
    res
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new().service(redirection)
    }).bind("127.0.0.1", 8080)?.run().await
}
```

## Context
App has a redirect to another service in JS that uses passport, the header it expects is "Authorization", but what is being passed is "authorization".

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
- Actix Web Version:

**Comment by robjtede** [comment]
Using your test server I could not reproduce the bug.

```
 › echo -ne "GET / HTTP/1.0\r\nHost: localhost\r\nAuthorization: 1234\r\n\r\n" | nc localhost 8080
HTTP/1.0 307 Temporary Redirect
Content-Length: 0
Authorization: 1234
Location: https://google.com
Date: Thu, 30 Jun 2022 00:03:40 GMT
```

You left out the Actix Web version information on the issue template but I suspect your version is outdated. There has previously been issues around camel case.

**Comment by robjtede** [comment]
I would also suggest opening (or +1'ing) an issue in the JS lib you mentioned. HTTP Headers are case-insensitive so that's a bug on their end if the lowercase `authorization` doesn't match.

**Comment by robjtede** [comment]
It could also be that you're thinking that headers are not sent with camel case because of the debug print. Eg:

```
HttpResponse { error: None, res:
Response HTTP/1.1 307 Temporary Redirect
  headers:
    "location": "https://google.com"
    "authorization": "1234"
  body: Sized(0)
 }
```

Note that the debug output will **always** be lowercase. The headers on-the-wire will be correctly camel-cased when enabled, as shown from the netcat (nc) output.

**Comment by letto4135** [comment]
Interesting,
I guess I'll continue arguing with it, currently seems like the auth header isn't making it to the underlying service (the logs from the service aren't showing the auth header, and insomnia timeline of the request is showing the auth header disappears between the redirect handshaking and final get) for some reason though seems like its working on yours... >_>
Also, using actix-web = "4"

Thanks much for the insight.

**Comment by letto4135** [comment]
Theres something going on that I can't figure out... I'm attempting to rewrite an app from js and the code below works as intended, sends auth header and all..
```
app.use("/redirect", (req, res, next) => {
    res.redirect(307, url);
}
```
But using actix it behaves differently, I had to tell insomnia/postman/curl to keep the auth header on redirect, but using the js implementation I don't have to do that...
