### ISSUE TITLE
Vary header overwritten by compress middleware

### ISSUE THREAD

**Issue by iyzana** [actix/actix-web#2797]
## Expected Behavior

Adding a `Vary` header to the HttpResponses HeaderMap includes the specified value in the response to the browser.

## Current Behavior

The `Vary` header is completely overwritten to `accept-encoding` when the Compress middleware is added and needed for the request.

## Possible solution

The encoding could append to the `Vary` header if it is already set instead of replacing it.
https://github.com/actix/actix-web/blob/592b40f914c0fc6fba6c7011edd9111b0e1258dd/actix-http/src/encoding/encoder.rs#L260

## Steps to Reproduce

```rust
use actix_web::{
    get,
    http::header::{HeaderValue, ACCEPT, VARY},
    middleware, App, HttpResponse, HttpServer, Responder,
};

#[get("/")]
async fn hello() -> impl Responder {
    HttpResponse::Ok()
        .append_header((VARY, HeaderValue::from_name(ACCEPT)))
        .body("Hello world!")
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .wrap(middleware::Compress::default())
            .service(hello)
    })
    .bind(("127.0.0.1", 8081))?
    .run()
    .await
}
```

```sh
curl -v localhost:8081 -H 'Accept-Encoding: gzip'
```

## Context

I am writing a handler that responds differently based on the `Accept` header and allows the client to cache the response, so the `Vary` header should include `Accept` in the response.

## Your Environment

- rustc 1.59.0 (9d1b2106e 2022-02-23)
- actix-web 4.1.0

**Comment by robjtede** [comment]
fix released in actix-http v3.2.0
