### ISSUE TITLE
Why does the other handler gets triggered?

### ISSUE THREAD

**Issue by megahomyak** [actix/actix-web#2802]
My code:
```
App::new()
    .app_data(web::Data::from(website.clone()))
    .route("/", web::get().to(routes::index))
    .route("/{filename}", web::get().to(routes::file))
```
When I make a request to `/`, the handler for `/{filename}` _sometimes_ gets called for some reason when making repeating requests to . Why does `/{filename}`'s handler gets triggered?

Full code:
* `routes::index`: https://github.com/megahomyak/blog/blob/dev/src/routes/index.rs
* `routes::file`: https://github.com/megahomyak/blog/blob/dev/src/routes/file.rs
* `main` (the origin of the snippet above): https://github.com/megahomyak/blog/blob/dev/src/main.rs
Maybe it happens because of the shared between handlers `website`, which gets locked in `routes::index`, but that should not be the reason for choosing the wrong handler.

## Steps to Reproduce
```
use std::io;

use actix_web::{http::StatusCode, web, App, HttpResponse, HttpServer};

#[allow(clippy::unused_async)]
async fn root() -> HttpResponse {
    println!("Inside the `root`");
    HttpResponse::new(StatusCode::OK)
}

#[allow(clippy::unused_async)]
async fn blah() -> HttpResponse {
    println!("Inside the `blah`");
    HttpResponse::new(StatusCode::OK)
}

#[actix_web::main]
async fn main() -> io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/", web::get().to(root))
            .route("/{blah}", web::get().to(blah))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
```
1. Run the thing above (the only dependency is `actix-web="4.0.1"`)
2. Go to http://127.0.0.1:8080/ in your browser
3. Spam/hold F5 to reload the page (on my machine (Windows + Firefox 101.0.1 (64-bit)), holding F5 for a while and then letting go always produces the desired behaviour)
4. See "blah" appearing in the console sometimes

## My Environment

- Rust Version (I.e, output of `rustc -V`): `rustc 1.61.0 (fe5b13d68 2022-05-18)`
- Actix Web Version: `actix-web = "4.0.1"`

**Comment by robjtede** [comment]
In the absence of a relevent meta tag, browsers will request `/favicon.ico` in addition to index pages.

Eg:
![2022-07-01_07 38 32-28ecb9a9](https://user-images.githubusercontent.com/3316789/176838582-8de5baf5-e978-4b00-8673-07f3b6955473.png)

If you stress test a server using a command line tool instead of a browser, you will never see the `/{blah}` route get hit.

**Comment by megahomyak** [comment]
Sorry, completely forgot about it
