### ISSUE TITLE
`GuardExt` extension trait

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#2807]
provides easier `.and()` and `.or()` guard combinators

**Comment by jporwal05** [comment]
Hi @robjtede - I would like to work on this. However, I am a newbie and would like to pick this up as first issues. I believe this would be relatively easier as it would not be a breaking change. Please guide!

**Comment by jporwal05** [comment]
Hi @robjtede! I was looking at the `Guard` trait in context to this ticket. I wanted to confirm my understanding for the same.
Current state:
```rust
App::new().service(
            web::scope("/")
                .guard(guard::Header("x-guard", "demo"))
                .guard(TokenHeader("Authorization", "bearer")) // TokenHeader is a custom guard
                .route("", web::get().to(hello)),
        )
```
Target state:
```rust
App::new().service(
            web::scope("/")
                .guard(guard::Header("x-guard", "demo").and(TokenHeader("Authorization", "bearer")))
                .route("", web::get().to(hello)),
        )
```

Is my understanding correct? Please advise!

**Comment by robjtede** [comment]
Yes, I think the original idea for this issue was an API like that.

**Comment by jporwal05** [comment]
> Yes, I think the original idea for this issue was an API like that.

I was reading the documentation and noticed that we do have `All` and `Any`, and these are similar to what we are trying to achieve.
```rust
web::route()
    .guard(
        guard::All(guard::Get())
            .and(guard::Header("accept", "text/plain"))
    )
    .to(|| HttpResponse::Ok());
```
```rust
web::route()
    .guard(
        guard::Any(guard::Get())
            .or(guard::Post()))
    .to(|| HttpResponse::Ok());
```

Do we have any other use case that I am missing? @robjtede

**Comment by robjtede** [comment]
Not that I can think of; so, it's possible that this isn't worth it just to save the off `guard::All(_)` wrapper.

**Comment by jporwal05** [comment]
Yes. In addition, introducing `and` and `or` combinators directly(without `All` and `Any`) will introduce a possibility where a user can do something like:
```rust
.guard(guard1.and(guard2).or(guard3).and(guard4))
```
and this will start to become non-deterministic in terms of readability and operator precedence, which, currently `All` and `Any` prevent against.

Shall we close this?

**Comment by robjtede** [comment]
Yep, I agree with that point.
