### ISSUE TITLE
ClientRequest silently fails without `alpn` or `tls` feature

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#283]
This is with the core `Actix` framework that I'm seeing this.

I have an Actor that is basically like this:

```
pub struct Forwarder {
    url: String
}

impl Handler<Message> for Forwarder {
    type Result = ResponseFuture<(), Error>;

    fn handle(&mut self, msg: Message, _ctx: &mut Self::Context) -> Self::Result {

        Box::new(ClientRequest::post(&self.url)
                .json(msg)
                .unwrap()
                .send()
                .from_err()
                .map(|resp| {
                    debug!("{:?}", resp);
                }))

    }
}
```

If the url is set to `https://<some_url>` and you don't have `alpn` or `tls` enabled, this silently fails. 

I have a feeling I haven't set up error handling correctly in Actix

**Comment by fafhrd91** [comment]
Do you log errors? 

You should get [this error](https://github.com/actix/actix-web/blob/master/src/client/connector.rs#L125) if alpn or tls are not enabled

**Comment by fafhrd91** [comment]
@cetra3 ping

**Comment by cetra3** [comment]
Sorry, I haven't had time to reduce this issue down. I'll see if I can make an example project and raise an issue again if I can replicate it

**Comment by fafhrd91** [comment]
@cetra3 ping

**Comment by cetra3** [comment]
@fafhrd91 To explain it a bit more, I have an actor which has a list of addresses, and just does a `do_send` on each, and logs out an error if there is any problems.   I.e,

```rust
pub struct BroadcastServer {
    sessions: Vec<Recipient<Syn, Message>>
}

impl Handler<Message> for BroadcastServer {

    type Result = Result<(), Error>;

    fn handle(&mut self, msg: Message, _ctx: &mut Self::Context) -> Self::Result {

        debug!("Received message: `{:?}`", msg);

        for session in self.sessions.iter() {
            match session.do_send(msg.clone()) {
                Ok(()) => {

                },
                Err(err) => {
                    error!("Could not broadcast to actor:{:?}", err);
                }
            }
        }

        Ok(())
    }
}
```

Looking at the API, it appears that the error from the actors at the other end of the address may not propagate accordingly unless I use the `send` method?  In which case I may need to rewrite this broadcast actor.

**Comment by fafhrd91** [comment]
`.do_send()` is for send and forget. in general case you can not get response immediately. if you need response then you have to use `.send()` and you have to wait on it.

**Comment by cetra3** [comment]
I'll close this issue off then, looks like the right thing is happening in this case.
