### ISSUE TITLE
Wrong default text encoding, not UTF-8

### ISSUE THREAD

**Issue by KonradHoeffner** [actix/actix-web#2836]
## Expected Behavior

According to <https://www.w3schools.com/charsets/ref_html_utf8.asp>, UTF-8 is the HTML 5 default text encoding and thus it should only be necessary to specify the encoding, when it is **not** UTF-8.

## Current Behavior

By default, Actix Web uses a different character encoding. unfortunately I don't see which one because Firefox and Chrome removed those options.

## Possible Solution

Set UTF-8 encoding by default.

## Steps to Reproduce

1. Create an HttpServer and run it
2. Serve `HttpResponse::Ok().content_type("text/html").body("<!DOCTYPE html><html><body>öüä<h1></h1></body></html>")`
3. The content is shown incorrectly both in Firefox Developer Edition 104 and Chromium 104, they will show `Ã¶Ã¼Ã¤` instead of `öüä`

This problem can be avoided by setting content type to  `text/html; charset=utf-8` or `<head><meta charset="UTF-8"></head>`, however as it is the default, it shouldn't be necessary.

## Context

Serving HTML content with non-English characters.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): 1.63.0
- Actix Web Version: 4.1.0
- Firefox Version: 104
- Chromium Version: 104

**Comment by robjtede** [comment]
Actix Web will not change your input of "text/html". To send a response with UTF-8 encoding specified, use one of the following:
- `Html(html)` from `actix-web-lab`
- `HttpResponse::Ok().content_type(ContentType::html())`
- `HttpResponse::Ok().insert_header(ContentType::html())`
- `HttpResponse::Ok().content_type("text/html; charset=utf-8")`
