### ISSUE TITLE
Server does not start when `spawn`ed

### ISSUE THREAD

**Issue by rollandjb** [actix/actix-web#2837]
## Expected Behavior

According to the documentation [here](https://actix.rs/docs/server/):

> [...]The `Server` must be `await`ed or `spawn`ed to start processing requests [...]

## Current Behavior

It seems that `spawn`ing the server does not start the server

## Possible Solution

I have insufficient rust experience to offer suggestions

## Steps to Reproduce (for bugs)

This code demonstrates the problem. See context below for explanation.

```rust
use std::{
    sync::mpsc::{self, Sender},
    thread,
};

use actix_web::{
    self, get,
    rt::System,
    web::{self},
    App, HttpRequest, HttpServer,
};
use anyhow::{Error, Result};

#[actix_web::main]
async fn main() -> Result<()> {
    //
    // run the server and wait to receive the secret from the handler
    let secret = run_http_server().await?;

    println!("{}", secret);
    Ok(())
}

struct AppState {
    tx: Sender<String>,
}

#[get("/")]
async fn index(req: HttpRequest, data: web::Data<AppState>) -> String {
    println!("==> handler for {} has started...", req.uri());
    let _ = &data.tx.send(String::from("the secret is 42 or 'xyzzy'"));
    format!("Hello, world!\n")
}

async fn run_http_server() -> Result<String> {
    let (tx_result, rx_result) = mpsc::channel();

    let server = HttpServer::new(move || {
        App::new()
            .app_data(web::Data::new(AppState {
                tx: tx_result.clone(),
            }))
            .service(index)
    })
    .shutdown_timeout(60)
    .bind("127.0.0.1:4242")?
    .run();

    //
    // ask user to call the server
    println!("please run the cmd 'curl http://127.0.0.1:4242' to get the secret");

    let server_handle = server.handle();

    //
    // this starts the http server
    let _server_task = thread::spawn(move || System::new().block_on(server));   // A

    //
    // neither of these start the http server
    // let _server_task = rt::spawn(server);                                    // B
    // let _server_task = rt::spawn(async move { server.await });               // C

    //
    // Wait for the result to be delivered
    let values = rx_result.recv();

    //
    // Stop the server
    server_handle.stop(true).await;

    //
    // return the secret sent from the handler
    values.map_err(|e| Error::new(e))
}


```

1. Add `actix-web` and `anyhow` crates to project
2. Run with `cargo run`
3. Run the command `curl http://127.0.0.1:4242` in a terminal 
4. Observe the secret is received as expected
5. Comment out line `A` and uncomment either of `B` or `C`
6. Observe that the handler does not run 

## Context
I am trying to run a temporary http server in the background and receive information sent from a handler called on that server.

## Your Environment
I am running an development in vs code on a MacBook Pro M1 Max

- Rust Version (I.e, output of `rustc -V`): `rustc 1.62.1 (e092d0b6b 2022-07-16)`
- Actix Web Version: 4.1.0

**Comment by Chaostheorie** [comment]
Can't reproduce on actix-web 4.3.1 (or 4.1.0) and rustc 1.68.2 on NixOS 22.11. Could you try updating rustc (`rustup update`) to check if the problem persists with the current stable?

**Comment by Jaffa-Cakes** [comment]
I am able to reproduce this error with `actix-web` 4.3.1.

**Comment by encephalone** [comment]
+1

**Comment by robjtede** [comment]
Using the reproduction steps in the OP:

```
 › cargo run &
[1] 98952
 ›     Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/Users/rob/.cargo/target-shared/debug/playground`
please run the cmd 'curl http://127.0.0.1:4242' to get the secret

 › xh :4242
==> handler for / has started...
HTTP/1.1 200 OK
Content-Length: 13
Content-Type: text/plain; charset=utf-8
Date: Sun, 27 Aug 2023 22:50:30 GMT

Hello, world!
 › the secret is 42 or 'xyzzy'

[1]  + 98952 done       cargo run
```

If someone posts reproduction steps that doesn't start the server I'll reopen this.

**Comment by encephalone** [comment]
> Using the reproduction steps in the OP:
> 
> ```
>  › cargo run &
> [1] 98952
>  ›     Finished dev [unoptimized + debuginfo] target(s) in 0.07s
>      Running `/Users/rob/.cargo/target-shared/debug/playground`
> please run the cmd 'curl http://127.0.0.1:4242' to get the secret
> 
>  › xh :4242
> ==> handler for / has started...
> HTTP/1.1 200 OK
> Content-Length: 13
> Content-Type: text/plain; charset=utf-8
> Date: Sun, 27 Aug 2023 22:50:30 GMT
> 
> Hello, world!
>  › the secret is 42 or 'xyzzy'
> 
> [1]  + 98952 done       cargo run
> ```
> 
> If someone posts reproduction steps that doesn't start the server I'll reopen this.


I am using your example https://github.com/actix/examples/tree/master/websockets/chat-broker. And everything works well. But when I try to call the following code, I get the error "System is not running":
```
tokio::task::spawn_blocking(move || {
        WsChatServer::from_registry().do_send(WsMessage { message });
});
 ```

I have tried replacing tokio::task with actix_rt::task and also changing dependency versions, but without success.

**Comment by robjtede** [comment]
when using actors you need to use `#[actix_web::main]` instead of `#[tokio::main]` [docs](https://docs.rs/actix-web/latest/actix_web/rt/index.html#running-actix-web-using-tokiomain)

**Comment by encephalone** [comment]
> spawn_blocking

Yes, I already tried. The problem is that the message is not sent to the WsChatServer actor from spawn_blocking. But if I call spawn_local there is no problem.

**Comment by robjtede** [comment]
Ahh of course, you don't have an actor context in any threads not managed by actix.
