### ISSUE TITLE
middleware::logger is private

### ISSUE THREAD

**Issue by rp-** [actix/actix-web#2838]
So in actix-web v3.2.0 I had the following helper function for my tests, to return the same actix service for all tests:

```
#[allow(dead_code)]
pub async fn test_app(
    pool: backend::DbPool,
) -> impl ax_dev::Service<Request = Request, Response = ax_dev::ServiceResponse<impl ax_dev::MessageBody>, Error = AxError>
{
    let refresh_token_map: DashMap<String, backend::v1::auth::Claims> = DashMap::new();
    let refresh_token_data = Arc::new(refresh_token_map);

    test::init_service(
        App::new()
            .data(pool.clone())
            .data(refresh_token_data)
            .wrap(Logger::default())
            .configure(linbit_admin_backend::app_config),
    )
    .await
}
```

Now I tried to migrate to v4.1.0, but I'm not able to get the return type right in the new version:
```
#[allow(dead_code)]
pub async fn test_app(
    pool: backend::DbPool,
) -> impl Service<Request, Response = ServiceResponse<middleware::logger::StreamLog<BoxBody>>, Error = Error>
{
    let refresh_token_map: DashMap<String, backend::v1::auth::Claims> = DashMap::new();
    let refresh_token_data = Arc::new(refresh_token_map);

    test::init_service(
        App::new()
            .app_data(pool.clone())
            .app_data(refresh_token_data)
            .wrap(Logger::default())
            .configure(linbit_admin_backend::app_config),
    )
    .await
}
```

Maybe there is another way for what I wan't, but strictly porting it over seems not to be possible right now.

## Expected Behavior
`StreamLog` should be accessible from outside or reexported

## Current Behavior
```
error[E0603]: module `logger` is private
  --> tests/common.rs:53:67
   |
53 | ) -> impl Service<Request, Response = ServiceResponse<middleware::logger::StreamLog<BoxBody>>, Error = Error>
   |                                                                   ^^^^^^ private module
   |
note: the module `logger` is defined here
  --> /home/rp/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.1.0/src/middleware/mod.rs:7:1
   |
7  | mod logger;
   | ^^^^^^^^^^^
```

## Possible Solution
reexport? or make logger public

## Steps to Reproduce (for bugs)
create a test project, where you want to return a `test::init_service`

## Context
I'm trying to migrate from v3.2.0 to v4.1.0

## Your Environment
- Rust Version (I.e, output of `rustc -V`): `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- Actix Web Version: `v4.1.0`

**Comment by fakeshadow** [comment]
A slight change to your first code would work:
```rust
impl Service<Request, Response = ServiceResponse<impl MessageBody>, Error = Error>
```

In general if you are not (yet) familar with opaque types and trait bounds in generic functions you should consider use `App::configure` to include everything you need to configure for the server rather than return an `AppInitService` instance. You would be get caught in the long run when the underlying trait change which could leave you cluess again.

**Comment by rp-** [comment]
mea culpa

I really have to read more about opaque types :/

**Comment by fakeshadow** [comment]
> mea culpa
> 
> I really have to read more about opaque types :/

np. actix-web's design can expose a lot of generics to you so it does not help on this matter. Using everything with `App::configure` could lead to slightly more code but it would be easier to maintain in the long run. (Unless for some reason actix-web decide to break it which is not likely to happen)
