### ISSUE TITLE
Clarify Scope docs warning/example

### ISSUE THREAD

**Issue by punkeel** [actix/actix-web#2843]
## Current Behavior
<img width="987" alt="image" src="https://user-images.githubusercontent.com/1859135/185500344-9698ec2a-cd89-4d97-b8fd-d01f6fbf2748.png">

From what I understand, the scope URL should NOT end with a `/`,  but in the example it does.
Source: https://actix.rs/actix-web/actix_web/struct.Scope.html

## Possible Solution
Either the warning block is wrong, or the example could be improved (removing the trailing slash). Or I'm just wrong and out of my league :-)

**Comment by robjtede** [comment]
Good spot, thanks 👍🏻
