### ISSUE TITLE
compile error: use of undeclared crate or module `io`

### ISSUE THREAD

**Issue by ilka-schulz** [actix/actix-web#2848]
## Expected Behavior
Comping a project with

```toml
[dependencies]
actix-web = "4.1.0"
```
should compile.

## Current Behavior
`cargo build` fails with the following output:

```text
   Compiling actix-web v4.1.0
error[E0433]: failed to resolve: use of undeclared crate or module `io`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.1.0/src/error/internal.rs:28:5
   |
28 |     io::Error;
   |     ^^ use of undeclared crate or module `io`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `actix-web` due to previous error
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. create an empty project with `cargo init`
2. add `actix-web = "4.1.0"` to the `Cargo.toml`
3. build with `cargo build`

## Context
N/A

## Your Environment
actix-web 4.1.0

with any of the following:

cargo 1.62.1 (a748cf5a3 2022-06-08)
rustc 1.62.1 (e092d0b6b 2022-07-16)

cargo 1.63.0 (fd9c4297c 2022-07-01)
rustc 1.63.0 (4b91a6ea7 2022-08-08)

cargo 1.64.0-nightly (85b500cca 2022-07-24)
rustc 1.64.0-nightly (9067d5277 2022-07-28)

cargo 1.65.0-nightly (9809f8ff3 2022-08-16)
rustc 1.65.0-nightly (015a824f2 2022-08-22)

**Comment by robjtede** [comment]
Does it work on stable?

**Comment by ilka-schulz** [comment]
> Does it work on stable?

Just tested, it does not work on stable either...

**Comment by robjtede** [comment]
Something is amiss with your dependencies. You can verify that the line mentioned in your error doesn't include `io::Error`: https://docs.rs/actix-web/4.1.0/src/actix_web/error/internal.rs.html#28.

I suggest `cargo clean` and try again.

**Comment by ilka-schulz** [comment]
> Something is amiss with your dependencies.

agreed. There were three lines which I think I added many weeks ago to check something quickly and which I accidently saved to the cached source code file. Apparently, the crate has never been recompiled until today when I did a `cargo clean` and the cached source code has never been updated.

Of course, I tried `cargo clean` to solve the issue before but that did not cut it. `rm -r ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.1.0/` solved the issue for me because cargo had to download the clean source again.

You can close the issue, sorry for the inconvenience...
