### ISSUE TITLE
Discrepency between the description of the default number of workers initialized between docs and website.

### ISSUE THREAD

**Issue by solidiquis** [actix/actix-web#2854]
The [website](https://actix.rs/docs/server/) under the "Multi-Threading" section says that it's one worker per logical CPU core:

```
HttpServer automatically starts a number of HTTP workers, by default this number is equal to the number of logical CPUs in the system
```

The [workers](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.workers) method on `HttpServer` however suggests that the number of workers is defaulted to physical CPUs:

```
Set number of workers to start.

By default, the number of available physical CPUs is used as the worker count.
```

Which is it?

**Comment by fakeshadow** [comment]
whoever change it to physical as default have no idea what he is doing.

**Comment by JohnTitor** [comment]
The latter is correct, and the new website has fixed that statement: https://actix-website.netlify.app/docs/server
