### ISSUE TITLE
Suspected memory consumption proportional to the number of cpu

### ISSUE THREAD

**Issue by Giancarlo1974** [actix/actix-web#2855]
## Expected Behavior

I wrote an app similar to "hello world"
I run it via docker on several machines
It requires 5 Mb of memory, but on a machine it requires about 10 Mb
The only difference I've noticed is the cores:
2 cores -> 5 Mb
30 cores -> 10 Mb

How can I solve the problem?

## Your Environment

- Rust Version (I.e, output of `rustc -V`):  FROM rust:1.63 AS builder
- Actix Web Version:   actix-web = "4.1.0"

**Comment by fakeshadow** [comment]
https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.workers

actix-web worker thread take up resources. You can limit your application's thread count.
