### ISSUE TITLE
update `ErrorHandlers` middleware documentation to include examples of changing body type

### ISSUE THREAD

**Issue by 3442853561** [actix/actix-web#2856]
https://github.com/actix/actix-web/pull/2515
I didn't find an example of how to change the body content in the error middleware

**Comment by zacck** [comment]
Isn't this done?

**Comment by zacck** [comment]
If this isn't done, I wonder could I get some direction on how to work on this and examples of what one needs go achieve?

**Comment by yinho999** [comment]
@robjtede Hello there, would you mind assigning this issue to me? I will try my best to finish it. I am new to open-source and rust in general and would like to take this issue as my starting point🙏.

**Comment by yinho999** [comment]
@robjtede Does the body type in this issue title refers to "Content-Type" in the header or the actual body content itself?

**Comment by robjtede** [comment]
Refers to changing actual body content.
