### ISSUE TITLE
abnormally low response times reported by midleware::Logger

### ISSUE THREAD

**Issue by lovasoa** [actix/actix-web#2875]
The logger provided by actix web reports erroneous response times when the endpoint uses body streaming.

In [SQLPage](https://github.com/lovasoa/SQLpage), when a request is received, the response body starts being streamed back to the user almost immediately. The time until the start of the response is not very relevant, but the time until the request has been fully served is.

## Expected Behavior

The response time reported should be the time from the beginning of the reception of the request to the end of the sending of the response.

## Current Behavior

The time reported in the logs seems to be the time  until the **beginning** of the response from the server. 

Here is the same request as seen from the firefox de tools and from actix web's logger.

![image](https://user-images.githubusercontent.com/552629/189998555-d8f810fc-55c3-490d-acf3-5c9b535ffcbb.png)

```
[2022-09-13T19:59:41Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 55089 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" 0.002353
```

**Comment by robjtede** [comment]
You can [see here for yourself](https://docs.rs/actix-web/latest/src/actix_web/middleware/logger.rs.html#351) that the logger does not record the time difference at the beginning of the response body stream. It logs as part of the `Drop` impl on the stream wrapper so this is an accurate reflection of the request's processing time.

**Comment by lovasoa** [comment]
Ok ! Sorry for the annoyance, then.
