### ISSUE TITLE
Cannot compile on Ubuntu due to brotli dependency

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#2882]
## Expected Behavior
I want to compile a simple actix_web and actix_files server but while compiling on ubuntu i get this error

`  Compiling brotli v3.3.4
error: could not compile `brotli`

Caused by:
  process didn't exit successfully: `rustc --crate-name brotli /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-3.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc-stdlib"' --cfg 'feature="default"' --cfg 'feature="ffi-api"' --cfg 'feature="std"' -C metadata=fd455976ca31647c -C extra-filename=-fd455976ca31647c --out-dir /home/hiro/APPS/elaverse-rust-server/target/debug/deps -L dependency=/home/hiro/APPS/elaverse-rust-server/target/debug/deps --extern alloc_no_stdlib=/home/hiro/APPS/elaverse-rust-server/target/debug/deps/liballoc_no_stdlib-fe6f0ebb5b5a4237.rmeta --extern alloc_stdlib=/home/hiro/APPS/elaverse-rust-server/target/debug/deps/liballoc_stdlib-66e5f6e8f3b16e80.rmeta --extern brotli_decompressor=/home/hiro/APPS/elaverse-rust-server/target/debug/deps/libbrotli_decompressor-67f761b1866c655b.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)`

- Rust Version rustc 1.63.0 (4b91a6ea7 2022-08-08):
- actix-web = "4"
- actix-files = "0.6.0"

**Comment by robjtede** [comment]
Since this is about the brotli crate, there's nothing to be done here.

I can only suggest to ask on their issue tracker and disable brotli until you've figured out the problem.

```toml
actix-web = { version = "4", default-features = false, features = ["macros", "cookies", "compress-gzip", "compress-zstd"] }
```
