### ISSUE TITLE
Make Error Send

### ISSUE THREAD

**Issue by rex-remind101** [actix/actix-web#2886]
## Expected Behavior

`actix_web::Error` conforms to `Send` so I may pass it across threads.

`impl Send for actix_web::Error ...`

## Current Behavior

Does not implement send, borrow checker complains when passing the error across threads.

Difference is errors are considered thread safe.

## Steps to Reproduce (for bugs)

1. 
```
let error_string = "Unauthorized";
let error = Err(error::ErrorUnauthorized(error_string));
...pass error across a thread boundary
...borrow checker complains
```
2.
3.
4.

## Context

I'm trying to pass an error across a thread boundary, where it will be recorded for special purposes

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
rustc 1.62.1 (e092d0b6b 2022-07-16)
- Actix Web Version: `actix-web = { version = "4.0.0" }`

**Comment by fakeshadow** [comment]
No it can't be done easily. People depend on `Error` being `!Send` and it's an often used pattern to put non thread safe type inside it for better error handling. For example `Error(HttpRequest)` type for referencing request in `ResponseError` trait impl and `HttpRequest` type is `!Send`.

At the same time you can just use your own typed error in handler function and downcast it to conrete type inside middleware to regain the trait bound of it. See doc for how to downcast error object to type: https://docs.rs/actix-web/latest/actix_web/struct.Error.html#method.as_error

**Comment by rex-remind101** [comment]
To use `as_error` it would appear that I need to know what `T` it should be, how would I know that?

**Comment by rex-remind101** [comment]
Oh, I misread what you meant by "just use your own typed error", I'd downcast to that. That's essentially what I'm already doing but then I have to keep track of transferring important data from `actix_web::Error` to my error, which isn't ideal. This sounds like this requested change goes against actix's design though unfortunately.

**Comment by fakeshadow** [comment]
It's not go against actix's design and more like the language limitation of expression. namely lifetimed future, higher kind trait bound and object safety issue.

For example if `ResponseError` trait can be expressed as below then there is no need to carry any info inside the error. which can not be done in current Rust.
```rust
struct Foo {
    ptr: *const u8
}

trait ResponseError: Send + Sync {
    async fn error_response(&mut self, req: &HttpRequest) -> HttpResponse {
        let non_thread_safe_info = req.extensions.get::<Foo>();
    }
}
```

Or in other word actix-web is waiting for Rust lang to catch up on related features to make the above possible which would naturally solve this problem.

**Comment by rex-remind101** [comment]
Got it, thanks for the thorough response!
