### ISSUE TITLE
Allow custom HTTP methods in route macro

### ISSUE THREAD

**Issue by SeriousBug** [actix/actix-web#2893]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

You should be able to use custom HTTP methods in the `route` macro:

```rs
#[route("/my/path", method = "CREATE")]
async fn create() -> HttpResponse {
  // ...
```

This is already possible with the `web::method` function, like this:

```rs
App::new()
  .route("/", web::method(Method::from_str("CREATE").unwrap()).to(|| async { "Hello CREATE" }))
```

## Current Behavior

The code above results in the error "Unexpected HTTP method: \`CREATE\`."

## Possible Solution

The parser in `actix-web-codegen` should be made more permissive so it will allow custom methods. The parsing code is already in place in `actix-web`, so that could likely be reused.

## Context

Trying to extend my server with additional HTTP methods. Not a dealbreaker and already possible, just a little more verbosely.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.64.0 (a55dd71d5 2022-09-19)
- Actix Web Version: 4.2.1

**Comment by andrewpollack** [comment]
Looking into this now -- is there a way I can assign myself to this issue?

**Comment by andrewpollack** [comment]
My desired code change spot is going to be at the `try_from` logic at line 154 in the `MethodType::try_from` portion https://github.com/actix/actix-web/blob/6f0a6bd1bb7ffdd98fa5ce825b24a73c4d71d9a7/actix-web-codegen/src/route.rs#L153-L157

One hangup I have is that by allowing for essentially arbitrary strings to define a Method, we nearly avoid any logic that defines the `method_type!` enum at https://github.com/actix/actix-web/blob/6f0a6bd1bb7ffdd98fa5ce825b24a73c4d71d9a7/actix-web-codegen/src/route.rs#L44-L54

How should I go about this? Should the `method_type!` logic be re-configured to just deal in arbitrary strings, or should I look to change behavior elsewhere?

**Comment by alexandrebouthinon** [comment]
Hi @andrewpollack, are you still working on it or can I try to add this feature too?

**Comment by andrewpollack** [comment]
I'm not sure I'll get a response on my request for feedback above, so I'm probably not the best owner. 

Happy to pass this to another interested party

**Comment by robjtede** [comment]
> Should the method_type! logic be re-configured to just deal in arbitrary strings, or should I look to change behavior elsewhere?

I'm torn here between accepting the potential DX hit and allowing arbitary uppercase strings (given that the `route` macro is not used as much as the defined method macros) and requiring a new parameter like `custom_method = "FOO"`. Thoughts?

**Comment by SeriousBug** [comment]
I'm in favor of just allowing arbitrary uppercase strings. I just took a look at the HTTP specification out of curiosity, and as far as I can tell all it says is:

> The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names. By convention, standardized methods are defined in all-uppercase US-ASCII letters.
> 
> https://datatracker.ietf.org/doc/html/rfc9110#section-9.1-5

It sounds like there is no real limitations on what the methods can be, even lowercase and non-ascii methods would be valid. HTTP 1.1, 2, and 3 also don't seem to introduce any restrictions. Requiring uppercase ascii does make sense to me as it's a very widespread common practice.

**Comment by robjtede** [comment]
Ok then. Let's allow arbitrary uppercase strings in the method parameter then.

@andrewpollack do you want to make the changes still or shall I unassign you?

**Comment by andrewpollack** [comment]
@robjtede good to unassign me, I'll pick up another issue later!

**Comment by notashes** [comment]
@robjtede Heya, could you please assign me the issue? I'm new to rust and open source in general but I'll try my best to get it done. It will also be a great learning point for me!

**Comment by notashes** [comment]
@robjtede Sorry for the tag. But it would be my first PR. I've made the changes to make it work in my test environment. If you have any comments or feedbacks, it would be extremely helpful! Thanks!
