### ISSUE TITLE
missing middleware

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#29]
actix-web is young but I think it has great potential. One important piece missing when choosing a framework is the management of authentication. I invite you to take inspiration from https://github.com/jaredhanson/passport: it is an indispensable middleware when developing a website quickly with authentication.

With this generic middleware you should capture the majority of developers who want to make a website in rust.

You are also missing a nice web page like https://rocket.rs (maybe your company can help you?)

Bye, Happy New Year

**Comment by fafhrd91** [comment]
regarding passport, it looks interesting, but it is out of scope of actix. I don't have enough time this big project. also it should be implemented as third-party library, maybe even within actix organization but external to actix-web library.

regarding website. i don't think my company will help, I work on actix in my free time. I have domain though, we can use it for guide and api docs at least

**Comment by AlbanMinassian** [comment]
thank
