### ISSUE TITLE
request method does not exist in ServiceRequest

### ISSUE THREAD

**Issue by no-miso** [actix/actix-web#2913]
Hello.

I'm trying to retrieve data from HttpRequest in middleware.

```
use std::{future::{ready, Ready, Future}, rc::Rc};
use actix_web::{
    dev::{Service, ServiceRequest, ServiceResponse, Transform},
    Error, HttpMessage, http::header::{self, HeaderValue}
};
use futures_util::{future::LocalBoxFuture, FutureExt};

fn call(&self, req:  ServiceRequest) -> Self::Future {
        let request = req.request();
// other code
}
```
error
```
no method named `request` found for struct `ServiceRequest` in the current scope
method not found in `ServiceRequest`
```
But "parts_mut()" can use.
My purpose is to take out "COOKIE" and use it, but I thought like this because ServiceRequest can't be cloned.
What am i doing wrong? Or is there another proper way to do it?

**Comment by fakeshadow** [comment]
https://docs.rs/actix-web/latest/actix_web/dev/struct.ServiceRequest.html#method.request

**Comment by robjtede** [comment]
~You're probably using v3 but~ that method was introduced in Actix Web v4.x.

**Comment by fakeshadow** [comment]
Strictly speaking it's 4.2.0 which introduce said method.

**Comment by no-miso** [comment]
I was able to solve it by doing "cargo update".
I was under the impression that VScode was upgrading the crates on its own.
Thank you.
