### ISSUE TITLE
HTTP/2 support in actix_web::client

### ISSUE THREAD

**Issue by parasyte** [actix/actix-web#292]
The client only supports HTTP/1.x (using [httparse](https://crates.io/crates/httparse)). Would love to see an HTTP/2 client (using [h2](https://crates.io/crates/h2)?)

**Comment by fafhrd91** [comment]
this is in my to do for 0.7

**Comment by rofrol** [comment]
Duplicate of #36 ?

**Comment by xtlsheep** [comment]
Does client still not support HTTP/2?

**Comment by sallyyu0** [comment]
> this is in my to do for 0.7
@fafhrd91, do you have a road map on when would this support be available?

**Comment by jkilpatr** [comment]
As far as I can tell http/2 support is either not available or not working properly, I'm having perfectly valid requests fail out to Cloudflare because of http/2 negotiation issues

**Comment by fafhrd91** [comment]
actix-http client provides http/2 support
