### ISSUE TITLE
Implement Responder trait for Option type

### ISSUE THREAD

**Issue by davidMcneil** [actix/actix-web#294]
Would it make sense to implement the Responder trait for Option? Similar to the way Rocket [does](https://rocket.rs/guide/responses/#option). Basically the T in Option<T> must implement Responder. If the Option is Some, it returns its response. Otherwise, if it is None, it returns a status code of Not Found. Maybe something like this would do it:

```rust
impl<T> Responder for Option<T>
where
    T: Responder,
{
    type Item = AsyncResult<HttpResponse>;
    type Error = Error;

    fn respond_to<S: 'static>(
        self, req: &HttpRequest<S>,
    ) -> Result<AsyncResult<HttpResponse>, Error> {
        match self {
            Some(t) => match t.respond_to(req) {
                Ok(val) => Ok(val.into()),
                Err(err) => Err(err.into()),
            },
            None => Ok(req.build_response(StatusCode::NOT_FOUND).finish().into()),
        }
    }
}
```
I would be happy to try and put together a pull request.

**Comment by fafhrd91** [comment]
PR would be great!
