### ISSUE TITLE
Unable to compile on Windows

### ISSUE THREAD

**Issue by drink-stack** [actix/actix-web#295]
Hello, this is my first time using Rust so I'm sorry if there was something that i overlooked but i'm having an issue with compiling this project on Windows.

Enviroment:
```
Windows 10
stable-x86_64-pc-windows-msvc
rustc 1.26.2 (594fb253c 2018-06-01)
```
Tried also with:
`rustc 1.28.0-nightly (8afb89493 2018-06-08)`

Whenever i try to build version `0.6.12` of this package from crates.io i stumble onto this error:
```
error: failed to run custom build command for `ring v0.12.1`
```

I then looked at the crate and noticed that there is an issue with windows compiling and was fixed in newer version so i went ahead, cloned this repo, linked it locally in Cargo.toml and changed the cookie crate to it's latest git version. After that i'm getting this error when compiling:
```
error[E0599]: no variant named `Timeout` found for type `actix_inner::actors::resolver::ResolverError` in the current scope
   --> C:\dev\actix-web\src\client\connector.rs:160:13
    |
160 |             ConnectorError::Timeout => ClientConnectorError::Timeout,
    |             ^^^^^^^^^^^^^^^^^^^^^^^ variant not found in `actix_inner::actors::resolver::ResolverError`
    |
    = note: did you mean `actix_inner::actors::resolver::ResolverError::Timeout`?
```

**Comment by fafhrd91** [comment]
ring requires c compiler, it is used for session, you can disable `session` feature.
https://docs.rs/actix-web/0.6.11/actix_web/#package-feature

master is fixed
