### ISSUE TITLE
Invalid Header provided on POST requests behind nginx

### ISSUE THREAD

**Issue by datapythonista** [actix/actix-web#2976]
## Expected Behavior

When implementing a POST handler with actix-web which returns a simple 200 response, this should work regardless of nginx being used.

## Current Behavior

The service is returning a 400 error instead, and if logging is added, this error is reported in the logs:

```
[2023-02-10T20:00:31Z ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
```

## Possible Solution

Feels like actix-web should support default nginx headers, but not sure if that's really the problem.

## Steps to Reproduce (for bugs)

1. Implement a simple web server with actix-web:

```rust
use actix_web::{post, get, App, HttpResponse, HttpServer, Responder};    
    
#[get("/submit/")]            
async fn test_get() -> impl Responder {    
    HttpResponse::Ok().body("GET")    
}    
    
#[post("/submit/")]            
async fn test_post() -> impl Responder {    
    HttpResponse::Ok().body("POST")    
}    
    
#[actix_web::main]    
async fn main() -> std::io::Result<()> {    
    HttpServer::new(move || {    
        App::new()    
            .service(test_get)    
            .service(test_post)    
    })    
    .bind(("0.0.0.0", 8000))?    
    .run()    
    .await    
} 
```

2. Proxy the traffic to the server:

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        
        location / {
                try_files $uri $uri/ =404;
        }
        location /preview/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://1.1.1.1/;
        }
}
```

3. Make a request to the proxied path in nginx, that will be passed to actix-web:

```
$ curl -X POST http://2.2.2.2/preview/submit/ -v
*   Trying 2.2.2.2:80...
* Connected to 2.2.2.2 (2.2.2.2) port 80 (#0)
> POST /preview/submit/ HTTP/1.1
> Host: 2.2.2.2
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.18.0 (Ubuntu)
< Date: Fri, 10 Feb 2023 21:04:35 GMT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 2.2.2.2 left intact
```

## Context

GET requests seem to always work, and POST requests work fine if nginx is not used. I tried calling the actix-web server manually adding the nginx generated headers, and it works fine:

```
$ curl http://127.0.0.1:8000/submit/ -X POST -H "X-Real-IP: 127.0.0.1" -H "Host: mydomain.com"
POST
```

I also tried deleting those headers in the nginx configuration, but POST requests continue to fail, so it doesn't seem related to them.

I'm not sure what other headers nginx is adding, but seems like actix-web should support whatever nginx is adding by default.

## Your Environment

- Rust Version: rustc 1.66.1 (90743e729 2023-01-10)
- Actix Web Version: 4.3.0

**Comment by datapythonista** [comment]
I managed to get the headers that nginx is adding:

```
Host: 3.3.3.3
X-Real-IP: 3.3.3.3
Connection: close
User-Agent: curl/7.87.0
Accept: */*
```

But I can't seem to reproduce the error by calling the web server directly with those headers. Even if I add arbitrary headers:

```
curl -X POST http://127.0.0.1:8000/submit/ -v -H "Host: 3.3.3.3" -H "X-Real-IP: 3.3.3.3" -H "Connection: close" -H "User-Agent: curl/7.87.0" -H "Accept: */*"
```

So, seems like nginx is modifying the HTTP message in a way that makes actix-web fail, but not necessarily because of the headers.

**Comment by robjtede** [comment]
I'm having a look at this today. @datapythonista 

Is this line in your Nginx config: `proxy_pass http://1.1.1.1/;` supposed to be `proxy_pass http://127.0.0.1:8000/;` ?

**Comment by datapythonista** [comment]
> Is this line in your Nginx config: `proxy_pass http://1.1.1.1/;` supposed to be `proxy_pass http://127.0.0.1:8000/;` ?

I used `1.1.1.1` to not use the real ip. The service is in a different host, but you're correct, `127.0.0.1:8000` would be the right address if the service was in the same machine.

Thanks for the help with this, let me know if I can help with anything.

**Comment by robjtede** [comment]
Adding `proxy_http_version 1.1;` to the `location` blocks makes it work.

This is a weird interaction of nginx using HTTP/1.0 by default, Actix Web not really trying to support 1.0, and empty POST requests not setting a content-length header.

Considering this issue closed but I'll have a look at the decoder logic to see if there is a reasonable fix on our side.

**Comment by datapythonista** [comment]
Yep, that worked, thanks a lot for the help!

**Comment by penso** [comment]
I do have the same issue, same nginx config and I already have `proxy_http_version 1.1;` in the nginx configuration. I use actix_web 4.2.1, shall I upgrade?

**Comment by robjtede** [comment]
@penso upgrading likely won't help, can you get me a minimal example repo that reproduces the issue with `proxy_http_version` set please

**Comment by penso** [comment]
@robjtede sadly it's very hard :( It's a project managing millions of queries per day and it only happened 2 times today so far. I started noticing because I added Sentry. Maybe actix error message could include the invalid header name as a help?

**Comment by robjtede** [comment]
They potentially could, or a trace log emitted. I'd consider a PR for the latter.
