### ISSUE TITLE
User guide for actix_web::client

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#298]

**Comment by ghost** [comment]
I'll do this

**Comment by ghost** [comment]
is [this](https://github.com/eddomuke/actix-website/blob/master/content/docs/client.md) good?

**Comment by DoumanAsh** [comment]
@eddomuke It is good as getting started, but I believe guide should cover various topics of client module functionality

**Comment by ZhangHanDong** [comment]
Is there more guide or demo?

**Comment by robjtede** [comment]
`awc` root docs were given a significant makeover recently
