### ISSUE TITLE
Compress middleware should not compress `image/*` content types

### ISSUE THREAD

**Issue by nyurik** [actix/actix-web#2981]
## Expected Behavior
Most `image/*` mime types such as png and jpeg are already pre-compressed, so when using `.wrap(middleware::Compress::default())`, the expectation is that the well known images would not be compressed.

## Current Behavior
Currently the compression middleware only looks at the  `content-encoding` of the response (which should not be set for images), and thus compresses images again.

## Possible Solution
* Check against a list of well known image types
* Offer a way to set a callback so that the user can check themselves
* all of the above?

## Your Environment

- Rust Version: 1.67.1
- Actix Web Version: 4.3.0

**Comment by robjtede** [comment]
I am surprised that browsers send Accept-Encoding headers for image assets so this appears to be a legitimate issue.

**Comment by cptrodolfox** [comment]
Hey @robjtede , I am interested in working on this issue. I will start working on a solution. I might have some questions though.
