### ISSUE TITLE
When cross compile to Linux : thread 'main' panicked at 'OpenSSL include directory does not exist: /usr/lib64/openssl/include'

### ISSUE THREAD

**Issue by chenyangguang** [actix/actix-web#2986]
Your issue may already be reported! Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

crago build --release 

## Current Behavior

error: failed to run custom build command for `openssl-sys v0.9.80`

Caused by:
  process didn't exit successfully: `/data/chatgpt/target/release/build/openssl-sys-37d3f491db751b54/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /usr/lib64/openssl

  --- stderr
  thread 'main' panicked at 'OpenSSL include directory does not exist: /usr/lib64/openssl/include', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/main.rs:86:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

## Possible Solution

I had add two line dependancies to Cargo.toml file: 

openssl-sys = "0.9.80"
openssl = "*"

but it steay does work.

And  ```cargo  build --target=x86_64-unknown-linux-gnu --release``` on mac to compile , it appreared an error with : 

 --- stderr
  error occurred: Failed to find tool. Is `x86_64-linux-gnu-gcc` installed?

## Your Environment

Mac 15.3 

- Rust Version (I.e, output of `rustc -V`): 1.66
- Actix Web Version: ^4.0

**Comment by robjtede** [comment]
OpenSSL requires system libraries to be installed. Using homebrew: `brew install openssl@1.1`

**Comment by chenyangguang** [comment]
> OpenSSL requires system libraries to be installed. Using homebrew: `brew install openssl@1.1`

I did it . But it did not work. So I had to choose docker instead.
