### ISSUE TITLE
Build issues due to minimium version of hyperium/http

### ISSUE THREAD

**Issue by jesterpm** [actix/actix-web#2987]
## Current Behavior

After adding a new dependency (on awc) and rebuilding my project, actix-http failed to compile with the following error:

```
error[E0015]: cannot call non-const fn `http::header::HeaderName::from_static` in constants
  --> /home/jesterpm/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.3.0/src/header/common.rs:51:43
   |
51 | pub const X_FORWARDED_PROTO: HeaderName = HeaderName::from_static("x-forwarded-proto");
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: calls in constants are limited to constant functions, tuple structs and tuple variants
```

## Possible Solution

It looks like HeaderName::from_static was made a const fn in [version 0.2.7](https://github.com/hyperium/http/releases/tag/v0.2.7). `cargo tree` indicated that an older version of http was being pulled in. Adding an explicit dependency on http 0.2.9 mitigated the error. actix-http currently depends on http 0.2.5 in the config, but depends on functionality only present in >= 0.2.7. Perhaps the minimum version needs to be increased?

## Steps to Reproduce (for bugs)

I'm honestly not sure what changed to caused cargo to start pulling in an older http (or a newer actix-http)...

## Your Environment

- Rust Version (I.e, output of `rustc -V`): 1.67.0
- Actix Web Version: 4

**Comment by robjtede** [comment]
fixed in 20c7c07dc00236b2d74aaed8c79a805aec54f89e
i'll get it released today
