### ISSUE TITLE
Actix and Actix Web always recompile on cargo build

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#3]
When using Actix and Actix Web as dependencies in a project, running `cargo build` triggers them to recompile every time.

I.e, running `cargo new --bin actix_test` with the following Cargo.toml :

```
[package]
name = "actix_test"
version = "0.1.0"

[dependencies]
actix = "*"
actix-web = "*"
```

Running `cargo build` will always trigger a rebuild:

```
$ cargo build
   Compiling actix v0.3.0
   Compiling actix-web v0.1.0
   Compiling actix_test v0.1.0 (file:///<path_to_dir>/actix_test)
    Finished dev [unoptimized + debuginfo] target(s) in 4.89 secs
```

**Comment by fafhrd91** [comment]
yes, that is problem with skeptic. this problem is fixed in master, I will release new versions soon.

btw I'd suggest to use git repo instead of cargo releases, I fixed a lot of inconveniences in actix-web.
