### ISSUE TITLE
Provide Documentation For Implementing Middleware in Rustdoc

### ISSUE THREAD

**Issue by Nerixyz** [actix/actix-web#3026]
## Expected Behavior

I'd like to be able to see examples and explanation on how middleware works and how to develop it on docs.rs.

## Current Behavior

Currently, most of the "entry" documentation around writing middleware is provided on https://actix.rs/docs/middleware, while the traits (e.g. `Transform` or `ServiceRequest`) are documented on docs.rs.

## Possible Solution

The documentation found on https://actix.rs/docs/middleware could be provided in the [`middleware` module's documentation](https://docs.rs/actix-web/latest/actix_web/middleware/index.html). Even though the types for implementing middleware aren't found inside this module, this seems to be the best place from a user-perspective compared to e.g. `dev` - "Where would I find documentation for middleware?".

I really like the documentation for middleware that [axum has](https://docs.rs/axum/latest/axum/middleware/index.html). Including e.g. the order in which middleware is running provides some great background.

## Context

This issue is about making the documentation more accessible (esp. for new/intermediate users).

When developing _stuff_, I usually have the documentation open. For Rust, this is (almost) exclusively docs.rs. I'm not writing middleware every day or week, so when I do write some, my knowledge will be lacking at some point. For me personally, that's mostly where to start - "Was it `Service` or `Transform` again?". I'd like to open docs.rs as I do for most other libraries I'm using, and get my answer.

**Comment by nhnansari** [comment]
I am also struggling for finding 1 working example of middleware for actix 4. Without any success.
