### ISSUE TITLE
ws client quits on large read

### ISSUE THREAD

**Issue by kazcw** [actix/actix-web#303]
I have a program that is essentially the ws client example (https://github.com/actix/examples/blob/master/websocket/src/client.rs), modified to connect to a particular wss endpoint. I can send messages and receive replies, but if I send a message that triggers a large reply then StreamHandler.finished() runs and the client exits. I can prevent this from happening by setting max_frame_size to a higher value.

Aborting if a hard coded message size is exceeded seems problematic. If it is necessary for that to happen, I would expect to get some type of error rather than looking the same if the server disconnected. Is there something I should be doing differently from the example to avoid this type of problem, or should I just set a large max_frame_size and hope it's big enough?

**Comment by ghost** [comment]
what should I do to fix this?

**Comment by fafhrd91** [comment]
@eddomuke actually, let me handle this

**Comment by fafhrd91** [comment]
seems everything work as expected. you can implement [StreamHandler::error()](https://docs.rs/actix/0.7.0/actix/trait.StreamHandler.html#method.error) and handle error gracefully.
