### ISSUE TITLE
Expose AppEntry for more friendly ergonomics/further impl capabilities

### ISSUE THREAD

**Issue by Wolftousen** [actix/actix-web#3033]
Your issue may already be reported! Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

AppEntry is publicly exposed so that App<AppEntry> can be further implemented.

## Current Behavior

Currently, AppEntry is not exposed publicly and makes the following impossible:

```
//several routes defined above

pub trait LibARouter {
    fn register_liba_routes(self) -> Self;
}

impl LibARouter for App<AppEntry> {
    fn register_liba_routes(self) -> Self {
        self.service(route_a)
            .service(route_b)
            .service(route_c)
    }
}
```

## Context

I'm currently working on a project to build a rather robust REST API and I'm splitting my route handler functions out into several files.  We'll be expanding out to more routes in the future and we want to have minimal changes to the  App::new() code.  So we thought about doing the code snippet above in each route file to accomplish that.  It would also help with ergonomics in general.

This is sort of the like the `plugin` functionality that bevy uses in it's builder. 

## Your Environment

- Rust Version (I.e, output of `rustc -V`): 1.69.0
- Actix Web Version: 4.3.1

**Comment by robjtede** [comment]
Duplicate or related to: #780 #1005 #1156 #2039 #2073 #2082 #2301

**Comment by robjtede** [comment]
Here's how to return App from a fn with v4.x:
https://github.com/actix/actix-web/blob/b1c85ba85be91b5ea34f31264853b411fadce1ef/actix-web/src/app.rs#L698
