### ISSUE TITLE
NormalizePath doesn't cover the situation of /./?

### ISSUE THREAD

**Issue by kvzn** [actix/actix-web#3035]
It looks like only the `end-slash` and `double-shash` are being handled by `NormalizePath`, could it also process the `/./` situation?

**Comment by robjtede** [comment]
I'd argue that `/./` is a legitimate and even safe path segment when not used in the context of filesystem traversal.

Consider a route `/resource/{name}/action` where `.` is allowed as a "name" for whatever reason. It'd be wrong for the built-in normalize middleware to strip out the `/./` and forward a call to `/resource/action`, which would result in a 404.

If you want to do this find-replace yourself, a simple [`from_fn` middleware](https://docs.rs/actix-web-lab/latest/actix_web_lab/middleware/fn.from_fn.html) should suffice:

(untested code)

```rust
async fn filter_path<B>(
    mut req: ServiceRequest,
    next: Next<B>,
) -> actix_web::Result<ServiceResponse<B>> {
    let uri = mem::take(&mut req.head_mut().uri);
    let mut parts = uri.into_parts();
    let path = parts.path_and_query.unwrap();

    let new_path = path.path().replace("/./", "/");

    let new_path_and_query = match path.query() {
        Some(query) => format!("{new_path}?{query}"),
        None => new_path,
    }
    .parse()
    .unwrap();

    parts.path_and_query = Some(new_path_and_query);
    req.head_mut().uri = Uri::from_parts(parts).unwrap();

    next.call(req).await
}
```

**Comment by kvzn** [comment]
> 

Great answer, thank you very much!
