### ISSUE TITLE
rustls v0.21 upgrade

### ISSUE THREAD

**Issue by D0bhareach** [actix/actix-web#3053]
## Steps to Reproduce (for bugs)

When  version of rustls upgraded from 0.20.8 to 0.21.2:
```
= note: `ServerConfig` and `ServerConfig` have similar names, but are actually distinct types
note: `ServerConfig` is defined in crate `rustls`
   --> /home/ferrislav/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.21.2/src/server/server_conn.rs:199:1
    |
199 | pub struct ServerConfig {
    | ^^^^^^^^^^^^^^^^^^^^^^^
note: `ServerConfig` is defined in crate `rustls`
   --> /home/ferrislav/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.20.8/src/server/server_conn.rs:201:1
    |
201 | pub struct ServerConfig {
    | ^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `rustls` are being used?
note: method defined here
   --> /home/s/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-web-4.3.1/src/server.rs:386:12
    |
386 |     pub fn bind_rustls<A: net::ToSocketAddrs>(
    |            ^^^^^^^^^^^
```

- Rust Version (I.e, output of `rustc -V`): 1.7.0
- Actix Web Version: 4

**Comment by f2calv** [comment]
Yep I've come across this also;

![image](https://github.com/actix/actix-web/assets/16097639/506da4e3-cb12-4a09-8bb2-2af1dd17cea3)

https://github.com/actix/actix-web/blob/0e8ed50e3a7ac93d94e6c1c6603d0048e1f33fb8/actix-web/src/server.rs#L19

Temporary workaround is to downgrade rustls to 0.20.8

...I don't have the Rust skillz to create a PR yet :)

**Comment by robjtede** [comment]
Some kind of non-breaking rustls v0.21 is in the works. For now, just use rustls v0.20. You shouldn't see anything missing really.

**Comment by eopb** [comment]
@robjtede Is there any way I could help make this update happen?

`rustls` `v0.20` depends on https://github.com/briansmith/webpki which is not regularly maintained and has [a vulnerability](https://rustsec.org/advisories/RUSTSEC-2023-0052.html)

**Comment by davids-work** [comment]
Another issue with using rustls v0.20 is that it does not have support for IP addresses in SANs and thus it's not possible to connect to peers named with IP addresses

**Comment by robjtede** [comment]
Minimum viable feature support is being prioritized given the recent RUSTSEC report. Changes made will be strictly backwards-compatible so will require users to enable new features and change methods called.
