### ISSUE TITLE
Input is not enough for unique date and time error

### ISSUE THREAD

**Issue by dadepo** [actix/actix-web#3056]
## Expected Behavior

`test::read_body_json` should be able to deserialise payload with `DateTime<Utc>`

## Current Behavior

This

`let result: Vec<Person> = test::read_body_json(resp).await;`

Fails with 

```
could not deserialize body into a alloc::vec::Vec<database::models::Person>
err: input is not enough for unique date and time at line 1 column 389
```

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.72.0-nightly (8c74a5d27 2023-06-14)
- Actix Web Version: 4

**Comment by robjtede** [comment]
can you provide a minimal reproducable example please

**Comment by robjtede** [comment]
This isn't an actix-web problem. You should be able to reproduce this using `serde-json` directly and figure out what is wrong in your code.
