### ISSUE TITLE
No body response has end-of-frame set to 0

### ISSUE THREAD

**Issue by sallyyu0** [actix/actix-web#307]
Hello,

When I send response with no body, curl client got stuck. I noticed that the HTTP/2 response packet has "End Frame" bit set to 0.  
 
pub fn my_handler(req: HttpRequest) -> Box<Future<Item=HttpResponse, Error=Error>> {
.....    
    result(Ok(HttpResponse::Ok()        
        .body("")))
    .responder()   
}

~$ curl --http2-prior-knowledge  --verbose -X DELETE http://172.17.0.3:8080/myTest
*   Trying 172.17.0.3...
* TCP_NODELAY set
* Connected to 172.17.0.3 (172.17.0.3) port 8080 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1070fb0)
> DELETE /myTest HTTP/2
> Host: 172.17.0.3:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 12 Jun 2018 20:21:15 GMT
< content-length: 0
<

**Comment by fafhrd91** [comment]
fixed in master and 0.6
i will make new release later today or tomorrow
