### ISSUE TITLE
Incorrect sentence in example documentation

### ISSUE THREAD

**Issue by HJX-001** [actix/actix-web#3085]
The line no 32 of `"actix_web::guard::mod.rs"` is as below:
called if the request method is `POST` and there is a request header with name and value equal

## Expected Behavior
The line should be:
called if the request method is **`GET` or** `POST` and there is a request header with name and value equal

## Possible Solution
Change line no 32 to:
called if the request method is `GET` or `POST` and there is a request header with name and value equal

- Actix Web Version: 4.3.1

**Comment by robjtede** [comment]
this was fixed in 8b2b755cdecdd21277ebcf8611f8bf028b05cbb1; release scheduled soon
