### ISSUE TITLE
implement FromResidual for Either

### ISSUE THREAD

**Issue by Tenshock** [actix/actix-web#3091]
## Expected Behavior

When I use a handler using `Either` enum (https://actix.rs/docs/handlers/#different-return-types-either) I would be able to use the `?` operator to automatically return a `Either::Left` variant

## Current Behavior

Currently, with following code does not work as intended:

```rust
use actix_web::{Either, Error, HttpResponse};

type RegisterResult = Either<HttpResponse, Result<&'static str, Error>>;

async fn index() -> RegisterResult {
    let value = get_a_value()?;
    Either::Right(Ok(value))
    }
}

fn get_a_value() -> Result<&'static str, HttpResponse> {
    Ok("Hello!")
}
```

## Possible Solution

Implement the [FromResidual](https://doc.rust-lang.org/std/ops/trait.FromResidual.html) trait for Either enum

## Context

In order to reduce boilerplate, handling special cases and so, we encapsulate logic into multiple Result enums. This functionality will reduce again the boilerplate needed to express logic in controllers.

**Comment by robjtede** [comment]
The `FromResidual` trait is unstable and only used inside the standard library for now.

**Comment by Tenshock** [comment]
Oh, I was unaware of that, thanks for the quick answer!
