### ISSUE TITLE
gracefull shutdown

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#31]
- Given browser try to load a content 
- And keep open connexion to application (because content-length is not exact by example)
- When i shutdown actix-web application 
- Then application stop
- But thread actor keep alive (because open by browser)
- And browser continue to wait 
- And i have "Adress is already use" when i restart application

examples/basic : https://github.com/actix/actix-web/pull/30

With firefox or chrome:  html not finish to load (because content-length seem not exact).

**Comment by fafhrd91** [comment]
yes, I know about this. I need time to think how to fix this efficiently

**Comment by fafhrd91** [comment]
should be fixed now

**Comment by AlbanMinassian** [comment]
Thank
