### ISSUE TITLE
Compile errors after actix-web-codegen v4.2.0 -> v4.2.1

### ISSUE THREAD

**Issue by nyurik** [actix/actix-web#3118]
After running `cargo update`, with the ONLY update being `actix-web-codegen v4.2.0 -> v4.2.1` (I updated all other ones one-by-one using `cargo update -p <...>`), i gets compilation errors of the [martin](https://github.com/maplibre/martin) project:

```
error: unexpected token
  --> martin/src/srv/server.rs:95:12
   |
95 |     wrap = "middleware::Compress::default()"
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/maplibre/martin.git`
2. `cd martin`
3. `git reset --hard b5902aa`
4. `cargo build`  <-- this should pass
5. `cargo update -p actix-web-codegen` <-- this will show updating `v4.2.0 -> v4.2.1`
6. `cargo build`  <-- this will now fail with lots of errors

## Your Environment

- Linux Mint
- Rust Version (I.e, output of `rustc -V`): `rustc 1.72.0 (5680fa18f 2023-08-23)`
- Actix Web Version: `4.4.0`

**Comment by robjtede** [comment]
Thanks for posting this regression. I've yanked v4.2.1 for now.

**Comment by robjtede** [comment]
Fix published in v4.2.2.

**Comment by robjtede** [comment]
```
 › cargo update -p actix-web-codegen
    Updating crates.io index
    Updating actix-web-codegen v4.2.1 -> v4.2.2
 › cargo check
  Downloaded actix-web-codegen v4.2.2
  Downloaded 1 crate (17.2 KB) in 1.62s
   Compiling actix-web-codegen v4.2.2
    Checking actix-web v4.4.0
    Checking actix-cors v0.6.4
    Checking martin v0.8.7 (/Users/rob/tmp/martin/martin)
    Finished dev [unoptimized + debuginfo] target(s) in 4.86s
 ›
```

**Comment by nyurik** [comment]
@robjtede thanks for such awesomely quick turnaround!
