### ISSUE TITLE
How it may be possible to return HTTP 500 on panic without catch_unwind

### ISSUE THREAD

**Issue by sjmiller609** [actix/actix-web#3126]
Your issue may already be reported! Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

- A panic seems like it should return 500 instead of a TCP disconnect

## Current Behavior

- If a route panics for some reason, the server sends a TCP disconnect instead of HTTP 500

## Possible Solution

- In a [previous issue](https://github.com/actix/actix-web/issues/1501) there is discussion around catch_unwind, however a maintainer mentioned that after a panic, it's not safe to continue. I agree with this reasoning.
- Since it's possible to put a proxy like Nginx in front and just return 500 if the server does a TCP disconnect, why not take a multi-process approach like that inside Actix? I'm wondering about a possibility of Actix having a proxy process that handles returning 500 if there is a TCP disconnect. I'm not sure if that is the best design, however I think that is an example that it's possible to return 500 without catch_unwind?

## Steps to Reproduce (for bugs)

just add `panic!('...')` in any route and do a GET request to that route

## Context

When deploying services with Actix, typically we can find 502 returned by a load balancer instead of 500, which is the normal behavior of other types of frameworks. Just being different than normal is a reason why it could be worth it to try something like this, but I'm sure maintainers have the best opinions here.

## Your Environment

502 returned by AWS ALB when Actix process returns TCP disconnect.

**Comment by robjtede** [comment]
this issue is the definitive source of info for this topic: https://github.com/actix/actix-web/issues/1501

there's not really anything else to add
