### ISSUE TITLE
Chrono change to v0.4.30 breaks the build of actix-http-1.0.1

### ISSUE THREAD

**Issue by bryan-roberts** [actix/actix-web#3135]
This is described by Chrono as a "SemVer-breaking change, we expect the risk of downstream users experiencing actual incompatibility to be exceedingly limited"
https://github.com/chronotope/chrono/issues/1268

cookie.set_expires(time::now() - Duration::days(365));
    |                                            ^ no implementation for `Tm - chrono::Duration`
    |
    = help: the trait `Sub<chrono::Duration>` is not implemented for `Tm`
    = help: the following other types implement trait `Sub<Rhs>`:
              <Tm as Sub<time::Duration>>
              <Tm as Sub>

https://github.com/actix/actix-web/blob/7880d5e2bf10d872ba340eb2230151479eaea4f4/actix-http/src/cookie/jar.rs#L226C25-L226C25

**Comment by robjtede** [comment]
Sorry to inform you that the Actix Web v3.x is not being maintained and will not receive a fix for this issue.

I can only offer to help you update to Actix Web v4.

As a temporary solution you can pin `chrono` to v0.4.29 in your manifest file.

**Comment by bryan-roberts** [comment]
For reference this is what I had to do to specify the exact version before the breaking changes.

chrono = { version = "= 0.4.29" }
