### ISSUE TITLE
API documentation's link is broken

### ISSUE THREAD

**Issue by bedax** [actix/actix-web#317]
If you go to https://docs.rs/actix-web it redirects to https://docs.rs/actix-web/0.6.13/actix_web/ which says "The requested resource does not exist".

Thank you for actix-web though, really excellent work

**Comment by fafhrd91** [comment]
docs.rs build process failed https://docs.rs/crate/actix-web/0.6.13/builds/105314
failure is in different crate 

https://github.com/onur/docs.rs/issues/23#issuecomment-388968757

i am not sure what we can do. maybe we should start publishing stable docs outside of docs.rs?

**Comment by fafhrd91** [comment]
onur/docs.rs/issues/23

**Comment by bedax** [comment]
That seems like a good temporary solution. Though it seems like a bug with docs.rs that someone else can break your documentation. It seems that it should have an option for skipping the documentation of external crates that it can't build, so perhaps an issue should be raised with docs.rs?

**Comment by fafhrd91** [comment]
0.6.14 and 0.6.15 are failed to build on docs.rs

**Comment by fafhrd91** [comment]
release docs are here https://actix.rs/api/actix-web/stable/actix_web/

**Comment by fafhrd91** [comment]
https://actix.rs/api/actix-web/0.7.0/actix_web/
