### ISSUE TITLE
`.negotiate()` prefers `gzip` over `brotli`

### ISSUE THREAD

**Issue by amitu** [actix/actix-web#3187]
If I enable `actix_web::middleware::Compress` middleware, it's serving `gzip`, even though `brotli` feature is on.

 
## Expected Behavior

I am expecting it to pick the best compression method supported by Browser, and between brotli and gzip, brotli is better (my site compresses to ~196KB with brotli and ~250kb with gzip). 

## Current Behavior

In the 4.4 release and on main, if you look at the test cases, `gzip` is given higher priority over `brotli`.

 https://github.com/actix/actix-web/blob/e50bceb91493087d4059e605d94c13a11b09e747/actix-web/src/http/header/accept_encoding.rs#L378-L385

## Possible Solution

Based on https://news.ycombinator.com/item?id=19678985 I recommend `brotli` > `zstd` > `gzip` as the priority in which one should pick the compression Algo to use if browser supports all three.

Since every browser that supports `brotli` or `zstd` also supports `gzip`, with current implementation of giving `gzip` priority over the two means we are compiling support for `brotli` and `zstd` for no real benefit.

Happy to send a PR if my proposal is accepted. 

## Steps to Reproduce (for bugs)

The test linked above demonstrates the problem. 

## Context

I am trying to optimise a [`fastn`](https://github.com/fastn-stack/fastn/) powered website: [`fastn.com`](https://fastn.com). Currently it is implemented as SSG, deployed on Vercel, and Vercel uses brotli and about 190KB is downloaded for a test page, and when I power it by running `fastn serve` on a Heroku instance, and enable compression middleware, it serves gzipped content, and browser downloads ~250KB of content. 

## Your Environment

- Rust Version (I.e, output of `rustc -V`): 1.73.0
- Actix Web Version: 4.4

Site is deployed on Heroku. [Code in question](https://github.com/fastn-stack/fastn/blob/85f972eb49818423cab055e43dafe71c5af9cc05/fastn-core/src/commands/serve.rs#L737).

**Comment by robjtede** [comment]
Since equally weighted q-values are not discriminated according to order (it's left up to the origin), I do think we should preference brotli if it is enabled 👍🏻
