### ISSUE TITLE
Can't reference HttpServer instances

### ISSUE THREAD

**Issue by bedax** [actix/actix-web#319]
I'm creating a newtype wrapper around HttpServer instances, like this:

``` rust
struct State(u8);
struct Server(
   actix_web::server::HttpServer<actix_web::application::HttpApplication<State>>
);

impl Server {
   fn index(_request: actix_web::HttpRequest<State>) -> &'static str {
      "hello world"
   }

   fn new() -> Self {
      let server = server::new(|| {
         actix_web::App::with_state(State{ 0: 1 })
            .default_resource(|r| r.f(Self::index))
      });

      Self {
         0: server.bind("127.0.0.1:8088").unwrap()
      }
   }
}
```

Which fails with:

```
error[E0603]: module `application` is private
```

While this isn't major, I can refactor the application, it would be convenient to be able to reference the type of created HttpServer instances.

**Comment by DoumanAsh** [comment]
I'm not sure what would be use case for such wrapper?

**Comment by bedax** [comment]
Well in my case I'm not running the server straight after binding it. First I want to set-up the server instance, bind it, and see if that all went well. If it failed the application errors and exits, if it worked, I set-up the other parts of the application. Once all set-up has been done, I then send the server off to another thread and run it. So essentially I need to set-up the server and store it somewhere until I need it.

It seems likely that I'll refactor now and move the web server set-up to the end, so this may as well be closed if it doesn't seem relevant to you. Though it does seem like users of the crate should be able to reference the types given to them.

**Comment by fafhrd91** [comment]
you can use `Box<HttpHandler>` and https://actix.rs/actix-web/actix_web/struct.App.html#method.boxed

**Comment by bedax** [comment]
brilliant yeah that works, thanks @fafhrd91
