### ISSUE TITLE
web site draft

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#32]
http://tmpxqsddkjqlkdjlqkjdlqkdjqlkjd.surge.sh/

I know the http://ejs.co/ site which is based on a free template proposed by https://themes.3rdwavemedia.com/. I quickly adapted this template (draft) for actix-web: see the real demo http://tmpxqsddkjqlkdjlqkjdlqkdjqlkjd.surge.sh/

I will remove the demo site within a week and if you are interested then copy the content to the temporary repository https://github.com/ami44/actix-web-ami44-site

Thank you for your help this week, my vacation is over and I will be less present. 
good continuation

**Comment by fafhrd91** [comment]
thanks! I'll take a look.

btw you should write blog post about your learnings and web dev in rust
