### ISSUE TITLE
Duplicate headers in ClientRequest

### ISSUE THREAD

**Issue by jesskfullwood** [actix/actix-web#320]
I'm using actix-web as a simple proxy,  using `ClientRequestBuilder::from(request)` like so:

```rust
pub fn proxy(
    (req, path): (HttpRequest, Path<String>),
) -> impl Future<Item = HttpResponse, Error = Error> {
    Url::parse(&*path)
        .map_err(Error::from)
        .and_then(|url| {
            client::ClientRequestBuilder::from(&req)
                .uri(url)
                .streaming(req)
        })
        .into_future()
        .map_err(Error::from)
        .and_then(|req| {
            println!("Headers: {:?}", req.headers());
            req.send().map_err(Error::from)
        })
        .map(|clientresp| {
            let mut resp = HttpResponseBuilder::from(&clientresp);
            resp.streaming(clientresp)
        })
        .map_err(Error::from)
}

let proxy_app = App::new()
    .prefix("/proxy")
    .resource("/{url:.*}", |r| r.route().with_async(proxy::proxy));
```
However, testing it with `httpie`, like so:
```
http :8000/proxy/http://example.org
```
I get the following printout:
```
 INFO 2018-06-16T09:31:53Z: proxy: Proxying: http://www.example.org/
Headers: {"host": "www.example.org", "user-agent": "HTTPie/0.9.9", "accept-encoding": "gzip, deflate", "accept-encoding": "gzip, deflate", "accept": "*/*", "connection": "keep-alive"}
```
Note that `accept-encoding` has been duplicated. This results in the server returning `400 Bad Request`.

What I think is happening is that `httpie` sends header `Accept-Encoding: gzip, deflate` (note title-case) and this is not recognized by actix when inserted into `HeaderMap`. Then actix adds it's own similar header in lowercase. I don't really understand how `HeaderMap` handles deduplication but something must have gone wrong.

**Comment by DoumanAsh** [comment]
`HeaderMap` is basically coming from [http](https://docs.rs/http/0.1.6/http/struct.HeaderMap.html) crate and currently `actix-web` rely on it.
There afaik all headers constants are lower case.

I guess one solution would be to normalize headers

**Comment by ousado** [comment]
actix adds `accept-encoding` unless `no_default_headers` is called on the builder - shouldn't it just check for an existing `accept-encoding` and skip it in that case? It [does the same](https://github.com/actix/actix-web/blob/8b0fbb85d135435c62325408f7e00a1d80b6f63a/src/client/request.rs#L616) for `user-agent` already.
