### ISSUE TITLE
Unable to Perform JSON Decoding Using Browser sendBeacon APIs

### ISSUE THREAD

**Issue by sstelfox** [actix/actix-web#321]
This is a tricky one and I'm not sure I should report it as a bug, but it is a limitation of the framework. I've worked around the issue by overriding the Content-Type header for the effected path using Nginx.

The problem is that the [sendBeacon][1] API, which was designed to send low priority data requests to servers, only sends the POST requests with a content type of `text/plain`. This can *technically* be overridden [to send a correct content type][2] but initially [Chrome][3] and then later [Firefox][4] "hardened" the implementation to require CORS preflights for none-text type requests, but won't send the preflight. Which will immediately cause the request to fail without ever attempting it.

This is ultimately an issue with the clients, and how they're choosing to implement the spec, but unfortunately that has impacts on the requirements of servers. The [explicit content type][5] is great behavior when clients also have great behavior, but causes issues when dealing with these kind of broken specs.

I don't have a good recommendation for how to solve this kind of issue as ultimately the bug isn't here, and ultimately I'd prefer if the implementation stayed the same. If others have any recommendations for dealing with this better I'd appreciate the input, but I kind of expect this issue to get closed.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
[2]: https://stackoverflow.com/questions/40523469/navigator-sendbeacon-to-pass-header-information
[3]: https://bugs.chromium.org/p/chromium/issues/detail?id=466038
[4]: https://bugzilla.mozilla.org/show_bug.cgi?id=1289387
[5]: https://github.com/actix/actix-web/blob/70244c29e0398a38d934a35d39f3a52eee91e350/src/json.rs#L290

**Comment by fafhrd91** [comment]
You can use `HttpMessage::body()` and then manually deserialize json

**Comment by sstelfox** [comment]
Wow. Before going with my route I searched for a very long time for pulling out the posted body easily and couldn't find anything. Thanks for putting me on to that.
