### ISSUE TITLE
Is there a reason the docs for `query` method for HttpRequest are hidden?

### ISSUE THREAD

**Issue by fristonio** [actix/actix-web#322]
https://docs.rs/actix-web/0.6.11/src/actix_web/httprequest.rs.html#375

**Comment by fafhrd91** [comment]
at some point i wanted to deprecate it. i'll unhide it.
but it is better to use `Query` extractor.

**Comment by fristonio** [comment]
Sorry, I don't follow `Query` extractor?
The only two methods I can see to extract query params are `query_string` and `query`, there is a Query struct [here](https://github.com/actix/actix-web/blob/master/src/httprequest.rs#L51) but I don't see it being used anywhere. Is there something I am missing here?

**Comment by fafhrd91** [comment]
here it is https://actix.rs/actix-web/actix_web/struct.Query.html
https://actix.rs/docs/extractors/

**Comment by fristonio** [comment]
Ah, This makes much more sense now. Thanks for your help.
Also, there is no example in the docs to use this Query extractor I had to look into https://github.com/actix/actix-web/blob/master/src/extractor.rs#L159 for using it, if you think it should be in the docs I can add it. :)

Closing this.
