### ISSUE TITLE
actix-http 3.5 "Prevent compression of zero-sized response bodies" causes delays to close connection

### ISSUE THREAD

**Issue by mrsarm** [actix/actix-web#3229]
I was working in some changes in my Actix project with latest dependencies installed, so as soon as I see the new minor versions released Today I wanted to give it a try, and everything continue to working with Actix 4.4.1, but now the endpoints that return no body take considerable time to finish the connection.

I see that the release of actix-http 3.5.0 has this in it's release note: "Prevent compression of zero-sized response bodies", so I changed the dependencies configuration and only updated this dependency (and it's dependencies) and not the rest of the Actix libs, and the problem persist, so looks highly probable that it's the reason why the delay happens. I also tried different clients and browsers: curl, httpie, Firefox and Chrome.

## Expected Behavior

In my service, when a HTTP 404 response is given with no body, the speed at what the response is delivered is as fast or even higher than HTTP responses with body.

## Current Behavior

It's really slow, here is a recording, first I make 2 HTTP calls to an endpoint that return JSON responses when the record is found, and the third call is made to the same endpoint with an id of a record that doesn't exist, in which case the endpoint respond back with HTTP 404 and no body. The first 2 calls are very fast while the third it's very slow to finish the connection:

![Actix HTTP Delay Error](https://github.com/actix/actix-web/assets/1608415/0e9de7ce-4a53-4146-8b89-643dab9e41c1)

## Possible Solution

For now, the only workaround is avoid updating to the latest actix-http version. Sticking with version 3.4 prevent the error to happen.

## Steps to Reproduce (for bugs)

Just update to the latest actix-http, and call a endpoint in your project that gives you no body in the response.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.74.1 (a28077b28 2023-12-04)
- Actix Web Version: 4.4.0 or 4.4.1
- Actix-HTTP: 3.5
- Ubuntu 20.04 x64.

The following dependencies were also updated when I did the upgrade to actix-http 3.5:

- zstd ~0.12.4~ -> 0.13.0
- zstd-safe ~6.0.6~ -> 7.0.0

**Comment by robjtede** [comment]
Thanks for the prompt report.

Verified the fix through manual testing to get it released faster. A fresh `cargo update` should put you straight.

Also yanked 3.5.0 to be on the safe side and trigger warnings on peoples builds who've got that package in their tree already.

**Comment by mrsarm** [comment]
Thanks for quick patch ! It worked for me.
