### ISSUE TITLE
Why is the code below why version 4 cannot access httpserver, but version 3 can?

### ISSUE THREAD

**Issue by liu1998-yowu** [actix/actix-web#3243]
version 4 code:
use std::{sync::mpsc::{Sender, self}, thread::{self, sleep}, time::Duration};
use actix_web::{dev::Server, rt, HttpServer, App, web};

#[actix_web::main]
async fn main() {
    let (tx,rx) = mpsc::channel();
    sapwn_server(&tx).await;
    let _srv = rx.recv().unwrap();
    
    sleep(Duration::from_secs(10));
}
async fn sapwn_server(
    tx:&Sender<Server>
){
    let tx =tx.to_owned();
    thread::spawn(move ||{
        let sys = rt::System::new();
        let pre_srv = HttpServer::new(||{
            App::new()
            .service(web::resource("/").to(|| async { "hello world" }))
        }).bind(("0.0.0.0", 8999));
        let srv = pre_srv.unwrap().run();
        let _ = tx.send(srv);
        sys.run()
    });
}
After cargo run, the port is open, and hello world cannot be accessed through the browser.
![image](https://github.com/actix/actix-web/assets/81906221/8130c456-ce1e-4727-ae83-0012ec5585b8)
![image](https://github.com/actix/actix-web/assets/81906221/a14bbb5b-db44-4f8b-b46d-fb0f5e55aac1)

version 3 code:
![image](https://github.com/actix/actix-web/assets/81906221/1b4daf8a-ba26-4a93-b127-bac20124999c)

**Comment by moy2010** [comment]
This is not an issue. If you need help understanding why your code doesn't compile, open a discussion instead.
