### ISSUE TITLE
add Proxy-Connection header

### ISSUE THREAD

**Issue by lieka1** [actix/actix-web#3250]
proxy-connection is a default header send with chrome when using http/https proxy
maybe adding it?
https://www.oreilly.com/library/view/http-the-definitive/1565925092/re40.html#:~:text=The%20Proxy%2DConnection%20header%20is,do%20so%20without%20causing%20harm.
https://stackoverflow.com/questions/15460819/what-is-the-difference-between-connection-and-proxy-connection-in-http-header

**Comment by lieka1** [comment]
An example of http proxy request header
proxy-connection: Keep-Alive
proxy-authorization Basic ...
host: ...
user-agent: ...

**Comment by robjtede** [comment]
As this is a standard header I'm happy to add it to Actix Web. Worth mentioning that, in the meantime, you can create a `HeaderName` in a const context.

**Comment by robjtede** [comment]
The links provided don't paint this header in a very positive light. I'm inclined to leave it out of the built-in set of header names.

You can create for you app in a const context and use it just like you would the built-in ones:
```rust
const PROXY_CONNECTION: HeaderName = HeaderName::from_static("proxy-connection");
```

**Comment by lieka1** [comment]
Thank you for reply, i definitly know it is not a stand header, due to it cannot be found in mdn document
but this header is for sure a big thing in chrome.
check out this chrome extension document, it is a preserved header for webrequest, same level as other headers like host / content-length. It's just for compatibility for chrome.
https://developer.chrome.com/docs/extensions/reference/api/webRequest

Thank you for your timely response!
