### ISSUE TITLE
Filter out completely impossible characters.

### ISSUE THREAD

**Issue by ryankopf** [actix/actix-web#3257]
## Expected Behavior

I'm doing something like the below:
```rust
let path = req.path().trim_start_matches("/add_domain/");
let host = path;
let host = if host.starts_with("www.") { &host[4..] } else { host };
loghostname::log_hostname_if_new(host);
```
I've noted in testing that "host" can contain null characters, which should be impossible. We've detected third party clients intentionally sending null characters in the hostname field of their requests, either maliciously or by accident.

When we log the new hostname we've detected, our logs would get messed up due to these nulls.

## Current Behavior

Null characters can be part of request.path()

## Possible Solution

Filter out characters that should be "impossible" to be part of the request.

## Steps to Reproduce (for bugs)

1. Create a new project
2. Log the received hostname
3. Send a request containin null characters (this may be difficult to do)
4. See that the nulls are in the log.

## Context

Messes up logging of new and novel hostnames received, may mess up other forms of logging too.

## Your Environment

Windows 10 & Ubuntu Linux 22

rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by robjtede** [comment]
> Send a request containin null characters (this may be difficult to do)

If possible can you give me a test snippet for this bit?

**Comment by robjtede** [comment]
I've tried and failed to reproduce this using manual TCP connections and HTTP/1.1 request constructions.

```console
$ pbpaste | xxd -ps -r | nc 127.0.0.1 8080
```

```
# null-byte in path => 400 Bad Request (logs `ERROR [actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided`)
GET               47 45 54 20
/foo-\0-bar       2f 66 6f 6f 2d 00 2d 62 61 72
 HTTP/1.1         20 48 54 54 50 2f 31 2e 31 0d 0a
host: localhost   68 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 0d 0a
EOF               0d 0a

# null-byte (url-encoded) in path => 404 Not Found
GET               47 45 54 20
/foo-%00-bar      2f 66 6f 6f 2d 25 30 30 2d 62 61 72
 HTTP/1.1         20 48 54 54 50 2f 31 2e 31 0d 0a
host: localhost   68 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 0d 0a
EOF               0d 0a

# null-byte in host header => 400 Bad Request (logs `ERROR [actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided`)
GET /foo HTTP/1.1  47 45 54 20 2f 66 6f 6f 20 48 54 54 50 2f 31 2e 31 0d 0a
host: foo%00.com   68 6f 73 74 3a 20 66 6f 6f 00 2e 63 6f 6d 0d 0a
EOF                0d 0a

# null-byte (url-encoded) in host header => 404 Not Found
GET /foo HTTP/1.1  47 45 54 20 2f 66 6f 6f 20 48 54 54 50 2f 31 2e 31 0d 0a
host: foo%00.com   68 6f 73 74 3a 20 66 6f 6f 25 30 30 2e 63 6f 6d 0d 0a
EOF                0d 0a

# null-byte in user-agent header => 400 Bad Request (logs `ERROR [actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided`)
GET /foo HTTP/1.1       47 45 54 20 2f 66 6f 6f 20 48 54 54 50 2f 31 2e 31 0d 0a
user-agent: foo%00.com  75 73 65 72 2d 61 67 65 6e 74 3a 20 66 6f 6f 00 2e 63 6f 6d 0d 0a
EOF                     0d 0a
```

No null-bytes were presented in Logger.

If you find a reproduction case that triggers invalid behavior please do drop a comment here.
