### ISSUE TITLE
Session backends double encode JSON values

### ISSUE THREAD

**Issue by soundslocke** [actix/actix-web#326]
While toying with the [redis-session example](https://github.com/actix/examples/tree/master/redis-session) I noticed that when looking at the data stored within Redis the JSON values seem to be double encoded and then the whole JSON string is double encoded itself.

For example, set a session value with:

```rust
req.session().set::<String>("test", "hello!".to_string())?;
```

Then the value stored within Redis using the Redis session backend looks like:
```
{\"test\":\"\\\"hello!\\\"\"}
```

After seeing this I looked at the values stored using the cookie session backend to compare. It seems as if only the JSON values are double encoded in the cookie:
```
{"test":"\"hello!\""}
```

So, I've been attempting to learn why... it looks like the session `set()` and `get()` methods are calling `serde_json::to_string` and `serde_json::from_string` and then the same is happening again within the given backend's [`set_cookie()`](https://github.com/actix/actix-web/blob/master/src/middleware/session.rs#L385)/[`update()`](https://github.com/actix/actix-redis/blob/master/src/session.rs#L210) and [`load()`](https://github.com/actix/actix-web/blob/master/src/middleware/session.rs#L436)/[`load()`](https://github.com/actix/actix-redis/blob/master/src/session.rs#L159) methods. 

I see that the `state` is a `HashMap<String, String>` (at least for these two backends) so I'm guessing the double encoding is an intentional way to keep the internal state as nothing but strings. Is this desirable? I'm unsure why the Redis backend seems to be encoding everything twice after encoding the values twice yet the cookie backend only encodes values twice. How might one go about ensuring everything is only encoded once? Any thoughts or explanations appreciated!

**Comment by fafhrd91** [comment]
`HashMap<String, String>` is intentional choice. reason is simplicity.

**Comment by fafhrd91** [comment]
we can storage format before 1.0, any ideas. we have several weeks

**Comment by soundslocke** [comment]
My only input is that it shouldn't encode/decode anything as JSON more than once :smile: -- I don't feel adept enough with Rust to suggest what a good session storage format/structure might look like...

**Comment by fafhrd91** [comment]
i couldn't come up with better idea without adding new dependency.

**Comment by fafhrd91** [comment]
wont changes this in 1.0
