### ISSUE TITLE
SendRequest execution failed with the "internal error: entered unreachable code"

### ISSUE THREAD

**Issue by alekseysidorov** [actix/actix-web#329]
This [code](https://github.com/alekseysidorov/exonum/blob/8df2baf1f6e00759f3e4636deeff6e2849090ff9/testkit/src/api.rs#L209) panics with message in this [test](https://github.com/alekseysidorov/exonum/blob/8df2baf1f6e00759f3e4636deeff6e2849090ff9/testkit/tests/counter/main.rs#L449) 

```
thread 'test_explorer_blocks' panicked at 'internal error: entered unreachable code', /Users/aleksey/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.6.13/src/client/pipeline.rs:383:27
```

I suppose that there are problems with timeout handling in pipeline.

At the moment I can't write a minimal example for bug, but you can launch `cargo test test_explorer_blocks` manualy from the [`8df2baf1f6e00759f3e4636deeff6e2849090ff9`](https://github.com/alekseysidorov/exonum/tree/8df2baf1f6e00759f3e4636deeff6e2849090ff9/testkit) revision of my code.

**Comment by fafhrd91** [comment]
fixed in 0.6
0.6.14 is released
