### ISSUE TITLE
with.rs code uses UnsafeCell unsafely. 

### ISSUE THREAD

**Issue by ZerothLaw** [actix/actix-web#331]
UnsafeCell documentation says: 

> Note that while mutating or mutably aliasing the contents of an & UnsafeCell<T> is okay (provided you enforce the invariants some other way), it is still undefined behavior to have multiple &mut UnsafeCell<T> aliases.

On master branch, src/with.rs has unsafe behavior at the lines:
104
209
359

Not to mention the other uses of unsafe blocks in order to get a raw pointer without doing any checks on required invariants at lines:
90
98

Example unsafe behavior:
```rust
let hnd: &mut F = unsafe { &mut *self.hnd.get() };
self.fut2 = Some((*hnd)(item));
```

The problem here is that fut2 is simply an option that can be easily unwrapped and multiple mutable references can be obtained that way. 

Proposed solution: Add invariant declarations in comments and enforce those invariants before entering unsafe code. You can use Rc::weak_count and Rc::strong_count to do some basic invariant checking. If this creates issues elsewhere in the code, for example panics or compiler warnings, then we should resolve those issues or redesign the structs here to avoid this issue. 

Acceptance conditions: 

- Invariants declared and checked
- Compiler warnings turned on
- Linting turned on
- Both pass the file with no complaints
- No issues arise in other files or dependencies

**Comment by fafhrd91** [comment]
fixed
