### ISSUE TITLE
Unexpected routing

### ISSUE THREAD

**Issue by DenuxPlays** [actix/actix-web#3317]
Hey when two routes are registered like this:
```rust
#[get("/{transaction_id}")]
pub(crate) async fn get_one() {}

#[get("/search")]
pub(crate) async fn search() {}
```
Actix matches a request to `/search` to  `/{transaction_id}`.
I kinda understand this behavior but I think this should either throw an compile error (idk if this is possible), an error on start up or just work.

## Expected Behavior

One of these three options

- compile error
- startup error
- **PREFERRED:** Just match to the other route

## Current Behavior

It just takes the first one that's getting registered (I guess is kinda workaround but I am still testing if this works reliable)

## Possible Solution

///

## Steps to Reproduce (for bugs)

1. create two endpoint as mentioned above
2. the `"/{transaction_id}` should be registered first
3. then register the other one
4. fire a get request at `/search`

## Context

It was kinda weird that I got a 404 response saying that he could not parse "search" as i32.
As I find out what was causing this a few minutes passed.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): 1.77.0
- Actix Web Version: 4.5.0

**Comment by moy2010** [comment]
That's expected. Your first route will match eagerly. The solution is to place such routes at the end of the router.
