### ISSUE TITLE
debug your demo hello world,An error occurred

### ISSUE THREAD

**Issue by zhangxize** [actix/actix-web#3377]
debug your demo hello world,An error occurred
thread 'main' panicked at auth\casbin\src\main.rs:30:10:
called `Result::unwrap()` on an `Err` value: IoError(Os { code: 3, kind: NotFound, message: "系统找不到指定的路径。" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by SteveLauC** [comment]
Just tested [hello-world](https://github.com/actix/examples/tree/master/basics/hello-world) on my host, and it works pretty well.

Would you like to provide a minimal reproducible code so that we can help?

**Comment by robjtede** [comment]
> auth\casbin\src\main.rs

looks like you're testing the casbin example from the examples repo, please file an issue there if your issue persists

**Comment by zhangxize** [comment]
cargo run is normal,but debug run an error occurred
![helloworlderror](https://github.com/actix/actix-web/assets/24538563/022a2a85-74ca-42b6-9411-a1be3e2bb195)
