### ISSUE TITLE
actix-web v1.0.8 & actix-http-0.2.11 issue

### ISSUE THREAD

**Issue by findzaatar** [actix/actix-web#3379]
## Expected Behavior

Serving on http://localhost:3000

## Current Behavior

```
error[E0277]: cannot subtract `TimeDelta` from `Tm`
   --> /Users/aradwyr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-http-0.2.11/src/cookie/jar.rs:226:44
    |
226 |             cookie.set_expires(time::now() - Duration::days(365));
    |                                            ^ no implementation for `Tm - TimeDelta`
    |
    = help: the trait `Sub<TimeDelta>` is not implemented for `Tm`
    = help: the following other types implement trait `Sub<Rhs>`:
              <Tm as Sub<time::Duration>>
              <Tm as Sub>

error[E0308]: mismatched types
   --> /Users/aradwyr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-http-0.2.11/src/cookie/mod.rs:742:40
    |
742 |         self.set_expires(time::now() + twenty_years);
    |                                        ^^^^^^^^^^^^ expected `Duration`, found `TimeDelta`

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `actix-http` (lib) due to 2 previous errors
```

## Steps to Reproduce (for bugs)

1. cargo run

## Context

Trying to run a web server based off of the O'Reilly Programming Rust book (2nd ed revised)

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.74.0 (79e9716c9 2023-11-13)

[dependencies]
actix-web = "1.0.8"
serde = { version = "1.0", features = ["derive"] }

**Comment by robjtede** [comment]
Sorry, Actix Web v1 is unsupported.

I'd be happy to assist with upgrading to v4.

**Comment by aradwyr** [comment]
Thank you, that'd be so great! If you have docs for that I'll check those out first

**Comment by findzaatar** [comment]
> Sorry, Actix Web v1 is unsupported.
> 
> I'd be happy to assist with upgrading to v4.


Thank you, that'd be so great! If you have docs for that I'll check those out first

**Comment by findzaatar** [comment]
Nevermind, I found the official [Programming Rust code snippets](https://github.com/ProgrammingRust/examples/tree/master)
