### ISSUE TITLE
actix-web + webassembly

### ISSUE THREAD

**Issue by icommit** [actix/actix-web#340]
Are there any plans to support Webassembly? I recently tried to compile a webassembly and actix-web demo but it seems the net2 crate which is a dependent crate in tokio is generating lots of errors. But Webassembly is a big deal and it would be nice to incorporate this feature.

**Comment by DoumanAsh** [comment]
it is very unlikely to run HTTP servers through webassembly.

As the wasm runs on client side it doesn't have access to such facilities.

P.s. actix-web is meant for back-end, not front-end

**Comment by fafhrd91** [comment]
I think it should be possible to run subset of actix, but not actix-web

**Comment by yonkeltron** [comment]
Just a note that [WASI](https://wasi.dev/) is coming along great, especially with the announcment of the [Bytecode Alliance](https://bytecodealliance.org/articles/announcing-the-bytecode-alliance) earlier this week. I would love to see this reconsidered, although I did read about this very subject [over here](https://users.rust-lang.org/t/another-small-step-to-wasm-compatibility-actix-actors-in-the-browser/26318).

**Comment by hkchindeko** [comment]
Hi, is Actix already supporting wasm32-wasi target? If no is that on the roadmap?
Will be good, now that wasm32-wasi can be run in Containerd, Docker and even can run in K8S. Work are being done to include multi-threading in wasm.

**Comment by lovasoa** [comment]
Is there no plan to support wasm ? All the modern serverless (deno, cloudflare, vercel, fermyon, ...), require you to compile your code to wasm.

**Comment by robjtede** [comment]
For WASI support, I'd ask for a new and fleshed out feature request issue.
