### ISSUE TITLE
Can not set Content-Length response header for S3 protocol

### ISSUE THREAD

**Issue by zrleblanc** [actix/actix-web#3413]
We just ran into issue #1439 when implementing S3 server code. While the work around works for "small" responses where we can just generate some random data to be thrown away for the body, when this needs to be done for muliti-gigabyte files it becomes very expensive and unnecessary.
I'd like to re-open the discussion around not being able to manually set this header

## Expected Behavior

Be able to set the Content-Length header in the response builder for S3 compatibility of large files. https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html

## Current Behavior

The Content-Length header can only be set programmaticly by including a body which is then calculated the length and then discarded. This is fine for "small" bodies, but multi-gigabyte bodies is impractical. 

## Possible Solution

Allow for manually specified Content-Length response header that overrides the computed value with big warnings in the documentation saying that it is highly discouraged to override this value.

## Steps to Reproduce (for bugs)

1. Set Content-Length in the response header >0
2. Do not include a body in the response
3. Check the Content-Length response header value in a client is 0.

## Context

It is common practice in S3 to HEAD a file to get things like size and ETAG in order to provide download progress bars for downloading of large files and checking the integrity of the file. Not being able to provide accurate size efficiently breaks these progress bars.

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
- Actix Web Version:

**Comment by nponsard** [comment]
I'm stumbling on the same problem today. A thought I had was to have a body that reports a big length but doesn't take a lot of memory. I haven't looked into how I could do that though.

**Comment by nponsard** [comment]
I found one workaround, using a body that reports a fake size : 

```rust
struct FakeBody {
    size: usize,
}

impl MessageBody for FakeBody {
    type Error = actix_web::Error;
    fn size(&self) -> BodySize {
        BodySize::Sized(self.size as u64)
    }

    fn poll_next(
        self: Pin<&mut Self>,
        _: &mut Context<'_>,
    ) -> Poll<Option<Result<Bytes, actix_web::Error>>> {
        Poll::Ready(None)
    }
}
```

And then in the head request you can create a response like that : 
```rust
 Ok(HttpResponse::Ok()
        .content_type("application/octet-stream")
        .body(FakeBody { size }))
```

It will set the content-length to the size you want.

**Comment by zrleblanc** [comment]
If I get this right, you are setting the Body to the size you want, but when Actix reads it, it grabs the size then tries to Poll for data and gets nothing? I just want to make sure it's not generating any data to get thrown away. When doing 10k or more per second it could be very expensive.
Thank you for posting this workaround, we will at least give it a try. (It shouldn't be this convoluted).

**Comment by nponsard** [comment]
I haven't done much testing, but according to the discussion in https://github.com/actix/actix-web/issues/1439 when a HEAD request has a body it is not read (so no data is polled) and only the size is checked.

**Comment by robjtede** [comment]
I've updated [the s3 example](https://github.com/actix/examples/blob/master/forms/multipart-s3/src/main.rs#L67-L79) to demonstrate how this is achieved within the current API.

Tested with cURL, xh, and HTTPie.
