### ISSUE TITLE
Error occurred during request handling: unexpected end of file

### ISSUE THREAD

**Issue by max-frai** [actix/actix-web#345]
Here is simplified example which reproduces this error
https://github.com/max-frai/actix-issue

Async handler which returns NamedFile results in error:
`ERROR 2018-06-25T11:59:41Z: actix_web::pipeline: Error occurred during request handling: unexpected end of file ERROR 2018-06-25T11:59:41Z: actix_web::server::h1: Unhandled error: unexpected end of file`

**Comment by ousado** [comment]
The problem is that in [ChunkedReadFile](https://github.com/actix/actix-web/blob/master/src/fs.rs#L444) a slice of length 0 is passed to file.read, the vector has the correct capacity, but not the correct length.

**Comment by DoumanAsh** [comment]
@max-frai Can you please check current master branch for whether this problem is still present?

**Comment by DoumanAsh** [comment]
@max-frai This time it is right PR so you can check out latest master for fix of your issue 😄
