### ISSUE TITLE
Needs an example about send and revice message from actix-web to other actix actors

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#349]
I saw actix documentation (actor system), it was awesome and i want to use it in my project but i'm a bit confused to using actix-web and other actors.

**Comment by DoumanAsh** [comment]
Generally you can store actor addresses in your state and use it to message them and since they return futures you can return these futures too

We have example repository and for example https://github.com/actix/examples/blob/master/async_db/src/main.rs

**Comment by fafhrd91** [comment]
you store address of the actor
https://github.com/actix/examples/blob/master/async_db/src/main.rs#L40

and then use it in handler
https://github.com/actix/examples/blob/master/async_db/src/main.rs#L48

**Comment by kporika** [comment]
is there an example similar to this to send a message to an actor and not wait for the response back,
I'm looking to send the HttpRequest and HttpResponse Objects on each of the handler functions to an audit actor, that just receives them and does some processing and logs them to an audit file. All the examples show there is a response expected from an actor handler function.
