### ISSUE TITLE
Request to Use “actix” in Crate Name

### ISSUE THREAD

**Issue by 3schwartz** [actix/actix-web#3507]
Thank you for creating such an amazing web framework!

I’ve developed a solution for integrating OpenID Connect as a backend-for-frontend with Actix, which you can find here: [actix-oidc-bff](https://github.com/3schwartz/actix-oidc-bff). I’d like to publish it as a crate and request approval to use “actix” in the name (actix-oidc-bff).

Let me know if this is okay. Thanks again for your great work!

**Comment by robjtede** [comment]
yea that's fine, plenty of third-party libs use the actix- prefix

**Comment by 3schwartz** [comment]
> yea that's fine, plenty of third-party libs use the actix- prefix

Thanks
