### ISSUE TITLE
StaticFiles's etag and last-modified header may not work in cluster

### ISSUE THREAD

**Issue by haozileung** [actix/actix-web#351]
In out StaticFiles handler, etag and last-modified was set to check file changes and response with 304.
This work well in single node server.
But when it comes to scale out, the etag is annoying because it never be the same in different server.
So to have a better cache control, I think we should add the cache-control header, and have a option to disable etag and  last-modified header when user want to use actix-web in a cluster.
Any thoughts?

**Comment by DoumanAsh** [comment]
I think we should be able to disable Etag/Last-Modified if user wishes.

I don't think `Cache-Control` is wise approach in this case
But I also think there should be a way for user to specify default headers.

The current work around I can suggest you is to use `Middleware` to fix outgoing requests headers(i.e. remove etag/last-modified from your responses)

**Comment by ousado** [comment]
One (and arguably the) correct way is generating etags deterministically, e.g. based on content. The  caching strategy certainly shouldn't be determined by the number of nodes a service is running on.
And of course all of this must be customizable.

**Comment by OtaK** [comment]
Shall we md5 the files to compute an etag?

**Comment by DoumanAsh** [comment]
@OtaK It is one of the options I guess, but I feel like it would be better to have configuration option for that as checksum strategy is more expensive comparing using File metadata and not all would need it as in case of single node, the metadata way is reliable enough

**Comment by DoumanAsh** [comment]
JFYI: We added generic [configuration](https://actix.rs/actix-web/actix_web/fs/trait.StaticFileConfig.html) for file services so now you can customize it all through static methods as trait parameter to `NamedFiles` and/or `StaticFiles`

**Comment by dessalines** [comment]
I'm still stuck on this for `.service(actix_files::Files::new(`, I can't figure out how to add response headers like `Cache-Control`...
