### ISSUE TITLE
http2 is broken because of h2 upgrade

### ISSUE THREAD

**Issue by fanzeyi** [actix/actix-web#352]
I've created an issue yesterday at actix/examples#23 but I believe it is more appropriate to discuss it here. 

It appears the latest `h2` upgrade breaks `actix-web`'s HTTP2 because of the add of this check: https://github.com/carllerche/h2/blob/master/src/server.rs#L1048-L1053.

I tested locally with commenting out the if block and I am certain this is the part causing the issue. I am not familiar with HTTP2 protocol nor SSL nor actix-web's code. So unfortunately I could not come up with a fix for this. 

Thanks!

**Comment by fanzeyi** [comment]
related: carllerche/h2#285

**Comment by OtaK** [comment]
Hello,

I've looked into it, and it seems that there's an an edge case with the `IoWrapper::read()` implementation; if the `bytes.len()` was strictly 2x the size of `buf.len()`, we'd discard our remaining bytes while there's still one iteration needed.

See here: https://github.com/OtaK/actix-web/commit/ec15cf2814116fa0dee1c0712fc754820e2bfb42

As usual, tests are passing ;)

Is a PR needed? 

EDIT: Actually, I was wrong, I'll continue looking into the matter though

**Comment by DoumanAsh** [comment]
@OtaK Feel free yes, all PRs are welcome.

**Comment by fafhrd91** [comment]
fixed in 0.6.15
