### ISSUE TITLE
Mixing actix actors and the web server

### ISSUE THREAD

**Issue by sstelfox** [actix/actix-web#353]
The `actix` actors on their own are working great, and are kind of a red herring for this issue. I'm trying to add an HTTP endpoint with the other actors which I couldn't seem to find an example of. You can see a pretty minimal example of what I'm trying to [do here][1] (which compiles fine, just won't run).

The reason I say the other actors are kind of a red herring is that if you strip out all of the `BackgroundTaskActor` related code it will throw the same error.

Specifically the `start()` off the HttpServer is panic'ing with:

```
thread 'main' panicked at 'System is not running'
```

There used to be a [similar issue][2] with the same results that was due to a mismatch of versions between actix and actix-web, which also seems to be the case here as `actix-web` depends on 0.5.8 not the 0.6.x branch.

I'm testing this on rust version: `rustc 1.28.0-nightly (e3bf634e0 2018-06-28)`

[1]: https://github.com/sstelfox/actix-background-worker
[2]: https://github.com/actix/actix-web/issues/46

**Comment by lholden** [comment]
For whatever reason Actix Web is using actix 0.5 and not 0.6. Does it work if you pin actix to 0.5?

**Comment by sstelfox** [comment]
Yeah looks like the 0.5.8 version doesn't have the supervised system services. After forcing it back down to 0.5.8 I was able to refactor it in a way that work and updated my sample repo with the changes :+1:.
