### ISSUE TITLE
has_route() doesn't know about prefixes.

### ISSUE THREAD

**Issue by lholden** [actix/actix-web#354]
has_route() currently does not have any understanding of routes containing a prefix. 

For example:
```
let app = App::new().scope("/scope", |s| s.resource("/sub", |r| r.method(Method::GET).f(index)) );
....
req.route().has_route("/scope/sub") // false
```

This prevents applications and middleware from inspecting routes containing a prefix. For example, one cannot apply the `NormalizePath` middleware against any prefix containing route. It will successfully *normalize* the path, but will fail to redirect when checking to see if the path exists before initiating a redirect.

---

This is documented on the has_route method, but after spending way too long trying to get the NormalizePath middleware to actually apply against prefixed routes it seemed pertinent to create an issue.

**Comment by OtaK** [comment]
Hello,

I've tried my luck at implementing the change, all tests are passing.

Should I create a PR?

https://github.com/OtaK/actix-web/commit/80088a117f30cc76fbe92c8b8c77ea5a7ec0d3a6
