### ISSUE TITLE
error[E0603]: module `actix` is private

### ISSUE THREAD

**Issue by Paradyx** [actix/actix-web#356]
Running the example from your [documentation example](https://actix.rs/actix-web/actix_web/client/fn.get.html) inside a test, results in the error: ``error[E0603]: module `actix` is private``

This happens on version 0.6.14 from cargo.

```
mod test {
    use actix_web::{actix, client};
    use futures::Future;

    #[test]
    fn connection_example() {
        actix::run(|| {
            client::get("http://www.rust-lang.org")   // <- Create request builder
                .header("User-Agent", "Actix-web")
                .finish().unwrap()
                .send()                               // <- Send http request
                .map_err(|_| ())
                .and_then(|response| {                // <- server http response
                    println!("Response: {:?}", response);
                    Ok(())
                })
        });
    }
}
```

**Comment by DoumanAsh** [comment]
If I'm not mistaken the documentation is for current master branch version, and not the cargo version.

For cargo version please use [docs.rs](https://docs.rs/actix-web/0.6.11/actix_web/)

Otherwise I would suggest to use master branch as dependency

**Comment by Paradyx** [comment]
Thx I will try it.
