### ISSUE TITLE
Using Scopes with CorsBuilder

### ISSUE THREAD

**Issue by Nazariglez** [actix/actix-web#359]
Scopes can be used with CorsBuilder somehow? I want to make a full cors api rest, and my resources are declared in the cors builder, but i can't use scope, seems like just App support this. 

With scope i can create versions of my api and fill with the routes easily.
- CorsBuilder
    - scope v1
        - set_routes(v1::routes)
    - scope v2
        - set_routes(v2::routes)

**Comment by fafhrd91** [comment]
at the moment it is not possible to do from cors builder. You have to register cors middleware for each resource within scope. you can use same cors instance as it implements `Clone`

**Comment by Nazariglez** [comment]
i'm using a `&mut cors` to add the resources with a function inside every mod version, and it's works. i'll close this. Thanks
