### ISSUE TITLE
Support HTTP/2 with rustls

### ISSUE THREAD

**Issue by DemiMarie** [actix/actix-web#36]
This is a feature request to support HTTP/2 with [rustls](https://github.com/ctz/rustls)

**Comment by AlbanMinassian** [comment]
info only : https://docs.rs/tokio-rustls/0.5.0/tokio_rustls

**Comment by fafhrd91** [comment]
I can not add rustls support at the moment. all packages needs to depend on same ring package

**Comment by mssun** [comment]
> all packages needs to depend on same ring package

What does it mean? I also hope to see rustls support. I understand rustls depends on ring internally.

**Comment by fafhrd91** [comment]
rustls depends on ring ^0.13.0-alpha
cookie depends on ring 0.12.1

I think it is not possible to compile two different ring dependency

**Comment by mssun** [comment]
Correct me if I'm wrong. I remember that cargo can compile with two different version crates. But probably have two copies of library code?

Also, the master cookie support ring ^0.13.0-alpha in Jan. https://github.com/alexcrichton/cookie-rs/blob/master/Cargo.toml#L20

**Comment by fafhrd91** [comment]
cargo can, but ring uses asm which is the problem. I don't think alpha dependency is good idea

**Comment by mssun** [comment]
I see. Thank you so much!

**Comment by DemiMarie** [comment]
May I ask why?

RustTLS is already used in production.

**Comment by fafhrd91** [comment]
You can use anything in production. But if library is ready for production why it is not released as stable version.

**Comment by DemiMarie** [comment]
Futures is not stable either.

**Comment by fafhrd91** [comment]
choice is yours. 

as a maintainer of the actix project i chose not to integrate with rustls at this stage.

**Comment by tommoa** [comment]
One option to solve the issue of differing ring dependencies is to use rustls 0.11 and tokio-rustls 0.4. Both of them use ring 0.12.1.

**Comment by hayd** [comment]
Multiple ring versions should work together after https://github.com/briansmith/ring/pull/619 is merged.

**Comment by ctz** [comment]
This should now be unblocked by https://crates.io/crates/rustls/0.13.0 which depends on the latest ring release without the single-version constraint. Please do let me know if I can help :+1:

**Comment by DoumanAsh** [comment]
We do have `cookie` that uses ring 0.12 also though

Hopefully after `0.13` stable ring we get new version of cookie https://github.com/alexcrichton/cookie-rs/pull/106

**Comment by fafhrd91** [comment]
fixed by #427
