### ISSUE TITLE
Using with actix 0.6

### ISSUE THREAD

**Issue by gabisurita** [actix/actix-web#361]
Is there any way to run actix-web on any plan to port it to actix 0.6? I couldn't find an issue specifically about this.

I depend on a fix/feature released in actix 0.6 (https://github.com/actix/actix/issues/74)

related to:
https://github.com/actix/actix-web/issues/353

**Comment by fafhrd91** [comment]
only way is to use actix and actix-web from the master

I am planing to make new release of actix and actix-web this weekend
