### ISSUE TITLE
Setting content encoding gzip for already compressed content

### ISSUE THREAD

**Issue by pka** [actix/actix-web#363]
I'm getting gzipped data as `Vec<u8>` from a function and have to add correct headers for the http response.

With
```
resp = HttpResponse::Ok()
    .content_type("application/x-protobuf")
    .content_encoding(ContentEncoding::Gzip)
    .body(*gzippeddata);
```
actix compresses the data a second time.

Until recently the following workaround did the trick: 

```
resp = HttpResponse::Ok()
    .content_type("application/x-protobuf")
    .content_encoding(ContentEncoding::Identity)
    .header(header::CONTENT_ENCODING, "gzip")
    .body(*gzippeddata);
```

Since the HttpRequest mutability refactoring this doesn't work anymore. Is there a proper way to set
the content encoding header without changing the data?

**Comment by fafhrd91** [comment]
Your workaround code should still work. You modify HttpResponseBuilder, it has nothing to do with HttpRequest

**Comment by pka** [comment]
No, it doesn't work anymore. The content-encoding header is missing. Last version which was certainly working was 0f27389e7207fb286ac47cd81f7b6a5e0622cf29

**Comment by fafhrd91** [comment]
should be fixed in master
