### ISSUE TITLE
Comments on the WebSocket implementation

### ISSUE THREAD

**Issue by bluetech** [actix/actix-web#365]
Some notes I noticed when skimming over the code. The presentation is jumbled but I thought it might be useful anyway.

---

This code can truncate on 32-bits architectures:

```rust
let len = NetworkEndian::read_uint(&buf[idx..], 8) as usize;
```

This repeats a couple times.

In general, `<u64> as usize` is suspicious, especially if read from the network.

---

```rust
LittleEndian::read_u32(mask);
```

I'm not sure why `LittleEndian` is used here - it looks a bit suspicious for big-endian architectures. Maybe `NativeEndian` should be used?

---

```rust
        // unmask
        if let Some(mask) = mask {
            let p: &mut [u8] = unsafe {
                let ptr: &[u8] = &data;
                &mut *(ptr as *const _ as *mut _)
            };
            apply_mask(p, mask);
        }
```

This seems quite dangerous, `data` is a `Bytes` but is mutated directly. If the invariant does indeed hold that `data` is the only reference to the underlying bytes, then the following should work (untested). If not, then the unsafe is probably incorrect, or at least requires justification.

```rust
        // unmask
        let mut data = data.try_mut().unwrap();
        if let Some(mask) = mask {
            apply_mask(&mut data, mask);
        }
```

---

There are a lot of calls like this:

```rust
 let raw_code = NetworkEndian::read_uint(payload.as_ref(), 2) as u16;
```

This can be simplified to:

```rust
 let raw_code = NetworkEndian::read_u16(payload.as_ref());
```

---

All addition operations on the payload length can overflow, e.g.

```rust
let mut buf = BytesMut::with_capacity(p_len + 10);
```

---

```rust
/// Mask/unmask a frame.
#[inline]
pub fn apply_mask(buf: &mut [u8], mask: u32) {
    unsafe { apply_mask_fast32(buf, mask) }
}

/// Faster version of `apply_mask()` which operates on 8-byte blocks.
///
/// unsafe because uses pointer math and bit operations for performance
#[inline]
#[cfg_attr(feature = "cargo-clippy", allow(cast_lossless))]
unsafe fn apply_mask_fast32(buf: &mut [u8], mask_u32: u32) { ... }
```

The usage of `unsafe` in `apply_mask` does not make sense - if it just forwards the input without any validations to an `unsafe fn`, then it means one of two things:

1. `apply_mask_fast32` should not be `unsafe`.
2. `apply_mask` should be `unsafe`.

Also, the explanation of `unsafe fn` on `apply_mask_fast32` does not really explain the `unsafe`. I mean, "math and bit operations for performance" does not make a function unsafe - a function marked as `unsafe` implies it assumes some preconditions on its inputs, e.g. the buffer has some alignment, the buffer is of a certain size, etc. So what the comment should state is those preconditions.

The comment "Faster version of `apply_mask()`" is confusing given that `apply_mask` calls `apply_mask_fast32`.

The name `apply_mask_fast32` is confusing, given the function works on 8-byte blocks.

---

```rust
    // Possible first unaligned block.
    let head = min(len, (8 - (ptr as usize & 0x7)) & 0x3);
    let mask_u32 = if head > 0 {
        let n = if head > 4 { head - 4 } else { head };

        <snip>

        if head > 4 {
            *(ptr as *mut u32) ^= mask_u32;
            ptr = ptr.offset(4);
            len -= 4;
        }
```

Because of the `& 0x3`, it is guaranteed that `head <= 3`, so the two conditions `if head > 4` are always false. I am too lazy to follow the entire function but it seems like it needs a careful look.

**Comment by fafhrd91** [comment]
thanks.

1. added check for `<u64> as usize`
2. `LittleEndian` is used because it is not number, just 4 bytes
3. added unsafe comment
4. i dont want to add overflow checks for every addition

could you provide some test cases or pr?

**Comment by bluetech** [comment]
No, sorry. Hopefully someone else will.

For testing overflows, the following frame can be useful. It says it will send a body with a full size of `2^64-1` bytes. Note that it is missing the actual body. A version for 32-bit architectures can be written as well by turning some of the ones to zeros.

```
0b1000_0011, 0b1111_1111, 0b1111_1111, 0b1111_1111,
0b1111_1111, 0b1111_1111, 0b1111_1111, 0b1111_1111,
0b1111_1111, 0b1111_1111, 0b0000_0000, 0b0000_0000,
0b0000_0000, 0b0000_0000,
```

Also, you should consider fuzzing the parser.

**Comment by fafhrd91** [comment]
I already added check for frame size before casting to usize.

**Comment by fafhrd91** [comment]
i will consider fuzzing.

**Comment by Shnatsel** [comment]
I've noticed the following comment at the top of `mask.rs`: "This is code from [Tungstenite project](https://github.com/snapview/tungstenite-rs)"

If I fuzz tungstenite, will this directly benefit actix-web, or there would be more steps to be taken?

Also, should the fixes already done in the scope of this issue be also applied to tungstenite?

**Comment by Shnatsel** [comment]
I have opened a pull request to add fuzzing support to Tungstenite: https://github.com/snapview/tungstenite-rs/pull/44

The interesting part for you is the fuzzing seeds - a set of websocket messages that exercises interesting codepaths in tungstenite. It should let you kickstart your own websocket fuzzing and save quite a bit of time.

For a quicks start on fuzzing Rust code see [Rust fuzz book](https://rust-fuzz.github.io/book/introduction.html).
