### ISSUE TITLE
Replace use of `UnsafeCell` with `LazyCell`

### ISSUE THREAD

**Issue by Diggsey** [actix/actix-web#366]
There exists a crate which is well tested and implements identical functionality:

http://indiv0.github.io/lazycell/lazycell/struct.LazyCell.html

I plan on opening a PR for this myself.

**Comment by DoumanAsh** [comment]
I'm not sure what is the reason for replacing `UnsafeCell`?

**Comment by Diggsey** [comment]
See #368 for the difference to the code.

In general, avoiding re-implementing unsafe code is good. LazyCell is more general, cleanly encapsulates the unsafe implementation, and is just as fast. Should similar initialisation be required elsewhere, code can reuse that abstraction instead of duplicating the unsafe code again.
