### ISSUE TITLE
Extractors are not working 

### ISSUE THREAD

**Issue by Nazariglez** [actix/actix-web#367]
Hi guys, i have a weird issues with the extractors, i tried a lot of them, but no one works for me, i just made a minor test-case, maybe i'm doing something wrong.

Rust: 1.27.0 (3eda71b00 2018-06-19)
actix: 0.58
actix_web: 0.6.14

This is my main:
```
#[macro_use] extern crate serde_derive;
extern crate actix_web;

use actix_web::{http, server, App, HttpRequest, Responder, Json};

#[derive(Deserialize)]
struct User {
    name: String
}

fn get_user(user:Json<User>) -> impl Responder {
    format!("Hello {}!", user.name)
}

fn get_user2(req: HttpRequest) -> impl Responder {
    let username:String = req.match_info().query("name").unwrap();
    format!("Hello {}!", username)
}

fn main() {
    std::env::set_var("RUST_LOG", "info");

    server::HttpServer::new(|| {
        App::new()
            .resource("/a/{name}", |r| r.method(http::Method::GET).with(get_user))
            .resource("/b/{name}", |r| r.method(http::Method::GET).with(get_user2))
    })
    .bind("127.0.0.1:8080")
    .expect("Can not bind to port 8000")
    .run();
}
```

If i try to access to localhost:8080/a/john a 400 bad request it's returned, but with /b/john return the text hello john!.

Anybody can advice me about what i'm doing wrong here?

**Comment by DoumanAsh** [comment]
If you read [Json](https://actix.rs/actix-web/actix_web/struct.Json.html) documentation you'll see important bit:

> To extract typed information from request's body, the type T must implement the Deserialize trait from serde.

So `Json` is intended for purpose of parsing Request's body.
What you want is to parse path component and for that you need [Path](https://actix.rs/actix-web/actix_web/struct.Path.html)

**Comment by Nazariglez** [comment]
Oh god, you're right! I need some sleep because i swear i tried path also, and didn't work, it's my fault, sorry! Thanks for your help.
