### ISSUE TITLE
serde query extractor fails on simple enum types

### ISSUE THREAD

**Issue by mqudsi** [actix/actix-web#371]
It seems that something in how the contents of a query string are passed to serde is causing breakage with simple enum types.

For the enum

```rust
// #[serde(untagged)]
// #[serde(rename_all = "camelCase")]
#[derive(Deserialize)]
pub enum ResponseType {
    Token,
    Code
}

#[derive(Deserialize)]
pub struct AuthRequest {
    client_id: String,
    redirect_uri: String,
    response_type: ResponseType,
    scope: String,
}
```

and with the handler

```rust
fn authorize(params: Query<AuthRequest>) -> impl Responder {
    format!("Do you authorize this application to sync files on your behalf?")
}
```

a request to `/authorize?...&response_type=code` (or `Code` or `ResponseType::Code` or `1` or any of a dozen other permutations I tried) I get back an error along the lines of the following:

```
 DEBUG actix_web::pipeline    > Error { err: "invalid type: string \"code\", expected enum ResponseType" }


 INFO  actix_web::middleware::logger > 127.0.0.1:52722 [06/Jul/2018:22:54:00 -0500] "GET /authorize?client_id=ebb82a88-8197-11e8-85a6-fb14d7e72e94&redirect_uri=msn.com&response_type=code HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 0.000427
```

As you can see from the commented-out code, I also tried playing around with different serde enum representations and formatting options.

**Comment by mqudsi** [comment]
I suppose it might actually be this: https://github.com/nox/serde_urlencoded/issues/35

**Comment by fafhrd91** [comment]
I don’t think we can do anything. This need bug fix from upstream.

@Dowwie am I right?

**Comment by Dowwie** [comment]
@fafhrd91 it seems that serde_urlencoded is no longer being maintained.. there's been a pending PR since Feb 2018 that upgrades to support enums: https://github.com/nox/serde_urlencoded/pull/30

I pinged the author weeks ago but haven't gotten any response

**Comment by fafhrd91** [comment]
that is unfortunate. so we need fork it or we need replacement

**Comment by DoumanAsh** [comment]
@Dowwie I'll ping nox on IRC if he is still around there I'll ask him about crate's state

**Comment by DoumanAsh** [comment]
Please see how you can use enum now https://github.com/actix/actix-web/blob/master/tests/test_handlers.rs#L94-L134

**Comment by mqudsi** [comment]
I don't even have to try it out, that's my code right there 😄

Thank you for the efficacious remedy.

**Comment by Roms1383** [comment]
> Please see how you can use enum now https://github.com/actix/actix-web/blob/master/tests/test_handlers.rs#L94-L134

Link is outdated 😅
