### ISSUE TITLE
Document how to send HTML code

### ISSUE THREAD

**Issue by kud1ing** [actix/actix-web#372]
Maybe this is documented somewhere, but i couln't find it.

I think HTML code needs to be returned from a handler via something like `HttpResponse::Ok().content_type("text/html").body(html_string)`

If one returns a plain String in the handler, the `HttpResponse` implementation sets the content type to "text/plain". This makes Safari wrap the HTML code in a `<html><head></head><bod><pre ...> ....` which puzzled me for a while

**Comment by DoumanAsh** [comment]
I'm not sure in what form you would like to have it documented?

As we do not have any special support for sending out HTML, there is nothing really to document.
So it is user responsibility to ensure proper `Content-Type` header

You can take a look at examples with templates though https://github.com/actix/examples/blob/master/template_askama/src/main.rs#L22-L33

What else would you like to see?

**Comment by kud1ing** [comment]
Hm, i guess some people will - like me - approach Actix-Web in the following order:

* print "hello world" as a `String` - everything is fine
* now they might adjust this so that the `String` contains HTML, which gives the unexpected behaviour.

I think it would have saved me some time if a "getting started" like document explained those two steps.

**Comment by DoumanAsh** [comment]
There is section [Getting Started](https://actix.rs/docs/getting-started/) in documentation, so if you think it could be improved, you can create PR

**Comment by kud1ing** [comment]
So you don't think this should be documented?

**Comment by fafhrd91** [comment]
PR is welcomed

**Comment by kud1ing** [comment]
Are there other means where you track possible documentation contributions?

**Comment by adrianheine** [comment]
I mean not even the handlebars example sets the right content-type …
