### ISSUE TITLE
Cannot disable signals from `server::new`

### ISSUE THREAD

**Issue by jordanmack** [actix/actix-web#374]
The disable_signals method does not appear to work from `server::new()`. It does work when using HttpServer::new(). 

```
extern crate actix_web;

use actix_web::{server, App, HttpRequest};
use std::time::Duration;
use std::thread;

fn main()
{
	thread::spawn(||
	{
		server::new(|| App::new().resource("/", |r| r.f(index)))
			.disable_signals()
			.bind("0.0.0.0:8000")
			.unwrap()
			.run();
	});

	loop
	{
		println!("Tick!");
		thread::sleep(Duration::from_millis(1000));
	}
}

fn index(_req: HttpRequest) -> &'static str
{
    "Hello world!"
}
```

**Comment by DoumanAsh** [comment]
This is definitely strange as it id just shortcut for `HttpServer::new()`,
Could you please clarify which version are you using?

**Comment by jordanmack** [comment]
@DoumanAsh Should be the newest version, `actix-web = "0.6.14"`.

Could it be related to the way the server was started in a thread using run()? Following the alternate method of using actix::System::new() with HttpServer::new() I did not experience the problem.

**Comment by DoumanAsh** [comment]
Ah... `HttpServer::run` actually enables signals back always https://github.com/actix/actix-web/blob/master/src/server/srv.rs#L482

@fafhrd91 Is there a reason we are overriding it it in `run`?

**Comment by fafhrd91** [comment]
I guess it is bug, we should fix it.
