### ISSUE TITLE
Add JS/CSS minification?

### ISSUE THREAD

**Issue by GuillaumeGomez** [actix/actix-web#378]
Hi,

I wrote [minifier-rs](https://github.com/guillaumeGomez/minifier-rs), a small crate to minify JS and CSS. It's currently being used in rustdoc and I'd like, if possible, to get more potential failure/issues feedbacks in order to improve it. Would it be possible to add it into your crate behind a feature so I could get some please?

Thanks in advance!

**Comment by DoumanAsh** [comment]
Currently we don't have any special feature that would involve around generating JS or CSS so I'm not sure how it would fit at all.

Minification seems to be more fit to template engines rather than `actix-web`, I'd say.

**Comment by fafhrd91** [comment]
Js/css minification is good candidate for third party library. If you’d like we can create repo in actix org

**Comment by hayd** [comment]
It would be useful if this came with reverse-routing feature, so minified assets routes can be labelled with their checksum as a suffix to their url (that way they can be aggressively cached) i.e. versioned assets.
