### ISSUE TITLE
Use JSON commands and POST instead of url encoded resources.

### ISSUE THREAD

**Issue by greenpdx** [actix/actix-web#379]
This is a feature enhancement.  This idea will make actix-web work better with Single PageWeb Apps.   Right now each resource is defined with a path

``` rust
    .resource("/hello", |r| r.f(index))
```
I really think the next evolution is web is using POST to send JSON commands to the server. The reason I say this is now the client can connect using websockets for bidirectional control. 
After the Client connects using websockets commands 

``` rust
    struct LoginArgs {
        user: String,
        passwd: String
     }

     // Later

    .command("hello",  |r| r.f(index))
    .command("who.login", LoginArgs, |r| r.f(login))
    .command("who.status", {}, |r| r.f(status))
```
while the function would look like 
``` rust
fn login(cmd: String, args: LoginArgs) -> impl JResponder {
    Ok(json!("Hello {}! passwd:{}", args.user, args.passwd)
}
```
Or something like that. 
It is just an idea.

**Comment by fafhrd91** [comment]
I think this is beyond scope of the project. But could be good third party library. We can make changes to actix-web api is it is not possible to make this router extension as third party library.

Thought?

**Comment by greenpdx** [comment]
My rust knowledge is not enough to create the library myself and I do not know how to hook in the library. Maybe with some guidance, I could make a simple library.
I like to concept of actix agents, but I only use web apps as the front end, so the routing is in the front end only. The server only supplies data. ( and maybe module or two). 
What would I have to do to create this library?

**Comment by fafhrd91** [comment]
i see this as follow:

1. create custom trait with `.command()` method
2. implement this trait for `Route` type
3. create custom handler for commands, (something similar to `With`)

**Comment by fafhrd91** [comment]
If you need help ask me in chat
