### ISSUE TITLE
Undefined behavior in implementation of HttpChannel

### ISSUE THREAD

**Issue by dtolnay** [actix/actix-web#385]
https://github.com/actix/actix-web/blob/82920e1ac1e6cdd12915fee127665625b7900378/src/server/channel.rs#L205-L206

This function takes two inputs, `self` of type `&Node<T>` and `next` of type `&Node<I>`.

The following lines cast both of these to `&mut Node<T>` and mutate their fields. This falls under the "Transmuting an & to &mut is UB" rule of the [Nomicon](https://doc.rust-lang.org/nomicon/transmutes.html).

> - Transmuting an & to &mut is *always* UB
> - No you can't do it
> - No you're not special

https://github.com/actix/actix-web/blob/82920e1ac1e6cdd12915fee127665625b7900378/src/server/channel.rs#L212-L217

---

Originally flagged by @Cocalus in [this thread](https://www.reddit.com/r/rust/comments/8wlkbe/actixweb_has_removed_all_unsound_use_of_unsafe_in/e1z2iiw/?context=1).

**Comment by fafhrd91** [comment]
removed transmute in 9aef34e
