### ISSUE TITLE
Is actix-web ready for production level web service?

### ISSUE THREAD

**Issue by kawpii** [actix/actix-web#386]
Recently I looked at Rust web frameworks, I came across [Rocket](https://rocket.rs/) but it is based on Rust nightly version. Then I came across [actix/actix-web](https://actix.rs) . It is really nice. But my question is : **Is actix-web ready for developing production level web service?**

**Comment by DoumanAsh** [comment]
This is a difficult question to ask as it is really depends on what you mean by production level.

As you can see currently we're still in pre 1.0.0 state and it is possible for incompatible changes to happen between 0.x.0 versions.
But we still follow semver and changelog is kept to notify users of all changes.

From web framework API perspective I do think it is mostly ready to provide you with all you need to successfully create good web server

And there are already cases when actix-web is used in the wild such as https://www.reddit.com/r/rust/comments/8xdsx5/rust_actixweb_in_the_on_of_the_biggest_music/

P.s. It is general question for Rust http://www.arewewebyet.org/

**Comment by OtaK** [comment]
In my opinion, it is production ready, but with potentially a few rough edges that will need to be solved along the way. If you're using it in production at your job, why not contributing back (as I'm trying to do), that way it'll get better and better!
