### ISSUE TITLE
"Module actix is private" error in client documentation

### ISSUE THREAD

**Issue by jorickert** [actix/actix-web#388]
Based on the [documentation](https://actix.rs/actix-web/actix_web/client/index.html) i used the following client code:
```
extern crate actix_web;
extern crate futures;
use futures::Future;
use actix_web::{actix, client};

fn main() {
    actix::run(
        || client::get("http://www.rust-lang.org")   // <- Create request builder
            .header("User-Agent", "Actix-web")
            .finish().unwrap()
            .send()                               // <- Send http request
            .map_err(|_| ())
            .and_then(|response| {                // <- server http response
                println!("Response: {:?}", response);
                Ok(())
            })
    );
}
```
I get the following error: 

> error[E0603]: module `actix` is private
 --> src/main.rs:4:17
  |
4 | use actix_web::{actix, client};
  |                 ^^^^^

How do i fix this?

**Comment by max-frai** [comment]
You should add `actix` into your cargo.toml and `extern crate actix`

**Comment by DoumanAsh** [comment]
This is development version documentation, so for this module to be public you need to use `master` branch

**Comment by jorickert** [comment]
Thanks for your help, looking at the right version of the documentation helped me
