### ISSUE TITLE
Undefined behavior in transmute of failure::Compat

### ISSUE THREAD

**Issue by seanmonstar** [actix/actix-web#389]
There is some unsafe code that transmutes a `failure::Compat` so as to reach into its private fields. This is very fragile, and can trigger UB if `failure::Compat` ever changes it's private fields: adding fields, or changing its field to something that isn't a `failure::Error`, will both result in treating invalid memory as the wrong type.

https://github.com/actix/actix-web/blob/696152f7635933c5d834551b207bf0e3c30f6baa/src/error.rs#L106-L111

**Comment by fafhrd91** [comment]
Is this UB or fragile code?

**Comment by fafhrd91** [comment]
@mitsuhiko could you add extra comment?

**Comment by fafhrd91** [comment]
This code will be removed after https://github.com/rust-lang-nursery/failure/pull/213

@seanmonstar could you be more precise in titles next time

**Comment by seanmonstar** [comment]
It technically works with the current exact versions, but to protect against UB, you'd need to pin to the patch version of failure. Any new release is allowed to change the layout. Actix-web could release a fix if it were changed, but all previous versions of actix-web couldn't be forced to not use the new code, resulting in UB.

The title was fine. The unsafety is still there, regardless of if waiting for a field to be made public in some possible new version of failure. Why allow the possibility of UB that you can't control?

**Comment by mitsuhiko** [comment]
@seanmonstar pinning failure is effectively going to break everything if failure makes a patch release, that seems not worth it. I rather get my patch into failure.
