### ISSUE TITLE
Is there a easy way to handle CORS/OPTIONS?

### ISSUE THREAD

**Issue by krircc** [actix/actix-web#39]

**Comment by fafhrd91** [comment]
What is OPTIONS? 

I have plans for cors support, but it is lower priority at the moment

**Comment by krircc** [comment]
I'M doing a person project. now it use vuejs, I also want to try yew(it's cool). so actix having a "native" built in support CORS would be grate. 
![..](https://raw.githubusercontent.com/krircc/nothing/master/imgs/2018-01-05%2009-24-33%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by fafhrd91** [comment]
I'll check what I can do.

**Comment by krircc** [comment]
@fafhrd91 thank you very much!

**Comment by fafhrd91** [comment]
@krircc could you explain how CORS/OPTIONS should work from your perspective?

**Comment by AlbanMinassian** [comment]
Hello

here tests around "cors" for nodesjs/express :

Some tests
- https://github.com/expressjs/cors/blob/master/test/test.js
- https://github.com/expressjs/cors/blob/master/test/example-app.js
- https://github.com/expressjs/cors/blob/master/test/issue-2.js
- https://github.com/expressjs/cors/blob/master/test

Info
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
- https://www.maxcdn.com/one/visual-glossary/cors/

**Comment by krircc** [comment]
@fafhrd91 my font-end code use vuejs. usually it use node sever in development at port 3000. my backend code use actix sever at port 8088. 
in vuejs : 
```vue
axios.get('http://localhost:8088/api/user_info', auth.getAuthHeader() )
```
but because CORS .web browsers sending a preflight OPTIONS request asking what resources it is allowed to access on the server, then after being given a resonse containing certain information in it's header a browser will send the actual GET/PUT/POST/etc query to the server, with no response it will not do this and cause Cross Site Scripting errors to be reported.
THERE is an issues in Rocker : [Lack of handling for CORS/OPTIONS](https://github.com/SergioBenitez/Rocket/issues/25)

**Comment by fafhrd91** [comment]
thanks, that is useful

**Comment by krircc** [comment]
@fafhrd91 
there is  also a good library for [rocket-cors](https://github.com/lawliet89/rocket_cors)
I don't  know Is it helpful? I'm a noder. actix is more faster than node frameworks.

**Comment by fafhrd91** [comment]
I added basic preflight support,

does anyone wants to do more work on cars support? otherwise I will complete it later this week

**Comment by krircc** [comment]
@fafhrd91 awesome! more and more projects use restful api , even grphaql sever let font-end and backend separation , It's friend for many clients  application, now actix-web is the first rust framework friendly support It 🥇 .

**Comment by fafhrd91** [comment]
I think cors support is completed.

@krircc could you test it on your project? also could you maybe add user guide section related to CORS/OPTIONS

**Comment by krircc** [comment]
@fafhrd91 ok Iwill write a blog in actix website.
