### ISSUE TITLE
Cookie parser fails for certain characters

### ISSUE THREAD

**Issue by kamek-pf** [actix/actix-web#392]
Hey,

I noticed some cookies always appear as `None` in `req.session()` (despite being in the Cookie header),  depending on what characters are being used apparently.
Quick example :

```rust
let payload = "hello";

let value = req.session().get::<String>("test");
println!("Value found in headers : {:?}", value); // Ok(Some("hello"))

let res = req.session().set("test", payload);
println!("Set result : {:?}", res); // Ok(())

// send response
```
Run this a couple times and everything works as expected.
Header looks like this :
```
actix-session=zsf1hIJu4CLUesyWHTQ/pedxPET4eqHjO5AQpvOawMU={"test":"\"hello\""}
```

Now if I change the payload, this is what happens :
```rust
let payload = "FJc%26continue_url%3Dhttp%253A%252F%252Fconnectivitycheck.gstatic.com%252Fgenerate_204"

let value = req.session().get::<String>("test"); 
println!("Value found in headers : {:?}", value); // Ok(None)

let res = req.session().set("test", payload);
println!("Set result : {:?}", res); // Ok(())
```
Header looks like this :
```
actix-session=dQxdyG08q5mLMu0Q6KAysLEtYbM/Uak/neM5L3QDj0Y={"test":"\"FJc%26continue_url%3Dhttp%253A%252F%252Fconnectivitycheck.gstatic.com%252Fgenerate_204\""}
```
It seems like the session middleware never picks up this value for some reason.
I assume this is an encoding issue. This happened while storing a URL, my current workaround is to base64 encode the payload and everything works fine.

Any idea what could be causing this ?

**Comment by DoumanAsh** [comment]
Just to clarify is the second example fully percent encoded url?

And the second, can you please make short and fully functional example of your problem?

**Comment by kamek-pf** [comment]
Yes, the url is percent encoded.
I sent a pull request with a test case based on what you did @DoumanAsh.
Thank you btw, I wasn't sure how to write a test for this, your sample helped a lot.

See comment in #395.

**Comment by DoumanAsh** [comment]
@kamek-pf Can you please check your use case with my branch https://github.com/DoumanAsh/actix-web/tree/session_special_chars

Note that you should not percent encode yourself and instead leave it actix

Updated test case https://github.com/actix/actix-web/pull/393/files#diff-48d46aa5fa3906ed3a97ad3e4e6ab7dcR1005

**Comment by kamek-pf** [comment]
I'll take a look later today.
In my case I'm not percent encoding things myself (I just take what I get from another service, which is a URL, with another URL in the query string, don't ask).

So if we go that route we may have to mention somewhere in the docs that some characters are forbidden.

**Comment by kamek-pf** [comment]
@DoumanAsh I feel like we're working around the problem rather than addressing it here.

With your proposed fix, if someone attempts to put some invalid characters in the store (either by inadvertence or simply because they might be unaware of the consequences), then we're back to square one :p

The way I see it, we can do one of the following things :
- Keep things as they were, and document the fact that some characters might cause unexpected behavior
- base64 encode the whole session :
```
actix-session=UniqueKeyHere={"base":"64","encode":"this"}
                            ^ base64 encode this ------ ^
```

Option 2 should be pretty straightforward to implement (decode the session payload when a request arrives, encode it before sending the response) and would effectively prevent this sort of things to happen again.
Although this should be transparent to most users, it might be considered a breaking change.
What do you think of this solution ?

**Comment by DoumanAsh** [comment]
Well, it is not like I intentionally working around the problem, there was already percent encoding partly builtin, I just made sure that we do it always.

I do prefer to keep things simple, but since we already were doing percent encoding on some stepts, I think it would be better to keep just everywhere(I added comment btw about possibility of problems with symbols)

P.s. I certainly don't feel that we should encode using base64 the whole session for this particular scenario.
It is better to be left to user.
Though the same could be said about percent encoding I guess

P.s.s Potential reason for percent encoding though maybe the fact that browsers are not very well consisted in how they treat non-ASCII characters in cookies.

**Comment by DoumanAsh** [comment]
@kamek-pf To summarize I believe we should only percent encode as non-ASCII characters may cause troubles when working with some browsers, but I don't think we should take extra measures for special symbols and rely on `cookie` crate itself.

**Comment by fafhrd91** [comment]
@DoumanAsh what is the status?

**Comment by DoumanAsh** [comment]
@fafhrd91 Well, we aligned percent encoding for non-ASCII characters, but I didn't look into treatment of special characters in `cookie` crate itself.
We also have mention that we rely on that crate and improper special characters may cause issue...

So I'm not sure should we try to look into why `cookie` may fail on some characters or not.

**Comment by fafhrd91** [comment]
when we load cookies do we get error from cookie crate?

**Comment by fafhrd91** [comment]
can we print error message if we can not load/store cookies?

**Comment by DoumanAsh** [comment]
No, we just add cookie to jar and that's it, there is no mechanism for error detection when attempting to put original cookie from header to jar.
We only capable to detect error when attempting to parse with `serde_json` result of cookie value in jar, if we get the cookie.

**Comment by fafhrd91** [comment]
@DoumanAsh did you check https://github.com/actix/actix-web/blob/master/src/uri.rs#L64
we can use it for custom encoder

**Comment by DoumanAsh** [comment]
No, I haven't I could look into it. We could use it instead of `percent-encode` feature of cookie crate I guess?

**Comment by ghost** [comment]
Both cookies shown in the first post are invalid, as you can't have backslashes in cookie values:

https://tools.ietf.org/html/rfc6265#section-4.1.1
https://tools.ietf.org/html/rfc2616#section-2.2
```
   cookie-header = "Cookie:" OWS cookie-string OWS
   cookie-string = cookie-pair *( ";" SP cookie-pair )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
       CTL            = <any US-ASCII control character
                        (octets 0 - 31) and DEL (127)>
```

Either they should either be magically percent-encoded, or refused by cookie-rs

**Comment by fafhrd91** [comment]
i need test case. at the moment we use percent encoding at both sides
