### ISSUE TITLE
Simplification of multipart handling

### ISSUE THREAD

**Issue by mqudsi** [actix/actix-web#398]
Hello all,

I was attempting to figure out how to add `.limit()` to either multipart requests (the whole thing) or multipart fields (length between boundaries) and figured I'd try to add `impl HttpMessage for Field<S>` to the code, which would give me a free implementation of that and other nice features such as decoding a json multipart field to a type directly, etc.

It seems this is not possible since `impl HttpMessage` requires `.payload() -> Self::Stream` whereas a `Field` struct does not own its `Stream` and can only ultimately obtain a mutable reference to in the form of `PayloadHelper::get_mut()`.

Is there a reason that multipart forms are implemented as their own types rather than just being a special case of `HttpMessage` when content-type is `multipart/form-data`?

**Comment by DoumanAsh** [comment]
@mqudsi Well, it is similar to `JsonBody` and friends I guess

**Comment by mqudsi** [comment]
But the difference is that `JsonBody` is applied against the top-level `HttpMessage`, meaning you can first operate against `HttpMessage` and then retrieve the `JsonBody` object and operate against that.

In the case of multipart messages though, first the multipart message must be obtained _then_ you have the equivalent of an `HttpMessage` that you would want to carry out operations against (but can't).

Each field in the stream of fields within the multipart streams is a potential `HttpMessage` but you don't have any opportunity to treat it as such. For example, decode it as JSON, set a limit on its length, etc. which are all only available for the top-level `HttpRequest` as a `HttpMessage`, but they would be undefined/invalid in that context since the incoming stream is strictly `multipart/form-data`.

I hope that makes sense?

**Comment by DoumanAsh** [comment]
Ah no what I mean is the way struct made resemble `JsonBody` but not necessary identical.

I guess maybe we should access to the whole `HttpMessage` rather than just stream.
Currently it seems to just operate on the whole stream to read and parse it all, I don't think you can split stream without storing it buffer (you can keep references though, which is done currently I think).

I think it should be possible to implement limit on the whole `Multipart` similar to how it is done with `JsonBody` but the difference is that multipart itself is not just single message, but rather multiple items so that may be the reason why there is no limit in first place.
I mean there is no sense in a overall limit, right?
Rather it would make sense the size of individual item.
Maybe the potential `.limit` should limit how big particular Item can get?
If it is too big, then stream should return error.

**Comment by fafhrd91** [comment]
I like idea of implementing `HttpMessage` for individual fields. it should be possible.

**Comment by mqudsi** [comment]
For some background, I'm working on a file upload API. From what I've seen, traditionally this is done in API form by any of these approaches:
* `application/x-www-form-urlencoded` or `application/json` encoded request that includes metadata and file content side-by-side (incurring a heavy toll in encoding overhead for the file content),
* HTTP headers for metadata (`X-Filename`, `X-Hash`, etc.) and raw file content in the body, with `Content-Type` either derived from the actual file being uploaded or set to a generic `application/octet-stream`,
* Metadata encoded in a single HTTP header, such as `X-File-Info` in JSON or similar form, and raw file content in the body of the request as in the previous case,
* Two separate API calls, the first of which `POST`s the metadata to the server encoded in the body of the request and the second either `POST` or `PUT`s the file content to a URL including a token returned by the server in the initial call,

I wanted to avoid the encoding overhead of the first approach, avoid the untyped pitfalls of the second/third methods, and avoid the latency and state requirements of the final method, so I used `multipart/form-data` to combine the "best" qualities of the above, allowing a single connection to include both metadata and raw, unencoded binary payload with the first half submitted as a JSON-encoded field - which is pretty much why mulitpart forms were invented in the first place. `HttpMessage` for `Field` would let me call `.json()` on the first payload then `.limit()` on the second.

*It occurs to me that there is one possible caveat here that might make this a no-go, I don't know if most clients (such as actix' own) allow the transmission of payload data for a mulitpart field before the entirety of its contents are known, given the requirement that the boundary be pre-determined and cannot appear in the body of the multipart field. If the boundary length is sufficient, the odds of a randomly-chosen boundary being found in the payload content are probably worth acting under the assumption that it won't clash, but I wonder....)*

---

As to the details of implementing `HttpMessage`, given the necessarily sequential nature of the multipart fields (and HTTP requests in general), presumably the easiest approach would be for each `Stream` of `Field` to be composed of a tuple `(backbuffer, &mut request_stream)` buffering only the `n` bytes needed to determine if the multipart boundary has been reached. If the buffer is big enough (to prevent byte-by-byte streaming), the backbuffer would be used to store excess data belonging to the next field that was "accidentally" read from the stream, ownership of which would be transferred to the next field in the multipart stream. If the underlying request stream has its own stream at least n bytes long and supports seeking or peeking this can be avoided entirely (I haven't dug into `HttpRequest`'s `impl Stream` to check).

**Comment by fafhrd91** [comment]
should be easier now with async/await

**Comment by mqudsi** [comment]
This wasn't an issue about the ergonomics of futures, but rather the lack of `HttpMessage` for multipart form data.
