### ISSUE TITLE
Proposal: Logo

### ISSUE THREAD

**Issue by krircc** [actix/actix-web#40]
I think a beautigul Logo is missing for the project.
so i make one and 3 colors.
![](https://raw.githubusercontent.com/krircc/nothing/master/imgs/ACTIX-ZERO-5.png)
![](https://raw.githubusercontent.com/krircc/nothing/master/imgs/ACTIX-ZERO-4.png)
![](https://raw.githubusercontent.com/krircc/nothing/master/imgs/ACTIX-ZERO-2.png)

**Comment by fafhrd91** [comment]
cool. I like black one. could you make it more black

**Comment by krircc** [comment]
@fafhrd91 thanks this one let corlor more Consistent.
![..](https://raw.githubusercontent.com/something-here/nothing/master/imgs/ACTIX.png)
