### ISSUE TITLE
Option to disable Content-Disposition for StaticFiles

### ISSUE THREAD

**Issue by Flakebi** [actix/actix-web#401]
Hi,
actix is really working well for a small website I built, thanks for that!

I noticed a change in `StaticFiles` starting with 0.6. It seems like `Content-Disposition: attachment; filename=<filename>` was added to the headers.
Unfortunately this does not work well in conjunction with `<object data="filename.pdf" type="application/pdf">` tags.
Firefox reacts like the file would not exist, chrome shows a "failed to load pdf document" error.
(Also see [this stackoverflow question](https://stackoverflow.com/questions/26611123/pdf-doesnt-load-in-a-object-tag))

It would be nice to have an option to switch this header off for `StaticFiles`.

**Comment by DoumanAsh** [comment]
Hm... Now I think about it, maybe we need to provide a way for user to specify mapping of mime type to what type of content disposition it would have.

Though option to disable sounds reasonable I guess.

**Comment by DoumanAsh** [comment]
JFYI: We added generic [configuration](https://actix.rs/actix-web/actix_web/fs/trait.StaticFileConfig.html) for file services so now you can customize it all through static methods as trait parameter to `NamedFiles` and/or `StaticFiles`
