### ISSUE TITLE
Consider implementing Fail trait for actix_web::error::Error 

### ISSUE THREAD

**Issue by cpick** [actix/actix-web#407]
I may be missing something obvious, but I'm having a hard time adding `failure::Context` to an `actix_web::error::Error`.

I'd like to do the following:
`Path::<String>::extract(&request).context("failed to extract path")`
but it fails because  `actix_web::error::Error` does not implement `Fail` or `std::error::Error`.

Additionally, `Error::as_fail` returns a reference so `Fail::context()` can't be called on it either.

I think it might be reasonable to just have `actix_web::error::Error` implement `Fail` directly?

**Comment by fafhrd91** [comment]
Fail requires `Sync + Send`, actix-web doesn’t provide those in general. Also I think there would be ergonomics problems. We can add context though

**Comment by fafhrd91** [comment]
pr is welcome, but I am not sure this is possible
