### ISSUE TITLE
default_resource take panick at 'not yet implemented' src/handler.rs:412:9

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#410]
Hi,
When I'm using default_resource on git version, rustc shows [`not yet implemented`](https://github.com/actix/actix-web/blob/master/src/handler.rs#L412) , when I will remove this method, Actix could not able to pass resources and it will show 404 error.

<img width="1132" alt="screen shot 2018-07-21 at 2 26 05 pm" src="https://user-images.githubusercontent.com/39458402/43034470-3cf623ae-8cf2-11e8-98f0-9c3462299c72.png">

**Comment by fafhrd91** [comment]
could you post full backtrace

**Comment by fafhrd91** [comment]
and code snippet

**Comment by fafhrd91** [comment]
fixed in master
