### ISSUE TITLE
filter multiple perd with or statements.

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#411]
This is part of my code
```
            .resource("/api", |r| {
                r.route()
                    .filter(pred::Post())
                    .filter(pred::Header("Content-Type", "application/json; charset=utf-8"))
                    .f(api)
            })
```

is it possible filter multiple kind of pred with or statement ?
for example if want filter both of "application/json; charset=utf-8" or "application/json" is possible ?

**Comment by fafhrd91** [comment]
https://actix.rs/actix-web/actix_web/pred/fn.Any.html

you should ask questions in chat
