### ISSUE TITLE
SystemService not Implemented for ClientConnector

### ISSUE THREAD

**Issue by rodoyle** [actix/actix-web#417]
I'm trying to use the Actix Web HTTP client as part of a larger Actix data processing pipeline. The Rust compiler complains the that SystemService is not implemented for ClientConnector despite an implementation being immediately apparent in actix_web::client::connector. I've been struggling with this error as I think I simply need to bring the implementation into scope. The documented examples only really cover the case where one wants to make a minimal HTTP request and run this directly or immediately pass the ClientResponse back as an HttpMessage (as in the proxy server example). 

This is with Rust 1.29 nightly. I'm using actix_web 0.6.15 (which uses actix 0.5.8) with actix 0.7.0 so I suspect this could be the issue. Is there some sort of incompatibility here to be aware of?

**Comment by fafhrd91** [comment]
actix_web 0.6 requires actix 0.5, actix_web 0.7 requires actix 0.7
you can not use actix 0.7 with actix_web 0.6

**Comment by fafhrd91** [comment]
this is rust feature.

**Comment by rodoyle** [comment]
That worked great. I just had to manually pin the versions so Cargo would install the compatible set.  Thank you!
