### ISSUE TITLE
Doc - features list seems to be outdated: flate-rust / flate-c -> flate2

### ISSUE THREAD

**Issue by neowutran** [actix/actix-web#423]
Hi,
It seems that in the code "flate-rust" & "flate-c" feature have been replaced by "flate2"
https://github.com/actix/actix-web/blob/master/src/lib.rs#L129

but in the doc, "flate-rust" & "flate-c" are still referenced
https://github.com/actix/actix-web/blob/master/src/lib.rs#L73

**Comment by DoumanAsh** [comment]
Just to clarify it is actually https://github.com/actix/actix-web/blob/master/Cargo.toml#L46-L50

But we need to update docs to reflect on it

**Comment by fafhrd91** [comment]
It is in api docs https://github.com/actix/actix-web/blob/master/src/lib.rs#L64

**Comment by DoumanAsh** [comment]
@fafhrd91 but feature names are `flate2-*`, no? 
In docs it is just `flate-*`

**Comment by fafhrd91** [comment]
I see, I'll fix it

**Comment by DoumanAsh** [comment]
Ah don't worry over this. I corrected feature names https://github.com/actix/actix-web/commit/6048817ba74f5a916bff72c17ec220656ea49c80

I'd prefer we'd use just `flate-*` though but it wouldn't be good idea as it would break stuff for anyone with non default features.

Maybe we could align it with `brotli` on next major release though...
