### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by blueway** [actix/actix-web#425]
error: multiple packages link to native library `ring-asm`, but a native library can be linked only once

package `ring v0.13.2`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `actix-web v0.7.2`

package `ring v0.12.1`
    ... which is depended on by `jsonwebtoken v4.0.1`

**Comment by DoumanAsh** [comment]
Well `actix-web` doesn't have `jsonwebtoken` as dependency so it is not an issue of `actix-web`

The upgraded `ring` package provides a fixed comilation for msvc and fixes for some security issues.
So we are not planning to downgrade it.
I would suggest for `jsonwebtoken` to upgrade its ring dependency and for now to pin `actix-web` to 0.7.1 if you want to avoid compiling multiple ring deps

**Comment by DoumanAsh** [comment]
@blueway Looking at `jsonwebtoken` https://github.com/Keats/jsonwebtoken/blob/master/Cargo.toml#L17 it is already upgraded for use with new ring.

I would suggest to try to use it as git dependency

**Comment by blueway** [comment]
ok,I got it ,thanks

**Comment by fafhrd91** [comment]
merging cookie 0.11 to a 0.7 was a mistake

**Comment by DoumanAsh** [comment]
@fafhrd91 Well maybe, I actually forgot that ring only recently fixed the problem of using multiple `ring` dependencies
