### ISSUE TITLE
Cannot set host header

### ISSUE THREAD

**Issue by shakyShane** [actix/actix-web#428]
trying to set the "host" header on a client request (using the builder) gives unexpected results.

```rust
client::ClientRequest::get(format!("http://{}", addr).as_str())
    .header(header::HOST, "example.com")
    .finish()
    ...
```

the receiver of this request sees:

```json
{
    "host": "127.0.0.1",
    "host": "example.com",
    "accept-encoding": "gzip, deflate",
    "user-agent": "Actix-web/0.7.2",
    "date": "Mon, 30 Jul 2018 08:29:50 GMT"
}
```

So, my question is: should there be a check [here](https://github.com/actix/actix-web/blob/master/src/client/request.rs#L294-L300) for an existing header with the name "host" - or is there a better way to acheive this.

Context: trying to build a transparent proxy, a bit like Caddy's https://caddyserver.com/docs/proxy

Would it make more sense to create a new request struct manually, or do you think the behaviour above should be altered?

Thanks for your time :)

**Comment by DoumanAsh** [comment]
~~I think we should have option to override header in builder.~~

As workaround you can access `HeadersMap` directly and update header using `HeadersMap::insert` https://actix.rs/actix-web/actix_web/client/struct.ClientRequest.html#method.headers_mut

**UPD:**
You can also use https://actix.rs/actix-web/actix_web/client/struct.ClientRequestBuilder.html#method.set_header 

And `uri` setter uses it too.

**Comment by shakyShane** [comment]
ahh, thanks! `.set_header()` worked perfectly. No need for any changes then I guess :)
