### ISSUE TITLE
HttpRequest::url_for is not working well with scopes

### ISSUE THREAD

**Issue by Kroisse** [actix/actix-web#429]
Reproducible example:

```rs
extern crate actix_web;

use actix_web::*;
use actix_web::test::TestServer;

fn get_url(req: &HttpRequest) -> impl Responder {
    let a = req.url_for_static("a").unwrap();  // case1 fails here
    let b = req.url_for_static("b1").unwrap();  // case2 fails here
    format!("{}, {}", a, b)
}

fn create_server() -> TestServer {
    // note: TestApp didn't provide .scope()
    TestServer::with_factory(|| App::new()
        .resource("/a", |r| {
            r.name("a");
            r.get().f(|_| HttpResponse::Ok());
        })
        .scope("/b", |scope| {
            scope
                .resource("/1", |r| {
                    r.name("b1");
                    r.get().f(|_| HttpResponse::Ok());
                })
                .resource("/2", |r| { r.get().f(get_url) })
        })
        .resource("/c", |r| { r.get().f(get_url) })
    )
}

#[test]
fn case1() {
    let mut srv = create_server();
    let req = srv.client(http::Method::GET, "/b/2").finish().unwrap();
    let res = srv.execute(req.send()).unwrap();
    assert!(res.status().is_success());
}

#[test]
fn case2() {
    let mut srv = create_server();
    let req = srv.client(http::Method::GET, "/c").finish().unwrap();
    let res = srv.execute(req.send()).unwrap();
    assert!(res.status().is_success());
}
```

**Comment by DoumanAsh** [comment]
Just to clarfiy by fail, you mean that it returns `Err`?

**Comment by fafhrd91** [comment]
fixed in master

**Comment by gnunicorn** [comment]
@fafhrd91 it appears your change broken non-scoped behavior though. adding a `println!("{}, {}", a, b);` to the end of `get_url` prints me:

```
http://localhost/b/a, http://localhost/b/1
http://localhost/a, http://localhost/b/1
```

With the first entry being clearly scoped though the URL found is not under that scope.

[You can find a currently failing test for it here](https://github.com/gnunicorn/actix-web/commit/97b6a029d5bb17846062e4fd62e17dff881c6286).

**Comment by fafhrd91** [comment]
@gnunicorn prefix is dynamic property of the router. you can not get non prefixed route if prefix is set.

**Comment by gnunicorn** [comment]
@fafhrd91 I can't follow. Are you saying [I changed the test incorrectly](https://github.com/gnunicorn/actix-web/commit/97b6a029d5bb17846062e4fd62e17dff881c6286) or that `/b/a` (an _invalid_ URL) is the expected result?

Neither makes sense to me. If I define a `named` URL in the `router` and I asked `url_for`  for it, should it not return _that_ URL (which is the only method there is to get URLS)? From within the handler code (or later template) I do not know, _nor care_ whether the URL match this was called from is prefixed or scoped or whatnot... This would totally break expectations...

**Comment by fafhrd91** [comment]
What I am saying, you can not set prefix for router and expect to get url without prefix. Prefix is set for all routes in router.

**Comment by gnunicorn** [comment]
I see. so I changed my test wrong. Thanks for explaining, @fafhrd91 !

Follow up question (because that is the issue I have) is the same to be expected for `.scope`'d-URLs? Like from within the `scope`-d-Handler, doing `url_for` to a non-scoped url leads to errors. Should I open an issue about this?

**Comment by fafhrd91** [comment]
Yes, create ticket for second problem
