### ISSUE TITLE
It'time to build a beautiful office website for actix.

### ISSUE THREAD

**Issue by krircc** [actix/actix-web#43]
can we start a new repository for this? I have time to do it!
let more people try actix.

**Comment by fafhrd91** [comment]
Sure, I changed org permissions, you should be able to create new repos

Btw did you check #32?

**Comment by krircc** [comment]
@fafhrd91 ok. that is beautiful,sorry i don't notice but we should do it in rust. I will use cobalt.rs build a all featuresns Responsive webside(not one page), and synchronization the conent from that.

**Comment by krircc** [comment]
@fafhrd91 The website is there now, but need you add more conents. It use [cobalt](http://cobalt-org.github.io/) and my custom theme [beautiful](https://github.com/krircc/beautiful).
 it's just begin ! we can Adjustment  the website make it more beautiful later.

**Comment by fafhrd91** [comment]
Could you make site less colorful, it is too yellow and purple

**Comment by fafhrd91** [comment]
let's use black-gray-white color scheme for right now. we can add colors later. right now, it looks slightly unprofessional

**Comment by krircc** [comment]
@fafhrd91 ok, you are right,let's do it. oh sorry it has permissions i don't know. now you have write permissions for the two repository.

**Comment by krircc** [comment]
IT's done.

**Comment by fafhrd91** [comment]
thank!
