### ISSUE TITLE
9-10 second builds for the README example

### ISSUE THREAD

**Issue by chinedufn** [actix/actix-web#430]
Hey!

Thanks a lot for writing a framework with such easy to grab examples!

I'm new to Rust web servers so exploring around to get the lay of the land. 

Actix's API caught my eye and feels like what I want to explore as a recommended (but not required) server for [Percy](https://github.com/chinedufn/percy).

The problem that I'm facing is that a clean build of the [example in the README](https://github.com/actix/actix-web#example) takes ~10 seconds. 

As a noob, I have absolutely no idea if that is normal or not.

```
$ time cargo build -p server-www
   Compiling server-www v0.1.0 (~~REDACTED~~)
    Finished dev [unoptimized + debuginfo] target(s) in 8.72s

real    0m8.787s
user    0m12.040s
sys     0m2.300s
```

```
$ cargo -V
cargo 1.29.0-nightly (506eea76e 2018-07-17)
$ rustc -V
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```

![image](https://user-images.githubusercontent.com/2099811/43462325-cf455776-94a3-11e8-93da-f68d7d944384.png)

I tried searching the issues for any related discussions, but I don't see any.

If this is normal - cool!! - just making sure that I'm not making a mistake!

Thank you!

**Comment by DoumanAsh** [comment]
Well, Rust is popular for its build timings... So it is more or less normal I guess and depends on your machine
