### ISSUE TITLE
No way to specify a socket URI for TestServer.ws()

### ISSUE THREAD

**Issue by jrconlin** [actix/actix-web#432]
It appears that in `test.rs`:

```rust 
pub fn ws(
        &mut self,
    ) -> Result<(ws::ClientReader, ws::ClientWriter), ws::ClientError> {
        let url = self.url("/");
        self.rt
            .block_on(ws::Client::with_connector(url, self.conn.clone()).connect())
}
```
`url` is hard set to "/". 
I have several entry points for websockets for my app, and I would like to be able to specify the path. The app allows for this, but unfortunately, testing does not.

I'm not sure what the preferred approach might be, possibly a second fn that takes a path string?

Thanks!

**Comment by fafhrd91** [comment]
we need new method for custom url. would you provide PR?

**Comment by jrconlin** [comment]
Sure, I can try.
