### ISSUE TITLE
cause() is not implemented for InternalError's Fail trait

### ISSUE THREAD

**Issue by mitskevich** [actix/actix-web#443]
As I understand, the best approach to throwing errors in `actix-web` handlers currently is something like this (simplified code):

```rust
fn authenticate_handler(req: &HttpRequest) -> Result<Json<AuthResult>, actix_web::Error> {
    let auth_data = get_auth_data_from_request(req).map_err(ErrorBadRequest)?;
    authenticate_or_fail(auth_data).map_err(ErrorUnauthorized)
}
```

Here I have two functions `get_auth_data_from_request` and `authenticate_or_fail` that return some `Result` with either correct data or my internal errors implementing `Fail` trait. Those errors get mapped into `InternalError` with helper functions `ErrorBadRequest` and `ErrorUnauthorized` which basically attach status code information to the resulting response.

The problem arise when I'm trying to output the error in the log (or in the email report, etc.). I want to display error with full cause chain, so I'm doing something like this in my error handler middleware (again, simplified):

```rust
impl<S> aw::middleware::Middleware<S> for MyErrorDisplayMiddleware {
    fn response(
        &self,
        req: &aw::HttpRequest<S>,
        mut resp: aw::HttpResponse,
    ) -> Result<aw::middleware::Response, aw::Error> {
        if let Some(err) = resp.error() {
            let err_str = format_fail(err.as_fail());
            warn!("API error for {}: {}", req.uri(), err_str);
        }
        Ok(aw::middleware::Response::Done(resp))
    }
}
```

Where `format_fail` is my function that displays any `Fail` error looping by `.cause()` calls. 

Doing that I have found that `Fail` implementation for `InternalError` doesn't contain `cause()` implementation. 

https://github.com/actix/actix-web/blob/e61ef7dee4a4e1017372783594b6f6bda6dc6f5c/src/error.rs#L685-L692

This means I can only display the top error in the chain. Was this done on purpose and is there any simple workaround for that issue? The only way I can think of now is to not use `InternalError` (and all helpers) at all, and use my own implementation instead...

**Comment by fafhrd91** [comment]
Could you submit Pr with cause impl?

**Comment by mitskevich** [comment]
Closing because there is no way to implement `.cause()` without changing public API (see PR).
