### ISSUE TITLE
SyncArbiter future execution hangs in tests

### ISSUE THREAD

**Issue by jtescher** [actix/actix-web#445]
I could be misunderstanding how arbiters must be started in tests, but when I try to send a message to an actor that was started in a test context the handler for the message never gets called and the future blocks forever.

I created a repo with a simple reproduction of the issue here: https://github.com/OutThereLabs/actix-web-test-bug-example/blob/master/src/main.rs

The simplest example seems to be something along the lines of: 
```rust
    ...
  
    #[test]
    fn it_should_not_hang() {
        let mut srv = test::TestServer::with_factory(create_app);

        // Starting a SyncArbiter and executing a future cause the tests to hang.
        let example_utility = &SyncArbiter::start(3, || TestUtilityActorExample {});
        let fut = example_utility.send(TestMessageExample {});
        srv.execute(fut).expect("Test utility method result");
        // If you comment the above 3 lines out, the tests pass like normal.

        let request = srv.client(http::Method::GET, "/").finish().unwrap();
        let response = srv.execute(request.send()).unwrap();

        assert!(response.status().is_success());
    }
```

This worked in older versions of actix/actix-web, if you revert this to `actix = "0.5.8"` and
`actix-web = "0.6.15"`,  the tests pass (shown on [this branch](https://github.com/OutThereLabs/actix-web-test-bug-example/tree/older-version))

**Comment by fafhrd91** [comment]
you have to create SyncArbiter inside test server factory (create_app)

**Comment by jtescher** [comment]
Ah thanks, is there a way to get test utilities that you don’t want in create app initialized? Was convenient that this worked in the previous versions

**Comment by fafhrd91** [comment]
you can start SyncActor in separate thread.

**Comment by jtescher** [comment]
Ah! I understand now. Thanks for the help, this is a really great project.

For anyone who needs a similar solution, something like this will work for you:

```rust
thread::spawn(move || {
    let mut system = System::new("test-utility");
    let example_utility = &SyncArbiter::start(3, || TestUtilityActorExample {});
    let fut = example_utility.send(TestMessageExample {});
    system.block_on(fut).expect("Test utility response")
}).join();
```
