### ISSUE TITLE
Setting several cookies at once

### ISSUE THREAD

**Issue by s-panferov** [actix/actix-web#446]
Hello, it seams that setting several cookies at once is not possible. My code:

```rust
HttpResponse::build(StatusCode::TEMPORARY_REDIRECT)
        .header(header::LOCATION, format!("https://{}", return_domain))
        .cookie(id_cookie)
        .cookie(access_cookie)
        .cookie(refresh_cookie)
```

It looks like it adds them all to the JAR, but them it just cannot set multiple `Set-Cookie` headers and I always get only one cookie.

**Comment by fafhrd91** [comment]
@DoumanAsh could you check?

**Comment by DoumanAsh** [comment]
Looking at how it is implemented:

```rust
    /// Set a body and generate `HttpResponse`.
    ///
    /// `HttpResponseBuilder` can not be used after this call.
    pub fn body<B: Into<Body>>(&mut self, body: B) -> HttpResponse {
        if let Some(e) = self.err.take() {
            return Error::from(e).into();
        }
        let mut response = self.response.take().expect("cannot reuse response builder");
        if let Some(ref jar) = self.cookies {
            for cookie in jar.delta() {
                match HeaderValue::from_str(&cookie.to_string()) {
                    Ok(val) => response.headers.append(header::SET_COOKIE, val),
                    Err(e) => return Error::from(e).into(),
                };
            }
        }
        response.body = body.into();
        HttpResponse(response, self.pool)
    }
```

Yeah we certainly set multiple headers rather than setting all cookies into one header

**Comment by DoumanAsh** [comment]
@s-panferov Ah... btw, did you examine how many `Set-Cookie` headers present in your response?

Each cookie should be sent in a separate `Set-Cookie` header with current implementation

**Comment by s-panferov** [comment]
@DoumanAsh I have only one Set-Cookie header, but should have three of them.

**Comment by DoumanAsh** [comment]
Hmm I'll try to write test case to check it out

**Comment by DoumanAsh** [comment]
@s-panferov Could you please share what cookies exactly you set?

I made test to simulate your case https://github.com/actix/actix-web/pull/447/commits/376ec9ef9f57440bc9b08ca00f44d9b6264c86dd#diff-801c536aa2036d5b9fe161179c380c82R966

I set 3 headers, but two of them has the same key so only 2 gets inserted and therefore there are two `Set-Cookie`

You could also try to setup middleware and log all `Set-Cookie` headers your response have

**Comment by s-panferov** [comment]
I'll try to create a reproduction repo for this

**Comment by s-panferov** [comment]
@DoumanAsh could you please take a look? https://github.com/s-panferov/actix-cookie

This app has two routes: '/' and '/u/auth'. Please go to `/u/auth` in your browser and see that it sets only one cookie header.

**Comment by s-panferov** [comment]
Maybe it is somehow connected with the encryption (it seems to work when I remove `rustls`). But nowadays you just cannot live in internet without `https`, so...

**Comment by DoumanAsh** [comment]
@s-panferov No, it should not be different for `https`, afaik standard says that all `Set-Cookie` must be set, unless you have several with the same key(in which case only latest must take effect so only latest would be present in actual headers)

I'll check out your example.

That's really strange, but in your example with HTTPs it doesn't set all `Set-Cookie` for some reason.
I'll need to check it out

Also it seems to be related to HTTP2, rather than TLS itself.
You can set `no_http2()` for now to make it work, I'll need to take a look how we write headers in case of HTTP2

**Comment by fafhrd91** [comment]
fixed in master

**Comment by s-panferov** [comment]
@fafhrd91 thanks. Could you please release a patch version?

**Comment by fafhrd91** [comment]
I need to fix one bug, but will release new version in couple or days

**Comment by marthvon** [comment]
Hahaha, same issue 2025 lol...
```
token1=....=; HttpOnly; SameSite=Strict; Secure; Path=/; Domain=localhost; Expires=Mon, 04 Aug 2025 12:24:12 GMTtoken2=....=; SameSite=Strict; Secure; Path=/; Domain=localhost; Expires=Mon, 04 Aug 2025 12:24:12 GMT
```
**GMTtoken2=**
doesn't seem, right?

**Comment by robjtede** [comment]
please open a new issue your problem
