### ISSUE TITLE
Host header does not comply with RFC2616

### ISSUE THREAD

**Issue by Paradyx** [actix/actix-web#448]
Sending a request to a host on a port other then 80 should change the `host` header according to [RFC2616 14.23 Host](https://www.ietf.org/rfc/rfc2616.txt)
i.e.: Connecting to localhost:8081 should write the header `host: localhost:8081` and not `host: localhost`

**Comment by DoumanAsh** [comment]
Isn't port optional though?

**Comment by Paradyx** [comment]
RFC states 

> A "host" without any trailing port information implies the default port for the service requested

And I have a server here which rejects my request when not setting the host header correctly.

**Comment by DoumanAsh** [comment]
Ah, I understand the implication, but what I say is that it is not MUST to specify port :)

So you would like default host to be set according to remote domain name and port, used for connection
automatically?
It is quite rare to run server on non-80 port, but I guess we could do it.

Just for your interest, HOST is set, if it is omitted, here https://github.com/actix/actix-web/blob/master/src/client/request.rs#L629-L640

**Comment by Paradyx** [comment]
That would be great :+1:

**Comment by DoumanAsh** [comment]
@Paradyx If you have time, you could do it youself, PRs are welcome 😄 

I'll take a look at it later one, after work

**Comment by DoumanAsh** [comment]
@Paradyx Btw should we omit port in header when we use default HTTPs port too? 😄
