### ISSUE TITLE
It's not necessary to use `systemfd` with `cargo watch`

### ISSUE THREAD

**Issue by rushmorem** [actix/actix-web#450]
You can simply use the `pkill` command to kill the process before restarting. I use it like so

```bash
cargo watch --shell "pkill -f '^target/'; cargo run"
```

**Comment by DoumanAsh** [comment]
Em... I'm not sure, what is the context of it?

**Comment by rushmorem** [comment]
> Em... I'm not sure, what is the context of it?

I was reading https://actix.rs/docs/autoreload so I just wanted to point this out. Simply killing the process first allows you to use `cargo watch` without modifying your app.

**Comment by DoumanAsh** [comment]
Ah I see, it is more of issue for our docs then.

You can find it [here](https://github.com/actix/actix-website/blob/master/content/docs/autoreload.md) but to be honest I'm not well familiar with unix systems to assert whether your suggestion is valid one or not.

Does `--shell "pkill -f '^target/'; cargo run"` going to be run each time changes are detected by `cargo watch`?
Though I wonder about windows support :)

**Comment by rushmorem** [comment]
> Ah I see, it is more of issue for our docs then

Yes, it's just a documentation issue.

> Does --shell "pkill -f '^target/'; cargo run" going to be run each time changes are detected by cargo watch?

Yes it does. It works just like `cargo watch -x run`. The pattern `'^target/'` is looking for only the sub-process that starts with `target/` so it doesn't kill `cargo watch` itself.

> Though I wonder about windows support :)

I don't use Windows myself, so I'm not sure. `pkill` is available there but [I don't know if it works as expected](https://unix.stackexchange.com/questions/19359/alternative-to-pkill-or-pgrep-f-on-cygwin).

**Comment by DoumanAsh** [comment]
@rushmorem there is no such thing on native `pkill` and most people don't use dirty hacks like cygwin.
So for them it wouldn't applicable.

What I think is that the current way should remain as it seems to be more portable
`systemfd` seems to work on Windows

P.s. but you can add alternative method to docs

**Comment by rushmorem** [comment]
Never mind. I thought `systemfd` was only being used to make development convenient. I've just learnt that it's also used so that the "process can then restart itself without dropping connections". This is useful in production.
