### ISSUE TITLE
Big files download - corruption

### ISSUE THREAD

**Issue by neowutran** [actix/actix-web#454]
Testing again 

Same code as here #426 , but updated to lasted change in master
Using StaticFile handler, big files are systematically corrupted. 
Like this one 
https://neowutran.ovh/updates/ShinraMeterV2.50.zip ( ~33Mo ) 
(  https://neowutran.ovh:8080/updates/ShinraMeterV2.50.zip ) 

The download start and complete, but the .zip is corrupted. 
On server side, the file is OK, but the result downloaded by users is not valid

**Comment by fafhrd91** [comment]
what do you use for download?

**Comment by fafhrd91** [comment]
first link contains corrupt file, second is good. i use actix-web master with rust-tls feature, curl downloads file without corruption

**Comment by fafhrd91** [comment]
ok, i see corruption

**Comment by fafhrd91** [comment]
@neowutran do you use rust-tls feature?

**Comment by neowutran** [comment]
Yes, I am using rust-tls

**Comment by fafhrd91** [comment]
Try OpenSSL. I think this is bug in rustls

**Comment by neowutran** [comment]
You are right, it is a bug in rustls. 
With openSSL it work as expected

**Comment by DoumanAsh** [comment]
@neowutran I've been trying to reproduce it on my machine but so far wasn't able to.
Just out of curiosity, if I'm not mistaken you did use curl to download the file, right?

**Comment by neowutran** [comment]
No, just classic browser firefox / chrome

**Comment by neowutran** [comment]
You can also reproduce a similar bug with this source code https://git.neowutran.ovh:8080/neowutran/Actix-web-issue-438 

The combinaison http2 + rustls have a lot of issues

**Comment by DoumanAsh** [comment]
@neowutran Ah ok, it is just I tried variously to reproduce your issue on my machine but wasn't able to do it. I'll try to use your example

**Comment by DoumanAsh** [comment]
Interestingly enough in release mode I see problem  https://i.imgur.com/UW8hysY.png
But surprisingly it doesn't even let me to download file now and browser just aborts connection

Though it is strange error.

**Comment by DoumanAsh** [comment]
@neowutran Can you please check if updated version of `tokio-rustls` solves issue? i.e. just call `cargo update`

**Comment by neowutran** [comment]
I confirm that the tokio-rustls + rustl upgrade fixed both #438 and #454 
Thanks : ) 

BTW, it is possible to make rustls publicly available throu actix-web ? (like: ``use actix-web::rustls::.... `` ) to be sure to always use the same version between actix-web and the soft using actix-web ?

**Comment by DoumanAsh** [comment]
hmm @fafhrd91 what do you think about exposing `rustls`?
I kinda like to expose important dependencies through public interface, makes life easier for user

I'll close the ticket once I'll update minimum versions

**Comment by fafhrd91** [comment]
We don’t need to, cargo always uses same patch version for all deps
