### ISSUE TITLE
Q about DbExecutor

### ISSUE THREAD

**Issue by CaptainVi** [actix/actix-web#456]
Hi everyone!

May be I have a strange question, but: I have two DBs in my project - Postgresql and Cassandra. How can I use/rewrite DbExecutor (https://actix.rs/docs/databases/) if I need to take data from Postgresql DB and send it to Cassandra DB, so in my function I have 2 DbConnection for 2 different DB.

**Comment by DoumanAsh** [comment]
This question is better to ask in our [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

I'm not sure how you designed your two databases, but assuming that each database is wrapped into actor like `DbExecutor` you could communicate between them using addresses as with any other actor.

**Comment by fafhrd91** [comment]
something like `self.addr.send(CassandraMessage).wait()`
