### ISSUE TITLE
Could the `HttpResponseBuilder` method `json` take paramater `value` by reference instead of value

### ISSUE THREAD

**Issue by davidMcneil** [actix/actix-web#457]
The `HttpResponseBuilder` method [`json`](https://actix.rs/api/actix-web/stable/src/actix_web/httpresponse.rs.html#652-669) takes a parameter `value` of type T by value. Is this necessary? It looks like only a reference to value is used in the method.

**Comment by DoumanAsh** [comment]
I think there should be no problem as we really need only reference to value, though we would need to wait for `0.8` for such change as it breaks compatibility of API.

**Comment by fafhrd91** [comment]
We can add `.json2()` for 0.7

**Comment by davidMcneil** [comment]
Great! I will put together a pull request.

**Comment by DoumanAsh** [comment]
@fafhrd91 should we plan for it to become `json` in 0.8 then?

**Comment by fafhrd91** [comment]
@DoumanAsh yes, but I don’t want to release 0.8

**Comment by DoumanAsh** [comment]
Well Ok, I'll try to keep it mind for next major release once it happens in future.

**Comment by fafhrd91** [comment]
Fixed by #458
