### ISSUE TITLE
System is not running with actix 0.4.2 and actix-web 0.3.0 (minimal example)

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#46]
So I updated `actix` and `actix-web` today by deleting my `Cargo.lock` and updating again.

I got this in my `Cargo.toml`

    actix = { git = "https://github.com/actix/actix" }
    actix-web = { git = "https://github.com/actix/actix-web" }

and this in my `Cargo.lock`
```
dependencies = [
 "actix 0.4.2 (git+https://github.com/actix/actix)",
 "actix-web 0.3.0 (git+https://github.com/actix/actix-web)",
...
]
```

Now this minimal example:

```
fn main() {
    let url = "localhost:8000";

    let sys = actix::System::new("test");
    let _server = HttpServer::new(
        || Application::new()
            .resource("/", |r| r.f(index))
              )
        .bind(url).unwrap()
        .start();

    let _ = sys.run();
}

fn index(req: HttpRequest) -> &'static str {
    "Hurray!"
}
```

gives me: 

> thread 'main' panicked at 'System is not running', /home/unmoving/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.4.2/src/arbiter.rs:143:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: actix::arbiter::Arbiter::system::{{closure}}
             at /home/unmoving/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.4.2/src/arbiter.rs:143
   7: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:377
   8: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:288
   9: actix::arbiter::Arbiter::system
             at /home/unmoving/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.4.2/src/arbiter.rs:141
  10: actix::arbiter::Arbiter::new
             at /home/unmoving/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.4.2/src/arbiter.rs:58
  11: actix::arbiter::Arbiter::start
             at /home/unmoving/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.4.2/src/arbiter.rs:196
  12: <actix_web::server::HttpServer<T, A, H, U>>::start_workers
             at /home/unmoving/.cargo/git/checkouts/actix-web-02c803d355aed967/584d0c9/src/server.rs:286
  13: <actix_web::server::HttpServer<tokio_core::net::tcp::TcpStream, std::net::addr::SocketAddr, H, U>>::start
             at /home/unmoving/.cargo/git/checkouts/actix-web-02c803d355aed967/584d0c9/src/server.rs:353
  14: rust_actix_test::main
             at src/main.rs:89
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:480
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:459
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start

I can't seem to find the reason. Any ideas?

Complete example now at: https://github.com/Unmoving/actix-web-test/tree/master

**Comment by fafhrd91** [comment]
do you have repo where I can reproduce the problem?

**Comment by fafhrd91** [comment]
I run tests for all `guide` examples on every commit, so those should work. could you also run one of examples

**Comment by ghost** [comment]
I just ran `examples/basics` and it worked. Give me a minute or two to prepare a repo.

**Comment by ghost** [comment]
See: https://github.com/Unmoving/actix-web-test/tree/master please! (And thanks for your efforts!)

**Comment by fafhrd91** [comment]
problem is that your code uses different actix from actix-web. actix-web uses 0.4.2 and your coded uses git repo. so rust compiles those as two different code bases.

just modify your Cargo.toml to use "actix = "0.4"

very confusing, I'd say ugly :)

**Comment by ghost** [comment]
Thanks, I understood Cargo wrong there then. Actually it's a shame that I even have to add `actix` manually then, as `actix_web` already specifies that as dependency... alas, I will learn. Sorry again!

**Comment by fafhrd91** [comment]
No problem.

You can also use `HttpServer::run()` method, it starts system and blocks

**Comment by casperin** [comment]
Maybe I missed it in the docs somewhere, but it isn't immediately obvious that you have to use `actix 0.5` (newest as of writing is `actix 0.6`) with `actix-web 0.6`.
