### ISSUE TITLE
Header predicate should enable checking for existence of Header, not just equality

### ISSUE THREAD

**Issue by chefsalim** [actix/actix-web#462]
Currently the Header predicate can only match exact values. This makes Header predicates inflexible and less useful than it should be. For example, if we could use a predicate to just check for existence of an Authorization header, that would be quite useful in simplifying the auth check code flow, for example, for paths that can be optionally authenticated (for example, we have a search API that can be used without authentication, but provides extra search facilities for authenticated users).  Alternatively, if the check function supported a regex that could be a solution as well.  Yet another alternative would be allowing users to develop their own predicates (currently not possible without forking).

**Comment by fafhrd91** [comment]
You should be able to develop custom predicate. What is the problem?

**Comment by fafhrd91** [comment]
You just need to implement this trait 
https://actix.rs/actix-web/actix_web/pred/trait.Predicate.html

**Comment by chefsalim** [comment]
Perfect, thanks.. closing.
