### ISSUE TITLE
Parse/Unparsing Client Response/Request

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#463]
I am writing a multi-threaded crawler which requires considerable amount of memory, for analysis purposes i have to store everything including my actix::client::ClientRequest and actix::client::ClientResponse objects in database.
Giving the dynamics of a http request/response, is there a way to parse/unparse these objects to a certain file format like JSON? if not, what is the best way to do so without writing a static parser?

**Comment by DoumanAsh** [comment]
This is quite strange question.

First of all what is the reason for storing requests and responses?
One problem with HTTP primitives is that their bodies may be futures so you would be able to read it only once. While it is simple matter for headers/uri and other stuff, bodies would prove difficulties.

Currently there is no easy way to deconstruct both request and responses so you would need lots of manual code to serialize and deserialize request.

In case of response, current API doesn't even allow to re-construct it.

I would suggest to consider to make some more simple way to represent your requests/responses

P.s. this question is rather for [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by ghost** [comment]
The main reason behind this decision is that i will be needing that information at a later time and since i am crawling a lot of URLs it is necessary to find a way to construct/deconstruct these objects. 
Thank you for your quick response and complete answer, i will ask further questions on gitter.
