### ISSUE TITLE
Can't obtain body if headers don't contain content-length

### ISSUE THREAD

**Issue by xoac** [actix/actix-web#464]
Code:
```
extern crate actix_web;
extern crate tokio;
use actix_web::{actix, client, HttpMessage};
use tokio::prelude::*;

fn main() {
    actix::run(|| {
        client::get("http://192.168.50.71/xml/ix.xml")   // <- Create request builder
            .header("User-Agent", "Actix-web")
            .finish().unwrap()
            .send()                               // <- Send http request
            .map_err(|_| ())
            .and_then(|response| {                // <- server http response 
                println!("Response: {:?}", response);

                response.body()                     // <- get Body future
                    .limit(5024)                // <- change max size of the body to a 1kb
                    .map_err(|_e| ())
                    .and_then(|bytes| {
                        println!("body: {:?}", bytes);
                        Ok(())
                   })
            })
    });
}
```

After run:
```
Response: 
ClientResponse HTTP/1.1 200 OK
  headers:
    "connection": "close"
    "content-type": "text/xml"
    "server": "lwIP"
    "cache-control": "no-cache"

body: b""
```

Body is available if I send request through Firefox or curl:
![](https://files.gitter.im/actix/actix/WHil/obraz.png)

@fafhrd91 on gitter found out in that case responder use content-length = 0.

**Comment by DoumanAsh** [comment]
afaik if there is no `Content-Length` or it is not chunked response, we cannot know exactly what is the body.
I think in this case it is right to assume that with no information of body, we should assume no body.

**Comment by fafhrd91** [comment]
We need some config for that. Some servers just broken

**Comment by Neopallium** [comment]
@DoumanAsh I can't find it in the HTTP/1.1 RFC specs, but there are some HTTP servers that use `Connection: close` instead of chunked encoding when they don't know the length of the response body.

Go's HTTP response parser has some test cases for handling response bodies without a `Content-Length` header or chunked encoding:
https://golang.org/src/net/http/response_test.go

**Comment by fafhrd91** [comment]
Client should support be able to read response even without content-length. That is just a reality

**Comment by terrence2** [comment]
I am also hitting this. In my case, the target server is a tiny embedded device that I have no control over.

**Comment by xoac** [comment]
@terrence2 I have exactly the same problem. Use Client from hyper. It will work in that case

**Comment by terrence2** [comment]
0.7.6 solves the issue for me. Thank you for the fast response!
