### ISSUE TITLE
Middleware should allow configuring per resource

### ISSUE THREAD

**Issue by chefsalim** [actix/actix-web#466]
One of the things that we are missing coming from Iron is the ability to set middleware on a per resource level. For example, we have Authenticated middleware that we'd like to set only on the authenticated resources. Currently, actix-web does not allow this, so we have to either not use middleware for auth, or try to hack around in less than elegant ways. It would be great to have this ability, or some other supported pattern.

**Comment by fafhrd91** [comment]
You can set middleware per resource. It is not possible to use middlewares on route level

https://actix.rs/actix-web/actix_web/dev/struct.Resource.html#method.middleware

**Comment by chefsalim** [comment]
Thanks @fafhrd91 .. apologies for missing the resource level middleware in the doc.  I'm trying this out, unfortunately running into another blocking issue that I will post separately.

**Comment by lermana** [comment]
FYI middleware at `route` level is now supported as well: https://github.com/actix/actix-web/pull/2725
