### ISSUE TITLE
BorrowMutError panic when borrowing extensions mutably in middleware and handler

### ISSUE THREAD

**Issue by chefsalim** [actix/actix-web#467]
So the scenario is that we have a couple of middlewares that insert extensions (eg, a 'session' in a Authenticate middleware, and a internal 'client' in a Client middleware).  The client is used in the handler (as well as in the Authenticate middleware), and needs to be borrowed mutably, hence extension_mut is used to get at it.  The issue is that retrieving the extension_mut in the handler results in a BorrowMutError panic.

thread 'arbiter:c45624a3-3594-4687-844b-fa006459cb6f:actor' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5

It's not immediately clear how to work around this.  Any guidance would be appreciated.

**Comment by chefsalim** [comment]
Never mind - pilot error.  Closing.

**Comment by mdtusz** [comment]
A bit old I know, but do you remember how you solved this? I'm encountering the same issue with both the identity and session middlewares and can't seem to find what the issue is - things seem to be set up the same way as outlined in the docs.

**Comment by fafhrd91** [comment]
@mdtusz do you use 0.7 or 1.0? post backtrace

**Comment by mdtusz** [comment]
Am using 0.7.19. 

I've fixed the issue though - I was making use of `request.query()` which caused a panic when using `request.remember()` afterwards.

By modifying my code to clone the `Ref` returned from `request.query` things appear to be working now. I don't fully understand the reasons for _why_ since my borrow-and-ownership-knowledge is still a work in progress, but it works.

Before:

```rust    
fn my_handler(request: HttpRequest<State>) -> impl Responder {
    let params = request.query();
    let config = auth_config();

    let code = params.get("code").unwrap().as_str();
    let token_result = config.exchange_code(code).unwrap();

    request.remember(token_result.access_token.to_owned());

    HttpResponse::TemporaryRedirect()
        .header("Location", "/")
        .finish()
}
```

After:

```rust    
fn my_handler(request: HttpRequest<State>) -> impl Responder {
    let params = request.query().clone();
    let config = auth_config();

    let code = params.get("code").unwrap().as_str();
    let token_result = config.exchange_code(code).unwrap();

    request.remember(token_result.access_token.to_owned());

    HttpResponse::TemporaryRedirect()
        .header("Location", "/")
        .finish()
}
```

I notice that the `HttpRequest.query()` method has been removed in 1.0 - is it for this reason?
