### ISSUE TITLE
Add db example

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#48]
Add db example without diesel

**Comment by AlbanMinassian** [comment]
why not download (and update) https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Rust/actix inside /examples ?

**Comment by AlbanMinassian** [comment]
and an example with redis :)

**Comment by fafhrd91** [comment]
we should implement db bench without diesel for framework benchmarks. i can not find how
to do batch updates with one execute. because of that "update" benchmark result is not good

**Comment by fafhrd91** [comment]
r2d2 example has been added https://github.com/actix/actix-web/tree/master/examples/r2d2
