### ISSUE TITLE
Compilation error with features=tls due to leftover tokio_tls in client

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#480]
It looks like tokio_tls has been removed from the project in 2e8d67e2aecfb850c341146bce5ccf60ff04f73b, except the client connector still depends on it:

https://github.com/actix/actix-web/blob/986f19af8655b95ebbba3a2b8fe2829eca1c85c5/src/client/connector.rs#L27

This causes a cascade of compilation errors:

> no method named `unwrap` found for type `native_tls::TlsConnectorBuilder` in the current scope
   --> src/client/connector.rs:302:51
    |
302 |             let builder = TlsConnector::builder().unwrap();

**Comment by DoumanAsh** [comment]
Oh damn, is this stable version? or master branch?

**Comment by fafhrd91** [comment]
This is master. I’ll fix

**Comment by fafhrd91** [comment]
fixed by 810995a

**Comment by kornelski** [comment]
Thank you
