### ISSUE TITLE
Middleware question

### ISSUE THREAD

**Issue by s-panferov** [actix/actix-web#484]
Hi, I’m trying to implement a basic authorization with Amazon Cognito and I’m building a middleware that should check for a user’s access token and transparently update it if it expires. Basic logic looks like this:

1. User makes a request to my site.
1. The Middleware checks for a `access_token` cookie.
1. If it expires it checks for a `refresh_token` cookie.
1. If `refresh_token` expires user should be redirected to a login page. If not — we should try to get a fresh token set of (`id_token`, `access_token`, `refresh_token`). Then we should allow the request to proceed as nothing happened except that we need to assign fresh cookies at the end.

What kind of workflow should I have with my middleware? 

Right now I’m struggling with appending fresh cookies at the end of user’s response. In nodejs I would just call `res.cookie(..); next()` from a middleware to assign a cookie and to continue normal execution flow. But in `actix-web` it looks like I should split my logic into two steps.

1. `fn start` with cookies checking/refreshing and storing somewhere.
2. `fn response` to finally assign fresh cookies at the end.

Am I right?

What I really don’t like it that I need to store these cookies somewhere untill the `response` is called. This means that I should require some specific user store shape in my middleware and I cannot make this transparent for an API user:

```rust
impl<S> Middleware<S> for CognitoMiddleware
where
  S: HasFieldsToStoreIntermediateCookies,
```

I would really like this middleware to be self-contained and not to require any additional boilerplate from users.

I see several ways to deal with this:

1. Stateful middlewares. Middleware can store some internal state between stages.
1. Some kind of a `TypeMap`(e.g. https://github.com/reem/rust-typemap) to store arbitrary data in a `Request`.
1. `fn start` in middleware to return a `FnOnce` closure that can modify a response at the end.
1. Merge middleware's response with the final response at the end.
1. Something else?

**Comment by DoumanAsh** [comment]
@s-panferov Using a separate `start` and `response` is likely the way to keep cookies up to date.
So I would suggest to take inspiration from Cookie Storage middleware https://github.com/actix/actix-web/blob/master/src/middleware/session.rs#L241-L270

It uses `Extensions` to store data from `start` and then access it in `response`

**Comment by s-panferov** [comment]
extensions! thanks!
