### ISSUE TITLE
Struct actix_web::client::ClientRequest

### ISSUE THREAD

**Issue by mgi2613github** [actix/actix-web#487]
the implementing methods cover the following methods:
get,
put,
head,
delete,
post.
I tested, and worked well.
Nonetheless, after developed patch methods to communicate Redis DB, I attempt to test patch by the rust framework, suchlike, 
let mut req = client::ClientRequest::patch("http://localhost:8010/6-15-2018/nudm-pp/v1/msisdn-123456/pp-data");        
It appears patch (update) not available.

Thank you for the help.

**Comment by fluxxu** [comment]
You can use `build` method directly
```rust
let mut req = ClientRequest::build().method(Method::PATCH).uri("http://localhost:8010/6-15-2018/nudm-pp/v1/msisdn-123456/pp-data");
```
