### ISSUE TITLE
Accessing to path info from predicate

### ISSUE THREAD

**Issue by katyo** [actix/actix-web#489]
The predicates filtering technique introduced by actix-web inspired me implementing access control in my apps using it.
As I see the `check()` fn can access to `Request` (not to `HttpRequest<S>`). I wondering how can get access to path info from predicates?

Say, I works on predicate which checks resource owning for the user which makes request. The path contains resource id which I would like to get in `check()` function of predicate.

Is it possible for now?

**Comment by katyo** [comment]
It seems the predicates isn't so suitable for access checks...

**Comment by DoumanAsh** [comment]
@katyo Not sure I follow you, if predicate has access to request, then it should be able to retrieve path from it? But I imagine something like [extractor](https://actix.rs/actix-web/actix_web/trait.FromRequest.html) could be more useful.
You could extract id and then return error if it is invalid
