### ISSUE TITLE
Can't have multiple Applications on a single server with different state

### ISSUE THREAD

**Issue by fuchsnj** [actix/actix-web#49]
I don't think this is currently possible, but please correct me if I'm wrong.

`HttpServer::new()` requires an iterator of `Application`s (something that implements `IntoHttpHandler`)

Since the `Application` has a generic State parameter, if you have applications with a different type for State, you can't create an iterator over these different types.

**Comment by fafhrd91** [comment]
You have to manually box applications, something like:

```rust
HttpServer::new(|| vec![
       Box::new(Application::<State1>::new().finish()),
       Box::new(Application::<State2>::new().finish()),
       Box::new(Application::<State3>::new().finish())])
```

maybe application should have convenience method.

**Comment by fuchsnj** [comment]
once you box the application, it doesn't implement `actix_web::server::HttpHandler` so I don't think this works either

```
the following trait bounds were not satisfied:
           `std::boxed::Box<actix_web::application::HttpApplication<State1>> : actix_web::server::HttpHandler
```

**Comment by fafhrd91** [comment]
you are right! thanks for report

**Comment by fafhrd91** [comment]
fixed in master

https://actix.github.io/actix-web/actix_web/struct.Application.html#method.boxed

**Comment by daleione** [comment]
error with  app with state and no state. such like

`    vec![
        App::new().resource("/test1", |r| r.f(test1))
            .boxed(),
        App::with_state(AppState::default())
            .resource("/test2", |r| r.f(test2))
            .boxed(),
`

**Comment by fafhrd91** [comment]
@daleione here is example 
https://actix.rs/actix-web/actix_web/struct.App.html#method.boxed
