### ISSUE TITLE
Incorrect URL in 'Starting server on' log

### ISSUE THREAD

**Issue by RazrFalcon** [actix/actix-web#493]
After updating to v0.7.4 the `actix-web` starts with:
```
 INFO 2018-08-29T14:07:49Z: actix_web::server::server: Starting 4 http workers
 INFO 2018-08-29T14:07:49Z: actix_web::server::server: Starting server on http://Some(V4(127.0.0.1:8000))
```

In 0.7.3 the url was `https://127.0.0.1:8000`. Also note http**s**, not http.

**Comment by DoumanAsh** [comment]
Yeah, sorry about that, it is fixed in https://github.com/actix/actix-web/pull/482
