### ISSUE TITLE
Using cookie auth with websockets?

### ISSUE THREAD

**Issue by Boscop** [actix/actix-web#494]
How can I use the [`CookieIdentityPolicy`](https://actix.rs/actix-web/actix_web/middleware/identity/index.html) with websockets? 

In my ws connect handler I have to see which logged-in user is connecting, and reject the connection if the user is not logged in.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

> The server can send other headers like Set-Cookie, or ask for authentication or redirects via other status codes, before sending the reply handshake.

**Comment by fafhrd91** [comment]
just check identity before starting ws stream/actor

**Comment by Boscop** [comment]
But I also want to support HTTP Basic auth and then set the identity cookie in the response, what's the best way to do that so that this cookie can be read by `CookieIdentityPolicy` in my REST API handlers?

**Comment by fafhrd91** [comment]
You need to build custom identity policy for basic auth

**Comment by Boscop** [comment]
Yes but that's for reading the username and pw from the header.

After that, how should I set the cookie so that it's readable by the `CookieIdentityPolicy` in my REST API handlers? Is there already a public function for doing it the same way? Or should I just copy&paste the code from `CookieIdentityPolicy`?

**Comment by fafhrd91** [comment]
Implement everything as new policy, do not try to re use cookie policy

**Comment by Boscop** [comment]
But my users should only have to log in once!
The app uses ws and rest api.
So the ws connection handler and my rest api handlers should use the same identity cookie.
So I have to encrypt / decrypt the cookie the same way in both cases..

**Comment by fafhrd91** [comment]
Check inventory service sorice code. It is really simple
