### ISSUE TITLE
actix-web client on master cannot handle Connection: close

### ISSUE THREAD

**Issue by untitaker** [actix/actix-web#495]
#483 breaks one of our services, all actix-to-actix requests (i.e. using `actix::client` to connect to a service using actix-web) end up in [this line somehow](https://github.com/actix/actix-web/pull/483/files#diff-d5dbe03a9d071b8c9d3937d8da44b0f1R45).

The only way to "fix" this inside of the client is to change the pattern match I linked above to this:

```
match io.read_available(buf) {
    Ok(Async::Ready(_)) => (),
    ...
}
```

however, that should not be necessary. I think the server prematurely disconnects for whatever reason.

Since the PR does not appear to be connected to an issue where it's proven that it actually fixes the issue, and it doesn't come with any testcase, I am not sure how to fix my issue without breaking the usecase of @Neopallium 

This is not quite a bugreport but a request to @Neopallium to clarify which issue they were seeing.

**Comment by fafhrd91** [comment]
I will check, thanks for report.

**Comment by untitaker** [comment]
@fafhrd91 I am not sure if you can investigate with this information. What baffles me is that the test_client.rs runs just fine

**Comment by untitaker** [comment]
~~To be clear I think there's a logic bug in that PR: The client errors out when the server disconnects but data has already been read, while it didn't do so before. In that case the old `read_available` would've returned `Ready(!read_some)` which doesn't match the branch `Ready(true)`. The new code would always return `Ready((read_some, true))` and this matches `Ready((_, true))`.~~ EDIT: nonsense

This seems entirely intentional by @Neopallium so I am not sure what's going on here.

**Comment by mitsuhiko** [comment]
There is a pull request up in our repo that shows the issue and the travis build that is failing: https://github.com/getsentry/semaphore/pull/74

**Comment by Neopallium** [comment]
Here is a simple HTTP client to show the problem I had found and was trying to fix with the PR.
https://gist.github.com/Neopallium/2bc4755bbbeca88093661ebd12489276

A HTTP Client can shutdown the write side of it's TCP socket (half closed) right after sending a request.  The HTTP server should still process that request and send a response.  The HTTP client can still read the response on it's half closed socket.

Also actix-web was leaking memory by not correctly detecting that the socket was closed.  The TCP connection on actix-web's side was stuck in the "CLOSE_WAIT", which means that actix-web needs to close the socket.

What I was trying to do in the PR was to allow read_available to return two different states (read_some and EOF).  read_available() keeps calling read() on the socket until it either returns an error or "0".
The reason actix-web wasn't detecting that the socket was closed, was that read_available() had read some data (read_some) and had read() return 0 (EOF).  So it had two bits of important information that needed to be return to the caller.

The PR could have been made simpler by only calling read() only once, but this could have a big impact on performance for some users.

FYI, read_available() should also have a limit on how much data it will read before returning.  One HTTP client with a very high bandwidth connection could starve other connections and cause high memory usage on actix-web.

I hope this helps to explain the PR.  I will try to answer any questions you might have.

**Comment by untitaker** [comment]
Apparently disabling keepalive does the trick to repro this issue:

```rust

fn forward_upstream(request: &HttpRequest<()>) -> ResponseFuture<HttpResponse, Error> {
    ClientRequest::build()
        .method(request.method().clone())
        .uri("http://localhost:3000/level2")
        .header("Connection", "close")
        .finish().unwrap()
        .send().map_err(|e| {
            println!("{:?}", e);
            Error::from(e)
        })
        .and_then(move |response| {
            let mut forwarded_response = HttpResponse::build(response.status());
            Ok(forwarded_response.finish())
        })
        .responder()
}

fn main() {
    let sys = System::new("relay");

    let mut server = server::new(|| {
        App::with_state(())
            .handler("/level1", forward_upstream)
    });

    server = server.bind("localhost:3000").unwrap();
    server.system_exit().start();
    let _ = sys.run();
}
```

Hit `http://localhost:3000/level1` and you will see the error we encounter.

Alternatively to the `Connection: close` header you can also disable keepalive serverside and will encounter the same error.

**Comment by untitaker** [comment]
@Neopallium I suppose your case is valid but I don't quite see why you had to change the client behavior on `read() == 0` for that?

**Comment by untitaker** [comment]
@mitsuhiko claims that `read() == 0` should never happen either because if there's a content-length the client shouldn't read past it, perhaps you could elaborate on that Armin?

**Comment by Neopallium** [comment]
the `read_available()` method doesn't know the value of content-length.  It just keeps calling `self.read()` in a loop until it gets an error `WouldBlock` or `0`

The problem is that `read_available()` can read some data and see that the socket has been closed.

**Comment by Neopallium** [comment]
I am seeing the problem you are having with "Connection: close".  It even happens with non-actix web servers.  I have tried with nginx.

**Comment by mitsuhiko** [comment]
The point I was trying to make wrt content-length 0 is that normally one would wait between headers and payload. Since there is no body it should stop after header parsing. So I was not sure why it would attempt to read past the headers and try to read into the (not closed) stream.

I did not study the code but it seems like this now runs ahead of the headers.

**Comment by Neopallium** [comment]
Fixed the issue.  Sorry I didn't test the `ClientRequest` with my previous PR.

**Comment by fafhrd91** [comment]
@untitaker could you test master

**Comment by untitaker** [comment]
Yup, works, thanks
