### ISSUE TITLE
Improve buffer management

### ISSUE THREAD

**Issue by Neopallium** [actix/actix-web#499]
This issue is for tracking improvements to actix-web's handling of IO buffers.

Goals:

1. Allow per connection buffer sizes to be tuned.  Servers that need to handle very large number of mostly idle connections will want to minimize per connection buffer size.  Also can help when the server is under DOS attacks.
2. Fix some memory leaking issues on long-lived connections (i.e. keep-alive connections have a buffer that keeps growing).
3. Look into using a buffer pool.  See if it can help improve performance.

**Comment by Neopallium** [comment]
I am using the buffer_management branch on my fork for this work right now.
https://github.com/Neopallium/actix-web/tree/buffer_management

I have already added a read limit to `read_available()`.  A quick test on local host posting a 31Mbyte file shows a saving to peak memory usages (before 69Mbytes, after 39Mbytes).  This change would be important for services that proxy large http messages between a client and a backend service, or if they want to handle a large number of streaming resources (stream video from a storage backend).

Backend services on the same wired network could send data much faster then the client connected to the frontend can download it.  Right now actix-web will keep reading from the TCP buffer until it is empty, but a fast backend service could keep it full until the whole resource has been transferred.  This would also cause latency issue with other connections, since large transfers would starve small requests for processing time.

**Comment by fafhrd91** [comment]
i don't think this is right solution.

* actix is built on fact that it read everything available in socket at once. 
  remember mio works in egde mode, if you do not read data until WhouldBlock, then socket fd
  is not registered in kernel. so here scenario, keep-alive connection, you get two request first request
  with big payload. lets say you read payload data, it is less that 64k, and then part of next http message
  decoder would return NotReady, but because socket fd is not registered in selector, then this 
  connection would hang forever.
* i dont believe you can get tcp data faster than app can read data from kernel

**Comment by Neopallium** [comment]
1. I will need to look into the lower IO layers to make sure that a connection can't hang.  So far the testing that I have done, shows that it works ok.

2. If the other side of the connection is local, then the TCP buffer can fill faster then it can be read (at least the sender can keep ahead of the receiver).

My main goal is to limit how large the buffers can grow (to support high connection counts).

edge-triggered mode doesn't require that the app fully drain the socket buffer before doing other work.  Edge-triggered mode allows the application more control over the draining of the socket.  The application just needs to keep track of which sockets are not blocked.  With level-triggered mode, the application would need to unregister read interest in to socket until it has drained the buffer.  Edge mode is better because it requires less syscalls.

I have a lot of experience with using epoll before and after edge-mode support was added. (even patch the kernel in our servers before it was included in linux).  For event loops that need to handle low-latency connections (client event subscribe) and large stream (backend data source publish) connections, it is important to balance/limit how much data is read from each socket.

Not all applications want to fully drain the TCP buffer.  If the application keeps the TCP buffer drained all the time, then the sender can keep sending faster and faster (TCP window size will grow).  Slowly reading from a TCP socket will provide back pressure (TCP window size) that will limit how fast the sender can send.

It might be best to allow tuning the read speed and buffer sizes, at compile-time and maybe some per-connection control too.

Here is two strace logs tracing `epoll_*/recvfrom/sendto`:
https://gist.github.com/Neopallium/cd09859217819d3433d3f85c020fc7f9

The first one shows actix-web's current behavior to fully drain the socket.  the buffer grows to about 40Mbytes in size (10Mbytes unused when `read_available()` returns).

The second one shows actix-web with a 64Kb read limit.  The buffer never grows larger then about 81Kb and most calls to `read_available()` fully fill the 81Kb buffer before returning.

**Comment by fafhrd91** [comment]
Adding socket tracking code just for sake of artificial local client seems not very wise.

**Comment by fafhrd91** [comment]
Don’t get me wrong, I’d like to add limit but current architecture is too sensitive to modifications and you change would case very hard to find bugs

**Comment by fafhrd91** [comment]
i am planing complete parsing redesign

**Comment by Neopallium** [comment]
Sorry for the late reply.  I am setting up a test environment for doing stress testing with remote connections (over gigabit LAN).  Some initial testing with >200,000 remote connections has shown some connection leaking issues, which I will look into.  It doesn't seem to happen with local connections.

I am glade to hear about the parsing redesign.  Actix-web's high memory usage (growing buffers) has been blocking me from committing to use it.  I need to handle a large number of long lived connections (event pushing).

Let me know if you want any help with testing.  I would like to see actix scale up to a million or more connections.
