### ISSUE TITLE
Example of a Handler that returns a future

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#5]
I would love an example of how to return a Future to an HttpResponse. 

For example using something like mysql async to make a request to a database and then compose an HttpResponse and have that been returned. Or an HTTP request via Hyper and then compose a response based on the result. 

I love what you have done so far and I suspect I'm missing something obvious but I haven't been able to figure it out myself.

I would be willing to contribute an example if you point me in the right direction.

Thanks.

**Comment by fafhrd91** [comment]
there are several options:

## Resource::async handler

you can use https://actix.github.io/actix-web/actix_web/struct.Resource.html#method.async
in that case your handle needs to return Stream<Item=Frame>

## Http actor

In that case you can define http actor, then you can use `HttpContext` to spawn any number of futures of streams. 
here is simple example https://github.com/actix/actix-web/blob/master/examples/multipart/src/main.rs#L25

if you need more complex interaction, then you can define `Message`'s and handle them as actix actor.
here is example how to add stream to your actor's context 
https://github.com/actix/actix-web/blob/master/examples/websocket.rs#L33
then you can handle items from this stream in your `Handler` https://github.com/actix/actix-web/blob/master/examples/websocket.rs#L49


Api still is not very stable, especially simple async handlers. But actor's `Handler` seems works well.
While building SockJS server, I didn't have any problems. also I am working on http/2 support, and it seems no public api changes will be required.

I am open to any suggestions and you are welcome to join !

**Comment by glademiller** [comment]
Trying to implement using Resource.async. I created a function that I want to have return Stream<Item=Frame> but I'm unsure of how to get a Frame object. It doesn't appear to be public. 

I suspect there is something simple I am missing. I'm not using Future yet but it should be easy enough to convert a Future into a stream as needed assuming I'm not misunderstanding what I need to do.
```
fn with_param(
    req: &mut HttpRequest,
    _payload: Payload,
    state: &(),
) -> impl Stream<Item = actix_web::route::Frame, Error = ()> {
    futures::stream::once(Ok(
        HttpResponse::builder(StatusCode::OK)
            .content_type("text/html")
            .body(format!("Hello {}!", req.match_info().get("name").unwrap()))
            .unwrap(),
    ))
}
```

**Comment by fafhrd91** [comment]
let me add example

**Comment by glademiller** [comment]
Thank you I really appreciate it. Thanks for having patience with me and for putting something as cool as Actix together.

**Comment by fafhrd91** [comment]
here is example https://github.com/actix/actix-web/blob/master/examples/basic.rs#L17
but you need to update actix-web to 0.2.1

I think `Error=()` is wrong choice.

**Comment by glademiller** [comment]
Agreed () is most certainly not the correct choice. 

Thanks for exposing Frame and for the example. This is exactly what I needed.
