### ISSUE TITLE
CORS middleware: allowed_headers is defaulting to None

### ISSUE THREAD

**Issue by fuchsnj** [actix/actix-web#50]
The documentation for `CorsBuilder::allowed_headers()` says

> If All is set, whatever is requested by the client in Access-Control-Request-Headers will be echoed back in the Access-Control-Allow-Headers header.
...
Defaults to All.

The code is correctly defaulting the internal `headers` value to `All`, but there is no code actually echoing back the `Access-Control-Request-Headers`, it just leaves the `Access-Control-Allow-Headers` header empty.

relevant line of code generating the response:
https://github.com/actix/actix-web/blob/master/src/middleware/cors.rs#L303

**Comment by fafhrd91** [comment]
Thanks for report!

Btw would you like to join actix and help with development?

**Comment by fuchsnj** [comment]
Sure, feel free to add me. I probably won't contribute too much until I get more familiar with actix.
Thanks!

**Comment by fafhrd91** [comment]
No problem, you already helped a lot.

Also that depends on your interests level, we need to do a lot to make actix usable on higher level. It requires a lot of functionality, like templates integration, better redis, better db integration, virtual hosting support, csrf, websockets client, maybe even http client

**Comment by fafhrd91** [comment]
Nested applications

**Comment by fafhrd91** [comment]
fixed in master
