### ISSUE TITLE
actix-web 0.7.6 on crates.io has executable file permissions for all files

### ISSUE THREAD

**Issue by silwol** [actix/actix-web#507]
The archive published to crates.io for `actix-web` 0.7.6 have the executable bit set for each file. This was not the case for earlier versions.

That might become a problem for tools like `debcargo` which do further processing of the archive and deploy its contents.

Fetching the archives of 0.7.6 and 0.7.5 for introspection can be done like this:
`wget -O actix-web-0.7.6.tar.gz https://crates.io/api/v1/crates/actix-web/0.7.6/download`
`wget -O actix-web-0.7.5.tar.gz https://crates.io/api/v1/crates/actix-web/0.7.5/download`

I assume it will not be possible to fix this for the already-published version, but maybe some measures can be taken to prevent this from happening for future releases.

**Comment by fafhrd91** [comment]
will release 0.7.7 today

**Comment by silwol** [comment]
Thanks for the quick answer. Sadly, the 0.7.7 tarball also has the executable bit set on the files.

**Comment by fafhrd91** [comment]
Oh! Crap. I will fix it in next release

**Comment by silwol** [comment]
Thanks!
