### ISSUE TITLE
Requests to TestServer fail with ParseError(Disconnect)

### ISSUE THREAD

**Issue by philbooth** [actix/actix-web#508]
The tests in [mozilla-services/syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs) break when we upgrade from 0.7.2 to 0.7.6. Initially I thought it might be a dup of #486, but it looks like that fix was already merged when 0.7.6 went out? I've also tried building against `master` but that also fails.

It's entirely possible they're failing because of something I'm doing wrong, I'm pretty new to both actix-web and Rust.

Failing tests are here:
https://github.com/mozilla-services/syncstorage-rs/blob/master/src/server/test.rs

And the server is defined here:
https://github.com/mozilla-services/syncstorage-rs/blob/master/src/server/mod.rs

Upgrade diff:
https://github.com/mozilla-services/syncstorage-rs/compare/master...philbooth:actix-web-0.7.6?expand=1

Any suggestions?

**Comment by DoumanAsh** [comment]
@Neopallium you might be interested to see

**Comment by Neopallium** [comment]
@philbooth Could you try the releases between 0.7.2 and 0.7.6?  If you can help narrow down which release or even which commit of actix-web causes the tests to fail, would be very helpful.  Also are all of those tests failing or just some.

I will try to take a look at it this week.

**Comment by philbooth** [comment]
>  If you can help narrow down...

Did a `git bisect` and the problem begins with 002bb24b26fbdfa6a664a10a109d763ca2f3f989.

I've also tried to create a minimal test case but I haven't managed to reproduce it outside that repo yet. For instance, this test case tries to do some of the same things our tests are doing, but it succeeds:

```rust
use actix_web::{http, test::TestServer, FutureResponse, HttpResponse, State};
use futures::future;

#[test]
fn test() {
    let mut server = TestServer::build_with_state(|| MyState).start(|app| {
        app.resource("/foo", |r| {
            r.method(http::Method::POST).with(handler);
        });
    });
    let request = server.client(http::Method::POST, "/foo").finish().unwrap();
    let response = server.execute(request.send()).unwrap();
    assert!(response.status().is_success());
}

struct MyState;

fn handler(_state: State<MyState>) -> FutureResponse<HttpResponse> {
    Box::new(future::result(Ok(HttpResponse::Ok().json(Response { foo: "bar".to_string() }))))
}

#[derive(Serialize)]
struct Response {
    foo: String,
}
```

> Also are all of those tests failing or just some.

All of them. I wonder if  I'm doing something stupid with the `TestServer` setup or our state struct or some of the handler arguments...

**Comment by fafhrd91** [comment]
i reproduced fail, checking

**Comment by fafhrd91** [comment]
fixed in master

**Comment by fafhrd91** [comment]
@philbooth could you confirm? i'll make new release after your confimration

**Comment by philbooth** [comment]
> could you confirm?

Tests are all green now, thank you!

**Comment by fafhrd91** [comment]
0.7.7 is released
