### ISSUE TITLE
Is possible to use a custom connector in actix_web::client to support http proxy?

### ISSUE THREAD

**Issue by salutant** [actix/actix-web#509]
Currently, `actix_web::client` doesn't support proxy.

**Comment by fafhrd91** [comment]
it is not possible at the moment

**Comment by transkatgirl** [comment]
Are there any plans to support this in the future?

**Comment by DoumanAsh** [comment]
I wouldn't mind for actix-web client to have it in future

**Comment by fafhrd91** [comment]
Possibly in 0.8

**Comment by dbldippy** [comment]
HTTP proxy support for the client would set actix-web apart as an all-in-one solution from say hyper which recently dumped its proxy (and also built-in TLS) to be leaner. There, if you want these client features you have to use reqwest which does not have a server.

**Comment by konghk78** [comment]
Can this be considered as a feature of AWC?

**Comment by fafhrd91** [comment]
Pr is welcomed

**Comment by micfan** [comment]
By the way, is there a way to use the `socks5` proxy?

**Comment by fafhrd91** [comment]
not at the moment

**Comment by fakeshadow** [comment]
This is now possible with the new middleware feature of awc v3.
If anyone interested in writing a proxy middleware service you can reference the redirect middleware https://github.com/actix/actix-web/blob/master/awc/src/middleware/redirect.rs
