### ISSUE TITLE
server should return 400 or 301 on malformed request URL

### ISSUE THREAD

**Issue by chefsalim** [actix/actix-web#512]
Currently, if a request is made where the url path is malformed, the server silently closes the connection.  This causes undesired behavior/errors at the downstream (eg, nginx rev proxy)

Instead, actix should return a 400 or 301 as per RFC 7230 (https://tools.ietf.org/html/rfc7230#section-3.1.1) in this case.

"Recipients of an invalid request-line SHOULD respond with either a 400 (Bad Request) error or a 301"

**Comment by theikkila** [comment]
I think there is bug in actix-web that causes some urls to be marked as malformed and then together with this bug it causes server to work very unhealthy way.

Test url:
`/q?^` (^-causes the problem)

**Comment by DoumanAsh** [comment]
@theikkila is `/q?^` actually valid?
Because everything after `?` is supposed to be query of url

**Comment by fafhrd91** [comment]
Actix-web uses http::Uri for uri parsing
