### ISSUE TITLE
No way to get to  application state from a responder

### ISSUE THREAD

**Issue by stew** [actix/actix-web#513]
I have encountered multiple situations where  I want to get access to some element my application state from inside the `respond_to`  method of a `Responder` I am implementing, but  I  don't  think  there is a  good, type safe  way to get to it from a responder.  Here is an example of  the type of thing I'm trying  to do:

    extern crate actix_web;
    
    use actix_web::*;
    use actix_web::http::Method;
    
    struct MyState {
        counter: u32,
    }
    
    struct Something{}
    
    impl Responder for Something {
        type Item = HttpResponse;
        type Error = Error;
    
        fn respond_to<S>(self, req: &HttpRequest<S>) -> Result<HttpResponse, Error> {
    
            // this is an error because the type of req.state() is &S not &MyState
            // error[E0609]: no field `counter` on type `&S`
            Ok(HttpResponse::Ok().body(format!("the counter is {}", req.state().counter)))
        }
    }
        
    
    fn index(req: HttpRequest<MyState>) -> Something { Something{} }
    
    fn main() {
        server::new(|| App::with_state(MyState{counter: 0}).resource("/", |r| {
            r.method(Method::GET).f(index)
        }));
    }

**Comment by mzhang28** [comment]
Hello, I'm running into this problem as well. Would it be a good idea to change `Responder` to `Responder<S: 'static>`? This way you would be able to `impl Responder` with further trait constraints or on specific structs rather than having the generic on `respond_to` which forces the inner function to deal with a generic `S` without trait constraints.

**Comment by fafhrd91** [comment]
I am planing to change Responder trait, but this is breaking change for 0.8 release

**Comment by mzhang28** [comment]
OK. Is there a dev branch in which this is implemented? I need this generic constraint functionality in my project. If there isn't I'm willing to contribute.

**Comment by mzhang28** [comment]
How are you planning to change the Responder trait?

**Comment by fafhrd91** [comment]
this is possible in 1.0 (master)
