### ISSUE TITLE
multiple allowed_origin

### ISSUE THREAD

**Issue by damody** [actix/actix-web#517]
```
Cors::for_app(app)
                    .allowed_origin("http://localhost:4200")
                    .allowed_origin("https://www.find-eat-price.com")
```
then get wrong result
```
access-control-allow-origin: https://www.find-eat-price.comhttp://localhost:4200
```
the correct result will like
```
access-control-allow-origin: https://www.find-eat-price.com, http://localhost:4200
```
reference: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMultipleAllowOriginNotAllowed

**Comment by fafhrd91** [comment]
@DoumanAsh could you check this?

**Comment by DoumanAsh** [comment]
Yeah it seems to be trivial error, I'll fix it today after work

**Comment by DoumanAsh** [comment]
Actually it is so trivial that I fixed it right now, i'll merge it once tests are passed

**Comment by damody** [comment]
new problem
access-control-allow-origin is fixed,
but still no Response.
![image](https://user-images.githubusercontent.com/6639075/47474143-3ef09800-d848-11e8-89ba-c022d518dcb5.png)
