### ISSUE TITLE
Content-length header shouldn't be set for "204 No Content" responses

### ISSUE THREAD

**Issue by davechallis** [actix/actix-web#521]
Returning `HttpResponse::NoContent()` results in a response like:

    HTTP/1.1 204 No Content
    content-length: 0
    date: Wed, 26 Sep 2018 13:57:04 GMT

From the HTTP 1.1 spec at https://tools.ietf.org/html/rfc7230#section-3.3.2:

> A server MUST NOT send a Content-Length header field in any response with a status code of 1xx (Informational) or 204 (No Content).

**Comment by DoumanAsh** [comment]
@fafhrd91 We do set it automatically for all responses, right?
I guess we should make it conditional then if RFC states it as `MUST NOT`

**Comment by fafhrd91** [comment]
It is a bug
