### ISSUE TITLE
Cookie auth without cloning HttpRequest

### ISSUE THREAD

**Issue by avtomat2023** [actix/actix-web#522]
I tried a cookie auth using request body by `IdentityService` middleware, following [the example](https://github.com/actix/examples/blob/master/cookie-auth/src/main.rs).

- [Cargo.toml](https://gist.github.com/yoshrc/1726588b983595e205958ebef8931955)
- [main.rs](https://gist.github.com/yoshrc/6512f6b2f83d7e809a80920270f19e03)

The compilation fails.

```
error[E0621]: explicit lifetime required in the type of `req`
  --> src/main.rs:41:5
   |
39 |   fn login(req: &HttpRequest) -> FutureResponse<HttpResponse> {
   |            --- consider changing the type of `req` to `&'static actix_web::HttpRequest`
40 |       // https://actix.rs/api/actix-web/stable/actix_web/trait.HttpMessage.html#method.urlencoded
41 | /     Box::new(
42 | |         req.urlencoded::<LoginParameters>()
43 | |             .from_err()
44 | |             .and_then(move |params| {
...  |
48 | |             }),
49 | |     )
   | |_____^ lifetime `'static` required
```

That's because the request cannot be accessed in the closure of a Future. This problem can be avoided by [cloning the request](https://gist.github.com/yoshrc/a97492df33e8487e223edbcfdd6f67b3), but I don't want to make an unnecessary clone.

Is there a good way to make a cookie auth using request body, without cloning the request?

**Comment by fafhrd91** [comment]
you don't have choice, you have to clone request if you use it inside .and_then()

**Comment by DoumanAsh** [comment]
Just to add that cloning request is relatively cheap as you're mostly cloning `Rc` pointers

**Comment by avtomat2023** [comment]
@fafhrd91 @DoumanAsh

Thank you. But I don't think cloning HttpRequest is ignorable cost. `std::mem::size_of::<HttpRequest>()` returns `248`. This size seems to come from `ResourceInfo` of `HttpRequest`.

Is it inevitable to copy 248 bytes whenever I use `IdentityService`?

**Comment by fafhrd91** [comment]
you need to copy request if you want to use it with future combinators

**Comment by DoumanAsh** [comment]
@yoshrc this is limitation of current way futures do things, you need to avoid tying it to lifetimes as handler requires `'static` lifetime

I'm surprised though about size of `HttpRequest`, wonder if it is with alignment/padding
