### ISSUE TITLE
JSON Deserialization

### ISSUE THREAD

**Issue by Defman** [actix/actix-web#524]
When posting a [base64 encoded image(1MB)](https://gist.github.com/The-Defman/9ba7fc1fac7c10045d192f32f5a719c9) the deserialization fails every other time, with the error.
```
actix_web::pipeline: Error occured during request handling, status: 500 Internal Server Error internal error
```

```rust
#[derive(Serialize, Deserialize)]
struct Data {
  data: String,
}

fn json(data: Json<Data>) -> Result<HttpResponse, UploadError>

app.resource("/json", |r| {
    r.method(http::Method::POST).with_config(json, |cfg| {
        cfg.0.limit(2_097_152);
    })
})
```

**Comment by DoumanAsh** [comment]
@The-Defman hmmm out of curiosity, could you try to use plain serde with your data to see if it would fail too? 

We use `serde-json` to serialize/deserialize

**Comment by Defman** [comment]
How would I go about doing so? I would have to take the payload and fold it to a byte slice and use from slice, something like.

```rust
n test<S>(req: &HttpRequest<S>) -> Box<Future<Item=HttpResponse, Error=SomeError>> {
  req
    .payload()
    .from_err()
    .fold(BytesMut::with_capacity(2_097_152), move |mut body, chunk| {
        if (body.len() + chunk.len()) > 2_097_152 {
            Err(SomeError::BadError)
        } else {
            body.extend_from_slice(&chunk);
            Ok(body)
        }
    })
    .and_then(|body| Ok(serde_json::from_slice::<Data>(&body)?));
}
```

**Comment by DoumanAsh** [comment]
@The-Defman yes, as example.
Or you could write simple program that loads the same payload from file and tries to parse.

I can do it myself, but only after work later on.

**Comment by Defman** [comment]
```rust
extern crate serde_json;
#[macro_use] extern crate serde_derive;

#[derive(Deserialize)]
struct Data {
    data: String,
}

fn main() {
    for _ in 0..100 {
        let data: Data = match serde_json::from_str(include_str!("image.txt")) {
            Ok(data) => data,
            Err(err) => panic!(err)
        };
        println!("Data lenght is: {}", data.data.len());
    }
}
```
Ran it and got 100: Data lenght is: 1243564

**Comment by DoumanAsh** [comment]
Ok, thank you.

I'll need to try to test your example with actix-web to see what could be wrong

**Comment by Defman** [comment]
[Large payload](https://gist.githubusercontent.com/The-Defman/7632678569018bd31deb857b14d3262b/raw/9f817bf505452e9a252954f83b91a1a199148419/Large%2520payload) for reference.

**Comment by DoumanAsh** [comment]
Just for clarification: how do you perform upload?

**Comment by Defman** [comment]
Insomnia with
```json
{
    "data": "{% file 'base64-image.txt' %}"
}
```

```
* Preparing request to http://127.0.0.1:8000/json
* Using libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host 127.0.0.1: 0x7fc3f8db8350 [can pipeline]
* Re-using existing connection! (#98) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#98)
> POST /json HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: insomnia/6.0.2
> Content-Type: application/json
> Accept: */*
> Content-Length: 1243579
| (16 KB hidden)
| (16 KB hidden)
| ...
| (16 KB hidden)
| (14.4 KB hidden)
< HTTP/1.1 500 Internal Server Error
< content-length: 14
< date: Mon, 01 Oct 2018 09:00:16 GMT
* HTTP error before end of send, stop sending

* Received 14 B chunk
* Closing connection 98
```

**Comment by Defman** [comment]
For good measure, I tried curl which also failed at times
```sh
curl --request POST \
  --url http://127.0.0.1:8000/json \
  --header 'content-type: application/json' \
  --data-binary "@/payload.txt" \
```

**Comment by Defman** [comment]
[Backtrace](https://gist.github.com/The-Defman/f9d399fe20651a1bf2c251d3b3ad3921)

**Comment by DoumanAsh** [comment]
@The-Defman Just letting you know, I tried to post your file using curl and it seems working just fine. 
You mentioned:

>I tried curl which also failed at times

By at times do you mean that it doesn't fail always?

**Comment by Defman** [comment]
Yea it fails quite often, ~5 out of 21 requests.

**Comment by Defman** [comment]
I was taking the data and saving it to a file, just removed the file saving part and it works every time now? But it was not even getting to file saving part before?

**Comment by DoumanAsh** [comment]
If possible could you please try again and enable debug logs?

For example simply pull env_logger and set it up:

```
    ::std::env::set_var("RUST_LOG", "actix_web=debug");
    env_logger::init();
```

**Comment by Defman** [comment]
https://github.com/actix/actix-web/issues/524#issuecomment-425878580

**Comment by Defman** [comment]
Just tried to create a fileSaver actor and tried to save the data async, same error and still not consistent. 
```rust
impl Handler<Data> for FileSaver {
  type Result = Result<(), UploadError>;
  fn handle(&mut self, msg: Data, _: &mut Self::Context) -> Self::Result {
    let random_part = base64::encode(&thread_rng().gen::<[u8; 18]>());
    let path = format!("/Some/Location/{}.jpg", random_part);
    File::create(&path)?.write_all(&base64::decode(&msg.data)?)?;
    Ok(())
  }
}
```
```
DEBUG 2018-10-01T16:54:44Z: actix_web::server::h1: Error sending data: disconnected
```

**Comment by DoumanAsh** [comment]
```
DEBUG 2018-10-01T16:54:44Z: actix_web::server::h1: Error sending data: disconnected
```

Is not actually problem
It is just client closed connection because response's body could be sent I think.

It happens for me with curl all the time

btw, sorry that I missed backtrace I'll take a look at it as I cannot really reproduce it and not sure whether there is something wrong with client or server part

**Comment by Defman** [comment]
I can only reproduce it when saving the data to file, like so.
```rust
File::create(&path)?.write_all(&base64::decode(&msg.data)?)?;
```

**Comment by fafhrd91** [comment]
could you split this code into three different calls and check which part actually returns error. it might be file operation that fails

**Comment by Defman** [comment]
When it fails, it never makes it to the file operations... it fails before it even hits any of my code.

**Comment by Defman** [comment]
I have now tested with the following clients: Insomnia, curl, hyper and actix_web::client, and they all randomly fail.

**Comment by fafhrd91** [comment]
i can not reproduce. here is my code, i use your large payload file:
```rust
#[derive(Serialize, Deserialize)]
struct Data {
    data: String,
}

fn json(msg: Json<Data>) -> Result<HttpResponse> {
    let res = base64::decode(&msg.data);
    assert!(res.is_ok());
    Ok(HttpResponse::Ok().finish())
}
```

**Comment by DoumanAsh** [comment]
Yeah the same for me, I couldn't reproduce it and i'm not sure if there is anything wrong with actix-web server code. I probably will look around pipeline code tomorrow

**Comment by fafhrd91** [comment]
@The-Defman you said you can reproduce only with following code

```rust
File::create(&path)?.write_all(&base64::decode(&msg.data)?)?;
```

in this code you can get error from `File::create()` and from `Write::write_all()` and from `base64::decode()`. first two are not related to actix-web.

**Comment by Defman** [comment]
Well, heres some [code](https://gist.github.com/The-Defman/3bd980f69bdb44fea5b89e19dd3c7c68)... it is working, as long as my random part is not base64 encoded? For some reason I thought the 500 error was from actix default error handling and not my custom DataError enum.

It all boils down to some illegal character from base64 in my file name...
```
ERROR 2018-10-01T19:46:42Z: actix_web::pipeline: Error occured during request handling, status: 500 Internal Server Error IO failed: No such file or directory (os error 2)
DEBUG 2018-10-01T19:46:42Z: actix_web::pipeline: IO { err: Os { code: 2, kind: NotFound, message: "No such file or directory" } }
```

I did not get these error messages before, which is weird.

**Comment by Defman** [comment]
Thanks for all the help and sorry for wasting your time :(

The illegal character is "/" which is quite obvious.

**Comment by 264nm** [comment]
> ```
> DEBUG 2018-10-01T16:54:44Z: actix_web::server::h1: Error sending data: disconnected
> ```
> Is not actually problem
> It is just client closed connection because response's body could be sent I think.
> 
> It happens for me with curl all the time

Just want to concur that for a normal 200 status code response (plain text response and no json serialisation) I get that particular message when running via curl vs via a browser request... so if anybody else stumbles on this thread after seeing that message and suspecting something pathological just keep that in mind!
