### ISSUE TITLE
Testing routes with multiple extractors

### ISSUE THREAD

**Issue by adamtrilling** [actix/actix-web#527]
How does one test routes that have multiple extractors?

I've got the following stubbed-out handler:

```
pub fn create_user((_state, _json): (State<AppState>, Json<CreateUser>)) -> HttpResponse {
    HttpResponse::Ok().into()
}
```

I'd like to write the following test (which obviously won't pass with the route as written):

```
fn create_user_success_returns_201() {
        let new_user = CreateUser {
            name: "User1".to_owned(),
        };
        let resp = TestRequest::with_state(test_state())
            .header("content-type", "application/json")
            .set_payload(serde_json::to_string(&new_user).unwrap())
            .run(&create_user)
            .unwrap();
        assert_eq!(resp.status(), StatusCode::CREATED);
    }
```

When compiling, I get an error about:
```^^^ expected signature of `for<'r> fn(&'r actix_web::HttpRequest<AppState>) -> _` ``` when calling `.run(&create_user)`

The problem is, `run()` takes a function whose parameter is an `HttpRequest`, but I'm trying to pass that function a tuple because extractors. What do do?? I need both the `AppState` because it has a handle to the database my `CreateUser` is going to get dropped into.

**Comment by fafhrd91** [comment]
at the moment this is not possible. there are two options:

* use TestServer
* use TestRequest::execute(), and manually construct extractors

**Comment by fafhrd91** [comment]
should be possible in 1.0, i will update docs soon
