### ISSUE TITLE
Problem converting HttpRequest to ClientRequest

### ISSUE THREAD

**Issue by mfr-itr** [actix/actix-web#533]
I'm writing an http proxy. My current code is:
```rust
fn main() {
    server::new(|| {
        App::new().resource("/", |r| r.f(|req: &HttpRequest| {
            println!("{:?}", ClientRequestBuilder::from(req).finish().unwrap().uri());     // <----
               // convert Request to ClientRequest
                ClientRequestBuilder::from(req)
                    .finish()
                    .into_future()
                    .and_then(|r| r.send().map_err(|e| e.into()))
                    // convert ClientHttpResponse to HttpResponse
                    .map(|r| HttpResponseBuilder::from(&r).finish())
                    .map_err(|e| {
                        println!("{:?}", e);                                                // <---
                        e
                    }).responder()
        }))
    }).bind("localhost:8000")
    .unwrap()
    .run();
}
```
After running `http_proxy=localhost:8000 curl http://sametmax.com`, I get:
```
/
Connector(InvalidUrl)
```
I guess that's because the `.uri()` is `/` and not `http://sametmax.com/`. Am I missing something or is it a bug?

**Comment by DoumanAsh** [comment]
Does `uri()` return only `Uri` with path?

I'm not sure sure, @fafhrd91 do you remember is it intended to work like that?

**Comment by fafhrd91** [comment]
It contains full uri. But uri for Http1 contains only path

**Comment by DoumanAsh** [comment]
Hmm do we consider it a bug? It is a bit bad that there is inconsistency between HTTP1 and 2

**Comment by fafhrd91** [comment]
we dont, this just two different protocols. make them consistent means more work/allocations

**Comment by mfr-itr** [comment]
So what should I do? Ignore `ClientRequestBuilder::from` and do the conversion by hand?

Also, `ClientRequestBuilder::from` only does method and headers, not uri and body. Is that by design? If so, I'll have to do the conversion by hand...

**Comment by fafhrd91** [comment]
use from, it copies headers and then set proper url

**Comment by mfr-itr** [comment]
Is there a reason why it's not done? I don't see a use case where one would not want the URL.

The Body also have to be handled, btw
