### ISSUE TITLE
Add support for http client Authorization Bearer and Basic

### ISSUE THREAD

**Issue by driftingaway86** [actix/actix-web#535]
I have a use case that requires me to make a post request from my actix-web application to an api that has authorization bearer; I would assume there would also be a use case for basic auth as well. Can we get that support added to the client side of actix-web. Doesn't make sense to go to an external crate for this functionality.

Or can someone provide me with a working example for each case ? Current;y im using either hyper or reqwests for this functionality.

**Comment by DoumanAsh** [comment]
Currently we do not have it implemented, but it is not difficult to write it on your own(you can take a look at`reqwest` source code)

But PR to change it would be welcome 😄

**Comment by driftingaway86** [comment]
#540 
Added PR Change. Pending the normal stuff.

**Comment by crusty-dave** [comment]
I am not familiar with the process, when does this actually make it into nightly and then stable?

**Comment by fafhrd91** [comment]
fixed by #540

**Comment by Firstyear** [comment]
It would be good if there was documentation associated with the usage of these apis please

**Comment by driftingaway86** [comment]
@Firstyear 
Can get some examples added in on another PR or add them here if the usage isn't immediately clear, but you are correct documentation does need to be added to some extent.

**Comment by Firstyear** [comment]
Adding them in another PR would be sufficient, I'm happy to provide docs review.
