### ISSUE TITLE
Documentation needs to be updated for url dispatch and App::route

### ISSUE THREAD

**Issue by jrmiller82** [actix/actix-web#539]
https://actix.rs/docs/url-dispatch/

Leads someone to believe calling `.route()` is equivalent to calling `.resource()`, which is not true.

See issue  #537 for example of compiler puke and more detail.

**Comment by fafhrd91** [comment]
PR is welcomed

**Comment by jrmiller82** [comment]
If I can get around to it, I may. No promises as I'm slowly learning.

**Comment by eaydogan** [comment]
@fafhrd91 
I added PR about documentation update 17 days ago.

https://github.com/actix/actix-website/pull/46

**Comment by fafhrd91** [comment]
pr is merged
