### ISSUE TITLE
HEAD responses can contain body

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#54]
I find this library awesome, the API is much cleaner and easier to work with than other web frameworks which utilising async operations. My only blocking issue is the lack of support for ranges and RFC compilant HEAD responses. Former one is more like an inconvenience, but the latter one is more problematic since seemingly I can't work around it. 

HEAD requests are special since their responses will contain the "content-length", but body will always be empty. I can't override the content-length(framework calculates it for me, which is nice) but in this case it would be a must. Another workaround is preparing a body, then throwing it away is not efficient solution.

I'm not a seasoned developer so maybe I overlooked something, if this is the case can you point me out what I missed? Thanks!

**Comment by fafhrd91** [comment]
You can use [HttpRequest::range()](https://actix.github.io/actix-web/actix_web/struct.HttpRequest.html#method.range) for range. 
I am not sure what else framework can provide regarding ranges. Do you have any suggestions?

Regarding HEAD, I'll review head support later today.

**Comment by fafhrd91** [comment]
HEAD support is fixed in master. I will make new release later today or tomorrow

**Comment by fafhrd91** [comment]
fixed by 91c44a1cf1493a8ffd8a26f3f3c3013d55301d41

**Comment by ghost** [comment]
[HttpRequest::range()](https://actix.github.io/actix-web/actix_web/struct.HttpRequest.html#method.range) is a lot closer to what I'd like to see. Peak of convenience would be when I can pass this information to the fs::NamedFile Responder, so it will only return the requested range of bytes. But I can implement this for myself, so it's not really an issue.

Thank you for the quick reply and fix!

**Comment by fafhrd91** [comment]
I just don’t have enough time, but I am planing to add range support to named file

**Comment by ghost** [comment]
No problem. If it's on your roadmap maybe I can help you out with this. When I'll be satisfied with my solution I'll open a PR for this feature.

**Comment by fafhrd91** [comment]
PR would be great!

**Comment by fafhrd91** [comment]
I made new release with head requests fix

**Comment by ghost** [comment]
Thanks for the HEADs up! :) I'm switching back to stable.

Meanwhile I took a dive in the [RFC](https://tools.ietf.org/html/rfc7233), and looks like it's not an easy task. Now I have a working solution, but it's ugly and violates the rfc, so it needs some more work. If I'm progressing well with it, I'll open a ticket during the week and I'll keep you posted.
