### ISSUE TITLE
V0.7.12 actix-web::ws can not run in arm-linux

### ISSUE THREAD

**Issue by lygz5016** [actix/actix-web#545]
The run error message:

`thread 'main' panicked at 'could not initialize thread_rng: All entropy sources failed (permanently unavailable); cause: OS RNG not yet seeded (not ready yet); cause: Resource temporarily unavailable (os error 11)'`

Where thread_rng is used in the source code:
1.  src/ws/frame.rs  line: 329  `let mask = rand::random::<u32>();`
2.  src/ws/client.rs   line: 302 `let sec_key: [u8; 16] = rand::random();`

Only use ReadRng on my target(arm-unknown-linux-gnueabi):
`let mut rng = read::ReadRng::new(std::fs::File::open("/dev/urandom").unwrap());`

**Comment by fafhrd91** [comment]
i dont know how to fix this. 

@DoumanAsh any ideas?

**Comment by DoumanAsh** [comment]
@lygz5016 Are you use we cannot use at least [EntropyRng](https://docs.rs/rand/0.5.5/rand/rngs/struct.EntropyRng.html)?

Disregard that, I looked at source code for `ThreadRng` and it uses `EntropyRng` 

I feel like it is strange that it is not possible to use it on your system since it is still Linux with `/dev/urandom` I wonder if there is similar issue in `rand` crate

**Comment by DoumanAsh** [comment]
This PR might help with such issues https://github.com/rust-random/rand/pull/579

It would allow user to set own source of entropy.
I don't think we should get away from using `thread_rng`, but it is still questionable why it fails on arm linux.

**Comment by lygz5016** [comment]
@DoumanAsh  I tried to use [EntropyRng](https://docs.rs/rand/0.5.5/rand/rngs/struct.EntropyRng.html), but it still can't work.

The use of [OsRng](https://docs.rs/rand/0.5.5/rand/rngs/struct.OsRng.html) is blocked.

So I can only use `read::ReadRng::new(std::fs::File::open("/dev/urandom").unwrap());`

I don't think we should get away from using `thread_rng`, too.

**Comment by DoumanAsh** [comment]
I think it might be worth asking from `rand` guys about it.
Since your target is linux I'm surprised that EntropyRng fails...

**Comment by lygz5016** [comment]
This is a very strange question. I'm not sure if it's a system cause, and it could not initialize without an entropy source.

**Comment by DoumanAsh** [comment]
It would explain the OsRng problem, but EntropyRng is intended to work on common systems as guaranteed way to initialize random(when HW's random fails you)

In any case I would prefer to not move away from thread_rng itself, I'll try to check `rand` crate myself on my raspberry pi.

**Comment by fafhrd91** [comment]
@DoumanAsh can we do anything?

**Comment by DoumanAsh** [comment]
I think we cannot unless random's author will tell that `EntropyRng` cannot be used on arm platform.
Otherwise we could only do platform specific code as @lygz5016 suggested, but I don't like this idea

**Comment by fafhrd91** [comment]
@DoumanAsh thanks
