### ISSUE TITLE
actix-new v0.1.1 will not build in Windows Server 2012

### ISSUE THREAD

**Issue by crusty-dave** [actix/actix-web#546]
Not sure if anything can be done about this, but I figured that I should ask, it seems like rustls has issues with almost any older OS.

Does anyone know the minimal library version on which it will build?  I have Visual Studio 2017 installed, but I believe it is currently defaulting to an older library.

Note that I have no issues building on Windows 10 with Visual Studio 2017 installed.

> Compiling actix-net v0.1.1
> error[E0432]: unresolved import `tokio_rustls::ClientConfigExt`
>   --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:40:5
>    |
> 40 |     tokio_rustls::ClientConfigExt, webpki::DNSNameRef, webpki_roots,
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ClientConfigExt` in the root. Did you mean to use `ClientConfig`?
> 
> error[E0599]: no method named `connect_async` found for type `std::sync::Arc<rustls::ClientConfig>` in the current scope
>    --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:835:34
>     |
> 835 |                                 .connect_async(host, stream)
>     |                                  ^^^^^^^^^^^^^
> 
> error[E0277]: the size for values of type `dyn server::IoStream + std::marker::Send` cannot be known at compilation time
>    --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:848:49
>     |
> 848 |                                                 Box::new(stream),
>     |                                                 ^^^^^^^^ doesn't have a size known at compile-time
>     |
>     = help: the trait `std::marker::Sized` is not implemented for `dyn server::IoStream + std::marker::Send`
>     = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized>
>     = note: required by `<std::boxed::Box<T>>::new`
> 
> error[E0277]: the size for values of type `dyn server::IoStream + std::marker::Send` cannot be known at compilation time
>    --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:844:44
>     |
> 844 |                                         Ok(stream) => {
>     |                                            ^^^^^^ doesn't have a size known at compile-time
>     |
>     = help: the trait `std::marker::Sized` is not implemented for `dyn server::IoStream + std::marker::Send`
>     = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized>
>     = note: all local variables must have a statically known size
> 
> error[E0277]: the size for values of type `dyn server::IoStream + std::marker::Send` cannot be known at compilation time
>    --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:839:41
>     |
> 839 |                                         Err(e) => {
>     |                                         ^^^^^^ doesn't have a size known at compile-time
>     |
>     = help: the trait `std::marker::Sized` is not implemented for `dyn server::IoStream + std::marker::Send`
>     = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized>
>     = note: required by `serde::export::Err`
> 
> error[E0277]: the size for values of type `dyn server::IoStream + std::marker::Send` cannot be known at compilation time
>    --> c:\rust\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.12\src\client\connector.rs:844:41
>     |
> 844 |                                         Ok(stream) => {
>     |                                         ^^^^^^^^^^ doesn't have a size known at compile-time
>     |
>     = help: the trait `std::marker::Sized` is not implemented for `dyn server::IoStream + std::marker::Send`
>     = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized>
>     = note: required by `serde::export::Ok`
> 
> error: aborting due to 6 previous errors
> 
> Some errors occurred: E0277, E0432, E0599.
> For more information about an error, try `rustc --explain E0277`.
> error: Could not compile `actix-web`.
> 
> To learn more, run the command again with --verbose.
>

**Comment by fafhrd91** [comment]
could you try master?

**Comment by crusty-dave** [comment]
Apparently my Windows-10 build was using a stale Cargo.lock, after deleting that, it also failed.

Here is what I currently have, the following fails:

```
[features]
default = ["rusttls"]
rusttls = ["actix-web/rust-tls"]

[dependencies]
clap = "2.32.0"

lazy_static = "1.0.2"
chrono = "0.4"
uuid = "0.6"

#futures = "0.1"
futures = "0.1.24"

slog = "2.4.1"

env_logger = "0.5"

http = "0.1.7"

actix = "0.7.4"
actix-web = { version="0.7.7", features=["flate2-rust"], default-features = false }

rustls = "0.13.1"
#webpki-roots = "0.15.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.11.13"

```

However, the following builds:

```
[features]
default = ["rusttls"]
rusttls = ["actix-web/rust-tls"]

[dependencies]
clap = "2.32.0"

lazy_static = "1.0.2"
chrono = "0.4"
uuid = {version = "0.7.0", features = ["v4"]}

#futures = "0.1"
futures = "0.1.24"

slog = "2.4.1"

env_logger = "0.5"

http = "0.1.7"

actix = "=0.7.4"
actix-web = { version="=0.7.7", features=["flate2-rust"], default-features = false }

rustls = "=0.13.1"
#webpki-roots = "0.15.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.11.13"
```

This is building on Windows-10 and WSL Ubuntu 16, a co-worker was working on Windows Server 2012 and made these changes - I will update with that result once I have it,.

**Comment by crusty-dave** [comment]
The above built OK on Windows 2012 Server.  I will close this issue.  However, it seem like versions are very finicky, perhaps someone should open an issue specific to that if it is a real problem.
