### ISSUE TITLE
version 0.7.13 breaks serving static files from behind a DMZ firewall and a proxy

### ISSUE THREAD

**Issue by jvo203** [actix/actix-web#549]
Up until version 0.7.12 everything used to work very well. With the new version 0.7.13 it is impossible to serve static file resources when browser requests go through a DMZ firewall and then a proxy.

Error messages seen in the browser: Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
marchingsquares-isocontours.min.js:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)

When resources are served to the browser directly (without any DMZ/firewall/proxy) everything works OK. actix-web is used in the production server in the following radio-astronomy project:

https://github.com/jvo203/fits_web_ql

As this is a production environment there is no space for experimentation. We had to downgrade actix-web to the previous release 0.7.12 in order to keep things working in order. Amongst other things we use actix-web WebSockets to stream HEVC frames created in real-time with x265. Overall actix-web is extremely fast and the API is pleasant to work with.

Static resources are handled in a standard way:

.handler("/", fs::StaticFiles::new("htdocs").unwrap().index_file(index_file))

**Comment by DanielJoyce** [comment]
Its a bit of a PITA, but you could use got-bisect to find the bad commit.

**Comment by jvo203** [comment]
Thank you Daniel for a good suggestion. We'll give it a try. We've setup a small test project with actix-web in a local directory and have managed to replicate the issue.

**Comment by jvo203** [comment]
git-bisecting was fast as there were only two commits to test. The commit causing problems is

"HttpServer not sending streamed request body on HTTP/2 requests #544"

Our proxy uses HTTP 1.0 internally (HTTP 1.1 requests seem to be handled as HTTP 1.0). The above commit has special handling for HTTP_2, HTTP_11 but handling HTTP 1.0 seems to be broken by this commit.

**Comment by DoumanAsh** [comment]
Thanks for looking into it,
Could you please test my branch https://github.com/DoumanAsh/actix-web/tree/refactoring_server_output
It should retain original behavior

**Comment by jvo203** [comment]
Thank you. Unfortunately in the meantime we removed the (no longer needed) setting in the Apache http proxy that was downgrading HTTP 1.1 to 1.0. Hence the original problem cannot be reproduced anymore! I tried using curl --http1.0 with a direct connection to the actix-web test application but no problems were encountered. curl seems to have no problems with actix-web v0.7.13. But going from any browser through the Apache proxy with HTTP 1.1 -->1.0 definitely had a problem.

Anyway, your test branch "refactoring_server_output" works OK, no problems whatsoever (but the proxy no longer downgrades to HTTP 1.0!). Since this is a production server there is no scope for further experimentation with the proxy settings.

**Comment by bbigras** [comment]
> Could you please test my branch https://github.com/DoumanAsh/actix-web/tree/refactoring_server_output
It should retain original behavior

I had the same problem and the branch fixed it. I had "upstream sent invalid chunked response while reading upstream" errors with nginx acting as a reverse proxy with http2.
