### ISSUE TITLE
Unify HttpRequest/HttpResponse with ClientRequest/ClientResponse

### ISSUE THREAD

**Issue by felipenoris** [actix/actix-web#553]
I'm trying to write a simple reverse proxy with Actix, so I need to chain a HttpRequest to a client and wait for the response.

I noticed that there are separate structs `ClientRequest` and `ClientResponse` to drive a `Client`.

I would suggest to unify these structs, or implement `From`/`Into` traits for this kind of use-case.

**Comment by DoumanAsh** [comment]
Unification might not be simple, but there are already implementation of these traits.

`ClientRequest -> HttpRequestBuilder`
`ClientResponse -> HttpResponseBuilder`

Though they might need improvement as in past I needed to manually copy some [parts](https://github.com/DoumanAsh/actix-reverse-proxy/blob/master/src/proxy.rs#L9-L36)

**Comment by felipenoris** [comment]
@DoumanAsh Thank you! I'm working on a derivative of your repo https://github.com/felipenoris/actix-reverse-proxy .
