### ISSUE TITLE
Are we able to use logging macros?

### ISSUE THREAD

**Issue by DougB-Code** [actix/actix-web#555]
Is it possible to write custom log messages using the built-in logging middleware? It seems as if we should be able to use macros such as ``info!`` or ``error!`` but that use-case doesn't seem to be documented anywhere.

EDIT: Changing the RUST_LOG variable to just *info* allows the use of logging macros.

```
extern crate actix_web;
#[macro_use] extern crate log;
extern crate env_logger;
use actix_web::{http, server, App, Path, Responder};
use actix_web::middleware::Logger;

fn index(info: Path<(u32, String)>) -> impl Responder {

    info!("------ Index called -----");
    
    format!("Hello {}! id: {}", info.1, info.0)
}

fn main() {

    std::env::set_var("RUST_LOG", "info");
    env_logger::init();
    
    info!("---- This should show up ----");

    server::new( || App::new()
         .middleware(Logger::default())
         .middleware(Logger::new("%a %{User-Agent}i"))
        .route("/{id}/{name}/index.html", http::Method::GET, index))
        .bind("127.0.0.1:8000").unwrap()
        .run();

}
```

**Comment by DoumanAsh** [comment]
You only able to configure format for your messages. See API [docs](https://actix.rs/actix-web/actix_web/middleware/struct.Logger.html)
By default all messages are logged as [info](https://github.com/actix/actix-web/blob/master/src/middleware/logger.rs#L118)

But it is not difficult to write own logger

**Comment by DougB-Code** [comment]
I edited my comment above after I found a solution to enable logging via macros. If it'll be possible to show which module wrote to the log it should be sufficient.

**Comment by DoumanAsh** [comment]
I'm not familiar with using `RUST_LOG`, but you can take a look at module structure in source code.
It should be something like `actix_web::middleware::logger`

**Comment by DougB-Code** [comment]
I'll investigate that,

Thanks for the pointer, 

Edit: FYI

We are able to use all logging level macros and the output will show which module logged the statement as expected.

``DEBUG 2018-10-19T00:13:07Z: example::auth: in the signup function``

Example:

Log *actix_web* at info and *myapp* at debug level.

``std::env::set_var("RUST_LOG", "actix_web=info,myapp=debug");``
