### ISSUE TITLE
URL Rewriting / Virtual hosting support

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#56]

**Comment by wunki** [comment]
With virtual hosting support, do you mean routing for domains? If so, this is exactly something I need.

I'm a Rust novice, but with some mentoring and reviewing I would love to try to add this to Actix.

**Comment by fafhrd91** [comment]
i think this is two fold problem.

1. we have to decide how to do routing for domains
2. ability to change (rewrite) original url. for example, it would be helpful in case if we use actix app as a part of bigger application

i'll help with code and mentoring

**Comment by wunki** [comment]
On the first point, maybe something like `App::with_domain("foo.example.com")` and then you can add routes as usual?

I'm not sure I follow what you mean about the ability to change original url.

What would also be nice, is that for the server you can bind multiple SSL builders which will be server depending on the domain used.

**Comment by fafhrd91** [comment]
Let’s add `App::filter()` similar to `Route::filter()` then we can reuse predicates and domain could be just new type of predicate.

I don’t think it is possible to use different ssl connectors for one port and for different port you already can specify different ssl builders

**Comment by fafhrd91** [comment]
By changing original url, I mean ability to modify request path befor route matching

**Comment by fafhrd91** [comment]
Added [App::filter()](https://actix.rs/actix-web/actix_web/struct.App.html#method.filter), it is possible to use different applications for different hosts.

**Comment by wunki** [comment]
Thank you soo much! I love the work you are doing, let me know if there is anything else I can do.

**Comment by leonbreedt** [comment]
@fafhrd91 Isn't (2) already possible with ability to mutate match info and request URI in-place? 

I ask since I tweaked your NormalizePath middleware and was able to strip a common prefix from the URL path then routed successfully on the updated URL path.

**Comment by robjtede** [comment]
The Host guard effectively provides this.

Further discussion should be in a new issue w.r.t. newer Actix Web versions
