### ISSUE TITLE
Extremely slow StaticFiles peformance

### ISSUE THREAD

**Issue by transkatgirl** [actix/actix-web#560]
When connecting to a HTTP server built with actix-web, if the server uses the builtin fs::StaticFiles method for serving content, there is a severe performance impact in newer versions of actix-web (> 0.7.8).

Here's a simple example server to show the issue:
```rust
extern crate actix_web;
use actix_web::{fs::StaticFiles, server, App};

fn main() {
    server::new(|| {
        App::new()
	        .handler("/",StaticFiles::new("./static/").unwrap().index_file("index.html"))
    }).bind("[::]:8080")
        .unwrap()
        .run();
}
```
(Note that the "index.html" file used for testing is 1024 bytes. When serving large files, the performance impact is much lower.)

Performance on actix-web v0.7.13: 
```
Running 10s test @ http://localhost:8080/index.html
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    41.77ms    8.92ms  47.70ms   95.54%
    Req/Sec   383.49     41.16   540.00     69.00%
  7643 requests in 10.01s, 9.37MB read
Requests/sec:    763.67
Transfer/sec:      0.94MB
```

Performance on actix-web v0.7.8: 
```
Running 10s test @ http://localhost:8080/index.html
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.92ms    0.89ms  28.22ms   91.59%
    Req/Sec    19.48k     1.13k   22.51k    71.50%
  387887 requests in 10.01s, 474.98MB read
Requests/sec:  38765.56
Transfer/sec:     47.47MB
```

**Comment by DoumanAsh** [comment]
Hm... interesting, I don't think there should such serious change to StaticFiles.
Thanks for noticing it

**Comment by fafhrd91** [comment]
I enabled timeouts by default in latest versions of actix-web. that might affect default performance, but it should not be that dramatic

**Comment by transkatgirl** [comment]
After a bit of testing, it looks like ChunkedReadFile is what's slowing down StaticFiles so much.


Also, something completely unrelated I noticed: Why is ChunkedReadFile public, but all of it's fields are private? Making it's fields public too would probably be a good idea.

**Comment by DoumanAsh** [comment]
Just a note: there are no significant changes to the way we read static files.

@kittyhacker101 So I'm curious do you see a similar problem with your regular handlers?

**Comment by transkatgirl** [comment]
Well, I haven't had any issues with normal streamed handlers, just with handlers using ChunkedReadFile (like StaticFiles).

**Comment by DoumanAsh** [comment]
@fafhrd91 Do you remember were there any changes recently to the way actix-web sends out streaming/chunked bodies?

I heard from another fellow that there was some problems with timing when responding with chunked responses

**Comment by transkatgirl** [comment]
@DoumanAsh It looks like commit [c674ea9](https://github.com/actix/actix-web/commit/c674ea912691d86379d610a4794a50cef4b2feac) is causing this problem.

Performance before the commit:
```
Running 10s test @ http://localhost:8080/index.html
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.85ms  675.10us  17.54ms   91.13%
    Req/Sec    19.95k     0.90k   22.48k    68.00%
  396994 requests in 10.00s, 486.51MB read
Requests/sec:  39687.22
Transfer/sec:     48.64MB
```

Performance after the commit:
```
Running 10s test @ http://localhost:8080/index.html
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    41.31ms    9.71ms  46.80ms   94.67%
    Req/Sec   387.95     44.02   535.00     64.00%
  7726 requests in 10.00s, 9.48MB read
Requests/sec:    772.43
Transfer/sec:      0.95MB
```

**Comment by fafhrd91** [comment]
added nodelay in master, could you test again.
