### ISSUE TITLE
Unable to use stable clippy with actix-web

### ISSUE THREAD

**Issue by stanislav-tkach** [actix/actix-web#561]
`clippy::lint_name` syntax is experimental, so it is impossible to use stable clippy if `actix-web` is a dependency.

**Comment by DoumanAsh** [comment]
should we wait for clippy to stabilize it then?
Or is there a way to work it around without losing anything?

**Comment by stanislav-tkach** [comment]
@DoumanAsh If I'm not missing something "old" syntax works well with both stable and nightly clippy.
