### ISSUE TITLE
does not work with flutter (websocket)

### ISSUE THREAD

**Issue by pythoneer** [actix/actix-web#567]
I have a webserver (actix_web) that i want a mobile application to communicate with. I choose flutter but having trouble to get a websocket connection going. I can connect from the flutter side and it looks like everything is working without any problems but immediately after the websocket actor and my `StreamHandler` is `started`  the `StreamHandler` and websocket actor are `finished` and `stopped` without an error or a close message and of course i cannot send any message from the flutter client.

I have no problems to connect from js (a simple website) or a python client to my actix webserver but i just can't get the flutter client to work. One could immediately guess this is the fault of the flutter client but i can connect to "ws://echo.websocket.org' and to a python websocket server without problems from the flutter client.

I have created a [repository](https://github.com/pythoneer/flutter_actix_websocket) with all the examples (simple echo servers with clients [adjust the ip's]) and all combinations for clients and servers are working except Flutter + actix_web   

[i also opened an issue for flutter](https://github.com/dart-lang/http/issues/1616)

EDIT: i also added a pure dart version with the same behavior but without the need of all the flutter and mobile stuff in the [`raw_dart`](https://github.com/pythoneer/flutter_actix_websocket/tree/master/raw_dart) folder. just `dart main.dart` should be enough with dart installed and no need for android studio/xcode and or mobile devices / emulators.

**Comment by pythoneer** [comment]
I also added some [wireshark](https://github.com/pythoneer/flutter_actix_websocket/tree/master/wireshark) captures. The switching protocol is working (i guess that's why we see on the server side that the websocket is established)  but after that there is a TCP RST

**Comment by pythoneer** [comment]
I looked a bit through the captures but unfortunately i have not much detail knowledge of the websocket negotiation scheme. But from the first look i would say that the dart/flutter client is requesting an `upgrade` with the `sec-websocket-extension: permessage-deflate`. The python server is answering with a `switching protocols` AND `sec-websocket-extension: permessage-deflate` but actix is not and thus the dart/flutter client sends a TCP-FIN because it insist on this and end the negotiation because actix does not support this?

**Comment by fafhrd91** [comment]
per mession protocol is not supported

**Comment by pythoneer** [comment]
Are there any plans to support this? I have no idea how often this is used in the wild.

**Comment by pythoneer** [comment]
I deactivated the compression but i still can't establish a connection unfortunately i don't really know the exact negotiation scheme but from the [new capture](https://github.com/pythoneer/flutter_actix_websocket/blob/master/wireshark/actix_server_dart_client_no_compression.pcapng) it still looks like the negotiation fails but i cannot see why.

**Comment by pythoneer** [comment]
Yesterday i wrote a little websocket test implementation to mimic the negotiation that actix is doing (exact same header information, same order, casing etc). I think i am close to being byte identical. The "Upgrade" is working but Actix is suddenly sending a TCP RST and i believe it is related to this issue https://github.com/actix/actix-web/issues/569 ... i try to downgrade to the same version that helped in that case and report back. i think there is something fishy with the TCP communication. 

EDIT:
I tried to use 0.7.8 but it didn't help.

**Comment by pythoneer** [comment]
I implemented i little test server in java [here](https://github.com/pythoneer/flutter_actix_websocket/blob/master/java_test_server/Main.java) just to check what the dart client is actually sending and to have a way to mimic the header actix is sending for the negotiation. Its just running without any problem and i get the bytes i expect and can see the messages i send from the [dart test client](https://github.com/pythoneer/flutter_actix_websocket/blob/master/raw_dart/main.dart). i also captured it with [wireshark](https://github.com/pythoneer/flutter_actix_websocket/blob/master/wireshark/test_server_2_dart_client.pcapng) and it looks pretty normal and really close to the one i captured with the [dart client and actix](https://github.com/pythoneer/flutter_actix_websocket/blob/master/wireshark/actix_server_dart_client_no_compression.pcapng) (it mostly differs in cases of the ports i think) but actix is just firing a FIN [packet No. 8] and a RST [packet No. 10] just after the negotiation is successfully made. The client didn't even send actual messages (which may be wrongly encoded) it has only enough time to ACK the `Switching Protocols` which looks fine from all i can tell (i did not investigated it very closely)  

I was thinking about also writing a websocket client to test if i can reproduce the behavior the dart client is causing. But the problem is that the dart client is not sending very much before actix is closing the connection. Its just opening the connection, sends an `HTTP Upgrade` actix is acknowledging and sends a `Switching Protocols` back, the dart client acknowledge it and actix is closing the connection. The only thing the client could do wrong here is sending a wrong acknowledge packet? I have no idea and i don't think writing a also websocket client is helping much – can someone hint me to some places in the actix codebase to debug this?

**Comment by fafhrd91** [comment]
did you try Actix-web 0.7.5?

**Comment by pythoneer** [comment]
not yet, but i can do so – give me a second and i report back.

**Comment by pythoneer** [comment]
same Problem and the wireshark capture looks very much the same

**Comment by pythoneer** [comment]
I need to go now, is there anything else i can provide or prepare for tomorrow? I tested this on different machines (work and home pc both with arch linux) and from an android phone and an iOS IPad. It is behaving the same way as the [raw dart](https://github.com/pythoneer/flutter_actix_websocket/blob/master/raw_dart/main.dart) test client. which is captured [here](https://github.com/pythoneer/flutter_actix_websocket/blob/master/wireshark/actix_server_dart_client_no_compression.pcapng)

**Comment by fafhrd91** [comment]
fixed in master.

dart client sends "content-length" header in request, and that is the problem.

**Comment by pythoneer** [comment]
Nice find. I somehow completely missed that header. Is sending "content-length" the "right" behavior for a client in that case? Couldn't  find much about it but it sound reasonable for a server to close the connection after the client has send enough bytes to match "content-length". But most server seem to "ignore" it if closing is even the right thing to do in the first place because i couldn't find any sort of "requirement" to close a connection after a server received "enough" bytes – but i guess "upgrades" handles that differently either way i couldn't really find anything to support or dismiss any of my assumptions. I am just asking weather i could close the issue on the dart side because it is the "right but unusual" behavior.

**Comment by fafhrd91** [comment]
Browsers do no send content-length. But I don’t remember which is right behavior

**Comment by pythoneer** [comment]
I read a little bit in the [RFC 7230](https://tools.ietf.org/html/rfc7230) and  [section-6.3](https://tools.ietf.org/html/rfc7230#section-6.3) talks about that HTTP/1.1 connections should be persistent by default, so closing after the server has read "content-length" bytes should be "wrong" in HTTP/1.1 . But its also stated in [section-3.3.2](https://tools.ietf.org/html/rfc7230#section-3.3.2) 

> A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.

But its only a "SHOULD NOT" and not a "MUST NOT" as in [rfc2119](https://tools.ietf.org/html/rfc2119) so it seams not to be wrong to send "content-length" but its not recommended.

**Comment by fafhrd91** [comment]
I wrote two implementations of ws server, dart is first client that does it. But in general I do t care much it is fixed
