### ISSUE TITLE
StaticFiles handler will not invoke default_resource on 404

### ISSUE THREAD

**Issue by DoumanAsh** [actix/actix-web#57]
When using `fs::StaticFiles::new(".", false)` default resource will not be called upon hitting 404.

Presumably because we only in handler for non-default resource

**Comment by fafhrd91** [comment]
this is not possible at the moment.

`default_resource` get invoked only if router can not find matching route

**Comment by DoumanAsh** [comment]
Yes, but it either should be somehow refactored or maybe StaticFiles should have a way to specify 404 handler?

**Comment by fafhrd91** [comment]
Yes, I’ve been thinking about custom 404 handler too

**Comment by fafhrd91** [comment]
Would you provide PR?

**Comment by DoumanAsh** [comment]
Yep, I could do it though maybe closer to weekend (doubt anyone else would notice this problem).

**Comment by fafhrd91** [comment]
Great!
