### ISSUE TITLE
Activate CORS middleware on a staticfile handler

### ISSUE THREAD

**Issue by rjanvier** [actix/actix-web#576]
Since `StaticFile` must be registered with `App::handler()` it seems impossible to make it work with the full featured CORS middleware (by "full featured" I mean the one that handle the 'OPTION' preflight)

I have tried this, obviously without success
```rust
let static_file_app = App::new()
            .prefix("static_content")
            .handler("data", fs::StaticFiles::new("mydir").unwrap())
            .configure(|app| {
                Cors::for_app(app).allowed_origin(client_url.as_str()).max_age(3600).register()
 }).boxed();
```

Does anyone ever succeed to manage something like this?
thanks.

**Comment by fafhrd91** [comment]
this should work in 1.0
