### ISSUE TITLE
 StaticFiles::index_file() redirects rather than just serving.

### ISSUE THREAD

**Issue by JadedBlueEyes** [actix/actix-web#579]
when using  StaticFiles::index_file(), ratedr than serving the specified index file, it redirects to it.
i have a program that is a static file server.
```rust
// hyper-serve by DerpMarine

// extern crate mime;
extern crate actix;
extern crate actix_web;
extern crate env_logger;

use actix_web::{fs, middleware, server, App};

fn main() {
    ::std::env::set_var("RUST_LOG", "actix_web=info");
    ::std::env::set_var("RUST_BACKTRACE", "0");
    env_logger::init();

    let sys = actix::System::new("static_index");

    server::new(|| {
        App::new()
	        // enable logger
	        .middleware(middleware::Logger::default())
	        .handler(
                "/",
                fs::StaticFiles::new("./").unwrap().index_file("index.html")
            )
    }).bind("127.0.0.1:8080")
        .expect("Can not start server on given IP/Port")
        .start();

    println!("Started http server: 127.0.0.1:8080");
    let _ = sys.run();
}
```
however, when i run it in a directory of static files and go to `/`, i get redirected to `index.html`. The code for this is [here](https://github.com/actix/actix-web/blob/master/src/fs.rs#L727). This code could be easily replaced with something like this from [`rusty-web-server`](https://github.com/phideg/rusty-web-server/blob/master/src/main.rs#L36).

```rust
if request_path.ends_with('/') {
     path.push("index.html");
}
```

This is [already a todo](https://github.com/actix/actix-web/blob/master/src/fs.rs#L749), but the sooner the better.

**Comment by DoumanAsh** [comment]
Duplicate of #557

**Comment by JadedBlueEyes** [comment]
It’s not a duplicate of #579, it is #579!

**Comment by JadedBlueEyes** [comment]
do you mean 
https://github.com/actix/actix-web/issues/557?

**Comment by DoumanAsh** [comment]
Yes
