### ISSUE TITLE
can official document be made to epub format?

### ISSUE THREAD

**Issue by aohan237** [actix/actix-web#585]
不知道能否提供可以下载离线阅读的epub 文档。

**Comment by DoumanAsh** [comment]
今で無理

P.s. I do not know chinese so here you go with japense 😄

**Comment by aohan237** [comment]
sorry actix-web has an official chinese document...
and i thought author may be chinese...

**Comment by DoumanAsh** [comment]
No problem, I think it was one of contributors who made chinese documentation
