### ISSUE TITLE
Re-export Server from actix_net

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#586]
To store the result of server::new(...).start() one have to import actix_net as server is private to actix_web.
Please re-export the server (or maybe the whole actix_net). 

(As I'm in early dev phase and i'm using the latest version from all (most) of the crates (version="*"), but for actix_net I have to find/update the exact version all the time.)

```
struct Foo { addr:Addr<Server> };
let f = Foo{addr: server::new(move || {...}).start()}; // fails and has no public type in actix_web to store.
```

**Comment by fafhrd91** [comment]
I am not sure this is good idea at the moment. actix-net is new and api will change. We can re-export server in 0.8 version

**Comment by ghost** [comment]
When choosing a solution, if actix_net is kind of "private" to the actix_web crate, please make sure to provide some wrapper type to handle the case above without explicitly depending on actix_net.
Also please note that some other types are already (re)exported from actix_net.

**Comment by fafhrd91** [comment]
just depend directly on actix-net
