### ISSUE TITLE
async resource methods with HttpRequest<AppState> is not documented

### ISSUE THREAD

**Issue by Firstyear** [actix/actix-web#588]
Attempting to use:

```
.resource("/search", |r| r.method(http::Method::POST).a(search))

error[E0621]: explicit lifetime required in the type of `req`
   --> src/main.rs:110:10
    |
75  | fn search(req: &HttpRequest<AppState>) -> Box<Future<Item = HttpResponse, Error = Error>> {
    |                ---------------------- help: add explicit lifetime `'static` to the type of `req`: `&'static actix_web::HttpRequest<AppState>`
...

```

This fails, but I'm quite certain it's not a bug in the framework, but a lack of documentation explaining correct usage of async with HttpRequest with an <AppState>. There are no examples of this in actix-examples (I have opened a bug there for a complete example to be added), but I can also see that there is very little in the way of documentation and examples on the actix Resource / Route types around the usage of  these types in complex scenarios (everything uses simple path extraction).

Thanks,

**Comment by maur1th** [comment]
I've been struggling with the same issue. Found no information that could help in examples, API docs or website. Did you find a workaround?

**Comment by Firstyear** [comment]
See the following PR where I got some traction on this topic. https://github.com/actix/examples/pull/63

**Comment by fafhrd91** [comment]
`.a()` does not exist in 1.0 and replaced with `.to_async()`
