### ISSUE TITLE
Difference between client and ClientRequest?

### ISSUE THREAD

**Issue by hbowden** [actix/actix-web#589]
Whats the difference between client and ClientRequest? Looking at the example in the docs https://actix.rs/api/actix-web/stable/actix_web/client/index.html and https://actix.rs/api/actix-web/stable/actix_web/client/struct.ClientRequest.html they look the same. So why is there both client and ClientRequest? and why would I use one over the other?

**Comment by DoumanAsh** [comment]
`client` is module where where we store `ClientRequest`, they only have the same documentation for example. They are not the same
