### ISSUE TITLE
System is not running or SpawnError { is_shutdown: true }

### ISSUE THREAD

**Issue by theredfish** [actix/actix-web#593]
Hello,

I'm getting different errors with Actix and Actix-web. Here the code to reproduce the errors (just update `&HttpRequest` by `HttpRequest` when necessary) :

```
extern crate actix;
extern crate actix_web;

use actix_web::{server, App, HttpRequest, HttpResponse, Result};
use actix_web::http::StatusCode;

fn welcome(_req: &HttpRequest) -> Result<HttpResponse> {
    println!("welcome");

    Ok(HttpResponse::build(StatusCode::OK).body("Welcome"))
}

fn main() {
    let sys = actix::System::new("basic-example");

    server::new(move || {
        App::new()
            .resource("/welcome", |r| r.f(welcome))
    }).workers(1)
    .bind(("127.0.0.1", 8080))
    .expect("Cannot bind listening port")
    .shutdown_timeout(0)
    .start();

    println!("Starting http server: 127.0.0.1:8080");
    let _ = sys.run();
}
```
### Error 1
`thread 'arbiter:501bf30e-568c-4988-bb4c-94fe6ae33c9d:actix-net-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:945:5`

Versions : 
actix = "0.7"
actix-web = "0.7"

Backtrace : [actix-web-0.7-backtrace.txt](https://github.com/actix/actix-web/files/2594802/actix-web-0.7-backtrace.txt)

### Error 2 (could be related to the version of actix, so not really an error?)
`thread 'main' panicked at 'System is not running', /home/theredfish/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.8/src/arbiter.rs:151:21`

Versions : 
actix = "0.6"
actix-web = "0.6"

Backtrace  : [actix-web-0.6-backtrace.txt](https://github.com/actix/actix-web/files/2594818/actix-web-0.6-backtrace.txt)

### Working example
Versions :
actix = "0.5"
actix-web = "0.6"

I would like to use the latest version (0.7), could you help me with these errors?

**Comment by DoumanAsh** [comment]
@theredfish I think Error 2 is due to mismatch of actix and actix-web version.
As for Error 1, I'm not sure why it goes this way, I'm curious if `server.run()` would fix it or not

**Comment by DoumanAsh** [comment]
@theredfish I just tried to reproduce error in first case, but cannot. Be sure to run `cargo update` and try again.There should be no problem

**Comment by theredfish** [comment]
Hello @DoumanAsh ,
I run `rustup update` but not `cargo update` :)

Issue solved, thank you!
