### ISSUE TITLE
can you  add actix::client support SSL?

### ISSUE THREAD

**Issue by aohan237** [actix/actix-web#595]
when use https,it shows:
Connector(SslIsNotSupported)
Connector(SslIsNotSupported)

but if i use hyper:client as an alternative, the error transfer is much more difficult.
because the document isn't that clear for transfering hyper::Error to actix_web::Error,which is critical for impl responder

**Comment by DoumanAsh** [comment]
Enable one of SSL features(they are disabled by default)

https://github.com/actix/actix-web/blob/master/Cargo.toml#L34-L44

**Comment by aohan237** [comment]
how to enable it? write all the things in actix_web cargo.toml?? @DoumanAsh

**Comment by aohan237** [comment]
ok . just write actix-web = { version="0.7.14", features=["ssl"] } in cargo.toml . thanks

**Comment by marccarre** [comment]
Just got bitten by `Err(Connect(SslIsNotSupported))` too 😐. For posterity, and until this makes it to the documentation [1], please try the following (a.k.a. "[_enabling the SSL/TLS feature_](https://github.com/actix/actix-web/blob/6e8ff5c905025c482303bb893032723a2bd4eb1d/Cargo.toml#L18)").

[1]: I am willing to open a PR to improve this. Where would you like this documented exactly?

----
In your `Cargo.toml`:

- Using [`rustls`](https://crates.io/crates/rustls):

  ```toml
  [dependencies]
  actix-rt = "1.1.1"
  actix-web = { version = "3.0.0-alpha.2", features=["rustls"] }
  rustls = "0.17.0"
  ```

- Using [`openssl`](https://crates.io/crates/openssl):

  ```toml
  [dependencies]
  actix-rt = "1.1.1"
  actix-web = { version = "3.0.0-alpha.2", features=["openssl"] }
  openssl = "0.10.29"
  ```

----
In your `main.rs`:

```rust
use actix_web::client::Client;

#[actix_rt::main]
async fn main() {
    let client = Client::default();

    // Create request builder and send request
    let response = client
        .get("https://www.rust-lang.org") // <--- notice the "s" in "https://..."
        .header("User-Agent", "Actix-web")
        .send()
        .await; // <- Send http request

    println!("Response: {:?}", response);
}
```

----
```console
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/rust-http-playground`
Response: Ok(
ClientResponse HTTP/2.0 200 OK
  headers:
    "strict-transport-security": "max-age=63072000"
    "x-amz-cf-id": "6gculLlBr5lYOjyFkFEErQpKKSY7w2xC70IvsL3ytGEk5HJoJMEMlQ=="
    "x-cache": "Miss from cloudfront"
    "x-xss-protection": "1; mode=block"
    "x-content-type-options": "nosniff"
    "via": "1.1 vegur, 1.1 77ffb7fa0ceed0e909a8f69baef40302.cloudfront.net (CloudFront)"
    "x-amz-cf-pop": "NRT20-C4"
    "content-security-policy": "default-src 'self'; frame-ancestors 'self'; img-src 'self' avatars.githubusercontent.com; frame-src 'self' player.vimeo.com"
    "content-length": "19220"
    "referrer-policy": "no-referrer, strict-origin-when-cross-origin"
    "vary": "Accept-Encoding"
    "server": "Rocket"
    "content-type": "text/html; charset=utf-8"
    "date": "Fri, 15 May 2020 07:32:08 GMT"
)
```
