### ISSUE TITLE
trying to create and API example with postgree

### ISSUE THREAD

**Issue by spielcrypto** [actix/actix-web#596]
Hello I working in an API example with actix_web, diesel and postgree based in the example https://github.com/actix/examples/tree/master/diesel but when I try to write the index function:

```rust
/// State with DbEx
struct AppState {
    db: Addr<DbExecutor>,
}

/// Async request handler
fn index((person, state): (Path<CreatePerson>, State<AppState>)) -> FutureResponse<HttpResponse> {
    state
        .db
        .send(CreatePerson {
            name: person.name,
            rich: person.rich,
            super_power: person.super_power,
            genius: person.genius,
        })
        .from_err()
        .and_then(|res| match res {
            Ok(person) => Ok(HttpResponse::Ok().json(person)),
            Err(_) => Ok(HttpResponse::InternalServerError().into()),
        })
        .responder()
}
```
I get error: 
```
no method named `from_err` found for type `actix::prelude::Request<listing_people_api_actix::db::DbExecutor, listing_people_api_actix::enpoints::people::model::CreatePerson>
```
The repository is https://github.com/dancespiele/listing_people_api_actix

I'm junior with rust :)

**Comment by DoumanAsh** [comment]
I think it would be better to ask such questions on our [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

The problem is that for some reason it cannot find `from_error` for result of `send`, check that you have imported `Future` trait.

**Comment by spielcrypto** [comment]
you right I have to import Future, thank you ;)
The next time I will ask in gitter.
