### ISSUE TITLE
extractor::QueryConfig is not exposed.

### ISSUE THREAD

**Issue by garyhai** [actix/actix-web#597]
rror[E0603]: module `extractor` is private
  --> src/lib.rs:23:72
   |
23 |     Error, FromRequest, HttpMessage, HttpRequest, HttpResponse, Query, extractor::QueryConfig,
   |                                                                        ^^^^^^^^^^^^^^^^^^^^^^

Query::<AsrParams>::from_request(&req, &QueryConfig::default())

**Comment by DoumanAsh** [comment]
I'm not sure why you need to use `QueryConfig` directly? You could use `Query` extractor itself.

But `QueryConfig` itself should be re-exported for user to use.
Can you please make PR for it?
It should be re-exported in the same way as other configs (e.g. `actix_web::dev::FormConfig`)

**Comment by garyhai** [comment]
In short, need the state in req.

**Comment by DoumanAsh** [comment]
@garyhai you can use together tuple `(State<T>, Query<T>)`
