### ISSUE TITLE
Json extractors don't disclose what went wrong in deserialise

### ISSUE THREAD

**Issue by Firstyear** [actix/actix-web#605]
When a json extractor is deserialising, no errors are returned about what went wrong. 

```
> curl -S --header "Content-Type: application/json" --request POST --data '{"name":"xyz"}}'  http://127.0.0.1:8080/add2
> 

```

For the API consumer, the error message should be returned why their json failed. This is important as not all consumers of an API have access to the server logs like:

```
 WARN 2018-11-28T00:04:05Z: actix_web::pipeline: Error occurred during request handling: Json deserialize error: trailing characters at line 1 column 15
 INFO 2018-11-28T00:04:05Z: actix_web::middleware::logger: 127.0.0.1:47942 "POST /add2 HTTP/1.1" 400 0 "-" "curl/7.60.0" 0.000585
 WARN 2018-11-28T00:04:12Z: actix_web::pipeline: Error occurred during request handling: Json deserialize error: expected `,` or `}` at line 1 column 14
 INFO 2018-11-28T00:04:12Z: actix_web::middleware::logger: 127.0.0.1:47944 "POST /add2 HTTP/1.1" 400 0 "-" "curl/7.60.0" 0.000332
```

Expected result:

```
> curl -S --header "Content-Type: application/json" --request POST --data '{"name":"xyz"}}'  http://127.0.0.1:8080/add2
Error occurred during request handling: Json deserialize error: expected `,` or `}` at line 1 column 14
> 
```

**Comment by fafhrd91** [comment]
Actix-web just prints serde error, it is up to serde to provide proper error

**Comment by Firstyear** [comment]
I'm sorry, this isn't my point. The point is you send the error to the middleware logger, but you don't construct a meaningful httpresponse to the caller. They just see "nothing" and can't understand what went wrong in there request.

Serde is fine, it's about sending the response to the caller.

Please reopen this issue because I think it's different to what you just state.

**Comment by fafhrd91** [comment]
Actix-web does not send error back to the peer as it can have security implications

**Comment by Firstyear** [comment]
Then can this be a configuration parameter which can be optionally enabled? There are not *always* security risks of disclosing why the request failed because of invalid input.

**Comment by fafhrd91** [comment]
It is possible already for json

**Comment by Firstyear** [comment]
Is there documentation or examples of this usage?  I'm trying to ask questions and improve this project to make it more accessible and usable to developers and I'd really appreciate more detailed answers about this rather than short answers and quick closing of issues please.

**Comment by fafhrd91** [comment]
Api docs 
https://actix.rs/actix-web/actix_web/dev/struct.JsonConfig.html

**Comment by Firstyear** [comment]
I'm sorry, but this is basically undocumented. The example you have in the top of page should be part of the JsonConfig section. There should probably be an example usage in actix-examples too (But I may add this now to diesel). 

So please re-open this as an request to improve the documentation because today this was "not able" to be found.

**Comment by fafhrd91** [comment]
You are welcome to provide PR for docs

**Comment by Firstyear** [comment]
I will provide a PR in the near future. I have a reasonable rest based actix application now, and have a list of things that I think need improving documentation wise. I would prefer if the actix team were able to do this, but if I can get the time I'll do it.
