### ISSUE TITLE
Error types don't return reason to the client.

### ISSUE THREAD

**Issue by Firstyear** [actix/actix-web#606]
Use of error::Error types, when setting a message into the error this is not returned to the client as part of the HttpResponse.

``` 
           .resource("/add2", |r| {
                r.method(http::Method::POST)
                    .with_async_config(add2, |(json_cfg, )| {
                        json_cfg.0.limit(MAX_SIZE) // <- limit size of the payload
                            .error_handler(|err, _req| {  // <- create custom error response
                                error::ErrorBadRequest(format!("Json parse failed: {:?}", err)).into()
                            });
                    })
            })

> curl -v -S --header "Content-Type: application/json" --request POST --data '{"name":"xyz""}'  http://127.0.0.1:8080/add2
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /add2 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 15
> 
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 400 Bad Request
< content-length: 0
< date: Wed, 28 Nov 2018 23:04:29 GMT
< 
* Connection #0 to host 127.0.0.1 left intact

```

Expected: The content of the Error is returned to the client as part of the response.

**Comment by Firstyear** [comment]
Note with error_handler you can not construct a manual response as:

```
168 | /HttpResponse::BadRequest()                                                                                                   
169 | |    .reason(&format!("Json parse failed: {:?}", err))                                                                        
170 | |    .body(format!("Json parse failed: {:?}", err))                                                                           
    | |_________________________________________________^ expected struct `actix_web::Error`, found struct `actix_web::HttpResponse`

```

**Comment by DoumanAsh** [comment]
I'd need to check how Error gets converted to HttpResponse, most likely we can make it to pass error's description as payload, but the format would be difficult to configure

**Comment by fafhrd91** [comment]
This won’t happen in 0.7 at least. This is potential security risk

**Comment by Firstyear** [comment]
Hey there @fafhrd91. You have said a few times this is a security risk, but haven't discussed what that risk is. If I'm controlling the message and have an understanding of what will be returned to the client this seems quite reasonable? 

The client is sending me in this example json, they know that it must be json, but they get the syntax wrong. So how is it a security risk to disclose why the json they sent was malformed? 

There are certainly cases I can see that are a risk (disclosing internal state), but this isn't the case here. 

Can you explain in detail the reason you consider this a security issue?

**Comment by kevlarr** [comment]
Running into this as well. Absolutely *love* the ease and clarity of extractors and responders, but having to manually construct a bad response instead of just `.map_err(error::BadRequest)` is annoying for a lot of use cases where security (regarding the error message being generated) *isn't* a concern.

@fafhrd91 Would it be possible to, rather than pass the message along by default, "opt in" via a different constructor used like `.map_err(|err| error::BadRequest.with_message(err))`?

I'm assuming this would not work because it doesn't really specify how it would then get converted to an `HttpResponse`, but wasn't sure.

**Comment by fafhrd91** [comment]
i dont want to change this in 0.7, but i am ok with the change in 0.8

**Comment by fafhrd91** [comment]
@Firstyear could you review 1.0 if it works and provide PR if it not

**Comment by Firstyear** [comment]
I will port my software to 1.0 and test soon then, thanks.

**Comment by fafhrd91** [comment]
it is implemented

**Comment by Firstyear** [comment]
Hey there. Where is this implemented? Is it documented? Does it have examples? It would be good to see these please.

**Comment by patrickelectric** [comment]
> Hey there. Where is this implemented? Is it documented? Does it have examples? It would be good to see these please.

Totally!  @fafhrd91
