### ISSUE TITLE
Feature request: follow redirects with actix_web::client

### ISSUE THREAD

**Issue by bedax** [actix/actix-web#607]
I am currently using actix-web, which has been a joy to use. The application also needs to download files, and as actix-web's client doesn't seem able to follow redirects I am using reqwest instead. I realise this feature isn't as simple as it sounds, as it would need to detect redirect loops and have a redirect limit, but it would be nice to be able to use actix-web's client for this.

**Comment by Shnatsel** [comment]
According to the [documentation](https://docs.rs/awc/1.0.1/awc/struct.ClientBuilder.html#method.max_redirects), this is implemented in awc 1.01, and possibly earlier. I believe this issue can be closed.

**Comment by teoxoy** [comment]
The prop is there but it doesn't do anything.

**Comment by robjtede** [comment]
closing in favor of newer #1571. working on a fix.
