### ISSUE TITLE
Client File Descriptor Leak

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#608]
I haven't found a root cause yet but after upgrading to 0.7.14. After running for ~12 hours with some regular traffic with periods of no traffic file descriptors become depleted. 

And new connections start resulting in the following error:
Connector(Resolver(IoError(Os { code: 24, kind: Other, message: "No file descriptors available" })

The endpoints being exercised follow a simple pattern:

1. Retrieve a token and URL from another service
2. Using the token retrieved make N other requests to the URL returned from step 1.

Testing locally I have seen TCP sockets left in a CLOSE_WAIT state but I haven't been able to make it happen consistently. Using wrk I have driven 30 concurrent connections over 30 seconds a number of times and then let the connections go into CLOSE_WAIT state and then wait some more time and run 30 more connections. With that pattern usually connections are cleaned up. However, in my latest test I was able to get 30 connections in CLOSE_WAIT state that are not being cleaned up by the server.

I have looked through the Connector code to see if there is something simple that is being missed but nothing is jumping out at me.

The server doesn't crash but once descriptors are exhausted the health endpoint which returns an empty string statically is reporting as timing out by AWS and the docker container is removed.

I do see this in my logs occasionally I'm not sure if it is relevant.
actix_web::client::pipeline: Client http transaction is not completed, dropping connection

**Build details**
nightly-2018-11-26 locally using x86_64-unknown-linux server is using musl

Locally running Ubuntu 16.04
Server runs in a docker container with the scratch base image

Actix Web Features rust-tls, flate2-rust default-features = false

**Comment by DoumanAsh** [comment]
Interestingly enough 0.7.14 actually fixed this problem for some people, strange that you see it. Do you use default `keep_alive` setting on server?

**Comment by glademiller** [comment]
I do use keep_alive yes.

**Comment by DoumanAsh** [comment]
Is it `Timeout` or?

I'm talking about https://actix.rs/actix-web/actix_web/server/enum.KeepAlive.html

**Comment by fafhrd91** [comment]
It might be client bug

**Comment by glademiller** [comment]
I looked deeper and found out this is due to leaked UDP sockets I will open another issue.
