### ISSUE TITLE
Content-Disposition inline incorrectly includes filename

### ISSUE THREAD

**Issue by sstelfox** [actix/actix-web#609]
While diagnosing an issue with returned Content-Disposition headers, I noticed that the `filename=` component is included even when the disposition is inline which is incorrect behaviour. This is present and tested on version 0.7.14 and can be reproduced with the following minimal snippet:

```rust
extern crate actix;
extern crate actix_web;

use actix_web::{server, App, HttpRequest, Responder};
use actix_web::fs::NamedFile;
use actix_web::http::Method;

fn css_file(_req: &HttpRequest) -> impl Responder {
    NamedFile::open("test.css")
}

fn main() {
    server::new(|| App::new().resource("/test.css", |r| r.method(Method::GET).f(css_file)))
        .bind("127.0.0.1:8000")
        .unwrap()
        .run();
}
```

The `test.css` file needs to be present in your current working directory, but can be empty. Running this and checking the headers with curl results in the following:

```
$ curl -sv http://127.0.0.1:8000/test.css > /dev/null
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /test.css HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-length: 0
< content-type: text/css
< content-disposition: inline; filename="test.css"
< last-modified: Fri, 30 Nov 2018 22:18:31 GMT
< etag: "3e0ec9:0:5c01b737:3a9b9892"
< accept-ranges: bytes
< date: Fri, 30 Nov 2018 22:20:34 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
```

The incorrect header is this one:

```
content-disposition: inline; filename="test.css"
```

This should be:

```
content-disposition: inline
```

**Comment by DoumanAsh** [comment]
Yeah, we always include file name here https://github.com/actix/actix-web/blob/master/src/fs.rs#L165-L168

But RFC 6266 doesn't strictly say we shouldn't provide filename
The grammar for content disposition is:

```
content-disposition = "Content-Disposition" ":" disposition-type *( ";" disposition-parm )
```

Having filename even in inline, allows you to control how browser would be prompted to save such inline file.

inline with filename is even mentioned in examples https://tools.ietf.org/html/rfc6266#section-5

So the behavior is not incorrect here

P.s. If you still believe it is incorrect behavior, I'd like you to describe concretely how current behavior is incorrect

**Comment by DoumanAsh** [comment]
This is not an incorrect behavior, so I'll close issue unless there is some strong argument against RFC allowing it

**Comment by sstelfox** [comment]
How about making this header entirely optional rather than mandatory? Even RFC6266 points out that it isn't included in the HTTP standards and in many cases, even with the use of static files, it isn't necessary or desired.

**Comment by DoumanAsh** [comment]
Hm... Well I think `inline` is also default behavior, so I guess we could omit this header, but it would require to add some more conditionals to that code
