### ISSUE TITLE
Javascript Files Content-Disposition Incorrectly Detected as Attachement

### ISSUE THREAD

**Issue by sstelfox** [actix/actix-web#610]
Current the mime detection from mime_guess correctly identifies javascript files as "application/javascript" but that doesn't match any of the specially named Mime types `mime::IMAGE`, `mime::TEXT`, or `mime::VIDEO` which is currently marked as inline.

This can be worked around through the StaticFileConfig, but the default for these files should be correct for a webserver.

**Comment by DoumanAsh** [comment]
I'm not sure what makes you think it is incorrect, but PRs are welcome

>This can be worked around through the StaticFileConfig

This is not work around, it is intended than when needed user can customize it, because we cannot know each possible need of user

**Comment by sstelfox** [comment]
Sorry I missed the notifications you had responded. I'll try and put together a PR tonight for the default behavior for javascript files.

**Comment by jcbritobr** [comment]
This bug is valid yet?
