### ISSUE TITLE
error: expected identifier, found reserved keyword `async`

### ISSUE THREAD

**Issue by bbigras** [actix/actix-web#613]
When using the new async_await stuff.

```
error: expected identifier, found reserved keyword `async`
   --> src/main.rs:334:21
    |
334 |     Ok(AsyncResult::async(Box::new(f)))
    |                     ^^^^^ expected identifier, found reserved keyword
```

**Comment by DoumanAsh** [comment]
It this problem with `2018` edition only?
I'm not seeing it on stable rustc

**Comment by bbigras** [comment]
Yes. I'm assuming the new async stuff is only for 2018.

**Comment by fafhrd91** [comment]
we should rename it

**Comment by DoumanAsh** [comment]
@fafhrd91 it should be ok to do such breaking change on `0.7` I guess? otherwise we couldn't let people compile on newer compilers where `async` is reserved

**Comment by fafhrd91** [comment]
i think it should be fine, i dont think `AsyncResult` is being used outside of actix-web

**Comment by DoumanAsh** [comment]
Ok, I'll fix it tomorrow, I guess we should do it before next Rust release

**Comment by DoumanAsh** [comment]
@bbigras New version `0.7.15` is published to remove usage of `async` keyword

@fafhrd91 I also had to update `actix` since otherwise we'd have multiple copies of `crossbeam-channel` and `parking_lot` when using actix-web

**Comment by bbigras** [comment]
Thank you very much.
