### ISSUE TITLE
Incomplete or incorrect custom handler documentation?

### ISSUE THREAD

**Issue by saarw** [actix/actix-web#615]
The custom handler documentation starts by extracting a future for JSON, but returns a synchronous response. How do you read the data returned by the **info** future while returning a synchronous response like that?  
```rust
fn handle(&self, req: &HttpRequest<S>) -> Self::Result {
		let params = Path::<(String, String)>::extract(req);
		let info = Json::<MyInfo>::extract(req); 

		...
			
        HttpResponse::Ok().into()
    }
```

The only way I get things to compile when reading the data in **info** is to return 
```rust
HttpResponse::Ok().streaming(info.map(|data| {
process(data);
::bytes::Bytes::new()
}).into_stream())
```

**Comment by catevita** [comment]
Same problem here. @saarw I was suggested this solution:
`impl<S:'static> Handler<S> for MyHandler{` and it compiles

**Comment by fafhrd91** [comment]
`Handler` is dropped in 1.0
