### ISSUE TITLE
Deserialization failure with struct flattening and Query

### ISSUE THREAD

**Issue by vmalloc** [actix/actix-web#623]
Trying to use the following with the `Query` extractor:

```rust
#[derive(Debug, Deserialize)]
pub struct Info {
    pub(crate) endpoint: Option<String>,
    #[serde(flatten)]
    pub(crate) timing: Timing,
}

#[derive(Debug, Deserialize)]
pub struct Timing {
    pub(crate) total: f64,
    pub(crate) active: f64,
}
```
Trying this with a URL containing numbers (e.g. `/route?total=1.1&active=2.2&endpoint=bla`) returns an error "invalid type: string \"1.1\" expected f64).

Without flattening it seems to work correctly though...

**Comment by DoumanAsh** [comment]
You can try to use `serde_urlencoded` directly to parse your string, I suspect it is a problem there

**Comment by vmalloc** [comment]
@DoumanAsh will try. Thanks!

**Comment by vmalloc** [comment]
Seems to already be a known issue: https://github.com/nox/serde_urlencoded/issues/33
