### ISSUE TITLE
Question: dynamically adding and removing resources

### ISSUE THREAD

**Issue by davedbase** [actix/actix-web#624]
I was wondering if it there was a way with the HTTPServer to dynamically add and remove resources. I'd basically like to define the App and the HTTP server separately, then be able to call app to make changes without having to restart the server. Is this at all possible?

Thanks.

**Comment by DoumanAsh** [comment]
No, at the moment application is defined in a static way

**Comment by fafhrd91** [comment]
I am strongly against this feature. But it is possible to create custom router. Just register it with .h() method
