### ISSUE TITLE
How to perform client side SSL certificate verification?

### ISSUE THREAD

**Issue by RazrFalcon** [actix/actix-web#625]
I have a server that uses a self-signed certificate and I want to disable/reject any requests that doesn't have/use the provided SSL key.

**Comment by DoumanAsh** [comment]
If i'm not mistaken, if you bind your server with just SSL it wouldn't listen for non-SSL requests at all

**Comment by RazrFalcon** [comment]
I still can access it using `curl` with the `-k/--insecure` flag.

**Comment by DoumanAsh** [comment]
Are you sure it uses Http, not HttpS without verification of certificate?

Because according to curl docs:

>Tell libcurl to not verify the peer. With libcurl you disable this with curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, FALSE);

>With the curl command line tool, you disable this with -k/--insecure.

From https://curl.haxx.se/docs/sslcerts.html

**Comment by RazrFalcon** [comment]
I'm not sure what it does, but I want to disable it.

**Comment by DoumanAsh** [comment]
Please read `curl` manual`

Use correct URI schema for HTTP without SSL: `http://<path>`

curl wouldn't attempt to connect over https unless you specify link with `https` schema

**Comment by RazrFalcon** [comment]
It's not a `curl` problem. I want to reject those request on the server side.

**Comment by DoumanAsh** [comment]
HTTP requests by default are no handled at all when you binds with SSL(because we don't open TCP over 80 port).
Do you mean you want to send response with redirect for HTTPs?


Ok, I re-read subject(the issue title is wrong):

>I want to disable/reject any requests that doesn't have/use the provided SSL key.

I think there is a bit of misunderstanding, if I remember correctly, server sends its certificate to indicate that SSL connection can be trustworthy for client and then client decides whether he is going to establish it or not.
I'm not sure what sort of reject you want? 

P.s. it is server who identifies itself, not client as far as I know

**Comment by fafhrd91** [comment]
I guess this is about client side cert validation.

**Comment by DoumanAsh** [comment]
Ah I see, I'm pretty sure we don't have any option for that though at the moment

**Comment by DoumanAsh** [comment]
There is no API in actix-web itself, but looking over our SSL libs:

For OpenSSL you can set verification method https://docs.rs/openssl/0.10/openssl/ssl/struct.SslAcceptorBuilder.html#method.set_verify
You'd need to set `FAIL_IF_NO_PEER_CERT`

For rustls and native-tls, I'm not sure?

**Comment by RazrFalcon** [comment]
Thanks. `ssl.set_verify(SslVerifyMode::PEER | SslVerifyMode::FAIL_IF_NO_PEER_CERT);` done the job.

**Comment by thehappycoder** [comment]
I managed to do it too. Here is what it made it work for me:

```
#!/bin/bash
openssl req -x509 -newkey rsa:4096 -keyout server_key.pem -out server_cert.pem -nodes -days 3650 -subj "/CN=localhost/O=Client\ Certificate\ Demo"
openssl req -newkey rsa:4096 -keyout client_key.pem -out client_csr.pem -nodes -days 3650 -subj "/CN=Client"
openssl x509 -req -in client_csr.pem -CA server_cert.pem -CAkey server_key.pem -out client_cert.pem -set_serial 01 -days 3650
openssl pkcs12 -export -clcerts -in client_cert.pem -inkey client_key.pem -out client.p12
```

```
let mut builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
    builder
        .set_private_key_file("server_key.pem", SslFiletype::PEM)
        .unwrap();
    builder
        .set_certificate_chain_file("server_cert.pem")
        .unwrap();
    builder.set_ca_file("server_cert.pem").unwrap(); // Without this would get curl: (35) error:1401E418:SSL routines:CONNECT_CR_FINISHED:tlsv1 alert unknown ca
    builder.set_verify(SslVerifyMode::PEER | SslVerifyMode::FAIL_IF_NO_PEER_CERT);
```

```
curl --insecure --cert client.p12:password --cert-type p12 https://localhost:8443
```

**Comment by RazrFalcon** [comment]
@thehappycoder Interesting, but why it still requires `--insecure`? I've tried your method via Qt and not curl, but it refuses to connect.

**Comment by krzysztofgal** [comment]
Because it's self signed certificate.
