### ISSUE TITLE
start_incoming replacement?

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#627]
I've noticed that in 0f1c80ccc63840b9da646b268f2e07dd520c6837 start_incoming has been deprecated. However, neither the commit nor the attribute mentions any replacement. What should I migrate to to handle Unix socket connections?

**Comment by DoumanAsh** [comment]
@fafhrd91 ping ?

**Comment by fafhrd91** [comment]
I’l add replacement 0.8

**Comment by fafhrd91** [comment]
it is not possible to implement start_incoming in new architecture

**Comment by kornelski** [comment]
Does that mean the support for Unix sockets has been dropped?

**Comment by fafhrd91** [comment]
i will add uds support directly

**Comment by tworec** [comment]
can you provide some example code for UDS?

**Comment by fafhrd91** [comment]
it is not possible at the moment. actix-server must be extended with uds support

**Comment by kornelski** [comment]
#92
