### ISSUE TITLE
fs::StaticFiles::new("static/", true) can't auto load index.html

### ISSUE THREAD

**Issue by damon-kwok** [actix/actix-web#63]
[dependencies]
env_logger = "*"
futures = "0.1"
tokio-core = "0.1"
#actix = "^0.4.6"
actix = { git = "https://github.com/actix/actix.git" }
actix-web = { git = "https://github.com/actix/actix-web.git" }

[source]
#![allow(unused_variables)]
extern crate actix;
extern crate actix_web;
extern crate env_logger;

use actix::*;
use actix_web::*;

/// do websocket handshake and start `MyWebSocket` actor
fn ws_index(r: HttpRequest) -> Result<HttpResponse> {
    ws::start(r, MyWebSocket)
}

// fn index(req: HttpRequest) -> String {
    // format!("Hello {}!", &req.match_info()["name"])
// }

/// websocket connection is long running connection, it easier
/// to handle with an actor
struct MyWebSocket;

impl Actor for MyWebSocket {
    type Context = ws::WebsocketContext<Self>;
}

/// Handler for `ws::Message`
impl Handler<ws::Message> for MyWebSocket {
    type Result = ();

    fn handle(&mut self, msg: ws::Message, ctx: &mut Self::Context) {
        // process websocket messages
        println!("WS: {:?}", msg);
        match msg {
            ws::Message::Ping(msg) => ctx.pong(&msg),
            ws::Message::Text(text) => ctx.text(&text),
            ws::Message::Binary(bin) => ctx.binary(bin),
            ws::Message::Closed | ws::Message::Error => {
                ctx.stop();
            }
            _ => (),
        }
    }
}

fn main() {
    ::std::env::set_var("RUST_LOG", "actix_web=info");
    let _ = env_logger::init();
    let sys = actix::System::new("ws-example");

    let _addr = HttpServer::new(
        || Application::new()
            // enable logger
            .middleware(middleware::Logger::default())
            // websocket route
            .resource("/ws/", |r| r.method(Method::GET).f(ws_index))
            // static files
            .handler("/", fs::StaticFiles::new("static/", true))
        // start http server on 127.0.0.1:8080
        .bind("127.0.0.1:8080").unwrap()
        .start();

    println!("Started http server: 127.0.0.1:8080");
    let _ = sys.run();
}

**Comment by fafhrd91** [comment]
it is not clear what is the problem.

if copied websocket example from actix-web repo, then you need to copy [static](https://github.com/actix/actix-web/tree/master/examples/static) directory as well, and adjust `StaticFiles` parameter

**Comment by fafhrd91** [comment]
you have to manually redirect to index.html at the moment.

```rust
            .resource("/", |r| r.method(Method::GET).f(|_| {
                httpcodes::HTTPFound
                    .build()
                    .header("LOCATION", "/index.html")
                    .finish()
            }))
```

**Comment by fafhrd91** [comment]
I added `index.html` file redirect support to `StaticFiles`

```rust
    .handler("/", fs::StaticFiles::new("static/", true)
           .index_file("index.html"))
```

**Comment by damon-kwok** [comment]
it's work :)

**Comment by damon-kwok** [comment]
@fafhrd91 
If it can support regular expressions even better :)

example:
.index_file("\\index.\\(html\\|htm\\)\\")

**Comment by fafhrd91** [comment]
but this is just redirect. how this regex would be used?

**Comment by damon-kwok** [comment]
if(fs::IsExist("index.html))
   index("index.html")
else if(fs::IsExist("index.htm))
   index("index.html")
else ...

example:
.index_file("index.html")
.index_file(["index.html","index.htm", "index.php"])

**Comment by damon-kwok** [comment]
@fafhrd91 
the apache web server use this config:

`<Directory />
DirectoryIndex index.html index.htm index.php index.php3
</Directory>`

actix_web can do like this:
.index_file("index.html")
.index_file(["index.html","index.htm", "index.php"])

**Comment by fafhrd91** [comment]
is there real use case for this? also it is easy to make custom version of StaticFiles.

actix-web is not general purpose files server. I am not sure this is good functionality for web framework

**Comment by damon-kwok** [comment]
@fafhrd91 
http://www.htaccess-guide.com/directoryindex-uses/

**Comment by fafhrd91** [comment]
can't you just use nginx or apache for static files?

**Comment by damon-kwok** [comment]
I'm using rust to develop a web application that needs to use websocket and StaticFiles in the same  domain, atix-web is almost perfect and hard to break. :)

**Comment by fafhrd91** [comment]
you should not use StaticFiles for production system, it is blocking at the moment. I suggest to use nginx for static content, and StaticFiles only for development

**Comment by damon-kwok** [comment]
i see, thanks.
