### ISSUE TITLE
Graceful shutdown broken

### ISSUE THREAD

**Issue by jeffsmith82** [actix/actix-web#633]
I'm testing the graceful shutdown so wrote the following

```
use actix_web::{server, App, HttpRequest};
use std::time::Duration;
use std::thread;

fn hello_world(_req: &HttpRequest) -> &'static str {
    "Hello World!"
}

fn sleeper(_req: &HttpRequest) -> &'static str {
        thread::sleep(Duration::from_secs(50));
        "sleepy time"
}

fn main() {
    server::new(|| App::new().resource("/", |r| r.f(hello_world))
        .resource("/sleep",|r| r.f(sleeper))
        )
        .bind("0.0.0.0:8080")
        .expect("Can not bind to port 8080")
        .run();
}
```

If I then start the server and then run curl against the /sleep endpoint and then CTRL +C the server process I would expect it to wait 30 seconds before force able killing the server process which is what the docs say. What I see is the server waits for the http request to end before gracefully shutting down.

```
[jeffreys@jeff1 ~]$ time curl -v http://127.0.0.1:8080/sleep
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /sleep HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 11
< content-type: text/plain; charset=utf-8
< date: Mon, 17 Dec 2018 11:46:18 GMT
<
* Connection #0 to host 127.0.0.1 left intact
sleepy time
real    0m50.017s
user    0m0.003s
sys     0m0.012s
```

**Comment by fafhrd91** [comment]
use SIGTERM for graceful shutdown, SIGINT is just shutdown

**Comment by jeffsmith82** [comment]
So if I do SIGINT using CTRL + C it waits for all the request to finish before dying, the docs say this which i'm taking as it should stop straight away.

SIGINT - Force shutdown workers

If I run the process get its pid and then kill it then its waiting for the requests and seems to ignore the default 30 second time before dying.

SIGTERM - Graceful shutdown workers

If I kill -9 the pid it really does force shutdown as expected.

SIGQUIT - Force shutdown workers

**Comment by fafhrd91** [comment]
Only SIGTERM waits. Other does not.

**Comment by jeffsmith82** [comment]
I'm testing it and from what I am seeing on Fedora 29.

SIGINT - waits for all requests to finish which is wrong.
SIGTERM - waits for all requests to finish even if they are longer than then 30 seconds set in shutdown_timeout()
SIGKILL - this works as expected.

**Comment by fafhrd91** [comment]
Hmm, strange. I’ll check. You can not handle SIGKILL

**Comment by fafhrd91** [comment]
fixed in master
