### ISSUE TITLE
multipart upload is very slow

### ISSUE THREAD

**Issue by kanekv** [actix/actix-web#634]
I have compiled https://github.com/actix/examples/blob/master/multipart/src/main.rs as is (without any changes) and issues:

```
$ time curl localhost:8080 -F upload=@src/main.rs
[3380]
real	0m1.022s
user	0m0.006s
sys	0m0.005s
```

It took over a second to process pretty small file. What could be the reason?

**Comment by kanekv** [comment]
Found more details:
```
[pid   718] 02:48:40 recvfrom(35, "POST / HTTP/1.1\r\nHost: 127.0.0.1"..., 8192, 0, NULL, NULL) = 209
[pid   718] 02:48:40 recvfrom(35, 0x7f46c98900d1, 7983, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid   718] 02:48:40 getpeername(35, {sa_family=AF_INET, sin_port=htons(58374), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_REALTIME, {tv_sec=1545101320, tv_nsec=479945600}) = 0
[pid   718] 02:48:40 write(1, "1\n", 21
) = 2
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=434315461}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=434782061}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 0) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=435662961}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=436144061}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=436557661}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 0) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=437354361}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=437805061}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=438316161}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 446) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=889026361}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=890275761}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=891721261}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 40) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=936003561}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=936953461}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=937923661}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 0) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=939801861}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=940552561}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=941242961}) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 0) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=942845761}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=943374861}) = 0
[pid   718] 02:48:40 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70042, tv_nsec=944091461}) = 0
[pid   718] 02:48:40 epoll_wait(13, [{EPOLLIN|EPOLLOUT, {u32=0, u64=0}}], 1024, 4100) = 1
[pid   718] 02:48:41 clock_gettime(CLOCK_MONOTONIC, {tv_sec=70043, tv_nsec=428121761}) = 0
```

stracing server, this part seems very suspicious:
```
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 446) = 0
[pid   718] 02:48:40 epoll_wait(13, [], 1024, 40) = 0
```

Data should be immediately available, why does it wait half a second and doesn't get anything?

**Comment by DoumanAsh** [comment]
`epoll_wait(13, [], 1024, 446) = 0` means that there is no events I think?

**Comment by kanekv** [comment]
I'm running curl on localhost, it seems impossible to have no events for 0.5 seconds

**Comment by Dowwie** [comment]
I found the same, built in release mode too.  ~1.0x second run time

@fafhrd91

**Comment by mzhang28** [comment]
I tried reproducing this, and after looking through `ltrace -rf` logs, I saw `100-continue`. Could it be related to [this](https://curl.haxx.se/mail/lib-2004-08/0002.html)? It might explain why there's no events being sent for some time.

Here are potentially relevant lines:

```
14888   │ [pid 13902]   0.000751 memcpy(0x6f3c42c500b0, "127.0.0.1:8080", 14 <unfinished ...>
14889   │ [pid 13902]   0.000752 <... memcpy resumed> )    = 0x6f3c42c500b0
14890   │ [pid 13902]   0.000763 memcpy(0x6f3c42c7f010, "\001\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\274\3076E\f\0\0"..., 216 <unfinished ...>
14891   │ [pid 13902]   0.000694 <... memcpy resumed> )    = 0x6f3c42c7f010
14892   │ [pid 13902]   0.000723 memcpy(0x6f3c431f73e1, "localhost:8080", 14 <unfinished ...>
14893   │ [pid 13902]   0.000661 <... memcpy resumed> )    = 0x6f3c431f73e1
14894   │ [pid 13902]   0.000720 memcpy(0x6f3c431f73e1, "curl/7.63.0", 11 <unfinished ...>
14895   │ [pid 13902]   0.000068 <... memcpy resumed> )    = 0x6f3c431f73e1
14896   │ [pid 13902]   0.000728 memcpy(0x6f3c431f73e1, "*/*", 3 <unfinished ...>
14897   │ [pid 13902]   0.000067 <... memcpy resumed> )    = 0x6f3c431f73e1
14898   │ [pid 13902]   0.000717 memcpy(0x6f3c431f73e1, "3623", 4 <unfinished ...>
14899   │ [pid 13902]   0.000688 <... memcpy resumed> )    = 0x6f3c431f73e1
14900   │ [pid 13902]   0.000723 memcpy(0x6f3c431f73e1, "100-continue", 12 <unfinished ...>
14901   │ [pid 13902]   0.000699 <... memcpy resumed> )    = 0x6f3c431f73e1
14902   │ [pid 13902]   0.000747 memcmp(0x6f3c42c3b360, 0xc4536d1f504, 1, 1 <unfinished ...>
14903   │ [pid 13902]   0.000859 <... memcmp resumed> )    = 0
```

I'll keep exploring I guess

**Comment by Dowwie** [comment]
@iptq Upon second inspection, you are right about the problem being related to curl, although I can't confirm that the issue is related to the one that you refer to

using httpie, timing is 0.377 (still pretty high..) 

``http -f POST localhost:8080 files@src/main.rs  0.34s user 0.03s system 98% cpu`` **0.377** ``total``


@fafhrd91 0.377 seconds to locally upload main.rs -- seems high.  In fact, I just ran a file uploader web app using flask and it finishes nearly at same time

**Comment by mzhang28** [comment]
Weirdly enough I'm still getting this delay with `epoll_wait`:

```
[pid  1523]      0.000146 epoll_wait(7, [], 1024, 0) = 0
[pid  1523]      0.000083 epoll_wait(7, [], 1024, 0) = 0
[pid  1523]      0.000039 epoll_wait(7, [], 1024, 488) = 0
[pid  1523]      0.488840 epoll_wait(7, [], 1024, 5) = 0
[pid  1523]      0.005468 epoll_wait(7, [], 1024, 0) = 0
[pid  1523]      0.000324 epoll_wait(7, [], 1024, 0) = 0
```

This delay appears every time this same consecutive 6 calls to `epoll_wait` happens. Do you know what's triggering the epoll?

**Comment by DoumanAsh** [comment]
tokio is polling for new IO events

**Comment by kanekv** [comment]
Any other server I've tried doesn't have this issue, at most it takes < 100 ms.

**Comment by kanekv** [comment]
Btw, where those weird timeout values are coming from?

**Comment by Dowwie** [comment]
@kanekv curl is clearly creating significant overhead.  Stop using it to benchmark api performance.  Further, am curious what implementations you're looking at that result in  < 100 ms.

However, the performance of multipart request handling is on par with flask, and that raised suspicions.  Upon further investigation, it seems that sluggish performance is attributed to a bug that @fafhrd91 is aware of and will try to fix within the next couple of days

**Comment by kanekv** [comment]
@Dowwie we should compare it with golang, I'll run a comparison when @fafhrd91 submits a patch.

**Comment by fafhrd91** [comment]
fixed.

@Dowwie you should do proper performance checks before post any results

2018-12-23T18:22:19Z INFO  actix_web::middleware::logger] 127.0.0.1:9760 "POST / HTTP/1.1" 200 6 "-" "curl/7.54.0" 0.000731****

**Comment by Dowwie** [comment]
@kanekv how does this compare with your Go implementation?

**Comment by ghost** [comment]
Hi,

this issue seems not fixed in `actix-web 0.7.18` nor in the `0.8` branch.

Using the same code (https://github.com/actix/examples/blob/master/multipart/src/main.rs) with a file of `235MB` takes **~45** sec in debug mode and **~15** sec in release mode while it takes only **~2** sec in Go.
(results are consistent across Chrome, Firefox and curl).

```
# cargo run
INFO 2019-03-06T22:22:37Z: actix_web::middleware::logger: 127.0.0.1:63822 "POST / HTTP/1.1" 200 11 "http://localhost:9090/" "Mozilla/5.0 ... Firefox/" 44.047632

# cargo run -- release
INFO 2019-03-06T22:26:30Z: actix_web::middleware::logger: 127.0.0.1:63955 "POST / HTTP/1.1" 200 11 "http://localhost:9090/" "Mozilla/5.0 ... Firefox/" 15.022333

# Go
[GIN] 2019/03/06 - 22:53:26 | 200 |  2.502863302s |             ::1 | POST     /upload
```

**Comment by ghost** [comment]
for information, here are the headers sent
```

Accept | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding | gzip, deflate
Accept-Language | en-US,en;q=0.5
Connection | keep-alive
Content-Length | 246726553
Content-Type | multipart/form-data; boundary=---------------------------4837802485215405941651999951
Host | localhost:9191
Referer | http://localhost:9191/upload
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 ... Firefox
```

**Comment by ghost** [comment]
I'm not sure if the problem can come from here, but when I add a `println` in `fold` I get these 'strange' results:
```rust
pub fn save_file(
    field: multipart::Field<dev::Payload>,
) -> Box<Future<Item = i64, Error = Error>> {
    let mut rng = rand::thread_rng();
    let x: u8 = rng.gen();
    let file_path_string = format!("upload_{}.png", x);
    let mut file = match fs::File::create(file_path_string) {
        Ok(file) => file,
        Err(e) => return Box::new(future::err(error::ErrorInternalServerError(e))),
    };
    Box::new(
        field
            .fold(0i64, move |acc, bytes| {
                println!("chunk: {}", bytes.len()); // <- let inspect the size of our chunks
                let rt = file
                    .write_all(&bytes)
                    .map(|_| acc + bytes.len() as i64)
                    .map_err(|e| {
                        println!("file.write_all failed: {:?}", e);
                        error::MultipartError::Payload(error::PayloadError::Io(e))
                    });
                future::result(rt)
            })
            .map_err(|e| {
                println!("save_file failed, {:?}", e);
                error::ErrorInternalServerError(e)
            }),
    )
}
```

```
...
chunk: 1
chunk: 205
chunk: 1
chunk: 212
chunk: 1
chunk: 972
chunk: 1
chunk: 389
chunk: 1
chunk: 205
chunk: 1
chunk: 56
chunk: 1
chunk: 98
chunk: 1
chunk: 52
chunk: 1
chunk: 138
chunk: 1
chunk: 145
chunk: 1
chunk: 672
chunk: 1
chunk: 709
chunk: 1
chunk: 788
chunk: 1
chunk: 40
chunk: 1
chunk: 509
chunk: 1
chunk: 738
chunk: 1
chunk: 42
chunk: 1
chunk: 484
chunk: 1
chunk: 44
chunk: 1
chunk: 86
chunk: 1
chunk: 68
chunk: 1
chunk: 315
chunk: 1
chunk: 170
chunk: 1
chunk: 353
chunk: 1
chunk: 710
chunk: 1
chunk: 390
chunk: 1
chunk: 984
chunk: 1
chunk: 91
chunk: 1
chunk: 141
chunk: 1
chunk: 289
chunk: 1
chunk: 452
chunk: 1
chunk: 164
chunk: 1
chunk: 87
chunk: 1
chunk: 336
chunk: 1
chunk: 93
chunk: 1
chunk: 40
chunk: 1
chunk: 258
chunk: 1
chunk: 875
chunk: 1
chunk: 2
chunk: 1
chunk: 594
chunk: 1
chunk: 301
chunk: 1
chunk: 1
chunk: 1
chunk: 575
chunk: 1
chunk: 2586
```

are those `chunk: 1` normal ?

**Comment by Keats** [comment]
Those `chunk: 1` seem to be `\r`. I've tried with a txt document with no `\r` and it still adds one of those after each line.

@z0mbie42 do you have the Go code so I can compare locally?

**Comment by ghost** [comment]
Hi @Keats , I've used the following code: https://github.com/gin-gonic/examples/blob/master/upload-file/multiple/main.go

**Comment by fafhrd91** [comment]
i dont think using multipart example as benchmark is good idea, it writes to disk which is blocking operation.

**Comment by Keats** [comment]
Part of the issue seems to be that some of my files don't get chunked. 
Note that this below is with alpha.3.

I am not entirely sure why that happens but they only get a single chunk and it takes 50s locally for a 60MB .txt file with the upload % stuck for many seconds at times.
I try another file that is a 100MB PDF and it takes a couple of seconds to upload and I do see the chunks.

Even if I rename the .txt file to .pdf to change the content-type, I still get a single chunk: `Chunk size: 58395198`.

Maybe I am missing something obvious though?

**Comment by fafhrd91** [comment]
@Keats could you show your code?

**Comment by Keats** [comment]
I am using the multipart example, with only a print added for the chunk bytes length

**Comment by fafhrd91** [comment]
How do you upload file?

**Comment by Keats** [comment]
I've tried with the form built-in the example and with curl

**Comment by ghost** [comment]
Hi,

@fafhrd91 is totally right, using the multipart example code is wrong because it use synchronous IO.

Using a `Vec` shows far better performances (~2.5 sec for a `235MB` `.mp3` vs ~15sec using sync IO, in release mode).

But, I wasn't able to find a good way to handle a multipart upload because `tokio::fs` does not work with actix (actix/actix#181) and all in memory is not manageable in real life.

On the other hand the other points raised are still valid.

**Comment by fafhrd91** [comment]
i found inefficiencies in implementation, i will update impl in next version.

@z0mbie42 you can use `web::block` for blocking operation.

**Comment by Keats** [comment]
In my usecase I don't really want to write to disk, just read the chunks while doing some validation and forward it to S3. I guess the fact that some files don't get chunked is another issue I'll open tomorrow

**Comment by Keats** [comment]
Just to give some more data as I've tried a Go/Actix (0.7) comparison as well on my end. For a 777MB file uploaded using `time curl`:

Actix (`cargo run --release`):
> [814619441]      216.33 real         0.24 user         1.17 sys

Go:
>        2.91 real         0.25 user         1.02 sys

Both actix/Go code is available at https://gist.github.com/Keats/5ea1b0ad9c1151f5e5a35a7a004d2535
The Go code is reading the file by chunks of 10kb while the actix-web only gets one chunk in some cases. One of the file I am using for test is https://norvig.com/big.txt, sometimes concatened multiple times and I never get more than the single chunk for it with actix-web.

**Comment by fafhrd91** [comment]
@Keats do you use curl for upload?

**Comment by Keats** [comment]
> For a 777MB file uploaded using time curl

Yes. Using a HTML form instead, actix-web took around 85s for the same file

**Comment by fafhrd91** [comment]
fixed in master

**Comment by Dowwie** [comment]
@Keats very curious to know what your findings are with the fix just committed to master

**Comment by Dowwie** [comment]
@Keats - given @fafhrd91 's fix committed to master, using your 777MB file and [the updated multipart logic in the examples here](https://github.com/actix/examples/blob/master/multipart/src/main.rs), what are your findings?

**Comment by Dowwie** [comment]
@Keats  FYI - fix committed to master.  curious what your findings are

**Comment by Keats** [comment]
I have mentioned it in #769 but that seems to be working well now
