### ISSUE TITLE
Parse JSON body when content type is text/plain

### ISSUE THREAD

**Issue by philbooth** [actix/actix-web#635]
To support legacy clients of an API, we have a [requirement](https://github.com/mozilla-services/syncstorage-rs/issues/113) to extract JSON bodies when `Content-Type` is `text/plain`. Unless I'm missing something, it seems like this isn't possible out of the box due to the implementation of `actix_web::dev::JsonBody`.

Is there any appetite for a way to work round this, possibly via extending `JsonConfig`? I'd be happy to work on a PR if so.

**Comment by fafhrd91** [comment]
PR is welcomed
