### ISSUE TITLE
Ignore double slashes in routes

### ISSUE THREAD

**Issue by TatriX** [actix/actix-web#636]
Hi!

I need routes like routes like `/v1/something` to be matched with `POST /v1//something/` despite it's an client error.

I know there is a `NormalizePath` but it doesn't work with `POST` requests.
It's also impossible to fix this in the `Middleware`, at least as far as I know.

Any ideas on how this can be solved?

**Comment by DoumanAsh** [comment]
I don't think it is good idea to attempt to fix invalid URI for bad client

@fafhrd91 If I'm not mistaken you plan to introduce some way to normalize paths in 0.8 for users?

**Comment by TatriX** [comment]
Sure, but sometimes it's required from the business perspective ;)

**Comment by fafhrd91** [comment]
i am planing to give mutable access to request in 0.8

**Comment by TatriX** [comment]
This could help. Any eta?

**Comment by fafhrd91** [comment]
this is possible now (in 1.0)
do we want to add middleware for this?

**Comment by TatriX** [comment]
It looks like it could make users live easier. I'm not sure about negative consequences, maybe some caching and indexing problems. Though I don't have an opinion.

**Comment by DoumanAsh** [comment]
@fafhrd91 would you like to see such middleware in separate crate or as part of builtin?

**Comment by fafhrd91** [comment]
i think this should be builtin. NormalizePath should be redesigned to a middleware and allow to use redirect or rewrite
