### ISSUE TITLE
Impossible to embedd in a separate thread.

### ISSUE THREAD

**Issue by dpc** [actix/actix-web#639]
This is a continuation of #638 .

I'm trying to run actix-web in it's own thread, as a embedded component, with ability to stop it gracefully. It seems impossible right now. Not only is setting it up in it's own thread difficult (#638), but to get an address on `HttpServer`,  I need to call `start() -> Addr<Server>` but that requires running a `System`, and in turn stopping that `System` too. But `System` doesn't seem thread-safe and I get ` `*const tokio_current_thread::scheduler::Node<tokio_reactor::Handle>` cannot be sent between threads safely`.

So I can spawn an actix instance, but there will be no way to stop it.

**Comment by fafhrd91** [comment]
`System` is thread safe, `SystemRunner` is not https://actix.rs/actix/actix/struct.System.html

**Comment by CodeSandwich** [comment]
I'm not quite sure, if this is the correct way to handle this problem, I'm a total newbie in Actix. 

In my experience System does not have to be `.run` to work. This works for me and handles requests on as many threads, as my cores and I get a server address to stop it, all without blocking the main thread:

```rust
let system = actix::System::new("whatever");
let server_addr = server::new(...)
        .bind("127.0.0.1:8088")
        .unwrap()
        .start();
println!("I'm not blocked!);
loop {}
```

Once again, I have no experience and this code might be eating my laundry in the background.

**Comment by dpc** [comment]
> I'm not quite sure, if this is the correct way to handle this problem, I'm a total newbie in Actix.

The missing piece is - how are you going to gracefully shut-down this server from the outside? I got it to work, but it required a lot of needless gymnastic.

**Comment by CodeSandwich** [comment]
I wanted to do it the same as you: by sending a StopServer message to server_addr. I'm not sure why, but the message is accepted, but never processed. On `.send(...).wait()` the main thread hangs forever.

**Comment by DoumanAsh** [comment]
@CodeSandwich don't use `Future::wait` on the same thread as actix `System`

**Comment by CodeSandwich** [comment]
@DoumanAsh But why? I didn't call `SystemRunner::run()` on main thread, so it's not used by Actix, is it? I can do work on it and still Actix-web handles requests correctly.

**Comment by DoumanAsh** [comment]
If you want to properly run your system you would need to do it. Without it tokio event loop is not going to spin properly

**Comment by CodeSandwich** [comment]
Thank you @DoumanAsh. Is it because `SystemRunner::run` starts an arbiter in current thread? Other parts of docs suggest that Actix can work without arbiter, but shouldn't (not sure, why yet).

**Comment by dpc** [comment]
This is what I went with. It is to be called with a closure that will actually construct the `App`, like we would do normally.

```
use crate::prelude::*;
use futures::Future;

pub struct ServerThread {
    pub join: Option<std::thread::JoinHandle<Result<()>>>,
    pub actix_addr: actix_web::actix::Addr<actix_net::server::Server>,
}

/// <https://github.com/actix/actix-web/issues/638>
pub fn construct_actix_thread<E, H, F>(
    f: impl FnOnce() -> std::result::Result<actix_web::server::HttpServer<H, F>, E> + Send + 'static,
) -> std::result::Result<ServerThread, E>
where
    E: std::error::Error + Send + Sync + 'static,
    H: actix_web::server::IntoHttpHandler + 'static,
    F: Fn() -> H + Send + Clone + 'static,
{
    let (tx, rx) = std::sync::mpsc::channel();

    let join = std::thread::spawn(move || {
        let sys = actix::System::new("embedded-http-server");
        match f() {
            Ok(app) => {
                tx.send(Ok(app.system_exit().start()))?;
                sys.run();
            }
            Err(e) => {
                tx.send(Err(e))?;
            }
        }

        Ok(())
    });

    let addr = rx.recv().unwrap()?;

    Ok(ServerThread {
        join: Some(join),
        actix_addr: addr,
    })
}

impl ServerThread {
    fn stop(&self) {
        self.actix_addr
            .send(actix_web::server::StopServer { graceful: true })
            .wait()
            .unwrap()
            .unwrap();
    }
}

impl Drop for ServerThread {
    fn drop(&mut self) {
        self.stop();
        self.join.take().map(|j| j.join().unwrap());
    }
}
```

usage:

```
        let thread = actix::construct_actix_thread({
            let log = log.clone();
            move || {
                let state = State { log, supervisor };
                server::new(move || {
                    App::with_state(state.clone())
                        .middleware(RequestLogger)
                        .resource("/v1/status", |r| {
                            r.method(http::Method::GET).f(server_status)
                        })
                })
                .bind(format!("0.0.0.0:{}", port))
            }
        })?;
```

**Comment by medwards** [comment]
Sorry for necroing this thread but I think I have similar requirements (I want to be able to spin up an `HttpServer` for integration tests) and I put together the following: https://pastebin.com/b2fbJmaQ

You can then call `server.thread.join()` if you want to block on the server running (eg inside of `main`), and tests can launch it on an arbitrary port (eg 0) and still connect to it.

Shutdown, however, is very awkward:
Using the actix `Addr` you can send a `StopServer` message which says ( https://actix.rs/actix-web/actix_web/server/struct.StopServer.html ):
> If server starts with `spawn()` method, then spawned thread get terminated.

I think here `spawn` might have become `run` but I don't see any way to get the servers `Addr` without running my own actix `System` and calling `start`. As a result if you send `StopServer` and then join the thread (waiting for the graceful shutdown) you block forever because the actix `System` is still running. I tried a few things (holding on to the `Arbiter` `Addr` or the system to call `System::stop`) but they were all pretty awkward. In the end I settled on just sending a `Int` `Signal` after stopping the server.

Sorry for the wall of text, but I feel like I'm missing something or the ergonomics on `HttpServer::start/run` could be better. Some function that returns a `Addr` that still lets us use `run` would probably be the ideal in my case.

**Comment by fafhrd91** [comment]
added example https://github.com/actix/examples/tree/master/run-in-thread

**Comment by raphaelsoul** [comment]
> added example https://github.com/actix/examples/tree/master/run-in-thread

404 Not Found

**Comment by aliemjay** [comment]
The new link

https://github.com/actix/examples/tree/master/basics/run-in-thread
