### ISSUE TITLE
Question: collecting a requests payload and serializing

### ISSUE THREAD

**Issue by davedbase** [actix/actix-web#643]
I'm wondering if there's an easy method or good practice for collecting the HttpRequest's: body, query string and other header values (such as cookies) into one JSON?

I'm writing a dynamic custom route handler that passes the values to an FFI. What I'm hoping for is an easy and consistent way to take all the values in the request, JSON serialize them and hand them off.

Currently looking at extractors to do this:
```
let params = Path::<(String, String)>::extract(req);
let info = Json::<MyInfo>::extract(req); 
```
Then merging the values into a dynamic object to create one JSON that I can hand off to the FFI as a string (at least for now until I decide my FFI structure):
```
{
  query: ...,
  body: ...
}
```
Suggestions?

**Comment by DoumanAsh** [comment]
[Extractor](https://actix.rs/actix-web/actix_web/trait.FromRequest.html) should be your way to go I guess
