### ISSUE TITLE
How can i read body at middleware?

### ISSUE THREAD

**Issue by ciyool** [actix/actix-web#645]
I tried by this way,but print nothing  (actix = "0.7.9"      actix-web = "0.7.16")
```rust
pub struct MiddlewareSign;

impl<S:'static> Middleware<S> for MiddlewareSign {
    fn start(&self, req: &HttpRequest<S>) -> Result<Started> {

        let fut = <String>::extract(&req.clone())
            .expect("Failed to extract body")
            .and_then(move |body| {
                println!("Body: {}", body);
                future::ok("".to_string())
            });

        Ok(Started::Done)
    }

    fn response(&self, req: &HttpRequest<S>, resp: HttpResponse) -> Result<Response> {
        println!("Hi from response");
        Ok(Response::Done(resp))
    }

    fn finish(&self, req: &HttpRequest<S>, resp: &HttpResponse) -> Finished {
        println!("Hi from finish");
        Finished::Done
    }
}
```

**Comment by DoumanAsh** [comment]
`fut` you created must be spawned on runtime, but in general.

You can return future that creates new response from `Middleware::start` also

**Comment by ciyool** [comment]
I want to check parameter signature in middleware. Is there any other way to get the body immediately?(actix = "0.7.9" actix-web = "0.7.16")

I found that in the 0.6 version can use the read_to_string() method to get the body.
```rust
let mut body = String::new();
        req.read_to_string(&mut body)
            .map_err(ErrorInternalServerError)?;
```

> `fut` you created must be spawned on runtime, but in general.
> 
> You can return future that creates new response from `Middleware::start` also

**Comment by DoumanAsh** [comment]
You're not supposed to perform blocking calls with async IO in first place and `Middleware` is not really all that flexible for your purpose.

I'd suggest to consider using [extractor](https://actix.rs/actix-web/actix_web/trait.FromRequest.html)

**Comment by fafhrd91** [comment]
It is possible to read body in middleware, but it is does make much sense because if you would consume body, handler wouldn’t get it. You can try extractor instead, FromRequest trait

**Comment by ctopher7** [comment]
is it possible to get request cookies and set response cookies in handler? I cant access ServiceRequest in handler, thats why i need to be able to read body in middleware
