### ISSUE TITLE
Docs - examples don't work on multi-core machines

### ISSUE THREAD

**Issue by mt-inside** [actix/actix-web#646]
The examples of state-handling, even the very simple ones e.g. (https://actix.rs/docs/application/), don't work as expected when actix-web makes more than one copy of the App for >1 thread. On my multi-core machine I seem to get one per core, and who doesn't have >1 core these days?

The problem is that there's more than one copy of the state made, meaning you have e.g. four counters, and the requests are spread over them, each one counting at 1/4 the expected rate. If you're impatient like me, you give up after the first test and assume it's all broken.

The proper solution is a shared object (e.g. Arc<RwLock<T>>), with construction outside the server closure, move semantics on the closure, and a clone() of the state object each time. As a beginner, this took me several days to work out!

**Comment by DoumanAsh** [comment]
Ehm... but we specifically warn about the way state works?

>http server accepts an application factory rather than an application instance. Http server constructs an application instance for each thread, thus application state must be constructed multiple times.

**Comment by mt-inside** [comment]
I guess
1) A lot of people just trying to bootstrap themselves with a library just copy the code out and skim read; I missed it
2) It's not explicit that actix *will* spawn multiple threads in the default instance; in a lot of libraries you'd have to opt in to that
3) As a beginner, those hints were only the start of a very long journey to make it actually work - little things like move semantics on the closure took me forever to work out, but it's only a few more lines to copy-and-paste
4) I still think that warning needs to be more prominent, or baked into the example - I fail to see who'd want that non-deterministic, thread-local version. Surely it only confuses people?

I don't want to start a fight here, just giving feedback on my experience as a rust beginner trying to build a simple web app with your library.

**Comment by DoumanAsh** [comment]
If you look at API, you can see that we expect function that returns your Application, not already created instance which already should hint that each time you gonna get copy of your application on each worker thread

Example with state already has Arced state https://github.com/actix/examples/blob/master/state/src/main.rs

If you think there is a better way to explain it, you can create PR.
Application chapter is here https://github.com/actix/actix-website/blob/master/content/docs/application.md

>It's not explicit that actix will spawn multiple threads in the default instance; in a lot of libraries you'd have to opt in to that

It is explicit if you read API documentation, since there is even API to configure number of workers
Next chapter also talks about underlying HTTP Server https://actix.rs/docs/server/

I'm not sure how we can be even more explicit here, but if you have a better idea, then we'll gladly accept PR

>A lot of people just trying to bootstrap themselves with a library just copy the code out and skim read; I missed it

Having mutable shared state is not really that common thing since blocking in async code is not nice.
I would say it is not prime example for state usage.

>I still think that warning needs to be more prominent, or baked into the example - I fail to see who'd want that non-deterministic, thread-local version. 

Some types can be, by their nature, internally use `Arc` and therefore do not need to be wrapped.
Good example os actix's `Addr` to communicate with actor

**Comment by mt-inside** [comment]
> If you look at API, you can see that we expect function that returns your Application, not already created instance which already should hint that each time you gonna get copy of your application on each worker thread
> 
Not obvious to a beginner I would say. I've programmed before; I'd have got that hint in Ruby, but in Rust it could have been to do with lifetimes or something else I don't understand yet.
> 
> Example with state already has Arced state https://github.com/actix/examples/blob/master/state/src/main.rs
> 
Yeah this was very helpful when I found it, maybe just a link to it would do.
> 
> If you think there is a better way to explain it, you can create PR.
> Application chapter is here https://github.com/actix/actix-website/blob/master/content/docs/application.md
> 
I will genuinely try to find the time.
> 
> > It's not explicit that actix will spawn multiple threads in the default instance; in a lot of libraries you'd have to opt in to that
> 
> It is explicit if you read API documentation, since there is even API to configure number of workers
> Next chapter also talks about underlying HTTP Server https://actix.rs/docs/server/
> 
But the doc we're talking about is front-page, intro stuff. It's designed to be read before the API docs.
> 
> I'm not sure how we can be even more explicit here, but if you have a better idea, then we'll gladly accept PR
> 
> > A lot of people just trying to bootstrap themselves with a library just copy the code out and skim read; I missed it
> 
> Having mutable shared state is not really that common thing since blocking in async code is not nice.
> I would say it is not prime example for state usage.
> 
I agree it's sub-optimal, but it's obvious and deterministic, and a working starting point people can iterate from.
> 
> > I still think that warning needs to be more prominent, or baked into the example - I fail to see who'd want that non-deterministic, thread-local version.
> 
> Some types can be, by their nature, internally use `Arc` and therefore do not need to be wrapped.
> Good example os actix's `Addr` to communicate with actor

Very true, but none of those types are used in that example.

Anyway, I think we just have different ideas about the audience for this doc. Thanks for your time!

**Comment by fafhrd91** [comment]
I don’t see what we can do. Please provide Pr if you have time
