### ISSUE TITLE
Authenticate problem with preflight request with CORS

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#652]
Hello 

I am trying to use the `actix_web::middleware::cors::Cors` with another authenticate middleware using Macaroon:
https://ai.google/research/pubs/pub41892

I am using this example: 
https://github.com/actix/examples/blob/master/web-cors/backend/src/main.rs

```
App::new()
    .middleware(auth_middleware) // <-- middleware verifying Macaroon
    .configure(move |app| {
        Cors::for_app(app)
        // rest of the code
    }
```
(I also tried to reverse `.middleware(...)` and `.configure(...)`, it does not work either)

But I have a problem with the preflight request.
The preflight request does not have an (`Authorize`|`Authorization`|`Access-Key`) header.
But the preflight request is each time intercept by my authenticate middleware verifying its `Access-Key` header, looking for a valid Macaroon. Of course there is none.
So I would like the Cors middleware to be before the authenticate middleware so I wouldn't have any authenticate problem.

So far I manage to make it work by allowing OPTIONS requests in my authenticate middleware, but I find it a bit nasty:

```
impl<S> Middleware<S> for MacaroonCheck {
    fn start(&self, req: &HttpRequest<S>) -> Result<Started> {
        if req.method() == Method::OPTIONS {
            return Ok(Started::Done);
        }
        // rest of the code
    }
}
```

Is there any way to handle this problem properly.

Thanks for all your hard work and happy new year !

**Comment by DoumanAsh** [comment]
Hmmm as far as I remember middleware should be executed on the order of their registrations so if you register cors middleware before anything else it would run first, though I'm not sure how exactly your middleware works

**Comment by ghost** [comment]
Hi, thanks for you reply.

I already tried this:
```
App::new()
    .middleware(auth_middleware) // <-- middleware verifying Macaroon
    .configure(move |app| {
        Cors::for_app(app)
        // rest of the code
    })
```
and this:
```
App::new()
    .configure(move |app| {
        Cors::for_app(app)
        // rest of the code
    })
    .middleware(auth_middleware) // <-- middleware verifying Macaroon
```

But each time the middleware verifying the Macaroon comes first.

**Comment by DoumanAsh** [comment]
Hmmm did you use logs to verify who's getting executed first?

I'll try to check it myself later on

Also can you please show in details what your middlewares return? Is it future with new response or?

**Comment by DoumanAsh** [comment]
Just made simple example with multiple middlewares and `start` method is executed in the order of registration:

```rust
fn index(state: State<()>) -> impl Responder {
    "Hello world"
}

struct First;
impl<S: 'static> Middleware<S> for First {
    fn start(&self, req: &HttpRequest<S>) -> error::Result<Started> {
        println!("First");

        Ok(Started::Done)
    }
}

struct Second;
impl<S: 'static> Middleware<S> for Second {
    fn start(&self, req: &HttpRequest<S>) -> error::Result<Started> {
        println!("Second");

        Ok(Started::Done)
    }
}

struct Third;
impl<S: 'static> Middleware<S> for Third {
    fn start(&self, req: &HttpRequest<S>) -> error::Result<Started> {
        println!("Third");

        Ok(Started::Done)
    }
}

fn app() -> App {
    App::new().middleware(First)
              .route("/", http::Method::GET, index)
              .configure(|app| app.middleware(Second))
              .middleware(Third)
}

fn main() {
    server::new(app).bind("127.0.0.1:8080").unwrap().run();
}
```

So it would be nice if you could verify how your middlewares are being executed...

**Comment by ghost** [comment]
Thanks for your reply. I will retest my code and keep you up to date.

**Comment by ghost** [comment]
I am doing this:
```
App::new()
    .configure(move |app| {
        Cors::for_app(app)
            .resource('url1', |r| { ### handler here ### })
            .resource('url2', |r| { ### handler here ### })
            .resource('url3', |r| { ### handler here ### })
            .register()
    })
    .middleware(auth_middleware) // <-- middleware verifying Macaroon
```
I have added `println!` but still, the Macaroon middleware comes first.

But I am doing this with `actix_web::middleware::cors::Cors`, so my `resource` are attached to `Cors::for_app(app)`, moreover, not having the authenticate middleware before the resources does not make sens. I need to authenticate user before they can access `resource`. And I need to attach my `resource` to the Cors middleware, so these resources are available for other domains.

**Comment by DoumanAsh** [comment]
Ah I see so you don't attach middleware to `App` but rather to particular resources.

Global middleware(attached through `App::middleware`) is always going to come first.
The way you register your resources, attaches `Cors` middleware per resource which will be invoked after all global middlewares are handled, you need to register `Cors` middleware on the same level as your auth middleware or vice versa

**Comment by ghost** [comment]
Thanks for you reply

If I do this:
```
App::new()
    .configure(move |app| {
        let cors_app = app.middleware(auth_middleware);
        Cors::for_app(cors_app)
            .resource('url1', |r| { ### handler here ### })
            .resource('url2', |r| { ### handler here ### })
            .resource('url3', |r| { ### handler here ### })
            .register()
    })
```
or this:
```
App::new()
    .configure(move |app| {
        let cors_app = Cors::for_app(app)
            .resource('url1', |r| { ### handler here ### })
            .resource('url2', |r| { ### handler here ### })
            .resource('url3', |r| { ### handler here ### })
            .register();

        cors_app.middleware(auth_middleware)
    })
```

It does not work either, the authenticate middleware keeps coming first.

But I can't do this because `CorsBuilder` does not have a method `middleware`
```
App::new()
    .configure(move |app| {
        Cors::for_app(app)
            .middleware(auth_middleware) // <- middleware method does not exist
            .resource('url1', |r| { ### handler here ### })
            .resource('url2', |r| { ### handler here ### })
            .resource('url3', |r| { ### handler here ### })
            .register()
    })
```

Is this what you suggested to me or didn't I understand what to do ?

Thanks a lot for all your help.

**Comment by DoumanAsh** [comment]
I think you can just do `App:new().middleware(Cors::build().finish())`

@fafhrd91 Should `Cors` middleware work fine when being globally registered?

**Comment by ghost** [comment]
It works !!! Thanks a lot !

**Comment by ghost** [comment]
I have done this: 
```
let auth_middleware = middleware::MacaroonCheck::new(arguments);
let cors_middleware = Cors::build()
    .allowed_methods(vec!["GET", "POST"])
    .finish();

App::new()
    .middleware(cors_middleware)
    .middleware(auth_middleware)
    .resource('url1', |r| { ### handler here ### })
```
And this works. Thank you so much for your help :)

Edit:
It works without "OPTIONS" in the "allowed_methods"

**Comment by DoumanAsh** [comment]
kk, please hit gitter for similar questions in future

**Comment by fafhrd91** [comment]
There is problem with cors atm, we resolve route before we execute middlewares, so option method has to be registered for route otherwise cors wouldn’t works
