### ISSUE TITLE
Test server listener leak

### ISSUE THREAD

**Issue by jtescher** [actix/actix-web#654]
If you start a test server during tests, when the server is dropped, the accept loop from the underlying server instance is never cleaned up. 

This caps the total amount of tests you can currently run before you start to get:
 ``` 
thread 'actix-web accept loop' panicked at 'Can not create mio::Poll: Too many open files (os error 24)'
```

Looks like the actor system is stopped when the test server is dropped in https://github.com/actix/actix-web/blob/master/src/test.rs#L200, but the accept loops are stuck polling here https://github.com/actix/actix-net/blob/master/actix-server/src/accept.rs#L240 and do not break out of that loop so they build up

**Comment by jtescher** [comment]
Happy to do a PR to stop the server. Seems like you could have TestServer struct store the address of the server actor. Something along the lines of 
```rust 
pub struct TestServer {
    addr: net::SocketAddr,
    ssl: bool,
    conn: Addr<ClientConnector>,
    rt: Runtime,
    backend: Addr<Server>,
}
```

And then in stop you could send the stop signal to the actor

```rust
/// Stop http server
fn stop(&mut self) {
    let _ = self.backend.send(signal::Signal(signal::SignalType::Term)).wait();
    System::current().stop();
}
```

**Comment by fafhrd91** [comment]
PR is always welcomed!

**Comment by abbec** [comment]
I still run in to this with `actix-web` `0.7.19` (which should contain the fixes) if I run more than a certain amount of tests in parallel.
