### ISSUE TITLE
Client Multipart Support

### ISSUE THREAD

**Issue by sameer** [actix/actix-web#657]
Does the actix-web client have support for streaming multipart form data? There is a [client.py](https://github.com/actix/examples/blob/master/multipart/client.py) but no Rust implementation that I see.

**Comment by oleid** [comment]
I have the same problem. And found this:

https://github.com/cetra3/mpart-async

There is an example for actix in their readme.

**Comment by sameer** [comment]
For future readers: I ended up extending https://github.com/ferristseng/rust-multipart-rfc7578 to support Actix, since the library I was working on already used it for hyper.

**Comment by rubdos** [comment]
For future reference: https://github.com/actix/actix-web/issues/195
