### ISSUE TITLE
Use NamedFile with an existing std::fs::File

### ISSUE THREAD

**Issue by wildarch** [actix/actix-web#659]
I have an application written in actix-web that generates a temporary file upon a client request, streams this file to the client and deletes it afterwards. To create the file I am using [`tempfile`](https://docs.rs/tempfile/3.0.5/tempfile/fn.tempfile.html). I would like a convenient way to stream this `File` (with a pseudo filename) to the client, but from what I can tell this is not possible with the current API. I have looked at `NamedFile`, but I can not provide the `File` to it myself, just the path.

My proposal would be to add a function `NamedFile::from_file<P: AsRef<Path>>(file: File, path: Path`. It would be largely equivalent to calling `NamedFile::open`, except that the path is used only to guess mime type and set the content disposition, it does not need to actually exist.

Example usage:
```rust
fn handle_request(_req: &HttpRequest) -> Result<NamedFile> {
    let file = tempfile()?;
    
    // write some data into the file
    // ...

    NamedFile::from_file(file, "data.tar.gz")
}
```

I'm more than willing to whip up a pull request for this in case you're interested :wink:

**Comment by DoumanAsh** [comment]
I suppose it may make sense in such cases
