### ISSUE TITLE
Trailing slash required: /foo/ works, but not /foo

### ISSUE THREAD

**Issue by SamuelMarks** [actix/actix-web#661]
Related: https://github.com/actix/actix-web/issues/241#issuecomment-391487459

Example codebase:
https://github.com/SamuelMarks/actix-diesel-auth-scaffold/tree/a7c20afec9e4ad44acc944a97c30c12e96ba0e12

Crux:
```rust
server::new(|| {
vec![
    App::new()
        .prefix("/bar")
        .resource("/", |r| r.method(Method::GET).with(index)),
    App::new()
        .prefix("/foo")
        .resource("/", |r| r.method(Method::GET).with(index)),
    App::new()
        .resource("/", |r| r.method(Method::GET).with(index)),
]})
```

`curl http://localhost:8000/bar` fails, whereas `curl http://localhost:8000/bar/`, `curl http://localhost:8000/` and `curl http://localhost:8000` succeed.

How do I configure such that `/bar` and `/bar/` go to the sample resource?

**Comment by DoumanAsh** [comment]
There is no option per se to configure such behavior.

@fafhrd91 ping

**Comment by fafhrd91** [comment]
App prefix does not support trailing slash. But Scope does
