### ISSUE TITLE
Stream body not stopping polling after client disconnection

### ISSUE THREAD

**Issue by earthengine** [actix/actix-web#662]
```rust
extern crate actix_web;
extern crate futures;
extern crate bytes;
use actix_web::{server, App, HttpRequest, Responder, Body, HttpResponse, http::Method};

fn dumy(_req: &HttpRequest) -> Result<impl Responder, actix_web::Error> {
    let mut c = 0;
    let buf = [b'='; 4096];
    Ok(HttpResponse::Ok()
        .body(Body::Streaming(
            Box::new(futures::stream::poll_fn(move || {                
                c+=1;
                if c>10000 { Ok(futures::Async::Ready(None)) }
                else {
                    println!("{} blocks iterated", c);
                    let mut b = bytes::Bytes::new();
                    b.extend_from_slice(&buf);
                    Ok(futures::Async::Ready(Some(b)))
                }
            }))
        )))
}

fn main() {
    server::new(||{
        App::new()
        .resource("/favicon.ico", |r| {
            r.f(|_| HttpResponse::NotFound())
        })
        .resource("/{tail:.*}", |r| r.method(Method::GET).f(dumy))        
    }).bind("0.0.0.0:12345")
      .expect("cannot bind port 12345")
      .run();
}
```

When running the above code, and open "localhost:12345" in browser, in console you can see the messages

```text
...
123 blocks iterated
124 blocks iterated
...
```
keep comming up

Even when you close the browser page (the underline connection should be closed automatically), the iteration message is still coming up. Even the "Ctrl + C" signal cannot stop it until very late.

As the connection was closed, it should be useless to poll the stream again. This is a wastful behaviour.

# Potential security risk - DOS attack

**As the server keep polling the stream through to the end of the file, even when the connection was closed, an attacker can abuse this to perform DOS attack.**

They can simply keep creating connections and get a medium sized file (1MB for example), and then drop the connection after receiving the first data block. The server will have to poll the file through to the end, and it will spend all computation time on doing this, effectively stopping the server from serving new requests.

To avoid this attack, the server have to stop polling the stream as soon as the connection being closed.

# Observations
When the connection is alive, and the file is a media file, the client have control to the data transfer. For example, when use similar code to send data read from an MP4 file, and use the browser to play it, you can see the polling being paused and continued as the browser requested.

However, as soon as the browser page being closed, the polling losts control - it is suddently accerelated to the highest possible speed. This means the server knows the connection was closed and tries to do some clean up work, and this work includes polling the stream to the end. This part of the work should be unnecessory and it is just wasting computation power and time.

**Comment by earthengine** [comment]
Simply change
```rust
if c>10000 { Ok(futures::Async::Ready(None)) }
```
to

```rust
if c>1000 { Ok(futures::Async::Ready(Some(bytes::Bytes::new()))) }
```

run the program, open a browser page, then close the page. The server will end up unstoppable. The only way to stop the server is `kill -9` (in a Ubuntu VPS).

**Comment by earthengine** [comment]
Follow up

I tried to write simple clients to check the behaviour of actix. All attempts using Rust or C# was not able to replicate this issue - as soon as you close the connection, the polling stops. If you shutdown only the "send" part before close, then you expect a few more polls before it stops.

However, the browsers (Firefox and Edge were tested) are different. Even you are closing the browser, not just the page, to ensure all connection being physically disconnected, you still seeing the polling through to the end.

I couldn't explain this - maybe the browsers have special socket options so it have different behaviour? If the server is written in Hyper, and having "RUST_LOG=debug", I can see a message shows the connection was reset by peer. This means the browser is not closing the socket, it just sending a "reset" packet to the server to indicate it wants to reset the connection. Maybe this is the difference, but I don't know how to write clients to simulate this.

**Comment by DoumanAsh** [comment]
From my observation, it seems the response with streaming body does take a while to process(despite connection being closed and even keep-alive being fired) but it doesn't wait for complete stream processing, pipeline detects error eventually before stream is completed

**Comment by earthengine** [comment]
@DoumanAsh Looks like to me "eventually" means the TCP TIME_WAIT period. This is usually set to 2 min, way longer than my patience.

So now my explaination is

* The browser try its best to do a graceful disconnection, so it first shutdown the send, and then wait for the read to receive EOF, then close.

* Therefore the polling is actually issued by the client OS because it need to wait for "no more data" from the server.

* The polling will eventually finish once TIME_WAIT timed out. But 2 mins is already too long for many purpose.

* actix, however should stop polling once the TCP connection receives EOF. Any further polling is wasteful as the client don't actually do anything with the data being sent in this period.

This means the fix should be to shutdown the "send" as soon as EOF received. This is what TCP graceful disconnection mean to be: it does not mean you should spend an hour to send useless data after the client requested a graceful disconnection.

**Comment by DoumanAsh** [comment]
I know what it means, what I said are purely my observations when I was checking whether there is issue or not

**Comment by earthengine** [comment]
@DoumanAsh I think it is still too much wastful to send data that the client didn't actually need. As I said, stop sending after the receiving of EOF might be better, as you already know the connection was no longer needed.

**Comment by DoumanAsh** [comment]
I understand that, but it is not as easy as you think it is.
There are no good ways to determine that connection is closed aside from performing read/write as far as I know so it is not as easy as just: "Oh check if EOF and stop doing stuff"
Not sure if tokio/mio notifies on closed connection unless you poll socket

**Comment by earthengine** [comment]
Usually when I write socket code directally, I would call `shutdown(Send)` in the receiving handler if I get zero sized data. I think this is how things should happen. 

In Rust, there is a little difficulty: in both the sending future and the receiving future, you either have to have access to the socket with a `&mut` reference (violates the ownership rules), or you can signal the other future to stop.

**Comment by fafhrd91** [comment]
problem is in `dumy` function.

* your stream always ready, so it will fill up any buffer.
* browser enables gzip compression by default, and this bytes `[b'='; 4096];` compress well

so both gives this problem, actix tries to pull stream until it ready, and writes to internal buffer. buffer size is 64kb. but response payload get compressed extremely well and can not fill up 64kb buffer. so we get busy loop. first of all, in current implementation it is not easy to fix. and second, i am not sure how relevant this problem at all. is this real production use case

**Comment by earthengine** [comment]
Your argument about the gzip compression does not make sense - it only makes sense on artificial dummy data. However, In reality if I try to host a big video file (2GB in my case) through a stream like in `dumy`, I have the same problem - even when the browser was closed the server is still keep polling to the end of the file. Actually this was how I figured out this problem. In this case, I suspect the compression would not be so good as you said.

But your other point advised me something. I server the file by using `std::fs::File`. The internal handle, however, would not return `std::io::ErrorKind::WouldBlock`, therefore the stream will always ready. So Maybe I need to figure out how to open the file with async options?

**Comment by fafhrd91** [comment]
To make gzip argument sense try to compress [b'=‘, 100000] with gzip. If you found this problem with fs::File, then you use it wrong way, fs::File is blocking so your server serve only one request. And even then actix-web buffers only 64kb, after that it will detect disconnect. Try your example with random data

**Comment by fafhrd91** [comment]
At the moment actix-web can not protect from busy loops created by developers.

std::fs::File can not be used directly, it is blocking
