### ISSUE TITLE
How can I respond to a file in asynchronous code?

### ISSUE THREAD

**Issue by Hentioe** [actix/actix-web#663]
DEMO CODE:

``` rust
fn find(req: &HttpRequest<AppState>) -> Box<Future<Item = HttpResponse, Error = Error>> {
    req.state()
        .f
        .send(file::FileName("actix.jpg".to_owned()))
        .from_err()
        .and_then(|r| match r {
            Ok(path) => {
                // The file was successfully found and the path was returned.
                // Here responds to a file
            }
            Err(e) => Ok(HttpResponse::with_body(
                http::StatusCode::NOT_FOUND,
                "File not found",
            )),
        })
        .responder()
}
```

If `Item = HttpResponse` I can't respond to a file. If `Item = NamedFile` I can't respond to an error.

I feel helpless.

**Comment by DoumanAsh** [comment]
That's how I did it in past

https://github.com/DoumanAsh/roseline.rs/blob/5c723d6e638d0649e5bd6b442b03067d945b0114/web/src/server/mod.rs#L228-L240

But I always transformed error into response myself

**Comment by DoumanAsh** [comment]
Please use [gitter](https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for such sort of queries
