### ISSUE TITLE
Client request chaining

### ISSUE THREAD

**Issue by sameer** [actix/actix-web#668]
Is it possible to chain client requests? I tried using `Future::join` but it times out as if the client future is not running on actix.

Something like below:

```rust
let first_response = client::get("http://localhost/").finish().unwrap().send();
let second_response = client::get("http://localhost/").finish().unwrap().send();
actix::run(||
    first_response
        .join(second_response)
        .and_then(|(first, second)| println!("Waited for both!"));
)
```

Except I am using the future as a response to an actix server request (`FutureResponse<HttpResponse>`).

**Comment by fafhrd91** [comment]
works in master
