### ISSUE TITLE
New `index_file` handling doesn't distinguish between `directory` and `directory/`

### ISSUE THREAD

**Issue by rocallahan** [actix/actix-web#671]
The code on the 0.8 branch serves `directory/index.html` for requests to both `/directory` and `/directory/`. That doesn't work properly for `/directory` because it breaks relative links in `directory/index.html`. E.g. if `directory/index.html` contains `<a href="hello.html">`, that should resolve to `/directory/hello.html`, but when `directory/index.html` is served for the URL `/directory`, the link will resolve to `/hello.html`, which is wrong.

**Comment by rocallahan** [comment]
I think probably `/directory` should not serve the contents of `directory/index.html` but redirect to `/directory/` (which serves `directory/index.html`) instead.

**Comment by DoumanAsh** [comment]
~`/directory` should just serve `/director/index.html`~

**Comment by DoumanAsh** [comment]
@rocallahan Ok, now I think about it, there might be some validity to your idea so we can add configuration option to perform redirect, but by default we should serve from both variants of directories since not everyone rely on relative links
