### ISSUE TITLE
Send http 2.0 PUT request and failed

### ISSUE THREAD

**Issue by xtlsheep** [actix/actix-web#675]
I was trying to use active-web to send a http 2.0 PUT request from client to server with code like this:

```
req = client::ClientRequest::build()
        .method(http::Method::PUT)
        .uri(client_url)
        .version(http::Version::HTTP_2)
        .json(req_body.clone())
        .unwrap();
rsp = client_sys.block_on(req.send()).unwrap();

```
And I got the following error with RUST_BACKTRACE:

[> running 1 test
> Started sim-nrf: localhost:8090 with DB at localhost:6379
> test test_mgmt_nfinstances_PUT_GET_DELETE_1_PreR15_0_0 ... FAILED
> 
> failures:
> 
> ---- test_mgmt_nfinstances_PUT_GET_DELETE_1_PreR15_0_0 stdout ----
> thread 'test_mgmt_nfinstances_PUT_GET_DELETE_1_PreR15_0_0' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(Disconnect)', libcore/result.rs:1009:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> stack backtrace:
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1: std::sys_common::backtrace::print
>              at libstd/sys_common/backtrace.rs:71
>              at libstd/sys_common/backtrace.rs:59
>    2: std::panicking::default_hook::{{closure}}
>              at libstd/panicking.rs:211
>    3: std::panicking::default_hook
>              at libstd/panicking.rs:221
>    4: std::panicking::rust_panic_with_hook
>              at libstd/panicking.rs:476
>    5: std::panicking::continue_panic_fmt
>              at libstd/panicking.rs:390
>    6: rust_begin_unwind
>              at libstd/panicking.rs:325
>    7: core::panicking::panic_fmt
>              at libcore/panicking.rs:77
>    8: core::result::unwrap_failed
>              at libcore/macros.rs:26
>    9: <core::result::Result<T, E>>::unwrap
>              at libcore/result.rs:808
>   10: _1_PreR15_0_0_NRFNFManagementService_NFInstance::test_mgmt_nfinstances_PUT_GET_DELETE_1_PreR15_0_0
>              at tests/1_PreR15_0_0_NRFNFManagementService_NFInstance.rs:106
>   11: _1_PreR15_0_0_NRFNFManagementService_NFInstance::test_mgmt_nfinstances_PUT_GET_DELETE_1_PreR15_0_0::{{closure}}
>              at tests/1_PreR15_0_0_NRFNFManagementService_NFInstance.rs:33
>   12: core::ops::function::FnOnce::call_once
>              at libcore/ops/function.rs:238
>   13: <F as alloc::boxed::FnBox<A>>::call_box
>              at libtest/lib.rs:1468
>              at libcore/ops/function.rs:238
>              at liballoc/boxed.rs:672
>   14: __rust_maybe_catch_panic
>              at libpanic_unwind/lib.rs:102
> Panic in Arbiter thread, shutting down system.](url)

In package capture I attacked it's like the connection is closed incorrectly. Therefore is this the right way to send out a http 2.0 request with actix-web? Thanks a lot.
[HTTP_2.zip](https://github.com/actix/actix-web/files/2784999/HTTP_2.zip)

**Comment by fafhrd91** [comment]
Client does not support http2, it is todo for 0.8

**Comment by xtlsheep** [comment]
Is there a road map that when will it be done?

**Comment by Lingli05** [comment]
@fafhrd91 can you give me some ideas on how to implement http2 for Client? I should be able to implement it for you.

**Comment by fafhrd91** [comment]
i am planing to switch to actix-http for lowlevel server and client impls. so any work related to http2 will go to actix-http

**Comment by fafhrd91** [comment]
@Lingli05 i can move repo to actix org and give you access if you want to work on http2. but you would need to understand how actix-net works

https://github.com/fafhrd91/actix-http

**Comment by fafhrd91** [comment]
i added http/2 support to actix-http
