### ISSUE TITLE
actix client no_default_headers method will not remove date header.

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#678]
Hello,
actix client no_default_headers method will not remove `date` header.
example code :
```
    client::ClientRequest::build()
        .uri("https://mirror.cert.tools")
        .method(http::Method::GET)
        .no_default_headers()
        .header(http::header::HOST, "mirror.cert.tools")
        .finish()
        .unwrap()
        .send()
        .map_err(Error::from)
        .and_then(|resp| {
            resp.body()
                .from_err()
                .and_then(|body| Ok(HttpResponse::Ok().body(body)))
        })
        .responder()
```
but request look like following response:
```
GET / HTTP/1.1
host: mirror.cert.tools
connection: close
date: Sun, 27 Jan 2019 18:43:09 GMT
```

**Comment by fafhrd91** [comment]
date is required field.

**Comment by uncotion** [comment]
Thank you.
I couldn't find any reference requirement of date header in `request`, It's just required in `response`.
for example in the following image I did attach Firefox default request headers and as you can see, date is not available.
<img width="645" alt="screen shot 2019-01-27 at 11 22 31 pm" src="https://user-images.githubusercontent.com/39458402/51806090-6f900580-226d-11e9-8f92-473718bd4f6d.png">
Could you please provide me reasons of sending date filed ?

**Comment by fafhrd91** [comment]
i see, we can remove it

**Comment by uncotion** [comment]
@fafhrd91 : thanks.

**Comment by vladgovor77771** [comment]
Any updates here? Date header still in HeaderMap even if I use `.no_default_headers()` in 3.3.3 version of actix_web.

Proof code:
```rust
let builder = SslConnector::builder(SslMethod::tls()).unwrap();

let client = Client::builder()
  .no_default_headers()
  .max_http_version(Version::HTTP_2)
  .connector(Connector::new().ssl(builder.build()).finish())
  .finish();
dbg!(
  client
    .get("https://httpbin.org/anything")
    .send()
    .await?
    .body()
    .await?
);
```

Also, I could't find how to disable Content-Length header if I send request without body. Is it real?

**Comment by asonix** [comment]
~that code is debugging the response body, not the request headers~

edit: i see that this is an echo server, oops.
