### ISSUE TITLE
If-Modified-Since is not ignored if If-None-Match is specified

### ISSUE THREAD

**Issue by bbigras** [actix/actix-web#680]
> A recipient must ignore If-Modified-Since if the request contains an If-None-Match header field; the condition in If-None-Match is considered to be a more accurate replacement for the condition in If-Modified-Since, and the two are only combined for the sake of interoperating with older intermediaries that might not implement If-None-Match.

https://greenbytes.de/tech/webdav/rfc7232.html

I tested with curl and I had a 304. `if-modified-since` matched but I used a bogus `if-none-match`.

**Comment by DoumanAsh** [comment]
afaik I think we currently ignore non-matching `If-None-Match` and try to match `If-Modified-Since`

**Comment by DoumanAsh** [comment]
We should take out [If-Modified-Since](https://github.com/actix/actix-web/blob/master/src/fs.rs#L444) only if `If-None-Match` is not present regardless of whether it matches

**Comment by bbigras** [comment]
> We should take out If-Modified-Since only if If-None-Match is not present regardless of whether it matches

Sorry if I'm not understanding correctly. Are you suggesting that both `If-Modified-Since` and `If-None-Match` should match to result in a 304?

My problem is that when building docker image with NixOS's [dockerTools.buildLayeredImage](https://nixos.org/nixpkgs/manual/#ssec-pkgs-dockerTools-buildLayeredImage), the modified date on the file are all set to 1970-01-01 00:00:01Z. I reported the issue (https://github.com/NixOS/nixpkgs/issues/54955) but it could be a limitation of the way NixOS handles things.

So when I update my static files I get new etags but with the same modified date which cause 304 problems with actix-web.

**Comment by DoumanAsh** [comment]
I meant that we should ignore presence of `If-Modified-Since` if there is `If-None_match` as per RFC

You can disable `Last-Modified` check via custom config btw https://actix.rs/actix-web/actix_web/fs/trait.StaticFileConfig.html

**Comment by bbigras** [comment]
> I meant that we should ignore presence of If-Modified-Since if there is If-None_match as per RFC

:+1: 

> You can disable Last-Modified check via custom config btw https://actix.rs/actix-web/actix_web/fs/trait.StaticFileConfig.html

oh thanks!!

**Comment by wilhg** [comment]
Hi @DoumanAsh , if it is possible, I would like to try to fix this bug for starting my contribution. Is it OK?

**Comment by DoumanAsh** [comment]
@cuebyte Sure, contributions are appreciated
