### ISSUE TITLE
StaticFiles does not decode %20 in urls

### ISSUE THREAD

**Issue by vandenoever** [actix/actix-web#683]
When serving a directory with StaticFiles, files that contain a space cannot be opened if the URL contains '%20' instead of ' '. This is true in Firefox.

One way to get this to work is to add ' ' to UNRESERVED in `src/uri.rs`.

Probably a better fix is to add a quoter to `src/uri.rs` that decodes all characters and uses that in `get_decoded` in `src/param.rs`.

**Comment by fafhrd91** [comment]
`%20` works in master
