### ISSUE TITLE
Client long-polling request

### ISSUE THREAD

**Issue by ufoscout** [actix/actix-web#684]
I need to perform an HTTP request to a remote server that requires the client to support long-polling.
In summary, the server keeps the connection open and streams JSON events in the response body when they are available. The event stream response is separated with new lines.

How can I read the response body line by line?
Here is my attempt:
```rust 
    actix::run(|| {
        let request_data = ...;
        ClientRequest::post("https://127.0.0.1:8080/eventStream")
            .header(header::ACCEPT, "application/json")
            .timeout(Duration::from_secs(999999)) // How to set the timeout to never?
            .json(request_data)
            .unwrap()
            .send()
            .map_err(|err| panic!("Connection failed. Err: {}", err))
            .and_then(|response| {
                println!("Response: {:?}", response);

                // I would like to read the response body line by line and send each line to an actor
                response.body()
                    .map_err(|_| ())
                    .map(|bytes| {
                        println!("Read body line by line");
                        println!("{:?}", bytes);
                        ()
                    });

                Ok(())
            })
    });
```

I cannot find any documentation or example about it.

**Comment by DoumanAsh** [comment]
I think currently there is no way to remove timeout completely? Need to check it

**Comment by ufoscout** [comment]
@DoumanAsh 
apart from the timeout issue, do you have an example that shows how to read the body line by line?

**Comment by DoumanAsh** [comment]
https://actix.rs/actix-web/actix_web/trait.HttpMessage.html#method.readlines

But then there is size limit

**Comment by fafhrd91** [comment]
ClientResponse implements `Stream` trait, you can combine response with https://actix.rs/actix-web/actix_web/dev/struct.Readlines.html

this is for master
