### ISSUE TITLE
fs: Allow to remove/configure content-disposition

### ISSUE THREAD

**Issue by idMysteries** [actix/actix-web#686]
How to remove filename or (and) Content-Disposition?
![image](https://user-images.githubusercontent.com/11484976/52296553-c0031380-298f-11e9-9100-4fbf671d66ac.png)

```rust
fn index(_: &HttpRequest) -> Result<fs::NamedFile> {
    Ok(fs::NamedFile::open("static/index.html")?)
}
....
.resource("/", |r| r.f(index))
```

**Comment by DoumanAsh** [comment]
You cannot remove it currently.
Why it is necessary though?

**Comment by idMysteries** [comment]
Ok. So... How to do it right? I want to open index.html when entering the site.
In the examples, this is implemented as follows. But all other sites do not show any content-disposition.


For ex. I want it like on facebook and on another web-sites 
![image](https://user-images.githubusercontent.com/11484976/52330075-7ead4b00-2a05-11e9-9a59-c47bebb57b81.png)
![image](https://user-images.githubusercontent.com/11484976/52330221-ec597700-2a05-11e9-8c07-9a3535258136.png)

**Comment by DoumanAsh** [comment]
In most cases `inline` is default value for `Content-Disposition` for most browsers. Note that it is not part of standard and therefore omitting `Content-Disposition` can be interpreted in different way AFAIK.

The question is why you want to remove the header?
If it is because of how other web sites behave, then there is really no concern with having it as it is because `filename` when used with `inline` only affects how browser is going to save web page.

**Comment by idMysteries** [comment]
When I open "messages" on "vk.com"
![image](https://user-images.githubusercontent.com/11484976/52330698-1c554a00-2a07-11e9-9f4e-cb7d0504d62e.png)
![image](https://user-images.githubusercontent.com/11484976/52330725-2aa36600-2a07-11e9-80f6-d1b4bdb5198a.png)

POST + referer?

**Comment by idMysteries** [comment]
I just want to open the page in a browser so that the file extension is not shown. And so that would not show how this file is called on the server

**Comment by DoumanAsh** [comment]
I see, it is not possible to remove file name from this header as of now,

**Comment by idMysteries** [comment]
I want to show not website.com/index.html, but website.com/index or just website.com.
This does not do?

Maybe just send an HttpResponse with the body. And the body read from the file?

**Comment by idMysteries** [comment]
```rust
HttpResponse::Ok().body(read_from_file("static/index.html")?)
```

But I'm not sure that this is a good idea. Or is it still normal?

**Comment by DoumanAsh** [comment]
Nothing stops you from constructing response yourself if you want.

It is up to you how to do it, but reading from file system is usually involves blocking so it is not always good idea

We set `filename` always when serving it https://github.com/actix/actix-web/blob/master/src/fs.rs#L204-L207 as of now

**Comment by idMysteries** [comment]
For example in apache there is
[Apache RewriteRule](https://www.digitalocean.com/community/questions/apache-remove-php-and-html-file-extensions-using-mod_rewrite-in-httpd-conf)

**Comment by idMysteries** [comment]
Maybe I ask too much, but I just want to use NamedFile to work the way I described.
> It is up to you how to do it, but reading from file system is usually involves blocking so it is not always good idea

NamedFile::open is not a blocking operation?

**Comment by idMysteries** [comment]
I think that content-disposition is better to use only for images and video or for text that needs to be downloaded.
And remove it from the response, if it is used to transmit html or customize this header.

**Comment by DoumanAsh** [comment]
>NamedFile::open is not a blocking operation?

Internally it uses thread pool to offload file ops without blocking actix-web worker.

>I think that content-disposition is better to use only for images and video or for text that needs to be downloaded.

it will be configurable

**Comment by idMysteries** [comment]
> it will be configurable

Well, I hope we understand each other.

**Comment by CoderOffka** [comment]
> ```rust
> HttpResponse::Ok().body(read_from_file("static/index.html")?)
> ```
> 
> But I'm not sure that this is a good idea. Or is it still normal?

But what if it returns the Future?

**Comment by utterstep** [comment]
We've stumbled upon this issue while trying to move some of our production web code to actix: it looks like iPhone default browser fails to load page, which was returned with Content-Disposition specified.
As this behavior currently is not optional we had to stay with nginx for index page service for now.

**Comment by fafhrd91** [comment]
added `File::disable_content_disposition()` and `NamedFile::disable_content_disposition()` methods
