### ISSUE TITLE
fs: Set content-type charset=utf-8 automatically for text/plain

### ISSUE THREAD

**Issue by idMysteries** [actix/actix-web#689]
I think it's useful to set it automatically

Default content-type
![image](https://user-images.githubusercontent.com/11484976/52337905-fab18e00-2a19-11e9-92c8-28d856c6051c.png)
With .set_content_type(mime::TEXT_PLAIN_UTF_8)
![image](https://user-images.githubusercontent.com/11484976/52338139-9a6f1c00-2a1a-11e9-89bc-7c7730a855e4.png)

**Comment by DoumanAsh** [comment]
It is wrong for library to assume user's intention.

To be sure we would need to detect actual type of content.
In short utf-8 should not be default
