### ISSUE TITLE
Feature request: Query with LHS Brackets

### ISSUE THREAD

**Issue by torepettersen** [actix/actix-web#691]
It would be quite convenient if LHS brackets were supported as query parameters. This could be helpful if you f. ex need to limit an attribute both upwards and downwards. Example query could be:

```
GET /api/items?price[gte]=50&price[lte]=500
```
And I would expect to be able to read the result from a structure like this:
```
#[derive(Deserialize)]
struct GteLte {
    gte: i32,
    lte: i32,
}

#[derive(Deserialize)]
struct Info {
    price: GteLte,
}

fn index(info: Query<Info>) -> String {
    format!("Price between {} and {}!", info.price.gte, info.price.lte)
}
```

**Comment by fafhrd91** [comment]
This format is outside of project scope. If you have serde decoder, it should be easy to integrate it.

Actix itself uses serde_urlencoded for decoding.

**Comment by torepettersen** [comment]
Thanks for clarifying
