### ISSUE TITLE
tuple parameter signature in handler function not supported in TestServer

### ISSUE THREAD

**Issue by Dowwie** [actix/actix-web#694]
The tuple parameter signature isn't working in a function handler registered in a TestServer:
```rust
fn my_func((path, req): (Path<i32>,  HttpRequest<MyState>))
                    -> impl Future<Item = HttpResponse, Error = AWError>{
 ...
}

fn create_app(state: MyState) -> App<MyState> {
   App::with_state(state)
        .scope("/my_resource/{bla}", |res_level| {
            res_level
            .resource("", |r| {
                r.method(Method::POST)
                 .with_async(my_func)
             })


...
TestServer::with_factory(move || create_app(state)

```

**Comment by idMysteries** [comment]
```rust
fn my_func((path, req): (Path<i32>,  req: HttpRequest<MediaSvcState>))
```
change to
```rust
fn my_func((path, req): (Path<i32>, HttpRequest<MediaSvcState>))
```

**Comment by idMysteries** [comment]
And I think it should be like this
```rust
fn my_func((path, state): (Path<i32>,  State<MyState>))
```

**Comment by Dowwie** [comment]
@CoderOffka Thanks.  That example was put together in a hurry.  The tuple param still does not work.

My original ``HttpRequest<State>`` is as it should be.  I'm successfully using actix-web across many handlers. The tuple param bug, or more likely lack of feature, is specific to the TestServer environment.  This is likely a feature gap because TestServer is not synchronized with new feature development.

**Comment by fafhrd91** [comment]
```rust
fn my_func(path: Path<i32>, state: State<MyState>)
```

**Comment by Dowwie** [comment]
@fafhrd91 no point being made here.  This issue was opened to identify the feature gap.

What I'm saying is to ignore the parameters that I used in the example and see that the tuple param that is the standard in latest actix-web server isn't in the TestServer App

**Comment by fafhrd91** [comment]
should work with 1.0
