### ISSUE TITLE
server KeepAlive::Disable is broken in later release

### ISSUE THREAD

**Issue by sallyyu0** [actix/actix-web#695]
It's still working in 0.7.8, but not latest which I've tried 0.7.16/17/18 and client always gets connection reset from server after 5 seconds, which I assume is the default 5 seconds. 

Here is what I have for Http2 server:
    server::new(move || { 
       ....
    )
    .bind(server_ip_port)
    .unwrap()
    .keep_alive(KeepAlive::Disabled)  <==
    .shutdown_timeout(1)
    .start();

    let _ = sys.run();

Here is what I got on client side:

Client[] connecting to Server[172.17.0.2:80] idle_duration=30, test_duration=300
Delaying.....30 seconds
Delaying.....30 seconds
Delaying.....30 seconds
Delaying.....30 seconds
Delaying.....29 seconds
Delaying.....29 seconds
Delaying.....29 seconds
Delaying.....29 seconds
Delaying.....29 seconds
Delaying.....28 seconds
Delaying.....28 seconds
Delaying.....28 seconds
Delaying.....28 seconds
Delaying.....28 seconds
Delaying.....27 seconds
Delaying.....27 seconds
Delaying.....27 seconds
Delaying.....27 seconds
Delaying.....27 seconds
Delaying.....27 seconds
Delaying.....26 seconds
Delaying.....26 seconds
Delaying.....26 seconds
Delaying.....26 seconds
Delaying.....26 seconds
[Mon 2019-02-11 21:04:19 UTC]remote server close connection.
[Mon 2019-02-11 21:04:19 UTC]Connection to 172.17.0.2 is reset.

**Comment by fafhrd91** [comment]
this is fixed in master. I am not sure about 0.7 branch
