### ISSUE TITLE
feature request : Server CONNECT header to supporting https requests over http proxy

### ISSUE THREAD

**Issue by uncotion** [actix/actix-web#696]
Hello,
I would like to write a simple HTTP proxy server that can support HTTPS too.
Based on [7231 RFC](https://tools.ietf.org/html/rfc7231#section-4.3.6) server must support CONNECT header.
I could not find any reference in Actix-web that point out CONNECT header.
Would you please give a **hint** for implementing CONNECT functionality.
In my opinion, if Actix could support this future internally will be great.

<img width="594" alt="screen shot 2019-02-12 at 4 19 52 pm" src="https://user-images.githubusercontent.com/39458402/52637144-566e9200-2ec6-11e9-8f5b-4ccb9bc50476.png">
I the above, I have no idea to handling this.

------

It must support something like this :
<img width="918" alt="screen shot 2019-02-12 at 4 32 38 pm" src="https://user-images.githubusercontent.com/39458402/52637253-a77e8600-2ec6-11e9-9ed3-1f97766a82ee.png">

Thanks.

**Comment by fafhrd91** [comment]
I don't see what actin-web could do for CONNECT. there is nothing special in CONNECT just ready request's payload and create response stream.

**Comment by uncotion** [comment]
I think streams have another intention because the problem is related to handling tunnel's payload (red handshake in the below image).
CONNECT behavior's is a little bit different.
After CONNECT's server response, the connection stay's open and binary protocol data will transfer in the same connection, something like WebSocket connection structure.
In fact, CONNECT header will create an HTTP Tunnel that can transfer none-HTTP connections that can use for transfer HTTPS connections over HTTP proxy also.
I did attach an image that describes the connection structure.
![2019-02-16 00 41 53](https://user-images.githubusercontent.com/39458402/52884619-5c829e00-3166-11e9-9cf4-d44f32d9f00a.jpg)

**Comment by fafhrd91** [comment]
it is your task to build tunnel and it is possible with actix

**Comment by fafhrd91** [comment]
it is similar to websockets

**Comment by uncotion** [comment]
I'm not good at actix, I think I must build the task by using Actix Context.
Thank you very much Nikolay.
