### ISSUE TITLE
How to shoot yourself in the foot. Best practices: using State with r2d2

### ISSUE THREAD

**Issue by idMysteries** [actix/actix-web#698]
CPU usage without (default server) and with keep-alive timeout (5 sec)
And after 1 day without keep-alive timeout, the server is frozen. Any request resulted in a timeout error.
Keep-alive timeout 5 fixed server timeout error
![image](https://user-images.githubusercontent.com/11484976/52809433-43fc8000-30a1-11e9-950b-66b97a5e06f3.png)

Memory usage without keep-alive timeout increases by 200mb/day
![image](https://user-images.githubusercontent.com/11484976/52845207-8fea0c00-3117-11e9-85e2-f4a7757140d1.png)
With keep-alive timeout 5: 1 day +100mb (14 feb)
![image](https://user-images.githubusercontent.com/11484976/52809916-6e9b0880-30a2-11e9-957a-e190bc0afcfd.png)

**Comment by fafhrd91** [comment]
What type of load to do you have? Do you serve static files?

**Comment by idMysteries** [comment]
Yeah. Static files only + api with a scope("/api", ...)
![image](https://user-images.githubusercontent.com/11484976/52811093-4f51aa80-30a5-11e9-92bd-afad7d9ed563.png)

**Comment by fafhrd91** [comment]
Could you split static files to separate process?

**Comment by idMysteries** [comment]
What do you have in mind?

**Comment by fafhrd91** [comment]
I’d like to understand if this is static files related or not

**Comment by idMysteries** [comment]
Delete code with static files and look for the usage after a day?

**Comment by fafhrd91** [comment]
Yes, or start two processes. One with logic and another with static files

**Comment by idMysteries** [comment]
This will help with RAM. But why is the load on cpu growing without keep-alive timeout?
Okay.. I will try

**Comment by fafhrd91** [comment]
I guess this is bug with stream handling. I just need confirmation.

**Comment by idMysteries** [comment]
Ok. Let's try w/o StaticFiles. But does NamedFile matter?
![image](https://user-images.githubusercontent.com/11484976/52811788-03a00080-30a7-11e9-8352-d46c03258325.png)

**Comment by fafhrd91** [comment]
It does. Static files uses namedfile internally

**Comment by idMysteries** [comment]
So... And without namedfile...
But I'm using NamedFiles in all functions hehe...
![image](https://user-images.githubusercontent.com/11484976/52812019-8fb22800-30a7-11e9-9afd-12578b41835c.png)
Ok. Let's remove it all :hocho:

**Comment by idMysteries** [comment]
OK. I'll write in another day
off top: did you see it https://github.com/actix/actix-web/issues/685

**Comment by idMysteries** [comment]
After 12 hours without NamedFile and StaticFiles:
1. No CPU usage (with keep-alive timeout)
2. +50mb smoothly (+1mb/~14min)
![image](https://user-images.githubusercontent.com/11484976/52842589-94f78d00-3110-11e9-9037-8387d6fe8760.png) ![image](https://user-images.githubusercontent.com/11484976/52842545-785b5500-3110-11e9-9e97-36a86874fdee.png)
> Memory usage without and with keep-alive timeout increases by 100mb/day

Fix: 200mb/day without keep-alive timeout and 100mb/day with keep-alive timeout

**Comment by idMysteries** [comment]
@fafhrd91 ok...
After 36+ hours
1. CPU usage +~0.5%
2. Memory usage (without NamedFile and StaticFiles) +180mb
![image](https://user-images.githubusercontent.com/11484976/52899757-a61ec780-31fe-11e9-9d4a-f774de95808c.png)

**Comment by fafhrd91** [comment]
Ok, I’ll take a look

**Comment by idMysteries** [comment]
And I'm using server with OpenSSL

**Comment by idMysteries** [comment]
@fafhrd91 site can’t be reached. Time out error.
Memory usage 224mb (after 60 hours)

**Comment by fafhrd91** [comment]
Could you check netstat, how many opened connections

**Comment by idMysteries** [comment]
>netstat -an | wc -l

2142
59 on port 443
holy ... 1009 to mongodb... But I'm using pool with 5 connections...

**Comment by idMysteries** [comment]
OK... It's interesting...
![image](https://user-images.githubusercontent.com/11484976/52915983-6f72ab00-32eb-11e9-9bd4-3d16d62d790b.png)
![image](https://user-images.githubusercontent.com/11484976/52916069-5dddd300-32ec-11e9-9595-951de3005f8c.png)


```rust
struct AppState {
    db: Pool<MongodbConnectionManager>,
}

fn main() {
    ...
    let manager = MongodbConnectionManager::new(
        ConnectionOptions::builder()
            .with_host("localhost", 27017)
            .with_db("namedb")
            .build(),
    );

    let pool = Pool::builder().max_size(5).build(manager).unwrap();

    server::new(move || {
        App::with_state(AppState{db: pool.clone()})
            .middleware(middleware::Logger::default())
            ...
    })
    .keep_alive(server::KeepAlive::Timeout(5))
    .bind_ssl("**:443", builder)
    .unwrap()
    .start();
}
```

Looks like I understood why so much memory is being spent. But idk how to fix it... 
I think State copies the pool every time.

**Comment by CoderOffka** [comment]
Is it good idea?
```rust
struct AppState {
    db: Box<Pool<MongodbConnectionManager>>,
}
```
