### ISSUE TITLE
actix-web should allow infinite timeout

### ISSUE THREAD

**Issue by marmistrz** [actix/actix-web#699]
When using reqwest, one can set the timeout to `None` to disable timeout entirely (i.e. to allow infinite timeout). actix-web provides no such option.

**Comment by fafhrd91** [comment]
added ability to disable timeouts in master

**Comment by Firstyear** [comment]
Was this feature documented?

**Comment by DoumanAsh** [comment]
It is in API docs https://actix.rs/actix-web/actix_web/client/struct.ClientBuilder.html#method.disable_timeout
