### ISSUE TITLE
Fragmented ws frames are not supported

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#7]

**Comment by DanielJoyce** [comment]
What's needed to support this?

**Comment by fafhrd91** [comment]
it is not hard, question is how to expose this to developer. I don't want to expose `Stream<Item=Bytes>`

**Comment by fafhrd91** [comment]
do you have interest in implementing this feature?

**Comment by DanielJoyce** [comment]
Yes.

**Comment by fafhrd91** [comment]
super! if you have any questions, i usually available in gitter chat

**Comment by fafhrd91** [comment]
added in master
