### ISSUE TITLE
Stream is polled slowly after Async::NotReady

### ISSUE THREAD

**Issue by clia** [actix/actix-web#701]
**Versions**
```shell
$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
$ cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)
```

**Dependencies**
```toml
actix = "0.7"
openssl = { version="0.10" }
actix-web = { version = "0.7", features=["ssl"] }
http = "0.1.15"
bytes = "0.4.7"
futures = "0.1"
tokio = "0.1.15"
```

**Source**
```rust
fn sse1(_req: HttpRequest) -> HttpResponse {
    let mut counter = 0usize;
    let server_events = poll_fn(move || -> Poll<Option<Bytes>, Error> {
        let payload = format!("data: {}\n\n", counter);
        counter += 1;
        Ok(Async::Ready(Some(Bytes::from(payload))))
    });

    HttpResponse::build(StatusCode::OK)
        .content_encoding(ContentEncoding::Identity)
        .content_type("text/event-stream")
        .streaming(server_events)
}

fn sse2(_req: HttpRequest) -> HttpResponse {
    let mut counter = 0usize;
    let server_events = poll_fn(move || -> Poll<Option<Bytes>, Error> {
        if counter % 2 != 0 {
            return Ok(Async::NotReady);
        }
        let payload = format!("data: {}\n\n", counter);
        counter += 1;
        Ok(Async::Ready(Some(Bytes::from(payload))))
    });

    HttpResponse::build(StatusCode::OK)
        .content_encoding(ContentEncoding::Identity)
        .content_type("text/event-stream")
        .streaming(server_events)
}
```

**Test**
The sse1 polls about 10000 times per second.
The sse2 polls slowly, after returned Async::NotReady, the next poll is about 4~5 seconds later.

**Expect**
The sse2 should poll fastly like the sse1, according to the Future/Stream definition, the Async::NotReady status indicates the Future/Stream is temporarily no result, not the ending of the Future/Stream, so the next poll time should as fast as the Async::Ready(data) result.
Sorry for my pool English!

**Comment by DoumanAsh** [comment]
>not the ending of the Future/Stream, so the next poll time should as fast as the Async::Ready(data) result.

To clarify: the next poll happens when tokio runtime is notified about future/stream being ready.
I'm not sure how `poll_fn` works though

**Comment by fafhrd91** [comment]
@clia you can not just return NotReady, you have to use some pollable object otherwise tokio does not know when to poll. Check how futures::task works

**Comment by clia** [comment]
@fafhrd91 Can you provide an example on how to achieve fast polls when result contains both Ready and NotReady, like the sse2 function. Thanks!

**Comment by fafhrd91** [comment]
You can just return NotReady. If you return NotReady you have to register task wake up notification and then something has to wake up your task. 

Why do you want to return NotReady in first place

**Comment by clia** [comment]
> Why do you want to return NotReady in first place

An infinite stream, pushing data to the client occasionally, when there is no data just prepared, will return NotReady when the framework polls.

**Comment by clia** [comment]
https://tokio.rs/docs/futures/getting_asynchronous/
The tokio example also returns Async::NotReady a number of times before returning the connected socket.

**Comment by fafhrd91** [comment]
Tokio example uses socket which is pollable object, that is the reason it works

**Comment by clia** [comment]
That is the inner implementation what it use, but what the poll function returns is the NotReady status, it's not concerned that the self.connect.poll() is called. I think Tokio can process the NotReady status properly.

**Comment by fafhrd91** [comment]
how tokio would know when to wake up task in your example?

there is no magic, tokio provides PollEvented trait, it goes back to mio's Evented trait.

**Comment by clia** [comment]
I think when tokio received NotReady status, it will continue to retry in its predefined frequency.
I have not viewed the source code of tokio and don't know how it is implemented, but its example code make me think so.
If I'm wrong, I'm sorry for waste your time!

**Comment by DoumanAsh** [comment]
You can still manually notify task https://docs.rs/tokio/0.1.15/tokio/prelude/task/struct.Task.html#method.notify

But it really wouldn't be very effective comparing to having stream from actual IO (which will automatically notify once data is ready)

**Comment by clia** [comment]
```rust
struct Sse {
    interval: Interval,
}

impl Stream for Sse {
    type Item = Bytes;
    type Error = Error;

    fn poll(&mut self) -> Poll<Option<Bytes>, Error> {
        match self.interval.poll() {
            Ok(Async::Ready(_)) => {
                println!("Async::Ready");
                Ok(Async::Ready(Some(Bytes::from("data: ping\n\n"))))
            }
            Ok(Async::NotReady) => {
                println!("Async::NotReady");
                Ok(Async::NotReady)
            }
            Err(err) => {
                println!("Err {}", err.to_string());
                Ok(Async::Ready(None))
            }
        }
    }
}

fn push(req: &HttpRequest) -> HttpResponse {
    println!("{:?}", req);
    HttpResponse::Ok()
        .content_encoding(ContentEncoding::Identity)
        .content_type("text/event-stream")
        .streaming(Sse {
            interval: Interval::new_interval(Duration::from_millis(5000)),
        })
}
```

I use this code, which polls a Stream in the poll function, and it behaves the same like the sse2 function. After returned Async::NotReady, the next poll is still after about 4~5 seconds.

**Comment by DoumanAsh** [comment]
Is `Interval` from tokio?

I'm not sure why, but I assume that it doesn't notify properly or maybe it is supposed to be like that 4-5s interval

**Comment by clia** [comment]
Oh Sorry! I think you are right. The internal duration is set at 5 seconds. When I change it to 500 ms, the output speed is fast now.
It's my understand mistake.
