### ISSUE TITLE
Replacing instead of appending headers in HttpResponseBuilder

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#705]
Behavior of `HttpResponseBuilder`'s `header()` method is surprising to me, because it appends a new copy of a header instead of setting/replacing previous values.

I have code that is similar to an HTTP proxy, so I wanted to copy headers from the upstream, and then override some of them with my own values. Because my own headers are set conditionally, it's simpler (and feels more robust) to copy all headers and then replace the ones that I want to set, rather than duplicate conditional logic to avoid copying some headers.

There are special-case methods `content_encoding`, `content_type`, `content_length` that replace the respective headers, but there are no methods that replace arbitrary headers.

Would you accept a PR that adds a way to replace headers?

What should it be? `set_header()`, `insert_header()`? `insert()`?

**Comment by DoumanAsh** [comment]
I think it would be useful since you have need.
The name I'd suggest is `set_header`

@fafhrd91 cc You might consider having it in next major version too?

**Comment by kornelski** [comment]
I haven't noticed it before, but there's also `.set()` method that appends. Having `.set()` and `.header()` that appends, and `.set_header()` that replaces would be inconsistent.

In that case I'll add `remove()` which doesn't interfere with the appending methods, and can be used as `.remove(h).header(h, v)` to replace headers.

**Comment by fafhrd91** [comment]
@DoumanAsh could you review 1.0 and close issue if it solved

**Comment by DoumanAsh** [comment]
`.remove()` is missing I guess, but we have way to append and replace headers.

@kornelski Do you still care about having `.remove()`? If so you could add it in https://github.com/actix/actix-http/blob/master/src/response.rs#L403
But otherwise I think we're good?

**Comment by kornelski** [comment]
OK, I'll add it
