### ISSUE TITLE
impl Future instead of Box<Future>

### ISSUE THREAD

**Issue by vimpunk** [actix/actix-web#708]
I'm not sure if this is possible yet, but in tokio I was able to use `impl Future<...>` as the return type instead of having to use boxed futures. Would this be possible in actix as well?

**Comment by onelson** [comment]
I think part of the issue is that you cannot define a type alias in terms of `impl Trait`. The crate would not be able to define `FutureResponse` in terms of `impl Future<Item/Error>`. Only boxed traits can be used in this way.

**Comment by vimpunk** [comment]
@onelson I see. Would that be such a bad thing, though? In my opinion it's not worth the additional runtime overhead to keep the code a bit prettier.

**Comment by DoumanAsh** [comment]
Internally we should use `impl Future` whenever it is possible, but it is not always possible to use in all places (e.g. in Trait method definition) since it might be limiting for user

**Comment by fafhrd91** [comment]
It is possible to use impl Future, there are special methods for that `.a()` and `.with_async()`. Different methods exists because of rust limitations. We need specialization to unify reg functions.

**Comment by vimpunk** [comment]
@fafhrd91 Ah, I didn't see that. Great news!
