### ISSUE TITLE
Multipart request

### ISSUE THREAD

**Issue by avoronsky** [actix/actix-web#715]
Hello guys! 
I am trying to implement the multipart request handler and stuck on some issue. My journey started with trying to modify `save_file` function to return a `Box<Future<Item=Bytes, Error=Error>>` where Error is a `failure::Error` or `actix_web::Error` [(sample).](https://github.com/actix/examples/blob/master/multipart/src/main.rs) I was trying to do it in different ways playing with any error what appeared on my way, but didn't reach the desired result.
Now it looks like this:
```
fn get_bytes_payload(field: multipart::Field<dev::Payload>) -> Box<Future<Item=Bytes, Error=Error>> {
    Box::new(
        field.fold(BytesMut::new(), move |mut acc, bytes| {
            acc.extend(bytes);
            Ok(acc)
        })
            .and_then(move |bytes| Ok(bytes.freeze()))
            .map_err(|e| {
                println!("bytes receive failed, {:?}", e);
                error::ErrorInternalServerError(e)
            }),
    )
}
```
Error looks like this:
![Error](https://i.imgur.com/8tLPPDu.png)

I will appreciate any help =)

**Comment by DoumanAsh** [comment]
I don't immediately see any error... so it is a bit difficult to say without compiling myself.
But most likely compiler is confused with return type there you need to annotate return type of closure in fold?

**Comment by avoronsky** [comment]
I was trying to specify it explicitly using a separate variable, but the result was the same

**Comment by spasius** [comment]
Two days I was tried to something like AVoronsky, and no result. My task is micro-simple: get bytes from upload, make some work, and return them back. Maybe task is too hard for async framework. I take a old rust sync framework and close my task. Now I just wait, and hope)). Today example with multipart not starts at all. Some errors with Arbiter exists (tokio has updated) ...

**Comment by avoronsky** [comment]
Hello @spasius. 
I replaced `Bytes` with `Vec<u8>` and succeed with it.

**Comment by spasius** [comment]
My code:
```fn save_file(field: multipart::Field<dev::Payload>) -> Box<Future<Item = Vec<u8>, Error = Error>>
{
	Box::new(
        field.fold(Vec::<u8>::new(), move |mut acc, bytes| {
            acc.append(bytes.to_vec().as_mut());
            Ok(acc)
        })
        .and_then(move |bytes| Ok(bytes))
        .map_err(|e| {
            println!("bytes receive failed, {:?}", e);
            error::ErrorInternalServerError(e)
        })
	)
}
```
The same error E0283 type annotations required. Maybe I miss something?

**Comment by avoronsky** [comment]
Your snippet is not readable) 
It is my final func, try to use:
```
fn get_bytes(field_name: &str, field: multipart::Field<dev::Payload>) -> Box<Future<Item = (String, Vec<u8>), Error = ActixError>> {
    Box::new(
        field
            .fold((field_name.to_string(), Vec::new()), move |mut acc: (String, Vec<u8>), bytes| {
                acc.1.extend(bytes.into_iter());
                let rt: Result<(String, Vec<u8>), MultipartError> = Ok(acc);
                future::result(rt)
            })
            .map_err(|err| {
                println!("get_bytes failed, {:?}", err);
                error::ErrorInternalServerError(err)
            }),
    )
}
```

**Comment by spasius** [comment]
Thanks. My final result:
```
pub fn get_field_filedata(field: multipart::Field<dev::Payload>) -> Box<Future<Item = Vec<u8>, Error = Error>>
{
	Box::new(
        field.fold(Vec::new(), move |mut acc : Vec<u8>, bytes| {
            acc.append(bytes.to_vec().as_mut());
            let rt: Result<Vec<u8>, MultipartError> = Ok(acc);
            future::result(rt)
        })
        .map_err(|e| {
            println!("bytes receive failed, {:?}", e);
            error::ErrorInternalServerError(e)
        })
	)
}
```

**Comment by fafhrd91** [comment]
seems problem is solved
