### ISSUE TITLE
Is app.with_config planned for v1 ?

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#720]
Hi,

Thank you for this great work!

Is a feature like 
```rust
App.with_config(|cfg| {
  cfg.0 // <- change json extractor configuration
    .error_handler(|err, req| {  // <- create custom error response
       MyError::BadClientData{error: err.to_string()}.into()
    });
});
```
is planned for v1 (i'm reading the examples on the 1.0 branch etc... but can't find) ?

Because it's very unergonomic to have to configure a custom handler for the Json extractor for *each* route instead of a App global one.

Because I really want to apply rules like a 128kb limit + custom error handler to a App scope ou Resource scope instead of route scope.

**Comment by fafhrd91** [comment]
it is renamed to `.to()`  and `.to_async()` that will be only way to add handler function
extractor configuration is more explicit https://github.com/actix/actix-web/blob/1.0/src/extract.rs#L901
if you want to explore 1.0 you should generate api doc from 1.0 branch

**Comment by ghost** [comment]
Ack, Thank you!

**Comment by ghost** [comment]
Hi again @fafhrd91 

This `1.0` looks very promising.

But after reading the generated docs it appears that the only way to 'apply' a actix_web::web::*Config (JsonConfig, PayloadConfig...) is a per route basis
```rust
use actix_web::{web, App};

/// extract text data from request
fn index(body: String) -> String {
    format!("Body {}!", body)
}

fn main() {
    let app = App::new().service(
        web::resource("/index.html").route(
            web::get()
               // limit size of the payload
               .config(web::PayloadConfig::new(4096).error_handler(/*... */))
               // register handler
               .to(index)
        ));
}
```


which is **absolutely not ergonomic** when you have 100+ routes you have to setup the JsonConfig for **each route**. What could be nice would to be able to do the following:

```rust
use actix_web::{web, App};

/// extract text data from request
fn index(body: String) -> String {
    format!("Body {}!", body)
}

fn main() {
    let app = App::new()
         // limit size of the payload for ALL services / routes
         // and setup a default JsonConfig error_handler for ALL routes
       .config(web::PayloadConfig::new(4096).error_handler(/*... */)
       .service(web::resource("/").route( web::get().to(index)));
       // ... 100+ services
       .service(web::resource("/user/{name}").route(
         // configure this specific route payload size and another error handler
         web::post().config(web::PayloadConfig::new(1024).error_handler(/*... */)).to(post_user))
      )
}
```

**Comment by fafhrd91** [comment]
i am not sure global config is good idea

**Comment by fafhrd91** [comment]
i want to delay decision on global configuration, maybe to 1.2 version

**Comment by ghost** [comment]
I totally understand that you don't have enough time  and it's not your main priority and I can wait as it's not really a bug but an ergonomic improvement. It's just code is ugly meanwhile.

Can I ping you here some time after the 1.0 release to reopen the issue, or should I open another issue ?

**Comment by fafhrd91** [comment]
Sure

**Comment by ddimaria** [comment]
I can't get this to work on individual resources, nor can I get the example in the docs to work (https://actix.rs/docs/extractors/#json).  I have a hard requirement for json errors.  Is there any insight on how to accomplish this, even it's on a per-route basis?  Thanks in advance!

Here's some code:
```
pub fn json_error() {
    JsonConfig::default().error_handler(|err, _| ApiError::BadRequest(err.to_string()).into());
}

pub fn routes(cfg: &mut web::ServiceConfig) {
    cfg.route("/health", web::get().to(get_health)).service(
        web::scope("/api/v1")
            .route("/user/{id}", web::get().to(get_user))
            .service(
                web::resource("/user")
                    .data(json_error)
                    .route(web::get().to(get_users))
                    .route(web::post().to(create_user)),
            ),
    );
}
```

**Comment by little-dude** [comment]
I'm also interested in a global config for the JSON extractor, because I'd like to customize the error.
Would it be possible to re-open this?

**Comment by fafhrd91** [comment]
Data and App::data
