### ISSUE TITLE
TestApp and App should have the same builder API

### ISSUE THREAD

**Issue by rokob** [actix/actix-web#721]
I would like to extract some `App` setup to another function along the lines of what `configure` provides. However, this same function cannot then be used in the same way for a `TestApp` because of the difference in the API used for building test vs non-test apps. In particular, for `resource`, `App` takes consumes self:

```rust
pub fn resource<F, R>(self, path: &str, f: F) -> App<S> 
where
    F: FnOnce(&mut Resource<S>) -> R + 'static,
```

whereas `TestApp` takes `self` by mutable reference:

```rust
pub fn resource<F, R>(&mut self, path: &str, f: F) -> &mut TestApp<S> 
where
    F: FnOnce(&mut Resource<S>) -> R + 'static, 
```

They both have the same basic function, but ideally they would use the same idiom. Would you be open to unifying on one pattern, either mutable reference or consuming self?

**Comment by fafhrd91** [comment]
1.0 uses new api, it does not need separate TestApp. i will update docs soon
