### ISSUE TITLE
actix_web::pipeline: Error occurred during request handling: A payload reached size limit

### ISSUE THREAD

**Issue by gyoyo** [actix/actix-web#724]
client::ClientRequest::get

**Comment by gyoyo** [comment]
Response:
ClientResponse HTTP/1.1 200 OK
  headers:
    "server": "nginx/1.10.1"
    "date": "Tue, 12 Mar 2019 08:00:14 GMT"
    "content-type": "application/json; charset=utf-8"
    "transfer-encoding": "chunked"
    "connection": "keep-alive"
    "set-cookie": "PHPSESSID=uonjdcicnc4d8rbir2mqpjtrn4; path=/"
    "expires": "Thu, 19 Nov 1981 08:52:00 GMT"
    "cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
    "pragma": "no-cache"
    "x-powered-by": "DORA"
    "x-querys-status": "0.015 seconds, 2 queries"
    "content-encoding": "gzip"
    "vary": "Accept-Encoding"
    "node": "198"

**Comment by gyoyo** [comment]
client::ClientRequest::get("http://gateway.shihuizhu.net/open/rankings/real") 
            .header(USER_AGENT, HeaderValue::from_static("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"))
            .header("APPID", HeaderValue::from_static("1902201052557968"))
            .header( "APPKEY", HeaderValue::from_static("57d7577946b8230a1ed9a669400104f3"))
            .finish().unwrap()
            .send()
            //.conn_timeout(Duration::from_secs(10000))
            .map_err(Error::from)
            .and_then(|resp|   {
                 println!("Response: {:?}", resp);
                // println!("Response: {:?}",  resp.body().wait());
                resp.body()
                //.limit(1024000)
                .from_err()
                .and_then(|body| {
                    println!("{:?}",body);
               let mut v: serde_json::Value = serde_json::from_slice(&body).unwrap();
 Ok(HttpResponse::Ok().content_type("application/json").json(v))
                })
                }).responder()

**Comment by fafhrd91** [comment]
it is not clear what error is

**Comment by tingfeng-key** [comment]
I also have this problem today. It just reminds me：
A payload reached size limit.

**Comment by neoeinstein** [comment]
There are default size limits for many things. For large payloads, you may need to configure, e.g. the JSON deserializer, to increase the limit.
