### ISSUE TITLE
actix-fs: Tidy up configuration capability of StaticFiles/NamedFiles

### ISSUE THREAD

**Issue by DoumanAsh** [actix/actix-web#730]
Subj.

Since trait based configuration makes things more complicated we're going to remove it completely

As a side note, we can also check out extra features people might need

**Comment by fafhrd91** [comment]
@DoumanAsh do you want to do more for for this ticket? it's closed automatically

**Comment by DoumanAsh** [comment]
Not really, if someone will have suggestion we can re-open. But as of now I do not think there are any API changes we need for actix-fs

**Comment by imp** [comment]
Not sure whether it falls under this issue or not - we are routinely serving the **content** of `tar` or `zip` file as a group of static files. It would super cool to just specify the archive file and have its content served without unpacking it. Does it make sense? Are there any other folks out there that need this feature?

**Comment by fafhrd91** [comment]
@imp interesting idea, but i am not sure this should be part of core crate. well, it could be feature of actix-files crate

**Comment by DoumanAsh** [comment]
There is one concern is that it would affect performance as you'd need to either unpack it every time or have a way to unpack it into memory once...

I'm not sure if many people would need such feature... Isn't it better to have your files unpacked for optimal performance?

**Comment by imp** [comment]
> @imp interesting idea, but i am not sure this should be part of core crate. well, it could be feature of actix-files crate

Agree, this probably best be out of the core crate. Just wanted to share the use case and set the thinking going.

**Comment by imp** [comment]
> There is one concern is that it would affect performance as you'd need to either unpack it every time or have a way to unpack it into memory once...
> 
> I'm not sure if many people would need such feature... Isn't it better to have your files unpacked for optimal performance?

I am not saying it is the most universal feature, just bringing the idea forward. You are correct that if that would be a case when performance matters unpacking would be the way to go. The use case we have is a specifically low performance and the web application is compiled into the binary.
Anyway, as mentioned earlier, a separate crate may be the most appropriate way to tackle this.

**Comment by fafhrd91** [comment]
if you'd like, you can use actix org for your crate.
