### ISSUE TITLE
Test examples in docs seem out of date

### ISSUE THREAD

**Issue by vimpunk** [actix/actix-web#732]
Can't really replicate the tests as seen [here](https://actix.rs/docs/testing/), e.g. there seems to be no `ClientResponse::body` method which I could call to check the response body. Any pointers? Or is the testing suite being overhauled for 1.0.0?

**Comment by fafhrd91** [comment]
book is still on 0.7

**Comment by vimpunk** [comment]
@fafhrd91 I see. How do I do testing with the current version of actix?

[edit] Actually, I'm still using actix 0.7 and actix-web 0.7.

**Comment by fafhrd91** [comment]
at the moment you have to check how actix-web tests itself. i will update docs soon

**Comment by vimpunk** [comment]
@fafhrd91 Alright, thanks for the quick response :)
