### ISSUE TITLE
actix-web documentation on actix.rs

### ISSUE THREAD

**Issue by e-max** [actix/actix-web#735]
Hi folks!

Could you please say to which version of library refers documentation on https://actix.rs/ ?
For example, https://actix.rs/actix-web/actix_web/test/index.html    looks different from 
https://docs.rs/actix-web/0.7.18/actix_web/test/index.html which, as I understand, is the latest stable version of the crate. 
Also, a guide about testing on a page https://actix.rs/docs/testing/  has a link to 
https://actix.rs/actix-web/actix_web/test/struct.TestServer.html which returns 404.

**Comment by DoumanAsh** [comment]
If you take a look at README https://github.com/actix/actix-web#documentation--community-resources

You can see that we have separate developement and releases versions
docs.rs have docs for latest release, while API documentation on actix.rs refers to documentation from `master` branch

But guide is still for release version

**Comment by e-max** [comment]
Cool. Thank you very much for the information!  So I continue using TestServer until 1.0 is here.
