### ISSUE TITLE
route meta data

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#738]
Hello, do we have the ability to add meta data to route (like: require_admin: true) I would like to implement a token check middleware, differents tokens have differents rights and abilities, differents route paths require differents rights to access.

I would like to add meta info when I register a ressource and get it in handler.

**Comment by fafhrd91** [comment]
middleware does not have access to concrete route. i think it is better to use extractor for this purpose. in 1.0-alpha you can assign arbitrary data to route, and you can access this data during extracting process

**Comment by 0x8f701** [comment]
@fafhrd91 Thanks for your reply, do we have some documentations on it? Hope you a great week-end!

**Comment by DoumanAsh** [comment]
Brief https://actix.rs/actix-web/actix_web/struct.Route.html#method.data

`RouteData` is extractor

**Comment by 0x8f701** [comment]
@DoumanAsh Thanks I will read that!
