### ISSUE TITLE
Remove ring dependency 

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-web#741]
We already had problem with ring dependency about year ago, we have it again.
we need to remove ring dependency from the project.

https://github.com/briansmith/ring/issues/774 and https://github.com/alexcrichton/cookie-rs/issues/113

and i'd like to do this be fore 1.0 release

**Comment by DoumanAsh** [comment]
Should we solve it on `cookie` side or replace `cookie` ourself?\

P.s. Looking at briansmith I really feel he is quite retarded so I see why you want to remove it

**Comment by fafhrd91** [comment]
too much work, i forked cookie for now

**Comment by briansmith** [comment]
> We already had problem with ring dependency about year ago, we have it again.

What is the actual problem that you're having? The problem mentioned in briansmith/ring#774 was a Cargo bug that has already been fixed.

@DoumanAsh wrote:
> P.s. Looking at briansmith I really feel he is quite retarded so I see why you want to remove it

Nice!

**Comment by fafhrd91** [comment]
it is not first level dependency problem, it is always second level. it is fine to depend on ring for application, but having second level of dependency for framework is nightmare

**Comment by fafhrd91** [comment]
forked cookie crate solves this problem partially, delay decision on this topic
