### ISSUE TITLE
Trying to make a "remember me" system with `IdentityService` and `CookieIdentityPolicy`

### ISSUE THREAD

**Issue by ocboogie** [actix/actix-web#742]
I'm trying to make a "remember me" system using `IdentityService` and `CookieIdentityPolicy`.
I need to change the `max_age` header conditionally on the request. So for example if I get a normal login request I need the `max_age` header to be empty, but if the remember me flag is set then, I need the `max_age` to be one week or something.

Is there any way of doing this with `IdentityService` and `CookieIdentityPolicy`, or I'm I going about this all wrong?

**Comment by fafhrd91** [comment]
there is no way at the moment.

**Comment by ocboogie** [comment]
@fafhrd91 What would you recommend to achieve this or do you have any plans for something like this, and if so, how could I help?

**Comment by fafhrd91** [comment]
sorry, I don't have time at the moment. you should check source code yourself. and PR is always welcomed

**Comment by fafhrd91** [comment]
i revisited this ticket. are this functions `.remember()` and `.forget()` what you want?

**Comment by fafhrd91** [comment]
https://docs.rs/actix-web/1.0.0-alpha.6/actix_web/middleware/identity/struct.Identity.html

**Comment by ocboogie** [comment]
I need to be able to change the `max_age` when I use the `remember` function.
Because I need the `max_age` to be able to differ per request.
I'm still new to auth, so I might be going about this all wrong.

**Comment by fafhrd91** [comment]
I see. You should create custom policy.
