### ISSUE TITLE
ConnectionInfo cannot get peer info at 1.0.0

### ISSUE THREAD

**Issue by hawkingrei** [actix/actix-web#744]
Code about getting peer addr have been removed.Please reimplement this features.

https://github.com/actix/actix-web/blob/master/src/info.rs#L121

**Comment by fafhrd91** [comment]
this is not easy. i can not say when this could be fixed

**Comment by goddessfreya** [comment]
What is stopping this feature? 

EDIT: How do I implement IP bans?

**Comment by therealprof** [comment]
I also just stumbled across this and would agree that it is rather important to have the connecting `SocketAddr` for all kinds of reasons, e.g. logging and connection hashing.

**Comment by fafhrd91** [comment]
@ZeGentzy if you really want to ban specific ips, you should do this before http server start working. in actix-net you can insert service that can directly work with socket before http server.

it is very inefficient to ban connection after server parses http request

**Comment by fafhrd91** [comment]
implemented
