### ISSUE TITLE
Adopt state-of-the-art security practices, as found in common router software

### ISSUE THREAD

**Issue by 197g** [actix/actix-web#751]
# Motivation & Overview

Recent industry practice has shown that http security can be improved a lot through very simple changes. Script-kiddies and advanced hackers often rely on simple security failures to inject their payloads and effective filtering before passing requests to the backend or the internal routing mechanisms is expected to improve the resilience of a system by a great amount. This also [made OpenBSD](https://marc.info/?l=openbsd-tech&m=155407864604288&w=2) tighten their security which is a good reason to do the same in `actix-web`.

I'm sorry for those for which this advice comes too late.

## Drawbacks and Alternatives

Since this change is interface compatible, there is no need to rush it.

This change increases processing time even for legit requests but the impact is proportionally small to the security gain from the hours wasted by helpless hackers not being able to break in.

It could be realized as a `middleware` but that would suggest that it might be a good idea to leave it out. But 84%¹ of coders will store passwords in plaintext or apply crypto the wrong way even if provided adequate libraries and documentation². To keep programmers from hurting themselves, it is thus best to always filter these requests. Actually advanced programmers can fork&patch it when they really require the utmost performance.

## Evaluation

Assuming you have installed the dangerous criminal's tools, you could be able to test it with the below code (untested, I do not condone such practices).

```bash
$ cargo run --example basic &
$ curl localhost:8080
$ # should return empty
```

Proper tests for these are complicated, as they rely on shipping hacker tools. I don't find this ethical and would rather ask supervised, trusted members to test this manually before every release.

<details>
<summary>Trivial patch</summary>

```
From: Andreas Molzer <andreas.molzer@gmx.de>
Date: Mon, 1 Apr 2019 17:43:22 +0200
Subject: [PATCH] Adopt standard state-of-the-art security

---
 src/route.rs | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/route.rs b/src/route.rs
index 7f1cee3d..73865a92 100644
--- a/src/route.rs
+++ b/src/route.rs
@@ -138,7 +138,11 @@ impl<P> Service for RouteService<P> {
     }
 
     fn call(&mut self, req: ServiceRequest<P>) -> Self::Future {
-        self.service.call(req)
+        match req.head().headers.get("User-Agent") {
+            Some(ua) if ua.as_bytes().starts_with(b"curl") =>
+                Box::new(futures::future::err(Error::from(Response::Forbidden().finish()))),
+            _ => self.service.call(req),
+        }
     }
 }
 
-- 
2.21.0
```
</details>

¹As evaluated by paying $25 to 50 random college student to build our production-ready e-commerce store. Provided libraries include: [`md5`](https://crates.io/crates/md5), [`des`](https://crates.io/crates/des), [`exonum`](https://crates.io/crates/exonum)
²We made sure to print out all the pages beforehand, as we learned that reading from a screen for extended periods of time such as in our test setup can lead to eye strain. Despite our best efforts to provide a comfortable environment, some (most) candidates showed obvious stress symptoms, such as sweating, dehydration, distress, and irritability, when we unlocked the doors the next day.

**Comment by DoumanAsh** [comment]
Do you really think it is funny to spam issue tracker with your jokes?

**Comment by fafhrd91** [comment]
@DoumanAsh relax. let's do less aggression.

**Comment by awulkan** [comment]
Even though I'm unsure if this post is a joke or not, it raises the question: how good is the security in Actix web? Are there any known flaws that need to be fixed? What kind of tests has been done to evaluate the security?
