### ISSUE TITLE
client::ClientRequest http2 does not work

### ISSUE THREAD

**Issue by Lingli05** [actix/actix-web#753]
In example [http-proxy]( https://github.com/actix/examples/tree/master/http-proxy), added the following line in main.rs to enable http2 request:

fn index(_req: &HttpRequest) -> Box<Future<Item = HttpResponse, Error = Error>> {
    client::ClientRequest::get("http://127.0.0.1:8080/index.html")
        *** .version(http::Version::HTTP_2) ***
        .finish().unwrap()
        .send()

however the http2 pkt from client was rejected by server, for "bad request"

Anything else needs to be set in ClientRequest?

**Comment by fafhrd91** [comment]
did you enable "ssl" feature?

**Comment by Lingli05** [comment]
No.

Btw, test was done with the latest version.

Thanks,
Ling

**Comment by fafhrd91** [comment]
you have to enable "ssl", http/2 does not work without ssl
