### ISSUE TITLE
Awc doesn't play nice with Google OAuth

### ISSUE THREAD

**Issue by DGolubets** [actix/actix-web#759]
It seems that new Actix http client has troubles with Google OAuth API.
Test case: send a query with an invalid access_token.
Expected result: 401 with JSON error message.
Awc (0.1.0-alpha.3): 400
```
let status: StatusCode = System::new("test")
        .block_on(lazy(|| {
            Client::default()
                .get("https://www.googleapis.com/oauth2/v3/userinfo?access_token=1234")
                .send()
                .map(|response| response.status())
        }))
        .unwrap();

    assert_eq!(status, StatusCode::UNAUTHORIZED);
```

**Comment by fafhrd91** [comment]
I think this is h2 library bug. I’ll check

**Comment by fafhrd91** [comment]
google doesnt like awc's "user-agent". if you set .no_default_headers() on request then it works.

i will remove default headers at all in next version

**Comment by fafhrd91** [comment]
it is actually "host" header. should be fixed in master

**Comment by a1ien** [comment]
@fafhrd91 Ammm... host header **must** present. Or this header is set somewhere else(not in the code was removed in b1547bbbb68938977e236e11c01a113adb06bb1f) ?

**Comment by fafhrd91** [comment]
i guess h2 sets it
