### ISSUE TITLE
Normalize every url

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#76]
Hey, it's me again.

Maybe I am misusing regex in Rust or in actix-web, but I want any url that ends in a slash to be redirected to the same version without an ending slash.

The simplest version of this is:

`.resource(r".*\/", |r| r.method(Method::GET).h(NormalizePath::new(
                    false, true, StatusCode::MOVED_PERMANENTLY)))`

Of course this regex would not cover yet special cases like ending in multiple slashes.... but that's where the second parameter (merge) comes into play, right?

Anyway, this doesn't work.
It's the topmost resource for me and still it never matches.

e.g. I enter: `http://localhost:8000/en/`, nothing happens, NO url at all matches! (why doesn't default_resource match here?)

I simply get a 404. On the other hand, if I visit `http://localhost:8000/en//` (double slash at the end), I get redirected to `http://localhost:8000/en` just fine.

whole definition: 

```
Application::new()
                .resource(r".*\/", |r| r.method(Method::GET).h(NormalizePath::new(
                    false, true, StatusCode::MOVED_PERMANENTLY)))
                .resource(r"{file_name}.{ext}", |r| r.method(Method::GET).f(assets))
                .resource("{language_code}", move |r| r.h(handle_language()))
                .resource("api/ws", |r| r.method(Method::GET).f(ws_index))
                .default_resource(|r| r.method(Method::GET).h(NormalizePath::new(
                    false, true, StatusCode::MOVED_PERMANENTLY)))
```

What baffles me here, is that `default_resource` doesn't fire.

**Comment by fafhrd91** [comment]
`NormalizePath` check if route actually exists before redirect. so maybe your application does not have those routes.

i'd suggest to check code for `NormalizePath` and just make your own version of it.

**Comment by ghost** [comment]
Nope, it doesn't have all those routes. But e.g. `http://localhost:8000/en` it has and `http://localhost:8000/en//` redirects just fine, while `http://localhost:8000/en/` doesn't. Was just wondering why

**Comment by fafhrd91** [comment]
i see. let me add test case for such path

**Comment by fafhrd91** [comment]
should work. you should enable "merge"

**Comment by ghost** [comment]
Probably again on old doc, right? https://docs.rs/actix-web/0.3.3/actix_web/struct.NormalizePath.html *sighs* (because second parameter here is merge and I set that to true)

**Comment by fafhrd91** [comment]
would you provide PR?

**Comment by fafhrd91** [comment]
here is test case 5634e5794f571904706d21c2b327560bbb4a7ba3

**Comment by ghost** [comment]
See https://github.com/Unmoving/actix-web/commit/25eca167e0dca46bfc97c25b72cbd167607d15b1, please (I didn't want to open MR for breaking test).

Maybe this is all fine and I just don't get it. To me it's strange that it works for "double trailing slash" but not for "single trailing slash"

**Comment by fafhrd91** [comment]
Ok, I’ll check a bit later

**Comment by ghost** [comment]
It's not that urgent ;) Your responsiveness is awesome! Thanks a lot and have a very nice day.

**Comment by fafhrd91** [comment]
should be fixed in master
