### ISSUE TITLE
Implementing IdentityService trait struct visibility.

### ISSUE THREAD

**Issue by mojzu** [actix/actix-web#766]
I'm very new to Rust so I may be missing something obvious, I'm trying to implement `IdentityPolicy` for a server application I'm writing but I can't seem to find a way to use the `ServiceRequest` or `ServiceResponse` structs because they're in the private `service` module. I've worked around this for now by including authentication calls in the route handlers, but the middleware seems like a much cleaner way to implement this.

Thanks for your time, and your excellent work on the various actix libraries, I've enjoyed using them to learn Rust and am hoping to use them in production at some point.

**Comment by fafhrd91** [comment]
Both types are exported in actix-web::dev module

**Comment by mojzu** [comment]
So I was missing something obvious, it's working now, cheers for the help!
