### ISSUE TITLE
http request on SyncActor failed

### ISSUE THREAD

**Issue by nathanloisel** [actix/actix-web#767]
I'm trying to execute http request into a Sync Actor (10 spawn) and I got this error for the first request: 

> Error reading response payload: timer is shutdown

And this debug log for others : 

> Client http transaction is not completed, dropping connection.

The second error stop the spawned actor.

With an AsyncActor, I don't have this problem.
Can you help me to understand what is wrong there?

Thanks

**Comment by fafhrd91** [comment]
Client is async, you can not execute it in sync actor.
