### ISSUE TITLE
Support Direct Submission of Requests to HttpServer

### ISSUE THREAD

**Issue by naftulikay** [actix/actix-web#768]
NGINX, Tide, and other web platforms provide the ability to submit a request manually into the web service without any network overhead.

Tide, for instance, provides an `into_http_service` method on `tide::App` which returns a `http_service::HttpService` implementation which has a `respond` method which accepts an `http_service::Request` and returns a `Future<http_service::Response>`.

I'll describe my architecture. I'm building an AWS Lambda function. The way that [the Lambda runtime works](https://github.com/awslabs/aws-lambda-rust-runtime/) is that the code polls a local endpoint to receive new events and then invokes a Rust function as a handler. Since it's possible to use Lambda as a serverless HTTP API, I'd like to do this with a Rust web framework. Using a web framework like Actix makes routing/middleware easy.

With Tide, I can do exactly what I'm describing and submit requests locally without network overhead. With Actix Web, I'd have to submit these requests over the loopback interface, which isn't the most efficient thing to do. Otherwise, I'll have to implement middleware and routing myself, which is reinventing the wheel.

Providing the ability to locally submit requests into Actix Web would be extremely helpful in this regard.

**Comment by fafhrd91** [comment]
it is supported already, you can use `.call(req)` method. A lot of unit tests uses this approach.

for example here is how app could be created
https://github.com/actix/actix-web/blob/master/src/app.rs#L700

then you create request and call service
https://github.com/actix/actix-web/blob/master/src/app.rs#L712

**Comment by naftulikay** [comment]
Permalinks:

 - [src/app.rs:700](https://github.com/actix/actix-web/blob/9d82d4dfb9f8e5174c46bcc68662b0e1ef0bbb4e/src/app.rs#L700-L709)
 - [src/app.rs:722](https://github.com/actix/actix-web/blob/9d82d4dfb9f8e5174c46bcc68662b0e1ef0bbb4e/src/app.rs#L722)

**Comment by fafhrd91** [comment]
just FYI you need [Service](https://github.com/actix/actix-net/blob/master/actix-service/src/lib.rs#L55) trait.

**Comment by naftulikay** [comment]
Thank you!

Permalinks:

 - [`actix_web::test::init_service`](https://github.com/actix/actix-web/blob/9d82d4dfb9f8e5174c46bcc68662b0e1ef0bbb4e/src/test.rs#L103)
 - [`actix_service::Service`](https://github.com/actix/actix-net/blob/feac0b43d9ae69b82dd26278f4fb85526ac51f5a/actix-service/src/lib.rs#L56)
