### ISSUE TITLE
Massive commit made the repository painful to clone

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#770]
The commit 3e986042973762e28fa6af25c8d161ce9f4de4d0 contains 347MB, 20581 files of rustdoc-generated documentation. 

This made actix-web repository so large, that GitHub struggles to serve it and cloning takes minutes, even on a very fast connection.

**Comment by tesuji** [comment]
I think you could use `git fetch origin master` or `git pull origin master`
to only fetch `master` branch.

**Comment by Stargateur** [comment]
Your also have generate the doc of all your dependencies. That include tokio, serde, http, etc... not the little one. So you have all http and all their sources. What did you expect with `cargo doc --all-features` ?

**Comment by Stargateur** [comment]
https://github.com/actix/actix-web/commit/2a89b995aa9f6a611fc1d645d5bd69d30ecdfd23 remove `--no-deps` @fafhrd91  little mistake ?

**Comment by DoumanAsh** [comment]
`--no-deps` to make documentation complete as otherwise you wouldn't have references to externals deps

You should clone with `--single-branch`

**Comment by kornelski** [comment]
Using this script to find largest files:

```sh
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- 
```

it shows some massive, but not very relevant files. Perhaps after doc generation, before commit, you could `rm -rf` docs of these large irrelevant dependencies? (e.g. `encoding_index_*` and other unicode tables for several languages). `syn` is also large, and used only internally. `minigz_oxide`, `openssl`, etc.

**Comment by fafhrd91** [comment]
this commit is for GitHub pages. I added `--no-deps`, next build should resolve this issue
