### ISSUE TITLE
Documentation doesn't show how to use StaticFiles as a fallback

### ISSUE THREAD

**Issue by kornelski** [actix/actix-web#772]
The documentation only shows how to serve static files from a directory such as `/static`, but doesn't show how to use it as a fallback for all URLs. Setting static files for `"/"` handler is not sufficient, because then the `default_resource` handler is never reached. 

I would like to handle in Rust all URLs that aren't satisfied by static files. However, it seems that StaticFiles serves its own no-content 404 page, preventing fallbacks.

I've seen there exists `pub fn default_handler<H: Handler<S>>(self, handler: H) -> StaticFiles<S, C>` and it's only briefly commented with:

> Sets default handler which is used when no matched file could be found.

but that doesn't tell me anything — I don't know when to call it, or what to do with the result.

**Comment by fafhrd91** [comment]
this is interesting idea, but it is not possible at the moment. i'll check how this could be done in 1.0

FYI 0.7 is in maintenance mode, only bug fixes

**Comment by fafhrd91** [comment]
in master you can do this:

```rust
use actix_files::Files;
use actix_web::{web, App, HttpResponse};

fn main() {
    let app = App::new()
        .service(
            web::resource("/index.html").to(|| HttpResponse::Ok()))
        .default_service(
            Files::new("", "./static")
        );
}
```

**Comment by fafhrd91** [comment]
btw if you set default service in `App` it should propagate to static files

**Comment by sariug** [comment]
This does not really the proper way... 

Lets say I have a complicated service, where the default service shouldn't be static, but just a fallback for some handler. How should one implement this?
