### ISSUE TITLE
Is JsonConfig globally configurable?

### ISSUE THREAD

**Issue by daddinuz** [actix/actix-web#775]
Hi,

Is there a way to apply JsonConfig rules to the whole app instead of per route?
My app has a lot of routes and it's a bit tedious to configure each of them one by one.

Anyway, brilliant job!
Thank you.

**Comment by DoumanAsh** [comment]
Hmm that actually might be good idea for macros to declare routes.
And having some ability to define config as constant would be even better

**Comment by fafhrd91** [comment]
implemented in master
