### ISSUE TITLE
how to use predicate and virtual host in actix-web 1.0

### ISSUE THREAD

**Issue by Kilerd** [actix/actix-web#777]
in version 0.7, there is the method `filter` in the struct `App` to dispatch requests into different hosts, as the demo says:
```rust
fn main() {
    let server = server::new(|| {
        vec![
            App::new()
                .filter(pred::Host("www.rust-lang.org"))
                .resource("/", |r| r.f(|r| HttpResponse::Ok())),
            App::new()
                .filter(pred::Host("users.rust-lang.org"))
                .resource("/", |r| r.f(|r| HttpResponse::Ok())),
            App::new().resource("/", |r| r.f(|r| HttpResponse::Ok())),
        ]
    });

    server.run();
}
```

but in version 1.0 I can only do in this way:
```rust
HttpServer::new(move || {
        App::new()
            .service(
                web::resource("/").route(
                    web::route()
                        .guard(guard::Header("host", "www.rust-lang.org"))
                        .to(|| "hello rust"),
                ),
            )
            .service(
                web::resource("/").route(
                    web::route()
                        .guard(guard::Header("host", "users.rust-lang.org"))
                        .to(|| "hello user"),
                ),
            )
    })
.run()
```

are there a more convenient way to implement this feature? for if there are a lots of resources in one host, I need to repeat the guard line.

**Comment by fafhrd91** [comment]
Good question. I’ll add something before releas

**Comment by fafhrd91** [comment]
You can use `Scope`, `web::scope()`

**Comment by Kilerd** [comment]
thx, maybe that is what I need.

**Comment by antonok-edm** [comment]
@fafhrd91 I don't think scope works for hosts, just for paths? If it does, there are no examples anywhere.

@Kilerd #989 should be useful when it's present in a release.

**Comment by fafhrd91** [comment]
@antonok-edm it should, it uses host header. But i think, for proper virtual hosting support, custom service is required. Something like VHM from pyramid
