### ISSUE TITLE
Provide a prelude module to reduce the number of imports

### ISSUE THREAD

**Issue by otavio** [actix/actix-web#779]
When working on libraries exposing the APIs make it easier for developers to import a `prelude` and avoid the long list of `use` on preamble of code.

**Comment by fafhrd91** [comment]
I am not sure about prelude. actix-web provides `web` and `dev` modules.

**Comment by otavio** [comment]
The `web` is logical to me however the `dev` is not too sound.

**Comment by fafhrd91** [comment]
how prelude would help? any specifics

**Comment by otavio** [comment]
Well, I'd possibly expect two prelude modules: `actix_web::client::prelude::*` and `actix_web::server::prelude::*` or `actix_web::prelude::*` directly.

This would import the most common structs, macros, and traits so it would make it easier for new users. It seems a common practice on Rust ecosystem. Do you see any problem?

**Comment by fafhrd91** [comment]
main problem is explicitness. it is hard to understand where type come from, you dont see from `use`. personally, i consider `use mod::*` a bad style.

**Comment by otavio** [comment]
A valid concern. Closing it.
