### ISSUE TITLE
Extension extractor

### ISSUE THREAD

**Issue by 0x8f701** [actix/actix-web#787]
Hello, do we have an extractor for extensions? I have a middleware which checks user's scopes and store user info in request's extensions, but it seems that we don't have an extension extractor,
so every time we need to call `req.extensions` to get the informations

**Comment by DoumanAsh** [comment]
Extensions can be of any type and I think it should be done only on user side.
What sort of extractor can you come up with, that would _common_ for any user of actix-web?

**Comment by fafhrd91** [comment]
@GopherJ i think you should create custom extractor for your type.

**Comment by 0x8f701** [comment]
@fafhrd91 @DoumanAsh  Thanks, I'll learn how to do it
