### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#79]
I don't have much data to go on but this is what I am seeing.

I am using commit aff43cc8b84b172b6937ea314c5e84a2746eb9d5.
On Linux with the alpn feature for client HTTPs requests. 
I am not serving over https.

I have an endpoint that takes a request makes another request using the Client and then decodes the body and returns JSON. 

When compiled in release mode after running some load that isn't super heavy using wrk. Occasionally when the test completes the server experiences a segmentation fault.

**Comment by glademiller** [comment]
I have been attempting to reproduce this when compiling in debug mode but have yet to see it happen. I'll update this if I see it happen but as of right now this is release only.

**Comment by glademiller** [comment]
Forgot to include my toolchain
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.25.0-nightly (b1f8e6fb0 2018-02-22)

**Comment by glademiller** [comment]
I downgraded to 
nightly-2018-02-15-x86_64-unknown-linux-gnu (default)
rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)

and have been unable to reproduce the problem. Should we investigate further or chalk it up to a compilation issue?

**Comment by fafhrd91** [comment]
Could you try to enable debug=true for release build and then run you app under lldb. When it segfaults, print backtrace. You would need to you your own copy of actix-web

**Comment by fafhrd91** [comment]
Could you also test this on rustc beta

**Comment by glademiller** [comment]
Sorry for the delay I'll try to find some downtime to test this. Unfortunately, I don't think I will be able to do the beta test since my code base is making extensive use of nightly features.

**Comment by fafhrd91** [comment]
nightly is fine. I just need backtrace for segfault. also try latest nightly, maybe it was specific nightly bug

**Comment by glademiller** [comment]
I have not been able to reproduce this today on the latest nightly. I tried getting back to rustc 1.25.0-nightly (b1f8e6fb0 2018-02-22) but wasn't able to find which nightly that corresponded to.

I'm going to close this and will reopen if it reappears.

**Comment by fafhrd91** [comment]
should be fixed in master, waiting for confirmation

**Comment by fafhrd91** [comment]
seems bug is fixed
