### ISSUE TITLE
Custom HTML error page

### ISSUE THREAD

**Issue by vbrandl** [actix/actix-web#791]
I want to implement a custom error page for my application, therefore I implemented `std::error::Error`, `Display` and `ResponseError` for my error type:

```rust
enum Error {
  Variant1,
  Variant2,
  ...
}
// default impl for Debug and std::error::Error

const P500: &str = include_str!("../static/500.html");
impl ResponseError for Error {
    fn error_response(&self) -> HttpResponse {
        HttpResponse::InternalServerError()
            .content_type("text/html")
            .body(P500)
    }
}
```

this didn't work and still returned the string value of my errors as defined in `Display`, so I changed the `Display` implementation like this:

```rust
impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        write!(fmt, "{}", P500)
    }
}
```

Now I get my custom error page as output but without the `content-type` header, so it isn't rendered as HTML in the browser.

What do I need to change to get a custom HTML error page?

**Comment by fafhrd91** [comment]
you need to implement [render_response](https://docs.rs/actix-web/1.0.0-beta.1/actix_web/error/trait.ResponseError.html#method.render_response)

**Comment by vbrandl** [comment]
Ty, somehow I missed that one...
