### ISSUE TITLE
to_async does not work with impl Future<Item = Json<SuccessResponse>, Error = Error>

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#792]
It fails with

```
the traitactixweb::handler::AsyncFactory<, _>is not implemented forfn(actix_web::request::HttpRequest, actix_web::types::json::Json<service::requests::add_organization::AddOrganizationRequest>) -> impl futures::future::Future {service::handlers::add_organization::add_organization}`
```

**Comment by fafhrd91** [comment]
fixed in master

**Comment by rokit** [comment]
I'm also getting an `AsyncFactory` error, but it's happening with `Future<Item = String, Error = reqwest::Error>`. I'm probably doing something wrong. @fafhrd91 Would you mind taking a look at my code?
https://github.com/rokit/actix-async-factory/blob/master/src/main.rs
