### ISSUE TITLE
CookieIdentityPolicy doesn't keep track of who's logged in/out

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#795]
At the moment, `CookieIdentityPolicy` marks a request as authenticated (`id.identity() == Some(_)`) iff it has a correctly encrypted session cookie.

This raises the following issues:

1. If the private key is leaked, an attacker can log in as anyone. Only the correct "identity string" (the one passed to `Identity::remember`) is needed.
2. If the identity cookie of a user (Bob) is leaked (e.g. by a man-in-the-middle attack), the attacker can log in as the user, even after Bob has logged out (`Identity::forget`).

`CookieIdentityPolicy` should keep track of who's logged in/out to solve (2). It should also add random salts to identity cookies to solve (1), so that an attacker has to "guess" the salt even if it knows the victim's id.

for example a call to `Identity::remember(identity_str)` would do (pseudo code)
```rust
// let salt_len: usize;
// let identities: HashMap<String, String>;
let salt = random_string(salt_len);
identities.insert(identity_str, salt);
let identity_cookie = encrypt(salt + identity_str);
```

and a call to `Identity::identity` would do:
```rust
let (cookie_salt, identity_str) = decrypt(identity_cookie).split_at(salt_len);
if let Some(salt) = identities.get(identity_str) {
    if salt == cookie_salt {
        // user is logged in
    } else {
        // attacker has access to the secret key
        // or someone is trying to log in with an old session cookie
    }
} else {
    // user has logged out, it should log back in again with `Identity::remember`.
}
```

Also maybe add a DateTime object to the `identities` map, so that identity cookies expires even if users forget to log out.

**Comment by fafhrd91** [comment]
1. could you just change private key? that would logout everyone.
2. tracking would add storage dependency which is complicates everything significantly.

**Comment by fafhrd91** [comment]
also check #502

**Comment by ghost** [comment]
Ah, thank you for pointing out the PR. So it solves (2)? Without a persistent storage dependency it would be difficult to solve this issue... I'm still convinced it's needed though: there's a time period between the private key leakage and when you realize that it's leaked, and people can just log in as admin.

**Comment by ghost** [comment]
I guess it's up to the user to implement such things
