### ISSUE TITLE
Add middleware configuration to ServiceConfig

### ISSUE THREAD

**Issue by Kazakuri** [actix/actix-web#797]
In the latest beta for v1.0.0 [ServiceConfig](https://docs.rs/actix-web/1.0.0-beta.1/actix_web/web/struct.ServiceConfig.html) allows you to delegate configuration for App state and routes, but is it possible to add the `wrap` method as well to let external methods configure middleware?

In the project I'm working on migrating from 0.7 to 1.0.0 I have both [routes](https://github.com/Kazakuri/urus.ai/blob/24001fa085de7e221debdd85171d9acca948caa7/src/handlers.rs) and [middleware](https://github.com/Kazakuri/urus.ai/blob/24001fa085de7e221debdd85171d9acca948caa7/src/middleware.rs) being configured in other methods and it'd be nice to be able to keep it that way.

**Comment by fafhrd91** [comment]
it is not possible, because middleware uses `T` type of nested middleware as parameter.
one option would be to add `web::scope()` and add middlewares on scope level

**Comment by fafhrd91** [comment]
also `.wrap()` would require generic param for ServiceConfig
