### ISSUE TITLE
why does error::ResponseError::render_response exists?

### ISSUE THREAD

**Issue by Ryan-Git** [actix/actix-web#798]
version: actix-web = "1.0.0-beta.1"

Description:
I defined a middleware(extractor) implementing FromRequest with customized error type that implements ResponseError::error_response, which returns a json body. But actually it surprisingly returns text/plain on error.

I find ResponseError has another method `render_response` that changes the result from `error_response`, then answer the client. What's the purpose of it?

btw, though api has changed a bit on 1.0, the web::block helper is great, saving me from create a brunch of sync actors and pass msgs back forth, fighting with the type system when passing lambdas. Thanks for all your work, hoping the formal 1.0 release will come up soon :)

**Comment by fafhrd91** [comment]
this one still requires final decision. here is problem. I'd like to send rendered error to peer as response body, but at the same time developers may want to use HttpResponse as error in form of InternalError.
so for first case I need to use `Display` trait and set rendered message as body, but in case of InternalError it should be used as is.

**Comment by Ryan-Git** [comment]
sounds like we need two separate trait/method for this. for now I just override `render_response` and it's ok.

Another question, how to schedule a repeated task now?  Before 1.0 I can start an actor, put the addr in state, but now it doesn't depend on actix..

**Comment by fafhrd91** [comment]
you can start actor in 1.0 as well, same as in 0,.7

**Comment by Ryan-Git** [comment]
thanks
