### ISSUE TITLE
Can I get params from query string or http body or cookie or http header as a map?

### ISSUE THREAD

**Issue by ufosky** [actix/actix-web#800]
I want to get some params dynamically, but now I only found the way to get some known field from the request

**Comment by fafhrd91** [comment]
use `fn index(req: HttpRequest) -> ...`

this is question for chat.

**Comment by ufosky** [comment]
I just find a method `req.query_string()`, do I need parse it myself to a map?

**Comment by fafhrd91** [comment]
you should check api docs and example. there are plenty of various examples

https://docs.rs/actix-web/1.0.0-beta.2/actix_web/web/struct.Query.html
