### ISSUE TITLE
Custom Json Config Error Handler must return Error

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#802]
I have a type that implements ResponseError ideally I would like to use that type directly for my error_handler. Right now I have to use CustomType{}.error_response().into() in order to turn the response into an Error that gets sent correctly.

**Comment by fafhrd91** [comment]
I don't get the problem. could you post some code?

**Comment by glademiller** [comment]
Essentially this is what I have to do today to meet the contract
```
pub fn handle_json_error(err: JsonPayloadError, _: &HttpRequest) -> Error {
    match err {
        JsonPayloadError::Deserialize(err) => ApplicationError::Custom {
            status: http::StatusCode::BAD_REQUEST.into(),
            reason: format!("BAD_JSON: {}", err),
        }
        .error_response().into(),
        JsonPayloadError::Overflow => ApplicationError::Custom {
            status: http::StatusCode::PAYLOAD_TOO_LARGE.into(),
            reason: "Payload to large.".to_string(),
        }
        .error_response().into(),
        JsonPayloadError::ContentType => ApplicationError::Custom {
            status: http::StatusCode::UNSUPPORTED_MEDIA_TYPE.into(),
            reason: "Unsupported Media Type.".to_string(),
        }
        .error_response().into(),
        JsonPayloadError::Payload(err) => ApplicationError::Custom {
            status: http::StatusCode::BAD_REQUEST.into(),
            reason: format!("Problem decoding request: {}.", err),
        }
        .error_response().into(),
    }
}
```
My ApplicationError type implements ResponseError. In order to get it to render correctly as a JSON error and not just be formatted as a string using Display I have to turn it into an HttpResponse via error_response and then call into on that to turn it into an actix_web::Error. It would be nice to be able to return impl ResponseError or something along those lines.

**Comment by fafhrd91** [comment]
it is not possible to `ResponseError` for `Error` at the moment. you dont need to call `.error_response()`, just `.into()` is enough.

**Comment by glademiller** [comment]
Using into causes the output to be a string instead of the Json
serialization I need. I could just call into and it will compile but won't
yield the desired result.

**Comment by fafhrd91** [comment]
You need to override render_response
