### ISSUE TITLE
Websocket actors not stopping

### ISSUE THREAD

**Issue by prplz** [actix/actix-web#803]
I have a problem with some websocket actors not stopping properly.
[Here](https://github.com/prplz/actix-ws-bug) is a program to reproduce it, `cargo run` it then run `client.py`. The output from the server is:
```
There are 1 sockets
There are 2 sockets
There are 3 sockets
There are 4 sockets
There are 5 sockets
There are 6 sockets
There are 7 sockets
There are 8 sockets
There are 9 sockets
There are 10 sockets
Websocket timed out!
There are 9 sockets
Websocket timed out!
There are 8 sockets
```
Most of the sockets don't stop or time out.
Notice the problem goes away and all sockets correctly time out if you comment out this line in main.rs: `ctx.text(msg.0);`.

**Comment by fafhrd91** [comment]
there was bug in actix-http, it should work with actix-http=0.2.1

my output is:
```
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
There are 1 sockets
There are 0 sockets
```

re-open if you think there is still bug

**Comment by prplz** [comment]
There is still a bug. [I have updated to latest actix-http & friends and changed the client.py script.](https://github.com/prplz/actix-ws-bug/commit/7adc712631c0f61d1b2b3bb81016dfbf8f7cadbd) No sockets time out and the problem still goes away if I comment out the `ctx.txt` line:
```
There are 1 sockets
There are 2 sockets
There are 3 sockets
There are 4 sockets
There are 5 sockets
There are 6 sockets
There are 7 sockets
There are 8 sockets
There are 9 sockets
There are 10 sockets
There are 9 sockets
```

**Comment by fafhrd91** [comment]
should be fixed in new actix-web-actors release

**Comment by prplz** [comment]
Confirmed, thanks for this!
