### ISSUE TITLE
extractor for Option

### ISSUE THREAD

**Issue by Ryan-Git** [actix/actix-web#804]
how can I say a parameter is optional? 
In my case, the request body can be empty or not due to query params, but a `web::Json<Option<T>> ` doesn't work. If the body is empty, the system reports deserialize error.

**Comment by Ryan-Git** [comment]
I realize it's a serde_json problem.

**Comment by Ryan-Git** [comment]
due to https://github.com/serde-rs/json/issues/539, the serde-json team rejects to this change. I reopen this issue to see what's your thought?

Generally, I think there should be a way to express "the parameter is optional". Cause rust doesn't have null, it will be an Option. Shall we implement this in actix-wb?

Currently the workaround is inject Request, check and parse body in application logic.

**Comment by fafhrd91** [comment]
there is no way to check emptiness in `web::Json`

**Comment by fafhrd91** [comment]
other idea would be custom `OptionJson<T>` extractor.

**Comment by Ryan-Git** [comment]
can we use `any` and compare the type with `Option`?

**Comment by fafhrd91** [comment]
`web::Json` fully relies on serde, to check for Option it would required to introduce a lot of code.
it just simpler to create new extractor with specific behavior.

**Comment by Ryan-Git** [comment]
it sounds ok to me

**Comment by fafhrd91** [comment]
btw did you try `Option<web::Json<T>>`?

**Comment by Ryan-Git** [comment]
oh it works, but how?

**Comment by fafhrd91** [comment]
It maps error to None

**Comment by Ryan-Git** [comment]
in `AsyncHandler`? I can't find this logic in Json extractor.

**Comment by fafhrd91** [comment]
I don’t understand the question

**Comment by Ryan-Git** [comment]
Where does actix-web maps error to None?

**Comment by fafhrd91** [comment]
https://github.com/actix/actix-web/blob/master/src/extract.rs#L90

**Comment by Ryan-Git** [comment]
thanks, that's awesome!

**Comment by ganimp84** [comment]
@Ryan-Git not sure, if this is what you are looking for. by using [serde field attributes ](https://serde.rs/field-attrs.html#skip_serializing_if), able to conditionally skip optional fields from serialisation
```
#[derive(Debug, Serialize, Deserialize)]
pub struct MyObj {
    name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    number: Option<i32>,
}

/// This handler uses json extractor
pub fn index(item: web::Json<MyObj>) -> HttpResponse {
    println!("model: {:?}", &item);
    HttpResponse::Ok().json(item.0) // <- send response
}
```
With JSON Input:
{
	"name": "John"
}
Log:
```
model: Json: MyObj { name: "John", number: None }
```

With JSON Input:
{
	"name": "John",
	"number": 32
}
```
model: Json: MyObj { name: "John", number: Some(32) }
```

**Comment by Ryan-Git** [comment]
@ganimp84 
No, my problem is the body as a whole is optional. `Option<web::Json<T>>` just works.

**Comment by dtheodor** [comment]
This `Option<web::Json<T>>` is no good. It means *any* deserialization error will result in None. The point here is to be able to express the case where you either have no request content, or if there is request content it should be deserialized from json with the appropriate structure and the right errors returned. You should reopen this.

**Comment by robjtede** [comment]
This is an ancient issue. Please open a new one or, even better, a [discussion](https://github.com/actix/actix-web/discussions/new/choose) for help.
