### ISSUE TITLE
Improving build time, it's too slow on development

### ISSUE THREAD

**Issue by williamtran29** [actix/actix-web#805]
Currently, I use this command to run the hello world example:
`$ cargo watch --shell "pkill -f '^target/'; cargo run"`
But I see it takes 6 seconds to rebuild small changes, too slow
in Rocket framework, it takes about 2 seconds.
I already try `systemfd`, but it same

Do we have some hack to improve build time?

**Comment by fafhrd91** [comment]
I don’t see how actix could solve this problem. You should file rustc issue
