### ISSUE TITLE
If two routes are defined via codegen with the same path but different methods only one works

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#808]
For example if I have a function annotated with

#[delete("/thepath")]
and another
#[get("/thepath")]

Only the first one registered as a service will resolve and the other returns 404.

**Comment by glademiller** [comment]
This is when adding the routes to a ServiceConfig ie
```
cfg.service(handler::delete).service(handler::get)
```

**Comment by glademiller** [comment]
I tried to work around this using the guard option from codegen but apparently it doesn't try the next matching request if the guard fails because the result is the same.

**Comment by DoumanAsh** [comment]
Since attributes are parsed independently they are not really aware of each other.

Since path attribute overwrite code and remove next attribute, it is not going to be parsed(otherwise it would cause error)
The fix would require for attribute to parse all other attributes that follow it.

**Comment by glademiller** [comment]
I see how that might be complicated but from a usability standpoint I don't think this can be ignored. If your working on a RESTful API then you are going to have a resource that has different handlers for each HTTP method.

**Comment by glademiller** [comment]
Just to make sure we have maximum understanding I'm going to give a more realistic example of two handlers.

```
#[get("/thething")]
fn get_thing(req: HttpRequest) -> HttpResponse {
// Retrieves a thing
}

#[post("/thething")]
fn create_thing(req: HttpRequest) -> HttpResponse {
// Creates a thing
}

// Meanwhile in the App configuration
.service(create_thing).service(get_thing)

// Today only one of those routes works.
```

**Comment by fafhrd91** [comment]
Yes, this is clear. It is a bug. I’ll fix it later

**Comment by fafhrd91** [comment]
@glademiller i can not reproduce this problem.

https://github.com/actix/actix-web/blob/master/actix-web-codegen/tests/test_macro.rs#L33

**Comment by fafhrd91** [comment]
please provide PR with test case if you still see the problem

**Comment by glademiller** [comment]
Now that I look back I'm pretty sure I was using a manually defined resource as the post or put and the get using codegen. In those cases I can't really use the codegen until I can provide a global JSON Config.
