### ISSUE TITLE
Need IP address as string for rate limiting

### ISSUE THREAD

**Issue by dessalines** [actix/actix-web#810]
I'm trying to implement a rate-limiter based on IP address, in a websocket application, but I can't figure out how to get the IP address as a string. I've been scouring the docs and there's no mention of IP address.

I have a `addr: Recipient<WSMessage>` and a context.

So far I've tried `ctx.address()` - Can't convert to string
`msg.addr.tx.0` - Can't unbox bc its private.

**Comment by fafhrd91** [comment]
you can get IP address before you start ws actor, https://docs.rs/actix-web/1.0.0-beta.2/actix_web/struct.HttpRequest.html#method.connection_info
0.7 has similar option.

btw this is question for chat

**Comment by dessalines** [comment]
Where's the chat?

**Comment by fafhrd91** [comment]
link is in every actix's create readme

https://gitter.im/actix/actix?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
