### ISSUE TITLE
Static files are (at least sometimes) incorrectly served as both chunked and with length

### ISSUE THREAD

**Issue by malthe** [actix/actix-web#812]
This seems to be a regression since the move away from `actix_web::fs`.

This was a file of size 304 bytes. The actual payload was in fact not chunked (looking at the raw data) even though the header was sent.

**Comment by fafhrd91** [comment]
i can not reproduce, re-open if you have instructions how to reproduce

**Comment by elomatreb** [comment]
I think this is happening to me too, I can reproduce it on both of my development machines with this demo: https://github.com/elomatreb/actix-web-bug-demo

I first noticed it with image files, but it seems to occur with both large and small files (I tested single-byte text files as well as images ~150MiB in site)

**Comment by fafhrd91** [comment]
@elomatreb thanks for demo! bug is fixed in master, i will make new release later today

**Comment by elomatreb** [comment]
Thank you very much for the impressively quick fix in particular and actix in general, great work!

**Comment by fafhrd91** [comment]
actix-files 0.1.1 is released
