### ISSUE TITLE
TestServer missing in 1.0

### ISSUE THREAD

**Issue by ufoscout** [actix/actix-web#818]
Issue #694 mentions the TestServer in 1.0 but I am not able to find it. Was it removed?
We are migrating our code from 0.7 to 1.0 and we have many tests based on the TestServer, how should we upgrade them?

**Comment by fafhrd91** [comment]
TestServer is less important for 1.0, but you can still use it. It is in actix-http-test crate

**Comment by ufoscout** [comment]
@fafhrd91 
Thank you. 
Could you clarify why the TestServer is less important in 1.0? Is a better alternative that we should use instead?

**Comment by phyber** [comment]
Clarity would be good here, as the migration documentation doesn't mention this and https://actix.rs/docs/testing/ doesn't appear to have been updated.

**Comment by daviddimariaFF** [comment]
I added this to Cargo.toml:
```
[dev-dependencies]
actix-http-test = "0.2.0"
```
and this to my imports:
```
use actix_http_test::TestServer;
```
to make it compile again.
