### ISSUE TITLE
Feature request: Websocket actor support for responding to Sec-WebSocket-Protocol header

### ISSUE THREAD

**Issue by jairinhohw** [actix/actix-web#821]
Using the websocket actor from the actix-web-actors crate, i ran into a problem with trying to create an actor for handling graphql requests from Apollo using the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/) package, in that it works well in firefox, but the websocket requests don't complete on chrome due to a missing Sec-WebSocket-Protocol header on the response.
Seeing the [code (line 43)](https://github.com/actix/actix-web/blob/master/actix-web-actors/src/ws.rs) for the handshake, in the commented out part of the documentation, it appears as that at some point it was allowed to pass a list of supported protocols, but i could not find it implemented in this repository.

**Comment by fafhrd91** [comment]
you can this header yourself.

**Comment by therealprof** [comment]
That worked. It is a bit tedious to copy over all code to implement a custom handshake and also my code won't profit from any fixed to it but at least it can be done. 😅

**Comment by fafhrd91** [comment]
Pr is welcomed

**Comment by jairinhohw** [comment]
I did make it work by copying and altering the handshake to respond to any protocol request, but i don't know how to make it possible to create an websocket actor passing an optional list of protocols, otherwise it will not be possible to have the old behavior of not accepting protocol request.

**Comment by fafhrd91** [comment]
pr is merged
