### ISSUE TITLE
Feature request: json convenience method for actix_web::test::TestRequest

### ISSUE THREAD

**Issue by boustrophedon** [actix/actix-web#824]
Something like a `set_json_payload` for TestRequest would be nice.

The implementation would be pretty much the same as `actix_web::client::ClientRequest::send_json` - set the header to `application/json` and call `serde_json::to_string` on the body parameter. The only problem is that it would have to return a Result, which none of the other methods on TestRequest currently do.

I'd be willing to work on this if you think it's a good idea.

**Comment by fafhrd91** [comment]
@boustrophedon do you plan to work on this ticket?

**Comment by boustrophedon** [comment]
Sure!

What do you think about the return type? Should it return a result or panic if the data cannot be serialized?

**Comment by fafhrd91** [comment]
panic is fine for TestRequest

**Comment by fafhrd91** [comment]
merged
