### ISSUE TITLE
Query extractor Config

### ISSUE THREAD

**Issue by daddinuz** [actix/actix-web#828]
Is there something similar to JsonConfig for Query extractor? 

It would be great to customize the error handler of the Query extractor in a JsonConfig-like way.

**Comment by fafhrd91** [comment]
would you provide PR?

**Comment by daddinuz** [comment]
Sure, I already have fixed it in this [branch](https://github.com/actix/actix-web/compare/master...daddinuz:query_config). 
Before opening a new PR, I'm waiting for someone to review/comment this [issue](https://github.com/actix/actix-web/pull/830#issuecomment-490676508) since conceptually there is the same logical problem on this fix.

**Comment by daddinuz** [comment]
Hi, any update on this?

**Comment by fafhrd91** [comment]
sorry for delay
