### ISSUE TITLE
Websocket client example broken

### ISSUE THREAD

**Issue by swilcox3** [actix/actix-web#829]
The examples/websocket/client.rs doesn't compile when you uncomment the websocket-client bin and run "cargo run --bin websocket-client."  
Here's the errors:

error[E0432]: unresolved imports `actix_web::client::ClientWriter`, `actix_web::client::Message`, `actix_web::client::ProtocolError`
 --> websocket\src/client.rs:6:33
  |
6 | use actix_web::client::{Client, ClientWriter, Message, ProtocolError};
  |                                 ^^^^^^^^^^^^  ^^^^^^^  ^^^^^^^^^^^^^ no `ProtocolError` in `client`
  |                                 |             |
  |                                 |             no `Message` in `client`
  |                                 no `ClientWriter` in `client`
  |                                 help: a similar name exists in the module: `ClientBuilder`

warning: unused import: `Message`
 --> websocket\src/client.rs:6:47
  |
6 | use actix_web::client::{Client, ClientWriter, Message, ProtocolError};
  |                                               ^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error[E0191]: the value of the associated type `Result` (from the trait `_impl_act_clientcommand::actix::Message`) must be specified
  --> websocket\src/client.rs:87:20
   |
87 | impl StreamHandler<Message, ProtocolError> for ChatClient {
   |                    ^^^^^^^ associated type `Result` must be specified

error[E0191]: the value of the associated type `Result` (from the trait `_impl_act_clientcommand::actix::Message`) must be specified
  --> websocket\src/client.rs:88:31
   |
88 |     fn handle(&mut self, msg: Message, ctx: &mut Context<Self>) {
   |                               ^^^^^^^ associated type `Result` must be specified

error: aborting due to 3 previous errors

Looks like this hasn't been updated for 1.0.0-beta.3?

**Comment by fafhrd91** [comment]
create issue in examples repo

**Comment by jesskfullwood** [comment]
I think there is more to this than just the example. I tried to make a PR to fix the example and couldn't figure out a way to do it. In particular, the `Sink` and `Stream` parts of the client websocket connection are unified inside a `Framed` object, and there doesn't seem to be a way to separate them. I ended up with code like:
```
        Client::new().ws("http://127.0.0.1:8080/ws/")
            .connect()
            .map_err(|e| {
                println!("Error: {}", e);
                ()
            })
            .map(|(_response, framed)| {
                let addr = ChatClient::create(|ctx| {
                    ChatClient::add_stream(framed, ctx);  // <-- *** PROBLEM ***
                    ChatClient
                });

                // start console loop
                thread::spawn(move || loop {
                    let mut cmd = String::new();
                    if io::stdin().read_line(&mut cmd).is_err() {
                        println!("error");
                        return;
                    }
                    addr.do_send(ClientCommand(cmd));
                });
            }),
    );
```
The problem is that `framed` has been consumed, so we have lost access to the `Sink` side of the connection, and so cannot send messages, only receive them. Seems like a problem with the API?

Also noticed some inconsistencies in the API, e.g. how `StreamHandler` trait receives a `ws::Message` but I think it ought to be a `ws::Frame`?

**Comment by fafhrd91** [comment]
you can split Framed object
