### ISSUE TITLE
Can Actix do http get requests?

### ISSUE THREAD

**Issue by dessalines** [actix/actix-web#831]
The [actix docs on requests](https://actix.rs/docs/request/) actually have nothing to do with requests, but rather setting up post endpoints.

Or should I just use [reqwest](https://github.com/seanmonstar/reqwest)?

**Comment by fafhrd91** [comment]
https://docs.rs/actix-web/1.0.0-beta.3/actix_web/client/index.html

This is chat question

**Comment by bedorlan** [comment]
> This is chat question

not quite. it is a google question and it got me here. thx.

**Comment by robjtede** [comment]
[https://docs.rs/awc](https://docs.rs/awc/3.0.0-beta.9)

**Comment by bitmage** [comment]
This is a more complete example of how to use `awc` or `reqwest` within `actix_web`.

https://github.com/actix/examples/blob/master/http-proxy/src/main.rs#L139-L144

Both `reqwest` and `awc` can be passed in through `app_data()` safely it would seem, and this would result in one client (or at least one reference to the client) being created for each actix thread.

Just leaving this note for anyone (like me) who arrives here searching for an answer to this.
