### ISSUE TITLE
Can't identify the original resource that invoked the request handler

### ISSUE THREAD

**Issue by autodidaddict** [actix/actix-web#833]
I'm building an application that creates routes dynamically based on configuration and then hands off the handlers of those requests to the things that created them. This correlation, at least in my plans, was to be done using the `name` field of the resource. In other words, in my request handler (which is called by multiple resources), I check the value of `request.resource().name()` , but the `resource()` responsible for the dispatching of the given request to the given function doesn't seem to be available.

Is there some data structure or trick I can use in order to get this correlation to work?

Thanks!

**Comment by robjtede** [comment]
New method introduced in v3 should solve your issue: https://docs.rs/actix-web/3/actix_web/struct.HttpRequest.html#method.match_name
