### ISSUE TITLE
Handle cancellation of uploads

### ISSUE THREAD

**Issue by Keats** [actix/actix-web#834]
With the latest version of actix-web and the examples, it doesn't look like cancellation is supported?
Eg, upload a file big enough in the example, refresh/cancel the request and the actix server is left hanging waiting for more. 
Doing Ctrl+c to stop the server will show a panic `thread 'actix-rt:worker:2' panicked at 'Safety get dropped but it is not from top-most task',`

**Comment by fafhrd91** [comment]
this is same as #736, i'll fix it later this week

**Comment by Keats** [comment]
I'm not sure if it's 100% the same thing.
The multipart stream should error if it is cancelled by the user, the other issue is not mentioning cancellation

**Comment by fafhrd91** [comment]
should be fixed in beta.4

**Comment by Keats** [comment]
I'm on `rc` right now but I don't think this solves the core issue. It does not panic anymore but the handler is still stuck waiting for more content.
Is there an idiomatic way to handle user cancellation?

**Comment by fafhrd91** [comment]
i need test case or at least reproducible example

**Comment by Keats** [comment]
Run https://github.com/actix/examples/tree/master/multipart with a big file and cancel the upload in the browser. As far as I can see no events/errors are raised in that case

**Comment by fafhrd91** [comment]
fixed in multipart-0.1.1

**Comment by Keats** [comment]
Thanks, I'll try next week and report

**Comment by Keats** [comment]
Works perfectly, thanks!
