### ISSUE TITLE
Add 'default_service' for ServiceConfig

### ISSUE THREAD

**Issue by ririsoft** [actix/actix-web#837]
Hello,

As far as I understand (sorry I am new to Actix), the only way to specify a default service at ServiceConfig level is to use a `Scope` service.

Would it make sense to have a `default_service` method at `ServiceConfig` level or I have missed something ?

**Comment by fafhrd91** [comment]
I am not sure that makes sense. default service is app wide

**Comment by ririsoft** [comment]
Sorry but I do not understand the purpose of `ServiceConfig`. Considering #797 and this issue it looks a bit too limited to me (again I am new to actix, sorry if I am missed something).

My usecase is the following : I want to create my application in a single function so that I am able to use it with `HttpServer::new` as my main application entry point, but also in several unittests using `call_service` utility.

One could argue that I can test my application through integration tests, running a true server, but my intention is to unittest my routing rules as a whole, I do not need a full server setup for that.

Actually I can build a `create_app` function that returns a `App` but I need to import several "low level" actix crates and objects into the namespace, making my code over complicated for such a simple use case.

I though `ServiceConfig` was designed for that. What pattern would you recommend for my use case then, please ?

Thank you very much in advance for your time.

**Comment by nebnes** [comment]
@ririsoft Have you feedbacks/advices about your past issue ?

**Comment by ririsoft** [comment]
> @ririsoft Have you feedbacks/advices about your past issue ?

No sorry @nebnes, I am not using actix anymore, I moved to tide.

**Comment by nebnes** [comment]
@ririsoft ok thanks ;)
