### ISSUE TITLE
Any way we can make WsClientError Send?

### ISSUE THREAD

**Issue by thedodd** [actix/actix-web#838]
I've been working with some code which needs to handle https://docs.rs/awc/0.1.1/awc/error/enum.WsClientError.html instances, but discovered that the type is `!Send`.

The plan was to send these error instances over to the addr of the actor which spawned the future which these error instances are coming from. Still possible to get around this, but I was just curious as to why the error would not be `Send`.

Looks like this really boils down to https://docs.rs/actix-http/0.1.1/actix_http/error/struct.Error.html being `!Send`. It is a wrapper around `Box<ResponseError>` which is a trait: https://github.com/actix/actix-web/blob/master/actix-http/src/error.rs#L57

Without having looked too much more deeply, we might be able to do `pub trait ResponseError: fmt::Debug + fmt::Display + Send { ... }`, but I would have to test to see how many of the other types which the trait is implemented for are actually `Send`. That could be the major impediment.

**Comment by fafhrd91** [comment]
it is not possible. HttpResponse is Error, and response is !Send

**Comment by fafhrd91** [comment]
that is main reason why I dropped failure

**Comment by thedodd** [comment]
+1

**Comment by fafhrd91** [comment]
possible solution would be to separate SendRequestError and WsClientError error, but i dont have any time atm
