### ISSUE TITLE
Codegen with parameters in the path only resolves the first registered endpoint 

### ISSUE THREAD

**Issue by glademiller** [actix/actix-web#841]
See failing test in my fork here
https://github.com/glademiller/actix-web/blob/bug/codegen_with_macros_breaks/actix-web-codegen/tests/test_macro.rs#L32-L69

**Comment by fafhrd91** [comment]
Could you submit test case

**Comment by glademiller** [comment]
yes the link above includes a test case which currently fails.

**Comment by glademiller** [comment]
I added a PR for the test case https://github.com/actix/actix-web/pull/842

**Comment by fafhrd91** [comment]
run "cargo update" that should fix the problem
