### ISSUE TITLE
HttpServer::shutdown_timeout low maximum

### ISSUE THREAD

**Issue by herbertjones** [actix/actix-web#848]
https://docs.rs/actix-web/1.0.0-beta.5/actix_web/struct.HttpServer.html#method.shutdown_timeout

This method is limited to u16, supporting a maximum of 18 hours for gracefully shutting down.  Internally it casts that to u64 and creates a Duration.  I was thinking about using actix for uploading, and would prefer to allow slow uploaders more time when a graceful shutdown is done.  Perhaps the u16 could be changed to u64 or u32 or Duration.  If this sounds good I can make a PR also.

**Comment by fafhrd91** [comment]
strange use case, but ok. we can use u64

**Comment by herbertjones** [comment]
Thanks!  Yeah, sometimes people like to upload large files from slow connections and I'd prefer to keep them from hating me.

**Comment by fafhrd91** [comment]
fixed by #849
