### ISSUE TITLE
Typos on lib.rs

### ISSUE THREAD

**Issue by olekspickle** [actix/actix-web#854]
I believe you have something wrong regarding actix-files description on lib.rs.

![Screenshot from 2019-05-20 18-13-29](https://user-images.githubusercontent.com/22867443/58032565-88c60600-7b2b-11e9-958b-f9fa8936c021.png)

Or not. In either case release dates look a bit confusing.

**Comment by fafhrd91** [comment]
i can not do anything, release is yanked
