### ISSUE TITLE
Add data from middleware to  handlers

### ISSUE THREAD

**Issue by cheolgyu** [actix/actix-web#855]
I want to check.
  /api/v1/users/{ceo_id}/shop/{ ceoShop_id}/products/{ceo_product_id} is normal.
But
/api/v1/users/{ceo_id}/shop/{other_ceoShop_id}/products/{other_ceo_product_id}  is invalid.

Use the jwt token and include user_id, user_role.
However, the jwt token data does not include all products_id.
In middleware I find shop.id, product.id as a jwt token in the table
We then check the regular expression and try to return it if it is other_ceoShop_id or other_ceo_product_id.

Question 1. But how do I pass the id structure of the table data to the handler?
Question 2. How to pass data to middleware's handler?
Question 3. I want an example that passes from middleware to a data handler.

ServiceRequest.req is not published.
Middleware :: Is identity used session? 
Is from_request using a session?

I try this example.
https://github.com/actix/examples/blob/master/middleware/src/simple.rs <- Easy.
https://github.com/actix/actix-web/blob/master/src/middleware/identity.rs <- It is difficult.

Thank you

**Comment by fafhrd91** [comment]
you can use extractor instead of middleware (ie FromRequest) in that case handler get it as parameter
or you can set request extension, then you can read extensions in handler function.

**Comment by cheolgyu** [comment]
Thank you.
The method to get as a parameter using FromRequest succeeded.
Where can I find examples of using request extensions?

**Comment by fafhrd91** [comment]
https://docs.rs/actix-web/1.0.0-rc/actix_web/struct.HttpRequest.html#method.extensions_mut

**Comment by cheolgyu** [comment]
Each handler using 'to_async' has a common logic to query db.
I am trying to do this logic in from_request but it is not good.
In the case of from_request, it gets the value from the 'path' extractor and gets the db variable in app.warp, but 'println ()' in the corresponding message handler function is not displayed in DbExecutor.send.

Would not it be nice to put a common long job in middleware?
And can middleware retrieve 'DbExecutor' into app.warp?

Should handlers using 'to_async' call their own common logic?

thank you

**Comment by fafhrd91** [comment]
you can get app data via https://docs.rs/actix-web/1.0.0-rc/actix_web/dev/struct.ServiceRequest.html#method.app_data

**Comment by cheolgyu** [comment]
thank you.
I tried to use a comfortable path extractor in middleware but I can not find it in servicerequest.
In middleware or in form_request, I need to query db synchronously. I forgot to use DbExecutor asynchronously.
As usual in db2.send (Get {id: 1}). From_err (), I can not catch the error.
If you find a synchronous example and try it out, you'll have to turn it off by calling its handler function.

And it would be even better if there is an example in github that looks up in middleware or form_request using DbExecutor.

thank you very much.

**Comment by cheolgyu** [comment]
ㅜㅜ
```
fn call(&mut self, mut req: ServiceRequest) -> Self::Future {
...
let mut db = req.app_data::<Addr<DbExecutor>>().unwrap();
let conn = &db.0.get().unwrap();
...
"field `0` of struct `actix_web::data::Data` is private"
```

**Comment by fafhrd91** [comment]
`Data` implements `Deref`

**Comment by cheolgyu** [comment]
Thanks to the middleware for DB query.
```
let pool = req
            .app_data::<r2d2::Pool<diesel::r2d2::ConnectionManager<diesel::PgConnection>>>()
            .expect("get app_data err 222222222")
            .get_ref()
            .get()
            .expect("pool err1111111111");
```
I have added a new connection pool to app.data due to the connection pool being used by the DBActor. If I have stored the actor address <dbexe> in app.data and look for the actor address <dbexe>, it returns the actor address. Do you know how to convert and find the dbexe in the actor's address?

**Comment by ndelvalle** [comment]
I have something similar working using `deref` as fafh suggested:

```rust
        let database = req
            .app_data::<actix_web::web::Data<Addr<database::Database>>>()
            .unwrap()
            .get_ref()
            .clone();
```
