### ISSUE TITLE
Client always connect to domain timeout under windows-msvc

### ISSUE THREAD

**Issue by deepseeksss** [actix/actix-web#858]
```
use actix_rt::System;
use awc::Client;

fn main() {
    System::new("test").block_on(lazy(|| {
       let mut client = Client::default();

       client.get("http://www.rust-lang.org") // <- Create request builder
          .header("User-Agent", "Actix-web")
          .send()                             // <- Send http request
          .map_err(|e| eprintln!("{:?}", e))
          .and_then(|response| {              // <- server http response
               println!("Response: {:?}", response);
               Ok(())
          })
    }));
}
```
the above code not work under windows msvc, it always return ConnectTimeout, otherwise under linux is ok

**Comment by Matrix-Zhang** [comment]
trust-dns-resolver's problem

**Comment by fafhrd91** [comment]
I can not do anything, this is trust-dns related

**Comment by tafia** [comment]
Out of curiosity, how do you know it is domain timeout?

**Comment by fafhrd91** [comment]
It is known problem

**Comment by tafia** [comment]
Thanks. There is no way to trace it down to dns directly?

**Comment by deepseeksss** [comment]
@fafhrd91 known problem? any issue tracking? i write a demo which use trust-dns-resolver  to resolve the domain is ok,,,

**Comment by fafhrd91** [comment]
try to enable trace! for actix-connect and actix-http

**Comment by fafhrd91** [comment]
you can use custom trust-dns resolver and custom timeout settings

**Comment by deepseeksss** [comment]
okay, i find the issue, actix-connect use trust-dns-resolver's read_system_conf func to construct the  ResolverConfig, where the read_system_conf will iter the windows's adapters to find nameserver, and my computer have vm's adapter, so appear the problem
