### ISSUE TITLE
Allowing shared Logger configs between threads

### ISSUE THREAD

**Issue by daddinuz** [actix/actix-web#859]
Hi!

Just saw that `Logger` only stores information about format and exclude strings.

Is there any reason behind `Logger` not beeing `Clone` and `Send + Sync` (using `Arc` instead of `Rc` for wrapping `Inner`)?

https://github.com/actix/actix-web/blob/fc85ae401486ba013865c62e6b4e867e4c0ffb75/src/middleware/logger.rs#L77

In this way a `Logger` instance could be shared between threads as follow:

```rust
use actix_web::middleware::Logger;
use actix_web::{App, HttpServer};

pub fn main() {
  env_logger::init();

  let logger = Logger::default();

  let server = HttpServer::new(move || {
        App::new()
            .wrap(logger.clone())
           // ...
    });
}
```

**Comment by fafhrd91** [comment]
What is the reason for that?

**Comment by fafhrd91** [comment]
closed as inactive
