### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by StevenDoesStuffs** [actix/actix-web#866]
Currently, the error type explicitly doesn't implement send or sync. What is the motivation behind this design choice?
It's pretty clear that the library wants us to use functions that return `Result<_, actix_web::error::Error>`, but not all types are easily converted. For example, while types that implement `std::error::Error` can be converted to `failure::Error` which then can be converted to `actix_web::error::Error`, the first cannot be directly converted to the latter, which means that the `?` operator doesn't work.

**Comment by fafhrd91** [comment]
send and sync in trait force to make all error sync and send. and that would complicate error management. also send and sync won't magically make `std::error::Error` compatible.

there is chat for this kind of questions, this is not a bug or an issue
