### ISSUE TITLE
actix_http::error::Error is !Send and !Sync

### ISSUE THREAD

**Issue by neoeinstein** [actix/actix-web#871]
This makes it difficult to include this type in other errors without first dispensing with it, either converting it to a `String` or a `Response`. I believe this is due to the `Box<dyn ResponseError>` not including `+ Send + Sync` requirements. Excluding these may be intentional, but I ran into it while trying to build up some errors with some middleware that expects the Send + Sync bounds on errors.

**Comment by fafhrd91** [comment]
There is no limitation on your own error only for actix_web::Error. You can convert your error in handler

**Comment by fafhrd91** [comment]
There are several similar issues
