### ISSUE TITLE
failed to run custom build command for `ring v0.14.6`

### ISSUE THREAD

**Issue by UpdateSelf** [actix/actix-web#873]
error: failed to run custom build command for `ring v0.14.6`
process didn't exit successfully: `D:\ServerProject\Rust_Project\FeedBack\target\debug\build\ring-669acebded536063\build-script-build` (exit code: 101)
--- stdout
=::: ::\
ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\1\AppData\Roaming
CARGO: \\?\C:\Users\1\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: msvc
CARGO_CFG_TARGET_FAMILY: windows
CARGO_CFG_TARGET_FEATURE: fxsr,sse,sse2
CARGO_CFG_TARGET_OS: windows
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: pc
CARGO_CFG_WINDOWS: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: C:\Users\1\.cargo
CARGO_MAKEFLAGS: --jobserver-fds=__rust_jobserver_semaphore_2118119947 --jobserver-auth=__rust_jobserver_semaphore_2118119947
CARGO_MANIFEST_DIR: C:\Users\1\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.6
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 6
CARGO_PKG_VERSION_PRE: 
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: DESKTOP-R471R1G
COMSPEC: C:\WINDOWS\system32\cmd.exe
DEBUG: true
DNX_HOME: %USERPROFILE%\.dnx
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
GOLAND: D:\program\tools\Servers\GoLand\GoLand 2018.3.3\bin;
GOPATH: C:\Users\1\go
GOROOT: D:\program\tools\Servers\golang\
GTK_BASEPATH: C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE: C:
HOMEPATH: \Users\1
HOST: x86_64-pc-windows-msvc
JAVA_HOME: D:\program\tools\android\jdk
LD_LIBRARY_PATH: C:\Users\1\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib
LOCALAPPDATA: C:\Users\1\AppData\Local
LOGONSERVER: \\DESKTOP-R471R1G
NUMBER_OF_PROCESSORS: 8
NUM_JOBS: 8
ONEDRIVE: C:\Users\1\OneDrive
OPT_LEVEL: 0
OS: Windows_NT
OUT_DIR: D:\ServerProject\Rust_Project\FeedBack\target\debug\build\ring-7f8077d125f4de1f\out
PATH: D:\ServerProject\Rust_Project\FeedBack\target\debug\deps;C:\Users\1\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\Users\1\.cargo\bin;C:\Users\1\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;D:\program\tools\other\Git\cmd;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Users\1\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;D:\program\tools\Servers\Redis\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;D:\program\tools\Servers\golang\bin;D:\program\tools\Servers\WinSCP\;C:\Program Files\010 Editor;C:\Users\1\.cargo\bin;C:\Users\1\.dnx\bin;C:\Users\1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;D:\program\tools\other\Git\bin;D:\program\tools\android\java;D:\program\tools\android\java\bin;D:\program\tools\android\asSdk\platform-tools;D:\program\tools\Code\PhpStorm 2018.3.4\bin;;D:\program\tools\Servers\GoLand\GoLand 2018.3.3\bin;;C:\Users\1\go\bin;
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PHPSTORM: D:\program\tools\Code\PhpStorm 2018.3.4\bin;
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 5e03
PROFILE: debug
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC: C:\Users\Public
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: C:\Users\1\.rustup
RUSTUP_TOOLCHAIN: stable-x86_64-pc-windows-msvc
RUST_BACKTRACE: short
RUST_RECURSION_COUNT: 1
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\WINDOWS
TARGET: x86_64-pc-windows-msvc
TEMP: C:\Users\1\AppData\Local\Temp
TERM: ansi
TMP: C:\Users\1\AppData\Local\Temp
USERDOMAIN: DESKTOP-R471R1G
USERDOMAIN_ROAMINGPROFILE: DESKTOP-R471R1G
USERNAME: 1
USERPROFILE: C:\Users\1
VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VS150PROCOMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\
WINDIR: C:\WINDOWS
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("true")
running "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "include" "/W4" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Od" "/RTCsu" "-c" "/FoD:\\ServerProject\\Rust_Project\\FeedBack\\target\\debug\\build\\ring-7f8077d125f4de1f\\out\\montgomery.obj" "crypto/fipsmodule/bn/montgomery.c"
montgomery.c
c:\users\1\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\fipsmodule\bn\../../limbs/limbs.inl(33): fatal error C1189: #error:  "MSVC 2015 Update 2 or later is required."

--- stderr
thread 'main' panicked at 'execution failed', C:\Users\1\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\build.rs:638:9
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::begin_panic<str*>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\panicking.rs:408
   8: build_script_build::run_command
             at .\build.rs:638
   9: build_script_build::compile
             at .\build.rs:515
  10: build_script_build::build_library::{{closure}}
             at .\build.rs:453
  11: core::ops::function::impls::{{impl}}::call_once<(std::path::PathBuf*),closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\ops\function.rs:279
  12: core::option::Option<std::path::PathBuf*>::map<std::path::PathBuf*,alloc::string::String,mut closure*>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\option.rs:414
  13: core::iter::adapters::{{impl}}::next<alloc::string::String,core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\adapters\mod.rs:568
  14: alloc::vec::Vec<alloc::string::String>::extend_desugared<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1929
  15: alloc::vec::{{impl}}::spec_extend<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1826
  16: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1821
  17: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1721
  18: core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>,alloc::vec::Vec<alloc::string::String>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:1465
  19: build_script_build::build_library
             at .\build.rs:449
  20: build_script_build::build_c_code::{{closure}}
             at .\build.rs:426
  21: core::iter::traits::iterator::Iterator::for_each::{{closure}}<core::slice::Iter<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*)>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:604
  22: core::slice::{{impl}}::fold<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*),(),closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\slice\mod.rs:3150
  23: core::iter::traits::iterator::Iterator::for_each<core::slice::Iter<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*)>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:604
  24: build_script_build::build_c_code
             at .\build.rs:424
  25: build_script_build::ring_build_rs_main
             at .\build.rs:294
  26: build_script_build::main
             at .\build.rs:256
  27: std::rt::lang_start::{{closure}}<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  29: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  30: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  31: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  32: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  33: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  34: std::rt::lang_start<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  35: main
  36: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  37: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  38: BaseThreadInitThunk
  39: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by fafhrd91** [comment]
I see `c:\users\1.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\fipsmodule\bn../../limbs/limbs.inl(33): fatal error C1189: #error: "MSVC 2015 Update 2 or later is required."`

but in any case this is not Actix-web related
