### ISSUE TITLE
selected_alpn_protocol

### ISSUE THREAD

**Issue by cheolgyu** [actix/actix-web#875]
'client.get ("http://www.rust-lang.org")' to request it as https.
cargo.toml to 'actix-web = {version = "1.0.0-beta.4", features = ["ssl"]} ".
'features = ["ssl"]', and it works fine locally, but when I build with travis, I get such an error.
If you remove 'features = ["ssl"] ", travis will build well.
```
error[E0599]: no method named `selected_alpn_protocol` found for type `&openssl::ssl::SslRef` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-0.5.1/src/ssl/openssl.rs:107:62
    |
107 |         let proto = if let Some(protos) = io.get_ref().ssl().selected_alpn_protocol() {
    |                                                              ^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```

**Comment by fafhrd91** [comment]
Travis has old version of OpenSSL, which does not support alpn. There is no way to check alpn support availability

**Comment by cheolgyu** [comment]
thank you
