### ISSUE TITLE
RFE: secure-cookies without ring

### ISSUE THREAD

**Issue by igor-raits** [actix/actix-web#881]
I might be late for this party (https://github.com/actix/actix-web/issues/741), but in Fedora we do not want to package crypto libraries so we don't have ring packaged. Is there chance to get support for cookies without it?

Thanks!

**Comment by fafhrd91** [comment]
You can disable secure-cookies feature

**Comment by igor-raits** [comment]
Yeah, my problem is coming mostly from the fact that they are in default features. If it would not be in default, I would just remove it from Fedora..

**Comment by fafhrd91** [comment]
You can specify features as console arguments

**Comment by igor-raits** [comment]
@fafhrd91 I know. My point was that I'm packaging actix stuff for Fedora. Since it is enabled in default features, users of actix crates expect that it will be available by default for them without specifying any features in Cargo.toml.

I would like to avoid patching default feature list in Fedora, because then people will get inconsistent result when using Fedora package versus upstream crate from crates.io.

**Comment by fafhrd91** [comment]
as I understand for you it is just build command arguments. on other hand for me it would require to write extra documentation and answer questions. I am not planing to change default features

**Comment by igor-raits** [comment]
It is not build command arguments…

In actix-http, `secure-cookies` is in the default features. That means, whatever features you would disable in actix-session, would still pull `ring`. Since we don't have it, we do remove `secure-cookies` from actix-http which means actix-session can't compile ever since it relies on it.

```rust
error[E0432]: unresolved import `actix_web::cookie::Key`
  --> src/cookie.rs:22:44
   |
22 | use actix_web::cookie::{Cookie, CookieJar, Key, SameSite};
   |                                            ^^^ no `Key` in `cookie`

error[E0599]: no method named `signed` found for type `actix_http::cookie::jar::CookieJar` in the current scope
   --> src/cookie.rs:110:43
    |
110 |             CookieSecurity::Signed => jar.signed(&self.key).add(cookie),
    |                                           ^^^^^^

error[E0599]: no method named `private` found for type `actix_http::cookie::jar::CookieJar` in the current scope
   --> src/cookie.rs:111:44
    |
111 |             CookieSecurity::Private => jar.private(&self.key).add(cookie),
    |                                            ^^^^^^^

error[E0599]: no method named `signed` found for type `actix_http::cookie::jar::CookieJar` in the current scope
   --> src/cookie.rs:130:55
    |
130 |                         CookieSecurity::Signed => jar.signed(&self.key).get(&self.name),
    |                                                       ^^^^^^

error[E0599]: no method named `private` found for type `actix_http::cookie::jar::CookieJar` in the current scope
   --> src/cookie.rs:132:33
    |
132 |                             jar.private(&self.key).get(&self.name)
    |                                 ^^^^^^^

error: aborting due to 5 previous errors
```

Moreover, the `cookie-session` features does absolutely nothing, it is not referenced in code anywhere. I have sent PR to improve this -- https://github.com/actix/actix-web/pull/883.

But anyway, even disabling that feature doesn't get rid out of ring because actix-http pulls it by default. Myself I'm just trying to avoid patching of the upstream stuff as much as possible.

**Comment by fafhrd91** [comment]
Why do you want to pack actix-http in first place?

**Comment by igor-raits** [comment]
So I'm working on packaging of https://getzola.org which is using actix framework. So I need to package it. We are not doing vendoring in Fedora, all crates are packaged separately.

**Comment by fafhrd91** [comment]
I can disable ring for Actix-http, but it will be available for Actix-web in any case

**Comment by igor-raits** [comment]
Oh, I actually misspelled, it was actix-web, not the actix-http who has secure-cookies in default features. So basically if you look at PR, it works by coincidence because actix-web is enabling feature for secure-cookies. Otherwise, actix-session would be broken as with my comment above.

Don't get me wrong, I'm not trying to just dump some work on you. Just asking for some help with would simplify my work in Linux distributions. 

So my proposals rather would be:

1) Drop secure-cookies from default features in `actix-web`
2) 1 + drop it from default features in `actix-session`
3) I'll just carry patches downstream over and over

In any of those 3 cases, I would appreciate if you would merge #883.

**Comment by fafhrd91** [comment]
i wont change actix-web deps. no options

**Comment by igor-raits** [comment]
I'm not asking to change dependencies, I'm just asking about `default` features.

**Comment by fafhrd91** [comment]
by changing default features, usability of actix-web will be reduced for most users, it would also increase support burden for me. and this is just to pack one app. also i can't imagine anybody develop app based on linux package rather than using cargo
