### ISSUE TITLE
The 405 Method Not Allowed status code is incorrect for custom guards

### ISSUE THREAD

**Issue by ctsrc** [actix/actix-web#885]
Responding with 405 Method Not Allowed is correct when the method is what is being checked (though actix-web does not adhere to the following from https://tools.ietf.org/html/rfc7231#section-6.5.5 "The origin server MUST generate an Allow header field in a 405 response containing a list of the target resource's currently supported methods").

But when you add custom guards checking for other things like the value of the Content-Type, responding with 405 Method Not Allowed is incorrect. However, 405 Method Not Allowed is what actix-web responds to the client when a custom guard returns false.

**Comment by fafhrd91** [comment]
You can change default behavior

**Comment by mattfbacon** [comment]
How?

**Comment by beowulf1416** [comment]
how?

**Comment by beowulf1416** [comment]
https://docs.rs/actix-web/latest/actix_web/struct.Resource.html#method.default_service
