### ISSUE TITLE
Issue in app::data

### ISSUE THREAD

**Issue by spielcrypto** [actix/actix-web#899]
I get this error in the frontend from the backend `APP data is not configured, to configure use App::data() and I'm passing the data` and I have this:

```rust
pub fn graphql_routes(cfg: &mut web::ServiceConfig) {
    let db_url = get_url("DATABASE_URL");

    let schema = std::sync::Arc::new(create_schema());

    let pool = init_pool(db_url);

    let addr = SyncArbiter::start(3, move || GraphQLExecutor::new(schema.clone(), pool.clone()));

    cfg.data(addr.clone())
    .service(web::resource("/graphql").route(web::post().to_async(SendMessage::graphql)))
    .service(web::resource("/graphiql").route(web::get().to(SendMessage::graphiql)));
}

_

**Comment by fafhrd91** [comment]
It is not possible to say what is wrong with your code. And there is no issue with app::data for sure

**Comment by spielcrypto** [comment]
but if there isn't any issue in the app::data why can I run the api without error?

When I call from the frontend api the server response with this error.

it looks like in this case `cfg.data(addr.clone())` doesn't have any effect

**Comment by fafhrd91** [comment]
You can submit Pr with error test case

**Comment by fafhrd91** [comment]
It is not possible to say what is the problem from ticket description

**Comment by spielcrypto** [comment]
Now that I could migrate my API which is private I will migrate https://github.com/dancespiele/listing_people_api_actix then will be possible to show all the repository which surely I will have the same issue, please don't close this ticket

**Comment by fafhrd91** [comment]
i dont see you using `web::Data<T>`, did you check api docs and example?

**Comment by spielcrypto** [comment]
`cfg.data(addr.clone())` it comes from web::ServiceConfig

**Comment by fafhrd91** [comment]
i dont know what type is this. i still dont see `web::Data<>`

**Comment by dancespiele** [comment]
```
```

**Comment by spielcrypto** [comment]
```rust
/// send message to graphql
    pub fn graphql(db: web::Data<GraphQLState>, data: web::Json<GraphQLData>) 
        -> impl Future<Item = HttpResponse, Error = Error> {
            db
                .executor
                .send(data.into_inner())
                .from_err()
                .and_then(|people|  Ok(HttpResponse::Ok()
                        .content_type("application/json")
                        .body(people))
                )
        } 
```

which GraphQLState is

```rust
/// State with GraphQl
pub struct GraphQLState {
    pub executor: Addr<GraphQLExecutor>,
}

impl GraphQLExecutor {
    pub fn new(schema: std::sync::Arc<Schema>, pool: StartPool) -> GraphQLExecutor {
        GraphQLExecutor { schema, pool }
    }
}
```

**Comment by fafhrd91** [comment]
where do you set `GraphQLState` instance with `.data()`?

**Comment by spielcrypto** [comment]
ok I think that have to coincidence `let addr = SyncArbiter::start(3, move || GraphQLExecutor::new(schema.clone(), pool.clone()));` with `web::Data<T>`,

I will try

**Comment by spielcrypto** [comment]
That was the issue `web::Data` has to coincidence with .data(), I change `GraphQLState` for `GraphQLExecutor`

```rust
 pub fn graphql(db: web::Data<Addr<GraphQLExecutor>>, data: web::Json<GraphQLData>) 
        -> impl Future<Item = HttpResponse, Error = Error> {
            db
                .send(data.into_inner())
                .from_err()
                .and_then(|people|  Ok(HttpResponse::Ok()
                        .content_type("application/json")
                        .body(people))
                )
        } 
```
