### ISSUE TITLE
Actix module error is private

### ISSUE THREAD

**Issue by cetra3** [actix/actix-web#9]
Trying to use the [basic](https://github.com/actix/actix-web/blob/master/examples/basic.rs) example again, I get the following:

```
error[E0603]: module `error` is private
 --> src/main.rs:8:5
  |
8 | use actix_web::error::Result;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fafhrd91** [comment]
Do you use latest code? https://github.com/actix/actix-web/blob/master/src/lib.rs#L69

**Comment by cetra3** [comment]
No, I'm using 0.2.1.  I'll update

**Comment by cetra3** [comment]
0.3.* isn't in cargo.

**Comment by fafhrd91** [comment]
0.3 is not in cargo. I can not release just yet, I need to complete some more refactoring. Also 0.3 depends on h2 crate, which is not released yet.
