### ISSUE TITLE
Update all actix webpage documentation for version 1.0 

### ISSUE THREAD

**Issue by jcbritobr** [actix/actix-web#901]
All documentation from actix home page is outdated. Update the "get start" section and another examples to actix 1.0.

**Comment by arve0** [comment]
Until actix/actix-website#90 gets merged, what about a warning on the frontpage that links to docs.rs? I wasted some time trying to get the examples working, and guess other people will too.

**Comment by cldershem** [comment]
@arve0 That was a plan of mine this week, but I got swamped. The first few sections are "done" and need review, but until then you're right we should update that. I might be able to make it happen tomorrow, but PRs are welcome! :)

**Comment by fafhrd91** [comment]
Merged
