### ISSUE TITLE
Re-export NewService and IntoNewService in actix_web::dev.

### ISSUE THREAD

**Issue by andy128k** [actix/actix-web#906]
I want to be able to do

```
fn create_app() -> impl IntoNewService {
   App::new() ...
}
```

**Comment by 64** [comment]
You can use [`App::configure`](https://docs.rs/actix-web/1.0.0/actix_web/struct.App.html#method.configure) for a similar effect.

**Comment by fafhrd91** [comment]
you can depend on actix-service directly

**Comment by andy128k** [comment]
I don't want to have extra dependency and keep an eye on its version and its compatibility with actix_web. But, nevertheless, App::configure solves my issue.
