### ISSUE TITLE
SO_REUSEPORT support

### ISSUE THREAD

**Issue by rvlzzr** [actix/actix-web#91]
Some way to enable reuse_port from net2::unix::UnixTcpBuilderExt would be useful, or a way to pass in a TcpBuilder instead of a SocketAddr so things like ttl, reuse_address, reuse_port, etc can be configured as desired.

**Comment by fafhrd91** [comment]
i think this is good idea. but should HttpServer just accept std::net::TcpStream? 

would you provide PR?

**Comment by fafhrd91** [comment]
added [HttpServer::listen()](https://actix.github.io/actix-web/actix_web/server/struct.HttpServer.html#method.listen)
