### ISSUE TITLE
Get resource name from ServiceRequest inside middleware

### ISSUE THREAD

**Issue by AndreyErmilov** [actix/actix-web#911]
I use middleware for tracking request duration time. From ServiceRequest I can get the requested path looking like `/v1/projects/1/` or  `/v1/projects/2/`, etc. (the resource is `v1/projects/{project_id}/`). But it’s no use, as I need to aggregate all the requested projects into one bucket with common label that looks like `projects_resource`. Is it possible to get the resource's name or path from ServiceRequest in this form: `v1/projects/{project_id}/`?

**Comment by fafhrd91** [comment]
#833

**Comment by rofrol** [comment]
Can we close it?

**Comment by fafhrd91** [comment]
in favor of #833
