### ISSUE TITLE
Choosing my own Executor

### ISSUE THREAD

**Issue by realcr** [actix/actix-web#913]
Hi, I checked the examples and the documentation, and couldn't find a way to choose my own executor to use with `actix-web`. I was wondering if there is a way to do this.

Let me explain why I want to do this: I have some code that uses Futures 0.3 and creates a TCP server. I would like to have all the code work together on one Executor, so for example, during the processing of some HTTP request I will be able to send something asynchronously through my TCP server.

One workaround I was thinking about is creating a new executor, having my other server run there and create a `channel::mpsc` to send messages from the `actix-web` HTTP server to my TCP server. I haven't tried it yet, I was wondering if this should actually work.

An example of how this would look like is inspired by the [aiohttp library](https://aiohttp.readthedocs.io/en/stable/) (Python). See for example this piece of code:

```python
import aiohttp
import asyncio

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def main():
    async with aiohttp.ClientSession() as session:
        html = await fetch(session, 'http://python.org')
        print(html)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

In the example above it can be seen that aiohttp plays like a good citizen in the async world. It creates one future state machine, and finally the user of the library can put this state machine into any loop he wants. (`loop` can be seen as python's equivalent for Rust Futures's `Executor`).

Is there an equivalent for `actix-web`? If not, what would be a good workaround for what I'm trying to do?

**Comment by asonix** [comment]
Actix-Web doesn't have a swappable "executor" per-se, each thread it spins up uses it's own `tokio::current_thread` executor. In order to share resources with actix-web, it might be a good idea to  implement your TCP server with [Actix](https://docs.rs/actix) in mind. Take a look at [Actix-Server](https://docs.rs/actix-server/), which provides a TCP server that plays nicely in an Actix system.

If you would like to keep your current TCP server code, you could provide the Addresses of the actors you care about to your TCP server, so it can send outbound messages to Actix. In your Actix-Web state, you could include your MPSC sender so your handlers can send messages into your TCP Server system.

**Comment by asonix** [comment]
Personally, I've had a good time working with `actix_threadpool` for blocking operations, and `actix::spawn` for non-blocking operations. Since each `actix::Arbiter` acts as a handle to a current_thread executor, it's possible to manage which threads care about which operations.

Here's an example of how your integration could look:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let sys = actix::System::new();

    let bridge_actor = SomeBridgeToActix::new().start();
    // Starting your TCP Server outside the closure will ensure detachment from
    // whatever is going on in Actix Web, but still allow communication between
    // the two servers.
    let your_handle = MyTcpServer::new(bridge_actor).spin_up_or_whatever();

    actix_web::HttpServer::new(move || {
        // note that HttpServer spins up `num_cpu` threads by default,
        // and executes this closure in each of them. If you want to "share"
        // the executor with Actix Web, you'd spin up Actors here, so each
        // Actix Web thread will have it's own associated TCP Server handle.
        // Doing it this way only makes sense if you implement your TCP server
        // as an Actix actor system. 
        actix_web::App()
            .data(your_handle.clone())
            .data(bridge_actor.clone())
            .service(/* whatever */)
    })?.bind("0.0.0.0:8000")?.start();

    sys.run()?;
    Ok(())
}
```

**Comment by asonix** [comment]
Also keep in mind that Actix still relies on 0.1 futures, so any integration with 0.3 futures will need to use `compat` a lot.

**Comment by realcr** [comment]
@asonix : Hi, thanks for the very detailed response, and also for your work on this project.
I understand from your answer that I might be able to use `actix_threadpool` or an `mpsc` sender to bridge my existing server code with `actix-web`.

I read a bit more and I understand now I might had a convoluted view of how things work. I understand that `actix-web` works around some kind of an actor model, so attempting to stuff all of it inside an `Executor` might not not be possible, or might not work the way I expect.

> it might be a good idea to implement your TCP server with Actix in mind

It's probably too late for me. I think my code base might be larger than the code base of `actix-web`.
But I have to admit this generally an idea I am somewhat opposed to. What if for example I wanted to have two or three different servers, each one asking me to implement my code with his paradigms in mind? Where I come from they have this saying: ["You can't dance at two weddings"](https://idioms.thefreedictionary.com/You+can%E2%80%99t+dance+at+two+weddings) (:

This is of course not to lessen from the usefulness of `actix-web`. I am sure that if I had started from scratch using it would have been a good option.

All of my code relies on `Futures 0.3`. I am aware of the `compat `, I hoped I wouldn't need to use it ):

If you believe this is not something that `actix-web` intends to do, please feel free to close this issue.

**Comment by asonix** [comment]
I actually haven't contributed to this project! I've just used it a fair bit, but thanks for the thanks anyway!

It is still possible using channels to integrate your current TCP server code with Actix web, but sharing an executor is likely not possible. Which executor are you using for your TCP server? or is it generic over the executor?

**Comment by realcr** [comment]
> I actually haven't contributed to this project!

I think answering issues is a pretty important contribution too!

> Which executor are you using for your TCP server?

You can plug in any executor. It's a very important testing feature. I have some tests for which I use a test executor, it is the testing "super weapon" on that project:
https://github.com/freedomlayer/offst/blob/master/components/common/src/test_executor.rs
It allows to detect deadlocks, simulate the passage of time and also make sure that all the tests are deterministic.

**Comment by asonix** [comment]
Wow, this is an incredibly cool project! I'll need to take a look through the codebase sometime

**Comment by fafhrd91** [comment]
it is possible to run Actix in custom executor now

https://docs.rs/actix-rt/0.2.3/actix_rt/struct.System.html#method.run_in_executor
