### ISSUE TITLE
Lack of WebSocket continuation support

### ISSUE THREAD

**Issue by djahandarie** [actix/actix-web#916]
This is [already noted in the code](https://github.com/actix/actix-web/blob/master/actix-http/src/ws/codec.rs#L105), but actix-web's WebSocket implementation doesn't support WebSocket Continuations.

It turns out that Chrome uses continuations fairly arbitrarily, regardless of message size. This results in it being pretty hard to use actix-web's WebSockets on standard websites, since actix will just close the WS whenever Chrome decides to use a continuation.

**Comment by djahandarie** [comment]
I just discovered https://github.com/actix/actix-web/pull/530, a PR from 8+ months ago which fixes this but never got merged. :sweat_smile:

@fafhrd91 I see you approved the PR back when it was submitted. Is there any chance you (or someone of your choice) could port it to 1.0 and merge it? The original author of the PR seems to no longer be available.

**Comment by fafhrd91** [comment]
ws continutation is added to master
