### ISSUE TITLE
Compress middleware adds body to NoContent (204) response [version 1.0]

### ISSUE THREAD

**Issue by andy128k** [actix/actix-web#918]
I use a proxy (webpack-dev-server) and it rejects to pass such responses. Proxy reports them as `HPE_INVALID_CONSTANT` (HPE stands for "HTTP parse error").

Tcpdump shows that response contains body of 31 bytes.

Removal of `.wrap(Compress::default())` makes things work well.

**Comment by fafhrd91** [comment]
fixed and master, actix-http 0.2.4 is released as well
