### ISSUE TITLE
actix-session docs missing SameSite

### ISSUE THREAD

**Issue by 0xpr03** [actix/actix-web#920]
Currently the session crate [has no documentation](https://docs.rs/actix-session/0.1.1/actix_session/struct.CookieSession.html#method.same_site) for SameSite type.

Note: SameSite is imported from [actix-web](https://docs.rs/actix-web/1.0.2/actix_web/cookie/enum.SameSite.html)

**Comment by fafhrd91** [comment]
https://docs.rs/actix-web/1.0.2/actix_web/cookie/enum.SameSite.html

**Comment by fafhrd91** [comment]
it is docs.rs problem
