### ISSUE TITLE
Can not increase WebSocket payload size when using actix-web-actors.

### ISSUE THREAD

**Issue by anthonyjchriste** [actix/actix-web#925]
It is currently not possible to directly increase the max payload side for WebSockets when using actix-web-actors. 

The functionality exists in https://docs.rs/actix-http/0.2.4/actix_http/ws/struct.Codec.html#method.max_size, but it appears that the Codec can't be set directly when creating a WebSocket server.

It should be possible to either set or edit the Codec when implementing a WebSocket server.

**Comment by fafhrd91** [comment]
fixed in master
