### ISSUE TITLE
client_timeout ignored

### ISSUE THREAD

**Issue by eastern-grey** [actix/actix-web#928]
In 1.0.2, incoming connections are not closed when they fail to send a request. After an initial request, the keep alive logic appears to kick in.

test_slow_requests() was commented out in 2d7293aaf8fa7e81cec3efc2a50ffbd79f9b1de9, so not sure if this is already on your radar or not.

**Comment by dae** [comment]
Apologies if I've misunderstood the tag, but is 'awc' referring to the http client functionality of actix? This is actually an issue with the server side - HttpServer currently seems to allow incoming connections to remain open (indefinitely?) if they do not send any data.

**Comment by eastern-grey** [comment]
Apologies if I've misunderstood the tag, but is 'awc' referring to the http client functionality of actix? This is actually an issue with the server side - HttpServer currently seems to allow incoming connections to remain open (indefinitely?) if they do not send any data.

**Comment by fafhrd91** [comment]
server timeout is your responsibility. actix-web has timeout only for reading client request, not body

**Comment by eastern-grey** [comment]
Sorry if I have not been clear. This is about actix waiting forever for http request headers. The following option appears in the code:

```
    /// Set server client timeout in milliseconds for first request.
    ///
    /// Defines a timeout for reading client request header. If a client does not transmit
    /// the entire set headers within this time, the request is terminated with
    /// the 408 (Request Time-out) error.
    ///
    /// To disable timeout set value to 0.
    ///
    /// By default client timeout is set to 5000 milliseconds.
    pub fn client_timeout(mut self, val: u64) -> Self {
        self.client_timeout = val;
        self
    }

```
It currently does not appear to work - incoming connections will stay open until the client sends headers, which I imagine could result in a DoS. If client_timeout() is no longer supported, perhaps the option needs to be removed.

**Comment by fragrans** [comment]
same here;

**Comment by jcbritobr** [comment]
Are this ticket solved?
