### ISSUE TITLE
should graceful shutdown prevent new requests on existing sockets?

### ISSUE THREAD

**Issue by eastern-grey** [actix/actix-web#929]
Currently when a graceful shutdown is initiated via SIGTERM, new connections are refused, but existing keep-alive connections will continue to process requests from clients. If the clients are sending requests frequently (such as API endpoints), the keep-alive connections will not time out, and actix will end up refusing new connections until the full 30 second graceful shutdown timeout has been exceeded. Perhaps it would make more sense for workers in graceful shutdown mode to terminate after the current request has been processed, if that is possible?

**Comment by fafhrd91** [comment]
You can send SIGINT

**Comment by eastern-grey** [comment]
Indeed, that's what I've done for now. At least in my case, the current graceful shutdown behaviour results in more failed connections than immediately terminating does, but I understand if it is difficult to address or not a high priority.
