### ISSUE TITLE
content-length incorrect when compressing response

### ISSUE THREAD

**Issue by JeanMertz** [actix/actix-web#930]
I noticed that enabling either gzip or brotli compression does not change the `Content-Length` header value returned by the server.

See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13

> Applications SHOULD use this field to indicate the **transfer-length of the message-body**

<img width="1274" alt="Screenshot 2019-06-19 at 22 08 39" src="https://user-images.githubusercontent.com/383250/59796924-cfe81800-92de-11e9-8c7e-bd07ca17a7a4.png">

As you can see, `Content-Encoding` is set to `gzip`, and its original `Size` is ~54kB, which is also the same length provided in `Content-Length`, even though only 14KB of data was `Transferred`. This is all using `HTTP/2.0` with SSL.

The same happens for Brotli.

You can also validate this with cURL, as it will tell you it expected to read more data than it received:

```shell
$ curl --silent --show-error 'https://my.domain/css/fa.css' >/dev/null
$ curl --silent --show-error --compressed 'https://my.domain/css/fa.css' >/dev/null
curl: (18) transfer closed with 40422 bytes remaining to read
```

(54kB - 14kB = 40kB remaining to read)

I haven't looked into the actual middleware implementation yet, but I couldn't find any issues about this, so I'd figure I report this before I see if there's an easy fix for this problem.

---

The reason I noticed this, is because both Chrome and Firefox refuse to cache the content when the file's content length does not match the value provided in the `Content-Length` header. ~~At least that's my going theory~~, as I've ruled out anything else, and caching (and `If-None-Match` requests) work as soon as I disable compression, and the content length matches the header again.

_edit_ I validated the above by adding some middleware that _removes_ the bad `Content-Length` header, which makes caching work again, even with compression enabled.

**Comment by fafhrd91** [comment]
Actix-files 0.1.3 is released

**Comment by JeanMertz** [comment]
Thank you for the update @fafhrd91, great to see this was fixed so quickly. Appreciate it.
