### ISSUE TITLE
Optional middlewares in 1.0 because of wrap generics

### ISSUE THREAD

**Issue by aschampion** [actix/actix-web#934]
The equivalent code in prior versions used to allow for easy optional enabling of middlewares, but now because of the generic return of `wrap` it's not clear how to get a coherent type for `app` when multiple middlewares may or may not be enabled. This can't be done with `App::configure`, either.

```rust
let mut server = HttpServer::new(
        || {
            let mut app = App::new()
                .service(
                    // etc
                );
            if cors {
                app = app.wrap(Cors::new().send_wildcard());
            }
            app
        })
```
```
error[E0308]: mismatched types
   --> src/main.rs:474:23
    |
474 |                 app = app.wrap(Cors::new().send_wildcard());
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `actix_web::app_service::AppEntry`, found opaque type
    |
    = note: expected type `actix_web::App<actix_web::app_service::AppEntry, _>`
               found type `actix_web::App<impl actix_service::NewService, _>`
```

**Comment by fafhrd91** [comment]
good question. there is no solution at the moment. we need `Optional` service.

**Comment by KeenS** [comment]
How about writing a middleware that conditionally enable another middleware like this?
https://github.com/KeenS/actix-web-condition-middleware

If this is acceptable, I'll submit a PR to this repository.

**Comment by fafhrd91** [comment]
@KeenS looks good. pr is welcomed!

**Comment by fafhrd91** [comment]
Condition middleware has been added to master

**Comment by aschampion** [comment]
I'm still not sure how to wire this up:

```sh
    Checking h2n5 v0.1.3 (/Users/championa/code/rust/h2n5)
error[E0277]: the trait bound `actix_web::middleware::Condition<actix_cors::Cors>: actix_service::transform::IntoTransform<_, actix_web::app_service::AppRouting>` is not satisfied
   --> src/main.rs:469:18
    |
469 |                 .wrap(actix_web::middleware::Condition::new(cors, Cors::new().send_wildcard()))
    |                  ^^^^ the trait `actix_service::transform::IntoTransform<_, actix_web::app_service::AppRouting>` is not implemented for `actix_web::middleware::Condition<actix_cors::Cors>`

error: aborting due to previous error
```

The `IntoTransform` trait and related bounds around `Condition` are complex. Just using `Cors::default()` works (but is useless to me), so it's something to do with the `IntoTransform` bounds on `Cors` vs. `CorsFactory`. I can't call `into_transform` on the `Cors` struct to get a `CorsFactory`, because it can't infer the type for `S` in `IntoTransform<_, S>`.

I'm lost.

**Comment by KeenS** [comment]
@aschampion Hmm... It reveals that `Condition` have poor support of `IntoTransform`. I guess we need another type to generate `Condition` using `IntoTransform`.

Adding code below and changing `Condition::new` to `WrapCondition::new` should let your code compile.

```rust
use actix_service::{IntoTransform, Service, Transform};

pub struct WrapCondition<T> {
    trans: T,
    enable: bool,
}

impl<T> WrapCondition<T> {
    pub fn new(enable: bool, trans: T) -> Self {
        Self { trans, enable }
    }
}

impl<S, T, Target> IntoTransform<Condition<Target>, S> for WrapCondition<T>
where
    S: Service,
    T: IntoTransform<Target, S>,
    Target: Transform<S, Request = S::Request, Response = S::Response, Error = S::Error>,
{
    fn into_transform(self) -> Condition<Target> {
        Condition::new(self.enable, self.trans.into_transform())
    }
}

```

Could you try this?

And we need distribute code like this for other users.

**Comment by aschampion** [comment]
Thanks, @KeenS! That seems to work.

**Comment by neoneye** [comment]
Thanks for adding this `Condition` middleware, with good example of usage
https://docs.rs/actix-web/3.3.2/actix_web/middleware/struct.Condition.html

**Comment by ppamorim** [comment]
@neoneye It seems to not be working properly with:
```rust
.wrap(Condition::new(env.as_str() == "production", HttpAuthentication::bearer(validator)))
```
