### ISSUE TITLE
middleware::errhandlers::ErrorHandlers

### ISSUE THREAD

**Issue by beykery** [actix/actix-web#936]
i use 

`middleware::errhandlers::ErrorHandlers::new().handler(http::StatusCode::INTERNAL_SERVER_ERROR, errhandle::render_500)`

for processing the error 500 in my application as the example in errhandlers.rs

how can i modify the response body ? the example just modify a response header .

**Comment by fafhrd91** [comment]
https://docs.rs/actix-web/1.0.2/actix_web/struct.HttpResponse.html#method.map_body

https://docs.rs/actix-web/1.0.2/actix_web/struct.HttpResponse.html#method.take_body

example https://github.com/actix/actix-web/blob/master/src/test.rs#L314

**Comment by beykery** [comment]
thank , as the test.rs :
`
  res.take_body().take_body()
        .fold(BytesMut::new(), move |mut body, chunk| {
            body.extend_from_slice(&chunk);
            Ok::<_, Error>(body)
        });
`
but it result in :
error[E0599]: no method named `fold` found for type `actix_http::body::ResponseBody<B>` in the current scope

**Comment by fafhrd91** [comment]
use futures::Stream;

**Comment by beykery** [comment]
sorry it dont work as bellow ：

`
use actix_web::{get, middleware, web, App, HttpRequest, HttpResponse, HttpServer, dev, http, Result, Error};
use actix_web::middleware::errhandlers::ErrorHandlerResponse;
use serde::{Serialize, Deserialize};
use actix_web::dev::ServiceResponse;
use actix_http::http::StatusCode;
use actix_http::Response;
use actix_web::web::BytesMut;
use futures::Stream;

pub fn render_500<B>(mut res: dev::ServiceResponse<B>) -> Result<ErrorHandlerResponse<B>> {
    res.take_body()
        .fold(BytesMut::new(), move |mut body, chunk| {
            body.extend_from_slice(&chunk);
            Ok::<_, Error>(body)
        });
    Ok(ErrorHandlerResponse::Response(res))
}
`

error[E0599]: no method named `fold` found for type `actix_http::body::ResponseBody<B>` in the current scope

**Comment by fafhrd91** [comment]
You may need to add B: MessageBody

https://github.com/actix/actix-web/blob/master/actix-http/src/body.rs#L104

**Comment by beykery** [comment]
i can't get it .

**Comment by pedrogao** [comment]
I can't get it too.

**Comment by Voronar** [comment]
https://users.rust-lang.org/t/actix-web-using-a-custom-error-handler-to-alter-the-response-body/41068/2
