### ISSUE TITLE
Error reporting in 1.0

### ISSUE THREAD

**Issue by eastern-grey** [actix/actix-web#938]
I am still quite new to actix and rust in general, so I apologise if I have missed something obvious in the text below.

In actix-web 0.7, if a handler returned an actix Error, the error message was logged:

```
ERROR 2019-06-24T07:29:59Z: actix_web::pipeline: Error occurred during request handling, status: 500 Internal Server Error test
DEBUG 2019-06-24T07:29:59Z: actix_web::pipeline: Custom { kind: Other, error: StringError("test") }
INFO 2019-06-24T07:30:00Z: actix_web::middleware::logger: 127.0.0.1:56449 "GET /error HTTP/1.1" 500 0 "-" ...
```

In 1.0, errors no longer appear to be logged. If the logger middleware is enabled, it is possible to see that a handler has returned a 500 response, but actix gives no indication of what the error actually was in the logs.

```
 INFO 2019-06-24T08:49:54Z: actix_web::middleware::logger: 127.0.0.1:59661 "GET /error HTTP/1.1" 500 4 "-" ...
```

I gather that I can implement a custom error type in order to log the error, and optionally display something else in the http response. The following seems to work:

```
#[derive(Debug)]
struct UserError {
    err: failure::Error
}

impl actix_web::error::ResponseError for UserError {
    fn error_response(&self) -> HttpResponse {
        error!("caught internal server error: {:?}", self);
        HttpResponse::new(
            http::StatusCode::INTERNAL_SERVER_ERROR)
    }
}

impl fmt::Display for UserError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "hidden error")
    }
}

impl<T: Into<failure::Error>> From<T> for UserError {
    fn from(t: T) -> UserError { UserError { err: t.into() } }
}

#[get("/error")]
fn errortest() -> impl Future<Item = String, Error = UserError> {
    futures::future::err(format_err!("test fail")).from_err()
}
```

But that took me quite some time to figure out as someone new to the ecosystem. The other web frameworks I have used in the past all hide error messages from end users by default, and show them only to the developer, so the fact that actix does the opposite caught me by surprise. While custom error types may be the best solution in the long run, for the benefit of people starting out, might it make more sense if actix's Error type behaved differently to how it does now?

Thanks for all your work on actix :-)

**Comment by vmalloc** [comment]
I'm also hitting this issue, and it also seems to not be working in regular (non-async) routes...

**Comment by vmalloc** [comment]
@fafhrd91 I'd like to attempt to fix this in a PR. Can you point me at where this logic is implemented? Is it in `actix-http`? If so, how can I set up a working (local) checkout with which I can test this?

**Comment by fafhrd91** [comment]
Error and RespinseError are defined in actix-http. But I don’t think this is the bug, it is a problem of docs and probably not very well designed api.

**Comment by vmalloc** [comment]
@fafhrd91 You mean the api of actix itself? I looked through the code of actix-http and couldn't find a place that actually calls `debug!` for error cases, although I might be missing something.
As for the use case, I think this is a very common case - for example in my case (using diesel):
```rust
fn query_objects(db: web::Data<DB>) -> Result<HttpResponse, Error> {
    let returned = my_collection
        .limit(10)
        .load::<SomeObject>(&db.connection_pool.get()?)?;
    Ok(HttpResponse::Ok().json(returned)
}
```
Without support for error logging, one would have to remember to add logs to every possible invocation of `execute`/`load`/etc., which is of course very easily forgotten, until the error actually happens and you don't have any logs :-(

**Comment by fafhrd91** [comment]
@vmalloc sorry, i missread issue. seems i forgot to port error logging.

it could be done here https://github.com/actix/actix-web/blob/master/src/middleware/logger.rs#L203
you can get access to error via this method https://github.com/actix/actix-web/blob/master/actix-http/src/response.rs#L98

**Comment by vmalloc** [comment]
@fafhrd91 👍 I will try to add it in. Thanks!

**Comment by vmalloc** [comment]
@fafhrd91 any objections that I make it an `error!`? I think a server returning 500 merits an error log in such cases...

**Comment by fafhrd91** [comment]
error! For 500 is ok, but some errors could be converted to different status codes and I am not sure it is good idea to use error for them

**Comment by vmalloc** [comment]
I opened a PR to restore the original behavior (logging as `debug!`). Will try to create an additional one to log internal server errors as `error!`, as this is critical for production deployments (actix_web tends to be set on a log level higher than debug for such cases)

**Comment by vmalloc** [comment]
My PR now contains code to log internal server errors as well. Feedback is most welcome!

**Comment by cypressf** [comment]
I'm not seeing any 500 response-code errors logged with log_level set to INFO using actix_web 4.3.1 and actix-http 3.3.1. Is there something I need to do to enable such logging?

```rust
use actix_web::{web, App, HttpResponse, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new().service(
            web::resource("/")
                .to(|| async { HttpResponse::InternalServerError().body("bad error") }),
        )
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await?;
    Ok(())
}

// cargo run
// curl 127.0.0.1:8080
// 
// Expected: log output
// Result: no internal server error logged
```

**Comment by robjtede** [comment]
@cypressf This issue is very old and not relevant to your version on Actix Web. Please open a [new discussion](https://github.com/actix/actix-web/discussions) with your question. Someone will be happy to answer there.
