### ISSUE TITLE
Slow static files serving

### ISSUE THREAD

**Issue by 8cichy8** [actix/actix-web#942]
Hello, as I mentioned earlier on gitter, I'm posting my problem.
When moved from 0.7.19 to 1.0.0 I did noticed a lot slower files serving. 

Reproducible examle is here: [https://github.com/8cichy8/files-test](https://github.com/8cichy8/files-test)
Run localhost:8081 in chrome (if possible) with opened console and disabled cache.

It looks like, when requests are near (reusing same connection?), then it starts downloading files really slow. However, when I made my custom function for serving files, it isn't affected! (last test in example)

Here you can see pictures from chromium console. It is request on same file and same service, however before first there was not any request, but second ran immediately after the first ...

1) fast download
![files_test_fast](https://user-images.githubusercontent.com/4511522/60113802-d0ffc600-9772-11e9-85ea-81c0087523cb.png)

2) slow download
![files_test_slow](https://user-images.githubusercontent.com/4511522/60113822-d78e3d80-9772-11e9-9dd7-e1efd9087a4f.png)

All requests are made synchronously.
Tested on debian.

Thanks

**Comment by dutchmartin** [comment]
I could reproduce this issue on Ubuntu with Chrome and Firefox.
The timeline on Firefox looks like this after running the code provided by @8cichy8 :
![image](https://user-images.githubusercontent.com/5509155/62322602-b1606980-b4a5-11e9-9128-e8ca61a30781.png)

**Comment by omid** [comment]
There is no problem with the latest versions.
You can see my changes in the PR: https://github.com/8cichy8/files-test/pull/1

![Screenshot from 2020-05-03 12-08-18](https://user-images.githubusercontent.com/45714/80911468-d9337500-8d36-11ea-9f20-5d13bdbffbb9.png)

**Comment by zzau13** [comment]
Another fast web server implementations have a LRU cache for this task, [h2o](https://github.com/h2o/h2o/blob/master/lib/common/filecache.c) is an example. 

Should we implement something like this?

**Comment by 8cichy8** [comment]
Hello again and sorry for big delay. I tested it again and it seems lot better. Now it happens (slowness) only with few (1 to 5) requests from 50 (before it was 50 from 50). So, we can say it's almost okay. It probably can be closed ...
