### ISSUE TITLE
Is ``changed`` unnecessary in SessionInner?

### ISSUE THREAD

**Issue by jensmetzner** [actix/actix-web#943]
I'm currently reimplementing cookie sessions (to gain a better understanding of actix-web and its services) and I noticed that the field ``changed`` is set to true 3 times but apart from that the field is never used. Is it used somewhere else and I missed something?

https://github.com/actix/actix-web/blob/c0c71f82c00fdac964bcf588c2ea49c4c18d5de7/actix-session/src/lib.rs#L104

https://github.com/actix/actix-web/blob/c0c71f82c00fdac964bcf588c2ea49c4c18d5de7/actix-session/src/lib.rs#L120

https://github.com/actix/actix-web/blob/c0c71f82c00fdac964bcf588c2ea49c4c18d5de7/actix-session/src/lib.rs#L130

https://github.com/actix/actix-web/blob/c0c71f82c00fdac964bcf588c2ea49c4c18d5de7/actix-session/src/lib.rs#L137

**Comment by fafhrd91** [comment]
#912 addresses this
