### ISSUE TITLE
Support to retrieve SSL related information in a handler

### ISSUE THREAD

**Issue by magnet** [actix/actix-web#946]
We're doing SSL certificate based validation, and we would like to access the peer certificate in handlers. Currently, it does not seem possible with Actix-Web. 

We can retrieve the information we want using OpenSSL's `SslAcceptorBuilder`'s callbacks (e.g `set_verify_callback`) but we cannot access any information about the Actix socket in there; in Actix middlewares or request handlers, we cannot access anything about SSL either.

Ideally, there would be a way to let us build an extension that lets us query the SSL information we're interested in (which would then be able to access in the request handlers or middlewares).

**Comment by 64** [comment]
Is this possible with a custom connector?

**Comment by fafhrd91** [comment]
added HttpServiceBuilder::on_connect()
