### ISSUE TITLE
Update to std::future::Future futures/0.3

### ISSUE THREAD

**Issue by pythoneer** [actix/actix-web#955]
`std::future::Future` is now in stable with Rust 1.36.0. What are the plans for migration? I think one mayor obstacle is at which point tokio is using them right? Do they already have? i am a little bit out of the loop https://github.com/tokio-rs/tokio/pull/1218

**Comment by fafhrd91** [comment]
actix-service must be ported first. It does not depend on tokio

**Comment by leaxoy** [comment]
How about use `tower::Service` instead

**Comment by fafhrd91** [comment]
I tried, it does not work well. Also I don’t want to depend on external dependency. So no tower

**Comment by leaxoy** [comment]
Okey, but can we provide a bridge between `actix-service` and `tower` as an optional feature?

**Comment by fafhrd91** [comment]
There is project in actix-net repo. But I am not interested in that project. I can move it outside so other people can work on it

**Comment by naturallymitchell** [comment]
Seems like a lot's going on now, eg [tokio 0.2.0-alpha-1](https://tokio.rs/blog/2019-08-alphas/).

**Comment by krircc** [comment]
There is also [async-std](https://async.rs/blog/announcing-async-std/) library.  [like this 1.0](https://async.rs/blog/announcing-async-std/#the-path-towards-1-0) and [status](https://async.rs/status/), maybe it is a good choose.

**Comment by leaxoy** [comment]
Async/Await stable pr is merged in today nightly version, should we start the process to update to `std::future::Future`

**Comment by zmlzm** [comment]
![img](https://raw.githubusercontent.com/zmlzm/nothing/master/2019-08-28%2007-57-50%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

I don't think it is a good news. But i really want to know when actix-* update, @fafhrd91 Do you plan to wait for tokio 0.2 or something others?

**Comment by semtexzv** [comment]
I started the work on migrating the actix-net ecosystem, which is needed in order to convert the 
actix-web libraries. Work can be seen here: https://github.com/actix/actix-net/issues/45.

**Comment by kanekv** [comment]
Are there any plans to migrate to tokio 0.2?

**Comment by Jonathas-Conceicao** [comment]
The migration has started on actix-net, there's a migration tracking issue [there](https://github.com/actix/actix-net/issues/45).

**Comment by wigy-opensource-developer** [comment]
I see this issue assigned to the 1.1 milestone. I doubt you can migrate to tokio 0.2 and async-await without breaking changes in the API. Based on that and semantic versioning the next actix-web version should be 2.0, right?

**Comment by cdbattags** [comment]
> The migration has started on actix-net, there's a migration tracking issue [there](https://github.com/actix/actix-net/issues/45).

We're going to need some help starting with the `actix-service` folder in `actix-net`.

See https://github.com/actix/actix-net/pull/57.

If you'd like to help, please converse in that PR and and/or if you have work open a PR into `actix-net/std-future` branch.

We should be able to get this done pretty quickly just need some minds to start talking it through.

**Comment by cdbattags** [comment]
Just landed in actix-net https://github.com/actix/actix-net/pull/64

Fantastic work, @fafhrd91!

**Comment by 0xpr03** [comment]
> the next actix-web version should be 2.0, right?

I'm all for that, people that need futures 0.1 and fixes can then still stay on 1.X
I think a 2.0 release would also reflect the amount of work that went into the async/await port and the changes when writing async stuff for actix-web.
(In other words: please don't repeat the 1.0.2 breaking changes.)

**Comment by fafhrd91** [comment]
tracking issue #1166
