### ISSUE TITLE
discrepancy in NormalizePath behavior from v0.7 to v1?

### ISSUE THREAD

**Issue by jspeis** [actix/actix-web#959]
I'm relatively new to actix-web and I'm working on migrating some code from v0.7.18 to v1.0.3 of actix web. 

Previously I had some code along these lines:

(v0.7.18)
```rust
use actix_web::{server, App, Path, Responder};
use actix_web::http::NormalizePath;

fn index(info: Path<()>) -> impl Responder {
    format!("Hello there!")
}

fn main() {
    server::new(|| {
        App::new()
            .resource("/test", |r| r.with(index))
            .default_resource(|r| r.h(NormalizePath::default()))
    }).bind("127.0.0.1:8080")
        .unwrap()
        .run();
}

```
Now in v1.0.3 I'm trying something along the lines of:

```rust
use actix_web::{middleware, HttpResponse};

fn index() -> HttpResponse {
    HttpResponse::Ok().body("Hello there!")
}

pub fn main() {
    use actix_web::{web, App, HttpServer};

    HttpServer::new(|| {
        App::new()
            .wrap(middleware::NormalizePath::default())
            .route("/test", web::to(index))
    })
    .bind("127.0.0.1:8088")
    .unwrap()
    .run()
    .unwrap();
}
```

For me the biggest discrepancy in functionality is that in v0.7.18, whether a user hits `/test` or `/test/` both routes will work (which was great!) -- but it seems like as of v1.0.3 only `/test` works in this example. Not sure if I'm missing something or if the behavior changed intentionally or unintentionally?

Thank you for your help!

**Comment by fafhrd91** [comment]
I ported normalize path handler when it was not possible to port it as is, but it could be ported in 1.0

**Comment by jspeis** [comment]
@fafhrd91 I'd be happy to help if I can with porting this functionality to 1.0. 

One quick thing could be to use [trim_end_matches("/")](https://doc.rust-lang.org/std/primitive.str.html#method.trim_end_matches) to remove trailing slashes from user requests. But my question would be how would you recommend going about handling the registration side of things? I think from a user perspective, it would be nice if: When using normalize path, I could register either `/test` or `/test/` and they would both work (e.g. using either `.route("/test", web::to(index))` or `.route("/test/", web::to(index))`). Is there anyway that the route registration could interface with the middleware to also trim the trailing slashes? Or is there an alternative approach you have in mind?

**Comment by fafhrd91** [comment]
@jspeis if you are still interested.

i see two options:

* your idea. It should be easy to create custom version of `Resource` type, that would be `trailing` slash aware. so it would be just full actix-web's Service impl. downside you would need to use different types.
* i just added `.resource_map()` method to `ServiceRequest` and `HttpRequest` types. so you
can check if resource map contains handler for specific path and trim path depends on result. downside is extra runtime work.
* NormalizePath could be service, in that case it could be added as default_service() same as in 0.7

**Comment by jspeis** [comment]
@fafhrd91 definitely still interested. [Here's my initial attempt](https://github.com/Datawheel/actix-web/commit/738fcdaa721f090659029298d4706849ae994773) following the gist of option 1, by simply providing an alternative interface to the `resource` function that creates the `Resource` struct. Curious to hear your thoughts.

**Comment by fafhrd91** [comment]
Problem of your approach is that it requires custom resource and normalize path middleware. I thought about full resource impl, so it could register both paths but use same route

**Comment by jspeis** [comment]
@fafhrd91 agreed. If I understand correctly, the full resource impl would simply register both paths and that would be _instead_ of using `NormalizePath`? Would we then migrate the slash merging functionality there as well? 

If my understanding is correct, I think I should have a better handle, if not, an example of the user API usage should help me understand what you have in mind. Thanks again for your help

**Comment by fafhrd91** [comment]
Yes, your understanding is correct

**Comment by jspeis** [comment]
@fafhrd91 I was looking at trying to twice call the `register` function inside a new version of `resource.rs` in order to register both paths. But it seems like to do that I would need to clone the new "Resource" which currently doesn't derive Clone. Just wanted to confirm if this is where you had in mind to do the double registration and if there's a simple way to clone a Resource that I'm missing? Because `config.register_service(rdef, guards, self, None)` will move `self` and I have been thinking to simply make a secondary `rdef2` to be registered in that function.

**Comment by fafhrd91** [comment]
register_service requires S: NewService, `Rc<T: NewService>` implements NewService too, so you can do Rc::new(self)

**Comment by jspeis** [comment]
sorry for the delay...thank you - I was able to clone using ` Rc::new` the only other thing is there an easy way to clone a the `guards` vec as well?

**Comment by fafhrd91** [comment]
We need to implement Guard trait for Rc<Vec<Box<Guard>>

**Comment by jspeis** [comment]
@fafhrd91 would you be able to provide any pointers/quick examples if I can help with that?

**Comment by fafhrd91** [comment]
you just need to add `impl<T: Guard> Guard for Rc<Vec<T>>`

**Comment by jspeis** [comment]
In `guards.rs` added:
```
impl<T: Guard> Guard for Rc<Vec<T>> {
    fn check(&self, req: &RequestHead) -> bool {
        for p in self.iter() {
            if p.check(req) {
                return true;
            }
        }
        false
    }
}
```
Would anything need to change in `register_service` as well? Was going to try something like:

```
let guards_rc = Rc::new(guards);
config.register_service(rdef, guards_rc.clone(),  service_ref.clone(), None);
```

But then I get a compiler error of:

```
^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found struct `std::rc::Rc`
```

**Comment by fafhrd91** [comment]
```rust
let guards_rc = Rc::new(guards);
config.register_service(rdef, Some(Box::new(guards_rc.clone())),  service_ref.clone(), None);
```

**Comment by jspeis** [comment]
```
config.register_service(rdef, Some(Box::new(guards_rc.clone())), service_ref.clone(), None)
   ^^^^^^^^^^^^^^^^^^ expected struct `std::vec::Vec`, found struct `std::boxed::Box`
```

**Comment by fafhrd91** [comment]
`Some(vec![Box::new(guards_rc.clone())])`?

**Comment by jspeis** [comment]
Thanks @fafhrd91 for all your help and patience! I tried adding your previous suggestion and received:

```
config.register_service(rdef, Some(vec![Box::new(guards_rc.clone())]),  self, None);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `FnOnce<(&actix_http::message::RequestHead,)>` closure, found `std::rc::Rc<std::option::Option<std::vec::Vec<std::boxed::Box<dyn guard::Guard>>>>```

Is there another trait `impl` that is needed?

**Comment by jspeis** [comment]
So I seemed to be able to fix the compiler error by altering the guards.rs trait impl above with:


```rust
impl Guard for Rc<Option<Vec<Box<dyn Guard>>>> {
    fn check(&self, req: &RequestHead) -> bool {
        let rc_unwrap = Rc::try_unwrap(self.clone());
        if let Ok(Some(guards_vec)) = rc_unwrap {
            for p in guards_vec.iter() {
                if p.check(req) {
                    return true;
                }
            }
        }
        false
    }
}
```

Does this seem reasonable? In particular is there a better way to get at what's inside the Rc than `let rc_unwrap = Rc::try_unwrap(self.clone());`?

**Comment by fafhrd91** [comment]
I think this is reasonable. I’d implement only `Rc<Vec<_>>`, if guards are not specified then just use `None`

**Comment by jspeis** [comment]
Ah, yes that makes sense - thanks!

**Comment by itsgreggreg** [comment]
FWIW I adapted the NormalizePath middleware to ensure **no** end slash. 

https://gitlab.com/snippets/1884466

If you wanted to ensure that there is an end slash simply add one either after `trim_end_matches("/")` or before `slash_regex.replace_all(path, "/")`

This is not a general solution for a route default handler as now if you actually wanted to match on a route with an end slash you couldn't, but if all you want is a quick piece of middleware to normalize slashes in paths this will do the trick.

**Comment by jspeis** [comment]
@itsgreggreg yup had thought about that too, though currently trying to work on it from the route handler side.

@fafhrd91 [in my fork](https://github.com/jspeis/actix-web) I've added a `NormalizedResource` and have made progress to the point where now I can do something like this:

```
    #[test]
    fn test_basic_normalized_paths_example() {
        let mut app = init_service(
            App::new()
                .service(web::normalized_resource("/v1/something").to(|| HttpResponse::Ok())),
        );

        let req = TestRequest::with_uri("/v1/something").to_request();
        let res = call_service(&mut app, req);
        assert!(res.status().is_success());

        let req = TestRequest::with_uri("/v1/something/").to_request();
        let res = call_service(&mut app, req);
        assert!(res.status().is_success());
    }
```

The last thing I'm wondering is, without using an additional `wrap` fn call is it possible for me to intercept and modify the user's request URL? Or would that have to happen via `wrap`middleware?

**Comment by robjtede** [comment]
Anyone able to comment what are action items in this PR as of v3 beta if it is still relevant?

**Comment by jspeis** [comment]
I think had hoped that NormalizePath might let you create a route like `/hello` and accept either `/hello` or `/hello/` I suppose this can also be achieved via route matching (e.g. ```#[get(r#"/hello{tail:/?}"#)]```)  (as an aside: I also wonder if users would prefer to accept both distinct routes or have one version 301 redirect to the other?). 

When I tried to check v3 beta, seems like my usage of NormalizePath did not work for me? Not sure if I have something mixed up here, but wasn't able to access either `/hello` or `/hello/`.

```rust
use actix_web::{middleware,HttpServer, App};
use actix_web::{get, Responder};

#[get("/hello")]
async fn index() -> impl Responder {
    "Hello there!"
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new()
        .wrap(middleware::NormalizePath)
        .service(index))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

Using 
```toml
actix-web = {git = "https://github.com/actix/actix-web.git", rev="ad7c6d26332395e4693a68da8c15de799b259ca5"}
```

**Comment by robjtede** [comment]
> When I tried to check v3 beta, seems like my usage of NormalizePath did not work for me? Not sure if I have something mixed up here, but wasn't able to access either /hello or /hello/.

Yep, as it stands, it always normalizes to *with* a trailing slash so all route defs must end in a slash.

I'll pencil in some customization options for after v3 is stable. See #1612.

**Comment by jspeis** [comment]
Great, thanks!
