### ISSUE TITLE
Problem migrating tests to 1.0

### ISSUE THREAD

**Issue by antoine-de** [actix/actix-web#960]
# Problem migrating tests to 1.0
Hi,

I'm migrating a project from 0.7 to 1.0 and I'm quite happy with the migration, great work!

The only things I'm stumbling upon are migrating the integration tests.

I don't know if that's really idiomatic, but for our integration tests we used the same App creation as for the real server.

To do this, the app creation was in a [function](https://github.com/CanalTP/mimirsbrunn/blob/586ce2d32533ba728cb6f7471e185d9f156141a4/libs/bragi/src/server.rs#L15) returing `App<Context>`.

```rust
pub fn create_server(ctx: Context) -> App<Context> {
    App::with_state(ctx)...
}
```

then in main:
```rust
server::new(move || create_server(ctx.clone()))
    .bind(&args.bind)?
    .workers(args.nb_threads)
    .run()
```

and in tests:
```rust
actix_web::test::TestServer::with_factory(move || create_server(ctx))
```

Now that the App type depends on the middleware I don't know the new return type for the `create_server` function.

Following some advice from gitter, I used [App::configure](https://docs.rs/actix-web/1.0.3/actix_web/struct.App.html#method.configure):

```rust
pub fn configure_server(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/")
            .route(web::get().to(entry_point)),
    )...
}
```
then in main:

```rust
HttpServer::new(move || {
        App::new()
            .data(ctx.clone())
            .wrap(some_middleware)
            .wrap(other_middleware)
            .configure(configure_server)
            .default_service(web::resource("").route(web::get().to(default_404)))
    })
    .bind(&args.bind)?
    .workers(args.nb_threads)
    .run()
```

And in test:
```rust
let app = actix_web::App::new()
    .data(ctx.clone())
    .wrap(some_middleware)
    .wrap(other_middleware)
    .configure(configure_server)
    .default_service(web::resource("").route(web::get().to(default_404)));
```

With this I can share all the initialization of the routes, but I'm forced to duplicate the middleware initialization and the `default_service`.
But well the `wrap` middlewares system is nice, so I guess that's a tradeoff with the typesystem.

But I'm blocked at the next step.

Before I had [a helper](https://github.com/CanalTP/mimirsbrunn/blob/586ce2d32533ba728cb6f7471e185d9f156141a4/tests/tests.rs#L210-L212) around `actix_web::test::TestServer` to ease the use of the `TestServer` (bringing some asserts and parsing of the results).

actix v0.7:
```rust
pub struct BragiHandler {
    app: actix_web::test::TestServer,
}

impl BragiHandler {
    pub fn new(url: String) -> BragiHandler {
        let make_server = move || {
            bragi::server::create_server(bragi::Context::from(&bragi::Args {
                connection_string: url.clone(),
                ..Default::default()
            }))
        };

        BragiHandler {
            app: actix_web::test::TestServer::with_factory(make_server),
        }
    }

    pub fn raw_get(&mut self, q: &str) -> Result<ClientResponse, Error> {
        self.app
            .execute(
                self.app
                    .client(actix_web::http::Method::GET, q)
                    .finish()
                    .map_err(|e| format_err!("invalid query: {}", e))?
                    .send(),
            )
            .map_err(|e| format_err!("impossible to query bragi: {}", e))
    }
}
```

What seems to be the actix v1 equivalent is `actix_web::test::init_service(app)`, but I don't see a way to store the resulting service as the [resulting type](https://docs.rs/actix-web/1.0.3/actix_web/test/fn.init_service.html) is a bit complex

```rust
pub fn init_service<R, S, B, E>(
    app: R
) -> impl Service<Request = Request, Response = ServiceResponse<B>, Error = E> where
    R: IntoNewService<S>,
    S: NewService<Config = ServerConfig, Request = Request, Response = ServiceResponse<B>, Error = E>,
    S::InitError: Debug
```

I'm far from being a rust expert and I'm stuck to know the concrete type of the service

```rust
pub struct BragiHandler {
    app: <what type is this?>,
}
```

I tried boxing it but I fail the know all the sub types of `NewService` (especially the `Response`)

What is the right course of action for this ? Is it not idiomatic to want to make a wrapper around the test service ?

**Comment by fafhrd91** [comment]
With init_service you can avoid any io. TestServer exists it get moved to actix-http-test

**Comment by fafhrd91** [comment]
init_service is same as App::wrap, it is designed to be used in-place.

reopen if this ticket is still relevant
