### ISSUE TITLE
How to use SESSION (Storage: Redis) and grab them in another program (PHP) ?

### ISSUE THREAD

**Issue by KabDeveloper** [actix/actix-web#964]
Hi,

I want to switch from PHP to Rust, but i don't understand well the concept of SESSION used on ACTIX.

As storage, I want use REDIS ... Since my PHP website is really BIG, First I switch one service to Rust but with the ability to share SESSION between PHP + Rust.

Is there a way to do this please ?

Thank you

**Comment by fafhrd91** [comment]
simplest would be to write custom session middleware. which could read php session id, and then read redis db

**Comment by KabDeveloper** [comment]
@fafhrd91 Any idea on how to start that please ? Or recommandation ? An example already done for another task etc.

Thank you

**Comment by fafhrd91** [comment]
first check middleware example. then check actix-session

**Comment by Dowwie** [comment]
@bcashier you are looking for [this library](https://github.com/actix/actix-redis)

both your PHP server and actix-web server would connect to the same cache

**Comment by KabDeveloper** [comment]
@Dowwie Thank you for your contribution.

I already checked that library, but I don't know if session used by PHP and Actix are using same format and structure ? If yes, this will be really awesome !

Because in order to read PHP sessions from another subdomain, I have to use this code:

```
session_name('RustAndPHP'); // I don't have any idea to name the sessions in Rust

session_set_cookie_params(0,"/",".mydomainname.com",FALSE,FALSE);
setcookie(session_name(), session_id(),0,"/","mydomainname.com");
session_start();
```

The session name is required.

Is there a way to specify the session name using that library ?

**Comment by fafhrd91** [comment]
@bcashier you have to write custom session impl which understands php format
