### ISSUE TITLE
How to create multipart response

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#965]
There are examples how to handle multipart requests (ex file uploads),
but I could not find a solution for multipart response. I'm trying to stream live content from the server (written using actix_web) to a browser client.
I can set the header to start the multipart streaming (`...header("Content-type", "multipart/x-mixed-replace; boundary=--frameboundary")`, and set a body through the `streaming` function, but how to set the content-type for each "frame" ?

I'm new to this type of content stream so maybe my method is completly wrong. 
Don't bother with the "camera" words, I wanted to make it work using plane text (before using binary content) following this description: https://docstore.mik.ua/orelly/web2/xhtml/ch13_03.htm)

This is my current (non-working) solution. The Content-type is interpreted as part of the body, which is not a big supprise as the stream is for the body.

```
struct LiveStream {    
    state: u32,
}

impl Stream for LiveStream {
    type Item = web::Bytes;
    type Error = ActixError;

    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
        match self.state {
            0 => {
                log::info!("hello 0");
                let mut mem = web::Bytes::from(&b"--frameboundary\n"[..]);
                self.state += 1;
                Ok(Async::Ready(Some(mem)))
            }
            1 => {
                log::info!("hello 1");
                let mut mem = web::Bytes::from(&b"Content-type:text/html\n<html><body>HI 0</body></html>\n--frameboundary\n"[..]);
                self.state += 1;
                Ok(Async::Ready(Some(mem)))
            }
            2 => {
                log::info!("hello 2");
                let mut mem = web::Bytes::from(&b"Content-type:text/html\n<html><body>HI 1</body></html>\n--frameboundary\n"[..]);
                self.state += 1;
                Ok(Async::Ready(Some(mem)))
            }
            _ => {
                log::info!("bye");
                 Ok(Async::Ready(None))        
            }
        }
    }
}

fn live_stream(_state: web::Data<AppData>) -> HttpResponse {
    log::info!("Start camera stream");
    HttpResponse::Ok()
    .header("Content-type", "multipart/x-mixed-replace; boundary=--frameboundary")
    .streaming(LiveStream{state:0})
}

pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(web::resource("/livestream").route(web::get().to(live_stream)));
}

```

**Comment by ghost** [comment]
A few \r\n was missing after the content-type.
And it seems as current browsers don't support this type of update dispite of the doc/spec.
(Wireshark understands the protocol and can parse the content and reports no error)

Though I still have an open question, when does the stream get flushed? Does it send all the streamed Bytes immediatelly or there is some buffering (ex nagling at driver level)?

**Comment by fafhrd91** [comment]
Socket get flushed in two states:

1. When Body stream returns NotReady
2. Body stream returned enough data to fill internal buffer
