### ISSUE TITLE
Example for client is broken

### ISSUE THREAD

**Issue by 0xpr03** [actix/actix-web#966]
The docs example in [client](https://docs.rs/actix-web/1.0.3/actix_web/client/index.html) is currently broken due to `futures` dependency as noted by other people.

**Comment by fafhrd91** [comment]
all api doc example get compiled and executed during test 

https://github.com/actix/actix-web/blob/master/awc/src/lib.rs#L3

**Comment by 0xpr03** [comment]
@fafhrd91 you're missing the futures crate here.
Try creating a new project with just the visible code, it won't compile.

**Comment by dkotrada** [comment]
@fafhrd91 please consider to reopen this issue. It is not about tests. It is about example in documentation.
