### ISSUE TITLE
HttpRequest::connection_info incurs a borrow of extensions (and can easily panic)

### ISSUE THREAD

**Issue by pjenvey** [actix/actix-web#967]
As of 1.0, ConnectionInfo caches itself onto request.extensions. So now holding onto a reference while attempting to mutate the extensions triggers a panic: `panicked at 'already borrowed: BorrowMutError'`.

This is surprising behavior and not easy to diagnose, it really shouldn't cause panics.

**Comment by pjenvey** [comment]
A reproducing test:

https://github.com/actix/actix-web/compare/master...pjenvey:ci-extensions-borrow

**Comment by fafhrd91** [comment]
This can not be fixed without breaking change. You can submit Pr for api doc with panic description

**Comment by pjenvey** [comment]
Couldn't there be a separate place (say internal to actix-web) to cache ConnectionInfo in vs request extensions?
