### ISSUE TITLE
Uncomplete Example

### ISSUE THREAD

**Issue by dkotrada** [actix/actix-web#969]
There is a difference in [here](https://github.com/actix/actix-web/blob/master/awc/src/lib.rs#L3)

```rust
//! ```rust
//! # use futures::future::{Future, lazy};
//! use actix_rt::System;
//! use awc::Client;
```

and [here](https://docs.rs/actix-web/1.0.3/actix_web/client/index.html)

```rust
use actix_rt::System;
use actix_web::client::Client;
```
Missing part is: `use futures::future::{Future, lazy};`

Maybe we need to remove `#` before `use futures::future::{Future, lazy};` [here](https://github.com/actix/actix-web/blob/master/awc/src/lib.rs#L3)

**Comment by kathampy** [comment]
Is it possible to use the client asynchronously if actix-web is already running a server? Must it create a new runtime thread pool or can it use the existing workers from the server? The documentation does not make this clear for beginners.

**Comment by fafhrd91** [comment]
updated
