### ISSUE TITLE
Pass variables from Rust code to Static Pages (HTML)

### ISSUE THREAD

**Issue by KabDeveloper** [actix/actix-web#970]
Hi,

I know how to show the static pages for each URL, but how to pass variables from Rust code to the HTML page for example ?

Is there a way to pass Arrays, Links etc ?

Thank you

**Comment by sonfangos** [comment]
I think that you might be looking for something like [Tera](https://crates.io/crates/tera), with which you can pass data in a context, or like [Askama](https://crates.io/crates/askama), with which you can pass data in a struct. There are examples for both in [actix/examples](https://github.com/actix/examples). The [DisplayAs](https://crates.io/crates/display-as) crate also enables you to send data in a struct.

**Comment by fafhrd91** [comment]
Use template engines

**Comment by KabDeveloper** [comment]
Thanks all for your answers.
