### ISSUE TITLE
actix-web async client bug

### ISSUE THREAD

**Issue by darkdarkfruit** [actix/actix-web#974]
## What's the problem?
> bench the async-client, then found the memory surges and never goes down.
> memory goes from 0.3M to 904M
## What tool to bench
> wrk --latency -d300 -c1000 -t100 'http://localhost:8081/proxy'
## What's the env
> * Linux bluesky 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
> * actix-web = {version = "1.0.3", features=["ssl"]}

## What the code below to do is just: (use actix-web's async client)
* grab the content of https://github.com
* return the future to actix-web

```rust
use log::*;

use actix_web::{
    self, middleware, web, App, Error, HttpResponse, HttpServer,
};
use futures::Future;


fn proxy() -> impl Future<Item=HttpResponse, Error=Error> {
    let url = "https://github.com/";
    actix_web::client::Client::default()
        .get(url.to_string())
        .timeout(std::time::Duration::from_secs(2))
        .send()
        .map_err(move |e| {
            error!("error while getting url: {:?}. e: {}", url, e);
            Error::from(e)
        })
        .and_then(|mut rsp| {
            rsp.body().limit(1024 * 1024 * 2).map_err(|e| {
                error!("error while getting payload. e: {}", e);
                Error::from(e)
            })
        })
        .and_then(|body| HttpResponse::Ok().content_type("text/html").body(body))
        .map_err(|e| {
            error!("error while response with body, e: {}", e);
            e
        })
}

pub fn main() {
//    openssl_probe::init_ssl_cert_env_vars();

    let _ = flexi_logger::Logger::with_str("info, actix_web=debug, foc=trace")
        .format(flexi_logger::detailed_format)
        .start()
        .unwrap();

    let web_addr = "127.0.0.1:8081";
    info!("Starting foc actix http server at {}", &web_addr);

    HttpServer::new(|| {
        App::new()
            .wrap(middleware::Logger::default())
            .service(web::resource("/proxy").route(web::get().to_async(proxy)))
    })
        .keep_alive(30)
        .bind(web_addr)
        .unwrap()
        .run()
        .unwrap();
}
```

**Comment by fafhrd91** [comment]
this seems like an artifact of alloocator. i tried to run this app in osx instruments, it does not report leaks, or at least memory usage goes down to normal level after wrk completes. also i tried to run test example with jemalloc, memory usage goes down after wrk exists.

also i noticed you create `Client` object for each request, which is very inefficient. if client object is shared across all request then memory usage drops 10x
