### ISSUE TITLE
Pass parameters to a function inside route (route(web::get().to(testit(paramters))))

### ISSUE THREAD

**Issue by KabDeveloper** [actix/actix-web#976]
Hi,

Is there a way to pass parameters to a function inside route for example:

```
            .service(web::resource("/user/{name}").route(web::get().to(with_param)))
            .default_service(
                // 404 for GET request
                web::resource("")
                    .route(web::get().to(testit("ok")))
                    // all requests that are not `GET`
                    .route(
                        web::route()
                            .guard(guard::Not(guard::Get()))
                            .to(|| HttpResponse::MethodNotAllowed()),
                    ),
            )
```

And the function example!

```
fn testit(param: String) -> String {
    println!("{}", param);
    param
}
```

Thank you

**Comment by max-frai** [comment]
Probably no. What's use case? What problem do you want to solve?
If you want to split route based on some argument, just split code into function and write two routes.

**Comment by KabDeveloper** [comment]
@max-frai 
I want to pass some arguments to the functions depend on the requests of users.

So I can get and serve the right datas.

I have a function that call models connected to my database and serve specific results depend on parameters requested, and then callback with JSON format readable using Javascript from the FrontEnd.

I tried a test like this (Notice that I need to declare a TYPE for this function but it return an error when doing that):

```
fn testit() {
    dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("set DATABASE_URL");
    let conn = MysqlConnection::establish(&database_url).unwrap();
    let types = 1;
    let period = 2;
    let first_date = 0;

    let result: Vec<chart_models::MultiArr> = bucks_models::bucks::bucks_infos(types, period, first_date, &conn);
    println!("{:#?}", result);
}
```
Router:

```
.default_service(
	web::resource("")
		.route(web::get().to(testit)) // <- Here is the function
		.route(
			web::route()
				.guard(guard::Not(guard::Get()))
				.to(|| HttpResponse::MethodNotAllowed()),
		),
)
```

But the server shutdown  (When accessing to: 127.0.0.1:8080) with this error message:

```
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` va
lue: Empty', src\libcore\result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Panic in Arbiter thread, shutting down system.
```

**Comment by sonfangos** [comment]
Not sure, but I think that [Path](https://docs.rs/actix-web/1.0.3/actix_web/web/struct.Path.html) ("Extract typed information from the request's path") might be what you are looking for here.

**Comment by HiruNya** [comment]
As the people above have said, you should probably use the path extractor but I'm going to guess that's what you did with the `with_param` function.
To do the thing that you originally wanted, use a closure instead.
```rust
use actix_web::{guard, web, App, HttpResponse, HttpServer};

fn main() {
    HttpServer::new(|| {
        App::new()
            // .service(web::resource("/user/{name}").route(web::get().to(with_param)))    // I don't have the `with_param` function
            .default_service(
                // 404 for GET request
                web::resource("")
                    .route(web::get().to(|| testit("ok".to_string())))  // Changed to a closure
                    // all requests that are not `GET`
                    .route(
                        web::route()
                            .guard(guard::Not(guard::Get()))
                            .to(|| HttpResponse::MethodNotAllowed()),
                    ),
            )
    })
    .bind("127.0.0.1:8080")
    .expect("Failed to bind to the server.")
    .run()
    .expect("Failed to run the server.")
}

fn testit(param: String) -> String {
    println!("{}", param);
    param
}
```

**Comment by KabDeveloper** [comment]
@HiruNya Awesome, It's what I was looking for :)

**Comment by zhangnew** [comment]
What if `testit()` is a post request  ? such as :
```rust
fn testit(item: web::Json<MyObj>, param: String) -> HttpResponse { 
    ...
}
```

**Comment by HiruNya** [comment]
@zhangnew Make the closure take a `web::Json<MyObj>` struct.
e.g.
```rust
web::post().to(|item: web::Json<MyObj>| testit(item, "ok".to_string()))
```

**Comment by zhangnew** [comment]
@HiruNya thank you, that's worked.

**Comment by literadix** [comment]
I tried to insert a string defined outside this function:

```
let hrx_ok: &str = "hello";
...
web::post().to(|body: web::Bytes, req: HttpRequest| debug_post(req, body, hrx_ok)),
```
Then I get an error:

```
error[E0597]: `hrx_ok` does not live long enough
   --> hrx_proxy\src\main.rs:89:91
    |
83  |     match HttpServer::new(|| {
    |                           -- value captured here
...
89  |                 web::post().to(|body: web::Bytes, req: HttpRequest| debug_post(req, body, hrx_ok)),
    |                 --------------------------------------------------------------------------^^^^^^--
    |                 |                                                                         |
    |                 |                                                                         borrowed value does not live long enough
    |                 argument requires that `hrx_ok` is borrowed for `'static`
...
101 | }
    | - `hrx_ok` dropped here while still borrowed


```
How to fix this?

**Comment by aliemjay** [comment]
> How to fix this?

if `hrx_ok` is `'static`, then you can apply `move` to the closures provided to `App::new` and  `Route::to` methods.

However, it is recommended to use `app_data` for configurable parameters you wat to provide to service handlers.

```rust
struct MyConfig(String);
let config = web::Data::new(MyConfig(hrx_ok.to_string())); // construct outside  HttpServer::new closure

HttpServer::new(move || {  // <- "move" config here!
    App::new()
    .app_data(config.clone())
    ...
    web::post().to(debug_post),
    ...
});

async fn debug_post(body: web::Bytes, req: HttpRequest, config: web::Data<MyConfig>) { }

```

**Comment by literadix** [comment]
Thank you very much. This solved my problem.

**Comment by suyashjawale** [comment]
```
use actix_web::{web, App, HttpResponse, HttpServer, Responder};

async fn manual_hello(data: web::Data<String>) -> impl Responder {
    HttpResponse::Ok().body(format!("Hey there! {}",data.to_string()))
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let greeting = "hello";
    let data = web::Data::new(greeting.to_string());
    HttpServer::new(move || {
        App::new()
            .app_data(data.clone())
            .route("/hey", web::get().to(manual_hello))
    })
    .bind(("127.0.0.1", 8081))?
    .run()
    .await
}

```

**Comment by halokid** [comment]
> As the people above have said, you should probably use the path extractor but I'm going to guess that's what you did with the `with_param` function. To do the thing that you originally wanted, use a closure instead.
> 
> ```rust
> use actix_web::{guard, web, App, HttpResponse, HttpServer};
> 
> fn main() {
>     HttpServer::new(|| {
>         App::new()
>             // .service(web::resource("/user/{name}").route(web::get().to(with_param)))    // I don't have the `with_param` function
>             .default_service(
>                 // 404 for GET request
>                 web::resource("")
>                     .route(web::get().to(|| testit("ok".to_string())))  // Changed to a closure
>                     // all requests that are not `GET`
>                     .route(
>                         web::route()
>                             .guard(guard::Not(guard::Get()))
>                             .to(|| HttpResponse::MethodNotAllowed()),
>                     ),
>             )
>     })
>     .bind("127.0.0.1:8080")
>     .expect("Failed to bind to the server.")
>     .run()
>     .expect("Failed to run the server.")
> }
> 
> fn testit(param: String) -> String {
>     println!("{}", param);
>     param
> }
> ```

this great!  thanks 👍
