### ISSUE TITLE
Unable to reproduce the explicit extractor example from the docs

### ISSUE THREAD

**Issue by ZapAnton** [actix/actix-web#977]
I am trying to follow the [extractor documentation](https://actix.rs/docs/extractors/), specifically the `Option 2 - accessed by calling extract() on the Extractor` example.

For some reason the `web::Json::<MyInfo>::extract(&req)` line does not accept the JSON I am testing it on (with the `Json deserialize error: EOF while parsing a value at line 1` error), although the JSON is successfully parsed, if the extractor is used as a function argument. Am I missing some additional steps?

`actix-web` version: `1.0.3`

JSON request example: `curl -X POST -H "Content-Type: application/json" localhost:8073 -d '{"message":"xyz"}'`

The source code:

```rust
use actix_web::{web, App, FromRequest, HttpRequest, HttpResponse, HttpServer, Result};                                                                                                                                                                                                  
use futures::future::Future;    
use serde::Deserialize;    
      
  #[derive(Deserialize)]    
  struct Item {    
      message: String,    
  }    

 fn index(req: HttpRequest) -> Result<HttpResponse> {    
     let item = web::Json::<Item>::extract(&req).wait()?;    
     println!(    
         "Got message: {}  From: {}",    
         item.message,    
         if let Some(client_ip) = req.connection_info().remote() {    
             client_ip    
         } else {    
             "Unknown"    
         }    
     );    
     Ok(HttpResponse::Ok().into())    
  }    

fn main() {
      HttpServer::new(|| App::new().route("/", web::post().to(index)))                                                                  
          .bind("0.0.0.0:8073")                                                                                                                        
          .unwrap()                                                                                                                                    
          .run()                                                                                                                                       
          .unwrap();                                                                                                                                   
  }    
```

**Comment by fafhrd91** [comment]
json extractor requires payload, you can not use .extract() method. specifically for json you can just use it as argument.

```rust
fn index(req: HttpRequest, item: web::Json<Item>) -> Result<HttpResponse> { 
   ...
}
```

i will change to docs

**Comment by mankinskin** [comment]
@fafhrd91 How can we explicitly extract a `Json<T>` from a `HttpRequest` if `extract()` does not work? Why can we not extract a `Payload` from a `HttpRequest` containing raw JSON?

**Comment by jesskfullwood** [comment]
If you want deserialize JSON explicitly inside the handler for some reason, you can just use the `String` (or `Option<String>`) extractor and deserialize manually with `serde_json`.

**Comment by mankinskin** [comment]
@jesskfullwood Thanks, that works.
