### ISSUE TITLE
Register `Data` without wrapping

### ISSUE THREAD

**Issue by 0ndorio** [actix/actix-web#978]
It seems like the `App` doesn't provide a way to register a `Data` element without wrapping it's content with an additional layer of `Arc`. This is true for `App::data()`, `App::register_data()` and `App::data_factory()`. The documentation refers to `web::Data::new` for this use case but this is just a plain reexport and will also wrap.

@fafhrd91 Mentioned in gitter that it should be possible to come up with a custom `Data` implementation instead but this also doesn't work as the only way to setup `Data` is via `Data::new` and the `DataFactory` trait is only public inside the crate itself.

--

So the open questions are: 

 - Is one of both ways expected to work and if so, which one is the one that need a fix? (I would be happy to provide a merge request fixing it.)
 - Or am I expected to change my internal data type to avoid the second layer?

**Comment by jesskfullwood** [comment]
I have hit this problem before.Suppose one has a type that does it's own synchronization
```
struct Counter(Arc<AtomicU32>)
```
Ideally we use this with a factory function like
```
let counter = Counter::new();
App::new().data_factory(move || counter.clone());
```
There is no way to do this without adding a second `Arc` - this is clear from the definition of `Data`:
```
pub struct Data<T>(Arc<T>);
```
We would have to make a breaking change to the definition of `Data` to make this work.

**Comment by jesskfullwood** [comment]
I think the way we solve this is with a new extractor, something like
```
#[derive(Clone)]
struct SyncData<T: Clone + Send + Sync>(T)
```
With the explanation that `T` will be cloned each time the extractor is used.

**Comment by fafhrd91** [comment]
Added `App::app_data()` and `HttpRequest::app_data()` methods.

`Data<T>` extractor could be implemented with this methods
