### ISSUE TITLE
Problem in returned headers in lowercase form

### ISSUE THREAD

**Issue by ffimnsr** [actix/actix-web#981]
**Tested Version: 1.0.3**

Currently, I've been experimenting on actix-web, juniper and vuejs front-end with tera template system. The behavior of the raw headers all returned in lower case form cause problems on some rest api client ("insomnia") and firefox quantum. Should suppose return header key be in first letter uppercase and subsequent characters lower case.

**Current returned headers:**

```
...
content-disposition: inline
content-type: application/json; charset=utf-8
...
```

**Expected returned headers:**

```
...
Content-Disposition: inline
Content-Type: application/json; charset=utf-8
...
```

**Sample code that returns lower case header keys:**

```
Ok(HttpResponse::Ok()
    .header(header::CONTENT_DISPOSITION, header::ContentDisposition {
        disposition: header::DispositionType::Inline,
        parameters: vec![
            header::DispositionParam::Filename(file_name.to_owned())
        ]
    })
    .content_type(content_type)
    .content_length(resp.len() as u64)
    .body(resp))
```

Also when I try to set up new values using `header` fn, the result raw headers still in lower case form.

**Comment by fafhrd91** [comment]
http create uses lower case headers repr. There is camel case feature but it work for client only. You can extend it to server impl as well.

**Comment by ffimnsr** [comment]
Yep just checked the http crate its all in lower case form. As per your advice I'll thinker and look in http client. I'll try to come up with an implementation, as serving static files doesn't play really well with lower case form header keys.

**Comment by cetra3** [comment]
FYI HTTP Headers are case insensitive as per [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

I've not had issues with insomnia myself, what function are you using that isn't working?

**Comment by ffimnsr** [comment]
@cetra3 yes I've read that they're suppose to be case insensitive but some developers usually write `headers["Content-Type"]` specially when crawling. As sample you can check and try loading some javascript files (e.g. Vue/React SPA) on some browser (e.g. Firefox, Webkit) which they don't load even if you write "content-disposition: inline" with proper mime-type (guess this is a bug on browser haven't tested fully). But in that case most of the static file server use camel case when serving files. For functions you could try returning some static javascript files it wouldn't serve properly nor rendered
.

**Comment by cetra3** [comment]
I've got no issues with a React app running & lowercase headers.  Can you provide a repo where you can demonstrate this behaviour?

**Comment by fafhrd91** [comment]
i dont want to add camel case headers support. it would increase already complicated http render code.
