### ISSUE TITLE
Consider making Query payload public

### ISSUE THREAD

**Issue by jesskfullwood** [actix/actix-web#987]
At the moment it is possible to destructure the `web::Json` and `web::Path` types inside the handler signature, which is very useful e.g. instead of
```
fn handler(wrapped: Json<MyData>) {
    let my_data = wrapped.into_inner();
    // ...
}
```
we do
```
fn handler(Json(my_data): Json<MyData>) {
    // ...
}
```
However this is not possible with `Query` as the contents are not public. I understand the logic, it stops users from constructing a `Query` with invalid contents. However, this is already possible with `Json` (no guarantee that the contents will be deserializable) and it is not possible to return a `Query` as a `Responder` anyway so I don't think there is really an issue.

**Comment by fafhrd91** [comment]
Reasonable. Would you provide PR?
