### ISSUE TITLE
documentation: rtype parameter count is invalid

### ISSUE THREAD

**Issue by flip111** [actix/actix-web#99]
i'm trying the code from here https://actix.github.io/actix-web/guide/qs_14.html

```rust
#[derive(Message)]
#[rtype(User, Error)]
struct CreateUser {
    name: String,
}
```

getting this error
```
error: proc-macro derive panicked
  --> src/main.rs:20:10
   |
20 | #[derive(Message)]
   |          ^^^^^^^
   |
   = help: message: #[rtype(type)] takes 1 parameters, given 2
```

https://github.com/actix/actix-derive/commit/e927c21f5415e084d8ca4f6d2c0a4debf9a96edf#diff-f619358e9c7b971d9e11c0b99f8a30a3

**Comment by fafhrd91** [comment]
oh, this is old code. i will update it.

if you need diesel example, check this https://github.com/actix/actix-web/tree/master/examples/diesel

https://github.com/actix/actix-web/blob/master/examples/diesel/src/db.rs#L16

**Comment by fafhrd91** [comment]
guide is updated
