### ISSUE TITLE
Bug in redis-session example (Cookie saved to redis is not complete)

### ISSUE THREAD

**Issue by KabDeveloper** [actix/actix-web#990]
Hi,

I noticied today that the cookie received in the header (from browser), is not completely saved into Redis !

Here what is received from the browser header:

```
HttpRequest HTTP/1.1 GET:/
  headers:
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    "cache-control": "max-age=0"
    "accept-encoding": "gzip, deflate"
    "cookie": "actix-session=ndI6gXSiTsNyVO8p67j4O8AD4aW5x40ncaHJeArAl4c=ujxrNZsUWFUmWeqQrcUvBXozbrc0gSfy"
    "host": "localhost"
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
    "connection": "keep-alive"
    "upgrade-insecure-requests": "1"
    "accept-language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
```

And in Redis side when I show all the keys:
```
C:\redis>redis-cli keys *
1) "ujxrNZsUWFUmWeqQrcUvBXozbrc0gSfy"
```
Only part after "=" is saved to Redis as key.

How to make it saving all the cookie values into Redis please and not only that part ?

Is it a bug ?

Thank you in advance.

**Comment by fafhrd91** [comment]
@Dowwie could you check?

**Comment by Dowwie** [comment]
@fafhrd91 @bcashier  that's a signed cookie.. only a portion of the cookie value is the actual session key

you key redis on the session key

**Comment by fafhrd91** [comment]
So this is not a bug?

**Comment by Dowwie** [comment]
@fafhrd91   No, not a bug-- a feature.  This is as intended and designed.    The uniquely identifying element is the session key.  The signature is used to confirm that the client did not tamper with the cookie.  In other words, the signature is cookie-specific info that has no relevance in redis cache entries.  

If we want to make this configurable, externalize config for key generation that would allow users to define cache keys however they please (a Config type, maybe).  Here's a working prototype of a type-safe KeyGen:   https://gist.github.com/Dowwie/1429538d872e928e360d687b5fee7a31

**Comment by fafhrd91** [comment]
Thanks for info

**Comment by KabDeveloper** [comment]
@Dowwie PHP is using the full value of cookie in order to store details inside Redis, it not using same process as yours.

Is there a way to make it using the full value please ? (It's a necessity to be able to interact with PHP applications like NodeJS doing).

**What I've tried:**

Made some changes on:
https://github.com/actix/actix-redis/blob/master/src/session.rs

After line 221, I've added:

    let cookie_value = cookie.value();

And modified line 225 from:

    let value = cookie.value().to_owned();

to:

    let value = cookie_value.to_owned();


This let me save randomly details (Sometimes with full value, sometime in the end part only), But when selecting values it do this from the incomplete part.

Is it possible to make it working with the full values instead of only part of it ?

Thank you all for your answers.
