### ISSUE TITLE
need a  http client. just like  hyper

### ISSUE THREAD

**Issue by zhuxiujia** [actix/actix-web#999]
need a  http client. just like  hyper

**Comment by jesskfullwood** [comment]
There is indeed an Actix Http client, in `awc` folder. See also [docs](https://docs.rs/awc/0.2.2/awc/).

**Comment by zhuxiujia** [comment]
> There is indeed an Actix Http client, in `awc` folder. See also [docs](https://docs.rs/awc/0.2.2/awc/).

awc , it's a  stable http  module?Or in development？

**Comment by zhuxiujia** [comment]
> There is indeed an Actix Http client, in `awc` folder. See also [docs](https://docs.rs/awc/0.2.2/awc/).

awc is not easy to use.
reqwest is also easy to use:
```
let body = reqwest::get("https://www.google.com").unwrap().text().unwrap();
println!("body = {:?}", body);
```
